### ISSUE TITLE
Installation progress bars are inaccurate

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#1007]
Hacky fix implemented in https://github.com/ModOrganizer2/modorganizer/pull/1006

> **The symptom:** Flashing progress dialog when installing certain mods. The test case for this fix was Collision Meshes FNV (https://www.nexusmods.com/newvegas/mods/59149/).
> 
> **The initial cause:** Files were still being extracted after the progress dialog reached 100%, causing the progress dialog to be opened and instantly closed for every progress update.
> 
> **The hacky fix:** Prevent the progress dialog from automatically closing and automatically resetting. This is not ideal as the progress quickly reaches 100% and then stays there.
> 
> **The root-ish cause:** Something with 7-zip or the integration of 7-zip has changed/broken. In the test case, the 0% to 100% progress is all about \meshes\vehicles\wreckage. Why? No clue.

**Comment by Al12rs** [comment]
This should be fixed by this: https://github.com/ModOrganizer2/modorganizer-archive/pull/16
