### ISSUE TITLE
Ability to access important Information of Mod and Mark Mods with Info

### ISSUE THREAD

**Issue by TimidScript** [ModOrganizer2/modorganizer#1010]
**Is your feature request related to a problem? Please describe.**
When running the game there are mods that contain lots of detail and you need to go back and read the online information, text file, or look at the image.

If Skyrim is running you need to unlock Mod Organizer to be able to access the listing to get to the readme files. 

Information can include guide, location detail etc.

**Describe the solution you'd like**
Ability to flag mods with important information with a info icon flag (ℹ️) .
Auto flag mods with images with an image icon.

Ability to access the readme/images/nexus description without unlocking MO when game is running.

**Comment by selsie** [comment]
Unlocking MO is not harmful.
You can always make a Note, which will show a little icon in the flags. The note can contain any HTML (and is basically HTML saved in the meta.ini)

**Comment by Al12rs** [comment]
Also you can actually read the nexus description from Mo2 itself in the Nexus tab. Closing as the Notes tab and icon should solve this.
