### ISSUE TITLE
Expanding drag and drop onto modlist capabilities

### ISSUE THREAD

**Issue by Al12rs** [ModOrganizer2/modorganizer#1011]
Currently to install an archive you need to drag and drop it to the downloads tab to copy it there and then install it. If the user doesn't want the copy they have to use the Install mod button which is less convenient than d&d.

Explore if it could be possible to make Mo2 install an archive if dropped on empty modlist space or between mods, without having to copy it.

Also explore the possibility to drag a folder onto empty space to make a mod out of that folder, but this could be a little trickier since it could be cause of unwanted behavior when trying to move folders inside a mod. 
So only do this if the Icon and text of the drop can be changed into something that clearly differentiates between copying into the mod and creating a new one.

**Comment by Al12rs** [comment]
- [ ] Drag Download from Downloads Tab onto modlist to install it to that priority.
- [ ] Drag archive (zip) onto modlist to install it at that prority.
- [ ] Drag folder onto modlist to copy it as a new mod folder _This one is out for debate as it could be problematic with dragging files from overwrite_

**Comment by Holt59** [comment]
Done in #1338
