### ISSUE TITLE
Safe Directory within Mod

### ISSUE THREAD

**Issue by TimidScript** [ModOrganizer2/modorganizer#1015]
**Is your feature request related to a problem? Please describe.**
You create store text/image content within the mods directory and when you update the directory the content gets removed. Allow the marking of directories within mods, so as not to get removed after update.

**Describe the solution you'd like**
Maybe directory with specific name or in closed bracket (example "[Guide]").

**Describe alternatives you've considered**
Storing all related information outside Mod Organiser.

**Comment by selsie** [comment]
I second this. If I install an update to a mod and forget to "merge", I would prefer to be asked if I want to delete user created files (or mod created files, like settings etc).

**Comment by Al12rs** [comment]
I reject this, overwriting and merging are clear cut operations and I don't want to introduce loopholes and special cases. Store the information in a secondary mod or in the notes if it's text.
