### ISSUE TITLE
Opening the Information Tab for a mod on Second monitor Softlocks MO2

### ISSUE THREAD

**Issue by Ethryan** [ModOrganizer2/modorganizer#1023]
## The problem:
When you try and open the **Information...** on a non-main monitor with a different resolution softlocks MO2 without an error report.

## To Reproduce:

1. Have MO2 open on second monitor
2. Click on '**Information...**' for a mod
3. Wait for half an eternity.
4. Use the 'Task Manager' and force MO2 closed.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.2.1
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details:
![image](https://user-images.githubusercontent.com/3237986/76220665-2bb15300-6218-11ea-8546-ba9a37040821.png)

## Link to Mod Organizer logs:
Nothing seen in the log files, they just stop.

**Comment by Al12rs** [comment]
If opening the mod information dialog or some other Mo2 dialog/window does not show said window, it's probably being shown outside of the screen. 

You can try bringing it back on screen by pressing the following sequence of keys: 
ALT + SPACE,  M, then Right Arrow . After that moving the mouse should bring the window in view.

**Comment by isanae** [comment]
> Nothing seen in the log files, they just stop

Please send them anyway. Set your log level to Debug, restart MO, reproduce the problem, close MO, attach `mo_interface.log` here. Ten bucks it's Nahimic.

**Comment by Ethryan** [comment]
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/4308033/mo_interface.log)
Here

**Comment by isanae** [comment]
> Nothing seen in the log files, they just stop

There's a warning in your log that literally says "Nahimic is loaded. This program is known to cause issues with Mod Organizer, such as freezing or blank windows. Consider uninstalling it." It should also be visible in the log window at the bottom.

You have a program called Sonic Radar, Sonic Suite or something similar. It's incompatible with many programs, including MO.

**Comment by Ethryan** [comment]
Thanks for the help, i found Sonic Radar 3, ... But i never installed it voluntairly, must have come with windows.
