### ISSUE TITLE
Won't save update. Says password is wrong but isn't. 

### ISSUE THREAD

**Issue by Darklustre** [ModOrganizer2/modorganizer#1025]
I have to update MO2 every single time I start it up. I go through the process and it installs correctly because I can then get mods from Nexus. But the next time I open the program, I have to go through it all again. This has happened 5 dozen times. 

It says my log-in failed so I've reset my Nexus password about 4-5 times. Still won't work. 

I have asked for help more than once and gotten no response. Is there ANYONE still working here that will take an interest in helping me fix this? This clearly shouldn't happen.

**Comment by LostDragonist** [comment]
... Where have you been asking for help?

The most likely explanation is that you're installing the update to MO to one location and then using an old shortcut/location to launch the old version of MO.  If you have a version old enough to ask for a username and password (which don't work at all anymore) then the updater doesn't even try to find where you installed MO.

**Comment by Darklustre** [comment]
Thank you for responding! <3

I've posted in several places. I'm using MO2 and I'm seeing the update in the program itself. So I click on the button and go through the installation process. It says it was updated successfully. And it seems to be because then I can finally get the downloads from Nexus to come through. But it still won't recognize my sign-in and constantly says it failed. And when I open MO2 up again, it again won't get downloads from Nexus and the icon says there's an update available. 

I have to do this everywhere.

**Comment by LostDragonist** [comment]
Again, the most likely explanation is that you keep installing the update somewhere else then launching the old version.  You need to tell the updater to install to the location you have MO installed in.  You need to do this manually.

**Comment by Darklustre** [comment]
Ok I think I get what you're saying. How do I do that from the program? Also, why will it not recognize my log-in no matter how many times I update my password? Thanks.

**Comment by LostDragonist** [comment]
![image](https://user-images.githubusercontent.com/7862539/76651741-5e15c580-6522-11ea-91ea-4ec99747d9aa.png)
You do it right here.

MO does not recognize the username and password because it does not work.  They shut down the servers.  It will never work.

**Comment by Al12rs** [comment]
To clarify, the old version of Mo2 was using the old Nexus API, for which they shut down the servers so we were forced to update. Once you have installed the update correctly over your Mo2 install then it should ask you to login using the new system they implemented.

**Comment by Darklustre** [comment]
Ok that's good to know. I've Googled it a lot and never read that. Just the advice to change the password. 

Your advice seems to have worked. I saw that the path was wrong. It was going to..../Mod instead of Mod Organizer. I didn't catch that .

However now I'm having difficulty with getting a mod to come through. It's saying it failed because Host requires authentication. Is there something else I'm supposed to do now?

Thanks.

**Comment by Al12rs** [comment]
Yes: open the Mo2 settings -> Nexus -> Connect to Nexus.

**Comment by Darklustre** [comment]
It worked! Would it be terribly out of line to pledge my undying love?

**Comment by Al12rs** [comment]
I shall allow it
Cheers

**Comment by Darklustre** [comment]
I do have another issue but I'm not sure if I should take up a new thread about it. I've created a few mods off Steam but the mods are unmanaged and not working. I've tried removing them, but it won't let me remove the mod or the plugins. Is there anything you can suggest?

**Comment by Al12rs** [comment]
No, since it's not a Mo2 issue/bug please use some other forum like reddit or the Steam forum for this.

**Comment by Darklustre** [comment]
I thought that was a bug since it can't be removed. Thank you I'll try finding someone who will respond to that.
