### ISSUE TITLE
Problem with switching themes in Mod Organaizer2

### ISSUE THREAD

**Issue by hhvvutg** [ModOrganizer2/modorganizer#1027]
There was a problem with the themes: I decided to change the theme in MO2 and started switching and see which one I like more but when switching to the Paper Automata theme, the OK button stopped appearing, the theme stopped changing, any changes are not applied. Please help me!!!
MO 2 version- v.2.2.2.1

**Comment by Al12rs** [comment]
Did you try restarting Mo2?
