### ISSUE TITLE
Problem With Mod Organizer 2 Not Saving Mod List

### ISSUE THREAD

**Issue by DivineGrapefruit** [ModOrganizer2/modorganizer#1028]
So, whenever i start up Mod Organizer after starting my PC, the same couple of mods are unchecked and whatever mod i downloaded and added is gone. I tried updating to the newest version and updated the Visual C++ 2019 redist, however the same issue still persists. It's like Mod Organizer has a certain "version" of the modlist and settings saved, and it resets everytime i restart my pc. Any help would be greatly appreciated :)

**Comment by LostDragonist** [comment]
It's probably some anti-virus taking exception to MO doing stuff in certain folders.  You'll want to look at stuff installed on your computer and go make exceptions in those programs.

**Comment by DivineGrapefruit** [comment]
> It's probably some anti-virus taking exception to MO doing stuff in certain folders. You'll want to look at stuff installed on your computer and go make exceptions in those programs.

I only have windows defender and a malwarebytes trial version, i tried making exceptions to all the folders/files but unfortunately it didn't work :( Thanks for the help though

**Comment by DivineGrapefruit** [comment]
> So, whenever i start up Mod Organizer after starting my PC, the same couple of mods are unchecked and whatever mod i downloaded and added is gone. I tried updating to the newest version and updated the Visual C++ 2019 redist, however the same issue still persists. It's like Mod Organizer has a certain "version" of the modlist and settings saved, and it resets everytime i restart my pc. Any help would be greatly appreciated :)

Hmm it would seem that it is a problem with my drive, because when i place a file on my drive and restart my pc, the file is gone so it might be a corrupted drive. Luckily it isn't my boot drive

**Comment by Al12rs** [comment]
Since this doesn't appear to be a mo2 issue I'm closing.
