### ISSUE TITLE
Not removing mod components correctly?

### ISSUE THREAD

**Issue by Darklustre** [ModOrganizer2/modorganizer#1034]
I'm trying to put Diseased Overhaul as top priority so that it overwrites anything that might conflict. Loot puts it near the middle. I listed it in the highest number priority in both plugins and mod tab. But "Cure (name of disease) Potions" keep showing up at alchemists. Googling I found that is related to Dangerous Diseases. I had that a long time ago and removed it from MO2 with "Remove Mod". I still have iNeed, but had nothing checked for DD. In desperation I removed iNeed too. But those potions still show up. They have to be coming from DD that isn't installed. No plugins, no mod. At the very least, Diseased Overhaul should be overwriting it. 

My friend and I have been researching this but can't find an answer to what is happening. Could you please assist? Thank you for your help.

Edit: I also started new games every time.

**Comment by LostDragonist** [comment]
If the plugin doesn't exist, then it doesn't exist.  That's about as much as we can help with in terms of MO2.  This is a modding problem which makes this a pretty inappropriate place to look for help.  There are various chat rooms (discord server) and forums where you can seek help with stuff like this.  Nexus forums, reddit.com/r/skyrimmods, STEP forums, the MO2 discord's #modding channel, the /r/skyrimmods discord, the Nexus mods discord.  All decent places to go.

To get any help you'd need to provide information like the game you're playing/modding and your entire mod list and load order.  The mod list would need to be exact as searching for "Diseased Overhaul" or "Dangerous Diseases" provides no useful results.

**Comment by Darklustre** [comment]
I don't think it's inappropriate to post a problem with MO2 not uninstalling components correctly. It should be removing these things from the game not leaving references even in a new game. But if you don't know what could be wrong, then thank you for your time anyway.
