### ISSUE TITLE
wrong file reported in error message when parsing fomod

### ISSUE THREAD

**Issue by jmdavis** [ModOrganizer2/modorganizer#1038]
## The problem:
If the info.xml file in a fomod installer has an error in it (e.g. it has `foo` or some other text after the closing tag for the root tag), MO2 pops up an error message which says `Failed to parse ModuleConfig.xml. See console for details`. So, the error message lists the wrong file name. In addition to that, nothing about the error gets printed to the console / log.

If instead ModuleConfig.xml is the file with errors, then the error message still (correctly) says ModuleConfig.xml, and you actually get an error message in the log. So, that seems to be working correctly, but the error handling for info.xml does not seem to be working properly.

## To Reproduce:

1. Take any fomod installer and unpack it.
2. Edit its Fomod\info.xml file so that it's invalid (e.g. adding random text at the end of the file)
3. Repack the mod.
4. Add it to MO2's downloads.
5. Right click on the file in the downloads and select "Install."

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.2.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): I have not tried other versions
* Desktop OS/version used to run Mod Organizer: Windows 10

### MO Interface:
Nothing shows up in the log from the error. If I actually complete the install instead of canceling it, then I get

[2020-04-03 16:10:17.570 I] None of the selected mods can be updated.

but I get the same line if the info.xml file isn't invalid and thus no error message pops up. So, it clearly has nothing to do with the incorrect error message.

**Comment by LostDragonist** [comment]
Do you have your log level set to debug?  Looks like all the messages in that area are considered debug messages.

**Comment by jmdavis** [comment]
I didn't realize that there was even a setting for adjusting the log level, though I suppose that I should have thought of it. If I change the log level to debug and alter the installer for `https://www.nexusmods.com/skyrimspecialedition/mods/34316` so that it has junk at the end of its info.xml, then I get

```
[2020-04-03 17:41:20.831 D] Opened  "G:/Skyrim SE Tools/Mod Organizer 2/downloads/Improved Bards - CBBE SE and CBBE 3BBB (3BA) Bodyslides.7z"  using  "7z"  (from signature)
[2020-04-03 17:41:22.002 D] trying encoding utf-16
[2020-04-03 17:41:22.004 D] not utf-16: Start tag expected. in line 1
[2020-04-03 17:41:22.005 D] trying encoding utf-8
[2020-04-03 17:41:22.006 D] not utf-8: Extra content at end of document. in line 9
[2020-04-03 17:41:22.007 D] trying encoding iso-8859-1
[2020-04-03 17:41:22.009 D] not iso-8859-1: Extra content at end of document. in line 9
[2020-04-03 17:41:31.566 D] module name :  "Improved Bards - CBBE SE and CBBE 3BBB (3BA) Bodyslides"
[2020-04-03 17:41:34.828 D] validator: cancelled
```

if I cancel the install once the fomod actually pops up. So, in that case, it at least logs the problem about extra content, but of course, the error message that pops up still indicates the wrong file. And it's a bit odd that if info.xml is screwed up, it's only logged with debug, whereas if ModuleConfig.xml is screwed up, it logs at info. So, the log messages should probably be adjusted, but either way, the error message clearly should be fixed.
