### ISSUE TITLE
Allow user defined emotes like system as a visual tag system

### ISSUE THREAD

**Issue by Al12rs** [ModOrganizer2/modorganizer#1045]
Suggestion from discord to either allow an emotes selector for the notes column or add a new column for user defined icons to assign to mods. We could ship with a pool of normal emotes and users cold create packs for the various games. 

Thus the emotes should be easy to expand.

To search for these we would either have to add an emote selector to the text filter, or add the emotes as custom categories in the filter list, which would make it much longer.

As an alternative to this system we could just use a fully fledged tags system.

**Comment by AnyOldName3** [comment]
What happens if someone just types emoji in the notes title box? That would do most of this already.

**Comment by Al12rs** [comment]
You can already use emojis in the Notes using Win+"." . So I'm closing this.
