### ISSUE TITLE
Creation Kit SE Source/Scripts workaround

### ISSUE THREAD

**Issue by steve962** [ModOrganizer2/modorganizer#1049]
As someone relatively new to MO2 and to the Creation Kit, I spent *far* too much time recently getting it to be able to compile my scripts.  I was particularly trying to put together a small MCM for diagnostics and experimentation, and got slammed in a roadblock right from the start.

The issue, as you probably immediatly saw being experienced, is the dreaded Source/Scripts problem with SE's version of Creation Kit.  By default, Creation Kit for Skyrim SE looks for (and puts) it's script sources in the folder "Data\Source\Scripts", while almost every mod in existence puts
them into Data\Scripts\Source.  This means when you try to access something like the SKI_ConfigBase class which SkyUI's MCM uses, it fails to compile.

I ran into a lot of confusing, conflicting, and incomplete information on how to fix this, and finally through a lot of experimentation launching the Creation Kit *outside* of MO2, I understood the problem and how to fix it.   I've written up this procedure for MO2 and submitted it as a new Wiki page, which I hope you'll accept - or feel free to take that information and put it on the troubleshooting page instead.  It would make other people's life easier to have all this information in one place.

Down the road, however, there's a feature you could add to MO2 which might make even easier for new people to get started.  Since you're virtualizing the disk anyway, overlaying folder over folder, why not add a checkbox in your workarounds which, when running Creation Kit through MO2, will overlay the Data/Scripts/Source folder on top of Data/Source/Scripts.  Should be almost trivial, and make it MUCH easier for people to get started with Creation Kit on SE.  Just a suggestion.

**Comment by Al12rs** [comment]
Where did you submit this wiki page? Also I thought it was just a matter of either changing an ini line for the ck or just fix the folder structure in the mods.

**Comment by Qudix** [comment]
The proper fix would be to get mod authors to stop packaging them as Data/Source/Scripts/. A few of them believe that Bethesda packaged it that way on purpose, when it was acutally a mistake they never fixed.

**Comment by steve962** [comment]
Yes, it'[s a matter of BOTH changing the ini line and fixing folder structure (I did it in Bethesda's scripts.zip in the wiki since more mods have the Scripts/Source layout than Source/Scripts and this is the biggest offender...), but there's nowhere I could find which explains all of that clearly and completely... and I spent a great deal of time searching for it.  It took a comment buried under a YouTube video to point me in the right direction, then more searching 

The wiki page I wrote needed to be out there somewhere, and since it was MO2 centric, the Wiki right here on MO2's Github made sense.   I had thought there would need to be accepted by whoever has admin rights for this project, but I'm seeing it as a new Wiki page in the right sidebar right now.  (Possibly because I submitted it?)  Here's the link:

https://github.com/ModOrganizer2/modorganizer/wiki/Skyrim-Creation-Kit-SE-and-MO2

As for the proper fix - it's far too late to have mod authors (and Bethesda) do it now -- that's why I suggested this feature request -- it would work consistently no matter how Bethesda or mod authors packaged things.

**Comment by Al12rs** [comment]
Regarding Mo2 changing the mapping of those folders, that is I'm afraid not at all trivial. Not even sure if it's a good thing to do. In any case we would end up with stuff that is cross linked which is very likely to cause all kinds of issues in usvfs.

**Comment by Al12rs** [comment]
I guess this can be closed?

**Comment by jimmed** [comment]
@steve962 Thanks for the helpful guide - I too have been down the same rabbit hole today.

I'm patching a script to fix a crash to desktop, which the creation kit is supposedly compiling successfully. However, even after following your guide, I don't see the .pex file written to disk *anywhere*. Any suggestions as to what I'm doing wrong here?

**Comment by jimmed** [comment]
Never mind, [apparently the fix I'm attempting to implement isn't going to solve the issue anyway :neutral_face:](https://afktrack.afkmods.com/index.php?a=issues&i=29159).
