### ISSUE TITLE
MO2 accepts invalid ModuleConfig.xml

### ISSUE THREAD

**Issue by PatrickGeurts** [ModOrganizer2/modorganizer#1050]
MO2 accepts invalid ModuleConfig.xml inside the FOMOD Folder.
Even with missing lines of code it still functions.

Mods posted with these invalid FOMODs will not function on NMM and Vortex
( and I guess not on Wrye Bash, not confirmed )

MO2 needs some sort of generic .xml library to check if the provided ModuleConfig.xml is valid.

**Comment by PatrickGeurts** [comment]
MO2 accepts invalid ModuleConfig.xml inside the FOMOD Folder.
Even with missing lines of code it still functions.

Mods posted with these invalid FOMODs will not function on NMM and Vortex
( and I guess not on Wrye Bash, not confirmed )

MO2 needs some sort of generic .xml library to check if the provided ModuleConfig.xml is valid.

**Comment by KerberX** [comment]
What missing lines of code? Can you upload an example of such `ModuleConfig.xml` file?

**Comment by PatrickGeurts** [comment]
[ModuleConfig.zip](https://github.com/ModOrganizer2/modorganizer/files/4466405/ModuleConfig.zip)

In the attached ModuleConfig.xml the bold lines are sometimes missing. 
These lines are mandatory in a .xml file. Without these lines MO2 still installs the files in the FOMOD, other MOs don't.


<plugin name="Black">
        **_<description><![CDATA[Select this if you want a black Windhelm horse]]></description>_**     
       <image path="00 Images\Black.jpg"/>
       <files>
               <folder source="09 Brown Horse\Black" destination=""/>
       </files>
       **_<typeDescriptor>
               <type name="Optional" />
       </typeDescriptor>_**
</plugin>

**Comment by PatrickGeurts** [comment]
![MO2](https://user-images.githubusercontent.com/45037827/79069944-563c7300-7cd2-11ea-9ede-063f171f995f.jpg)

**Comment by KerberX** [comment]
Now I see. These options aren't mandatory for FOMod to function properly but they're defined as mandatory in XML scheme. NMM and Vortex validates FOMod's XML against the scheme, MO2 and other mod mangers don't.

**Comment by KerberX** [comment]
MO2 would need to use an XML scheme validator to catch these. I personally don't think MO2 need to discard such FOMods but it can show a warning when the config doesn't pass XML scheme validation.

**Comment by isanae** [comment]
[Not a bug](https://en.wikipedia.org/wiki/Postel's_law).
