### ISSUE TITLE
Removal of backup marks installed file as uninstalled

### ISSUE THREAD

**Issue by cibrhusk** [ModOrganizer2/modorganizer#1059]
## The problem:
Removal of backup marks installed file as uninstalled

## To Reproduce:
- Install a mod v1
- Install same mod v2 - replacing v1 with the backup option selected
- remove the now created backup
- see that file file used to install the mod v2 is now marked as uninstalled,

## Environment:

* Mod Organizer Version 2.2.2.1
* Desktop OS/version used to run Mod Organizer: Win 10 1909

**Comment by sibirskoye** [comment]
It still occurs in 2.3.2 RC 1.1 and can be reproduced more simply by just making a backup of a mod and deleting the backup.
