### ISSUE TITLE
Unrecognized Game Mode: skyrimspecialeditiona

### ISSUE THREAD

**Issue by TaraBryn** [ModOrganizer2/modorganizer#1062]
## The problem:
Getting "Unrecognized game mode: skyrimspecialedition" error.

## To Reproduce:
Steps to reproduce the behavior: try downloading a SSE mod from nexusmods with the "vortex" option (manual mod installs work fine).

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.2.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.2.2.1, prior to nexusmods updating (apparently nexusmods changed the link format for some games about a week ago, see [related issue for NMM](https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/998))
* Desktop OS/version used to run Mod Organizer: windows 10

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed.

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by LostDragonist** [comment]
This indicates you are not using 2.2.2.1.  Make sure you don't have two copies of MO2 installed in various places.

**Comment by TaraBryn** [comment]
> This indicates you are not using 2.2.2.1. Make sure you don't have two copies of MO2 installed in various places.

So it *is* on 2.2.2.1; however, when I went to uninstall/re-install it, it turns out I had NMM installed along with mod organizer, and NXM links were associated with NMM, and up until the change for some reason it hadn't made a difference?

I removed NMM and now it's working fine. Thanks!
