### ISSUE TITLE
Allow python plugin as whole "module"

### ISSUE THREAD

**Issue by Holt59** [ModOrganizer2/modorganizer#1067]
### Problem

Currently, a python module consists of a `.py` file in the `plugins/` folder and anything required by the plugin goes to the `data/` folder. As the number of python plugins grows (let's be optimistic!), the `data/` folder is going to be cluttered, especially if one want to separate his plugin into multiple python files.

### Feature

It should be possible to provide a python plugin as a folder corresponding to a module with a `__init__.py` file containing the `createPlugin()` function.

This also allows python plugin to store their assets in their own folder. This does not even require modification of the interface (e.g., to give the plugin path) since it is very easy to access the current module path in python.

### Implementation

This requires very minor modification of the `plugin_python` project:
- Modify the `ProxyPython::pluginList()` function to also return modules.
- Modify the `PythonRunner::instantiate` function to import module.

Currently the only issue is to give `PythonRunner` access to the plugin path which is currently not accessible from `IOrganizer` (only `pluginDataPath` is available).

**Note:** It is not possible to treat both single files and folder as module as this would require having a `plugins/__init__.py` file which we might not want.

**Comment by Al12rs** [comment]
So basically this change would require all existing python plugins to be changed to be a folder with __init__.py in it?

**Comment by Holt59** [comment]
No, we allow both.

I think there are plugins that do not require multiple files (your `generic_game` or the `Form43Checker` for instance), so I see no benefits as forcing them to have a whole module instead of a single file.

**Comment by Al12rs** [comment]
Ah ok, I wasn't sure from the wording. In that case this would be a good solution for the plugin/data problem.
