### ISSUE TITLE
Missing modsource-registration based overwriting error

### ISSUE THREAD

**Issue by Feuerkl1nge** [ModOrganizer2/modorganizer#1068]
No plugin overwrite of a plugin, that overwrite another plugin with the same name if the source path of the (manual) installation of the corresponding old overwritten mod was changed and that change was't registered in MO yet.

To be clear "registered" in that context means the case that also results in a not working mod reinstallation while intended and not based on a bug.

That can be annoying especially in some mod testing cases.

MO2 2.2.2.1
SkyrimSE
Windows 10 Pro 1909

**Comment by Al12rs** [comment]
We discussed this on discord (https://discordapp.com/channels/265929299490635777/403979692501106688/708035512711118932) and we couldn't reproduce.
