### ISSUE TITLE
Allow localized strings for MO2 plugin names and add localized plugin categories

### ISSUE THREAD

**Issue by Holt59** [ModOrganizer2/modorganizer#1069]
Proposal to fix the two following issues:
- Currently, the name of the plugin cannot be localized (`tr()`) because the names is used to actually store the settings of the plugin.
- The "category" of the plugin (i.e., the implemented interface) is hard to access from the actual plugin (have to try all the types), and the name is a C++ class.

For display purpose, it would be interesting to have localized names and plugin type/category names. I propose to:

1. Add a `pluginDisplayName` method to the `IPlugin` class, which, unlike `name()`, can use a localized strings and is only used for display purpose. The default implementation would simply call `name()` to avoid issue with existing plugins.
2. Add a `pluginDisplayCategory` method to the `IPlugin` that should only be implemented by top-level plugin interface which returns the type of the plugin, for display purpose, e.g., `Games`, `Previews`, etc. The default would be `"Others"` (or something alike, see notr below).

**Note:** `displayName` cannot be used because it's a method of one of the plugin type (`IModPage` I think), which is why I propose `pluginDisplayName` and `pluginDisplayCategory` (to be consistent).

**Note:** We should specify what `pluginDisplayCategory` should return. For instance, for `IPluginGame`, should it be `"Game"`, `"Game Plugin"`, `"Games"`, `"Game Plugins"`, ...?

**Note:** `puginDisplayCategory` could also be `pluginDisplayCategories` and return a list of localized strings for classes that actually implement multiple plugin type (I'm thinking of `Diagnose` and `FileMapper` plugins in particular).

**Comment by Al12rs** [comment]
> The "category" of the plugin (i.e., the implemented interface) is hard to access from the actual plugin (have to try all the types), and the name is a C++ class.
I'm not clear on what you mean here, can you make a use case example?

**Comment by Holt59** [comment]
@Al12rs The idea is that if we, for instance, want to display the plugins by category, there is no easy way to do that right now: we can group them depending on the interface they inherit, which is already not really clean, and then we do not have an actual name to display.

Here is what this would look like:

```cpp
class IPlugin {
    virtual QString pluginDisplayCategory() const { return "Others"; }
};

class IPluginGame: IPlugin {
    QString pluginDisplayCategory() const override { return "Games"; }
};

class IPluginPreview: IPlugin {
    QString pluginDisplayCategory() const override { return "Preview"; }
};
```

The actual plugin would not have to implement this, except in special cases (e.g., standalone `Diagnose` plugin). And we could make it returns multiple categories for classes that implement multiple interfaces.

**Comment by Al12rs** [comment]
I was thinking that if we return an empty list in `IPlugin` we could simply append to the list returned by the parents in `IPluginDiagnose` and `IPluginTool` etc so that we automatically get correct lists for all plugins. Would you want these to be translatable or more for internal classification?

**Comment by Holt59** [comment]
Another possibility, since `PluginContainer` uses `boost::fusion`, would be to have names stored somewhere else:

```cpp
template <class Plugin>
struct display_name;

template <>
struct display_name<IPlugin> {
    static const QString name = tr("Others"); // Note: This cannot be initialized here actually.
};

template <>
struct display_name<IPluginGame> {
    static const QString name = tr("Games");
};
```

**Comment by Al12rs** [comment]
I like this one, but what happens when a plugin is both diagnose and tool?

**Comment by Holt59** [comment]
@Al12rs 

First comment: I would them to be localized because it's mainly for display purpose (that long list of plugins is getting me nervous ;)).

Second comment: I'd have to check how the plugins are actually stored but you could fetch all the matching ones and either concatenate the names or display the plugin in each category.

**Comment by Al12rs** [comment]
Ok, I was mostly curious about what you wanted it for. Since I don't really mind one ui or another for plugins settings tab I don't mind how it's implemented.

**Comment by AnyOldName3** [comment]
While I can see the advantage of moving `displayName()` from `IPluginTool` to `IPlugin` so we've got a name we can use in the plugin settings list (although we might need to do some thinking as `/` is used to add menu nesting), I don't really see the advantage of categories. If we want to make the list prettier, we already have the data to do stuff like let you filter by author or interfaces implemented without adding anything to the plugins.

**Comment by Holt59** [comment]
@AnyOldName3 I did not even notice that `displayName` was in `IPluginTool`. There is also a `displayName` in `IModPage` so the name may conflict.

> I don't really see the advantage of categories. If we want to make the list prettier, we already have the data to do stuff like let you filter by author or interfaces implemented without adding anything to the plugins.

Yes, but you have no way to present a proper plugin "category" name currently. Best you can do is say "Show me the plugin that implement X", where `X` is a Visual Studio generated strings to represent, e.g., `IPluginGame`, so probably not something you want the user to see.

I agree that the version with template specialization is probably better though.

**Comment by AnyOldName3** [comment]
> I did not even notice that `displayName` was in `IPluginTool`. There is also a `displayName` in `IModPage` so the name will conflict anyway.

Maybe `localisableName` and add a default implementation in the interfaces that already have a display name to use the display name.



We already merge list entries with the same name, even if they're different pointers so we could just iterate over all the things the plugin manager has pointers for, ask them for their names, and then set a bool in a map from name to bool array. We could also have a static `pluginInterfaceName` method for each of our interfaces and use that to turn the bool list into a text list or give us column headings for the bool lists to be displayed as table entries. We run MOC on our plugin interfaces, so it might even have made such a field for us already.

**Comment by Holt59** [comment]
yes, `localizableName` seems like a good name, and it's quite simple to default it to `displayName` if possible.

I don't think the class names generated by Qt for the plugins are localized, and there are plugin types that do not inherit `QObject` so it's a bit more complicated. I think adding a static method is probably the best way to get the interface name.

**Comment by AnyOldName3** [comment]
I thought of the MOC thing, then came up with a reason why it wouldn't work, then got to writing that part of the post and couldn't remember it any more, so it's good that you noticed the thing I forgot.

I anticipate that we'll be constructing this mapping when loading plugins in the first place, and at that point, we have access to the original plugin pointer, so can get the instance name, and we have a bit of code for every plugin interface and plugin extension interface that we have, so know everything that it implements (although this happens in multiple passes for proxied plugins as that made things a bazillion times easier with Python).

**Comment by Holt59** [comment]
I don't think we even need to do per-plugin type things because `m_Plugins` is a `boost::fusion::map` that contains everything needed, so with a tiny bit of meta-programming, we can extract everything properly whenever we want. We just need to iterate over it, fetch the "category" from the key, the names from the actual plugins, and we're good to go.

**Comment by Holt59** [comment]
Why is that issue still open? 🤔
