### ISSUE TITLE
Mod Organizer 2.2.2.1, Fallout 4 crashes in seconds of loading or starting new game 

### ISSUE THREAD

**Issue by andyonix** [ModOrganizer2/modorganizer#1070]
## The problem:
I found the Issue. If i use Mod Organizer 2.2.2.1 Fallout 4crashes in 15 seconds no error, when i load a save game or start a new game. 0 mods or 498 mods does not matter, this is a new one for me. I have tried to run Fallout 4, 312 times in the past 3 weeks and it only 9 times did a new game or loaded a save file work, when i used the direct files f4se_loader.exe, Fallout4.exe, and Fallout4Launcher.exe directly.

What i think: Mod Organizer 2.2.2.1 appears to be broken, or incompatible with Fallout 4 game files.

## To Reproduce:
As i said start Mod Organizer 2.2.2.1, select fallout 4, run f4se_loader.exe, Fallout4.exe, or Fallout4Launcher.exe through Mod Organizer 2.2.2.1. Start a new game or load a save file, it will crash in 15 seconds, every time.

 I have tried to run Fallout 4, 312 times in the past 3 weeks 97% of the runs with Mod Organizer 2.2.2.1 and its been spot on, no inconsistencies yet.

## Environment:

* Mod Organizer 2.2.2.1 is appears to be broken, or incompatible with Fallout 4 game files. in my case
* Mod Organizer 2.2.1.0 was fine for me.
* Windows 10 64 bit, version 1909, build 18363.778 is what i use

## Details:
As i said If i use Mod Organizer 2.2.2.1 Fallout 4 crashes in 15 seconds with no error for no appear-ant reason when i load a save game or start a new game. I have tried the game as a fresh install with 0 mods crashed in 15 seconds or fully decked out with 498 mods(643 plugins) and it still does not matter. I have tried to run Fallout 4 312 times in the past 3 weeks. and it only 9 times did a new game or loaded a save file work, when i used the direct files f4se_loader.exe, Fallout4.exe, and Fallout4Launcher.exe WITHOUT Mod Organizer 2.2.2.1. and last week i uninstalled and reinstalled Mod Organizer 2.2.2.1. still no difference. I have slimmed down my load order to 197 mods(226 plugins) and it works without Mod organizer 2.2.2.1, very slow to load, but it works. 

And as for pictures..... it crashes with no error or warning, how can i take a picture of something that doesn't tell you there is an error. 

### MO Interface:
https://gist.github.com/andyonix/7419622f0a0d4547ee4124ac9d7e5468

**Comment by LostDragonist** [comment]
Best guess at this point is some sort of anti-virus interfering with MO2.  If you upload a new mo_interface.log with debugging turned on, I might be able to confirm that more easily.

>1) Go in the Settings, Diagnostics tab, set Log Level to Debug.
>2) Restart MO.
>3) Upload new mo_interface.log

**Comment by andyonix** [comment]
I've been using Bitdefender total security for nearly 6 years, never had an issue before with mod organizer. but i will do as you suggest.

**Comment by andyonix** [comment]
https://gist.github.com/andyonix/51ccc5a8f62e62c9ec5a721b1f592aaa

**Comment by LostDragonist** [comment]
Yeah, it's 95% going to Bitdefender causing problems.  /shrug.

**Comment by 352** [comment]
I use Bitdefender (BitDefender Total Security) with Skyrim SE (this may not apply precisely to Fallout).  Every time I update MO2 (I keep current with all beta releases), Bitdefender refuses to permit usvfs_proxy_x64.exe to install insisting it is a virus.  The solution is easy, when the notification pops up, select allow.  You can also whitelist MO and the usvfs file in the ONLINE THREAT PREVENTION section of BitDefender's Protection Features area.

I have notified BitDefender's customer service department about the false positive re usvfs_Proxy_x64.exe, but those notifications have apparently fallen on deaf ears.

Hope this information is of help.

**Comment by andyonix** [comment]
I did that long ago. I whitelist all my best apps in the Antivirus, Firewall, Advanced Threat Defense, Online threat Prevention, and Ransomware remediation.

And i have tried running Mod Organizer 2.2.2.1 without my antivirus... Still the same thing.  I EVEN FUCKING REINSTALLED WINDOWS, AND STILL THE SAME RESULT, I SWAPPED OUT MY GPU, MY CPU, MY MOTHERBOARD, RAM, DIFFERENT HARDDRIVES, A DIFFERENT POWER SUPPLY, I EVEN USED MY OLD A8 6600K APU WITH DDR3 ON AN FM2+ MOTHERBOARD, IM NOT A FUCKING IDIOT, I DIAGNOSED EVERY POSSIBLE POINT OF FAILURE BEFORE I SUSPECTED MOD ORGANIZER, INCLUDING USING WINDOWS 7, 8, 8.1, EVEN AN OLDER VERSION OF WINDOWS 10.

I did say i had been at this for over 2 months, and its only been the past 3 weeks did i suspect Mod Organizer 2.2.2.1.  But instead i have been looking at mod compatibility Ant the last 3 weeks were hell, I went through 498 mods, looking for compatibility issues, crashes, and all sorts of issues that were common and rare. and finally 3 days ago i had gone through every mod, and i tried running Mod Organizer 2.2.2.1 without mods it did the same thing.

Everything seems to run fine as i said it only crashes when i load a save game or start a new game, everything else gives a BIG ALL GREEN CHECK MARK.

If i run the files Directly: f4se_loader.exe, Fallout4.exe, and Fallout4Launcher.exe i can run all 498 mods. And i checked Bitdefender, it says Mod Organizer 2.2.2.1 is ALL GREEN, not blocking or restricting anything.

Besides As i have said, this is the First version of Mod Organizer, Mod Organizer 2, Nexus Mod Manager, Vortex or any other mod Manager that has done this for me.

I have Had BitDefender for over 6 years, this has never happened to me before. 

FINAL VERDICT: I'm going back to Mod Organizer 2.2.1.0 and i did. look at this.

https://imgur.com/a/HgOKitC

**Comment by LostDragonist** [comment]
I had a perfectly functioning pancreas for 28 years.  That doesn't make me any less diabetic than it does today.  Bitdefender is known to mess with MO2 even if you think Bitdefender is disabled.  Even if Bitdefender says nothing about it.  There's really nothing we can do about it.  

Though you're welcome to continue using 2.2.1.0.  /shrug.

**Comment by andyonix** [comment]
I understand what your saying,  and im willing to help fix this error, but its not related to Bit defender, did you even read my post.... if you did you would understand i ran MO2 on a FRESH VERSION OF WINDOWS 7, 8, 8, 1, AND 10, WITHOUT BITDEFENDER, AND WA STILL GETTING THE SAME RESULT.
............ i just don't want others to have this same problem, THAT IS WHY I SPENT 2 MONTHS DIAGNOSING IT TO FIND THE ROOT OF THE PROBLEM before i suspected Mod Organizer 2.2.2.1, in case some else has the same issue as me. they would know what to do by finding my post, or Help fix the problem so it never does happen(not likely though)

**Comment by LostDragonist** [comment]
No, I did not read your post.  Sorry.

I will concede that Bitdefender might not be to blame.  However there is *something* on your computer that is causing fundamental issues with MO2.  This is observable in the USVFS logs with the smattering of messages that say something like `[I] existing hook to 7ff7ccfa0d00 in unknown`.  This is a very abnormal condition that tells me that something is hooking the game in a similar manner to MO but one that is in likelihood fundamentally incompatible with MO.

My experience over the last 2 years is that everyone who had these messages in the logs were using something like Bitdefender and all their problems went away after uninstalling that something.  

Maybe there's something for us to fix here or maybe there's not.  I honestly don't know.  I just know that the problem with the logs you posted this last time were *most likely* a problem with Bitdefender.  Hell, it may or even may not be involved in the crash.  The only way we could actually test something like that is if you uninstalled Bitdefender and produced new logs but you said FINAL VERDICT so I'm going to assume that you're not going to do that.

I guess not that there's any point directing that to you at this time.  There, everything is out in the open for historical purposes.  I hope it helps someone.

**Comment by andyonix** [comment]
Wow now were getting to the meat of the pie, as far as i know i dont use any other mod organizer, programs i use daily:
Advanced SystemCare, FX Sound Enhancer, Smart Defrag, Logitech Gaming Software, Steam, Origin, Intelligent Standby List Cleaner(https://www.wagnardsoft.com/), VLC, Bitdefender Total Security, Radeon Software, i Also use Bluetooth for my Xbox one controller, my Wireless AG9+ Headset(USB Dongle), I do have Folding at Home( i use it a lot)...... and i DO have an App that does mess with some games it allows me to turn any smartphone/tablet/even Android TV's into a second wireless screen, i can have many active at once. called Spacedesk(https://spacedesk.net/) its freaking awesome. Depends on connection throughput but these settings that work awesome for me.
Quality/Performance: image quality  - 2/3 to 3/4, Encoding Color Depth - Medium color quality, Custom FPS Rate - 30fps, Rendering Color Depth - 16-bit
Resolution: Use custom resolution - (check), Choose Custom Resolution - 1280 x 720.

**Comment by andyonix** [comment]
..........................sorry..................... i got carried away.

**Comment by Al12rs** [comment]
Lets rewind a little. What happens if you start F4SE directly, without MO2? Does it still occasionally crash?

**Comment by andyonix** [comment]
no, not for me, runs fine this is my Load order, and i can run it all without Mod organizer 2, pretty well. I had to go back to Mod Organizer 2.2.1.0, but its also running well, im going to stream it in a bit to see how well it does... maybe just braodcast it through steam....not sure

i modified it a bit.... added 15 extra mods...lol
[loadorder.txt](https://github.com/ModOrganizer2/modorganizer/files/4621388/loadorder.txt)

**Comment by andyonix** [comment]
Wait, are you talking about the occasional random crash that almost does it near every hour- hour and a half?

**Comment by Al12rs** [comment]
Ok so it's not crashing outside of Mo2.
Could you test creating a new profile and selecting the "Default Game INI settings" option when doing so?

> To check whether the issue is related to one of the mods installed or your ini settings, see if it keeps happening in a new empty profile:
https://cdn.discordapp.com/attachments/403979692501106688/524939782435110924/unknown.png
https://cdn.discordapp.com/attachments/403979692501106688/524940397643038740/unknown.png

**Comment by andyonix** [comment]
a lot of my issues were fixed a long time ago

I mostly fixed it for me by using 
Fallout 4 - Texture Optimization Project(slow process, but worthwhile)
https://www.nexusmods.com/fallout4/mods/978
Unofficial Fallout 4 Patch(fixed many issues)
https://www.nexusmods.com/fallout4/mods/4598
BethINI(freaking life saver)
https://www.nexusmods.com/fallout4/mods/67
Universal Patch Installer - Fallout 4 Edition(if you use many mods or weapon mods.. well any mods)
https://www.nexusmods.com/fallout4/mods/34825

**Comment by Al12rs** [comment]
Please run the game as I described, without any mods or running any other tool

**Comment by andyonix** [comment]
...............................................i already have a profile like that....i call it test

**Comment by Al12rs** [comment]
Please make a new use selecting the Default Game INI settings option and run the game, see if it crashes.

**Comment by andyonix** [comment]
<img width="960" alt="ScreenShot_20200513065648" src="https://user-images.githubusercontent.com/65219754/81804467-222dbb00-94e7-11ea-90bf-ca7eb23bcf8f.png">

Did you read my posts.... i already did that, and it didn't work With Mod Organizer2.2.2.1, so i had to go back to Mod Organizer 2.2.1.0................ but here you are, and the result.
With mod Organizer 2.2.1.0(known working for me)
Fallout4.exe(works)
F4SE_Loader.exe(works)
Without Mod Organizer 2.2.1.0
Fallout4.exe(works)
F4SE_loader.exe(works)
why are you asking me to do something i have done 94 times in the past 3 weeks? i did it, but im not happy.

**Comment by andyonix** [comment]
If your wondering, im not angry, but i am the type who thrists for information when someone asks me or tells me to do anything. that is all about that, its pretty simple, i love Mod Organizer 2, very much so. And if LostDragonist is as good as i think he is then something in Windows, or maybe a program i use, is intercepting and changing.... maybe... if i may ask Were there any Major changes in Mod Organizer 2.2.2.1 that are not present in Mod Organizer 2.2.1.0?

**Comment by Al12rs** [comment]
Look I'm trying to debug the problem and I can't do so with other factors into play like mods etc. The logs get hundreds of thousands of lines long and each mod can add thousands of lines. 

What I'm asking you is to reproduce the issues (so on 2.2.2.1 obviously) with the least amount of things interfering. That means creating a profile where **I** know that there are no problems with in settings and no problems with mods. 
I can't be sure you didn't change something in your testing profile and I really don't feel like diving into megabytes of log lines multiple times for nothing. No one pays me.

**Comment by andyonix** [comment]
If your wondering, im not angry, but i am the type who thrists for information when someone asks me or tells me to do anything. that is all about that, its pretty simple, i love Mod Organizer 2, very much so. And if LostDragonist is as good as i think he is then something in Windows, or maybe a program i use, is intercepting and changing.... maybe... if i may ask Were there any Major changes in Mod Organizer 2.2.2.1 that are not present in Mod Organizer 2.2.1.0?

**Comment by Al12rs** [comment]
https://github.com/ModOrganizer2/modorganizer/wiki/Mod-Organizer-2-Changelog#v2221

**Comment by andyonix** [comment]
Thank you, i will look at it, im just wondering if anything changed in how MO2 interacted with the game, that will help me narrow it down..... brb going to look at it, Thank You

**Comment by Al12rs** [comment]
There is nothing there that is relevant to this. 

If you can please verify that the issue persists using the method specified above on 2.2.2.1 .
I don't like to waste time and the things we ask the users to do are to determine facts I can rely on. I don't want to waste a lot of time only to discover two hours later that there was in fact an ini setting that was influencing this. This has happened before so I ask users to perform tests where I know what has happened and not test performed on their own. You could be very good and have done the tests correctly or you could have made a mistake, but I have no way of knowing. So I ask to do my little test.

**Comment by andyonix** [comment]
ill comply with your tests no worries, but, I might have an idea about whats causing it. Borderlands GOTY Enhanced, had a similar issue, and it was fixed by deleting drivers for Virtual displays. And i have a Virtual Display, real quick im going to get rid of it, and seee if that does anything. any variable no matter how insignificant can play a part in an equation.

**Comment by Al12rs** [comment]
I also use spacedesk and I didn't have issues with Nvidia drivers, maybe and is different.

**Comment by andyonix** [comment]
Maybe, im glad im not the only one who uses it, i love it.... especially when watching stuff in different rooms

**Comment by andyonix** [comment]
CRAPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP, not fair

**Comment by andyonix** [comment]
That was the problem, and i use if for monitoring my pc when im bus wityh something else.

**Comment by Al12rs** [comment]
I guess I'm using only the viewer part on my desktop and not the one that casts another screen

**Comment by andyonix** [comment]
do you want me to create a new gist, and eport the logs, or anything....?

**Comment by Al12rs** [comment]
Not really. We can't do much about other software interfering.

**Comment by andyonix** [comment]
Yeah, but now i know why it wasn't working.. im sorry.... i jump to conclusions, without thinking about 1 little piece of tech that extremely useful.... who knew it would happen... Im sorry. Well At least i know RX550, and RX580 don't mix well with Spacedesk, when running Mod Organizer 2.2.2.1. 

But i really do like the features and quality of life update you all did from 2.2.1.0 to 2.2.2.1... impressive as always......
