### ISSUE TITLE
Mods wont sort without internet

### ISSUE THREAD

**Issue by tetoNidan** [ModOrganizer2/modorganizer#1071]
Mods wont sort without internet. Most of the time I will not have internet connection. This makes MO2 unusable and obsolete in every way.

**Comment by LostDragonist** [comment]
That all seems a bit hyperbolic.  

I'm assuming that by "wont sort" you mean that the sort button above the plugin list is not functioning.  Which would make some sense given that LOOT is going to be trying to find updates to the masterlist first.  That said, if MO already has a masterlist, there's no reason it should fail the sort outright if it can't get an update. (I'm not saying this is or is not what it does.  I don't know yet.)

**Comment by LostDragonist** [comment]
I forgot to mention that if you want a workaround, get the real LOOT and run it through MO (assuming it doesn't do the same thing for you).  Bam, MO2 is not longer obsolete and unusable in every way.

**Comment by tetoNidan** [comment]
Well it might be a bit hyperbolic but when you dont have reliable connection to the internet and you get 

[info] Attempting to create a game handle with game path "C:/home/took/.steam/steam/steamapps/common/Fallout 4" and local path "C:/users/steamuser/Local Settings/Application Data/ModOrganizer/Fallout4/profiles/Default"
[info] Initialising load order data for game of type 4 at: C:/home/took/.steam/steam/steamapps/common/Fallout 4
[info] Attempting to open Git repository at: C:\users\steamuser\Local Settings\Application Data\LOOT\Fallout4
[info] Setting URL for remote origin to https://github.com/loot/fallout4.git
[error] A firewall may be blocking LOOT.
[error] Git operation failed. Details: -1; failed to send request: : libgit2 error
[error] Loot failed. Exit code was: 1

And bam you cant use it!

**Comment by LostDragonist** [comment]
You don't need to compile LOOT to use it.  Just... download it and use it.  https://github.com/loot/loot/releases/tag/0.15.1

It looks like it has the same issue unless you go to the LOOT settings and disable the "update masterlist before sorting" option.  I wonder if that means the issue actually is with LOOT and we're just using a more updated version than Vortex...?  Eh, either way, it seems like something we should be able to do something about.

**Comment by isanae** [comment]
`MainWindow::on_bossButton_clicked()` could check for offline mode and force `m_DidUpdateMasterList` to `true` so it never updates.
