### ISSUE TITLE
Reinstall mod : keeping the meta informations

### ISSUE THREAD

**Issue by Shine753** [ModOrganizer2/modorganizer#1081]
When asking for reinstalling a mod, keep the meta informations that could have been defined by the user :
- nexus ID
- category
- notes
- ...
instad of just clearing them.

**Comment by isanae** [comment]
We already do that.

**Comment by Shine753** [comment]
Well... then it's not a feature requets but a bug. Each time I reinstalled a mod, all the metas were gone.

**Comment by isanae** [comment]
How do you reinstall it? Right-click, "Reinstall mod"?

**Comment by Shine753** [comment]
Yes

**Comment by Al12rs** [comment]
the code to keep that stuff is definitely there so I guess we need to test it to see if we can reproduce.

**Comment by Shine753** [comment]
Don't spend time to reproduce. I will do it again on my side and will give you a test scenario.

**Comment by Shine753** [comment]
Badly I uninstalled and reinstalled everything before I posted my comment, as I though MO2 didn't handle the feature. And now, I can't reproduce it... Well, let's say for the moment that it's ok, and I tell you if I meet the problem again with a non-working scenario.

**Comment by Al12rs** [comment]
You can reopen in case you can reproduce
