### ISSUE TITLE
Mods test : visual indicator

### ISSUE THREAD

**Issue by Shine753** [ModOrganizer2/modorganizer#1089]
Being able to have a visual indicator defined by the user showing mods that are "in test".

**Comment by isanae** [comment]
That's what notes are for.

**Comment by Shine753** [comment]
But... How do you filter on "notes" content to see which mods are "in test" ?

**Comment by Al12rs** [comment]
The text filter also filters the notes column. The text filter also supports and/or expressions: https://github.com/ModOrganizer2/modorganizer/wiki/Mod-Organizer-2-Changelog#improvements

**Comment by Shine753** [comment]
Wow, ok. My fault. It's so low into the screen that I did not see it even searching it everywhere.
If possible, I suggest to put both the text filter and the grouping dropdown menu on the top of the list. As it's a common place to find them.

**Comment by Al12rs** [comment]
It has been at the bottom for like 7 years, changing position would anger users (this was tested).

**Comment by isanae** [comment]
> this was tested

tee-hee

**Comment by Shine753** [comment]
Sure, but guess what... once someone had the idea to completely refresh that user interface of windows 3.1 to make windows 95. People were angry. people still use massively windows :)

But this is not a big deal, we have the solution not to angry 7-years-users and make unhappy users happy : just duplicate these item on the top of the list :)

But I will live without this :) This is the best and cleverly designed ever MOD organiser I've seen, and it deserve the best polish and participation by its users. The venerable and powerful Wrye Bash looks like a dinosaur beside it.
