### ISSUE TITLE
Maintain some ESP dependencies is loading order

### ISSUE THREAD

**Issue by Shine753** [ModOrganizer2/modorganizer#1090]
Being able to keep some .esp dependencies defined by the user, to ALWAYS have some .esp loaded after some others, even if ordered by LOOT. So the root esp can be ordered by LOOT, but the dependant ones must follow the "After" rule whatever LOOT decides.

And being able to see these dependant files into the ESP list (some sort of visual, and an highlight when selected).

**Comment by Holt59** [comment]
> Being able to keep some .esp dependencies defined by the user, to ALWAYS have some .esp loaded after some others, even if ordered by LOOT. So the root esp can be ordered by LOOT, but the dependant ones must follow the "After" rule whatever LOOT decides.

This can already be done using custom LOOT rules, I don't think we should duplicate features from LOOT in MO2.

**Comment by isanae** [comment]
This is already supported in LOOT with custom rules.

**Comment by Shine753** [comment]
OK, I didn't know that.
How does this have to be done when using Mod organiser 2 ?

**Comment by isanae** [comment]
https://wiki.step-project.com/LOOT/Meta_Rule_Instructions

**Comment by Shine753** [comment]
Thank you.
If I follow these steps https://wiki.step-project.com/LOOT to add rules by installing a searated LOOT program, do I have to make something special into Mod organizer 2 not to confict with the default LOOT engine used when clicking onto the button shown on top of the ESP list into MO2 ?

**Comment by Al12rs** [comment]
Once you set up the rules with Loot standalone, the Mo2 sort button will follow those rules. The sort button is basically like calling loot from command line and telling it to sort immediately.
Duplicating loot features directly in MO2 seems like a waste of effort and we would rather spend time on features that can't be obtained in other ways.

**Comment by Shine753** [comment]
Yes, that's sure. No need to duplicate these untill necessary.
But just to be sure, I never installed LOOT by any way, and MO2 runs fine without it (I suppose it calls the lootcli.exe inside MO2 folder). But if i separately install LOOT as described, how do MO2/LOOTnew know each other so MO2 uses the rules defined in the new isntall of LOOT ?

**Comment by Al12rs** [comment]
Loot keeps it's cached master list and all its rules in a loot folder in appdata. The internal sort button loot uses that folder as well.

**Comment by Shine753** [comment]
Thank you
