### ISSUE TITLE
Batch source file update

### ISSUE THREAD

**Issue by Shine753** [ModOrganizer2/modorganizer#1091]
As it is done in many softwares dealing with lists of source files, when updating a source foldername for a mod that does not find its source file (see #1080 feature request), try to relocate all other mods that do not find their source file and had their source file in the same "old" hierarchy (whether the change occured on the child folder, the root one, or one of its intermediate).

For example, if 3 mods have their sources in :
- C:\MODs\Best of MODs\Oblivion\
- C:\MODs\Good MODs\Oblivion\Gameplay\
- C:\MODs\Others MODs\Oblivion\Textures\

If you move all of these from C:\ to D:\, and update the source location of one mod located in one of these folders, it would try to refresh all the other mods pointing to these folders, but with D:\ instead of C:\

Same thing if you just rename \MODs with \MyMODs

Or if you rename \Gameplay with \GameplayMods, and move all of the folders to D:\MODs folder before updating a path.
In that case it would detect the 2 changes, and try to find the other orphan mods into :
- D:\MODs folder\Best of MODs\Oblivion\
- D:\MODs folder\Good MODs\Oblivion\GameplayMods\
- D:\MODs folder\Others MODs\Oblivion\Textures\

If it can't succeed finding the source with the supposed new path, it does not change it of course.
If it finds the supposed sources, it shows a resume of supposed changes (source folder - new folder), asking the user if he wants to proceed to update those pathes.

Using a CRC could be easier in the process to help locating missing files in the new hierarchy, but could lead to find many matching files (instead of using just an updated path), leading to a more complex resume shown to the user.

**Comment by isanae** [comment]
> update the source location of one mod 

I don't understand. MO puts all the mods in one folder. If you want to change that folder, you can do so in the Settings. MO cannot (and should not) keep track of the mods folder if you move it manually.

**Comment by Shine753** [comment]
If MO does not find a source file, it should ask the user where it is now (see #1080 feature request) instead of doing nothing, and then forcing to uninstall the mod to reinstalling it.

Then, when one source file is found again, it would be a great idea to suppose that the user does not have just changed the location of one mod, but for example moved its root root folder, or just renamed it.
And then try to apply "what it finds" to other orphan mods that shared part of the old path, not to force the user to relocate individually each orphan mod.
This is a common usage in softwares that deals with such source files.

**Comment by Al12rs** [comment]
With source file @Shine753 is talking about downloads, not mods.
Basically mods have an ini line that contains the path of the archive that was used to install them. 
@Shine753 is proposing a system to automatically search for archives after a folder change.

I'm not a fan. The way mo2 is expected to be used is to have the all the archives in the downloads folder. No custom folder structure.
You are not supposed to change the path and the program does not support that.

**Comment by Al12rs** [comment]
Basically it's an uncommon enough scenario that I don't want to spend time working on just so a handful of users can benefit from it. Most users don't even know Mo2 keeps a path to the download archive.
You are better of writing a small script that updates the ini files for you with the correct path.

**Comment by Holt59** [comment]
I'm with @Al12rs, I don't think making it "automatic" is worth it. This could easily be implemented as a tool plugin though.

**Comment by Shine753** [comment]
No, I'm talking about mods, not a download url. I'm talking about the source file that is asked for when you try to reinstall a mod but you have moved the zip file elsewhere since the install.

I don't agree with you. Any user that tries to reinstall a mod after have changed its name, or organised them into subfolders, know that MO2 keeps these pathes.
And if this was so uncommon, their would not be so many commercial softwares that implement this.

But I also can understand that you don't want to spend time on this.
If I find some time to configure a development environment and understand the spirit of the MO2 code, I will try to implement and propose this.

**Comment by Al12rs** [comment]
I was also talking about the archive paths, not the download url.
What you call source files we call downloads or archives.

**Comment by Holt59** [comment]
> I don't agree with you. Any user that tries to reinstall a mod after have changed its name, or organised them into subfolders, know that MO2 keeps these pathes.

Well, the vast majority of MO2 users use the standard MO2 download locations, so this is not an issue for them. Changing the standard MO2 download locations can easily be done.

> And if this was so uncommon, their would not be so many commercial softwares that implement this.

Using an external download folder is not the *standard* way of using MO2, so it is hard to support features for non-standard way. Installing mods "manually" is required in very few cases, and even when you don't have a "Download with Vorex" on NMM, you can still put the downloaded archive in MO2 downloads folder.

**Comment by Shine753** [comment]
Well, I understand what you say, but let me explain some aspects of my point of view.
I suggest you to read me to the end before reacting, as these comments are cumulative, and one point can find part of a solution in the next point, and does not reflect alone the whole picture that was the reason of this feature request.
Perhaps I missed someting, in that case please don't hesitate to correct me.

1. I'm used (and it's a good usage) to organise my files on my computer how they are supposed to be organised, and not the way the softwares tell me to do or how they expect it to be to work.

For my game mods for example, I have :
- a folder for my "to keep" mods, into a folder dedicated for game files (that is backuped)
- a folder for my "to test" mods (that is not backuped)
- a folder for my "in test session" mods (that is backuped less often than the main one)

And I don't have to be forced to put them into any software folder because this is the way it works. 
And I don't have to be forced to put a software in my games files neither.

Forcing people to dispatch their files all around their hardisk depending on the software they use (and they can use more than one for the same purpose) is not a good way to do.
As forcing people to put all their files into a single folder.
Well, this is how it works for MO2, ok, but my though is despite everything in MO2 is cleverly designed, this aspect has a flaw.
I mean, do you expect a development sofware to force you to have ALL your source files into the same and unique folder, and never move or change a folder or file name outside of it ? I guess no.

In addition, I don't want to copy all my "more than 20GB" of mods twice to satisfy the need of some software.
And I'm not feeling concerned if the vast majority of users don't organise their files or don't do backups. This is their problem. Or perhaps they do so because they don't have the choice... who knows... :)

For me, a software have to provide a default and simple way to work, and be smart enough to adjust its behaviour to users habits. As it actually deal with these source files, MO2 imposes bad habits to the user without letting their a choice. With this feature I request, it would match the standards and be able to adjust its working process to users who have good habits.

2. You say that the MO2 download folder can be configured in the settings. OK, but assuming its name has some kind of importance, or not, I don't want to mix my "to keep" mods, with my 'to test one day perhaps" mods, and my "downloaded I don't know why" mods.

3. When I install a mod, if I like it, I move it into the "to keep" mods folder. Sometimes I rename it. Sometimes I reorganise the inner structure of these folders to match the growing file number inside them. And sometimes I move the whole thing elsewhere because of missing disk space.
Doing that, MO2 looses the link with one or many of the mod sources archives, and can't reinstall them.

On my point of view, such a software has to keep the things clean.
So, as any decent (image cataloging, video editing, development environment, UML designing software, ...) do, when a link to a file is broken :
- it says it to the user
- it ask him to locate the missing file
- and it updates/propose an update for the whole project accordingly to this new place, without asking/waiting for the user to do it on each broken file.

4. You say that "Using an external download folder is not the standard way of using MO2".
Well, ok, MO2 has a standard way to work that is not usual. Perhaps this have to be reworked.
But... I know this can be a lot of work.
With this feature request, it does not have to change its way of working, but can meet the standards.

Do we meet on some points ?

**Comment by Al12rs** [comment]
Then the problem isn't updating the path of the origin archive but rather the fact that the user has to work with a single download folder location.
So to resolve the problem we should allow the user to define more downloads locations.
There are several issues with that, like how to decide where to place new downloads, if there is a default location then the user is expected to be moving downloads and then we need to allow users to do that from within Mo2, then we need to update the paths etc.
So not an easy thing to implement but it's a better solution than to randomly iterate arbitrarily sized folders calculating hashes on all files to try to find some lost archive.
In any case what @Holt59 was saying is that the vast majority of our users don't feel the need to organize the downloads, so this feature would still only be for only a minority of users, making it less worth spending time on compared to other stuff that users are asking for.

I personally think that having multiple folders is a bad idea for the downloads tab as it generates a lot of complexity for both the user and the application that isn't needed. The organization problem could be solved in my opinion by improving how the downloads tab presents the downloads, allowing users to better organize their view from within the manager. 
I don't see you or anyone else asking to allow you to move the mods folders themselves from the standard location for better organization, so my take is that it's a matter of the downloads tab not providing enough organization facilities to users.

**Comment by Holt59** [comment]
Well, you have valid point, but it's still outside of MO2 philosophy. 

For instance, you separate "To Keep", "To Test", "In Test Session", but those have nothing to do with your actual download folders... MO2 has a whole profile / instance stuff to handle this kind of things: you can have different mod installed in each instance, and you can have different mod activated in each profile, so asking MO2 to do something 100% different because you don't want to use the MO2 built-in feature is... ironic.

>  So, as any decent (image cataloging, video editing, development environment, UML designing software, ...) do, when a link to a file is broken :

All those are project-based... Sure if you open a project from a different location, then it will find the other files because those are listed in the project. If you open a "recent file" in any software, and it does not find it, it would most likely ask you to remove it from the "recent" file, not to locate it, and it certainly won't update the other "recent" files to point to similar location. 

MO2 is like a single project (per instance): you have a single download folder. If you move it, you can tell MO2 were it has been. MO2 does not force you to have anything inside MO2 folder, you can specify the locations of every folder (mods, downloads, profiles, etc.). You can have difference instances with different download folders if you need to, I personally don't see the point.

Your download folder does not have to be located anywhere near your actual mod folder... If you lack space on your disk, then you can move the download folder somewhere else, that's not an issue.

**Comment by Shine753** [comment]
Then why not :
- defining a download folder (already done)
- allow the user to add one or more custom locations for his mods
- track each CRC of each source file in the meta.ini when installed 
- when a link is broken, try to find again the file by its crc in one of these folders and possible subfolders

This sounds simple to code, user friendly, does not need any file moving/managing within MO2, and does not change current users habits.

I ask this for your opinion about the idea, in case I decide to take charge of this modification, for not developping it for nothing.

**Comment by Holt59** [comment]
Computing the CRC of huge archives is not cheap, even you only do it at installation, it's a bad user-experience. Finding files by CRC in every folders specified by the user is probably even worse since you would need compute the CRC of each file in every folders...

If you really want something like that, make a tool plugin for it: just ask the user for a list of possible locations (you can cache them), and allow user to do a kind of "refresh" source where the plugin go through the list of installed mods and when the source does not exist anymore, try to look it in the list of folders you specified.

**Comment by Shine753** [comment]
Yes I know the resources that a CC can take. But there are solutions. I'll think about that.
Do plugins can alter the core behaviour of MO2, or are they limited to some menus/buttons added ?
