### ISSUE TITLE
Downloading and merging patches for mods ruins versioning

### ISSUE THREAD

**Issue by Sorbe** [ModOrganizer2/modorganizer#1095]
If you have a mod "x" and download/merge a patch "y", the resulting version for x is the version of y.

In effect, one mod is overwriting the other and destroying version information.  This makes it quite difficult to tell if your downloads have pending updates on Nexus.  In this respect, Vortex was far more trustworthy and much easier to get new updates from Nexus with.

This is highly ironic since one of the chief benefits of MO2 is the virtualization which prevents mods from overwriting each other since they have never destructively copied to the game directory.

Suggestion: Keep all mods, their patches, and their version numbers separate so you can tell if there are new updates pending.  This should have always worked this way for merged mods+patches.

**Comment by LostDragonist** [comment]
![image](https://user-images.githubusercontent.com/7862539/83316230-90f26000-a1d9-11ea-975e-379a3d3333a6.png)
Click the rename button instead and make it a separate mod.  What you want to happen has always been an option.
