### ISSUE TITLE
In conflict image compare, adding shortcut to easily compare

### ISSUE THREAD

**Issue by Shine753** [ModOrganizer2/modorganizer#1097]
When a file is in conflict, the 2 files in conflict can be compared, switching from one to the other by clicking on 2 arrows at the top of the windows.
Would it be possible to add some kind of shortcut not to have to touch the mouse.
Something like using the left/right key (but I understand that these are already used for something else). Perhaps with a modifier key (Ctrl?) added to the left/tight arrown ?

**Comment by Al12rs** [comment]
Duplicate of #1029
