### ISSUE TITLE
Making separators selectable to activate/deactivate

### ISSUE THREAD

**Issue by Smashpatch** [ModOrganizer2/modorganizer#1099]
**Suggestion:** I'm not sure if this has already been suggested in item **#464**. It reads, "_- Make separators not being hidden by the enabled filter._" I'm not clear on what that's saying, but it might be what I'm looking for and this post may clear that suggestion up, because I find the wording a bit confusing.

When I set the filter to **Active**, my Separators disappear because we can't activate them. I use the section names (in Separators) the _STEP Guide_ uses to keep all the mods organized in the same way, but I don't mod with all of those active. I use a different profile for modding with just the basics and it leaves me with many unactivated mods in the way of what I need to focus on.

If we could select separators in the left pane like mods, it would be perfect because there are entire sections (between the separators I use, I mean) of mods in my modding profile that have nothing activated, so I don't want every divider being displayed when filtering only active mods.

I think that if collapsible separators are implemented as per combined issue(s) **#464**, the checkbox to activate each separator  would be separate from the **[+]** or whatever control used to collapse the section. This way, users could both easily collapse sections and hide the separator (using the **Active** filter) if desired.

Though if collapsible separators are implemented, a way to activate/deactivate every mod under that separator to the next separator (or bottom of the list) would come in handy.

I'd also like to second suggestion **#983** for separators to be added to the downloads screen and, of course, it would be great if they too would offer collapsible sections of files (always leaving each separator visible, I suppose) between separators or the end of the files.

Thanks for listening and for all the effort undertaken on MO2.

Apologies, I can't see how to add the tags: enhancement | Feature Request | help wanted |  UI

**Comment by LostDragonist** [comment]
>When I set the filter to Active, my Separators disappear because we can't activate them. I use the section names (in Separators) the STEP Guide uses to keep all the mods organized in the same way, but I don't mod with all of those active. I use a different profile for modding with just the basics and it leaves me with many unactivated mods in the way of what I need to focus on.

In the bottom-right of the filter pane, there's a little drop-down that probably says "filter separators" right now.  You can set that to "show separators" to force separators to always be shown.

**Comment by Smashpatch** [comment]
> In the bottom-right of the filter pane, there's a little drop-down that probably says "filter separators" right now. You can set that to "show separators" to force separators to always be shown.

Oh, thanks very much for pointing that out. It works fine, other than that it's displaying multiple separators stacked on top of one another because of no mods between those separators being active. Small thing and my suggestion would fix that allowing us to activate only certain separators. Or perhaps MO2 could have logic to check the mods between separators and if none are active below a given separator, don't display that particular one.

If that were implemented, and a checkbox control was added to each separator, the checkbox could be used to confirm "[De-]Activate all mods under this separator?" to give us easy ways to enable/disable a section of mods, which would also be handy if the separators become collapsible.

Thanks again.

**Comment by Al12rs** [comment]
tracking this in #627
