### ISSUE TITLE
[Enhancement] Allow "Ignore missing data" context menu to apply to all selected mods

### ISSUE THREAD

**Issue by fireundubh** [Modorganizer2/modorganizer#11]
### Steps to Reproduce

1. Ctrl+Click or Shift+Click more than one empty mods.
2. Right-click the selection.
3. Click the "Ignore missing data" context menu item.

### Result

The "ignore missing data" feature works on only the last empty mod in the selection.

**Comment by Silarn** [comment]
It probably only works for the mod you right-clicked on. I can put this in as an enhancement.

**Comment by Al12rs** [comment]
The right-click menù in general is only referred to the mod that was right-clicked on, if other mods are selected the menù disregards them.
It would be nice to support multiple selection context menù, it would need a bit of new code though.

**Comment by Al12rs** [comment]
This has been implemented by @LostDragonist here: https://github.com/Modorganizer2/modorganizer/commit/f20a1f6a849510438ca5c9abe8fdac1dada263d2
