### ISSUE TITLE
Impossible to delete the NexusID from the mods list

### ISSUE THREAD

**Issue by Shine753** [ModOrganizer2/modorganizer#1107]
When I try to delete the nexusID from the list (Suppr or Delete key), it comes back after validation.
Same thing if I try from from mod detailed panel.

**Comment by isanae** [comment]
Can you clarify? What ID and where?

**Comment by Shine753** [comment]
Well... the Nexus ID, the one visible in the MOD list and on the Nexus page in the mod properties, the number that allows to go to the Nexus page of the mod when set.

When set, then clicked into the list to empty it, it comes back when you validate the field.
When set, then emptied within the appropriate field into the property panel, same thing, it comes back.

**Comment by Al12rs** [comment]
You need to write 0 to reset it. Deleting the contents of the field makes qt think that you wanted to abort the operation. The new value is reported to be what it was before instead of an empty string or something like that. So just use 0

**Comment by Shine753** [comment]
OK Working :)
But not intuitive nor usual.
