### ISSUE TITLE
Slow Premium download speeds (800Kbps - Vortex speeds are fine)

### ISSUE THREAD

**Issue by MisterLahey** [ModOrganizer2/modorganizer#1116]
## The problem:
Download speeds are capped at 800-850Kbps despite me being a premium user, and having premium servers selected.

## To Reproduce:

1. Go to mod page on Nexus Mods, in this case it is NMC's Texture Pack for Fallout NV
2. Click on Download with Mod Manager
3. Proceed to MO2 to watch slow speeds.

## Environment:

* Mod Organizer Version that exhibits the issue: v2.3.0 Alpha 9
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 10 home 64bit

## Details:
No matter what I do I cannot get premium speeds while I have premium servers set as my preferences. Both in the program and on the website. I have tried reinstalling the base program, tried installing the latest dev build, deleting everything under [SERVERS] in the ModOrganizer.ini, Disconnecting my account from MO2 and reconnecting it. Tried changing my password to refresh the API, And everything else I have seen suggested. MO2 log shows I am logged in as premium. Keep in mind, I have restarted my PC in between all of these changes, yet my speed still peaks at 800Kbps. I am currently running on 1 gigabit fiber optic internet, download speed is currently 458mbps down, and 360mbps up.

NOTE: Vortex speeds are fine. No caps.

[MO2 DL speed picture](https://gyazo.com/8cd3fa8203f46a2275566512bc8f983c)
[Account Status Picture](https://gyazo.com/0f40ffc5eef4edd147948d1627d20c71)
[Server Selection Picture](https://gyazo.com/69a2659e018bad8aa295c31ba567b2b9)

## Link to Mod Organizer logs:

[MO2 Log](https://pastebin.com/Z1stfqLq)

### USVFS:

[USVFS Log](https://gist.github.com/MisterLahey/74ce9a70236cec600b8ce9f793a9b05d)

NOTE: All of my USVFS Logs look identical to this one.

### MO Interface:

[MO2 Interface GIST](https://gist.github.com/MisterLahey/49e40780ecd5e875dace0e783c519091)

**Comment by Al12rs** [comment]
Did you try leaving the cdn server as preferred? That one is actually the one Vortex uses.
Also what speed do you get with vortex?
What speed to get downloading manually with the browser?

**Comment by MisterLahey** [comment]
> Did you try leaving the cdn server as preferred? That one is actually the one Vortex uses.
> Also what speed do you get with vortex?
> What speed to get downloading manually with the browser?

I swapped back to CDN, still under 1mbps.
Vortex speeds are currently at 5.9 - 6.3Mbps
manual is at the same. bouncing from 5.5 to 6.5

**Comment by LostDragonist** [comment]
The only possible issue the logs show is something to do with Malwarebytes but this would be a pretty unusual symptom.  Vortex and manual downloads use the preferred download location you have selected here: https://www.nexusmods.com/users/myaccount.  You'd want to select the same server in MO for a fair test.

Beyond that, no clue.  MO doesn't have internal speed limits.

**Comment by MisterLahey** [comment]
> The only possible issue the logs show is something to do with Malwarebytes but this would be a pretty unusual symptom. Vortex and manual downloads use the preferred download location you have selected here: https://www.nexusmods.com/users/myaccount. You'd want to select the same server in MO for a fair test.
> 
> Beyond that, no clue. MO doesn't have internal speed limits.
> 
> Edit: I guess the download location would also be different between MO, Vortex, and manual downloads. You might want to look into that. Maybe see if you need to add anti-virus exclusions to the MO download folder or something.

I will give these a try.

**Comment by isanae** [comment]
Any news?

**Comment by Al12rs** [comment]
Closing this for lack of user response. If you do come back, please reopen this issue.
