### ISSUE TITLE
Loot not recognizing Mo2 plugins.

### ISSUE THREAD

**Issue by BurnedMan** [ModOrganizer2/modorganizer#1140]
When i launch loot it opens perfectly fine, only problem is it doesn't display the 49 mods i have installed just the base game, dlc, and update esm.

And if i hit the sort button in the plugins tab it tells me this 

**Plugin 'ACloserLook.esp' is in the load order file 'E:\Modding\Mo2\profiles\Default\loadorder.txt' but does not exist on the filesystem in 'D:\steam\steamapps\common\Skyrim Special Edition\Data'.**

and goes on for each mod.

How do i fix this?

**Comment by LostDragonist** [comment]
Upload your log files here. Follow these steps:

1) Go in the Settings, Diagnostics tab, set Log Level to Debug.
2) Restart MO.
3) Use the "Open Folders" button to open the logs folder.
4) Recreate your problem.
5) Close MO.
6) Drop mo_interface.log and the most recent usvfs log here. You might need to compress them.

Note: When you're done with fixing the problem, go set the Log Level back to Info.

![](https://cdn.discordapp.com/attachments/458597400638914563/617049541350260794/openlogs.png)

**Comment by BurnedMan** [comment]
where exactly do you want me to drop those files?

**Comment by LostDragonist** [comment]
Here, in Github.  "Attach files by dragging & dropping, selecting or pasting them."

**Comment by BurnedMan** [comment]
i have no clue what happened, but now it no longer shows me those errors and the sort button actually sorted my plugins. but executable version of Loot still doesn't pick them up. 

but here are the files anyway
[Files you asked for.zip](https://github.com/ModOrganizer2/modorganizer/files/4808649/Files.you.asked.for.zip)

**Comment by LostDragonist** [comment]
If you're having problems with the real version of LOOT, you need to post logs that have you using the real version of LOOT.  The only thing I can really see going wrong at the moment is McAfee doing something as it tends to dislike MO2.

**Comment by BurnedMan** [comment]
well as i said in the original post, i initially had no problems until i moved the "ModOrganizer" file from my C: drive now loot doesn't act right and the sort button wasn't originally working after the move either

**Comment by BurnedMan** [comment]
i have no clue what you did but you fixed it....thank you
