### ISSUE TITLE
Skyrim Special Edition won't launch with an empty plugins.txt file

### ISSUE THREAD

**Issue by Elaura1970** [ModOrganizer2/modorganizer#1143]
After attempting to revert to a vanilla install and a default profile in MO2, I have discovered that the SSE Launcher works fine, but selecting the auto generated SSE executable in MO2 doesn't work. The message I get in the Log section is "Mod Organizer 2 - SSE/profiles/Default/plugins.txt empty"

I have entered the game using the launcher and saved, but the plugins.txt file still won't populate. Of course, I have backed up the file, I just wanted to let you know.

EDIT: I was mislead by the log message. It doesn't appear to have anything to do with the plugin.txt file. The problem is somewhere in the BethINI edits. The SSE executable works fine using the default inis It's only after using BethINI that the Launcher works and the SSE executable doesn't. 

Oddly, the executable works outside of MO2 even with the edits.

**Comment by PizingoSayNo** [comment]
Pizingo has the same problem. Pizingo was wondering if there was a way to load mods _without_ using the mod organizer.
