### ISSUE TITLE
Error in MO2

### ISSUE THREAD

**Issue by Roger1868** [ModOrganizer2/modorganizer#1144]
I previously downloaded 95 mods from Nexus.  Today I tried a mod download and was disconnected from Nexus with the following error message: SSL SOCKETS ARE NOT SUPPORTED ON THIS PLATFORM.

I tried everything and still cannot connect to Nexus.  Please advise what I should do to fix this error.

**Comment by isanae** [comment]
You might be missing files in MO's installation folder. Make sure you add an exclusion for the folder in your antivirus and try reinstalling MO.

**Comment by Roger1868** [comment]
Thanks for your help.  I reinstalled MO2 and the error message disappeared.
