### ISSUE TITLE
MO2 launch fails "LoadLibrary failed with error 87..."

### ISSUE THREAD

**Issue by Oxika95** [ModOrganizer2/modorganizer#1145]
When attempting to launch MO2 I get "LoadLibrary failed with error 87: The parameter is incorrect."

1. Fresh install of MO2.
2. Attempt to launch the MO2
3. Error

Environment:
* Mod Organizer Version that exhibits the issue: Mod Organizer 2 (Installer Version) v2.2.2.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro Version 2004 (OS Build 19041.329)

Details:
I attempted to troubleshoot with help from LostDragonist on the Discord server. Ultimately no solution was found. Linked is a google doc with the aforementioned discord conversation. 
https://docs.google.com/document/d/1oy5izXSc9vy-aHm30bzzAWHtH2fqsOLV029IZohvCmE/edit?usp=sharing

Link to Mod Organizer logs:
Irretrievable, program cannot be accessed.

**Comment by isanae** [comment]
This error is not from MO, as far as I can tell. Googling it shows a bunch of people having similar issues, some have fixed it by updating or reinstalling AMD drivers or utilities.

**Comment by Oxika95** [comment]
What was the wording of your Google search as I haven't found anything related to AMD and have already done a complete windows reinstall including AMD drivers in an attempt to fix this issue. I appreciate your response thank you. Will continue to search.

**Comment by isanae** [comment]
I searched for `LoadLibrary failed with error 87`.

**Comment by Oxika95** [comment]
I also searched for for this repeated times. I appreciate you sharing though because searching error 87 in conjunction with AMD has yielded more relevant results.
