### ISSUE TITLE
Transifex matter

### ISSUE THREAD

**Issue by GoogleBeEvil** [ModOrganizer2/modorganizer#1153]
I used to translate mo2 to my native lang on transifex about 1 year ago.Due to busy work I suspend the translate ， now I want continue it and find all my edit history were cleared，the only history record of the texts I had edited  is Silarnid(maybe MO2 team leader?) about 7 monthes ago. So was there  retreated matters on transifex？

**Comment by isanae** [comment]
We changed the Transifex team for MO, I'm not sure how that affected edit history. The new project is at https://www.transifex.com/mod-organizer-2-team/mod-organizer-2/dashboard. You're always welcome to come chat with us on the discord in the #translations channel if you're interested in translation.
