### ISSUE TITLE
Create hard links in game data folder to remove need for vfs when playing and not modifiing mods

### ISSUE THREAD

**Issue by CzBuCHi** [ModOrganizer2/modorganizer#1157]
**Is your feature request related to a problem? Please describe.**
I dont see any reason for having mod organizer up and running when playing the game and do not mess with mods.
Also VFS is (at least for me) not working for wrye bash ...

**Describe the solution you'd like**
Add "Inject to game" and "Withdraw from game" buttons that would execute this code:

"Inject to game":  
1. loads active mods from current profile
2. create dictionary of mod files: (mod with higher priority 'wins')
  - key: absolute path into game data folder, where mod file should be
  - value: absolute path to mo2 mods folder where file actually is
3. generate ntfs hard links for each dictionary key pointing to its value (aka: `mklink /h key value`)
  - when target file already exists it need to be renamed so it isnt overriden and also not loaded by game
4. save dictionary keys to state file

"Withdraw from game"; 
1. delete all links stored in state file and then delete state file itself
2. restore all renamed files from inject 3.

**Describe alternatives you've considered**
I wrote this tool in c#: ([source code here](https://github.com/CzBuCHi/ModOrganizerLinkGenerator/tree/master)) that basically do as described above and it "just works", but it has also its drawbacks:
- override folder do not work: new files are saved into game data directory, existing files are overriden
- when injected mo2 will show all mods twice (one normaly and second as "unmanaged")

**Additional context**
This solution will also work with any other tools (wrye bash, bodyslide, etc.) that needs to read/modify mod files.

note: loot needs to be called from mo2 so mods are correctly sorted before injecting

note2: does anybody have experience with [dokany](https://github.com/dokan-dev/dokany)? - because it looks like vfs alternative, that may also "just work"

**Comment by isanae** [comment]
If you're having problems with usvfs and wrye bash, come by the discord and we'll check it out.

I'm closing this because there's basically zero chances of it ever happening. Go with Vortex if you want hard links.

**Comment by AnyOldName3** [comment]
It'd be a pretty easy Python plugin if you wanted to make it yourself.

**Comment by CzBuCHi** [comment]
> It'd be a pretty easy Python plugin if you wanted to make it yourself.

i looked at python code once and it has wierd syntax (im used to see braces & semicolons everywhere) so i will continue to use my c# solution ...
