### ISSUE TITLE
Pluggin problems

### ISSUE THREAD

**Issue by shodin5** [ModOrganizer2/modorganizer#1163]
So I decided to finally try modding Skyrim SE & I ended up with a little problem... The plugins go straight to old Skyrim instead of going into Skyrim SE... I can't seem to find a fix for this... I also seem to be unable to redirect the plugin location at this time. Can you please help?

**Comment by Holt59** [comment]
What do you mean by *go straight to old Skyrim*? MO does not copy plugins into the data folder, so unless you're looking through the virtual explorer (run from MO2), the files you're seeing in the old Skyrim might not be from MO2.

**Comment by Qudix** [comment]
Perhaps when creating an instance they selected Skyrim instead of Skyrim Special Edition?
