### ISSUE TITLE
usvfs_proxy_x86 is detected as a trojan by Windows Defender

### ISSUE THREAD

**Issue by HowellBP** [ModOrganizer2/modorganizer#1166]
## The problem:
Windows Defender in Windows 10 build 18363 sees usvfs proxy as a trojan. 

## To Reproduce:

1. Install ModOrganizer 2 with Windows Defender active

## Environment:

* MO2 2.3.0rc2
* MO2 2.3.0rc1
* Windows 10 build 18363
* Windows Defender Antimalware Client Version: 4.18.2006.10

## Details:
usvfs_proxy_x86.exe was detected as trojan Trojan:Win32/Wacatac.C!ml by Windows Defender.
https://imgur.com/BhCiqNJ

Unless this is a legitimate threat, it may require either a code change or submission of the file to Microsoft's antimalware database to be unflagged.

## Link to Mod Organizer logs:
N/A, happened during installation

### USVFS:
N/A, happened during installation

### MO Interface:
N/A, happened during installation

**Comment by Al12rs** [comment]
Usvfs will be flagged by antiviruses randomly due to the fact that it injects into running processes and child processes like some malware do. Can't do much about it. It's a false positive. 
Btw update your windows version ;)
