### ISSUE TITLE
Zip file extaction fails on network drives

### ISSUE THREAD

**Issue by mdavis199** [ModOrganizer2/modorganizer#1167]
In v2.3.0 RC1 and in v2.3.0 RC2, I'm unable to install downloads that are on network drives.  In previous versions, I had no problem.

## My Downloads Path:
My Downloads path is: `\\nickel\games\Skyrim\ModArchives\Mods\4.Mods`.  

This works in earlier versions of MO2.

## In RC1 and RC2:
When trying to install a mod, it reports: `None of the available installer plugins were able to handle that archive`

## Tried mapping folder to drive:
Mapped z:\ to `\\nickel\games\Skyrim\ModArchives\Mods\4.Mods`

Set Downloads path to: `Z:/`.  Downloads panel shows archives correctly.

When trying to install a mod, it reports: `exists \\?\Z:\`

## Tried mapping a higher level folder to drive:
Mapped z:\ to `\\nickel\games\Skyrim\ModArchives\Mods`.  

Set Downloads path to `Z:/4.Mods`.  Downloads panel shows archives correctly.

Was able to install a zipped mod using this drive mapping.

**Comment by Holt59** [comment]
Could you upload the debug log? 

> Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

**Comment by isanae** [comment]
Alpha 9 is the last working version.

**Comment by isanae** [comment]
https://github.com/ModOrganizer2/modorganizer-archive/commit/0a8a18a20e9b4b73f97430001ae87bfa6a852712#diff-21ec12b28da552c55a7a086581d768b8 would be the problem, it's eventually moved to `IO::make_path()`. It blindly prepends `\\?\` to paths, which is invalid for UNCs.

**Comment by Holt59** [comment]
> 
> 
> [ModOrganizer2/modorganizer-archive@0a8a18a#diff-21ec12b28da552c55a7a086581d768b8](https://github.com/ModOrganizer2/modorganizer-archive/commit/0a8a18a20e9b4b73f97430001ae87bfa6a852712#diff-21ec12b28da552c55a7a086581d768b8) would be the problem, it's eventually moved to `IO::make_path()`. It blindly prepends `\\?\` to paths, which is invalid for UNCs.

That's also what I think but why would it work in one case and not the other? 🤔 And they are not actually using the UNC path in MO2, but the mounted drive.

**Comment by isanae** [comment]
> My Downloads path is: `\\nickel\games\Skyrim\ModArchives\Mods\4.Mods`.

**Comment by Holt59** [comment]
> 
> 
> > My Downloads path is: `\\nickel\games\Skyrim\ModArchives\Mods\4.Mods`.

Hm, right, I was thinking about the mounted drives version where it does not work in one case (unless I misunderstand the issue). But this should be fixed anyway.

**Comment by mdavis199** [comment]
Here is the log.  I think I may have pasted the wrong network path in my problem report.  The log may show the Download path as `//nickel/games/MyInstall/4.Mods`.  But the problem is the same.   The attached log is when the download path is the plain networked path.   Let me know if you need a log showing the error with mapped drives.

As a side note, if the download path is a mapped drive and the mapped drive is disconnected.  MO2 will refuse to launch.  You have to find MO2 ini file and manually delete the download entry.  

[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/4972953/mo_interface.log)

**Comment by isanae** [comment]
I've fixed the regressions for UNC paths and the root of network drives. I don't plan on an RC3 for this, so it will be released with 2.3.

> if the download path is a mapped drive and the mapped drive is disconnected. MO2 will refuse to launch

This is part of a series of long-standing issues MO has on startup when the paths are invalid.
