### ISSUE TITLE
Support for Mount and Blade 2 Bannerlord

### ISSUE THREAD

**Issue by BaileyLove** [ModOrganizer2/modorganizer#1170]
Right now the only tool for "managing" mods for Mount and Blade 2 is Vortex (previously known as Nexus Mod Manager).
Do I really need to elaborate why Vortex shouldn't even be in the field of mod management? It doesn't manage anything. It creates symlinks, and whenever an official update for the game is released, the mod files get overwritten with vanilla files through those links. And then you can not really "uninstall" the mod, because that will overwrite updated vanilla files with backed up files released in previous patch. So the only way to recover is to uninstall mods and reinstall (verify) a 60 gig game. It's such a pain to use it.

Please, Mount and Blade 2 deserves better tooling. Please.

**Comment by Holt59** [comment]
2.3 is coming out tomorrow, and with it you'll be able to use https://github.com/holt59/modorganizer-basic_games for (at least) basic support.

If you feel the template below, we could have *basic* plugin in no time (this is a template we may use for future game support request).

---

**This template is mostly useful if you want to request support for "basic" games as handled by https://github.com/Holt59/modorganizer-basic_games. If you need support for more complex game, feel free to ignore the template.**

**Please provide the following information for the game (remove the optional lines you do not use):**

- **Name:** Name of the game
- **Short name:** Name of the game in Nexus URL (e.g. skyrimse for Skyrim SE).
- **Nexus ID [optional]:** ID of the game on Nexus (you can usually find this in Nexus URL).
- **Executable:** Name of the main executable for the game (relative to the game folder).
- **Launcher [optional]:** Name of the game launcher (relative to the game folder).
- **Data path:** Path to the data folder of the game (relative to the game folder).
- **Documents path:** Path to folder containing INI files, etc., for the game (usually under "My Games", or the game folder itself).
- **Saves directory [optional]:** Path to the folder containing save games (this default to the path above).
- **Save extension [optional]:** Extension of the saves
- **Steam ID [optional]:** ID of the game on Steam (if the game is on Steam).

**Provide additional details regarding the game that could be required for the plugin.**

**Comment by BaileyLove** [comment]
- Name: Mount & Blade II: Bannerlord
- Short name: mountandblade2bannerlord
- Nexus ID [optional]: can't find it :(
- Executable: bin\Win64_Shipping_Client\Bannerlord.Native.exe
- Launcher [optional]: bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.Launcher.exe
- Data path: Modules
- Documents path: Documents\Mount and Blade II Bannerlord\Configs
- Saves directory [optional]: Documents\Mount and Blade II Bannerlord\Game Saves\Native
- Save extension [optional]: sav
- Steam ID [optional]: 261550

**Details**.
**Data path**: the game data consists of "modules" - folders in Modules. Mods are usually shipped as separate modules, that go into Modules. But some modules overwrite vanilla data. Vanilla data is in modules Native, Sandbox, SandboxCore, StoryMode, CustomBattle. The bulk of data is in Native.
**Executables**: there are Bannerlord.exe, Bannerlord.Native.exe and Bannerlord_BE.exe in bin\Win64_Shipping_Client, but launching them directly launches the game vanilla (without mods). I suspect the Launcher reads $(Documents path)/LauncherData.xml and passes modules listed in that file to Bannerlord.Native.exe as arguments. In task manager' details tab the only game' process listed is TaleWorlds.MountAndBlade.Launcher.exe.
**Steam ID**: The game is also available on Epic Store.

**Comment by Holt59** [comment]
>  Executables: there are Bannerlord.exe, Bannerlord.Native.exe and Bannerlord_BE.exe in bin\Win64_Shipping_Client, but launching them directly launches the game vanilla (without mods). I suspect the Launcher reads $(Documents path)/LauncherData.xml and passes modules listed in that file to Bannerlord.Native.exe as arguments. In task manager' details tab the only game' process listed is TaleWorlds.MountAndBlade.Launcher.exe.

So you mean you have to register the mod / modules in `LauncherData.xml`?

**Comment by Holt59** [comment]
I've added **UNTESTED** support for Mount & Blade II: Bannerlord to https://github.com/holt59/modorganizer-basic_games. You can test it right now with pre-release 2.3 RC 2 (https://github.com/ModOrganizer2/modorganizer/releases/tag/v2.3.0rc2) or wait 'til tomorrow for official release.

This is 100% untested as I don't own M&B, so if you experience issue, please come by the Discord server so we can fix them (if it is indeed possible... ).

**Comment by BaileyLove** [comment]
M&B comes with its own launcher, where you can sort mods manually, modded launcher that has some fixes and also another mod tool that also allows mod sorting but also checks mod deps and reports to the user if there are dep issues in their load queue.

We still can install mods through MO2, putting them into Modules and then just launch those tools to launch the game through the launcher. That way the game directory stays unpolluted and whenever an update is released we won't have to verify/reinstall everything.

Gonna test it right now and report things.

**Comment by BaileyLove** [comment]
Works like a charm. As usual, one only have to pay attention to how a mod archive is packed so there wouldn't be paths like "Modules/Modules/ModName".

Thank you man. Finally this game is in order.

**Comment by Holt59** [comment]
> Works like a charm. As usual, one only have to pay attention to how a mod archive is packed so there wouldn't be paths like "Modules/Modules/ModName".

It might be possible to fix this. If there is an easy way to detect the layout of a Module, we can check those so that the quick-installer can take care of the installation instead of the manual one. 

I saw that a lots of mods had a `SubModule.xml` file, this can be checked for. Althgouh, I did not find mods that overrides "Native" data so I cannot say if these would.

**Comment by BaileyLove** [comment]
This mod overwrites files in "Native" module: [Full Body Sliders](https://www.nexusmods.com/mountandblade2bannerlord/mods/197?tab=description) 

Indeed, this one doesn't have SubModule.xml in it and it kinda makes sense, because that file is used to describe mod's dependencies and "Native" is essentially base files and everything depend on them, and this mod doesn't add new stuff, but modifies existing stuff.

Regardless, checking for the presence of SubModule.xml sounds like a good idea. Even if it's gonna be a miss with ones that overwrite stuff, it's gonna be mostly a hit. Except maybe for mods that are shipping several root folders with several SubModule.xml files in each root folder. Maybe that can be checked too, and reported to the user that they must choose the right folder themselves.

**Comment by Holt59** [comment]
> Regardless, checking for the presence of SubModule.xml sounds like a good idea. Even if it's gonna be a miss with ones that overwrite stuff, it's gonna be mostly a hit. Except maybe for mods that are shipping several root folders with several SubModule.xml files in each root folder. Maybe that can be checked too, and reported to the user that they must choose the right folder themselves.

You mean if a "mod" has multiple submodules, then you might have to choose which submodules you want? Do you have any example of this?

If a mod is shipping multiple root folders, then this would probably trigger the BAIN installer.

**Comment by BaileyLove** [comment]
Haven't seen it yet, but I think that is a possibility.
We had such mods for Sky and Fall for sure.

**Comment by Holt59** [comment]
I'll try to implement something, we'll see how it goes. The one modifying Native have a `Native` folder so I guess I can either look for:

- One of these folders: Native, Sandbox, SandboxCore, StoryMode, CustomBattle.
- A folder with a `SubModule.xml` inside.

**Comment by Holt59** [comment]
@BaileyLove Okay, I've added the feature, you can "update" the `basic_games` plugin (redownload and erase everything... ).

The update is available here https://github.com/holt59/modorganizer-basic_games and will soon be here https://github.com/ModOrganizer2/modorganizer-basic_games.

I tested with a fake M&B installation and the most popular plugins on Nexus, and it worked for all of them except (it does not recognize "Fixed Launcher", but that's the expected behavior).

**Comment by BaileyLove** [comment]
Git cloned your repo into plugins. Tested with Community Patch. Works. 💯
