### ISSUE TITLE
Found zlib Compressed

### ISSUE THREAD

**Issue by Atoro10** [ModOrganizer2/modorganizer#1179]
Mod organizer 2 told me to upload my save here. It has been on my saves for somewhile but I don't know if it is an issue.

https://workupload.com/file/4ugBQgQdvtV

**Comment by isanae** [comment]
Can you explain what your problem is?

**Comment by Atoro10** [comment]
I don't know if ther is a problem MO2 told me to simply post it here and I did since it might be relevant to another problem I've had in the past.

I've had a problem with my game using the wrong compression which was then solved by uicompression=1/0
I don't know what caused it and since client gave a warning I was sondering if it is because of some bigger issue, perhaps I've messed something up.

**Comment by isanae** [comment]
This is not a problem with MO.
