### ISSUE TITLE
Bundle installer only installs first installer in a bundle

### ISSUE THREAD

**Issue by AnyOldName3** [ModOrganizer2/modorganizer#1185]
## The problem:
According to a MO2 user testing the experimental OMOD installer, if multiple OMODs are in the same zip file, only the first will be installed. This involves the bundle installer and from their description, it didn't sound to me like the OMOD installer was involved in the issue.

## To Reproduce:

1. Put multiple FOMODs/OMODs/whatever in a zip file (the user didn't link a pre-prepared zip file).
1. Install it via MO2.
1. Observe that only one of the things in the zip gets installed.

## Environment:

* Mod Organizer Version that exhibits the issue: 3.0.1 (with OMOD installer)
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): Unknown
* Desktop OS/version used to run Mod Organizer: Unknown, presumably any supported.

## Link to Mod Organizer logs:
None provided.

**Comment by AnyOldName3** [comment]
Note: I've not personally verified this.

**Comment by Holt59** [comment]
I’m not sure if it is a good idea to let the bundle installer install multiple archives by default. If we end up fixing the archive name in the mods, you would have two different mods that would be linked by an archive.

I can add a setting (disable by default) to do this or/and a popup when this kind of archive pops up.

**Comment by AnyOldName3** [comment]
Maybe just show a popup saying *This archive contains multiple potential mod installers. Which one would you like to install?*

I don't think that it's a major issue if several mods end up with the same installation file, either. It's not wildly different from installing the same mod twice with different settings, and we let people do that. Worst-case scenario, we can have the bundle installer *prepend* the bundle path to the inner installer path instead of replacing it, that way it's identified properly.

**Comment by Holt59** [comment]
Asking the user to choose the mod to install is a good idea. I was worried of having the same archive in two mods because reinstalling the mods would force you to reinstall both mods, but that’s no issue if we ask the user to choose.

Regarding the archive name with path, that’s a good idea but would require some changes to the plugin interface.
