### ISSUE TITLE
Installing multi-part archives freezes program

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#1186]
## The problem:
Multi-part archives created by 7-zip cause the program to go not responding when installing.

## To Reproduce:

1. Create a multi-part 7z archive.
2. Try to install it with MO.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.3.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.2.2.1
* Desktop OS/version used to run Mod Organizer: Windows 10, Version 2004 (19041.388)

## Details:

How to create archive:
1. Download a mod (I used USSEP) and extract it.
2. Right-click the extracted contents, 7-zip, "Add to archive...".
3. Set "Split to volumes, bytes" to something.  USSEP is ~150MB so I used 100M.

Stack trace:
![image](https://user-images.githubusercontent.com/7862539/89926338-95fc6400-dbb9-11ea-9008-88d1952fe1e4.png)

**Comment by isanae** [comment]
Added this to `opencallback.cpp:133` (based on [this commit](https://github.com/ModOrganizer2/modorganizer-archive/commit/ad3b477cf69c4663b5e4569c2b0caa6b79dbb276#diff-068f7d32d1b11d73077dfb522bd7e51e))

```
  const auto path = m_Path.parent_path() / name;
  if (!IO::FileBase::GetFileInformation(path, &m_FileInfo)) {
    return S_FALSE;
  }
```

and commented out this from `extractcallback.cpp:156` (based on [this commit](https://github.com/ModOrganizer2/modorganizer-archive/commit/2afab6dcbfb86002fd07389a41bf702aef660d1e#diff-d082537740c8ba28bbab1ce0c7a2330d)):

```
  //if (prop.is_empty()) {
  //  m_LogCallback(Archive::LogLevel::Error, fmt::format(L"Error getting property {}.", property));
  //  return false;
  //
  //}
```

and it seems to be working again. @Holt59 Can you check me?

**Comment by Holt59** [comment]
Looks good to me at first glance but I can’t check right now (won’t be home for a few days). I based the implementation of the callbacks and other stuffs on the original 7z implementation, so you can check if there are similar stuff in there for split archives.

**Comment by isanae** [comment]
Fixed in https://github.com/ModOrganizer2/modorganizer-archive/pull/19.
