### ISSUE TITLE
Fallout76 plugin appears to not work with MO2? 

### ISSUE THREAD

**Issue by jarrard** [ModOrganizer2/modorganizer#1187]
Someone created a fallout76 plugin a while ago and unfortunately it doesn't appear to allow you to select Fallout76 as a game and I'm not sure why. 

I couldn't see any way to alter MO2 to include FO76 in the selectable games list?

Source
https://www.reddit.com/r/fo76/comments/aadfx1/modorganizer2_support_for_fallout76_released/
https://github.com/EntranceJew/modorganizer-game_fallout76/tags

**Comment by jarrard** [comment]
I checked the mo_interface.log and apparently it says this:  Could be a issue!

[2020-08-12 01:39:01.580 W] 'D:/Games/LAUNCHERS/Mod Organizer 2/plugins/game_fallout76.dll': file is blocked (Internet (3))

**Comment by jarrard** [comment]
Ok I think the plugin is setup right and the gameName according to modorganizer.ini configuraiton should be Fallout 76 but it causes MO2 to think for a minute at %10 cpu usage then silently crash.   

This suggest the fo76 plugin is no longer compatible with mo2. 
I do not know why but perhaps I can cross reference the source-code with the update fo4 plugin and make appropriate changes. 

I'm no programmer but its simple word replace sort of scripting stuff.

**Comment by jarrard** [comment]
Looking into building the DLL myself, however there isn't very clear instructions on howto setup the build environment for just the DLL cmake process, I have some stuff setup correctly. 

I'm going ahead with the whole MO2 compile setup procedure, but hopefully there is a shortcut / simple way to just bypass compiling entire MO2 just for a single DLL plugin.  (I've already modified FO4 plugin to FO76 and am 95% sure it's all good).

**Comment by isanae** [comment]
This is a plugin made by a third-party, I think there were some discussions on discord about it in the past few weeks. I'm closing this because it's not an issue with MO. If you need information about building MO or creating plugins, hop on to the discord on #development-info and we'll be happy to help you.

**Comment by jarrard** [comment]
Ok cheers. I just thought it be nice if MO2 had proper support for FO76 which does have some more simple mods for it. (There is a GUI injection mod but it needs constant updating)

**Comment by Holt59** [comment]
There was an attempt to “fix” the plugin in https://GitHub.com/Holt59/modorganizer-game_fallout76 

The prebuilt DLL can be found in the discord, but it is certainly not a fully functional plugin...

**Comment by jarrard** [comment]
Looks better then my very basic word replacement attempts. 
Do you know what doesn't function with it yet? 

Also fallout76 quick configuration tool is pretty good for mods. Its possible there are some tricky issues with fo76 that might make it hard for mo2 support. 

The real benefit of having MO2 support is the comprehensive conflict resolution and control you get over individual mods all on one screen where as most other tools you gotta dig through tabs and options to find basic details.
