### ISSUE TITLE
Collapsible separators

### ISSUE THREAD

**Issue by isanae** [ModOrganizer2/modorganizer#1190]
Find a way to get a tree-like mod list where items below separators can be collapsed.

**Comment by StormFX** [comment]
Just an idea, but since there's already a sort of "group" functionality, could that be expanded to include custom groups with headers that could then be collapsed/expanded?

**Comment by Al12rs** [comment]
That is the idea, though groups aren't actual mods while separators are actual modlist entries, then there is the fact that we would like users to be able to use drag and drop still, which is currently disabled for groups. So it will probably be used as a start but it will require lots of changes from that.

**Comment by StormFX** [comment]
That's a fair point. It would be nice if it could be done in such a way that there aren't dozens of `_separator`-style _"mod"_ folders in like there is with separators. I know most people probably don't spend a lot time in their "mods" folder, but it gets pretty messy for those of who do. As someone who's OCD about organization, I'd opt for something that uses directory structure (eg, `<Mods>/<Group>/<Subgroup>/<AddOn>/<Data>/`) but that would likely wreak havoc on the VFS. :p

**Comment by Al12rs** [comment]
Yeah the last part would just break everything. It doesn't make sense as it would mean that changing the group would require moving files and it would totally break the structure.

You also need to remember that we have thousands of people out there that already have 1000 mods installed and organized with separators. We can't just invent how we want things to be, they need to work with how it currently already works.

**Comment by Holt59** [comment]
Closed by #1338 and #1350.

Open dedicated issues if there are problems with the implementation or new related features you'd like to have.
