### ISSUE TITLE
Enderal not working in MO 2.3.x

### ISSUE THREAD

**Issue by supergeorg** [ModOrganizer2/modorganizer#1192]
## The problem:
When using Mod Organizer 2.3,x, managing Enderal is no longer possible. With 2.2.x it works just fine.

## To Reproduce:

Do this with MO 2.2.2.1 and 2.3.1:
1. Create a new profile, call it Enderal and select Manage Enderal
2. Get in Organizer Main View
3. Close MO
4. Restart MO

## Environment:

* Mod Organizer Version that exhibits the issue: 2.3.0, 2.3.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.2.2.1
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details:
It doesn't set anything. If one shortcut is launched, everything will reload as not set (plugins, addons etc.)

## Link to Mod Organizer logs:
![MO_alt](https://user-images.githubusercontent.com/24377292/90054243-e23fc500-dcdb-11ea-8f82-62b24b8e4f50.PNG)
![MO_neu](https://user-images.githubusercontent.com/24377292/90054267-ebc92d00-dcdb-11ea-8b4d-b2728f900216.png)

### USVFS:
https://gist.github.com/supergeorg/006f2f20836198796fa395d22b03a0ef

### MO Interface:
https://gist.github.com/supergeorg/3cd5e2559a9cfb3055db77971fc24ac6

**Comment by isanae** [comment]
This will be fixed for 2.3.2, which should be released in a few days. In the meantime, you can come by the discord and check out the most recent build in #dev-builds.

**Comment by supergeorg** [comment]
Ok, the issue seems fixed in 2.3.2 RC1.
