### ISSUE TITLE
SKSE co-saves aren't saved to profile-specific save game directories with SKSE 2.0.18+

### ISSUE THREAD

**Issue by sibirskoye** [ModOrganizer2/modorganizer#1193]
## The problem:
with SKSE 2.0.18+, SKSE co-saves don't get saved to profile-specific save directories

## To Reproduce:

1. enable profile-specific save games in your current profile
2. run the game through SKSE
3. enter the game and save before quitting
4. check your profile's save directory to confirm the co-save is missing
5. check __MO_Saves in My Games to find the missing co-save

## Environment:

* Mod Organizer Version that exhibits the issue: 2.3.2 RC 1.1 (also at least as far back as 2.2.2.1)
* Desktop OS/version used to run Mod Organizer: Windows 10 build 2004

## Details:
the issue doesn't occur with SKSE 2.0.17 or when using the default save directory in My Games, discussed in the Discord server's testers channel

**Comment by isanae** [comment]
Fixed in https://github.com/ModOrganizer2/usvfs/pull/34.
