### ISSUE TITLE
Issues with dll not loading in Skyrim SE

### ISSUE THREAD

**Issue by ObviouslyImDoingSomethingWrong** [ModOrganizer2/modorganizer#1196]
I've got everything loaded, but cannot get the dlls to load properly, as such, the uncapper ini will not execute.

**Comment by Al12rs** [comment]
The uncapper requires a preloader to work. 
With this one line report we can't help you in any way. We need more information, like what is written in the issue template.

**Comment by ObviouslyImDoingSomethingWrong** [comment]
0  0     Skyrim.esm
  1  1     Update.esm
  2  2     Dawnguard.esm
  3  3     HearthFires.esm
  4  4     Dragonborn.esm
  5  5     Unofficial Skyrim Special Edition Patch.esp
  6  6     Lanterns Of Skyrim - All In One - Main.esm
  7  7     ApachiiHair.esm
  8  8     ApachiiHairFemales.esm
  9  9     ApachiiHairMales.esm
 10  a     BSAssets.esm
254 FE   0 RealisticWaterTwo - Resources.esm
 11  b     BSHeartland.esm
 12  c     BS_DLC_patch.esp
 13  d     Campfire.esm
 14  e     FlowerGirls SE.esm
 15  f     SkyrimIsWindy.esp
 16 10     FloraRespawnFix.esp
 17 11     SkyUI_SE.esp
 18 12     Blowing in the Wind SSE.esp
 19 13     Blowing in the Wind - Lanterns of Skyrim Patch SSE.esp
254 FE   1 Blowing in the Wind - Lanterns of Skyrim SE - MCM versionPatch.esp
 20 14     SMIM-SE-Merged-All.esp
 21 15     Blowing in the Wind - SMIM Merged All Patch SSE.esp
 22 16     Mortal Enemies.esp
 23 17     Vivid WeathersSE.esp
 24 18     FNIS.esp
 25 19     iNeed.esp
 26 1a     Immersive Sounds - Compendium.esp
 27 1b     Weapons Armor Clothing & Clutter Fixes.esp
 28 1c     iNeed - Extended.esp
 29 1d     Summermyst - Enchantments of Skyrim.esp
 30 1e     Cutting Room Floor.esp
 31 1f     AcquisitiveSoulGemMultithreaded.esp
 32 20     Book Covers Skyrim.esp
 33 21     Skyrim Immersive Creatures Special Edition.esp
 34 22     Civil War Aftermath.esp
 35 23     RLO - Exteriors.esp
 36 24     AI Overhaul.esp
 37 25     LC_BuildYourNobleHouse.esp
 38 26     Man Those Borders!.esp
 39 27     AmazingFollowerTweaks.esp
 40 28     SPTConsistentOlderPeopleSE.esp
 41 29     HearthfireMultiKid.esp
 42 2a     SkyTEST-RealisticAnimals&Predators.esp
 43 2b     Legendary Skyrim Crossbows.esp
 44 2c     skyBirds_SSE.esp
 45 2d     Hothtrooper44_ArmorCompilation.esp
 46 2e     hearthfireextended.esp
 47 2f     Point The Way.esp
 48 30     OpulentOutfits_2017-SSE AIO.esp
 49 31     Holidays.esp
 50 32     fallentreebridgesSSE.esp
 51 33     Immersive Weapons.esp
 52 34     Skyrim Flora Overhaul.esp
 53 35     Verdant - A Skyrim Grass Plugin SSE Version.esp
 54 36     JKs Skyrim.esp
254 FE   2 JKs Skyrim_Holidays_Patch.esp
254 FE   3 Blowing in the Wind - JKs Skyrim Patch.esp
 55 37     Immersive Encounters.esp
 56 38     Run For Your Lives.esp
 57 39     Cloaks.esp
 58 3a     VioLens SE.esp
254 FE   4 Qw_BeyondSkyrimBruma_USSEP Hotfix Patch.esp
 59 3b     HarvestOverhaul_Redone.esp
 60 3c     TreasureHunter.esp
 61 3d     Hunterborn.esp
 62 3e     Immersive Patrols II.esp
 63 3f     Craftable Horse Barding.esp
 64 40     WaterView.esp
 65 41     Frostfall.esp
 66 42     SexLab-AmorousAdventures.esp
254 FE   5 Qw_WACCF_BSHeartland Patch.esp
254 FE   6 BSHeartland - Unofficial Patch.esp
 67 43     Book Covers Skyrim - Lost Library.esp
 68 44     ExpandedCarriageService.esp
 69 45     manny Lantern Caretakers.esp
 70 46     The Paarthurnax Dilemma.esp
 71 47     HoldBorderBanners.esp
 72 48     HFE-CRF-Patch.esp
 73 49     Apocalypse - Magic of Skyrim.esp
 74 4a     Apocalypse - Waterstride Spell Addon.esp
254 FE   7 Beyond Skyrim - Bruma - Guard Cloaks.esp
254 FE   8 Bruma - iNeed Patch.esp
254 FE   9 Bruma - SkyTEST Patch.esp
254 FE   a BS_Campfire.esp
 75 4b     NBsNPCApachiiHair.esp
 76 4c     Bijin_AIO 2018.esp
 77 4d     DawnguardArsenal.esp
 78 4e     Bijin - UCMT.esp
 79 4f     BSHeartlandFRF.esp
 80 50     CBBE.esp
 81 51     RaceMenuMorphsCBBE.esp
 82 52     Cloaks - Dawnguard.esp
 83 53     Faction Crossbows.esp
 84 54     Dr_Bandolier.esp
254 FE   b Qw_CloaksOfSkyrim_CRF Patch.esp
 85 55     DarkerNights-BeyondSkyrimBruma.esp
 86 56     DarkerNights.esp
 87 57     DeadlySpellImpacts.esp
 88 58     DiverseDragonsCollectionSE.esp
 89 59     DIVERSE SKYRIM.esp
 90 5a     Dragon Combat Overhaul.esp
 91 5b     Fixed body collision.esp
 92 5c     FNISSexyMove.esp
 93 5d     FNISspells.esp
 94 5e     Footprints.esp
 95 5f     HOR_AlchemyXP60.esp
 96 60     HFE-iNeed-Patch.esp
 97 61     TheEyesOfBeauty.esp
 98 62     HearthfireMultiKid_LastName.esp
 99 63     HBRemoveDrops.esp
100 64     Hunterborn - Campfire Patch.esp
101 65     Hunterborn - iNeed Patch.esp
102 66     Hunterborn - Soups and Stews.esp
103 67     iNeed - Dangerous Diseases.esp
104 68     Beards.esp
105 69     Hothtrooper44_Armor_Ecksstra.esp
106 6a     iHUD.esp
107 6b     imp_helm_legend.esp
108 6c     dD-Increase Fall Damage.esp
109 6d     Wildcat - Combat of Skyrim.esp
254 FE   c Wildcat-Immersive Weapons Patch.esp
110 6e     dD - Enhanced Blood Main.esp
111 6f     ISC Enhanced Blood Patch.esp
112 70     dD-Reduced Splatter Size.esp
113 71     EBT - IC PATCH.esp
114 72     EBT - skyBirds Patch.esp
115 73     PluginTemplate.esp
116 74     sandboxcylinderheight.esp
117 75     NoBSAIProjectileDodge.esp
118 76     PumpingIron.esp
119 77     RaceMenu.esp
120 78     RaceMenuPlugin.esp
121 79     RLO - Effects.esp
122 7a     PrvtIRoyalArmory.esp
123 7b     Runandwalkpaces.esp
124 7c     Serana.esp
125 7d     The Eyes Of Beauty - Elves Edition.esp
126 7e     Tribunal Robes for SSE.esp
127 7f     UIExtensions.esp
128 80     Vivid Weathers - Extended Rain.esp
129 81     Vivid Weathers SE - Bruma Patch.esp
130 82     Vivid Weathers Utilities.esp
131 83     We Dont Float.esp
132 84     WetandCold.esp
133 85     SOSRaceMenu.esp
134 86     XPMSE.esp
254 FE   d Qw_BookCoversSkyrim_CRF Patch.esp
254 FE   e Qw_ConsistentOlderPeople_AIOverhaul Patch.esp
254 FE   f Qw_DeadlySpellImpacts_ISC Patch.esp
254 FE  10 Qw_ISC_CRF Patch.esp
254 FE  11 Qw_WACCF_CRF Patch.esp
254 FE  12 Qw_WACCF_CloaksOfSkyrim Patch.esp
254 FE  13 Qw_WACCF_ISC Patch.esp
254 FE  14 Qw_WACCF_LSCrossbows Patch.esp
254 FE  15 DiverseSkyrim - Skyrim Immersive Creatures patch.esp
254 FE  16 Flora Respawn Fix - SkyBirds patch.esp
135 87     HOR_SkyBirdsPatch.esp
254 FE  17 Flora Respawn Fix - Skyrim is Windy patch.esp
136 88     SkyrimIsWindy-HarvestOverhaul-Patch.esp
254 FE  18 Summermyst - SIC patch.esp
254 FE  19 Vivid Weathers - Wet and Cold patch.esp
254 FE  1a USSEP-Immersive Weapons Patch.esp
254 FE  1b IW_AIOverhaul_Patch.esp
254 FE  1c Qw_AIOverhaul_CRF Patch.esp
137 89     Imperious - Races of Skyrim.esp
138 8a     MLU.esp
139 8b     MLU - Summermyst.esp
140 8c     Helgen Reborn.esp
141 8d     Blowing in the Wind - Helgen Reborn Patch SSE.esp
142 8e     ISC Morrowloot Ultimate Simplified Patch.esp
254 FE  1d MLU - CRF.esp
143 8f     MLU - Immersive Armors.esp
144 90     Trade & Barter.esp
145 91     Ordinator - Perks of Skyrim.esp
146 92     Apocalypse - Ordinator Compatibility Patch.esp
147 93     HOR_OrdinatorPatch.esp
148 94     Multiple Enchantments - Ordinator Patch.esp
149 95     Ordinator - Beyond Skyrim Bruma Patch.esp
150 96     Alternate Start - Live Another Life.esp
151 97     Alternate Start -- New Beginnings.esp
152 98     LRSLALHunterExtension.esp
153 99     Immersive Citizens - AI Overhaul.esp
154 9a     Provincial Courier Service.esp
155 9b     Relationship Dialogue Overhaul.esp
156 9c     RDO - AFT v1.66 Patch.esp
157 9d     Convenient Horses.esp
158 9e     CH Bruma Patch.esp
159 9f     RDO - CRF + USSEP Patch.esp
160 a0     Realistic AI Detection 2 SE - Medium Interior, Medium Exterior.esp
254 FE  1e Diverse Skyrim - Provincial Courier Service.esp
161 a1     Open Cities Skyrim.esp
162 a2     JKs Skyrim_Open Cities_Patch.esp
163 a3     Immersive Citizens - OCS patch.esp
164 a4     Immersive Encounters - Open Cities Patch.esp
165 a5     Blowing in the Wind - Open Cities Skyrim - Signs of Skyrim Patch SSE.esp
166 a6     RLO - Interiors.esp
167 a7     RLO - CRF Patch.esp
168 a8     RLO - IC Patch.esp
169 a9     RLO - Illuminated Spells.esp
170 aa     RLO - VIS Patch.esp
171 ab     RealisticWaterTwo.esp
254 FE  1f JKs Skyrim_RWT_Patch.esp
 This is the load order, Appachi had to be manually installed, and I am running both Meh123's and ShadowMans dll loaders, both of which I have tried alone before both running together. The game itself runs well, but the edited ini file for Uncapper, does not affect the game.

**Comment by Al12rs** [comment]
Did you check your skse logs in the documents/mygames/... folder?

**Comment by Al12rs** [comment]
The loadorder isn't really useful. What would be useful is Mo2 version on which this is issue is reproduced, which versions it isn't, windows version, Mo2 logs, and SKSE logs and version as well since the issue seems related to that. The issue teamplate detailed what we might have needed from you.

**Comment by ObviouslyImDoingSomethingWrong** [comment]
Seems after fighting with it for two days, I used a different Uncapper, and just changed the ini name to match, and low and behold, it's working. I'm not sure if maybe the new version of SKSE (2_00_19) is incompatible with the uncapper I had.
