### ISSUE TITLE
Downloading large files return -1 unable to write to drive

### ISSUE THREAD

**Issue by Bia10** [ModOrganizer2/modorganizer#1197]
## The problem:
Downloading files over 5Gb return -1 unable to write download to drive ... check storage

## To Reproduce:

try dling https://www.nexusmods.com/skyrimspecialedition/mods/2347

## Environment:
* Mod Organizer Version that exhibits the issue: 2.3.1

**Comment by LostDragonist** [comment]
It sounds like you're trying to download to either (1) a storage drive that is full or (2) a storage drive formatted to FAT which is not capable of having files over 4GB large.

**Comment by Bia10** [comment]
> (2) a storage drive formatted to FAT which is not capable of having files over 4GB large.

oh dang i forgot to properly format my flash drive, BTW could there be a feature to not abandon the downloaded data when such thing occurs? i don't wanna download that mod for third time again

something like status - download success, write to disk failed prompting a dialog pick different disk to write to

**Comment by Al12rs** [comment]
No, we only support one download folder and that is unlikely to change. There can be many fringe cases where writing to disk can get errors, supporting all of them is improbable and it's not done by most programs since it's assumed that if you have problems writing to disk there are bigger issues than the program itself (of course we support the usual ones like permissions etc).

**Comment by Bia10** [comment]
"... supporting all of them is improbable and it's not done by most programs since it's assumed that if you have problems writing to disk there are bigger issues than the program itself"

could you please explain in more technical language i have hard time understanding what you mean?

i do not consider this problem solved anyhow the mod manager should be robust enough to handle this programatically

**Comment by AnyOldName3** [comment]
There are hundreds of things that can go wrong with writing data to a drive. Many of them are so rare that none of the users of an application are ever likely to see them, and are quite a lot of work to identify. Programmers need to strike a balance between handling likely problems and not covering rare ones as it's not feasible to do all of them. The particular issue you've had isn't something easily identified or recovered from, and implementing a system to handle it in MO2 will probably be more work for the developers than it would be for all the people who ever run into the issue to fix it manually put together.

**Comment by Bia10** [comment]
"There are hundreds of things that can go wrong with writing data to a drive. Many of them are so rare that none of the users of an application are ever likely to see them, and are quite a lot of work to identify. Programmers need to strike a balance between handling likely problems and not covering rare ones as it's not feasible to do all of them."

Partially agreed.

"The particular issue you've had isn't something easily identified or recovered from, and implementing a system to handle it in MO2 will probably be more work for the developers than it would be for all the people who ever run into the issue to fix it manually put together."

Completely disagreed, could you please provide some technical arguments why do you think so?

**Comment by AnyOldName3** [comment]
We're not going to reject a maintainable pull request if you want to prove me wrong, but the gist of the situation is that the OS doesn't give us details about the cause of this kind of problem when it happens, so we'd have to implement a bunch of tests to work out the cause, and even at the end of that, the best we could reliably do is display a popup saying the drive is using FAT32. This wouldn't be the hardest thing in MO2, but it's the kind of thing that might need adjusting after a Windows update, so it would either stop working or need developer time to maintain it.

It's not an issue that will affect many people. By default, Windows formats drives as NTFS, so the only way a user is likely to unintentionally have a MO2 downloads folder on a FAT32 drive is if they're using a small SD card or USB stick, which is a bad idea anyway as it'll fill up. Larger external drives are unlikely to be preformatted as FAT32.

**Comment by Bia10** [comment]
finally we are getting somewhere!
it seems the assumptions based on your reasoning don't follow my reality that's the main problem of our disagreement

in your view a SDD drive will be bigger/faster and preformatted in NTFS
in my reality my SDD is small/slow and indeed preformatted in NTFS

in your view a SD card/USB stick is small/slow and therefore not usable
in my reality a SD card/USB stick is fat-ass/hyper-fast and therefore better choice to use then my native SSD for MO2

for reasons i don't understand these hyper-fast (400mbs read/write) very fat-ass(512GB, 1TB, 2TB) USB sticks come in preformatted as FAT32 -_-. At first i had my MO2 at SSD and it was fcking slow at IO now i have it on hyper-fast USB stick and it works much faster. The investment in proper SSD would be 2-3x times the price i paid for this USB stick as such i consider it a worthy IO upgrade for me.

Now back to the "what can be done". Disclaimer i have not read a single line of MO2 src nor do i know much c++ in context of winAPI. 

However i find no reasons to believe that it should not be possible safely to decide file-system type
use GetVolumeInformation on MO2 download folder path retrieve the lpFileSystemNameBuffer save into global var, when download meta-data get resolved compare the total dl size if greater then limit of FAT32 raise warning dialog...

"Hey bro we got a problem here your MO2 download folder is on drive of file-system FAT32 which cannot have individual files larger then 4GB the download total size is greater then this limit therefore its not possible to download as one file.

What would you like me to do?

1. Move entire content of disk drive to different drive, reformat the drive, move data back , restore last operations.
2. Split the download into N files
3. Download file into different disk drive
etc... "

The main point to me is that currently MO2 doesn't bother doing robust pre-download check if the download can even begin to commence, in this case it simply proceeds to download the file then crash on unable to write and wastes all the bandwidth downloading 4GB file to trash it seconds later? This is not a acceptable behavior, the MO2 should know if it will be able to write what it downloads or not and in most probable cases like this case it indeed can be done.
