### ISSUE TITLE
I went from vortex to mod organizer

### ISSUE THREAD

**Issue by d4rius911** [ModOrganizer2/modorganizer#1199]
my problem is that I am going from vortex to mod organizer having previously uninstalled all mods only when I run mod organizer all the mods that I have uninstalled and permanently deleted from my computer are still present I tried to uninstall and reinstall my game and mod organizer nothing works.

can you help me please.

**Comment by LostDragonist** [comment]
If you want to delete mods, you need to delete the mods.  Nothing else is going to do it for you.  Given what you've written there, the mods are going to be in the game folder so you'd have to go delete them there.  Uninstalling the game with Steam does not delete mods.  You need to go to the actual game folder and delete them (or delete everything and *then* reinstall with Steam).

**Comment by Al12rs** [comment]
The mods are left over from vortex, you could try asking there if you still have trouble. Closing this for organizational purposes.
