### ISSUE TITLE
v2.3.2 fails to recognize installed FO4 masters

### ISSUE THREAD

**Issue by leehelck** [ModOrganizer2/modorganizer#1203]
i recently updated MO2 from 2.3 to 2.3.2 (archive) for Fallout 4 and when i opened the manager today i discovered that for some reason MO2 isn't recognizing the installed master files for the game. i haven't changed the load order or added any new mods. in fact i haven't even played the game in over a week. i tested the game by launching both F4SE and the standard launcher outside of MO2, along with launching F4SE within MO2 and there are no problems running the game with my current load order yet even after doing this MO2 still doesn't recognize that everything is where it should be. i even installed the latest version of C++ (which supposedly this latest version of MO2 requires) and i am still getting the "missing masters" error. how do i fix this?
![missing masters](https://user-images.githubusercontent.com/43259698/90832144-2736ad80-e313-11ea-8b57-c8006f519aa2.jpg)

**Comment by isanae** [comment]
Reopen if you have more information.
