### ISSUE TITLE
2.3.2 UI Problem (Mod Details doesn't load after updating MO)

### ISSUE THREAD

**Issue by SephVEVO** [ModOrganizer2/modorganizer#1207]
So after updating to the latest version (2.3.2) and even a reinstall, I am incredibly confused on why this is happening.

After installing this update, whenever I try to check a mod's details (double clicking it) it just shows a half white screen and I can't see anything.

[Here's an image to show what I mean.](https://imgur.com/5egVuFR)

I am unsure on why that's happening exactly, but any help on how to fix this would be appreciated.

Btw, logs: https://gist.github.com/SephVEVO/30c5f62a69862952904866fec3eef96d

Thanks in advance,
Seph

**Comment by isanae** [comment]
Reopen if you have more information.
