### ISSUE TITLE
Let the ctrl+f search in Ini editor search the entire document.

### ISSUE THREAD

**Issue by YannickMG** [ModOrganizer2/modorganizer#1209]
**Is your feature request related to a problem? Please describe.**
Presently the ctrl+f search functionality in the Ini editor only searches forward from the cursor. This leads me to think some values are not presently defined in the ini file, when they are actually defined earlier in the document.

**Describe the solution you'd like**
Either change the behavior to search the entire document, or add a toggle to the search interface if the previous behavior is actually desired.

**Describe alternatives you've considered**
Clicking at the top of the document before searching, or copy-pasting the document in Notepad++ to use it's search functionality instead.

**Comment by Al12rs** [comment]
You can already set in the Modorganizer Settings -> plugins -> Ini Editor -> use external editor. That way it will open the ini files using your windows default application for ini files, which can be Notepad++ for example. 

But the suggestion is still good.
