### ISSUE TITLE
every time i create a new group (Separator), the list is reset. 

### ISSUE THREAD

**Issue by g2mXagent** [ModOrganizer2/modorganizer#1215]
## The problem:
I want to manage the mod by my own group/category. I use "Create Separator" to split these groups.
i find the "Priority" in left panel is actually "Index", does not affect the load order. which is good. because i just want to organize the mod, not load order.

the problem is: every time i create a new group (Separator), the list is reset. 
in fact, the only thing to reset is "Non-MO" category.

https://imgur.com/CI9YHhB

I know MO can't manage "non-mo" mod, but the left panel is just a "list", the "Priority" is just "index". why can't put "non-mo" in the order?

## Environment:
MO v2.3.2
Windows 10 (1909) x64

**Comment by Qudix** [comment]
The left panel order does matter. It determines what assets (meshes/textures/etc) override, or are overriden by, other mods. You need to install those unmanaged mods in MO if you want to move them.
