### ISSUE TITLE
Changes to executable settings not sticking

### ISSUE THREAD

**Issue by ashelleyPurdue** [Modorganizer2/modorganizer#122]
The second time you change a checkbox in the "Modify Executables" window, the change will never save.

To reproduce:

* In the data tab, right click on an executable file(BodySlide x64 in this example) and choose "Add executable".
* In the executables list, click "Edit"
* Select BodySlide x64
* Check the box "Create files in Mod instead of overwrite"
* Click "Modify"
* Close the "Modify Executables" window
* Go back to the "Modify Executables" window that we just closed
* Select BodySlide x64 and uncheck "Create files in Mod instead of overwrite" again.
* Click "Modify"
* Select BodySlide x64 again.  You should see that "Create files in Mod instead of overwrite" is still checked, even though we unchecked it before.

If you open your profiles folder and look at settings.ini, you'll find that it doesn't get updated after you uncheck the box.  If you delete the relevant line from settings.ini, the box will be unchecked again.

**Comment by Al12rs** [comment]
I have identified the problem and I have uploaded a fixed Modorganizer.exe on the discord channel to be tested. Since this is a very old entry I will close this in a couple of days if there are no further comments.
