### ISSUE TITLE
Error messages when starting the program (MO2)

### ISSUE THREAD

**Issue by firefoxjco** [ModOrganizer2/modorganizer#1221]
## The problem:
When starting Mod Organizer 2, three error messages appear, as shown in the Screenshots.
The messages say: SyntaxError: Invalid character in identifier.
![Mod Organizer 2_1 ](https://user-images.githubusercontent.com/13730344/91645534-250fd580-ea1c-11ea-9d13-9019b8bf89d5.png)
![Mod Organizer 2_2 ](https://user-images.githubusercontent.com/13730344/91645535-25a86c00-ea1c-11ea-96c0-41bcf63a330c.png)
![Mod Organizer 2_3 ](https://user-images.githubusercontent.com/13730344/91645536-26410280-ea1c-11ea-9b96-00a693e2c076.png)

## To Reproduce:

1. When starting the program by clicking on the executable.

OS settings:
-Windows 10 64 bits
-MO2 installed in a partitioned drive different from the root (where the OS is installed.

Observations: Running MO2 from the unit where the Operating System is installed, the above error does NOT occur.

**Comment by LostDragonist** [comment]
I'm really just guessing here but can you try changing the "á" in "Utilitários" to an "a"?

**Comment by firefoxjco** [comment]
I made the suggested change and it really worked. Thank you for your help.
