### ISSUE TITLE
Skyrim LE-SkyUI - could not compile script error

### ISSUE THREAD

**Issue by apalazzi** [ModOrganizer2/modorganizer#1223]
Hi,
I'm trying to use MO2 (2.2.2.1, the version that Lutris installs) on linux to run Skyrim LE, but when I try to install SkyUI I have an error "could not compile scripts; errors were found" followed by an "installation failed (errorcode 3221225477)" message.

The console output does not give any helpful message, I think:
```[...]Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
wine: Unhandled page fault on read access to 0000000000000068 at address 000000007AC2EEB1 (thread 084c), starting debugger...
```

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.2.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Linux Pop_os! 20.04 5.4.0-7642-generic #46~1597422484~20.04~e78f762-Ubuntu SMP Wed Aug 19 14:35:06 UTC  x86_64 x86_64 x86_64 GNU/Linux

### USVFS:
https://gist.github.com/apalazzi/eb1cee29b4124b71418838a08a3b48e7

### MO Interface:
https://gist.github.com/apalazzi/dabcf6db48d734bb3b3f547554636105

Note: the latest MO2 version doesn't even start under Linux.

**Comment by Al12rs** [comment]
I'm sorry but we don't support linux or wine. None of us has a setup with it or particular interest on spending time on it. In addition, assuming this issue isn't reproduced on windows, the fault would be on wine in theory.

If you want to try to get it to work anyways, here is the wine thread we have, where some people got it working on some flavours of wine: https://github.com/ModOrganizer2/modorganizer/issues/372

**Comment by Al12rs** [comment]
Please reopen if you can reproduce on windows.
