### ISSUE TITLE
USVFS crashes when the OBSE forcing workaround is applied to directly launching Oblivion

### ISSUE THREAD

**Issue by JamesYeoman** [ModOrganizer2/modorganizer#1228]
## The problem:
When I try to use the library forcing workaround the oblivion subprocess opens up, but no window appears (as if oblivion is hanging), and MO2 remains locked. Checking Event Viewer reveals the following error entry

```
Faulting application name: Oblivion.exe, version: 1.2.0.416, time stamp: 0x462392c7
Faulting module name: usvfs_x86.dll, version: 0.4.4.8, time stamp: 0x5f3a1b58
Exception code: 0xc0000409
Fault offset: 0x00086c2c
```

However, if I apply the library forcing rules to the Oblivion Launcher, when it launches the oblivion executable, and I can play oblivion with OBSE enabled.

So I have to go through the Oblivion Launcher in MO2 in order to play Oblivion

## To Reproduce:

1. Edit the Oblivion executable options in MO2 to force `obse_1_2_416.dll` when `Oblivion.exe` is a detected process
2. Try to run it
3. Look in Event Viewer under `Event Viewer (Local) > Windows Logs > Application`
4. Use task manager to end the MO2 Oblivion process (I spent 5 minutes waiting for something to happen to no avail. It's as if Oblivion was waiting for USVFS, resulting in a deadlock)
5. Edit the Oblivion Launcher executable options in MO2 to force load `obse_1_2_416.dll` when `Oblivion.exe` is a detected process
6. Run the Oblivion Launcher
7. Click Play
8. Bask in the glory of OBSE working after spending several days trying to figure out why it wasn't working

## Environment:

* Mod Organizer Version that exhibits the issue: `v2.3.2 Revision 1412befe`
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: `Windows 10`

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

Oblivion Library Force Settings
![image](https://user-images.githubusercontent.com/21042602/92329547-f3bc8880-f05f-11ea-971f-962a05091fb9.png)

Oblivion Launcher Library Force Settings
![image](https://user-images.githubusercontent.com/21042602/92329560-0931b280-f060-11ea-87d9-ea57ef0e47bb.png)

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your latest USVFS log, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

https://gist.github.com/JamesYeoman/e11083b6a606bc998e513c9c5161521d

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

https://gist.github.com/JamesYeoman/1f50f3acd540fba426e562f2637c1017

**Comment by AnyOldName3** [comment]
You've not included any logs, despite the clear instructions telling you to do that. Please add some logs.

**Comment by JamesYeoman** [comment]
Ah, sorry about that. There we go.

I also noticed an error with USVFS in Event Viewer that I've detailed at the start of the bug report

**Comment by JamesYeoman** [comment]
I've just edited the issue to more accurately reflect my recent discovery. Hopefully this helps in debugging

**Comment by Al12rs** [comment]
@JamesYeoman the usvfs log suggests that usvfs was able to load the OBSE just fine inside the Oblivion.exe process. In fact the log is right in the middle of loading some OBSE plugins when it stops.
This would suggest that the game is hanging when trying to load one of your obse plugins.

Could you please go and check your obse logs (some should be in Data/obse/plugins ,some in MyGames/oblivion/etc.)? After trying to run Oblivion.exe with OBSE directly of course.

**Comment by JamesYeoman** [comment]
[Here's the OBSE log](https://gist.github.com/JamesYeoman/37492375b91285075fe1a21890fbbbc8), and it appears as though the plugins do infact load, because the final log line just says `patched`


One interesting thing to note is the [nvac.log content](https://gist.github.com/JamesYeoman/7dcb97d1c9bb862c9ccea24f3bc4c44b). It looks like it gets stuck in a loop _because_ of usvfs. Of course, that could just be me misinterpreting what it's doing, but it definitely looks like usvfs tries to block it or something. I'll generate an OBSE log and nvac log for launching via the launcher and make another comment, just in case that helps

**Comment by Al12rs** [comment]
That log is reporting an unhandled exception in usvfs. When you run the installer does OBSE and everything else load correctly? Can you check the logs in that case

**Comment by JamesYeoman** [comment]
[nvac.log](https://gist.github.com/JamesYeoman/2511cef4c8431b34e9990c4da8805ff5)
[obse.log](https://gist.github.com/JamesYeoman/3881c9fa1cef229c599ea777bf9aee29)
[mo_interface.log](https://gist.github.com/JamesYeoman/ca9c737b8ede347d4835cf3c0644f448)
[usvfs.log](https://gist.github.com/JamesYeoman/c5febc1ee88f82dde1ebaa28bef35d63)

One interesting thing to note is that by launching oblivion by `OblivionLauncher.exe`, the `usvfs.log` is significantly longer

**Comment by JamesYeoman** [comment]
Launching via `Oblivion.exe` causes the usvfs error
Launching via `OblivionLauncher.exe` loads oblivion perfectly fine, and OBSE works (I know this for a fact because I have `LINK` installed which is a mod config menu as an OBSE plugin, and I'm able to access it)

**Comment by Al12rs** [comment]
go to `F:/MO2/crashDumps`, clear the contents. Run the game from Mo2 reproducing the crash, upload the new crashdump in that folder.

**Comment by JamesYeoman** [comment]
Wow that was mental. I had the folder open in explorer when I launched oblivion, and it was just a torrent of crashdumps. When I killed the oblivion process (after about 30 seconds, as usual), all that was left was crash dumps 95-99. [crashDumps.zip](https://github.com/ModOrganizer2/modorganizer/files/5197092/crashDumps.zip)

**Comment by JamesYeoman** [comment]
Also, out of interest, how does one go about viewing the crash dumps? Does the debugger use it to recreate the crash conditions or something?

**Comment by Al12rs** [comment]
Can you try removing the nvac plugin? It's basically ignoring the fact that usvfs is crashing and making it continue on its marry way until it throws the exception again and again. That is why it's hanging. It should be crashing instead.

**Comment by JamesYeoman** [comment]
Ooooooh this time the oblivion window opened, then closed. But no crash dump was created for some reason.
[mo_interface.log](https://gist.github.com/JamesYeoman/727a0f5b43a5b48030cadadd42fc14cc)
[usvfs.log](https://gist.github.com/JamesYeoman/ee816fccf6e4494757c5580333818c7f)

**Comment by Al12rs** [comment]
It didn't crash in the same point it seems since it actually got past it

**Comment by Al12rs** [comment]
The crashdumps show a crash here: https://github.com/ModOrganizer2/usvfs/blob/master/src/usvfs_dll/usvfs.cpp#L393
An access violation exception inside the spdlog::get() portion. 
![image](https://user-images.githubusercontent.com/26797547/92639942-d516f580-f2dc-11ea-84f7-7854afcc2e48.png)

**Comment by Al12rs** [comment]
@JamesYeoman Can you test running the game from the launcher without nvac?

**Comment by JamesYeoman** [comment]
Ooh that crashed
[mo_interface.log](https://gist.github.com/JamesYeoman/300c5bfe8801a64d212e6299aac9be5b)
[usvfs.log](https://gist.github.com/JamesYeoman/e7d201db28a88f9ebfd026dabf974fdf)

**Comment by Al12rs** [comment]
So if you don't use nvac it crashes no matter what and always without crashdumps?

**Comment by JamesYeoman** [comment]
Yep... and there's no errors in the event log now... I hate it when bugs masquerade as other bugs. Thanks for your help pinpointing where the error came from

**Comment by Al12rs** [comment]
I think there is a good possibility that there is a Mo2 issue on top of whatever is making you crash now. The fact that running the launcher made everything work is very strange. We also have that other report of nvac not working

**Comment by JamesYeoman** [comment]
Yeah, I linked to that

**Comment by Al12rs** [comment]
Could you report back if you figure out what is making oblivion crash without nvac?

**Comment by JamesYeoman** [comment]
I installed `Message Logger` and it looks like there's several missing assets. So that's more on me. I've reproduced the nvac crash with nvac being the only loaded mod (the files are over at #1224 )

**Comment by Al12rs** [comment]
I will look into that one some other time. Thanks for helping out with all the testing and logs.
