### ISSUE TITLE
Warning on Uninstall for your Downloads folder

### ISSUE THREAD

**Issue by aceidon** [Modorganizer2/modorganizer#123]
During uninstall in current build 2.0.8.3 be warned that it will delete your downloads even though it prompts to ask a Yes/No question it doesn't give you the ability to provide a Yes or a No.  It is an 'Okay'.  So it always deletes your stuff even if you do not want it to.

In one click it deleted every download I had even though I wanted those to be kept.  Boom 3 hours of work and it's gone.

**Comment by LePresidente** [comment]
Fixed in 2.1.2
