### ISSUE TITLE
IOrganizer.persistent()  is not returning the latest values

### ISSUE THREAD

**Issue by mdavis199** [ModOrganizer2/modorganizer#1234]
I'm developing a plugin tool.  It stores information such as the plugin's window size and maximized state in MO's persistent settings. I am using `IOrganizer.setPersistent()` because settings such as window size do not seem appropriate for user-facing settings stored by `IOrganizer.setPluginSetting()`.

**The problem:** 

`IOrganizer.persistent()` returns the value MO had when it was launched, not the current value stored in `modorganizer.ini`

**For example:**  
1. I launch MO and then launch my plugin, my plugin is displayed non-maximized.  
2. I then maximize my plugin window and close the plugin, saving the the new maximized state via `setPersistent()`. 
3. I look in `modorganizer.ini` and it correctly says the plugin's maximized setting is `true`.  
4. I then launch my plugin again.  But it is launched non-maximized. 
5. However, if i close and reopen MO2 before relaunching the plugin, the plugin will display maximized.   

It appears that MO2 relies on cached values for persistent settings, but an MO Plugin would need the latest value.

**Comment by AnyOldName3** [comment]
These lines are relevant:
* https://github.com/ModOrganizer2/modorganizer/blob/460a068b38ff9c03ec63578fd5a7968f07bd3465/src/organizercore.cpp#L700
* https://github.com/ModOrganizer2/modorganizer/blob/4fc61c7cd4befb79beabc2cc4e6b8b9a954db95c/src/settings.h#L337
* https://github.com/ModOrganizer2/modorganizer/blob/b9ff5cc7dc8b9e338d5a3002db8eb5ca5a6b811b/src/settingsutilities.h#L86-L114

**Comment by Al12rs** [comment]
Are you positive that Mo2 is returning startup values and not the default values instead?

**Comment by Al12rs** [comment]
@mdavis199 Are you calling void `PluginSettings::setPersistent()` with the `bool sync` flag set to true?

**Comment by mdavis199** [comment]
It's True by default, but I've tried leaving it off and explicitly setting it to True.  No change.

**Comment by mdavis199** [comment]
It's a problem on my end.  There was a logic error in interpreting  the Variant values.   I swear I checked it a hundred times before contacting you.  Sorry to waste your time.    Thank you.

**Comment by Al12rs** [comment]
No problem
