### ISSUE TITLE
Explain what to do with "Unmanaged" mods.

### ISSUE THREAD

**Issue by Zetawilk** [ModOrganizer2/modorganizer#1246]
I've uninstalled all mods and plugins previously installed via Vortex. I cannot remove or modify any mods that are listed as "unmanaged" in Mod Organizer 2.

**Comment by Holt59** [comment]
Did you check that your `data` directory was clean (no extra ESPs / BSAs)? What are the "unmanaged" mods you're seeing?

**Comment by isanae** [comment]
Reopen if you have more information.

**Comment by Jaderivers** [comment]
Hello 
I know these are old post, but I just a started to have similar issues,  
When I was playing on sse , there were no un-managed showing, I was playing skyrim le  for awhile then popped over to check something on sse profile on mo2 , and suddenly  I have all these blasted un-managed mods, and I'm like what the .... hell!!!
In the right pane I've been clicking on " open in explorer" option and deleting ones there and then they don't show anymore, but some are ones I'm might still use, and Whyyyy they've become un-managed has got me confused  n ticked off, I don't how I'm going to fix it , other than remove every mod, back to an empty page on mo2 and re install the ones on the list , ..
I printed out a list, including all  so I could keep a check , also I  don't do separate profiles , on this particular profile I have mods unckecked that I still want to use and mods checked that I'm using for vamp mage play thru, 
Can't use drop down spoiler tags, they didn't  work, can use attach file, ppl will weary about downloading a file ...
I have no idea why some of those are now un-managed, as I still want to and or was using them..... o_O 

> # This file was automatically generated by Mod Organizer.
*Unmanaged: PC Head Tracking - MCM
*Unmanaged: PC Head Tracking - Patch
-Glorious Fort Dawnguard
-Unique Vampire Dens SSE
-Remove Blood
-Crypt of the Old Guard - Vampire Player Home
-Realm of Lorkhan - Freeform Alternate Start 3
-KillableSeranaEng
-The Blades Can Die
-Caranthir Tower Reborn SE
-Gryphonknight Regalia - Breton Noble Armor (optional SMP)
-LockMaster - Lock Doors Containers and Usable Skeleton Key
-Golden Statue of Mara
-Statue of Mara - My Interior patches SE
-Slof's Fluffy Khajiit Tails SSE
-Path to Volkihar--Vampires Can Skip Fort Dawnguard
-NPC's Run and Walk at Your Pace
-More Ferries - Fast Travel Improvement
-More Carriages
-Face Discoloration Fix
-Daedric Armor from Morrowind
-Cooking Pots in Inns
-BAT - Bigger Argonian Tails SE
-Girl's Heavy Armors (CBBE)
-Digitigrade Beast Races for Skyrim SE
-BeastHHBB - Khajiit and Argonian content - player character and NPC replacer
-Realm of Lorkhan - Freeform Alternate Start
-Unlucky Loot
-The Black Sepulchre
-Real Shelter - Full Release
-Blooded Heavy Armor
-Riverside Lodge
-Skaal Heavy Armor SE
-Heavy Nordic Armor
-Beards of Power
-Vampire Armors and Weapons Retexture SE
-Better Vampire Lords 1.2
-Rally's Skeleton Key
-Draw - A Dueling Mod
-The Third Eye racemenu add-on
-Concentrative Fire and Frost Breaths
-Hylios Female Mannequins
-The Prophecy -Lord Harkon Voice Rework-
-Leather Backpack - Special Edition - Rerelease v1.0
-DBVO Female Orc Voice
-Relaxed Sneak Animations
-RUSTIC FURNITURE - SPECIAL EDITION
-Village beds
-Unread Books Glow SSE
-Imperial Battlemage Robes
-JS Dragon Claws AE Anniversary Edition
-The Eyes of Beauty - Ai Remastered
-Mythic Dawn armor SE
-Statue of Mara
-Feral Eyes - Beast Eyes for Humanoid Races
-Daedric Shrines - Molag Bal
-Argonian - Khajiit FabULook Eyes SSE 1.0
-Amon's Talos Statue Replacer
-Portal - Dynamically Placed Teleportation SE
-Improved Butterfliegen
-Amon's Dibella Statue Replacer
-Buyable Home Patch for Leaf Rest SSE
-Leaf Rest SSE
-DreamBurrows Regal Huntsman Armor - SSE
-The Thalmor's Shadow - Taliesin (Custom Voiced Follower)
-_ Superior Lore-Friendly Hair HD 2K - Rough Hair
-Gotobed-se-patches
-Go to bed
-Rally's Vampire Coffins
-Better Vampire NPCs 2.0
-Vampire Coffin
-The Paarthurnax Dilemma
-College of Winterhold - Quest Expansion
-Convenient Carriages
-Solid Spy - a DBVO voice pack
-DBVO - Argonian Male Voice Pack
-Geralt of Rivia DBVO Pack Patches
-FileAccess Interface for Skyrim SE Scripts - FISSES
-Fangs and Eyes White-6842-1-0
-Fangs and Eyes - A Vampire Appearance Mod-Red
-Master Chief DBVO Pack cfto
-Master Chief DBVO Pack
-Better Vampires 8.9
-Vampires Cast No Shadow
-Humanoid Vampires SE - Vampires use normal faces and Serana's eyes variant
+Hunt vampires as a vampire - do dawnguard questline as a vampire
-Vampire Lord Overhaul - BVL Patch
-Aeonbarr - a Unique and Summonable Horse (CH-Friendly) For SE
-Dawnguard Fortress Improved
-Simple Actions - The floor is as good a place to sleep (or sit) as any by BralorMarr
-Guards Armor Replacer SSE
-Dragon Claws Auto-Unlock
-Shadow Duelist Armor
-Gemling Queen Jewelry SE
-Redguard Assassin Armor
-More Colorful Collectibles
-Unread Books Glow SSE with MCM
-aMidianBorn Book of Silence SE
-Ecotone Simple Portable Storage
+More Growable Plants SE
-More Colorful Bug Jars Part Deux
-Bandit Lines Expansion
-RUSTIC WINDOWS - Special Edition
-RUGNAROK - Special Edition
-PELTAPALOOZA - Special Edition
-Unlimited Weapon Enchant
-Enigma Series -All In One- SSE
-Quests Are In Skyrim
-Recipe Auto-Learn
-Serana SHUT UP
-Simply More Runes
-Winter Is Coming SSE - Cloaks
-Mage Backpack SSE
-Better Magic Lighting (Unlimted magelight. Increased radius for candlelight and magelight. Cheaper magelight)
-The Mystery of Icebound Crypt SSE
+Forgotten Dungeons (SSE)
-Lock o Motion SSE
-GTFO My Room
-Inventory Functions SE-AE
-Improved Wall Baskets - Meshes and Textures
-Magically mine
-Dynamic Autosorting System
-Higher Jumping
-Dead NPC Body Cleaner Remover
-Strange Runes
-Pierced Ears - Earrings SE
+Lanterns Of Skyrim II
-To Your Face SE - AE - VR
-Evanora - DBVO Female Player Voice Pack
+Penitus Oculatus
-Nilheim - Misc Quest Expansion
-The Only Cure - Quest Expansion
-Nordic Leather Armor
-Save the Icerunner - Lights Out Alternate Routes
-Destroy the Dark Brotherhood - Enhanced
-Destroy the Thieves Guild - Special Edition
-A Quality World Map
-powerofthree's Papyrus Extender
-Beyond Skyrim - Bruma
-Darker Nights 1.7p13
-My Home is Your Home (MHiYH 2plus) - SSE
-More Triss Armor Recolours UNP
-Belethor's Sister - Quest
-Nordic Cooking
-Convenient Horses
-Convenient Bridges BETA - Special Edition
-The Conflict Under the Crescent - A Companions and Silver Hand Mod
-Horn Of Jurgen Windcaller Redone
-Medieval Torch
-NK_Horns Aplenty
-Sneak Tools SE Edition
-Saints and Seducers Begone
-IHarvest
+Sybille Stentor DBVO Player Voice - FemaleSultry
-JS Dragon Claws SE
-Arclight
-Medieval Spirits
+Embers HD
-Legacy of the Dragonborn Patches (Official)
-Legacy of the Dragonborn
-Incandescence - Colorful Candlelight and Magelight
+Skyrim Cheat Engine
-Legacy of the Dragonborn BadGremlins Collection
-Dear Diary DM and Paper (Squish) Fixes
-Dragonborn Voice Over
-Dear Diary Dark Mode (warm text)
-Display Enemy Level
-Customizable UI Replacer Less Intrusive HUD SE
-Less Intrusive HUD II SE patch
-Less Intrusive HUD II SE
-Havok's Racemenu Makeup Overlays (Lipstick)
-UIExtensions
+Timing is Everything SE
-lockpickpro_v
-Jaxonz Blink Teleport SE
-Jaxonz Positioner Converted
-Improved Alternate Conversation Camera
-More Informative Console
-Not So Fast - Main Quest
-Realm of Lorkhan - Freeform Alternate Start 3 Best one
-ConsoleUtilSSE NG
-JContainers SE
-Khajiit rito kalshan SE
-KRK
+Header file for DLL plugin author (Anniversary Edition)
+PC Head Tracking and Voice Type SE
-Nordic Beds SE
-Relaxed Bards
-The Eyes Of Beauty SSE
-Ordinator - Perks of Skyrim
+Community Overlay 3 (51- 70) Bodypaints Warpaints and Tattoos
+Community Overlays 2 (31-50) Bodypaints Warpaints Tattoos and more made for the Community (Special Edition)
+Apachii Sky Hair SSE male
+Apachii Divine Elegance Store
-RaceMenu
+Apachii Sky Hair SSE
-The Innocence Lost - Quest Expansion
-Caliente's Beautiful Bodies Enhancer -CBBE-
-The Choice is Yours
-Fishing - Reduced Cut
+Skyrim Sewers - Radiant Quests Enabled
+Skyrim Sewers 4
-Unofficial Skyrim Special Edition Patch - USSEP
-SkySight Skins - Ultra HD Male Textures and Real Feet Meshes (4K2K HIGH)
-Remove Creations from Main Menu
-A Matter of Time - A HUD clock widget
-SkyUI_5_2_SE
-Breezehome by Lupus v.1.0.2 rc1
-Rally's Feather and Ink
-Daedric Shrines - All in One
-They Turk err Jerb's
+Fuz Ro D-oh - Silent Voice
-Scoped Bows SE 1.3.1
-LOHS
-KS Hairdos SSE
-Dragon Age Dalish Vallaslin Face Tattoo's for Racemenu SE
-Vampire Clans and Bloodlines
*DLC: Dragonborn
*DLC: HearthFires
*DLC: Dawnguard
-ZXXZZZ_separator
*Unmanaged: 1NDArmor
*Unmanaged: [CAS]DragonbornExpansion
*Unmanaged: 00EButterfliegenENGLISH
*Unmanaged: ccQDRSSE001-SurvivalMode
*Unmanaged: [CAS]Implementation
*Unmanaged: ccBGSSSE037-Curios
*Unmanaged: ccBGSSSE025-AdvDSGS
*Unmanaged: ccBGSSSE001-Fish
*Unmanaged: [CAS]VanillaMerge
*Unmanaged: AddItemMenuSE
*Unmanaged: _ResourcePack
*Unmanaged: Aeonbarr V2.1
*Unmanaged: AMatterOfTime
*Unmanaged: Apachii_DivineEleganceStore
*Unmanaged: Apachii_DivineEleganceStore_Dawnguard_Patch
*Unmanaged: Apachii_DivineEleganceStore_Patch
*Unmanaged: ApachiiHairFemales
*Unmanaged: Archery Tweaks
*Unmanaged: Arclight
*Unmanaged: Bandit Lines Expansion
*Unmanaged: BCS_NotSoFast_Patch
*Unmanaged: BCS_TCIY_Patch
*Unmanaged: BeastHHBB
*Unmanaged: Better Magic LightsMP
*Unmanaged: Better Vampire Lords
*Unmanaged: Better Vampires
*Unmanaged: Bleakfalls Twin Towers
*Unmanaged: Bowgasm
*Unmanaged: BPH Autumngate Forge
*Unmanaged: BS_DLC_patch
*Unmanaged: BSAssets
*Unmanaged: BSHeartland
*Unmanaged: BSHeartland - No Custom Map Markers
*Unmanaged: BugJarReplacer
*Unmanaged: Carriage Drivers - New Clothes by Xtudo
*Unmanaged: CBBE
*Unmanaged: CFTO
*Unmanaged: CFTO-Lanterns
*Unmanaged: Cloaks&Capes
*Unmanaged: College Of Winterhold - Quest Expansion
*Unmanaged: CommunityOverlays2_31T50
*Unmanaged: Convenient Horses
*Unmanaged: Cooking in Inns
*Unmanaged: CookingAdventuresInSkyrim
*Unmanaged: CuC
*Unmanaged: CosmeticVampireOverhaul
*Unmanaged: Dalish_Vallaslin
*Unmanaged: DarkerNights
*Unmanaged: DarkerNights-BeyondSkyrimBruma
*Unmanaged: DBM_GuardsArmorReplacer_Patch
*Unmanaged: DBM_SkyTEST_Patch
*Unmanaged: DBM_TeldrynSerious_Patch
*Unmanaged: DBM_UnreadBooksGlow_Patch
*Unmanaged: DBM_Wyrmstooth_Patch
*Unmanaged: DBVO
*Unmanaged: Destroy the Dark Brotherhood - Enhanced
*Unmanaged: Destroy the Thieves Guild
*Unmanaged: Dragon Claws Auto-Unlock
*Unmanaged: DSerArcheryGameplayOverhaul
*Unmanaged: DynamicAutoSort
*Unmanaged: Ecotone Simple Portable Storage
*Unmanaged: Eli_Battle Mage Armour
*Unmanaged: FeralEyes
*Unmanaged: Fishing - Reduced Cut
*Unmanaged: FISS
*Unmanaged: Fort(ified) Dawnguard
*Unmanaged: Gotobed
*Unmanaged: Gotobed-HearthFires-patch
*Unmanaged: GTFO My Room
*Unmanaged: Guards_Armor_Replacer
*Unmanaged: Hand Placed Enemies
*Unmanaged: HavoksLipPatterns
*Unmanaged: icepenguinworldmapclassic
*Unmanaged: IHarvest
*Unmanaged: IHarvestVanillaFixes
*Unmanaged: Innocence Lost - Quest Expansion
*Unmanaged: Innocence Lost QE - The Choice Is Yours Patch
*Unmanaged: Innocence Lost QE - USSEP Patch
*Unmanaged: JaxonzBlinkTeleport2
*Unmanaged: JaxonzEnhGrab
*Unmanaged: Jump300
*Unmanaged: Khajiit Rito Kalshan
*Unmanaged: KRKTamira
*Unmanaged: KS Hairdo's
*Unmanaged: LegacyoftheDragonborn
*Unmanaged: LessIntrusiveHUD
*Unmanaged: Magically mine
*Unmanaged: mihaildismemberthosemudcrabs
*Unmanaged: MOD - Simply Better Torches (SE)
*Unmanaged: more plants all extra
*Unmanaged: MoreColorfulSceneryJars
*Unmanaged: MoreVampireEyes
*Unmanaged: My Home Is Your Home
*Unmanaged: Nilheim_MiscQuestExpansion
*Unmanaged: NK_HornSlider
*Unmanaged: NordicCooking
*Unmanaged: NordicLeatherArmor
*Unmanaged: NosPiercedEarsAll
*Unmanaged: NotSoFast-MainQuest
*Unmanaged: Odin - Skyrim Magic Overhaul
*Unmanaged: Ordinator - Perks of Skyrim
*Unmanaged: Ordinator - Slower Leveling Speed and Double Skill Training Costs
*Unmanaged: PoisoningExtended
*Unmanaged: Populated Skyrim Legendary
*Unmanaged: Portal
*Unmanaged: Predator Vision
*Unmanaged: RaceMenu
*Unmanaged: RaceMenuPlugin
*Unmanaged: RealisticNeedsandDiseases
*Unmanaged: Realm of Lorkhan - Custom Alternate Start - Choose your own adventure
*Unmanaged: Redguard Assasin Armor
*Unmanaged: Relic Hunter Triss
*Unmanaged: Run For Your Lives
*Unmanaged: SaintsSeducersDisabled
*Unmanaged: SaveTheIcerunner
*Unmanaged: Serana SHUT UP
*Unmanaged: ShocksCookingSkillHF
*Unmanaged: Silent Moons Camp Reborn
*Unmanaged: Simply More Runes - 5 Rune Variant
*Unmanaged: SkyTEST-RealisticAnimals&Predators
*Unmanaged: SkyUI_SE
*Unmanaged: Sneak Tools
*Unmanaged: Sneak Tools Vanilla Hoods
*Unmanaged: Sneak Tools Vanilla Masks
*Unmanaged: The Paarthurnax Dilemma
*Unmanaged: The Whispering Door - Quest Expansion
*Unmanaged: The Whispering Door QE - USSEP Patch
*Unmanaged: TheChoiceIsYours
*Unmanaged: TheCleaner
*Unmanaged: TheEyesOfBeauty
*Unmanaged: TheOnlyCureQuestExpansion
*Unmanaged: They Took our Jobs
*Unmanaged: TimingIsEverything
*Unmanaged: UIExtensions
*Unmanaged: Unofficial Skyrim Special Edition Patch
*Unmanaged: UnreadBooksGlow
*Unmanaged: Vanilla Hair Replacer - VHR
