### ISSUE TITLE
loot

### ISSUE THREAD

**Issue by tony2013fl** [ModOrganizer2/modorganizer#1251]
the built in loot not working its out of date so cant sort. Plus if i use new loot installed it doesnt see the mods i usauly only use the built in loot but like i said not working in current release.

**Comment by Al12rs** [comment]
What game are you managing? What makes you think Loot is out of date? It's working fine here.
Are you running the standalone loot through MO2? 

If the sort button isn't working please provide the requested log files so we can have a look at what the problem might be. It could be Loot is looking at a different game installation from the one Mo2 is managing for example.

**Comment by Al12rs** [comment]
Reopen if you have more information.
