### ISSUE TITLE
"Installed" Indicator Incorrect

### ISSUE THREAD

**Issue by Sorbe** [ModOrganizer2/modorganizer#1261]
## The problem:
The "Installed" status on the "Download" tab entries sometimes is not accurate.  Even pressing "refresh" does not fix this.

## To Reproduce:
After using MO2 for a while (vague I know) I was looking at my list of downloaded mods to see if I had any old ones.  I do this periodically to make sure I'm not keeping older mod versions that I've already upgraded in MO2.   While I'm pleased to see that there are no "older" versions of mods when I look in the list, I do see an installed mod that I know I'm not using.

At one point, I had "Skyrim Flora Overhaul SE" installed and working well.  Then I tried "Veydosabrom" instead, by disabling and ultimately removing SFO.  But somehow, while the mod name list no longer shows SFO at all, the download list shows it as "installed".

So, I'm thinking the "installed" status just needs a "refresh", which I do by pressing the "refresh button to "refresh the downloads.  And.. nothing happens.  It still shows as "installed.  I only have the one profile "Default" and the backup matches the current mod list. (Screenshots below)

Is this a bug or something else?  Why doesn't "refresh" actually update the installed status?

## Environment:

Mod Organizer V2.3.2
Windows 10 Pro

## Details:
https://ibb.co/Y2zJvSS
https://ibb.co/DDkf8s7
https://ibb.co/dP42db3

**Comment by Al12rs** [comment]
To clarify, currently the installed/uninstalled flags are simply given to the download upon it's installation or upon the uninstallation of the mod. Any other even outside of these two will leave the flag as it is. Even for example manually deleting the mod from the mods folder. With the newest dev builds you can now edit the meta.ini file via a right click option making it possible for users to manually update the flag if they want to.

**Comment by Al12rs** [comment]
2.4.0 will have fixed for merge/replace install cases
