### ISSUE TITLE
query info in the downloads tab is no longer able to find mods

### ISSUE THREAD

**Issue by jmdavis** [ModOrganizer2/modorganizer#1262]
## The problem:
"Query Info" in the Downloads tab now fails to find the mod ID and game name on its own. It always asks what the mod ID is and what game it's for instead of being able to properly figure it out on its own like it could before.

## To Reproduce:

1. A lot of (all?) mods have the problem, but `Wet and Cold SE` definitely does, so you can manually download the latest file from there: https://www.nexusmods.com/skyrimspecialedition/mods/644?tab=files

2. After you download it, drag it over onto the Downloads tab in MO2.

3. Right click on the file in the Downloads tab and select "Query Info."

4. Instead of correctly querying the mod's info from the Nexus, it asks you to select the mod ID and then the game.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.3.2
* Last Mod Organizer Version that did not exhibit the issue (if applicable): IIRC, it used to work with exact the same version of MO2, though I suppose that it's possible that I wasn't paying enough attention, and the problems started when I updated last (presumably from 2.3.1).
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details:

At some point in the last few weeks, the Nexus started putting long numbers on the end of file names (e.g. the newest version of Wet and Cold SE has the file `Wet and Cold SE v2.4.0-644-2-4-0-1601332084.7z`), and I _think_ that when they made that change is when this started happening. Whether the file name is the problem or some other change in the Nexus API, I don't know, but it looks to me like something on the Nexus' side of things changed, and it broke "Query Info" in MO2. Regardless of the exact cause though, "Query Info" now fails consistently, and I'm not sure that I've seen it work even once, since the Nexus started putting those long numbers on the end of file names.

### USVFS:
Not relevant, since USVFS is not involved.

### MO Interface:

The lines added when using "Query Info" were

```
[2020-10-17 04:39:13.078 D] Searching SkyrimSE for MD5 of af8903d01b03bbdccb9e52c10dc9d41d
[2020-10-17 04:39:13.327 D] Searching Skyrim for MD5 of af8903d01b03bbdccb9e52c10dc9d41d
[2020-10-17 04:39:15.620 D] user selected mod ID 644 and mod name "Wet and Cold SE v2.4.0"
[2020-10-17 04:39:17.233 D] Information updated
[2020-10-17 04:39:17.664 D] timing: DownloadManager::refreshList() 396 ms
```

**Comment by LostDragonist** [comment]
It's not broken for all files.  Maybe all new files after some date.  This is purely a Nexus server issue where they store an incorrect MD5 for a file, or possibly none at all, and it's never corrected.  There's really not much we can do about it from our side.

**Comment by jmdavis** [comment]
Well, if it hasn't been reported already (and I see no sign of it having been reported on their github page), then it would probably be best if one of you folks reported it, since then you could indicate which API calls aren't working correctly. The best that I could do would be to repeat your comment (or link to it).

**Comment by LostDragonist** [comment]
I've reported it several times over the years through several channels.  They never seem interested.  Maybe someone else will have better luck.

**Comment by jmdavis** [comment]
Lovely. :|
