### ISSUE TITLE
BSA Packer plugin unable to create and pack bsa

### ISSUE THREAD

**Issue by juliandevast** [ModOrganizer2/modorganizer#1264]
## The problem:
Trying to use the BSA Packer to create a bsa main file for the mod Skibbada Weapon Pack is not possibloe, everytime the plugin is used estates that the bsa was created then a second windows pops up showing the progress(last a couple of seconds) but then MO2 shows a window saying 'Plugin ''bsa packer'' failed: Archive is not on writing mode.

Which seems that the folder  is on Read-Only but is not possible to change it everytime is unticked, the option turns on again, this makes imposible to modify the virtual data folder and hence, the bsa packing of the mod

## To Reproduce:

1. Go to 'Tools'
2. Click on 'BSA Packer'
3. Select the mod to be packed
4. Choose a Name
5. First Message appears, accept
6. Error Window

## Environment:

* Mod Organizer Version that exhibits the issue: v 2.3.2
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro 64 bits

**Comment by LostDragonist** [comment]
>Which seems that the folder is on Read-Only but is not possible to change it everytime is unticked, the option turns on again, this makes imposible to modify the virtual data folder and hence, the bsa packing of the mod

Windows does not have the concept of read-only folders.  It shows you a square in the option to denote this fact.  A square is "I have no clue what this setting is" not "this setting is active".  That said, someone will have to look into the rest of it.

**Comment by AnyOldName3** [comment]
A square is technically closer *don't care, let something else decide*, so while what you've said is accurate for Windows folders, there are plenty of other situations in other programs where understanding it the way you've described could be misleading.

I'm just saying this in case it gets seen by someone who only found out about the filled-in-square for checkboxes today so they don't think something else is broken when it's not.

**Comment by juliandevast** [comment]
I see, i didnt want to mislead it was just guessing, i dont know how does that work, so... how do i pack my mod? thats what i need

**Comment by Al12rs** [comment]
The author of the plugin is able to reproduce the issue and is looking into a solution.

**Comment by Al12rs** [comment]
Should be fixed in: https://github.com/ModOrganizer2/modorganizer-bsapacker/pull/21 
Once the Build system is done here will be a link to a hopefully working version of Mo2: https://ci.appveyor.com/project/ModOrganizer2/modorganizer/build/artifacts
