### ISSUE TITLE
A .dll mod will not load in MO2. 

### ISSUE THREAD

**Issue by dalevj** [ModOrganizer2/modorganizer#1265]
Can't install NPC AI Process Position Fix V2.10 with MO2. When I try to install the following error occurs; 

"File in Use", "The action can't be completed because the file is open in SkyrimSE.exe". No, it isn't I'm not running the game just in MO2. More info as reported by MO2 - [2020-10-23 23:13:43.825 E] Extraction failed: cannot delete output file '\\?\E:\Games\Steam\SteamApps\common\MO2\mods\NPC AI Process Position Fix - SSE\SKSE\Plugins\MaxsuAIProcessFix.dll': Access is denied

**Comment by Holt59** [comment]
Please fill-in the details of the issue instead of keeping the initial instructions (remove the section if you find it irrelevant). I just downloaded the mod from Nexus SSE and installed it with no problem with latest MO2 so we need (a lot) more details to figure out the problem.

**Comment by isanae** [comment]
The game is running in the background. Try rebooting.

**Comment by dalevj** [comment]
I'm embarrassed, that was it. Must have had SkyrimSE running, sheese.
Thanks for the tip!
