### ISSUE TITLE
new mod order replaced by old

### ISSUE THREAD

**Issue by bonesaw73** [ModOrganizer2/modorganizer#1270]
## The problem:
I was just on fallout 4 mod organizer 2 and switched over to new vegas which I had been playing earlier and noticed that my mod order completely changed.

## To Reproduce:
im not sure how to replicate this
## Environment:

* Mod Organizer Version that exhibits the issue: v2.1.5
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: windows 10

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your latest USVFS log, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by isanae** [comment]
First, you're running a version that's more than two years old, you should update to the most recent version. As for the mod order, you might have clicked on a different column than Priority. Can't help you without more information.
