### ISSUE TITLE
MO2 Skyrim SE Doesn't load DLLs for SKSE64

### ISSUE THREAD

**Issue by renfenghuan** [ModOrganizer2/modorganizer#1306]
## The problem:
When playing **Skyrim SE** using MO2, I got the issue. All the other mod files are fine, but skse failed to detect any dlls in the virtual game folder

## To Reproduce:

1. Start the game, find some mod that use skse dll are not working
2. quit the game
3. check skse64's log file

## Environment:

* Mod Organizer Version that exhibits the issue: v2.3.2
* Desktop OS/version used to run Mod Organizer: win10 20H2

## Details:
I have mulltiple MO2 portable instance installed, one for LE, one for SE. MO2 is installed in E:\SSE\x, 
SkyrimSE is installed in steam folder. But I also tried moving SSE to D:\, and change paths in MO2,  but the issue is still on.

 you can see that it can load AddItemMenu's translation file, but can't load its dll ( because if its dll loaded, there should be a string like 

    plugin E:\The Elder Scrolls V Skyrim\Data\SKSE\Plugins\\nioverride.dll (00000001 nioverride 00000006) loaded correctly
    checking plugin E:\The Elder Scrolls V Skyrim\Data\SKSE\Plugins\\AddItemMenuLE.dll

    (this is the string from my LE skse log)

## skse log
https://gist.github.com/renfenghuan/f3140e976ee206957ea6f40de6dc98ef

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
https://gist.github.com/renfenghuan/db8cee36b984e403e5b368d4a0a8c0b9

### MO Interface:
https://gist.github.com/renfenghuan/7e9e729fc04f3beca3c8810234933f89

**Comment by LostDragonist** [comment]
>Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.

You need to do this for the logs to be any help at all.

**Comment by renfenghuan** [comment]
> > Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
> 
> You need to do this for the logs to be any help at all.

Ok, I'll do it again.

**Comment by renfenghuan** [comment]
> > Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
> 
> You need to do this for the logs to be any help at all.

OK, I updated the two gist. The interface one and vfs one.

**Comment by renfenghuan** [comment]
By the way, it just looks like SKSE64 didn't get run with MO2 at all. But I did use the button inside MO2 to start SKSE.

**Comment by renfenghuan** [comment]
![image](https://user-images.githubusercontent.com/64941682/100491234-ea503300-3119-11eb-9eef-08d091dea2a0.png)

I used this button, skse

**Comment by LostDragonist** [comment]
The only potential issue I see is the game being installed in C:\Program Files (x86)\.  This is bad in all sorts of ways.  You'll want to move the game somewhere else and fix up the paths\executables in MO.

**Comment by renfenghuan** [comment]
> The only potential issue I see is the game being installed in C:\Program Files (x86). This is bad in all sorts of ways. You'll want to move the game somewhere else and fix up the paths\executables in MO.

I said I tried move the game folder to D drive, but I got the same result

**Comment by renfenghuan** [comment]
> The only potential issue I see is the game being installed in C:\Program Files (x86). This is bad in all sorts of ways. You'll want to move the game somewhere else and fix up the paths\executables in MO.

And I use another MO2 instance to test this new game in the D drive. same result.

**Comment by isanae** [comment]
What files do you have in `C:/Program Files (x86)/Steam/steamapps/common/Skyrim Special Edition/`?

**Comment by renfenghuan** [comment]
![image](https://user-images.githubusercontent.com/64941682/100491583-a6aaf880-311c-11eb-8edc-c4153574ab75.png)


> What files do you have in `C:/Program Files (x86)/Steam/steamapps/common/Skyrim Special Edition/`?

**Comment by renfenghuan** [comment]
Also I tried use Explorer++ inside MO2, it can detect the dll files in the virtual folder. So it must be a problem with skse itself.

**Comment by renfenghuan** [comment]
I tried update the Skyrim to the newest version, and downloaded the newest version of SKSE64, and used steamless to unwrap SkyrimSE.exe.

**Comment by LostDragonist** [comment]
The fact that you cracked the game is pretty important.  SKSE plugins break when you do that.

**Comment by renfenghuan** [comment]
But LE is fine with steamless, why?

**Comment by renfenghuan** [comment]
Thanks. I tried the original exe file, and it's ok. Looks like skse64 won't work on steamless version of SkyrimSE.exe

**Comment by LostDragonist** [comment]
The LE log you posted wasn't from a Steamless install so the crack method is different.  The difference in cracks is why we don't support cracked games.  You can try adding -forcesteamloader to the arguments for SKSE but it's not on us if it doesn't work.  Closing as it's not related to MO2.

**Comment by renfenghuan** [comment]
By the way, Vortex works fine with steamless file. So it's still an issue for MO2.

**Comment by renfenghuan** [comment]
I just moved from Vortex to MO2, and got this issue.

**Comment by LostDragonist** [comment]
Cool. Don't care.  We don't support cracked games.

**Comment by renfenghuan** [comment]
I didn't crack the game. I bought it. I just don't want to boot up steam everytime.

**Comment by LostDragonist** [comment]
Crack = modifying the game executable to remove DRM.  It doesn't mean you pirated it.

**Comment by isanae** [comment]
@renfenghuan Can you come by the discord? It'd be easier to have a look at this.

**Comment by renfenghuan** [comment]
Sure.

**Comment by vsTerminus** [comment]
> You can try adding -forcesteamloader to the arguments for SKSE

Sorry to necro this old thread but if I stumbled on it then others will too.

I just wanted to confirm that this worked perfectly for me running Skyrim SE 1.6.353 in MO2 with a Steamless .exe file

Also possibly worth noting, I'm running this on Arch Linux + Lutris + wine-ge-8.

With the recent release of SkyrimSE 1.6.1130 and the way it breaks things I'm probably not the only one who decided "Ok enough is enough" and used depot downloader + Steamless to create a copy of Skyrim on a specific version that is detached from Steam and not at risk of being updated ever again. So this might come in handy.
