### ISSUE TITLE
Fallout 4/Wasteland Melody's Service Rifle plugin keeps getting deactivated

### ISSUE THREAD

**Issue by schmittcw** [ModOrganizer2/modorganizer#1309]
### Problem:
On a frequent but inconsistent basis, the plugin associated with Wasteland Melody's Service Rifle, "1CAS_ServiceRifle.esp", will be deactivated.

### Details:
I can **fairly** consistently reproduce this by opening xEdit, but I also occasionally encounter it after installing a mod, opening a mod's options window, opening the overwrite folder, etc. But sometimes it will remain active, with no indication I can see of why it was deactivated or not.

The game launches just fine with the plugin active, and xEdit reports no errors.

**Caveat**: I am also using "SREP REDUX - Service Rifle Expansion Project", which overwrites that plugin.

### Environment:
Mod Organizer Version that exhibits the issue: Latest release, 2.3.2
Last Mod Organizer Verison that did not exhibit the issue (if applicable): Unknown (only installed in this version)
Desktop OS/version used to run Mod Organizer: Windows 10 Education, build 1909

**Comment by Holt59** [comment]
Could you try reproducing this with debug log enabled and then upload the logs here (remove sensitive information beforehand)?

**Comment by schmittcw** [comment]
Here you go!

[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/5653860/mo_interface.log)
[usvfs log](https://drive.google.com/file/d/1po3Ngv34dAf5VTPFkxGSSzOjV5KAMhko/view)

**Comment by Al12rs** [comment]
The only thing that comes to mind is that your loadlrder.txt or pluginlist.txt are read-only in your profile folder.
Otherwise it's a pretty obscure bug in pluginlist refresh code.

**Comment by schmittcw** [comment]
Well, I'd tried making them read-only at one point to see if it would prevent the issue - with no change in behavior. And as many times as I add and remove plugins, I should have seen this more often if that was the case. So that leaves likely some quirk buried in the refresh code.

FWIW, I gave up on that rifle a while ago (wasn't that exciting to me in game). So this issue no longer bothers me. Thanks for looking into it!

**Comment by Holt59** [comment]
I can reproduce quite easily with a simple refresh, no need to run an executable. The problem is likely that `plugins.txt` is case-sensitive or something like that and it gets messed-up because the original file is `1CAS_serviceRifle.esp` but the overwriting one is `1CAS_ServiceRifle.esp`.
