### ISSUE TITLE
Package Analyzer plugin

### ISSUE THREAD

**Issue by josephsmendoza** [ModOrganizer2/modorganizer#1317]
**Is your feature request related to a problem? Please describe.**
When installing malformed archives, mod organizer presents a dialog asking the user to find the data directory

**Describe the solution you'd like**
Use my [Package Analyzer](https://github.com/josephsmendoza/Package-Analyzer) to automatically resolve these situations when possible, or implement similar logic for automatic resolution.

**Describe alternatives you've considered**
Writing the code myself: I'm a whiny baby who hates python and C. don't wanna do it.

**Additional context**
I wrote the package analyzer specifically because I often find these malformed packages have a folder called "Data" and I lowkey lose my shit at how frustratingly simple it is to automate that, so I made a program for it.

**Comment by Al12rs** [comment]
We already implement fully what the package analizer offers in each of our installer plugins.

Each installer plugins is given a tree of the contents of the archive and the plugin then decides whether they can, with good confidence, handle the automatic or guided installation of that archive.

Can you present a specific scenario that you don't think is currently supported correctly and should be automated?
There is the possibility that some scenarios weren't automated because we couldn't know for sure if the user wanted to also use stuff from other folders.

For example:
ArchiveRoot/
  - data/
    - someplugin.esp
  - someOptionalFolder/
    - optionaltexture.dds

**Comment by Al12rs** [comment]
You mentioned you don't like python or C (MO2 uses c++ but I don't think that will change your opinion), but in case you wanted to know what MO2 is doing, here is the plugin that handles quick installation:
https://github.com/ModOrganizer2/modorganizer-installer_quick/blob/master/src/installerquick.cpp

The main MO2 code calls `isArchiveSupported()` and passes a file tree to the plugin that will be used by it to decide.

**Comment by Holt59** [comment]
Like AL said, we already implement similar features for the data folder, plus we can have game-specific fix.

The basic installer system is not exactly like yours: we check if the current folder is valid, according to the game, if it's not, we look for a folder and recurse in it. The main difference with your analyzer is that we only recurse if there is one folder with "useless" files around. In 2.3.2, we only ignore text files (`.txt` and `.pdf`), but starting from 2.4 other files will be ignored, see https://github.com/ModOrganizer2/modorganizer-installer_quick/blob/master/src/installerquick.cpp#L76

If you find archives that MO2 does not handle automatically, you should open issues with these specific archives explaining what MO2 could do to auto-detect them (or come by the Discord and discuss this with us there).

I recently did a Oblivion build with about 200 mods and, with the 2.4 changes, I don't think I found a single archive that MO2 did not recognize.

**Comment by josephsmendoza** [comment]
In that scenario, I would actually prefer that both the data and optional folder are listed as candidates, and I could simply pick one or both. That's on the future plans for my package manager. I think the case that I originally referenced is the one you described. A mod comes packaged with a data and screenshots folder, but I always choose to discard the screenshots. In this case, I suppose I would rather be presented with the option to discard the extra data, since there is an obvious data folder, before being asked to locate the data folder, which results in discarding the extra data anyways if the provided instructions are followed in that dialogue. A future version of my package analyzer may implement that kind of decision tree in the available results, but the current version doesn't provide any better functionality over what is already in MO.
