### ISSUE TITLE
 Files overwritten, persistent problem after reinstall

### ISSUE THREAD

**Issue by lobstek** [ModOrganizer2/modorganizer#1321]
## The problem:

The problem started when I tried to install a file that makes Skyrim HD, it said that overwrite something and every file got the symbol of missing information, now even from nexus, it has the symbol "!", the mods from nexus I am able to query info and get rid of that. Also, I need to press all the time "refresh" to be able to see the mods.
I can't just drop mods anymore and mods are not and mods have "information missing" on the downloads tab, also I have to refresh every time

## To Reproduce:

1. Drop the mod on the download tab
2. SYmbol appears of information missing and the mod doesn't show until I click on the refresh
3. either the mod is having the ticket in plugin automatically after I ticket the one mod tab
4. the status for these mods are "installed: if I click query info just says "downloaded"
5. I erased everything and started again (game and mod organizer)

## Environment:

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Verison 2.3.2
* Desktop version also

## Details:
I use to drop files in MO2 download section and installed them without any problem, but I installed a mod that changes something and the issue started. now all the time that I drop a mod it says ! "information missing", Querry info. (I'm installing mods from loverslab) so nexus doesn't query the info for these mods. then it asked me for the id and again is not from nexus so I can't get the id.

![image](https://user-images.githubusercontent.com/70252431/102422975-ccf5e280-3fbc-11eb-8ed6-4fc7032d69a2.png)

### USVFS:
https://gist.github.com/lobstek/937b360b833eed3cf27a0ce7ac1403cf

### MO Interface:
https://gist.github.com/lobstek/581296a713e4bcc741a662293f011b95

In addition, I reinstalled Skyrim LE and SE, I changed from MO@ portable to desktop and the issue continues. I erase all data files in app/local.
When I reinstalled the mod it still recognizes my previous file where the game was even if it was change and everything was erased from zero.

**Comment by Al12rs** [comment]
Well if the file isn't from Nexus you just skip querying info for those files. You will not have update checks but that is a given since it's not from nexus. The warning isn't an error it's just there to advise querying info. If you know it can't be done you can ignore it and install the mod.

**Comment by lobstek** [comment]
I can do that with nexus mods, but mods from outside like loverslab I cant. either I  can't just drop the mods anymore.

**Comment by Al12rs** [comment]
So ignoring the warnings, what exactly is the problem?

**Comment by lobstek** [comment]
Before this issue, there were no warnings, no message of missing info, no need to query for mods. drag and drop still working but now I need to refresh every to see the new  file dropped before was autmatically

**Comment by LostDragonist** [comment]
If you're not able to drag .7z, .rar, etc. files to the downloads tab, then you're probably running MO as admin.  The only solution for that is to stop running MO as admin.  

Restarting MO might also help with the "having to refresh thing" if this is a brand new instance.  MO is always a bit wonky with the downloads tab during the first start up of any instance.

**Comment by Al12rs** [comment]
The refresh issue is completely unrelated to the query warning. The refresh is skipped during certain operations of the downloads tab to avoid chaining multiple   refreshes (this used to cause hard freezes as tens or hundreds of refreshes were triggering off of each other since some operation created files in the download folder.

The failsafe mechanism could potentially get stuck and the download tab will not refresh or there are changes in the folder. Closing and opening mo2 should fix it.

**Comment by lobstek** [comment]
the drop and drag refresh was because I was running as admin, thank you for that info. So the main issue now it's just the query and it asks for mod ID from outside nexus, even from nexus if don't do the query, a thing that didn't happen before :(

**Comment by Al12rs** [comment]
It asks you to query *because* it doesn't know the origin of the file. How can mo2 know that the file is not from Nexus unless it tries to query it?

**Comment by Al12rs** [comment]
Just double clicking on the file tries to query it now or does it install as normal?

**Comment by lobstek** [comment]
I can install normal, It's just annoying because that didn't happen before. and what calls my attention is that I erased completely the game and mod organizer and deleted reminding files, when I reinstalled mod organizer (portable to desktop) it was still asking me where was the game (previous path and also the same log window.  I think the mod is using another file that I dunno where is to gather the information. 

the file tries to query when I double-clicking

**Comment by lobstek** [comment]
> Just double clicking on the file tries to query it now or does it install as normal?

If I'm not connected to nexus tries to query, if I'm connected and the file is installed already goes back to "downloaded", but the esp. reminds installed

**Comment by isanae** [comment]
You seem to have basic problems with using Mod Organizer. Come by [the discord](https://discord.gg/j7zYEwRshA) and we'll give you a hand.
