### ISSUE TITLE
SKSE64 won't launch through MO2

### ISSUE THREAD

**Issue by menguele** [ModOrganizer2/modorganizer#1337]
Whether it is with or without any plugin loaded.
Trying to open without the forwarding done by MO2, SKSE is able to load successfully
[usvfs-2021-01-01_07-35-32.log](https://github.com/ModOrganizer2/modorganizer/files/5758727/usvfs-2021-01-01_07-35-32.log)
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/5758728/mo_interface.log)

EDIT:Tested the "create another profile" but only partially resolves the problem, once I use mods it all go back to "CTD state", even w/o using any mod, again.

**Comment by LostDragonist** [comment]
You need to set your logs to debug for them to show anything interesting.  Settings > Diagnostics > Log Level > Debug.  Then restart MO, recreate your problem, and upload your logs again.

>once I use mods it all go back to "CTD state", even w/o using any mod, again.

This doesn't make much sense.  Are you using mods or are you not using mods?

**Comment by menguele** [comment]
I see...
Turns out this new profile reported a error with the "Simply Knock SE" mod, the other profile only reported something in overwrite, so I sadly deactivated it and SKSE was launched

> This doesn't make much sense. Are you using mods or are you not using mods?

I had created a blank profile, then launched SKSE, it had launched successfully. Then I tried with my mods, and the problem was back
