### ISSUE TITLE
UI mods not being recognized.

### ISSUE THREAD

**Issue by B0iledEGG** [ModOrganizer2/modorganizer#1343]
For whatever reason UI mods that I download aren't being recognized in both MO2 and loot. It downloads and installs it, but does not recognize it as a plugin. The mods affected are: Nameplates, MCM, Full Dialogue Interface and Def_UI. All other mods are fine and working.

**Comment by isanae** [comment]
None of the mods you mention contain plugins. Plugins are `.esm`, `.esp` or `.esl` files. That's why these mods are not in the Plugins tab in MO and LOOT doesn't see them.

**Comment by B0iledEGG** [comment]
Do you know a way to fix it, cause I have no idea what to do?

**Comment by isanae** [comment]
Fix what? What problems are you having? Not seeing these mods in the Plugins tab or in LOOT is normal.

**Comment by B0iledEGG** [comment]
I see. So I shouldn't be too worried then?
