### ISSUE TITLE
Since v2.3.0 RC1 the GUI is not shown (QT known issue)

### ISSUE THREAD

**Issue by ElektroStudios** [ModOrganizer2/modorganizer#1344]
## The problem:
Since v2.3.0 RC1, the GUI is not shown in rare circumstances.

## To Reproduce:
I don't know, this bug does not affect every user.

## Environment:

* Mod Organizer Version that exhibits the issue: Any version after 2.2.2.1
* Last Mod Organizer Version that did not exhibit the issue (if applicable): 2.2.2.1
* Desktop OS/version used to run Mod Organizer: Windows 10.0.18363.959 x64

## Details:
The issue surely it is related to the change to Qt 5.14.2.0. This is a "known" issue that we debated about in this other repo from **RPCS3** emulator:

https://github.com/RPCS3/rpcs3/issues/8409

The workaround for **RPCS3** emulator was to downgrade three ofthe QT dlls to version 5.13.2, however if I try to apply this same workaround by copy/paste QT dlls from **ModOrganizer** v2.2.1 into v2.3.x, when I try to launch the executable it throws critical errors and does not run.

Kepp the thread from **RPCS3** repo as a reference point, since devs commented and finally they managed to solved the issue. by upgrading to Qt 5.15.x

Then, I suggest to downgrade to Qt 5.13.2 or upgrade to Qt 5.15.x in order to avoid some users this strange issue that affects the current Qt dll version and so maximize compatibility with all systems.

**Comment by LostDragonist** [comment]
This sounds like the regional settings issue where Qt tries to provide the user a warning that their decimal symbol and digit grouping symbol are the same.  This mostly affects users that have had to change their decimal symbol for some reason and didn't change the digit grouping symbol.

This should be fixed in Qt 5.15.1 or 5.15.2 which is pulled into more recent dev builds of MO 2.4.0.  

Thanks for report!

**Comment by ElektroStudios** [comment]
> their decimal symbol and digit grouping symbol are the same

It is that!!, awesome discovery!!.

> This mostly affects users that have had to change their decimal symbol for some reason and didn't change the digit grouping symbol.

In fact I think this issue will affect at least every user that during the OS installation selected Spanish culture settings in the installer, because in my Spanish Windows O.S by default a dot is specified for decimal and miles separator in the regional settings (although in our country we use the comma for decimals in real life scenarios), don't ask me why.

In the regional settings If I change the decimal separator to use a comma, **ModOrganizer** v2.3.x loads the GUI, if I keep the dot for both decimal and miles separator, it doesn't load.

I'm very used to use the dot as decimal separator in programming and seeing it every time in the O.S (eg. when reading a file size in the Explorer), so using a comma for decimals in the O.S would become very annoying to me.

An update of the QT libs to 15.x is required in ModOrganizer to fix this failure from Qt devs!

**Comment by ElektroStudios** [comment]
I'm not sure where to download the dev build that you mentioned, or maybe it is only available for devs of this project?. I would like to test the program execution using **MO** 2.4.0 while keeping my default regional settings. For this reason I'm also not sure if I need to close or leave open this issue. As you wish, without testing it I think the update to use Qt 15.5.x will be the key to solve this.

**Comment by LostDragonist** [comment]
We post all dev builds to the #dev-builds channel in our discord (https://discord.gg/vD2ZbfX).  

Here's a link to 2.4.0 alpha 5b: https://mega.nz/file/bV1TlSKS#2x4pTmD8mo879PjecsolAmFY2GYNdnHcYCfnTIZLLQ8

**Comment by ElektroStudios** [comment]
Thanks. I confirm it works regardless of my regional settings for decimal and miles separators.
