### ISSUE TITLE
Incorrect game path update for game plugins with executable in subfolders

### ISSUE THREAD

**Issue by Holt59** [ModOrganizer2/modorganizer#1346]
When updating the game path through the settings dialog, users have to specify the game executable and MO2 then deduce the game path from the executable.

Currently MO2 consider that the game folder is the folder containing the executable, which is not true for games for which the executable is in a sub-folder such as Darkest Dungeon from basic games.

This should be changed to take into account the actual value from `binaryName()` 

https://github.com/ModOrganizer2/modorganizer/blob/master/src/settingsdialogpaths.cpp#L100

**Comment by isanae** [comment]
This is going to be a bit of a pain. The settings dialog doesn't care about game plugins right now, it actually uses what's in the texbox as a filter for the filename, it doesn't even ask the plugin. It'll have to get the binary path from the plugin and remove that from the selected path. It also means it has to check that the selected path ends with the binary path correctly.

**Comment by isanae** [comment]
Also, this is a showstopper for 2.4.
