### ISSUE TITLE
"Install mod here" or "Install mod at this position" - this is crucial, please implement.

### ISSUE THREAD

**Issue by Atlntssplayer** [ModOrganizer2/modorganizer#1369]
**Is your feature request related to a problem? Please describe.**
Yes my feature request is related to a problem. The problem is when I install a mod it gets put at the bottom and the window scrolls to it's position. Now I have to either drag it to the position I want or send it to a prio or to a separator, because the chances that I want it at the bottom are astronomically tiny, unless I'm just putting a completly new setup together and I install all mods in the right order from the very beginning, which is very unlikely.
These actions in themselves take more time and clicks than the mod installation.
This makes installing mods on a medium or long setup very cumbersome and it's slower than it could be.

**Describe the solution you'd like**
2 possible solutions I see.

1: If the user right clicks in the left panel and uses the "Install mod" menu then the mod installed this way should be put at the position where he clicked. Just below the mod he highlighted with his click. So if he right clicked at a mod that is at priority 30, the newly installed mod should be put at prio 31. This way he can skip the very cumbersome  part of sending the mod to this position from the bottom.

2nd: If you don't want to alter the "Install mod" behavior, put in a new menu, something like "Install mod here" or "Install mod at this position".

**Describe alternatives you've considered**
There is no alternative I can think of. Suffering more and wasting time and putting more clicks into my old and tired fingers.

**Additional context**
I'm a big fan by the way. MO is great, has been forever. You guys are great.
If you guys having trouble implementing this little qol feature, you can always ask the magus who did Collapsible Separators. He must be like totally hella smart. He will know what to do.
Thank you for everything!

**Comment by isanae** [comment]
The most recent devbuild on the discord supports dragging downloads over the mod list to install them and they'll have the priority of where you dropped it. Is this good enough?

**Comment by Atlntssplayer** [comment]
I'm sorry to say, that the downloads part of MO is completely irrelevant to my use case or how I use MO and how I mod the games. I don't use MO to download mods, I download them manually and put them into different folders on my disk and I install them from there. I do this on a different computer than which I mod and play because most of the time I don't have internet connection on the one I run the game on. And also because I like to keep all the mods I have in the structure I want and not in a single download folder where MO would put them.

**Comment by isanae** [comment]
You can drag from the Downloads tab, but it also works with files from Explorer.

**Comment by Atlntssplayer** [comment]
I'd have to see how it feels to drag & drop from the file manager then, because I'm not used to doing it, I just never use drag & drop.

thx

**Comment by Al12rs** [comment]
Can you test it and let us know? 
Adding an Install Mod context menu option under All mods next to Create mod and Create separator doesn't sound like a bad idea though.

**Comment by Atlntssplayer** [comment]
It works nicely using 2.4.0a5b. I can drag & drop a .zip from a file manager into MO to a certain position.

I'd just need to keep this in mind to be able to try and break my long time habit of using the big "Install a new mod from an archive" button or using the right click -> All mods. -> Install mod menu.
If you think lots of people would welcome putting this into the context menu then it's up to you guys. I have no idea how much work it needs or what other considerations there are when you decide if you put in something or not.

**Comment by Atlntssplayer** [comment]
Oh, also "Create emtpy mod" and "create separator " options are missing from the "Open list options..." button, but that is probably another ticket.

**Comment by Al12rs** [comment]
Yeah that has already been fixed internally. Also Holt already made a Pull Request for the making the Install Mod option use the current position. Linked above.

**Comment by Atlntssplayer** [comment]
Wow, that was insanely fast. Thanks alot!

Now lets hope that other people won't complain that the behavior of that menu changed and it doesn't install mods at the now. I know I'm not the only one with their own little OCD when it comes to modding. :)
