### ISSUE TITLE
Force query?

### ISSUE THREAD

**Issue by kleshas** [ModOrganizer2/modorganizer#1381]
## The problem:
I downloaded a modlist's mods last year, and ended up with loads of mods with a version number of 0.0.0.0 in MO2 (iirc nexus was partly down, allowing downloads but not meta or something?).  Right-clicking the mod shows no option for query like there is for mods with an empty field for version.

* Mod Organizer Version that exhibits the issue: 2.2.1

As there is a 0.0.0.0 there is a .meta file and if this was an issue for all my downloaded mods I could just delete all .meta files and manually query each mod.  But there are hundreds of mods WITH 0.0.0.0 and hundreds with a correct version number.  
I'm looking for a way to force a query in all circumstances

**Comment by Al12rs** [comment]
Can you try installing the latest version of Mo2 ([2.3.2 from Nexus](https://www.nexusmods.com/skyrimspecialedition/mods/6194?tab=files) ) and see if the issue persists?
2.2.1 is really old (2019)

**Comment by kleshas** [comment]
Unfortunately I can't as I'm on linux and am using lutris-se-installer which is stuck on 2.2.1 for now.
I DO have a slow workaround, delete all .meta's from that time frame, refresh and I now have a huge list of version <null>.  I can then delete all the small ones (I'll just redownload) and can manually query the large ones.

**Comment by Al12rs** [comment]
I'm afraid we can't help you much if you are stuck with that older version of mo. We didn't hear of similar issues on the latest version so I can only assume this is already fixed there. You might be able to write a script to manually update the meta.ini of all mods affected. Like if you know some python or bash or something like that.

**Comment by Al12rs** [comment]
(closing since it isn't relevant to current version, feel free to continue the discussion if you have questions)
