### ISSUE TITLE
Can't get SKSE SE to launch from MO2

### ISSUE THREAD

**Issue by Ciderking09** [ModOrganizer2/modorganizer#1394]
Been trying to make the jump to both SSE and Mod Organizer the past couple of weeks. I've been trying to get this _going_ for the past couple of weeks, but every attempt I make at trying to launch SKSE results in a CTD before I even get to black screen. It's like MO2 just gives up. I tried uninstalling ALL mods and doing a clean reinstall of SSE. I wiped all logs and scripts. I made sure to pedantically reread install instructions for every mod as well as SKSE and resolve every conflict I knew of as well as LOOT. I even tried deactivating all ESP's just see if that would work, didn't fare any better. I went looking for crash logs for SSE (searched the internet and couldn't find anything--just normal gameplay logs that wouldn't help with this issue). Coming from Oldrim, this is the cleanest modlist I've ever compiled so I have _no_ idea what the problem could be. Launching the SKSE loader from the SSE folder works fine. Launching the vanilla loader works fine. So I'm down to mods and MO2, but I've already tried deactivations to see if it'd launch. I tried a quarter, half, and 75% deactivation and SKSE still wouldn't launch. I've already mentioned deactivating everything. I even tried the -forcesteamloader argument and that didn't work either (Oldrim-specific I think; correct me if I'm wrong). LOOT and MO2 both say everything's green. Any suggestions?

I've attached my MO2 Debug Log if that helps.
[usvfs-2021-02-04_01-16-50.log](https://github.com/ModOrganizer2/modorganizer/files/5923183/usvfs-2021-02-04_01-16-50.log)

Here's the load order as well--generated by LOOT. The Bashed Patch is for Leveled List mods. I made sure Garrus Axes and Blanket Scarves had the correct bash tags for the merge as well.
[LOOT Load Order.txt](https://github.com/ModOrganizer2/modorganizer/files/5923228/LOOT.Load.Order.txt)

Apologies to anyone taking the time to help, but I'm really stuck.

**Comment by isanae** [comment]
Can you come by the discord? It'd be much easier to diagnose the problem.

**Comment by Ciderking09** [comment]
Heading over now.
