### ISSUE TITLE
Hide/exclude/delete files from another mod

### ISSUE THREAD

**Issue by mihaifm** [ModOrganizer2/modorganizer#1396]
Sorry if this has been raised before. Let's say I want to make a mod that fixes another mod by deleting a few files. Is this currently possible in MO2?

I know I can manually open the other's mod folder and delete the files, but it's not a very clean way of doing it. If the original mod gets updated I need to go and delete the files again. It can get messy if you have hundreds of files.

I know you can have .mohidden files, but a file named let's say `x.nif.mohidden` doesn't override `x.nif`, so you can't hide `x.nif`

It would be a nice feature for several reasons:
- clean separation of mods, no more messing with a mod's internal file structure
- makes filesystem operation complete (addition + subtraction of files)

Thanks

**Comment by mihaifm** [comment]
I think the easiest way to implement this would be via a new extension, let's say `.modelete` or `.moignore`. A file named `abc.moignore` will override `abc` and hide itself at the same time.

**Comment by mihaifm** [comment]
I went ahead and created a plugin to solve this. It works a bit different than what I described above but it takes care of the problem.

https://www.nexusmods.com/skyrimspecialedition/mods/52097
https://github.com/mihaifm/broom

**Comment by Al12rs** [comment]
Wow awesome work! I added the plugin to our list of Mo2 plugins here: https://github.com/ModOrganizer2/modorganizer/wiki/List-of-MO2-Extension-Plugins
