### ISSUE TITLE
Shortcuts don't work with a portable installation if ModOrganizer is close

### ISSUE THREAD

**Issue by UnchartedSystems** [ModOrganizer2/modorganizer#1406]
Desktop & Start Menu shortcuts bring up an error prompt: "Instance at "C/Users/USERNAME/AppData/Local/ModOrganizer/Portable" not found. Select another instance. This error does not occur if mod organizer is open. This issue is not fixed by enabling administrator privileges

**Comment by LostDragonist** [comment]
Confirmed broken in 2.4.0 RC 1.1
