### ISSUE TITLE
MO2 locks up when I try to run any executable

### ISSUE THREAD

**Issue by qualityassuance** [ModOrganizer2/modorganizer#1412]
It shows a white box with Mod Organizer ? at the top. Happens from any instance on my computer.

**Comment by Holt59** [comment]
Please don't put your whole issue in the title... It's hard to understand the problem. The "Lock" dialog is normal, MO2 just locks itself when running an executable. What are the actual issue you're having with that lock dialog?

**Comment by qualityassuance** [comment]
Apologies, I've never used github before. But yes I get the lock dialog, but once I do MO2 freezes/stops responding and the dialog box stays as a white box indefinitely until I close it with task manager. No matter what executable, no matter which instance of MO2, even on a different hard drive, the application freezes if I try to run anything from inside it. It started completely out of nowhere, nothing was changed from within nor where the files changed. I've restarted my computer, done everything I can think of to no avail, I'm at wits end here.Sent via the Samsung Galaxy S10, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Mikaël Capelle <notifications@github.com> Date: 2/17/21  6:16 AM  (GMT-05:00) To: ModOrganizer2/modorganizer <modorganizer@noreply.github.com> Cc: qualityassuance <kkearns91@gmail.com>, Author <author@noreply.github.com> Subject: Re: [ModOrganizer2/modorganizer] MO2 locks up when I try to run any
  executable . Shows a white box with Mod Organizer ? at the top. Happens from
  any instance on my computer. (#1412) 
Please don't put your whole issue in the title... It's hard to understand the problem. The "Lock" dialog is normal, MO2 just locks itself when running an executable. What are the actual issue you're having with that lock dialog?

**Comment by isanae** [comment]
1. Go in the Settings, Diagnostics tab, change the log level to Debug.
2. Restart MO.
3. Go in the logs folder for your instance. Upload `mo_interface.log` here.

You can find the logs folder by clicking the folder icon just above the mod list and selecting "Open MO2 Logs Folder".

**Comment by GiovanH** [comment]
I can confirm I'm experiencing this same issue. It's instance-specific, and seems to have something to do with the VFS being in a bad state.
