### ISSUE TITLE
Witcher 3 mod install location

### ISSUE THREAD

**Issue by GF-Huang** [ModOrganizer2/modorganizer#1414]
The mod: [Witcher 3 - Enhanced Edition](https://www.nexusmods.com/witcher3/mods/3522?tab=description) should install file at the root directory of the game. But MO install all the mod files into the `Mods` folder. How to custom this behavior?

Should install into `C:\Users\iFeng\Games\Steam\steamapps\common\The Witcher 3`,
But actually MO install into `C:\Users\iFeng\Games\Steam\steamapps\common\The Witcher 3\Mods`.

![image](https://user-images.githubusercontent.com/4510984/108554504-24069380-732f-11eb-8d1b-bae9dc8b888b.png)

**Comment by Al12rs** [comment]
Mo2 can't handle most mods that go on the top level. So the plugin was made to target the mods folder directly. USVFS is loaded after the load time dlls and the like so it is too late for most top level mods. You can manually edit the game plugin in your Mo2 folder, plugins/basic_games/games/game_witcher3.py , by changing the GameDataPath value to "" and try it out to see if it works. 

Reopen if you want to continue the discussion or come talk with us directly on discord: https://discord.gg/2ap8nmtete
