### ISSUE TITLE
Improvement / Minor Bug: C# FOMOD installers always overwrite the mod directory

### ISSUE THREAD

**Issue by Silarn** [ModOrganizer2/modorganizer#142]
# The problem

C# FOMOD installers (NCC) always overwrite the current mod directory in the process of running the installer. Basically, the installer files are extracted removing any existing files. Then the C# installer is compiled and run. The results of this are then wiped and rewritten into the Mod directory again. We should reroute this so that the actual C# extraction and execution routes to Temp and then writes the files to the Mod directory with the appropriate replace/overwrite dialog.

# Environment

Frankly I'm not sure. It could be an old issue as the C# installer code hasn't really changed. Definitely happening on current development builds.

**Comment by GrantSP** [comment]
Oh this is an excellent suggestion. Kudos to you if you can wrangle it.

**Comment by ewillett804** [comment]
I am testing a small fix for this now.  Thanks,

**Comment by Al12rs** [comment]
Maybe the new installer by @Holt59 will not have this issue and we will be able to close this
