### ISSUE TITLE
Styles don't affect the download list anymore

### ISSUE THREAD

**Issue by isanae** [ModOrganizer2/modorganizer#1427]
The widget type was changed from `DownloadListWidget` to `DownloadListView`. We need to either fix all the qss files or just rename it back.

**Comment by Holt59** [comment]
I'll fix the `.qss`, I changed the name because it was inconsistent with the other tree views.

**Comment by isanae** [comment]
There's a bunch of them, some in repos we don't control, so they will need PRs and hope owners will accept them.

**Comment by Holt59** [comment]
> 
> 
> There's a bunch of them, some in repos we don't control, so they will need PRs and hope owners will accept them.

Yes, we'll see. If don't think all the themes require change (some seems to be working fine).

**Comment by Holt59** [comment]
PR opened. 
- The `mob` PR will update most 3rd-party themes, except the new "Transparent Morrowind" theme,  but it does not use `DownloadListWidget` so it's fine.
- The `modorganizer` PR will update all the other themes.

So this should cover everything (for the download list).
