### ISSUE TITLE
MO 2.4 'profile specific ini' option not working and only read and store Fallout4 savedata into \Documents\My Games\Fallout4\__MO_Saves\ 

### ISSUE THREAD

**Issue by noc9109X** [ModOrganizer2/modorganizer#1428]
## The problem:
MO is only reading ini in 'MyGames' that under 'Documents', with or without 'profile specific game-ini' option

## To Reproduce:

just updated to 2.4.0, and MO would only read and store Fallout4 savedata into \Documents\My Games\Fallout4\__MO_Saves\ , (not 'Fallout 4' folder in MyGames, it is 'Fallout4' folder which without a space ) ( MO could recognize saves for different profiles, as it could shows saves in the <saves> tab on the right part of the MO )

turns out it was cause by the fallout4customs.ini in MyGames that has 'sLocalSavePath' nor 'useMyGamessave' lines, if I remove the  'sLocalSavePath' and 'useMyGamessave' lines, the game would read saves from \Documents\My Games\Fallout4\saves\, and I also tried editing some other lines, only the edits in 'MyGame' folder works, and I'm 100% certain that there is no 'sLocalSavePath' nor 'useMyGamessave' lines in any of my game ini that stored in profile folder, or mods' ini files

the issue was only on Fallout4, SkyrimSE are perfectly fine (tried both archive and installer that both are downloaded from github, tried manually 'rip' MO2 protable instance from SkyrimSE to Fallout4, tried enable Modorganizer.exe with 'run as administrator' in its property option, none of the methods could work)

## Environment:

* Mod Organizer Version that exhibits the issue: 2.4.0
* Last Mod Organizer Version that did not exhibit the issue (if applicable): 2.3.2
* Desktop OS/version used to run Mod Organizer: Win10 pro x64 19042, only have Windows Defender and excluded entire MO2 and the steam folders

my settings.ini in my profile folder is
[General]
LocalSaves=true
LocalSettings=true
AutomaticArchiveInvalidation=false

all the other ini files in my profile folder (GitHub can't upload ini so I changed them into txt)
[fallout4.txt](https://github.com/ModOrganizer2/modorganizer/files/6026702/fallout4.txt)
[Fallout4Custom.txt](https://github.com/ModOrganizer2/modorganizer/files/6026704/Fallout4Custom.txt)
[fallout4prefs.txt](https://github.com/ModOrganizer2/modorganizer/files/6026705/fallout4prefs.txt)
[initweaks.txt](https://github.com/ModOrganizer2/modorganizer/files/6026706/initweaks.txt)
[ModOrganizer.txt](https://github.com/ModOrganizer2/modorganizer/files/6026707/ModOrganizer.txt)
[settings.txt](https://github.com/ModOrganizer2/modorganizer/files/6026708/settings.txt)

my MO logs:
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/6026561/mo_interface.log)
[usvfs-2021-02-22_13-06-23.log](https://github.com/ModOrganizer2/modorganizer/files/6026562/usvfs-2021-02-22_13-06-23.log)
[usvfs-2021-02-22_13-03-12.log](https://github.com/ModOrganizer2/modorganizer/files/6026563/usvfs-2021-02-22_13-03-12.log)
[usvfs-2021-02-22_12-59-07.log](https://github.com/ModOrganizer2/modorganizer/files/6026564/usvfs-2021-02-22_12-59-07.log)
[usvfs-2021-02-22_12-45-56.log](https://github.com/ModOrganizer2/modorganizer/files/6026565/usvfs-2021-02-22_12-45-56.log)
[usvfs-2021-02-22_12-33-14.log](https://github.com/ModOrganizer2/modorganizer/files/6026566/usvfs-2021-02-22_12-33-14.log)

**Comment by LostDragonist** [comment]
The only reason MO would be looking in the __MO_Saves folder is if one of the INI files has that as the sLocalSavePath.  You'll want to look in the fallout4.ini and fallout4custom.ini in your MO profile.  When you find that setting, delete the whole line.

Note that you may have to or want to move files from that __MO_Saves directory to the normal saves directory or into a profile's saves directory.

**Comment by noc9109X** [comment]
> The only reason MO would be looking in the __MO_Saves folder is if one of the INI files has that as the sLocalSavePath. You'll want to look in the fallout4.ini and fallout4custom.ini in your MO profile. When you find that setting, delete the whole line.
> 
> Note that you may have to or want to move files from that __MO_Saves directory to the normal saves directory or into a profile's saves directory.

thanks mate and I was aware of it, but I can't find any line neither in fallout4.ini nor fallout4prefs.ini, and my fallout4custom.ini were blank. my guess is that some mod folder containing an ini that has the sLocalSavePath line, still looking

**Comment by Al12rs** [comment]
To be clear if you want profile specific Saves to work you need to let Mo2 write that line in the INI files. 
Please reopen if this is still an issue.
