### ISSUE TITLE
[Enhancement] Is it possible to add text descriptors to the logs?

### ISSUE THREAD

**Issue by GrantSP** [ModOrganizer2/modorganizer#143]
In looking through logs I'm always trying to figure out what certain lines mean when comparing mine to those of users with issues. Doing so I find a lot of information is too esoteric for me to decode and thus I'm left blind.
e.g.1
`DEBUG (18:17:52.0874): createfile w: C:\Users\GrantSP\AppData\Local\Skyrim\plugins.txt -> D:\Games\ModOrganizer\TES5\profiles\Default\plugins.txt (0 - 3) = 00000AD4 (0)
DEBUG (18:17:52.0874): createfile w: C:\Users\GrantSP\AppData\Local\Skyrim\plugins.txt -> D:\Games\ModOrganizer\TES5\profiles\Default\plugins.txt (80000000 - 3) = 00000AD4 (0)`

What do the numbers at the end of each line mean and can text descriptors be inserted into the logging to make these sort of things more clear to non-coders?
e.g.2
`DEBUG (18:17:47.0292): hook for CreateProcessA installed at 750544B0 (trampoline at 03670000)`

I'm guessing the last number is a memory address but what about "trampoline"?

This should be viewed very low down on the list of TODOs but nonetheless I think it might be useful to many.

**Comment by SuperSandro2000** [comment]
I don't think that a better description would enhance the logs in anyway. Logs are considered for developers and people that know what to do with them and additionally these are debug lines so their only purpose is it to inform the developer about what is going on.

**Comment by GrantSP** [comment]
Logs are not only used by developers.
This should be considered a very low priority but adding them in would make a very big difference to support teams all over the place.
Not everyone immediately goes to the Discord to get their issue solved and aiding others to diagnose issues, even if it's just pinpointing exactly what the problem is and then telling the developers of that, makes for a more streamlined process.
