### ISSUE TITLE
MO2 2.4.0 overscans my screen - buttons are offscreen

### ISSUE THREAD

**Issue by TastelessOne** [ModOrganizer2/modorganizer#1432]
## The problem:
(Unable to ask my question on your Discord: "Messages failed to load.")

1920x1080 resolution. Windows 10.0.18363
I was able to change the theme by moving the taskbar to the side. But that no longer brings the buttons on view.
Screencap here: 
https://imgur.com/a/u8dsULQ

## Environment:

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your latest USVFS log, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by LostDragonist** [comment]
The settings window has a minimum size of around 450 x 560 pixels.  Given your screenshot, you probably have your DPI scaling in Windows set to 200% which would make it 900 x 1120 pixels, pushing the bottom of it off your screen.

We might be able to rejigger stuff to lower the minimum size or get stuff to reflow automatically or something.  In the meantime, you can access the buttons by reducing your DPI scaling in Windows.

**Comment by TastelessOne** [comment]
My scaling is at 150%. I'll try going smaller. (Could the size be made user adjustable?)

**Comment by LostDragonist** [comment]
It is adjustable to some extent but the reason there's a minimum is because stuff would start getting hidden at that point.  The page would require some rework to make that not happen.

**Comment by TastelessOne** [comment]
I'm getting a headache trying to read the screen. I'm going to put MO2 aside for now.

**Comment by LostDragonist** [comment]
https://github.com/ModOrganizer2/modorganizer/pull/1447 fixes this in the next release, 2.4.1.
