### ISSUE TITLE
Deleted executables come back when MO2 is restarted

### ISSUE THREAD

**Issue by BustinJay** [ModOrganizer2/modorganizer#1440]
## The problem:
I have executables that I wish to delete as I have renamed them to something else, when I click the "Remove the selected executable" button they appear to be deleted. However, when I relaunch the program they have returned and are cluttering up my list of executables.

## To Reproduce:

1. Select executable from list within the "Modify Executables" menu
2. Click the "Remove the selected executable"
3. Click Apply and OK
4. Close MO2
5. Relaunch MO2

## Environment:

Mod Organizer v2.4.0, I believe this problem occurred prior to updating as well.

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
USVFS GIST - https://gist.github.com/BustinJay/619a685256f645b93294a1ae7cbb4633

### MO Interface:
MO Interface GIST - https://gist.github.com/BustinJay/87609f3d15ead8f50e3d6f3c061e061a

**Comment by isanae** [comment]
MO will always recreate [default executables](https://github.com/ModOrganizer2/modorganizer/wiki/Executables-window#default-executables). Are you getting this problem with custom executables or just the default ones?

**Comment by BustinJay** [comment]
> 
> 
> MO will always recreate [default executables](https://github.com/ModOrganizer2/modorganizer/wiki/Executables-window#default-executables). Are you getting this problem with custom executables or just the default ones?

The ones that will not delete are "NVSE" and "Construction Kit"

![image](https://user-images.githubusercontent.com/79729978/109371151-cf987200-7860-11eb-922c-6b0d423317f8.png)

Are these considered default executables? If so, I'm not sure exactly why MO2 prevents me from both being unable to rename them or delete them? It's not a huge problem but it's a bit annoying that they're cluttering my list of executables, when I'd rather name them something else.

**Comment by isanae** [comment]
For Fallout NV, the default executables are the main exe, the launcher, NVSE, FOMM, the CK, BOSS and LOOT. The reason they're automatically re-added on startup are explained on [the wiki](https://github.com/ModOrganizer2/modorganizer/wiki/Executables-window#default-executables).

Basically, if we add a new default executable in the future, it has to be added automatically to the list when you start MO. So MO doesn't know the difference between "this is an old executable that should be there but the user has deleted it" and "this is a new executable that was just added in this version and must be added". Differentiating between the two would require a bunch more code that nobody's written yet.

If you want to hide the executable from the dropdown, you can check the ["Hide in user interface"](https://github.com/ModOrganizer2/modorganizer/wiki/Executables-window#hide-in-user-interface) option for it.

**Comment by BustinJay** [comment]
> 
> 
> For Fallout NV, the default executables are the main exe, the launcher, NVSE, FOMM, the CK, BOSS and LOOT. The reason they're automatically re-added on startup are explained on [the wiki](https://github.com/ModOrganizer2/modorganizer/wiki/Executables-window#default-executables).
> 
> Basically, if we add a new default executable in the future, it has to be added automatically to the list when you start MO. So MO doesn't know the difference between "this is an old executable that should be there but the user has deleted it" and "this is a new executable that was just added in this version and must be added". Differentiating between the two would require a bunch more code that nobody's written yet.
> 
> If you want to hide the executable from the dropdown, you can check the ["Hide in user interface"](https://github.com/ModOrganizer2/modorganizer/wiki/Executables-window#hide-in-user-interface) option for it.

The "Hide in user interface" option is all I need, thank you.
