### ISSUE TITLE
Print out exceptions when initializing Python

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#1451]
MO 2.4.0
An exception being thrown during initializing python only outputs this incredibly helpful message:
> [2021-03-03 18:14:44.848 E] [pythonrunner.cpp:1339] An unexpected C++ exception was thrown in python code

https://github.com/william76/boost-python-tutorial/blob/master/part2/handle_error.cpp shows how to hopefully get more information about these kinds of exceptions... I think?  The repo itself doesn't have a license though it's for a publicly available tutorial.

**Comment by Holt59** [comment]
That's already done. If the error is not converted it's usually because it's being thrown before everything else is set up.

**Comment by Holt59** [comment]
To be precise, if the exception happens when initializing a Python plugin, the "conversion" is done. If the conversion is not done it means the exception happens during or before the initialization of `mobase`.
