### ISSUE TITLE
Error "failed to parse config file" when sorting

### ISSUE THREAD

**Issue by Durgen1** [ModOrganizer2/modorganizer#1459]
I'm trying to use the sort function for M02 but get this error, the sort function works fine for other games but not Skyrim SE. I tried allowing M02 though my fire wall for my anti virus software, I tried turning off my firewall completely as well as windows defender. Nothing has worked so far. And I was hoping I could get some help with this.

A firewall may be blocking LOOT.
Git operation failed. Details: -1; failed to parse config file: invalid configuration key (in C:/Users/Me/AppData/Local/LOOT/Skyrim Special Edition/.git/config:1): libgit2 error

**Comment by isanae** [comment]
Delete the folder `C:/Users/Me/AppData/Local/LOOT/Skyrim Special Edition` and try again.

**Comment by Durgen1** [comment]
I tried it and I still get the same error, thank you for responding so quickly btw.

**Comment by isanae** [comment]
Can you upload the file `C:/Users/Me/AppData/Local/LOOT/Skyrim Special Edition/.git/config` here?

**Comment by Durgen1** [comment]
Yea of course here's the whole file, without the mods or override files. Unless you need those as well, if you need anything else from me lmk.
[Skyrim Special Edition.zip](https://github.com/ModOrganizer2/modorganizer/files/6120407/Skyrim.Special.Edition.zip)

**Comment by isanae** [comment]
I need `C:/Users/Me/AppData/Local/LOOT/Skyrim Special Edition/.git/config`, not the content of your instance. Note the `LOOT` folder. I'm asking for the file that LOOT is complaining about.
