### ISSUE TITLE
Issue with dll files

### ISSUE THREAD

**Issue by JeremiahRoland** [ModOrganizer2/modorganizer#1464]
I recently did some mod tweaking with GECK on my Fallout TTW instance. After I was done using GECK, MO2 says there are some incompatible plugins. Specifically, some dll mod files. For reference, these files are Charisma Overhaul, Mod Limit Fix, StewieAI's Tweaks, NVTF, OneTweak, EnhancedCamera, and UI Organizer Plugin. All of these mods are updated, xNVSE is updated, and most strange of all, all the plugins still work when in game. There's no issue with their performance, but MO2 keeps the error message that those plugins failed to load.
Honestly, I don't think it's that big of a deal since they do still work. Just thought I'd bring it to your attention. Maybe you know a fix for it, or maybe it's just some new bug?

**Comment by isanae** [comment]
MO just reports what `ttw_nvse.log` says. Can you have a look at it?

**Comment by JeremiahRoland** [comment]
The ttw_nvse.log simply had my esp load order. I looked through the other log files and the issue was in nvse_editor.log. It was the one saying those dll files weren't loading, even though some of the other log files said that they were. I removed that log file and the issue is resolved. Not sure if this is just a temporary fix, but hopefully it was simply just a bug.
