### ISSUE TITLE
Select multiple files at once in Downloads tab

### ISSUE THREAD

**Issue by sibir-ine** [ModOrganizer2/modorganizer#1468]
**Is your feature request related to a problem? Please describe.**
Unlike most other tabs (e.g. Plugins, Data, Saves), users aren't able to select multiple files at once in the Downloads tab i.e. to delete or install multiple files at a time.

**Describe the solution you'd like**
It'd be convenient for users to be able to shift-click to select a list of mods & control-click to select multiple mods.

**Describe alternatives you've considered**
Users can always open the Downloads folder & select multiple files, but it'd be convenient to be able to do it within MO2. Users wouldn't have to worry about .meta files that way as well.

**Comment by isanae** [comment]
Duplicate of #725.
