### ISSUE TITLE
[Question] Has MO2 been updated to support Cyberpunk 2077 v1.2?

### ISSUE THREAD

**Issue by dep-deprecated** [ModOrganizer2/modorganizer#1487]
I understand the mod path was changed from `archive/pc/patch` to `archive/pc/mod`. Just curious. I loaded up MO2 with CP2077 mods, and they don't seem to appear in the game.

**Comment by Holt59** [comment]
The MO2 plugins uses the base path of the game as the mod folder so you probably needs to edit your MO2 mods to change the path (manually unfortunately).

**Comment by SiTWulf** [comment]
No, all the Mods than use .DLL or similar not work.
Only the Normal MODS works.

The main problem if the DLL Mods (For example CET) need to be HardLink
