### ISSUE TITLE
Can't change profiles

### ISSUE THREAD

**Issue by SHGoldfarb** [ModOrganizer2/modorganizer#1489]
## The problem:

I am trying to change profiles, but when I select another profile and click "Select" the profiles dialog closes but the active profile does not change.

## To Reproduce:

1. Click on the "Profiles" button. A dialog will open with a list of profiles and actions.
2. Create a new profile.
3. Select that new profile either by double clicking it or selecting it and then clicking the "Select" button.
4. The dialog will close but the new profile will not activate, instead the old profile will still be active.

Note: Changing the profile manually in `ModOrganizer.ini` works correctly.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.4.1. I initially installed 2.4.0 and this issue was also present.
* Last Mod Organizer Version that did not exhibit the issue (if applicable):--
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details:
--

### USVFS:
https://gist.github.com/SHGoldfarb/abce4b68a6419f98ac27b8a6ddbf9ea3

### MO Interface:
https://gist.github.com/SHGoldfarb/d6cbaef95eb4a0a21e8f8f76aa04d3a5

**Comment by SHGoldfarb** [comment]
Just noticed that selecting the profile in the profiles dropdown over the mods list works just fine. This solves my problem. I don't know if this is still an issue, you may close it as far as I'm concerned.

**Comment by isanae** [comment]
Confirmed, it works fine when switching from the dropdown, but not from the toolbar or menu.
