### ISSUE TITLE
false bsa tag

### ISSUE THREAD

**Issue by bloodparty74** [ModOrganizer2/modorganizer#1490]
im using mo2 for skyrim se, ive noticed lately that a small mod i created to edit a character,has a bsa flag even though it does not contain a bsa, also if i hover over it ,it says it loads the archives of every bsa in my game that starts with the letter d.  it doesnt seem to have any effect in game, or actually causing me any problem, i just found it very strange. ive tried renaming the mod, and the .esp, and moving it in my load order, but it made no difference, a strange bug, just figured id report it, thanks for all the great work on mo2.

**Comment by LostDragonist** [comment]
The archive association is overly loose for Skyrim SE. Having a plugin called "d" will indeed make MO think every archive that starts with "d" is associated with that plugin.  This is due to other games following this method of archive association.

**Comment by bloodparty74** [comment]
ok thanks for the response. i had renamed it but i just renamed it from d. stormcloud to d. stormcloud ck edit. glad to know to avoid these sort of names in the future. thanks a bunch keep up the good work
