### ISSUE TITLE
Moving collapsed separator doesn't move mods.

### ISSUE THREAD

**Issue by richardaubin** [ModOrganizer2/modorganizer#1493]
## The problem:
Moving a collapsed separator containing mods doesn't move the mods, only the separator .

## To Reproduce:

1. Collapse a separator that has mods underneath.
2. Move the collapsed separator .
3. Expand the separator 
4. See no mods
5. Go find missing mods
6. Move mods back under separator .

## Environment:

Latest

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your latest USVFS log, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by Holt59** [comment]
That's on purpose. You can Alt+Click to select a separator and all its children (even if the separator is collapsed) and then move them all at once.

**Comment by richardaubin** [comment]
all right! Thanks!
