### ISSUE TITLE
endorsement integration

### ISSUE THREAD

**Issue by frozenparagon** [ModOrganizer2/modorganizer#1494]
due to previous version issues in vortex I refuse to use it for any Bethesda games and exclusively use MO2 for those, but one thing vortex has that MO2 would benefit from and make it vastly easier for me to catch up on endorsing all the mods that I hadn't bothered with back when I first started using nexus would be an endorsement toggle option. I Do periodically go through and retroactively endorse mods, but... it's a long list. this feature would be a boon for players and modders alike so if it wasn't being considered previously hopefully it is now.

**Comment by AnyOldName3** [comment]
I don't understand what you're asking for. We already have endorsement integration, and you can select multiple mods at once you endorse all of them.

**Comment by Al12rs** [comment]
![image](https://user-images.githubusercontent.com/26797547/115910103-baa91b00-a46c-11eb-8790-5057d341f46b.png)
![image](https://user-images.githubusercontent.com/26797547/115910183-ceed1800-a46c-11eb-9a05-287b9ad044b6.png)
![image](https://user-images.githubusercontent.com/26797547/115910244-e4624200-a46c-11eb-933f-621414b41802.png)

**Comment by Al12rs** [comment]
Assuming that is what you were asking about I'll close, feel free to reopen if that wasn't it.
