### ISSUE TITLE
Add support for game Valheim

### ISSUE THREAD

**Issue by micah686** [ModOrganizer2/modorganizer#1510]
- **Name:** Valheim
- **Short name:** valheim
- **Executable:** valheim.exe
- **Data path:** valheim_Data
- **Saves directory [optional]:** %AppData%\LocalLow\IronGate\Valheim
- **Save extension [optional]:** Characters:*.fch, Worlds: *.db. *.fwl
- **Steam ID [optional]:** 892970

**Provide additional details regarding the game that could be required for the plugin.**

The game is made in Unity, and here is the default folders/files  
[Valheim tree structure.txt](https://github.com/ModOrganizer2/modorganizer/files/6410772/Valheim.tree.structure.txt)

And here's the folder structure of the normally used modLoader:  
[modLoader.txt](https://github.com/ModOrganizer2/modorganizer/files/6410775/modLoader.txt)

**Comment by Martan404** [comment]
Yes please
