### ISSUE TITLE
Path Change

### ISSUE THREAD

**Issue by dankston05** [ModOrganizer2/modorganizer#1512]
Every time I start up skse or LOOT through mod organizer it keeps resetting all the paths

**Comment by isanae** [comment]
What paths are you talking about?

**Comment by dankston05** [comment]
> What paths are you talking about?

The base directory path, download path, mod path, etc. The base directory keeps changing to my c drive when the directory is in my d drive

**Comment by LostDragonist** [comment]
Every time I've seen this it's been because of an aggressive anti-virus that goes around deleting a bunch of MO2 files.

**Comment by dankston05** [comment]
> Every time I've seen this it's been because of an aggressive anti-virus that goes around deleting a bunch of MO2 files.

Thank you, I ran as administrator and now everything is working.

**Comment by isanae** [comment]
@dankston05 Note that running MO as administrator is not a very good permanent solution. It just hides the symptoms: there's something on your system that is preventing it from accessing files on the drive. With the amount of crap code I put it in, I wouldn't run MO as admin.

**Comment by dankston05** [comment]
The only thing I can think of that is blocking it would be ccleaner or windows

**Comment by isanae** [comment]
I'm closing this because it's not a problem with MO. If you need a hand figuring out what to do, come by the discord, we'll be happy to help.
