### ISSUE TITLE
Can't execute anything after long time not using MO2

### ISSUE THREAD

**Issue by parasiteoflife** [ModOrganizer2/modorganizer#1517]
## The problem:
After a lot of time (many months, since march 2020) of not using this instance of Fallout 4 I decided to play the game again, I loaded the instance and MO2 complained that the game path was wrong (I installed the game on another path this time so it was all good), changed the paths of every single executable as they were pointing to the old game path and supposedly everything was good, all the mods and downloads were loaded OK but then everytime I wanted to execute anything be it Fallout4.exe, Fallout4Launcher.exe, f4se, Explore Virtual Folder, everything fails with the following message:

```
Error 5 ERROR_ACCESS_DENIED: Acceso denegado. (0x5)
 . binary: 'L:\Games\Fallout 4\f4se_loader.exe'
 . owner: BUILTIN\Administradores
 . rights: (normal rights)
 . arguments: ''
 . cwd: 'L:\Games\Fallout 4'
 . stdout: no, stderr: no, hooked: yes
 . MO elevated: yes
 . usvfs x86:ok x64:ok proxy_x86:ok proxy_x64:ok
```

I can open every executable directly so there is no problem there, the problem is in MO2. MO2 can't even start Steam. Even tried deleting the ini and still the same.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.4.2 rc1.1 was happening also with 2.4.2
* Last Mod Organizer Version that did not exhibit the issue (if applicable): the one from march 2020, I don't know the exact version.
* Desktop OS/version used to run Mod Organizer: Windows 10 20H2

### USVFS:
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/6431369/mo_interface.log)

### MO Interface:
[usvfs-2021-05-06_02-24-00.log](https://github.com/ModOrganizer2/modorganizer/files/6431370/usvfs-2021-05-06_02-24-00.log)

**Comment by isanae** [comment]
You seem to somehow have ESET, Kaspersky _and_ Defender all active at the same time. I'm guessing they might be interfering.

**Comment by parasiteoflife** [comment]
> You seem to somehow have ESET, Kaspersky _and_ Defender all active at the same time. I'm guessing they might be interfering.

Yeah I saw that too but it is weird. I had Kaspersky before but it's now uninstalled (since long time actually, I even used kaspersky remover official tool), Defender is and always has been disabled system wide (through policy) and ESET is currently disabled too. I don't know why is picking up Defender and Kaspersky.

**Comment by parasiteoflife** [comment]
I just saw a couple errors like this in event viewer:

```
Nombre de la aplicación con errores: ModOrganizer.exe, versión: 2.4.2.0, marca de tiempo: 0x608e12b6
Nombre del módulo con errores: Qt5Core.dll, versión: 5.15.2.0, marca de tiempo: 0x5fa4dd3b
Código de excepción: 0xc0000005
Desplazamiento de errores: 0x000000000048f778
Identificador del proceso con errores: 0x290c
Hora de inicio de la aplicación con errores: 0x01d7421eace998e0
Ruta de acceso de la aplicación con errores: C:\Games\MO2\ModOrganizer.exe
Ruta de acceso del módulo con errores: C:\Games\MO2\dlls\Qt5Core.dll
Identificador del informe: ae58fb3c-7d51-4732-9caf-e4d0d7bed697
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores: 
```

I don't know if they are related.

**Comment by isanae** [comment]
Can you upload the most recent file in `C:/Users/parasiteoflife/AppData/Local/ModOrganizer/Fallout 4/crashDumps`?

**Comment by parasiteoflife** [comment]
Here is the latest one, I had a couple files though.

[ModOrganizer-2.4.2-20210506T030840.dmp.zip](https://github.com/ModOrganizer2/modorganizer/files/6431499/ModOrganizer-2.4.2-20210506T030840.dmp.zip)

**Comment by parasiteoflife** [comment]
Ok, after rebooting my PC am now able to launch the programs without problems. Should this issue be closed?
I have no clue at what happened, I haven't installed any other program much less any AV.
