### ISSUE TITLE
MO won't launch at all

### ISSUE THREAD

**Issue by beldura** [ModOrganizer2/modorganizer#1527]
My Mod Organier won't launch

Instantly, my MO stopped working in the middle of nowhere. I installed some mods, MO crashed, and I haven't been able to restart it since.
Currently when I run it I see it open in task manager (so I tried closing it). When I try to restart it, it tells me "an instance of MO is already running".
So I have already deleted my latest mods and then reinstalled the software, but the situation is still the same.

* Mod Organizer Version that exhibits the issue: Mod Organizer 2 2.4.2
* Last Mod Organizer Version that did not exhibit the issue (if applicable): Mod Organizer 2 2.4.2
* Desktop OS/version used to run Mod Organizer: Windows 10

**Comment by isanae** [comment]
Try deleting the `webcache` folder that's in your instance. If you're using a portable instance, you should see it in MO's installation folder. If not, it should be inside your instance folder in `C:\Users\username\AppData\Local\ModOrganizer\`.

**Comment by beldura** [comment]
It worked, thank you !

**Comment by marcsiqueira** [comment]
Sorry to bother you guys but i'm having the same problem and the solution didnt not worked for me as there wasnt even the folder there to be deleted. I freshly installed it and i try to start the application but nothing happens, even tho i can see it in the taskmanager as if it was running, but no visible application what so ever...

**Comment by M-313an** [comment]
marcsiqueira, I hope this helps even though maybe this is too late. Just delete python.dll, I started having problems with mod organizer2 (like your problem) when I downloaded python. If you don't have python then im so sorry, I don't have any other solution.

**Comment by Silarn** [comment]
That's a potentially problematic solution. MO2 is built against a specific version of Python and deleting the embedded Python dll will only work if your local Python is a compatible version which is also available on the system path.

Windows should always prioritize a dll that's in the same directory as the application you're running as well, there's really no reason installing Python should interfere with MO2. In fact that's how I generally have my system set up.

**Comment by nimiwio** [comment]
Just wanted to add another potential fix for anyone who stumbles across this - try updating Visual C++ Redistributable on your machine. This fixed it for me

**Comment by User0057** [comment]
> Just wanted to add another potential fix for anyone who stumbles across this - try updating Visual C++ Redistributable on your machine. This fixed it for me

^This^ worked for me, thanks nimiwio.

**Comment by timdespair** [comment]
> Just wanted to add another potential fix for anyone who stumbles across this - try updating Visual C++ Redistributable on your machine. This fixed it for me

worked for me too, it wouldn't launch, wouldn't have believed this kind of advice would work!
