### ISSUE TITLE
Version numbers for mods are date the mod was downloaded.

### ISSUE THREAD

**Issue by kinkybrewster** [ModOrganizer2/modorganizer#1532]
![mod organizer 2 issue](https://user-images.githubusercontent.com/30942430/120088726-84cd0700-c0a8-11eb-9ac8-7c432b137cac.jpg)
The title says it all. Mod version numbers are today's date (5/29/2021) instead of their actual version number. Screenshot included. I've never had this issue before and I'm not sure what the cause is. Fresh install of everything on Windows 10.

**Comment by LostDragonist** [comment]
When installing the mod, did you import the downloads to MO2, query info on them, and then install them from the downloads tab?  That's the only way the version will be auto-populated (for most mods).

**Comment by kinkybrewster** [comment]
I did, so I'm not sure wtf is up. It's weird. am I able to manually fix the listed version or would I need to try uninstalling and reinstalling to see if it auto-populates?

**Comment by LostDragonist** [comment]
Sure, you can always change that info manually.  Select the mod and click on the version field.  Or double-click the mod and go to the Nexus tab.

I'm unable to reproduce any issues here.  /shrug.  Maybe post a screenshot of your downloads tab if you think you did all that correctly?
