### ISSUE TITLE
Asking to Unpack BSA??

### ISSUE THREAD

**Issue by tsunami2311** [ModOrganizer2/modorganizer#1537]
Recent build of Mo2 start asking me I want to "unpack" Bsa in Unofficial Patch. Anyone else notices this? It never did this before

At this point in time the mod skyrim has I use that still update is the Unoffical patch and they all ask me if I want unpack BSA now since the new builds. is there reason why Mo2 is asking this now??

**Comment by Al12rs** [comment]
The unpacker plugin was disabled by default before. After the update we removed the disabled by default thing for plugins so it now asks when installing new mods with BSAs if you want to unpack (and it recommends not to). So press no and you are good.

**Comment by LostDragonist** [comment]
It should actually *not* ask by default as of one of the latest versions but it depends on what versions you had installed when as to what your configuration settings are.  In any case, you can always turn off that functionality in the MO2 settings, plugins tab.

**Comment by tsunami2311** [comment]
2.4.2 and it been asking for past  2 verisons? i cant remeber. I have told it no and made it remeber it, but i never change anything it just start with recent builds.

Assuming BSA Extractor
Should be set to false
which is is at now since i made it remeber the not to ask
