### ISSUE TITLE
Mo2 admin issue/ refuses to open apps. 

### ISSUE THREAD

**Issue by Roguespectre101** [ModOrganizer2/modorganizer#1539]
## The problem:
Mod organiser opens but won't launch any apps e.g Skyrim/ skse and when I try to launch an app it says that steam is running in administrator however I have checked and as far as I can tell it is not. I've tried a clean reinstallation of both Skyrim and mo2 and skse all of which repeated the issue I've tried fixing the issue myself but I can't figure out how to fix it hence why I'm posting here as I'm guessing this is an issue with mo2. 

On a side note, the app will run if you press continue however with the warning of crashes I don't know if that's ideal or not. 

## To Reproduce:

1. Go to MO2
2. Click on any application
3. run 
4. https://imgur.com/a/yhiVLA5 this pops up
5. accept the pop-up/ run as admin
6. try again same issue

## Environment:

* Mod Organizer Version that exhibits the issue: 2.4.2
* Last Mod Organizer Version that did not exhibit the issue (if applicable): I have got mo2 to work completely on a different computer last year however on my current pc the one with the issue I haven't been able to get mo2 to work properly :( .
* Desktop OS/version used to run Mod Organizer: windows 10 build 19043

## Details:
Here is the pop up that appears whenever I try to run a app via mo2 https://imgur.com/a/yhiVLA5

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
https://gist.github.com/Roguespectre101/4ea7bed2667444eaa46fe02ab28fa921#:~:text=https%3A//gist.github.com/Roguespectre101/4ea7bed2667444eaa46fe02ab28fa921
### MO Interface:
https://gist.github.com/Roguespectre101/4ea7bed2667444eaa46fe02ab28fa921#:~:text=https%3A//gist.github.com/Roguespectre101/4ea7bed2667444eaa46fe02ab28fa921

**Comment by LostDragonist** [comment]
There's nothing in the logs that say you tried to run the game through MO so the actual problem wasn't captured.

The only thing I can guess at this point is that AVG is doing something that prevents MO from messing with Steam.  MO can't really tell the difference between that and Steam being run as admin.  

That said, if running the game works and your mods work, it's probably fine to ignore the dialog and just "continue".

**Comment by Roguespectre101** [comment]
Is there any way I could capture the issue in my mo2 logs? I've set avg to ignore the file paths for steam, mo2 and its directories.
As for the game running if I press continue on the pop up the game seems to run and it loads skse however I haven't got any mods installed as of yet as I'm starting fresh on this pc.

**Comment by Roguespectre101** [comment]
Ok I've just done a few tests with avg and it looks like that was the culprit now as soon as I start skse through mo2 it launches immediately no need for pop-ups or warnings seems to have fixed the issue. I was just super confused as I haven't had this issue with mo2 before on a pc so had no idea how to fix it but it seems to be working correctly now though.
