### ISSUE TITLE
auto snap

### ISSUE THREAD

**Issue by bloodparty74** [ModOrganizer2/modorganizer#1544]
i recently reinstalled mo2 from scratch on a different pc. and im having a small problem that when i try to shrink mo2 from the top it auto minimizes. no other screens are doing this only mo2. i researched it and made sure it is turned off in win 10.  i also looked at mo2 ini, found this[ auto_collapse_on_hover=false] i dunno if this means that but i changed it to true and tried it, but it didnt help, any advice on fixing this?

**Comment by Al12rs** [comment]
auto_collapse_on_hover is for modlist separators while drag and dropping mods. Nothing to do with what you described. I don't know what your issue is but it sounds like a windows issue
