### ISSUE TITLE
[Game Request] Subnautica and Subnautica Below Zero

### ISSUE THREAD

**Issue by BrandonPotter0** [ModOrganizer2/modorganizer#1547]
I do apologize if this is the incorrect format to do this, but I would like to put in a 'request' for game support for Subnautica and Subnatuca Below Zero. 

I have attached 2 screenshots of the location of where the mod folders for these games 'QMods' where mods get installed to.

If more information is needed, Please let me know :)

![Subnautica Mods Folder Location](https://user-images.githubusercontent.com/54760537/124818115-7a135680-df1f-11eb-9a6c-34d03a6d2a3e.jpg)
![Subnautica_BZ Mods Folder Location](https://user-images.githubusercontent.com/54760537/124818118-7aabed00-df1f-11eb-8ed0-bdc84066544a.jpg)

**Comment by Al12rs** [comment]
There is a dedicated Issue template for requesting game support that details all the required information. We very likely don't own or have the time to find out about those info ourselves. Please open another issue with the required information.
