### ISSUE TITLE
Revert Download tab sorting back to <=2.4.0 ways

### ISSUE THREAD

**Issue by ixanza** [ModOrganizer2/modorganizer#1551]
**Is your feature request related to a problem? Please describe.**
Back in versions up to 2.4.0 the downloads tab was sorted by

Downloaded New to Old > Installed New to Old > Uninstalled New to Old

However in 2.4.1 and 2.4.2 they're now sorted by

Downloaded Old to New > Installed Old to New > Uninstalled Old to New

This makes following mod guides or downloading mod requirements a bother to keep up with as now the install order and viewing order of mods to install is reversed

**Describe the solution you'd like**
Downloads tab sorting to be reverted to 2.4.0 and below versions

**Describe alternatives you've considered**
Downgrading to 2.4.0 but that doesn't work in Windows 11 anymore.

**Comment by Qudix** [comment]
![Sort](https://user-images.githubusercontent.com/17361645/125160351-02714180-e142-11eb-93de-6e126c06513c.gif)
Or am I misreading what you mean?

**Comment by Al12rs** [comment]
I think he means while sorting by Status

**Comment by Qudix** [comment]
That would make sense. I wasn't aware that it worked that way.

**Comment by ixanza** [comment]
Yes sorry while sorting by status.

Lemme pull up a comparison real quick. Here's how it is sorting by status in 2.4.2

![image](https://user-images.githubusercontent.com/5535758/125160493-c1177b00-e1af-11eb-869d-4b76abecc7ad.png)

And compared to sorting by status in 2.4.0
![image](https://user-images.githubusercontent.com/5535758/125160527-f91ebe00-e1af-11eb-998d-7cce63c84388.png)

The bottom one is a lot better because I can clearly see the mods I most recently installed as well as the downloaded mods in new to old order whereas the top one, I don't need to see the mods I installed a looong time ago IMO

**Comment by Al12rs** [comment]
Yeah I already found the issue. We fixed a bug where uninstalled would always be at the top when opening MO2, by reversing the order in which Status is sorted by default, but we didn't invert the sorting of the filetime together with it, so now it appears as reversed. I'm trying to build it to check but my dev env is broken

**Comment by Al12rs** [comment]
Ok, I give up, it won't build.
I think just changing the `<` to `>` here should do it: https://github.com/ModOrganizer2/modorganizer/blob/e7f15ff4fd95adc5edefc312609e1610c1bf10f9/src/downloadlist.cpp#L276

If someone else wants to test it and push it feel free.

**Comment by Al12rs** [comment]
The Pull Request above should have it fixed. Maybe someone will make a dev build on discord one of these days and you will be able to use that. I don't think 2.4.3 is coming out any time soon

**Comment by Al12rs** [comment]
I put up a dev build on discord
