### ISSUE TITLE
Filter for facegendata

### ISSUE THREAD

**Issue by Atlntssplayer** [ModOrganizer2/modorganizer#1556]
Bethesda games can contain assets related to faces and whatnot and these are in the "facegendata" folder.

Please make it so that users are able to filter for this.

This folder is usually in:
meshes\actors\character\
textures\actors\character\

I don't know if it can be in other places too. I've only ever seen it at these two places but it might be possible a mod puts it at a custom place, I'm not sure.

The point is that some mods contain these kind of assets and it would be useful if the user could filter for these.

Thank you!

**Comment by Al12rs** [comment]
Someone would need to edit all 15 or something game plugins

**Comment by Atlntssplayer** [comment]
So I guess that means it takes a lot of time and work.

Would it be too much to ask to only do it for SSE so it's just a fraction of the time and that is what probably most people use MO2 for. Also no big secret, that is what I'd like to have this feature for too.

I'd do it myself but the source code looks like a martian language to me, I'm not a computer guy.

Anyway thx for what all of you put into MO2 so far, it's an invaluable tool.

**Comment by Al12rs** [comment]
I was wrong, Holt made it so it could be changed from just one repo. 
It's just a filter for now and not an icon in the content column. I don't have an icon for it. If you have a black/white 32x32 icon that could work I could add it maybe.

**Comment by Atlntssplayer** [comment]
Great!

I searched for icons. I found a free icon pack of 32x32 faces here: https://emily2.itch.io/pixel-portraits-32x32
I picked a few female and male ones I thought look better and converted them to black and white and saved in .png format.
Pick whichever you like. I don't know how it will actually look in MO2 though. :)
If you don't like any of these, I can search for more.

The artist if you want to credit them is: Exuin

![female_02__icon_by_Exuin__black_and_white](https://user-images.githubusercontent.com/18383444/125943525-b99d3065-155c-42b7-981c-e6bb7ed935ec.png)
![female_09__icon_by_Exuin__black_and_white](https://user-images.githubusercontent.com/18383444/125943535-c39351d0-03c5-42dd-b52f-518893269fc2.png)
![male_01__icon_by_Exuin__black_and_white](https://user-images.githubusercontent.com/18383444/125943541-3cd328ed-224d-4677-880f-7a0635684b90.png)
![male_03__icon_by_Exuin__black_and_white](https://user-images.githubusercontent.com/18383444/125943544-f3dbeb9b-b9a0-4de3-afe7-75afd48726c2.png)
![male_04__icon_by_Exuin__black_and_white](https://user-images.githubusercontent.com/18383444/125943546-c39ee717-fd8b-4973-a325-3bc81c19759d.png)
![male_07__icon_by_Exuin__black_and_white](https://user-images.githubusercontent.com/18383444/125943550-5b7b76f1-66a0-4b06-bc22-2db62e81054e.png)
![male_10__icon_by_Exuin__black_and_white](https://user-images.githubusercontent.com/18383444/125943553-c3a2c715-493d-4716-9080-9bbf3f068149.png)
![male_14__icon_by_Exuin__black_and_white](https://user-images.githubusercontent.com/18383444/125943556-95bb6027-ef2a-4c9c-bf33-806371b149a6.png)

**Comment by Al12rs** [comment]
Those are in grayscale, while the current icons we are using are only black and white. You can see them all by hovering your mouse over the Content column header

**Comment by Atlntssplayer** [comment]
Right...paint.net said black and white, also I have no idea what I'm doing.
Anyway, these should be monochrome now.
![female_02__icon_by_Exuin__black_and_white](https://user-images.githubusercontent.com/18383444/125945097-ea76f355-6496-4933-9f5b-c4b415e28664.png)
![female_09__icon_by_Exuin__black_and_white](https://user-images.githubusercontent.com/18383444/125945101-45cbca29-975b-4c56-a4b9-1f5b804c29db.png)
![male_01__icon_by_Exuin__black_and_white](https://user-images.githubusercontent.com/18383444/125945103-21268b19-04bb-4194-9fdc-3d8fedbef028.png)
![male_03__icon_by_Exuin__black_and_white](https://user-images.githubusercontent.com/18383444/125945106-ab5a8bc4-263d-490a-932e-f1f2986c0572.png)
![male_04__icon_by_Exuin__black_and_white](https://user-images.githubusercontent.com/18383444/125945111-04cb94ce-8ca5-448f-bfc6-e992b169b4c7.png)
![male_07__icon_by_Exuin__black_and_white](https://user-images.githubusercontent.com/18383444/125945113-c0723914-8a5d-4ef3-bb45-7765295f4494.png)
![male_10__icon_by_Exuin__black_and_white](https://user-images.githubusercontent.com/18383444/125945115-9e050056-5a8a-416f-87a5-39b7d6a06519.png)
![male_14__icon_by_Exuin__black_and_white](https://user-images.githubusercontent.com/18383444/125945119-77582bb0-3bb3-4a56-ae0f-e415c6eda060.png)

**Comment by Al12rs** [comment]
I misspelled the path to the resource and spent 20 minutes trying to get the icon to show up correctly...
![image](https://user-images.githubusercontent.com/26797547/125948047-f2daa703-18c8-4c48-a055-ba21b82be678.png)

**Comment by Al12rs** [comment]
I think it looks fine

**Comment by Al12rs** [comment]
Merged everything. Next dev build on discord should have it, if I remember to rebuild all the game plugins.
