### ISSUE TITLE
Fallout NV crashes to desktop after game was repaired

### ISSUE THREAD

**Issue by Cbmnrg99** [ModOrganizer2/modorganizer#1557]
## The problem: 

So, this all started out when I wanted to download this mod: [https://www.nexusmods.com/newvegas/mods/36835](url). But this mod wasn't like other mods. This one was one you manually had to install and then enable a plugin in the mod manager. So, I followed the instructions but got stuck trying to enable the .esp file in the mod manager, not knowing at the time that it was at the plugin tab. But, I did notice that the .esp file shows up on the game launcher, so I just checked the box located under data files and went with it. Of course, it didn't work. So, I did the wrong thing and installed the mod again while using mod orgainizer while my original download of the mod was still in the game folder. Still didn't work. So then, I got pissed and deleted the mod files, both on mod organizer and in the game files, while also accidently deleting my game's data folder. So, I downloaded the mod again, thinking that the modded data folder will include my game's data files. It didn't. So, after repairing my game and getting my data folder back, I re-downloaded the mod and followed the instructions again. This is when I realized that the mod's .esp file was included at the plugins tab. After checking the file, I deleted this file in my game's folder: FalloutNV_lang.esp. I deleted this file because I didn't need it. This is when I noticed that there was 2 mods that were named after the mod's .exe file: ExtendedNVRGenerator and Extended New Vegas Radio Generator. Not knowing if I should check both, I deleted one of the mods. This is when I got an error from mod organizer because MO couldn't locate the NV_lang file I deleted earlier. But, strangely enough, the mod deletion still went through. Then, when I closed MO, I got another error: failed to save load error, again arising from the fact that I deleted that file. I then booted up the game through MO, using a shortcut on my desktop. The first thing I noticed was that my game wasn't in full screen; it still had the white border. And when the Bethesda logo popped up, the game crashed. So, I decided to repair the game again and get back the file I deleted. This is where I am right now. Can anyone help? What am I missing? (Sorry that this was lengthy).

## Environment:

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10

**Comment by Holt59** [comment]
You should come by the Discord server https://discord.gg/N3YfAt74, it will be difficult to help you troubleshoot your problem through Github issues.
