### ISSUE TITLE
Cant save with MO2 and Windows 11 (Skyrim SE crash)

### ISSUE THREAD

**Issue by Kintaro71** [ModOrganizer2/modorganizer#1561]
## The problem:
On my PC i've installed Windows 11 insider preview and now MO2 cannot allow me to save game on Skyrim Special Edition.
Every time i try to save or quicksave game crash and i return back on MO2.

## To Reproduce:

1. Have Windows 11
2. Launch MO2
3. Lauch SKSE trough MO2
4. Play on Skyrim SE
5. Try to save game

## Environment:

* Mod Organizer Version that exhibits the issue:  last versione 2.4.2

## Details:

Always this error on MO2 log.. 

(eg. my last entry on usvfs-2021-07-28_20-32-44.log)
[usvfs-2021-07-28_20-32-44.log](https://github.com/ModOrganizer2/modorganizer/files/6896395/usvfs-2021-07-28_20-32-44.log)

### USVFS:
22:32:53.380 [I] inithooks in process 7944 successful
22:33:12.732 [W] hook_FindFirstFileExW(): path 'Saves/' ends with slash, always fails

**Comment by Al12rs** [comment]
People have reported that windows 11 resets all your permissions and security settings, some of which try to protect files in documents folders (where the game is trying to save).
Try to disable stuff like anti ransomware protection and see if the permissions have changed on relevant folders or something.

**Comment by Kintaro71** [comment]
Disabled bitdefender and other protection stuff on windows 11 settings, nothing changed.

Tried also to set folder game outside document folder adding SLocalSavePath=..\..\..\..\..\skyrim\saves\  in order to set C:\skyrim\saves as a new target folder   (i moved my saves from mygame doc folder to the new one)

I launched SKSE via MO2, and Skyrim SE recognize the new folder & allow me to load my games but when i try to save i reproduce the same previous error.   
In the new folder i find a file named  Save4_00000000_0_447261676F6E626F726E_Tamriel_000201_20210729102049_81_1.ess.tmp   with 0KB sizes.

My Win 11 is 22000.100 release preview.

**Comment by NiceneNerd** [comment]
I can't even get it to launch on Windows 11, crashes at 94% when preparing VFS. It's not even just the game; it also applies when doing Explore or other things.

**Comment by Al12rs** [comment]
Everyone else having issues with win 11 resolved them by fixing windows defender and folder permissions. Redirecting with the INI will not help if Mo2 doesn't have permission to write in whatever folder or if his VFS dlls have been quarantined. 

Maybe try coming by the discord to discuss it in a more realtime manner

**Comment by Al12rs** [comment]
Duplicate #1596
