### ISSUE TITLE
Discord doesn't display a game launched from ModOrganizer2

### ISSUE THREAD

**Issue by svndvst** [ModOrganizer2/modorganizer#1567]
## The problem:
Discord doesn't display a game launched from ModOrganizer2. Tested one game: Stalker Anomaly
Tried to remove from Executables blacklist Discord.exe and UiOverlay.exe - it gave nothing. 

## Environment:
ModOrganizer v2.4.2
Windows 10 Pro

**Comment by Al12rs** [comment]
Have you tried manually adding it from the Discord settings under Activity Status "Not seeing your game? Add it!" ?

**Comment by Al12rs** [comment]
If that doesn't work I don't really know what to do about it.

**Comment by svndvst** [comment]
I solved it. In game settings in Other section there's separate checkbox to turn on/off the Discord status. It was just turned off :)
