### ISSUE TITLE
Executables won't start from MO2 on win11

### ISSUE THREAD

**Issue by ProdigyDxx** [ModOrganizer2/modorganizer#1568]
## The problem:
Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead. 

When trying to launch executables from MO2 - for Skyrim SE - everything goes as normal but after maybe a second the mo2 lock goes away and in the log it says nothing to wait for. this happens for xlodgen, Creation Kit, DynDOLOD and texGen but not for xEdit and Nemesis. I'm using the -sse argument where needed.

## To Reproduce:

1. Select executable
2. Click on 'Run'
3. wait for the lock on mo2 to release and for nothing to happen.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.4.2
* Last Mod Organizer Version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: win 11 (10.0.22000.120) (KB5005188)

## Link to Mod Organizer logs:
for xlodgen
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/6951637/mo_interface.log)
[usvfs-2021-08-08_23-48-05.log](https://github.com/ModOrganizer2/modorganizer/files/6951638/usvfs-2021-08-08_23-48-05.log)

for creation kit
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/6951644/mo_interface.log)
[usvfs-2021-08-08_23-52-14.log](https://github.com/ModOrganizer2/modorganizer/files/6951645/usvfs-2021-08-08_23-52-14.log)

for DynDOLOD
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/6951647/mo_interface.log)
[usvfs-2021-08-08_23-53-31.log](https://github.com/ModOrganizer2/modorganizer/files/6951648/usvfs-2021-08-08_23-53-31.log)

**Comment by LostDragonist** [comment]
> [2021-08-08 23:48:04.964 D]   . Bitdefender Antivirus (antivirus), definitions outdated
[2021-08-08 23:48:04.964 D]   . Bitdefender Firewall (antivirus)
[2021-08-08 23:48:04.964 D]   . Malwarebytes (autoupdate|antivirus)

I'm gonna assume that one of these is causing your issue.

**Comment by ProdigyDxx** [comment]
Thank you very much for the help. That solved my problem, I had to make the exceptions for each specific exe file.
That is normally one of my go to troubleshooting steps but for some reason I didn't this time.
