### ISSUE TITLE
Running an EXE through MO2 not working

### ISSUE THREAD

**Issue by OldMensch** [ModOrganizer2/modorganizer#1570]
## The problem:
I am creating an app for Fallout 4 with Python, but when I try to gain access to MO2's VFS by running my executable within MO2, my app does not run at all. Outside of MO2, my executable runs perfectly fine, but when called by MO2 it doesn't start up at all. No command prompt, no GUI window, nothing. It does briefly show that the VFS was initialized, but closes immediately.

## To Reproduce:
Create a simple script in Python that prints something (anything) and then asks for user input. Like this:
```
if __name__ == '__main__':
    print("This is a statement")
    input()
```
Then compile this into a .exe file using pyinstaller by running this in the command line:
```
pyinstaller name_of_file_to_test.py --onefile
```

Then, finally, in MO2, enter the "Modify Executables" menu and add the newly created .exe file. 

With this example code, I expect a command line menu to pop up waiting for the user to hit the enter key, after which the program will close. If you then try to run this file, you can see the VFS initializes, and then it instantly closes out as if the program finished. I would expect the "input()" line in Python to hold up the process until the user enters anything into a command prompt, but no prompt even appears. Even in the full program which I am developing which opens a proper GUI instead, it never opens, just the same. Not even a momentary flash of the GUI window. 

## Environment:
 - MO2 v2.4.2
 - Python 3.9 (64-bit)
         -pyinstaller (can run "pip install pyinstaller" to install this)
- WIndows 10 Home version 21H1 build 19043.1165

### USVFS:
[link to the GIST](https://gist.github.com/OldMensch/377db5d3f1fa86ec325e822277659b35)

### MO Interface Log:
[mo_interface.log](https://gist.github.com/OldMensch/a05d294e0462a2de1f4c81e4ab800392)

**Comment by Holt59** [comment]
I have no issue here, can you upload your `mo_interface.log`?

**Comment by OldMensch** [comment]
> 
> 
> I have no issue here, can you upload your `mo_interface.log`?

Uploaded the mo_interface log file. I also re-generated the original USVFS, though the new log shouldn't be very different from the old one

**Comment by LostDragonist** [comment]
According to that, the file is not found when calling CreateProcessInternalW.  Following the steps you've posted works fine for me.  So I guess the question is, is the file where you say it is?

**Comment by LostDragonist** [comment]
Ah, no, it's not.  You added it to a mod instead of the FO4 folder directly.  In that case, I'm going to assume that the "LooksMenu Utility" mod is disabled therefore the file does in fact not exist to the VFS.

**Comment by OldMensch** [comment]
> 
> 
> Ah, no, it's not. You added it to a mod instead of the FO4 folder directly. In that case, I'm going to assume that the "LooksMenu Utility" mod is disabled therefore the file does in fact not exist to the VFS.

Ah, this was the problem exactly! *facepalm*

Many thanks!
