### ISSUE TITLE
Why can't we move Global Instances. It keeps filling up my C drive. I just want it in a portable drive without installing dozens of mod organizers.

### ISSUE THREAD

**Issue by nate-mccay** [ModOrganizer2/modorganizer#1572]

**Comment by Qudix** [comment]
You can't move a global instance, but you can change the base directory for downloads, mods, etc.
![image](https://user-images.githubusercontent.com/17361645/129640030-3098d4d8-84a3-49db-9e73-cbeba5831d48.png)
It doesn't automatically move anything already there however, so you'll have to move those files to the new location.

**Comment by Al12rs** [comment]
Check https://github.com/ModOrganizer2/modorganizer/wiki/Moving-things for more info on how to move stuff.
