### ISSUE TITLE
error 13

### ISSUE THREAD

**Issue by Coleisnotgay23** [ModOrganizer2/modorganizer#1579]
## The problem:
Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our [discord channel](https://discord.gg/5tCqt6V)

## Environment:

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your latest USVFS log, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by Coleisnotgay23** [comment]
![Capture](https://user-images.githubusercontent.com/89362949/130373244-e26d72ea-7bc6-4892-af02-d361e9bbd3b9.PNG)

**Comment by LostDragonist** [comment]
Are you trying to mod Binding of Issac or are you trying to mod another game?

**Comment by Coleisnotgay23** [comment]
> Are you trying to mod Binding of Issac or are you trying to mod another game?

I opened the instances and saw Binding of Isaac and wanted to mod it. I changed the instance to the game and it crashed instantly. This error comes up everytime I open Mod Organizer.

**Comment by LostDragonist** [comment]
I think you want to go to `\Documents\My Games\Binding of Isaac Afterbirth+` and copy options.ini to the game directory listed in the error.  That seems like something we'll have to fix.

**Comment by LostDragonist** [comment]
Be sure you've run the game from Steam (and have Afterbirth+) so that options.ini is generated in the My Games folder specified.  If that doesn't help, I'm guessing you have some kind of anti-virus or other protection thing preventing MO from copying the file to the MO profile.  Or you have Controlled Folder Access enabled.  Or OneDrive itself is causing problems.

Hopefully something there helps.
