### ISSUE TITLE
Skyrim LE: MO2 does not launch SKSE 

### ISSUE THREAD

**Issue by GrafKostevskiy** [ModOrganizer2/modorganizer#1583]
- **Name:** Skyrim Legendary Edition
- **Short name:** skyrimle
- **Nexus ID [optional]:** ID of the game on Nexus (you can usually find this in Nexus URL).
- **Executable:** TES5
- **Launcher [optional]:** Skyrim Launcher
- **Data path:** D\Skyrim - Legendary Edition
- **Documents path:** C\User\My documents\My games\Skyrim
- **Saves directory [optional]:** 
- **Save extension [optional]:** 
- **Steam ID [optional]:**

**Provide additional details regarding the game that could be required for the plugin.** 
Through MO2 (2.4.2) skse does not start (it used to be launched) Launcher and the game starts. The paths are right. The SKSE version is the latest. Skyrim Legendary.

Skse runs from the root folder without any problems.

What could be the problem?

I run everything through the admin, tried to reinstall skse and Skyrim itself

* I use Google translator, so forgive me if something is not clear. I got to the site from MO2 "report a problem".

**Comment by LostDragonist** [comment]
Upload your log files here. Follow these steps:

1) Go in the Settings, Diagnostics tab, set Log Level to Debug.
2) Restart MO.
3) Use the "Open Folders" button to open the logs folder.
4) Try to launch the game.
5) Close MO.
6) Drop mo_interface.log and the most recent usvfs log here. You might need to zip them up first.

![](https://cdn.discordapp.com/attachments/458597400638914563/617049541350260794/openlogs.png)

**Comment by GrafKostevskiy** [comment]
# #
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/7071027/mo_interface.log)
[usvfs-2021-08-28_12-37-30.log](https://github.com/ModOrganizer2/modorganizer/files/7071028/usvfs-2021-08-28_12-37-30.log)
[usvfs-2021-08-28_14-12-09.log](https://github.com/ModOrganizer2/modorganizer/files/7071029/usvfs-2021-08-28_14-12-09.log)
[usvfs-2021-08-28_14-28-56.log](https://github.com/ModOrganizer2/modorganizer/files/7071030/usvfs-2021-08-28_14-28-56.log)
[usvfs-2021-08-28_14-30-23.log](https://github.com/ModOrganizer2/modorganizer/files/7071031/usvfs-2021-08-28_14-30-23.log)
[usvfs-2021-08-28_15-25-42.log](https://github.com/ModOrganizer2/modorganizer/files/7071032/usvfs-2021-08-28_15-25-42.log)


https://disk.yandex.ru/d/gnp3P0oI7JrHmQ

Thanks for the quick response.

Here are the logs (I don't know which ones are needed, so that's all).

Follow the link - the most recent log - it is much heavier than the others - 404 765 kb. I could not open it - notepad freezes.


Tell me if you have problems with the file sharing - I will give another

**Comment by LostDragonist** [comment]
Possibilities: 
- Bitdefender is causing problems and you may need to uninstall it.
- Avast is causing problems and you may need to uninstall it.
- Your game is pirated and that is causing problems.
- You've reached the limit of modding Skyrim LE.  Too many mods, too many plugins, etc.
- Windows needs to be updated...?

**Comment by GrafKostevskiy** [comment]
God it works!
With the removal of Bitdefender, the problem disappeared. Who would have thought that an antivirus could ruin everything like that.
Thank you so much for your help!

**Comment by Goga370** [comment]
Have a similar problem, can someone help?
[mo_interface.log](https://github.com/user-attachments/files/17006373/mo_interface.log)
[usvfs-2024-09-15_05-15-01.log](https://github.com/user-attachments/files/17006374/usvfs-2024-09-15_05-15-01.log)
[usvfs-2024-09-15_15-09-15.log](https://github.com/user-attachments/files/17006375/usvfs-2024-09-15_15-09-15.log)
[usvfs-2024-09-15_15-16-42.log](https://github.com/user-attachments/files/17006376/usvfs-2024-09-15_15-16-42.log)
[usvfs-2024-09-15_15-40-53.log](https://github.com/user-attachments/files/17006377/usvfs-2024-09-15_15-40-53.log)
