### ISSUE TITLE
unable to switch to wide screen

### ISSUE THREAD

**Issue by senatorwary** [ModOrganizer2/modorganizer#1587]
## The problem:
I launched fallout 4 via f4se in mod organizer 2 and it appeared in the corner of the screen I tried selecting maximize from the launcher shortcut would not change the size of the screen

## To Reproduce:
I opened the game from steam and had it be windowed prior to installing f4se and mo2 after installation was complete I closed fallout 4 on steam and set up f4se launcher clicked it game appeared full size then changed properties in the shortcut to windowed game launched in the corner of the screen

## Environment:
was using windows 10 and latest version of mo2

**Comment by LostDragonist** [comment]
You need to select and run the game launcher through MO2 in order to configure your display settings.  Then you can exit the launch and run F4SE like normal.

**Comment by senatorwary** [comment]
Thank you sir it worked much appreciated
