### ISSUE TITLE
Ultrawide 21:9 launch of Skyrim SE (skse64_loader.exe) forcing 16:9 

### ISSUE THREAD

**Issue by keithwrites** [ModOrganizer2/modorganizer#1591]
## The problem:
Windows 10 home 64bit - all updates done. 
SkyrimSE installed on E:/steam/....
MO2 installed E:/GameTools/MO2   (as portable)
download directory: f:/mod-downloads/skyrimse
all other paths default. 

Launching Skyrim SE - (skse64_loader.exe)  forces the display to 16:9 (2560x1440)
Launching from the game folder (steam/.../Skyrim Special Edition/skse64_loader.exe  allows the game to load in 21:9 (3440x1400)

It does this with 200+ mods and with zero mods active.  

(https://discord.gg/5tCqt6V)

## To Reproduce:

Not sure if it's monitor/driver dependant (no reason to belive it would be) but it's an ASUS PG348Q monitor.  The behavior described above is 100% repeatable - never changes.  

## Environment:

* Mod Organizer Version that exhibits the issue: 2.4.2 (revision: 2a5dd6c7)
* Last Mod Organizer Version that did not exhibit the issue (if applicable): don't remember it was over a year ago. 
* Desktop OS/version used to run Mod Organizer: Windows 10 Home 64bit. 

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your latest USVFS log, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!
[usvfs-2021-09-22_09-16-11.log](https://github.com/ModOrganizer2/modorganizer/files/7209425/usvfs-2021-09-22_09-16-11.log)

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/7209429/mo_interface.log)

**Comment by keithwrites** [comment]
RESOLVED 
MO2 (I'm pretty sure I installed MO2 after Skyrim was working widescreen) did not copy the iSize H= and iSize W= values from my Skyrimperfs.ini - to the MO2/profiles/.../skyrimperfs.ini   - those files all had 
iSize H=1440
iSize W=2560

**Comment by Holt59** [comment]
MO2 copy the files from the My Games folder to the profile files when the profile is created. If you changed the settings after having created the profile, the profile files are not updated. If you switched to profile-specific settings after modified the global settings, I'm not sure those are updated either.
