### ISSUE TITLE
MO2 hooking brave.exe

### ISSUE THREAD

**Issue by Bia10** [ModOrganizer2/modorganizer#1592]
## The problem:
MO2 is hooking Brave

## To Reproduce:

Open Skyrim thru SKSE in MO2 while brave.exe is running.
Exit Skyrim.
Attemp to exit MO2.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.4.2
* Desktop OS/version used to run Mod Organizer: Win10 latest build

## Details:

![image](https://user-images.githubusercontent.com/2548763/135058012-ea0a3c81-8461-4991-b3bf-c58ed1d10d5d.png)

Logs related to issue:
```
Line 1000: 20:01:13.383 [I] inithooks called mod_organizer_instance in process C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe:640 (log level 1, dump type 1, dump path C:/Modding/MO2/crashDumps)
Line 1000: 20:01:13.383 [I] inithooks called mod_organizer_instance in process C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe:640 (log level 1, dump type 1, dump path C:/Modding/MO2/crashDumps)
Line 1000: 20:01:13.383 [I] inithooks called mod_organizer_instance in process C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe:640 (log level 1, dump type 1, dump path C:/Modding/MO2/crashDumps)
Line 1053: 20:01:13.415 [I] inithooks called mod_organizer_instance in process C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe:3216 (log level 1, dump type 1, dump path C:/Modding/MO2/crashDumps)
Line 1053: 20:01:13.415 [I] inithooks called mod_organizer_instance in process C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe:3216 (log level 1, dump type 1, dump path C:/Modding/MO2/crashDumps)
Line 1053: 20:01:13.415 [I] inithooks called mod_organizer_instance in process C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe:3216 (log level 1, dump type 1, dump path C:/Modding/MO2/crashDumps)
Line 2321: 01:01:07.446 [I] inithooks called mod_organizer_instance in process C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe:14868 (log level 1, dump type 1, dump path C:/Modding/MO2/crashDumps)
Line 2321: 01:01:07.446 [I] inithooks called mod_organizer_instance in process C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe:14868 (log level 1, dump type 1, dump path C:/Modding/MO2/crashDumps)
Line 2321: 01:01:07.446 [I] inithooks called mod_organizer_instance in process C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe:14868 (log level 1, dump type 1, dump path C:/Modding/MO2/crashDumps)
Line 2374: 01:01:07.473 [I] inithooks called mod_organizer_instance in process C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe:18448 (log level 1, dump type 1, dump path C:/Modding/MO2/crashDumps)
Line 2374: 01:01:07.473 [I] inithooks called mod_organizer_instance in process C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe:18448 (log level 1, dump type 1, dump path C:/Modding/MO2/crashDumps)
Line 2374: 01:01:07.473 [I] inithooks called mod_organizer_instance in process C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe:18448 (log level 1, dump type 1, dump path C:/Modding/MO2/crashDumps)

01:01:07.473 [I] access existing config in 18448
01:01:07.473 [I] 75 processes
01:01:07.473 [I] mod_organizer_instance_19 opened in process 18448
01:01:07.481 [I] attached to mod_organizer_instance_19 with 94847 nodes, size 33,554,432 B
01:01:07.482 [I] inv_mod_organizer_instance_1 opened in process 18448
01:01:07.482 [I] attached to inv_mod_organizer_instance_1 with 441 nodes, size 131,072 B
01:01:07.482 [I] Process registered in shared process list : 18448

```

**Comment by Holt59** [comment]
You have to clarify what you mean because MO2 does not do anything regarding key/mouse events in game. The "hooks" you see are filesystem hooks to redirect files that have nothing to do with keyboard or mouse events.

Your problem is likely unrelated to MO2 or related to a mod you're using. There are many program that are not hooked by MO2 that exhibit this behavior when playing Skyrim.

**Comment by Bia10** [comment]
> You have to clarify what you mean because MO2 does not do anything regarding key/mouse events in game. The "hooks" you see are filesystem hooks to redirect files that have nothing to do with keyboard or mouse events.
> 
> Your problem is likely unrelated to MO2 or related to a mod you're using. There are many program that are not hooked by MO2 that exhibit this behavior when playing Skyrim.

thanks i see that now, however i hope your not trying to imply that calling inithooks in brave.exe is expected behavior??

why should i want to close my browser to close MO2? doesn't make much sense to me

i would understand if inithooks was called on programs related to MO2 like Loot.exe, skse64_loader.exe, SkyrimSE.exe, Nemesis Unlimited Behavior Engine.exe

but how the heck is brave.exe related to modding Skyrim? I am very confused thanks for clarification

**Comment by Holt59** [comment]
No, I was referring to the scrolling behavior. 

Regarding the hook of brave, does it happen consistently?

**Comment by Bia10** [comment]
> No, I was referring to the scrolling behavior.
> 
> Regarding the hook of brave, does it happen consistently?

Indeed

**Comment by Al12rs** [comment]
You can add brave.exe to the black list in the settings
![image](https://user-images.githubusercontent.com/26797547/135071717-29c7f563-18ee-40a7-9264-46706df69d32.png)

**Comment by Bia10** [comment]
> You can add brave.exe to the black list in the settings 

You forgot to mention to restart machine, merely adding it to settings had none effect whatsoever.

> You have to clarify what you mean because MO2 does not do anything regarding key/mouse events in game. The "hooks" you see are filesystem hooks to redirect files that have nothing to do with keyboard or mouse events.

Interestingly once brave.exe is no longer hooked i am not able to reproduce the mouse event being redirected to it. What are the reasons for this if the hooks themselves have nothing to do with mouse events? 

The more i know about MO2 the more confused i become. 
Thank you very much for cooperation.

**Comment by Holt59** [comment]
Did you try restarting your machine before? Likely it's the restart that "broke" the scroll issue between Skyrim and Brave, not the blacklist. And if it's the case, then the issue within MO2 likely come from the same issue.

**Comment by Bia10** [comment]
> Did you try restarting your machine before? Likely it's the restart that "broke" the scroll issue between Skyrim and Brave, not the blacklist. And if it's the case, then the issue within MO2 likely came from the same issue.

Yes i am confident this bug has occurred after a restart it doesn't happen immediately after restart but something triggers it, and once its triggered the bugged state persist till another restart merely restarting MO2 doesn't solve it.

The precise causality seem not easy to untangle, maybe its related to fact that i sometimes find programs like Loot.exe not being properly exited by MO2 and i see multiple instances of such process "running".
