### ISSUE TITLE
Update to detect Windows 11

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#1607]
![image](https://user-images.githubusercontent.com/7862539/139470287-51770450-ef63-436a-a161-7489e0edcbd7.png)

**Comment by Sulhir** [comment]
Just in case someone is looking to find answers or if it could help the devs - MO2 100% does not play nicely with Windows 11 and Skyrim Special Edition.  Not tested with non-portable or other games.   If you use MO2 for your mods and have Windows 11 you may wish to use an alternate manager or downgrade to a previous version of Windows unless you enjoy the wide world of debugging like we do.

**Comment by Al12rs** [comment]
On the contrary, we have people using it just fine on windows 11. Make sure you have the latest version of MO2 and that when updating to 11 the antivirus didn't decide to kick MO2 around. If you still have an issue please open a separate issue with all the requested information.

**Comment by LostDragonist** [comment]
Pretty sure we have thousands of users on Windows 11 at this point and zero known issues about it.  If you think something is going wrong and it has to do with Windows 11, please let us know instead of just fear mongering.

**Comment by Sulhir** [comment]
> Pretty sure we have thousands of users on Windows 11 at this point and zero known issues about it. If you think something is going wrong and it has to do with Windows 11, please let us know instead of just fear mongering.

wasn't my intention.  I was helping a friend debug it.  He reinstalled Skyrim SE and MO2 and it worked when he skipped MO2 - even with no mods loaded.  I've told him to open a ticket.  He was resigning himself to no Skyrim for the next couple of months so hopefully this will perk him up a bit.

**Comment by Nyxterius** [comment]
Hi, I'm the friend, I'm modding skyrim rn and with my ~450 mods LO im getting visual artifacts and textures floating in the sky. It's the most bizarre thing as I've gone through all my mods and disabled them, re-run texgen, dyndolod, re-pre-cached my grass, and tried running my game without mo2. I have also tried reinstalling skyrim and installing the newest update of mo2.
![enb2021_10_30_22_33_12](https://user-images.githubusercontent.com/77221598/139764111-febf27dc-a3fe-4f4a-9b4c-f4bb2090244f.png)
![enb2021_10_30_22_32_23](https://user-images.githubusercontent.com/77221598/139764122-75404cf1-d126-4605-97d5-5c70a282f3f9.png)
![enb2021_10_30_22_32_08](https://user-images.githubusercontent.com/77221598/139764131-119697f7-2434-4ebb-bfa2-0d3a2ce6ece0.png)
these images arent even the weirdest of them, ive had moss shaders floating above my head at the gate to whiterun.

**Comment by Holt59** [comment]
@Nyxterius This does not look like something related to MO2 but rather to your mod setup. You want to create a clean profile with default INI and no mods and see if these artifacts are still there.

**Comment by Nyxterius** [comment]
@Holt59 they are still present, i made a new profile with no mods installed and even started a new save and the artifacts were immediately present on the wagon sequence

**Comment by LostDragonist** [comment]
According to some Google searches, this is a wide-spread issue in tools.  The official recommendation by Microsoft seems to be to check for buildId >= 22000 which seems utterly stupid.  Instead of doing that, I'm just going to remove the mentions of ProductName from the logs.

ReleaseId also seems to be stuck on 2009 while DisplayVersion is 21H2? So I'll go ahead and change that as well...?

This should not be this difficult.
