### ISSUE TITLE
Windows 11 issue

### ISSUE THREAD

**Issue by iConnaz** [ModOrganizer2/modorganizer#1608]
Having trouble running since the update to Windows 11 unsure if it is the source of the issue but have tried updating through Wabbajack and the issue is still present hoping to hear back about it

**Comment by LostDragonist** [comment]
................................................................
................................................................
................................................................
................................................................

What issue?

**Comment by Al12rs** [comment]
Hi, please follow our issue templates when creating new issues, making sure to provide all the requested information.
Otherwise you may visit the Discord server instead.
