### ISSUE TITLE
Skyrim SE CrAshing!! HELP (For dummies) -_-

### ISSUE THREAD

**Issue by UrbReb47** [ModOrganizer2/modorganizer#1611]
Just figured out how to activate Phoenix vivd enb reshade. Although i had some trouble at first, I followed the directions and installed the files in the order and manner requested and it now loads up beautifully, but unfortunately 3-5 min into the breathtaking re-shaded gameplay it crashes.. I ran loot through mod organizer several times and found no errors, yet the crashing continues.. Anyone know how to fix this issue?

  Here is my load order

[info] Calculated order: 
[info] 	Skyrim.esm
[info] 	Update.esm
[info] 	Dawnguard.esm
[info] 	HearthFires.esm
[info] 	Dragonborn.esm
[info] 	Unofficial Skyrim Special Edition Patch.esp
[info] 	RSkyrimChildren.esm
[info] 	Skyrim Project Optimization - Full ESL Version.esm
[info] 	RaceCompatibility.esm
[info] 	WhiterunHoldForest.esp
[info] 	3DNPC.esp
[info] 	Whiterun Forest Borealis Lightweight.esp
[info] 	FlowerGirls SE.esm
[info] 	ApachiiHair.esm
[info] 	SexLab.esm
[info] 	RealisticWaterTwo - Resources.esm
[info] 	GQJ_DG_vampireamuletfix.esp
[info] 	SkyUI_SE.esp
[info] 	Audio Overhaul Skyrim.esp
[info] 	Obsidian Weathers.esp
[info] 	SMIM-SE-Merged-All.esp
[info] 	TrueStormsSE.esp
[info] 	TrueDirectionalMovement.esp
[info] 	RLO - Effects.esp
[info] 	RLO - Illuminated Spells.esp
[info] 	DiverseDragonsCollectionSE.esp
[info] 	KSHairdosSMP.esp
[info] 	KS Hairdo's.esp
[info] 	CharacterMakingExtender.esp
[info] 	EnhancedCharacterEdit.esp
[info] 	icepenguinworldmapclassic.esp
[info] 	COTN - Falkreath.esp
[info] 	The Great Cities - Minor Cities and Towns.esp
[info] 	Immersive Weapons.esp
[info] 	3DNPC0.esp
[info] 	SkyHUD.esp
[info] 	dD - Enhanced Blood Main.esp
[info] 	dD-Larger Splatter Size.esp
[info] 	dD-Medium Script Range.esp
[info] 	AI Overhaul.esp
[info] 	TouringCarriages.esp
[info] 	Cutting Room Floor.esp
[info] 	Skyrim Immersive Creatures Special Edition.esp
[info] 	SoundsofSkyrimComplete.esp
[info] 	Cathedral Weathers.esp
[info] 	WindhelmSSE.esp
[info] 	RLO - Exteriors.esp
[info] 	The Great City of Solitude.esp
[info] 	Odin - Skyrim Magic Overhaul.esp
[info] 	Particle Patch for ENB SSE.esp
[info] 	JK's Palace of the Kings.esp
[info] 	SoS_ELE_Patch.esp
[info] 	JK's Temple of Dibella.esp
[info] 	Bijin Wives.esp
[info] 	SkyTEST-RealisticAnimals&Predators.esp
[info] 	Hothtrooper44_ArmorCompilation.esp
[info] 	Realm of Lorkhan - Custom Alternate Start - Choose your own adventure.esp
[info] 	Bijin Warmaidens.esp
[info] 	Hothtrooper44_Armor_Ecksstra.esp
[info] 	Bijin NPCs.esp
[info] 	WayshrinesIFT.esp
[info] 	JKs Riften.esp
[info] 	Antennaria.esp
[info] 	Cloaks.esp
[info] 	MaximumCarnage.esp
[info] 	JK's Riverwood.esp
[info] 	JKs Markarth.esp
[info] 	Immersive Speechcraft.esp
[info] 	JKs Whiterun.esp
[info] 	EmbersHD.esp
[info] 	Cloaks - Dawnguard.esp
[info] 	Cloaks - USSEP Patch.esp
[info] 	RSChildren.esp
[info] 	EBT - IC PATCH.esp
[info] 	SOSRaceMenu.esp
[info] 	XPMSE.esp
[info] 	UIExtensions.esp
[info] 	DeadlyMutilation.esp
[info] 	Footprints.esp
[info] 	Runed_Nordic_Weapons.esp
[info] 	Smoking Torches and Candles.esp
[info] 	EmbersHD - RLO Patch.esp
[info] 	KD - Realistic Fireplaces SE.esp
[info] 	EnchantedArsenal.esp
[info] 	JK's Ivarstead.esp
[info] 	JK's Riverfall Cottage.esp
[info] 	Obsidian_TS_Patch_Spectral_WaterFix.esp
[info] 	Obsidian_TS_Patch_Spectral.esp
[info] 	Obsidian_TS_AOS_Patch.esp
[info] 	Obsidian_TS_SoS_Patch.esp
[info] 	All armor - All enchantments.esp
[info] 	JKs Whiterun exterior.esp
[info] 	Skyrim Flora Overhaul.esp
[info] 	WayshrinesIFT - Whiterun Forest Borealis patch.esp
[info] 	MCMHelper.esp
[info] 	Schlongs of SkyrimSE - Light.esp
[info] 	CBBE.esp
[info] 	3BBB.esp
[info] 	Chesko_WearableLantern.esp
[info] 	Ordinator - Perks of Skyrim.esp
[info] 	Immersive Citizens - AI Overhaul.esp
[info] 	Relationship Dialogue Overhaul.esp
[info] 	Immersive Horses.esp
[info] 	Immersive Real Horses.esp
[info] 	Immersive Citizens - TC patch.esp
[info] 	Lux.esp
[info] 	Lux - JK's Skyrim.esp
[info] 	ELE_SSE.esp
[info] 	Immersive Citizens - ELE patch.esp
[info] 	ENB Light.esp
[info] 	RealisticWaterTwo.esp
[info] 	Lux - RWT Patch.esp

**Comment by Al12rs** [comment]
This repository is for issues of Mod Organizer 2, if the game crashes it's very likely some mod incompatibility, incorrect ini settings, or even a bug with either the game or the mods. Unless there is something that indicates that this is a MO2 issue, we can't help you. You can try on reddit or the Nexus discord I believe.

**Comment by UrbReb47** [comment]
How do you know it isnt?

**Comment by UrbReb47** [comment]
my issue is that mod organizeer wont tell me what the issue is lol

**Comment by LostDragonist** [comment]
If you have a feature suggestion for MO2 on how to give you more information to diagnose crashes, please open up another ticket.
