### ISSUE TITLE
Modding  FO3 at the moment not posibble

### ISSUE THREAD

**Issue by ranafuineluva** [ModOrganizer2/modorganizer#1612]
## The problem:
Fallout 3 Modding practically  not working at the moment.
I am trying to mod FO3 thru MO2.
Steam made a new update to the game recently. 
And the FOSE does not work at this version.
They made a new patcher for the game named “Fallout Anniversary Patcher”
https://www.nexusmods.com/fallout3/mods/24913?tab=description

The patched game works by itself.
But when I try to run the game thru  MO2 the game crashes into the loading screen.
Can you update MO2 to support this version I would be appreciated.
 

## To Reproduce:

1.Install FOSE  to the latest fo3 installation.
2. Run FOSE runner. And you will get a error mesage:
FOSE Loader
You have an unknown version of Fallout . Please ..
If you are reporting a bug, _always_ include the USVFS logs!

Would it be possible to code MO2 to run the "Fallout Anniversary Patcher” version of the game?

**Comment by Holt59** [comment]
FO3 works perfectly with MO2, even after using the anniversary patcher. Your issue is most likely related to your mod setup or something else (ini files, etc.), Try a new, clean MO2 profile and see if it works. Otherwise you can drop by our Discord or another modding place to ask for guidance.

**Comment by ranafuineluva** [comment]
FOSE doesn't work

**Comment by Qudix** [comment]
MO2 has nothing to do with FOSE not working. There is nothing to "fix" on our end.
