### ISSUE TITLE
Issue that I'm confident I created while installing MO2 but I can't find it. 

### ISSUE THREAD

**Issue by soil23au** [ModOrganizer2/modorganizer#1619]
## The problem:
Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our [Discord server](https://discord.gg/6GKR9jZ).
I just installed MO2 for my 2nd time on new PC. When I try to install a executable file with the "install a new mod button" there are only empty folders that I get. No files inside. But outside of MO2 I can navigate to the folders and the files are there.

## Environment:

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your latest USVFS log, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by LostDragonist** [comment]
MO2 can only "install" archive files like .zip, .rar, .7z, etc.  It doesn't know what to do with an .exe file so it doesn't show it to you.
