### ISSUE TITLE
Omods not working

### ISSUE THREAD

**Issue by Punslinger1995** [ModOrganizer2/modorganizer#1628]
## The problem:
Trying to install some OMODs fails, giving me an error message about a negative number. Currently, I cannot install Robert's Male Body or Darnified UI. They installed just fine before but I had to do a clean install of oblivion and now they won't install. HGEC's OMOD works fine though.

## To Reproduce:
Attempt to install Darnified UI or Robert's Male Body via OMOD.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.4.2
* Last Mod Organizer Version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details:
Exact error message:
Unhanded .NET Exception: System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
    at System.IO.BinaryReader.ReadChars(Int32 count)
    at OMODFramework.Classes.BSAArchive..ctor(String path, Boolean populateAll)
    at OMODFramework.Classes.BSAArchive.<>c.<Load>b__15_0(String f)
    at OMODFramework.Utils.Do[T](IEnumerable`1 coll, Action`1 list)
    at OMODFramework.Classes.BSAArchive.Load(List`1 list)
    at OMODFrameworkWrapper.install(OMODFrameworkWrapper* , GuessedValue<QString>* modName, QString* gameName, QString* archiveName, QString* version, Int32 nexusID)

Error appears to be identical for both mods.
## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
[<script src="https://gist.github.com/Punslinger1995/8707040b33d7113ddd1fd3a9fa762ecd.js"></script>](https://gist.github.com/Punslinger1995/8707040b33d7113ddd1fd3a9fa762ecd)
### MO Interface:
[<script src="https://gist.github.com/Punslinger1995/e2ec7c63412264b07fdfcf4999d5e549.js"></script>](https://gist.github.com/Punslinger1995/e2ec7c63412264b07fdfcf4999d5e549)

**Comment by LostDragonist** [comment]
IIRC, these typically fail because you haven't run the game outside of MO in order to generate the normal INI files?  Mod installers aren't fully virtualized so they can't really make changes to profile-specific INI files and can get terribly confused.  Still need to fix that at some point.

**Comment by AnyOldName3** [comment]
That's actually not the cause here. This is something I fixed months ago, but it's not made it into an actual release yet. Try one of the development builds from our Discord.
