### ISSUE TITLE
Skyrim AE update.esm File Not Recognized

### ISSUE THREAD

**Issue by cajire** [ModOrganizer2/modorganizer#1629]
The problem:
The Game .esm Files should all show under the mods list. But the update.esm does not despite being present in the plugins and Skyrim game folder. I've also have had issues where the file in the MO2 folder that contains my actual load order isn't matching my load order I set. I have uninstalled and reinstalled both Skyrim and MO2 twice and this is continuing to be the case. I have been using MO2 since fall of 2020 and never had this issue before.

To Reproduce:
Install MO2, connect to Skyrim, open MO2, review the mod list where the vanilla .esm files appear.

Environment:

* Mod Organizer Version that exhibits the issue: v2.4.2
* Last Mod Organizer Version that did not exhibit the issue (if applicable): Unknown
* Desktop OS/version used to run Mod Organizer:
64-bit operating system, x64-based processor
Edition-Windows 10 Home
Version-21H2
Installed on-‎8/‎12/‎2021
OS build-19044.1415
Serial number-MJ0CW7GF
Experience-Windows Feature Experience Pack 120.2212.3920.0

Details:
![image](https://user-images.githubusercontent.com/59515794/147020196-7322cab2-a94c-4d1a-9000-bd952f13cda2.png)

Link to Mod Organizer logs:
USVFS:
[usvfs-2021-12-22_01-29-51.log](https://github.com/ModOrganizer2/modorganizer/files/7759331/usvfs-2021-12-22_01-29-51.log)
[usvfs-2021-12-22_01-38-50.log](https://github.com/ModOrganizer2/modorganizer/files/7759333/usvfs-2021-12-22_01-38-50.log)
MO Interface:
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/7759340/mo_interface.log)

**Comment by LostDragonist** [comment]
Update.esm isn't DLC so there's not really any reason for it to be listed.  (Granted, the others aren't really DLC for Skyrim SE either but meh.)

This isn't really an issue and everything is working as intended.
