### ISSUE TITLE
Window dimensions and position are not saved on closing on dual monitor setup

### ISSUE THREAD

**Issue by ThisIsPatrick** [Modorganizer2/modorganizer#163]
# The problem

When I exit Mod Organizer then run it again the window dimensions and position onscreen are reset to a small window on the middle of the first monitor.

# Environment

* Mod Organizer Version that exhibits the issue: **Mod Organizer 2.1 Revision: 5c192fb and 100f57d**
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): **Unknown**
* Desktop OS/version used to run Mod Organizer: **Windows 10 Home Version 1709 (OS Build 16299.125)**

# Details

While 2 monitors are active:
adjust the onscreen window dimensions and/or position
exit then reopen Mod Organizer
Mod Organizer will open in a small window in the middle of the screen on the primary monitor

If the secondary monitor is disabled through the NVIDIA Control Panel then Mod Organizer will go back to remembering these 2 settings between sessions, until Mod Organizer is used again with a second monitor active.

# Link to Mod Organizer logs

Logs are from revision 100f57d with logging set to Debug.

## USVFS
https://gist.github.com/ThisIsPatrick/fbff247941d444234f81d8910c0f9242

## MO Interface
https://gist.github.com/ThisIsPatrick/35d6674a79682486c8d7caf009b36078

**Comment by Evolution0** [comment]
Strangely enough the version of QT MO is up to already supports this which leads me to believe the screen settings are being saved in a way that either subverts QT entirely or only touches on it for things like getting window dimensions.

Looking at the ini which only saves window geometry this sounds about right.

**Comment by ThisIsPatrick** [comment]
This looks to have been a Windows 10 issue. The issue was fixed after looking into a seemingly unrelated problem with folder layouts not saving.

For reference here's the forum topic and article I looked into to solve the issue:
https://answers.microsoft.com/en-us/windows/forum/windows_10-files-winpc/windows-10-keeps-resetting-my-folder-view/7959873f-28e4-4b36-b148-3882c594bf00
http://www.thewindowsclub.com/windows-7-forgets-folder-view-settings

**Comment by Silarn** [comment]
Thanks for the update.
