### ISSUE TITLE
Discord Ban from Hack

### ISSUE THREAD

**Issue by Ynotnoswad** [ModOrganizer2/modorganizer#1634]
I was a member of Mod Organizer 2, until my account got hacked and I was banned. I recieved a notification that everyone on my Discord got a message about free Nitro, that I didn't send. I deleted all of the messages, and set up 2 Step Verification, as well as changing all of my online passwords. Now I can't rejoin MO2 Discord
![Screenshot Discord Unable to accept](https://user-images.githubusercontent.com/22228237/147393358-288f2ab4-4d22-4545-9de3-2eb79c530ce7.png)
.

**Comment by LostDragonist** [comment]
You've been unbanned. Don't click on sketchy links in the future and keep up with that 2FA. ;)
