### ISSUE TITLE
OMOD installer doesn't edit INI being installed

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#1642]
Hello, I'm reporting an issue with the omod installer in MO2 v2.4.4.
When installing a .omod file in MO2, none of my custom selected options are reflected in the mod's config/ini file. No matter what I select, it just keeps the default options. As a test, I even installed the mod through Oblivion Mod Manager and confirmed that it was changing the ini file as expected. 
Game: Oblivion
Mod: Basic Primary Needs by Maskar https://www.nexusmods.com/oblivion/mods/37088

From sixpockets#5241 on discord.

**Comment by LostDragonist** [comment]
[Basic Primary Needs 6.3.omod.zip](https://github.com/ModOrganizer2/modorganizer/files/7798615/Basic.Primary.Needs.6.3.omod.zip)

Mod has open permissions so here's an already converted OMOD.

**Comment by LostDragonist** [comment]
The script uses EditXMLReplace commands to perform this action.

> EditXMLReplace "Basic Primary Needs.ini", "BPN.ini_language to -1", "BPN.ini_language to %language%"

OMOD Framework seems to support EditXMLReplace at a basic level. I'm guessing that this is a problem where the INI file doesn't exist when the EditXMLReplace commands are being processed therefore the commands are meaningless.

**Comment by AnyOldName3** [comment]
If you're logging level is high enough *something* should be logged about the failure, which should narrow down what's going wrong. If you're looking at the OMOD Framework source, by the way, you'll need to look at the `old-2.x` branch, as the 3.x series was developed after I'd started the MO2 plugin, and has an incompatible API.

**Comment by LostDragonist** [comment]
Debug logs don't show anything terribly going wrong.

> [2022-01-02 15:58:21.077 D] "EditXMLLine OR EditXMLReplace" called with line: 'EditXMLReplace' 'Basic Primary Needs.ini' 'BPN.ini_language to -1' 'BPN.ini_language to 4' 

4 matches with the language I selected /shrug.

**Comment by AnyOldName3** [comment]
So if there are no warnings about the path being invalid or arguments not being right, it sounds like it thinks it's working.

**Comment by LostDragonist** [comment]
Finally managed to get a debugger on it and OMOD Framework is indeed correctly modifying `Basic Primary Needs.ini` in the temporary\0 directory... and that change is lost somewhere between running the script and installing the files.

It's almost like the temporary files are just being discarded and the files are being extracted again.....???

**Comment by LostDragonist** [comment]
Fixed in https://github.com/ModOrganizer2/modorganizer-installer_omod/pull/6
