### ISSUE TITLE
Unlock MO corrects CTD?

### ISSUE THREAD

**Issue by lareri** [ModOrganizer2/modorganizer#1645]
Hello.
In game I have a recurring CTD whose error message is:
  [ 1] ShadowSceneNode(Name: `ShadowSceneNode`)
  [ 39] BSFadeNode(Name: `skeleton.nif`, Owner: `PlayerCharacter(FormId: 000014, BaseForm: TESNPC(Name: `Lareri`, FormId: 00000007, File: `Skyrim.esm`))`)
  [ 42] NiCamera(Name : `WorldRoot Camera`)
  [ 81] NiCamera(Name : null)
  [ 97] BSMultiBoundRoom(Name : null)
  [ 101] BSMultiBoundRoom(Name : null)
  [ 103] BSMultiBoundRoom(Name : null)
 
I found that if I unlock MO after running the game but before running my save, I have no CTD.
Can you please help me?
 
My hypothesis is not believable, but I specify that having 2 saves, each in a different dungeon, 20s to 30s before the CTD I made several tests.
When I launch the game and the saves without unlocking MO, the CTD are unavoidable.
By unlocking MO after launching the game but before launching the saves, no CTD.
I tested by disabling my camera mods, light mods, climate mods. I'm sure the XP32 skeletons are not overwritten. All these mods are not the cause of CTD.
 
 I could not post on the MO mod page because it is locked.

I tried a new thing.

My desktop resolution is 3840x2160 and my game was set to 1920x1080.
By also setting the game to 3840x2160 I don't have any CTD even with MO locked.
   
 
Traduit avec www.DeepL.com/Translator (version gratuite)

**Comment by Al12rs** [comment]
The chances of Mo2 being the actual cause responsible of the CTDs are very low as unlocking MO2 changes nothing for the game. Even the act of ALT tabbing out of the game might be more influential on your problem than unlocking Mo2. 

Even then the actual cause of the ctd in the first place is most likely to be a mod or a combination of mods or INI settings. It might even be a vanilla bug though a mod is more likely.

**Comment by lareri** [comment]
I agree.
I have done a lot of testing though.

You are certainly right. 
Thank you for your answer.
