### ISSUE TITLE
MO 2.1.0 - message on launch: basic_string::reserve max_size() exceeded

### ISSUE THREAD

**Issue by MisterPenguin95** [Modorganizer2/modorganizer#165]
# The problem

When updating from MO 2.0.8.3 to MO 2.1.0, I get the following message : 
ERROR
basic_string::reserve max_size() exceed

https://www.noelshack.com/2017-52-2-1514301916-capture-d-ecran-2.png

I have no idea what it is...

I have been using MO2 for Skyrim Special Edition with no special issues (except some crashes), this is the first time happening, on Windows 10.

**Comment by erasmux** [comment]
When installing a new MO build don't just overwrite an existing installation, you should first remove the old files as they could cause issues, you can keep your settings and setup by leaving/backupping: ModOrganizer.ini, profiles, mods, downloads, overwrite and stylesheets.
An alternative is to simply keep the new build in a different directory and, in the MO settings, point to the old mods, downloads etc folders.

Did you do this?

**Comment by MisterPenguin95** [comment]
I deleted everything in my Mod Organizer folder except "mods", "downloads" and "profiles" and i extracted the new version in the Mod Organizer folder, so yes obviously I did something wrong as it was a "dirty" update :/

I restored the deleted file and installed the new version in another folder, but I still got the same error message...

**Comment by erasmux** [comment]
Can you please join the discord channel and see if we can get to the bottom of this issue (mentioned on the [main github page](https://github.com/LePresidente/modorganizer)).

**Comment by Al12rs** [comment]
Was this issue resolved? If there are no further comments here I will close this for lack of activity.
