### ISSUE TITLE
Point to xOBSE instead of OBSE in the wiki

### ISSUE THREAD

**Issue by katawful** [ModOrganizer2/modorganizer#1660]
xOBSE is the currently supported fork of OBSE, much like xNVSE, yet the wiki for setting it up with MO2 does not point to it. It contains many new features, with many mods and updates requiring it

https://github.com/llde/xOBSE/releases

**Comment by LostDragonist** [comment]
You can edit the wiki yourself if you're feeling up to it.  Otherwise, I guess one of the devs will get to it at some point. /shrug.

**Comment by Al12rs** [comment]
Done
