### ISSUE TITLE
Cannot install MO2 on ARM based processor

### ISSUE THREAD

**Issue by Woodams** [ModOrganizer2/modorganizer#1673]
I'm running Windows via Parallels on the new MacBooks with M1 ARM based chip. It seems that MO2 can't be installed since the release versions are compiled for x64 only.

While it is niche, can there be a release for M1/ARM architecture offered as well?
<img width="513" alt="Screen Shot 2022-03-11 at 4 24 23 PM" src="https://user-images.githubusercontent.com/50756481/157971279-58eb2630-72f8-45e7-b065-eaf3113d6392.png">
<img width="264" alt="Screen Shot 2022-03-11 at 4 29 54 PM" src="https://user-images.githubusercontent.com/50756481/157972897-eca9be6d-1be5-4bf4-8af2-7993fbc06743.png">
<img width="327" alt="Screen Shot 2022-03-11 at 4 29 47 PM" src="https://user-images.githubusercontent.com/50756481/157972911-95317e79-7962-491f-a10f-cee74f33e9a1.png">

**Comment by Al12rs** [comment]
No, not something we will make or support. The chances of it working even after successfully building are very low anyways. I don't think there are even many games that will work anyways. 

Either you are happen to be a developer with lots of free time to that doesn't care about wasting it, in which case you can try porting it yourself (as I said, it likely won't work), or I can close this directly to avoid giving folder hope.

**Comment by Woodams** [comment]
I appreciate the direct and honest answer.

I'm still testing, but I've found Skyrim LE installs and seems to work OK. I decided to try MO1, and it runs surprisingly (the installer fails, but 'full manual-installation' from Nexus runs).
That's nothing to say on it functioning correctly, though. I'll try it out a bit more in depth later today/tomorrow.

As a brutal worst case, and for anyone desperate enough, you could likely do mod management via VM snapshots.

If it's alright with you guys, I'll finish trying it out and post results back here and then close out this ticket. This way I can provide resolution to anyone else in my shoes.

**Comment by Woodams** [comment]
Hey alright I'm back WAY sooner than I expected. It's as you probably suspect, MO1 runs, but doesn't operate correctly. It's actually able to install mods, and manage them, but when it runs Skyrim or SKSE the UI is bugged and unusable (unknown characters on the title menu, no input accepted). This is something to do with MO1, because I can run Skyrim and SKSE directly without issue.

I found that Nexus Mod Manager is working, thankfully. I've tested a few basic mods, like the Unofficial Skyrim LE Patch and SkyUI. 

This seems like the best avenue for (the very few) people who find themselves in a similar setup.
Cheers

**Comment by Al12rs** [comment]
The problem likely comes from the fact that both MO1 and MO2 implement their VFS by hooking and changing the behavior of Windows filesystem related API calls, some of them pretty low level like ntQueryDirectoryFile, which is likely to not work correctly in a windows emulated environment where all these windows functions aren't replicated exactly the same or even hooking those functions could provide unexpected results.

**Comment by jfranknichols** [comment]
MO2 works fine in a VM (either VMWare or Parallels on and Intel based Mac. 

I am running a 300-mod build (No ENB) using Vortex on an M1 Mac Mini (ARM Based) and it works well (generally 30 FPS outside and 55 FPS inside). However, Vortex has a lot of bugs, and you need to be careful with it, if you give it commands to fast, it will corrupt files. So, just go slow and let it finish before telling it to do something else. 

If I have time, I will take a look at building MO2 for Apple Silicone, but it will be January at the soonest before I can get to it.

**Comment by Qudix** [comment]
I suspect it would be "easier" to build the GUI on ARM than USVFS

**Comment by AnyOldName3** [comment]
There's a pretty large amount of Windows-specific stuff in the bits of MO2 that don't inherently need to be Windows-only, so *easier* just means not literally impossible. There might be some value in making that not the case any more, e.g. because the USVFS integration was specifically designed so it could be moved to a plugin one day (in which case, a FUSE-based alternative for Unix could be made) and there's the OpenMW export plugin (so some Unix users are fine running MO2 and never using USVFS), but it's a large enough amount of work that the people who've looked at how much work it'd be in the past have all decided it wasn't worth their time.

**Comment by Qudix** [comment]
I just assumed they meant Windows on ARM

**Comment by Tyranicus2063** [comment]
I recently encountered this issue, and I want to shed some light on this. We do not need an ARM build of MO2 to solve this issue. We simply need the installer for MO2 to allow it to be installed on Windows for ARM. The latest builds of Windows for ARM have excellent x86 and x64 emulation built in and can run MO2 just fine. I tested this by copying it over from an x64 PC. It works perfectly fine on Windows for ARM, but because the installer has a platform check built into it, it refuses to install.

**Comment by Al12rs** [comment]
If that is the case, you can get the pre-installed archive version of MO2 from the this GitHub Release page: https://github.com/ModOrganizer2/modorganizer/releases

**Comment by jfranknichols** [comment]
AI12rs: "If that is the case, you can get the pre-installed archive version of MO2 from the this GitHub Release page:"

Excellent, thank you! I got a copy of my wife's install (Windows), and it works on my M1 Mac mini. I appreciate the suggestion and feel dumb for not thinking of it.

**Comment by vancegillies** [comment]
Running into the same issue and I believe it has something to do with the VFS, I can launch stalker anomaly no problems but when trying to launch it with the VFS it just sits waiting for the application to open and then stops, no errors or useful logs. 

Huge grain of salt with this because I have only used MO for about a day haha

**Comment by Therises** [comment]
> Running into the same issue and I believe it has something to do with the VFS, I can launch stalker anomaly no problems but when trying to launch it with the VFS it just sits waiting for the application to open and then stops, no errors or useful logs.
> 
> Huge grain of salt with this because I have only used MO for about a day haha

Have the same exact problem. MO2 starts fine but refuses to launch the game. Even the launcher. The game itself starts and plays alright.

Trying to launch GAMMA modpack with Anomaly 1.5.2 on MacBook Pro 2021 (M1 Max/32GB/Ventura13.4/Parallels18.1)

**Comment by Dima564** [comment]
I have the same problem.

**Comment by Luis2222223** [comment]
> Hey alright I'm back WAY sooner than I expected. It's as you probably suspect, MO1 runs, but doesn't operate correctly. It's actually able to install mods, and manage them, but when it runs Skyrim or SKSE the UI is bugged and unusable (unknown characters on the title menu, no input accepted). This is something to do with MO1, because I can run Skyrim and SKSE directly without issue.
> 
> I found that Vortex (Nexus Mod Manager) is working, thankfully. I've tested a few basic mods, like the Unofficial Skyrim LE Patch and SkyUI.
> 
> This seems like the best avenue for (the very few) people who find themselves in a similar setup. Cheers

Maybe m1 doesn't support mo2's Virtual File System, Vortex's Hardlink seems better.

**Comment by Luis2222223** [comment]
> Hey alright I'm back WAY sooner than I expected. It's as you probably suspect, MO1 runs, but doesn't operate correctly. It's actually able to install mods, and manage them, but when it runs Skyrim or SKSE the UI is bugged and unusable (unknown characters on the title menu, no input accepted). This is something to do with MO1, because I can run Skyrim and SKSE directly without issue.
> 
> I found that Vortex (Nexus Mod Manager) is working, thankfully. I've tested a few basic mods, like the Unofficial Skyrim LE Patch and SkyUI.
> 
> This seems like the best avenue for (the very few) people who find themselves in a similar setup. Cheers



> Hey alright I'm back WAY sooner than I expected. It's as you probably suspect, MO1 runs, but doesn't operate correctly. It's actually able to install mods, and manage them, but when it runs Skyrim or SKSE the UI is bugged and unusable (unknown characters on the title menu, no input accepted). This is something to do with MO1, because I can run Skyrim and SKSE directly without issue.
> 
> I found that Vortex (Nexus Mod Manager) is working, thankfully. I've tested a few basic mods, like the Unofficial Skyrim LE Patch and SkyUI.
> 
> This seems like the best avenue for (the very few) people who find themselves in a similar setup. Cheers

Hello, how did you open the vortex?
I finished installing vortex and I clicked on it and there was no response, just the mouse showed a few seconds loading icon.
My device is MacBook Air m1 2020 8G 256G, Parallels Desktop 19 for Mac Business Edition 19.1.0, Windows 11 23H2, .NET 6.0+ installed, Vortex Version 1.9.12.
Thank you!

**Comment by FanumTax6767** [comment]
#Hello, how did you open the vortex?
I finished installing vortex and I clicked on it and there was no response, just the mouse showed a few seconds loading icon.
My device is MacBook Air m1 2020 8G 256G, Parallels Desktop 19 for Mac Business Edition 19.1.0, Windows 11 23H2, .NET 6.0+ installed, Vortex Version 1.9.12.
Thank you! 

I have the same problem, please tell me if you manage to solve it. Thanks.

**Comment by jfranknichols** [comment]
> #Hello, how did you open the vortex? I finished installing vortex and I clicked on it and there was no response, just the mouse showed a few seconds loading icon. My device is MacBook Air m1 2020 8G 256G, Parallels Desktop 19 for Mac Business Edition 19.1.0, Windows 11 23H2, .NET 6.0+ installed, Vortex Version 1.9.12. Thank you!
> 
> I have the same problem, please tell me if you manage to solve it. Thanks.

I don't know what you are doing wrong, but I have installed it on several Macs and had no problems. I am currently running a 250 mod build with Requiem 5.x, and it runs perfectly; Vortex is, of course, my Mod Manager. 

I have both an M1 Mac mini and an M2 Mac mini Pro. They both work fine; of course, the Pro runs better. :)

**Comment by jfranknichols** [comment]
As a follow up to this OLD thread.

MO2 runs on my M2 Pro Mini using Crossfires Crossover. I can also run ENB in that environment, which I have not figured out out to do in Parallels yet.

**Comment by ndabas** [comment]
This PR in usvfs fixes this issue: https://github.com/ModOrganizer2/usvfs/pull/93
