### ISSUE TITLE
MO2 replaces text in the log with USERNAME when the text matches the username

### ISSUE THREAD

**Issue by lg126** [ModOrganizer2/modorganizer#1674]
## The problem:
Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our [Discord server](https://discord.gg/6GKR9jZ).
The Fallout 4 Mod Organizer 2 log inserts the tag USERNAME in the log to replace identical text.

## To Reproduce:

Set username to a single letter such as "s"
Check the log in the main screen - all instances where a word contains the letter s will now show USERNAME. Example "UUSERNAMEer iUSERNAME logged in to NexuUSERNAME."

## Environment:

* Mod Organizer Version that exhibits the issue: 2.4.4
* Last Mod Organizer Version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Win10

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.
![example](https://user-images.githubusercontent.com/46290476/158502844-9b6ac2f8-a8b8-4599-bd18-d7d8f83fa3d4.PNG)

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your latest USVFS log, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by AnyOldName3** [comment]
It's doing this by design. Users send us their logs a lot, so we don't want personally identifiable information in them. Usually, their username isn't just `l`, so this causes no problems, and when it *is* just `l`, we can do a quick find-and-replace to swap `USERNAME` for `l` and tidy up the mess. It could maybe be a bit prettier, but I don't think there's really a *problem* here, per se.

**Comment by Al12rs** [comment]
I think Lost already improved the replacer on the development versions to only do its thing when there are path like slashes next to the username

**Comment by Iannic-ann-od** [comment]
> I think Lost already improved the replacer on the development versions to only do its thing when there are path like slashes next to the username

As a user with a single letter username I'm looking forward to this eventual update and being able to read my log files easily again!

**Comment by Al12rs** [comment]
There are development builds available for testing on discord if you can't wait

**Comment by LostDragonist** [comment]
What's somewhat funny about this feature is that it didn't actually address what I meant to address.  When using a Microsoft account as your Windows log in, your actually have a "display name" that is different from your username.  Which.. I guess the username would still contain like 60% of your name but the full display name isn't filtered.

sigh.
