### ISSUE TITLE
JIP LN NVSE Plugin

### ISSUE THREAD

**Issue by TrueGinake** [ModOrganizer2/modorganizer#1675]
## Environment:

* Mod Organizer Version that exhibits the issue: v2.4.4
* Last Mod Organizer Version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:  Windows 10 Pro

## Details:
Every mod that depends of JIP LN NVSE Plugin inform that the plugin is not installed or up to date with a message box

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your latest USVFS log, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by ShneekeyTheLost** [comment]
What version of JIP LN NVSE do you have?

**Comment by TrueGinake** [comment]
> What version of JIP LN NVSE do you have?
The lastest. [56.50]

**Comment by LostDragonist** [comment]
Do you have xNVSE installed? Which version are you using? Are you running the game with xNVSE through MO2?

**Comment by TrueGinake** [comment]
> Do you have xNVSE installed? Which version are you using? Are you running the game with xNVSE through MO2?

I already solved it, it was a problem with Microsoft Visual C++. I installed the last package here from Github and it solved everything.
