### ISSUE TITLE
MO v2.4.4 fails to launch 

### ISSUE THREAD

**Issue by USMA56795** [ModOrganizer2/modorganizer#1679]
## The problem:
When I try to launch Skyrim SE via Mod Organizer 2, Skyrim SE crashes.

Launching Skyrim SE outside of MO 2 works.

## To Reproduce:

1. Open Mod Organizer 2
2. Run Skyrim Special Edition
3. Skyrim starts, and then crashes

## Environment:

* Mod Organizer Version `2.4.4`
* Last Mod Organizer Version that did not exhibit the issue (if applicable): This is my first install on this machine.
* Desktop OS/version used to run Mod Organizer: `Windows 11 21H2 (OS Build 22000.556)`
* Skyrim SE Anniversary Edition version `1.6.353`

## Details:
`Skyrim_SE.exe` runs outside of MO2.
`Skyrim_SE.exe` runs via `SKSE_Launcher.exe` outside of MO2.
Neither work inside of MO2.

Windows Error Reporting shows that `ucrtbase.dll` is causing an exception.
Exception Offset `000000000007c648`
Exception Code `c0000409`
Exception Data `0000000000000005`

A lot of Googling indicates others have had this issue and have solved it by uninstalling software related to audio and/or re-installing VC Redist 2015 x64.  I've tried both of these potential fixes, but neither has fixed it.  (I previously had Dell Wave Audio installed.)

`C:\Windows\System32\ucrtbase.dll` says it's version `10.0.22000.1` and is part of the Microsoft C Runtime Library.

### USVFS:
[https://gist.github.com/USMA56795/44829856214214800853487d3000a957](https://gist.github.com/USMA56795/44829856214214800853487d3000a957)

### MO Interface:
[https://gist.github.com/USMA56795/cdfdf891bda6c07f6962e2b95128ab75](https://gist.github.com/USMA56795/cdfdf891bda6c07f6962e2b95128ab75)

**Comment by Al12rs** [comment]
This is very likely either a mod or some ini settings (in mo2 there is a different set of ini files for each of your profiles). Come by the discord to troubleshoot it.

**Comment by USMA56795** [comment]
Update based on conversation in Discord: I tested with a fresh profile using Default INI settings, but get the same result.  Skyrim crashes and Windows Error Reporting indicates `C:\Windows\system32.ucrtbase.dll` is causing the crash.

**Comment by Al12rs** [comment]
Resolved on discord, there were some leftover files in overwrite causing the crash.
