### ISSUE TITLE
Is there a public API for GameDependencyRequirement for python plugins?

### ISSUE THREAD

**Issue by mdavis199** [ModOrganizer2/modorganizer#1680]
I'm trying to return a `GameDependencyRequirement`  from a python MO2 Plugin.  It doesn't appear to be a part of the public API.  Am I missing something? Neither of these worked.

My code:
``` python
def requirements(self):
    return mobase.GameDependencyRequirement(SUPPORTED_GAMES)
    # return mobase.IPluginRequirement.GameDependencyRequirement(SUPPORTED_GAMES)
```
MO2:

https://github.com/ModOrganizer2/modorganizer-uibase/blob/87759269533c804c5d1925121ca87aeb98c9b053/src/pluginrequirements.h#L89-L96

``` cpp
class GameDependencyRequirement : public IPluginRequirement {
  friend class PluginRequirementFactory;

public:
  GameDependencyRequirement(QStringList const& gameNames);

  virtual std::optional<Problem> check(IOrganizer* organizer) const;
```

**Comment by LostDragonist** [comment]
It looks like you're meant to call PluginRequirementFactory.gameDependency (something like that) instead of manually creating a GameDependencyRequirement.

https://github.com/ModOrganizer2/modorganizer-plugin_python/blob/master/src/runner/pythonrunner.cpp#L315-L321

**Comment by Holt59** [comment]
`GameDependencyRequirement` is just a specific implementation of `IPluginRequirement`, you can either:

- use `mobase.PluginRequirementFactory.gameDependency("gameName")`,
- implement your own `mobase.IPluginRequirement`:

```python
class MyPluginRequirement(mobase.IPluginRequirement):
     def __init__(self):
        ...

    def check(self, organizer: mobase.IOrganizer) -> Optional[mobase.IPluginRequirement.Problem]:
        ...
```
