### ISSUE TITLE
2.4.4 - The game is in PUSERNAMEram Files

### ISSUE THREAD

**Issue by 0pLuS0** [ModOrganizer2/modorganizer#1683]
## The problem:
I have Skyrim SE installed from Steam and when I started MOD2 2.4.4 for the first time, in the log window at the bottom of the app it said;

```the game is in PUSERNAMEram Files; this may cause issues because it's a special system folder```

## To Reproduce:

1. Install Skyrim SE in steam
2. Install MO2 and run it, and pick a portable instance

## Environment:

* Mod Organizer Version that exhibits the issue: ```2.4.4```
* Last Mod Organizer Version that did not exhibit the issue (if applicable): ```2.2.1 was the last version I used, and I didn't see this message with it.```

* Desktop OS/version used to run Mod Organizer: ```Windows 10 21H2```

## Details:
I'm only seeing this message in the logs, I'm not really seeing any problems using MO2 2.4.4, but it says it may cause issues, so hopefully this  is either something I can fix, or will be fixed, whatever is going on.

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your latest USVFS log, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

https://gist.github.com/0pLuS0/781e4708aa6cc9f2177b8ec0f8469bbd

[usvfs-2022-04-07_22-56-19.log](https://github.com/ModOrganizer2/modorganizer/files/8447335/usvfs-2022-04-07_22-56-19.log)

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

https://gist.github.com/0pLuS0/11c4d7fd2c2236a89a83990ad9e26b4e

[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/8447338/mo_interface.log)

Here's a screen shot of MO2 2.4.4

![MO2](https://user-images.githubusercontent.com/36190223/162331708-38df1bdf-0d35-499a-99ae-826c5234b52f.jpg)

**Comment by Qudix** [comment]
The log line is just mangled, it doesn't effect anything and should be fixed in future versions. But beneath the mangled-ness it's warning you that you have the game installed inside of `Program Files (x86)` which is not recommended.

**Comment by 0pLuS0** [comment]
This is the path Steam installs the gamess, so what are we saying, don't use this path to install our Steam games, and what path is prefered and why is the typical Steam directory bad? I've personally always just let Steam install into it's own directory and I've never had issues... hmm

**Comment by Qudix** [comment]
Don't use Program Files if you intend to *mod* a game is what we are saying, some people tend to run into permission issues.

**Comment by Al12rs** [comment]
You don't have to move steam itself, you just need to add a new steam library location or move your current one 

Follow the guide below to move your steam library out of programfiles to other location:
https://github.com/LostDragonist/steam-library-setup-tool/wiki/Usage-Guide

**Comment by 0pLuS0** [comment]
I have a new steam location now; C:\Steam

I just reinstalled Steam instead...

THANKS
