### ISSUE TITLE
Filter mods only after 3 characters.

### ISSUE THREAD

**Issue by picobyte** [ModOrganizer2/modorganizer#1706]
Filtering mods becomes terribly slow if you have many installed. The results normally become useful after 3 letters anyway, so why not wait with filtering after at least 3 characters are provided. For the cases that the user does want to filter after 2 characters. An alternative trigger could be implemented after hitting return, when the filter input field is active.

An alternative would be making the interface more responding, of course, but that's probably more difficult to implement. If you want to go that way, then I'd suggest running a profiler to find out where the time is spent.

**Comment by Holt59** [comment]
How many mods do you have for filter to be "terribly slow"?

**Comment by picobyte** [comment]
390 mods active, of 799, 306 plugins. I must say I run this via proton in Linux, that could be relevant.
Generally MO2 starts responsive, but after a while MO2 gets progressively slower, in particular after e.g. running loot, reorganizing or installing multiple mods.
The mod ordering is slower than the plugin ordering. Also slow becomes the building of the environment. I've tried disabling Nexus connections, maybe it helps a bit, but not a lot. What helps best is just closing MO2 and restarting it. There isn't a particular moment when it slows, it's gradually.
Since you ask, I'm guessing it's only for me?

**Comment by Holt59** [comment]
I'd say this is most likely due to Proton/Linux. We never had any other reports on this.

I only have 400 mods, but the filtering is instantaneous, and since it's purely Qt (and visual stuff), it should probably handle thousands of mods without issue. The fact that MO2 gets progressively slower is a huge hint at a proton issue since we never had any such reports on Windows.

**Comment by picobyte** [comment]
Thanks a lot, that is very useful information. If I find a cause I'll post it.

**Comment by picobyte** [comment]
I seem to have had a nasty case of file corruption. Skyrim installation, downloads, Mod organizer and its mods dirst were all on this drive. Still recovering, after verifying SKSE, checking archives now comparing for mods CRC32s on disk with those in archive for matching basenames.
