### ISSUE TITLE
The NXGEN-Nice Bush mod

### ISSUE THREAD

**Issue by 007chabp** [ModOrganizer2/modorganizer#1710]
On Manuel Instalation  DATA dos not look invalid.
Fallout 4 
https://www.nexusmods.com/fallout4/mods/49356

**Comment by Al12rs** [comment]
You know that manual means that you have to tell MO2 what to do so unless you prepare something yourself that is aceptable MO2 will not sort it out for you.

If you want MO2 to sort it out for you don't use Manual. If there is some problem with the installation and MO2 doesn't know what to do, MO2 will tell you, you don't have to use manual to check.

I don't understand why people keep choosing to use Manual and be surprised it doesn't do the fancy installations.

**Comment by 007chabp** [comment]
Allo
Thank to answer.
So
It was look like went we found something wrong we let you know.
Now I know.
The thing is I get confuse and is not easy to find my self in the modeling
word and all the sites too.
Y try but the thing is so big and I not a super user in that . But I found
some satisfaction in that and I try to go o
Forward in your word.😉
Have a nice day
