### ISSUE TITLE
Open same .nif from any mod's Conflicts tab

### ISSUE THREAD

**Issue by Sceptrum** [ModOrganizer2/modorganizer#1711]
**Is your feature request related to a problem? Please describe.**
When it comes to .nif files and comparing them, I always have to make searches in the mods folder in File Explorer. It requires memorizing file names, opening new windows and doing the search with each file.

**Describe the solution you'd like**
It would be extremely convenient, if I could open directly the same .nif on the conflicts tab from any mod, inside the right-click context menu. Literally it would be the same, as it is now with the "Go to...", but instead going to the other mod's "Information" pane, which includes the same mesh, MO2 would just open the file directly. A new menu named like "Open from..." would be perfect just below the "Go to...".

**Describe alternatives you've considered**
I can't think any better of the above.

**Additional context**
None.

**Comment by Al12rs** [comment]
@Exit-9B created a Nif preview plugin for MO2 here: 
https://www.nexusmods.com/skyrimspecialedition/mods/69813 (awesome plugin btw)

I think it is pretty much what you were looking for.
