### ISSUE TITLE
Couldn't load Qt5QuickWidgets.dll

### ISSUE THREAD

**Issue by Chronovore** [Modorganizer2/modorganizer#173]
# The problem

When attempting to open a link on nexus, the MO2 shows a popup that claims that nxmhandler.exe cannot find the Qt5QuickWidgets.dll.

# Environment

* Mod Organizer v2.1.0.1
* Installed via GitHub release exe
* Installed over an old version of MO2

# Details

This issue was fixed for me locally by copying the Qt5QuickWidgets.dll from the dlls folder to the main application folder.

**Comment by SuperSandro2000** [comment]
Can't reproduce. I think this can be closed.
