### ISSUE TITLE
Install Cyberpunk 2077 mods more effectively

### ISSUE THREAD

**Issue by RowanSkie** [ModOrganizer2/modorganizer#1742]
**Is your feature request related to a problem? Please describe.**
So, after Cyberpunk 2077 entered 1.6 and REDmod became available, mods have come with a variety of directories with how it is packaged. Most of the time, they are either zip files leading straight to `.archive` files or `<Mod Name>/archives/` with the latter being a REDmod.

**Describe the solution you'd like**
I propose a way that MO2 automatically moves said files to the correct directory. It also helps with user experiences.

**Describe alternatives you've considered**
For the mods that are straight `.archive` files, I had to basically create directories and manually move the file to the correct spot. This can basically be tricky as the way to create directories is below setting the selected directory as the main path, restarting things all over. 

**Additional context**
Can this be done with a plugin? Maybe it could be something I do one day...

**Comment by Holt59** [comment]
This can be done by adding a mod-data checker to [the Cyberpunk 2077 plugin](https://github.com/ModOrganizer2/modorganizer-basic_games/blob/master/games/game_cyberpunk2077.py). 

Some game plugins that implement this feature if you want to get started:

- https://github.com/ModOrganizer2/modorganizer-basic_games/blob/master/games/game_dungeonsiege2.py
- https://github.com/ModOrganizer2/modorganizer-basic_games/blob/master/games/game_stardewvalley.py
- https://github.com/ModOrganizer2/modorganizer-basic_games/blob/master/games/game_stalkeranomaly.py
