### ISSUE TITLE
S.TA.L.K.E.R. G.A.M.M.A. crashing on launch

### ISSUE THREAD

**Issue by 7heseus** [ModOrganizer2/modorganizer#1760]
I have been playing stalker gamma for a few days now, however when I tried launching it today, it crashed with no error messages. The first time it crashed, my pc blue screened and restarted itself. Every time after that, it has crashed with no error messages, just the error sound from windows. here are some screenshots of the game and it trying to open. Hope they help in the diagnostic. 

![stalkergammacrash](https://user-images.githubusercontent.com/116994467/204033774-cc9fbc64-3da3-406e-9811-5460d6801af9.PNG)
![stalkergammacrash2](https://user-images.githubusercontent.com/116994467/204033783-63071df0-a48d-4968-91ba-ed9bf8402710.PNG)

**Comment by Qudix** [comment]
We can only help with problems related to MO2 itself. There's nothing we can do when it comes to modding issues.

**Comment by 7heseus** [comment]
> We can only help with problems related to MO2 itself. There's nothing we can do when it comes to modding issues.

okay, thanks for the reply.
