### ISSUE TITLE
skyrim SE switches language when i run it with mod organizer from english to russian

### ISSUE THREAD

**Issue by Bochora777** [ModOrganizer2/modorganizer#1765]
As I mentioned in the title, when I run skyrim via mod organizer, It's Russian instead of English, I tried to fix this problem by myself, but it seems that I can't figure it out on my own. when I open the game without mod organizer, it's normal (English).  

Also the game is windowed instead of Fullscreen when I run it with mod organizer.

Can I get some help please?

**Comment by Bochora777** [comment]
After doing that, not a single NPC is talking, they are just looking at me. any idea on how can I fix this?
When back to Russian, everything seems to be normal?

**Comment by Qudix** [comment]
This probably?
![image](https://user-images.githubusercontent.com/17361645/206786070-0ebe53d1-dbc9-4993-8c6a-5691748bbabc.png)
