### ISSUE TITLE
You totally fuck up my Windows setup/Defender settings?!? WTH!

### ISSUE THREAD

**Issue by cdycdr** [ModOrganizer2/modorganizer#1767]
## The problem:
You deactivate Defender completely!

## To Reproduce:
Just install & run this shit.

## Environment:
Windows 10

## Details:
Defender will be completely deactivated and Defender-UI will be disabled if you run this... "MOD Organizer". You will not be able to scan directories/Files after running it, Any mod will be excluded from virus-scanning... etc... You will have to regedit Settings to get protection back. Nuts! (Lazy programmers or intention?)
Take a look at
  - HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Policy Manager
  - HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender
WTF!
I'm really pissed!

**Comment by Holt59** [comment]
MO2 does no such things. I might had exclusion for itself if you asked it to during the installation process but that's all.
