### ISSUE TITLE
Fallout 4 closes immediately

### ISSUE THREAD

**Issue by SmurgBurglar** [Modorganizer2/modorganizer#177]
# The problem

whenever i launch fallout 4 or f4se with or without mods through mod organiser it closes after about 3 or 4 seconds of a black screen
# Environment

* Mod Organizer Version that exhibits the issue: 2.10
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: win 7 64

# Details
Both MO2 and Fo4 are installed to the root of my SSD NOT programfiles and i have tried Both Portable and local instance
# Link to Mod Organizer logs

## USVFS
Full - https://gist.github.com/SmurgBurglar/f3f77655cf3731f5a8079a179c85e6db
What i think the problem is - https://gist.github.com/SmurgBurglar/5368d28ec3d58fbd070da0fb9e00b322
## MO Interface
https://gist.github.com/SmurgBurglar/728920a84a772f40c1ca83e89943a453

Thank you for any help.

**Comment by CptMcSplody** [comment]
Do you have files in data/f4se/plugins/

**Comment by SmurgBurglar** [comment]
nope

**Comment by erasmux** [comment]
Retest with the usvfs 0.3 beta available on the discord channel (link on main github page). If the problem persists let me know (preferably also on the discord channel).

**Comment by MaoKwen** [comment]
I have same problem and logs, but without "failed to hook" error.

**Environment**
- MO2 version: 2.1.1
- Fo4 version: 1.10.64.0.0
- OS: Windows 10 64
- Fo4 are installed to `E:\SteamLibrary\steamapps\common`, clean install.

Here is my [Papyrus log](https://gist.githubusercontent.com/MaoKwen/2380c985b671c8b015ca0aff15694fd3/raw/aa145561f0f8c9753df18daeeab52f1234319b67/Papyrus.0.log). It looks like DLCs does not load correctly.
Hope it helps.

**Comment by Al12rs** [comment]
These issues should be resolved on the latest dev builds. If there is no further feedback in the next days I will close this.
