### ISSUE TITLE
Entry to discord relies on a non-standard discord permission

### ISSUE THREAD

**Issue by J-Hill-Dev** [ModOrganizer2/modorganizer#1776]
## The problem:
The Discord server relies on the bot sending a DM to users who knew beforehand to enable messages from people who aren't on their friend list.

## To Reproduce:
1 Make a new discord account.
2 Join the server.
3 Even if you unlock your DMs and rejoin, you can't get the DM again from the Bot.
4 The admins who you are invited to get help from have their DMs locked as well.

**Comment by LePresidente** [comment]
Changed the bot to not require dms for verification
