### ISSUE TITLE
XEdit is no longer reading plugins from MO2 

### ISSUE THREAD

**Issue by DGNursery** [ModOrganizer2/modorganizer#1797]
## The problem:

The other night I had to Reinstalled Skyrim SE/AE in Steam to correct an issue with Creation Kit, I did that the last thing that evening. The next day when started up MO2. I found upon launching XEdit. there were NO plugins found from MO2 besides the base game and DLC .ESM's

The steps I took to remediate the issue before reaching out for help are:
-Launched game through Steam
-Launched game through SKSE.
-Reinstalled XEdit (multiple times)
-Checked XEdit path in MO2.
 -Reinstalled MO2 (multiple times)
- Updated Microsoft Visual C++ Redistributable 

Always restarting the computer in between.

## To Reproduce:
Steps to reproduce the behavior:  IU 

## Environment:

* Mod Organizer Version that exhibits the issue: 
V 2.4.4
* Last Mod Organizer Version that did not exhibit the issue (if applicable): 
V 2.4.4
* Desktop OS/version used to run Mod Organizer: 
Windows 11

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

![Pathway for XEdit](https://user-images.githubusercontent.com/127150165/223233052-9b110fce-cd07-438a-a095-674e09b3beeb.png)

![Issue XEdit](https://user-images.githubusercontent.com/127150165/223233456-32f2a332-25f7-4fa8-ba48-8ab8e827f6d8.png)

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:

https://gist.github.com/DGNursery/c31aca24def943fb1ce9c2d5c7e627c7

### MO Interface:

https://gist.github.com/DGNursery/72ef8e15b7b156373cb12fe0bd47173d

**Comment by Holt59** [comment]
Do you see the files when you use Explorer++ or the mods when you launch the game?

**Comment by DGNursery** [comment]
Thank you for taking the time to reply. I am happy to say that I have resolved the issue. I am going to close the ticket. 

Best regards and thank you for helping all of us out!

**Comment by cmoore228** [comment]
Still having this issue.

[mo_interface.log](https://github.com/user-attachments/files/20379765/mo_interface.log)

[usvfs-2025-05-22_03-59-14.log](https://github.com/user-attachments/files/20379767/usvfs-2025-05-22_03-59-14.log)
