### ISSUE TITLE
Skyrim SE

### ISSUE THREAD

**Issue by hajoberlin** [ModOrganizer2/modorganizer#1802]
Why does my Mod Organizer 2 not work anymore. It does not recognize any plugins on the right side.
Reinstalled the organizer but no change.
Screenshot is attached.
Tried everything to get the program working again.
Skyrim SE is affected by this. Fallout 4 and Skyrim are working.
Can anyone help me?
![Screenshot 2023-03-14 122703](https://user-images.githubusercontent.com/127841543/225087516-bbe78c42-444a-4dcb-902b-fd9f0f877f8f.jpg)

**Comment by PinoyBloon** [comment]
err... IIRC the mods you installed/listed there does not have any plugins... have you tried installing USSEP and check whether its plugin is detected or not?

**Comment by hajoberlin** [comment]
it was originally all about 170 mods were not recognized. Loot also did not recognize any mods. As it is,
the error was in the operating system, have it so far to run again. Thanks for your effort.
