### ISSUE TITLE
MO2 error when opening for GOG version of Oblivion

### ISSUE THREAD

**Issue by Astronamy** [ModOrganizer2/modorganizer#1805]
## The problem:
I am using MO2 to mod my GOG version of Oblivion, it works mostly well though I find I have to install some but not all OBSE files directly into my data folder and its paired with wrye bash but every time I open MO2 for Oblivion I get the same error and have no clue what it is talking about. Upon clicking okay it loads up fine but not sure if its something to do with the GOG version.

[2023-03-19 21:35:30.838 E] an error occurred: Traceback (most recent call last):
[2023-03-19 21:35:30.838 E]   File "F:/Game Tools/MO2/plugins\crashlogtools\crashloglabeler.py", line 75, in onUserInterfaceInitializedCallback
[2023-03-19 21:35:30.838 E]     self.processor.update_database()
[2023-03-19 21:35:30.838 E]   File "F:/Game Tools/MO2/plugins\crashlogtools\crashlogutil.py", line 29, in update_database
[2023-03-19 21:35:30.838 E]     self.clone_database()
[2023-03-19 21:35:30.838 E]   File "F:/Game Tools/MO2/plugins\crashlogtools\crashlogutil.py", line 22, in clone_database
[2023-03-19 21:35:30.838 E]     self.database.remote,
[2023-03-19 21:35:30.838 E] AttributeError: 'NoneType' object has no attribute 'remote'

## To Reproduce:
Every time I open it, either through my task bar shortcut, start menu, created a desktop shortcut, and from the main executable and same error every time. 

## Environment: 
MO2 is installed in F/Game Tools/MO2. Oblivion is under G/GOG Galaxy/Games/Oblivion, the error comes from my F drive which is also for games as I have them split across 3 drives. 

* Mod Organizer Version that exhibits the issue: 2.4.4
* Last Mod Organizer Version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Mod Organizer: Windows 11 Home

## Details:
This error comes up every single time I load MO2 for Oblivion, the GOG version. Once clicking okay the app loads up fine and able to load the game with mods but not all obse mods work right so they have to be installed manually, but that's okay it's more this error. It only happens with this game none other.

## Link to Mod Organizer logs:
Log is saved in the gist link below

### USVFS:
In this gist, at line 393 is where the same error I get when booting comes up.
https://gist.github.com/Astronamy/a52bcf4a89304af6bf7b88ed5c7463f2

### MO Interface:
See the gist above.

Here is a screenshot of the error. Any help would be much appreciated as I do not use Discord and with the nexus comments locked I had no where else to ask.
![MO2 error when opening Oblivion](https://user-images.githubusercontent.com/37883668/226212183-acb8a8d9-4f0e-4a53-93b4-5ec4dce1820b.png)

**Comment by Holt59** [comment]
That plugin (`crashlogtools`) is not an official MO2 plugin, so you should see directly with its author.

**Comment by Astronamy** [comment]
Oh, I am so sorry to waste your time, it seems to be part of Crash Log Tools for Mod Organizer which I have for my SE Skyrim game. I have reported it there. https://www.nexusmods.com/skyrimspecialedition/mods/66743

**Comment by Holt59** [comment]
@Astronamy if it's a plugin for SSE, you can disable it in your Oblivion instance and see if that fixes the issue (Tools > Settings > Plugins).
