### ISSUE TITLE
Service site is dead

### ISSUE THREAD

**Issue by prochor666** [ModOrganizer2/modorganizer#1824]
## The problem:
Service site nexusmods is dead. Cannot consent (Cookie consent broken, web browser stucks).  API requests not working (JS errors).

## To Reproduce:

1. Install Mod organizer
2. Try to obtain account
3. Try to obtain API key (fail, due to site is not working)

## Environment:

* Mod Organizer Version that exhibits the issue: 2.4.4
* Windows 10 Professional

**Comment by Qudix** [comment]
There's nothing we can do about that, the website is a third party and any issues with it are outside our control.
