### ISSUE TITLE
Sub-Separator Proposal

### ISSUE THREAD

**Issue by CopyableBadge37** [ModOrganizer2/modorganizer#1829]
**Is your feature request related to a problem? Please describe.**
Creating too many separators can result in MO2's interface feeling cluttered, however, attempting to have a larger mod list without creating many separators can result in the separators containing an extremely large number of mods. Therefore, I propose that a sub-separator that is entirely cosmetic should be added as a new feature.

**Describe the solution you'd like**
In this new solution, the original kind of separator would be known as a "main separator," and would function the same as now, including the inability to be placed beneath other main separators. However, a new option to create a sub-separator would now be available. Sub-separators would be a new kind of separator that is able to be placed beneath a main separator. Sub-separators could have mods placed underneath them, in the same way that you can place mods beneath separators now, and could be closed to hide the mods beneath them. When a main separator with sub-separators beneath it is closed, the sub-separators would be hidden. 

You would also be able to use the "Send to" function in order to move mods beneath sub-separators. However, you cannot place a sub-separator or a main separator beneath another sub-separator.

Optionally, it could be made so that the sub-separator would be required to be placed underneath a main separator, meaning that it cannot be placed outside of a main separator. Also, another optional proposal I have is that the option to create a new sub-separator could be blocked from use without at least one main separator present on your current instance, with all existing sub-separators being removed if a user decided to remove all of their main separators without removing their sub-separators. 

**Describe alternatives you've considered**
The only alternative to this solution that I have considered is the ability to hide the enable/disable checkmark box on empty mods. By hiding the box, you could create something somewhat similar to what I have proposed, although you would be unable to hide any mods beneath them. Additionally, the ability to make the names of these empty mods bold would also aid in making them distinct.

**Additional context**
There is no additional context.
Thank you for your time.

**Comment by Silarn** [comment]
This is mostly duplicated by #1694
