### ISSUE TITLE
Errors in qsslsocket on startup

### ISSUE THREAD

**Issue by kurumushi** [Modorganizer2/modorganizer#183]
# The problem

Fresh install of MO. When I start up the first time, it asks if I want portable mode, and also which game to use. After that The main window appears, but also Two error boxes.
Box 1: "an error occurred: HTTP status 0"
Box 2: "an error occurred: Network Failed: Error creating SSL context ()"

# Environment

Mod Organizer 2.1.1 (standalone) on Windows 10

# Logs

Most likely useful part of logs:

> 10:36:43 [D] displaying main window
>10:36:43 [W] QSslSocket: cannot call unresolved function SSLv23_client_method
>10:36:43 [W] QSslSocket: cannot call unresolved function SSL_CTX_new
>10:36:43 [W] QSslSocket: cannot call unresolved function SSL_library_init
>10:36:43 [W] QSslSocket: cannot call unresolved function ERR_get_error
>10:36:43 [W] QSslSocket: cannot call unresolved function ERR_get_error
>10:36:43 [D] network error 99
>10:36:43 [C] uncaught exception in handler (object , eventtype 43): Network failed: Error creating SSL context ()
>10:36:43 [C] uncaught exception in handler (object , eventtype 43): HTTP Status 0: 

Full logs [here](https://pastebin.com/Am4Pygwh)

**Comment by erasmux** [comment]
That is most likely caused by outdated opensll dlls installed in your path or windows folders.
Try to update your openssl install or remove it (as MO already comes with an updated version of the opensll dlls). You can also try searching the windows folder for libeay32.dll and ssleay32.dll and updating them "manually" (for example by copying over the updated files that come with MO).

**Comment by Gnidddy** [comment]
Another workaround is to set MO to offline mode

**Comment by Silarn** [comment]
Does this only happen when you first launch MO or does it happen every time you start?

I've noticed while debugging that if I delay the startup process long enough it can also trigger these SSL errors. This may be due to a dangling thread timing out waiting for the main MO process to respond.

**Comment by oabdellatif** [comment]
I also get these errors, even on a fresh install of Windows 10. It happens on every launch, unless offline mode is enabled like Gniddy mentioned. I've confirmed there are no OpenSSL libraries anywhere in my path, so this has to be a bug in MO2. Silarn might be on the right track here.

**Comment by kurumushi** [comment]
This happens every time, but does not seem to affect functionality in any
way.

I should also note that the error appears in a VM with a clean windows
install, so it doesn't seem to be a conflict, unless it's with Windows
itself.

On Jan 6, 2018 6:50 AM, "Omar Abdellatif" <notifications@github.com> wrote:

I also get these errors, even on a fresh install of Windows 10. It happens
on every launch, unless offline mode is enabled like Gniddy mentioned. I've
confirmed there are no OpenSSL libraries anywhere in my path, so this has
to be a bug in MO2. Silarn might be on the right track here.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LePresidente/modorganizer/issues/183#issuecomment-355674922>,
or mute the thread

**Comment by erasmux** [comment]
Can you test with this version:
http://www.mediafire.com/file/6382z091cry16df/MO2.1-openssl_test1.7z
Please install into a new clean folder. If it still doesn't work share mo_interface.log.

**Comment by Silarn** [comment]
We are now compiling from source and with the corrected path issue this should no longer be an issue.
