### ISSUE TITLE
Loading Python packages from a local folder no longer works in Qt6

### ISSUE THREAD

**Issue by JonathanFeenstra** [ModOrganizer2/modorganizer#1835]
On dev build 2.5.0 Alpha 6, I get the following error with [LOOT Warning Checker](https://github.com/JonathanFeenstra/modorganizer-loot-warning-checker) installed (after replacing all occurrences of `PyQt5` in the code to `PyQt6`):

![error](https://media.discordapp.net/attachments/780602041482346566/1124384725834936401/image.png)

In the `__init__.py` file I have the following lines to make the packages in the local lib folder available (as suggested by Holt59):
```python3
import site

site.addsitedir(os.path.join(os.path.dirname(__file__), "lib"))
```
This works in v2.4.4 of MO2 but not in the latest dev build. I need a fix or a workaround before I can update LOOT Warning Checker to work with Qt6.

**Comment by Holt59** [comment]
The plugin needs extra updating - The yaml embedded in this plugin is for Python 3.8, you need to update it for Python 3.10 (the version used by 2.4.5).

**Comment by JonathanFeenstra** [comment]
I see, never mind then. When I tried changing it to `SafeLoader` I got another error for the `esplugin` module, but that one is also dependent on Python 3.8 so that makes sense.
