### ISSUE TITLE
NCC/Fomod Options don't worked. (Linux)

### ISSUE THREAD

**Issue by jarrard** [ModOrganizer2/modorganizer#1844]
## The problem:
Whenever selecting Use NCC, it has never worked through many installs and many mods. Never! 

## To Reproduce:

1. Go to 'Install download'
2. Click on 'Use NCC'

## Environment:

* Mod Organizer Version that exhibits the issue: 2.xxxx 
* Last Mod Organizer Version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Mod Organizer: Linux EndeavourOS Proton Steam (and GE)

## Details:
![UseNCCBroken](https://github.com/ModOrganizer2/modorganizer/assets/17428910/292c61e8-7274-4397-849d-ffecfbcfebb0)
![UseNCCBroken2](https://github.com/ModOrganizer2/modorganizer/assets/17428910/594651a6-b4d3-444b-baf3-3ea4ae181068)
![UseNCCBroken3](https://github.com/ModOrganizer2/modorganizer/assets/17428910/0f1f43d3-64ca-45ec-a90f-5b9ed58260fa)

## Link to Mod Organizer logs:
No Logs generated for Install process

### USVFS:
No USVFS is being used in this step

### MO Interface:
None

**Comment by jarrard** [comment]
I have tried to use this functionality endless times and its never worked under Linux Proton. 

No explanation found.

**Comment by Holt59** [comment]
NCC is not shipped with MO2 for recent versions, MO2 now has a dedicated installer for FOMOD that use C# scripts (that was the only type of installers not supported natively by MO2). If that installer is disabled, it's most likely because you're missing a proper NET Framework version, try installing 4.7 or 4.8.

**Comment by jarrard** [comment]
I tried .Net and it just created a different error, plus MO2 unloads the C# plugin.

**Comment by Holt59** [comment]
> I tried .Net and it just created a different error, plus MO2 unloads the C# plugin.

We do not provide support for Linux, you should ask other Linux users, this is clearly a configuration issue on your distribution. There is an open issue for Linux users, you can try there.

**Comment by jarrard** [comment]
I think in the end I'll need to use a dedicated FOMOD installer and just copy files over once done.

**Comment by Holt59** [comment]
> I think in the end I'll need to use a dedicated FOMOD installer and just copy files over once done.

There are very (very very very) few mods that use FOMOD C# and usually these mods have custom logic that you cannot simulate by simply moving files around (otherwise they could use a normal FOMOD XML installer).

**Comment by jarrard** [comment]
Yeah. I did get around the issue in the end by using my win10 VMware image and just correctly mapped the needed folders and all. MO2 doesn't know the difference if I load it up in there and install mod via that method. 

Not ideal; But until a solution can be found for fomod install method under Linux with MO2, it will have to do.

**Comment by jarrard** [comment]
The one shown in the images has a gui fomod, you pick the  parts you want with screen shots.

**Comment by Holt59** [comment]
> The one shown in the images has a gui fomod, you pick the parts you want with screen shots.
> 
I will check later today on Windows to see if that's an issue with Linux or with the FOMOD installer but this FOMOD is basically useless, all it does is showing you a bunch of text and then copying the `meshes` folder so you can basically do a manual install and set the `data` folder appropriately.

**Comment by jarrard** [comment]
No I don't believe its quite that simple. You need to look at the mod I showed to understand its not a simple file copy, you are selecting preferences in the mod. 

And it should work under Windows as I tested it in VM. It's just there is a missing component for Proton/Wine and I don't really know what that is exactly.

**Comment by Holt59** [comment]
> No I don't believe its quite that simple. You need to look at the mod I showed to understand its not a simple file copy, you are selecting preferences in the mod.
> 
> And it should work under Windows as I tested it in VM. It's just there is a missing component for Proton/Wine and I don't really know what that is exactly.

The mod you shown (Breezes New Vegas Males - https://www.nexusmods.com/newvegas/mods/35451) as literally no options.

If you actually have a mod with options, please post the Nexus (or whatever site you are using) link.

**Comment by Holt59** [comment]
> No I don't believe its quite that simple. You need to look at the mod I showed to understand its not a simple file copy, you are selecting preferences in the mod.
> 
> And it should work under Windows as I tested it in VM. It's just there is a missing component for Proton/Wine and I don't really know what that is exactly.

I actually downloaded the wrong mod since there is "Breezes New Vegas Males" and "Breezes New Vegas Males - AIO" - The AIO seems to have a more complex script but on Windows, both the built-in installer and NCC fails with exception so the script might be incorrect.

**Comment by jarrard** [comment]
https://www.nexusmods.com/newvegas/mods/48222

**Comment by BaconCatBug** [comment]
Posting in case anyone finds this while googling: `winetricks dotnet48` will fix it.
