### ISSUE TITLE
MAP UI AND CURSER

### ISSUE THREAD

**Issue by rogerthat33** [ModOrganizer2/modorganizer#1850]
## The problem:
Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our [Discord server](https://discord.g
I DO NOT HAVE ANY ISSUES LIKE OTHERS EXCEPT CURSER ON MAP UI IS ONLY LIMITED TO THE UPPER LEFT GRID.
I CAN GO TO DIAMOND CITY ON FOOT AND FAST TRAVEL BACK TO SANCTUARY AND CAANNOT FAST TRAVEL BACK TO DIAMOND CITY. THE CURSER WILL NOT GO ANY FRTHER THAN THE UPPER LEFT GRID,  I DON'T DO DISCORD SIMPLY BECAUSE OF THE SONG AND DANCE TO GET TO ANYONES DISCORD PAGE.

## Environment:

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your latest USVFS log, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by rogerthat33** [comment]
GOOD BUILD BUT CURSOR AND MAP UI NEED TO BE FIXED. CONSIDER DUMPING PIP PAD ALSO.  MANY OF US DO NOT PLAY ON YOUR SCREEN. TYPE ON PIP PAD TO SMALL.

**Comment by Qudix** [comment]
_...what?_
