### ISSUE TITLE
Game saves in Fallout 4 GOG not recognized

### ISSUE THREAD

**Issue by ViperMerlin** [ModOrganizer2/modorganizer#1855]
Mod Organizer 2 Version 2.4.4 can not recognize the Saved games. It will run and save the games in the right place, but just like when Skryim SE was released on Gog it won't show up as Saved games on MO2. Which results in not being able to tell if you are missing a Plugin for that particular Save.

**Comment by Silarn** [comment]
GOG / Epic Game Store support has not been officially added. Can you please open a new issue requesting 'game support' for GOG and please include the relevant registry entries / game IDs used by GOG as well as the correct directory names for My Games and AppData.

**Comment by ViperMerlin** [comment]
Just read your feedback and checked my Ini files and noticed I mistakenly entered the path to the save files in the wrong place, so when I corrected that, it now works perfectly. Thank you, and am now closing the issue.
