### ISSUE TITLE
Fallout 4 vr

### ISSUE THREAD

**Issue by iamlegend264** [ModOrganizer2/modorganizer#1867]
I having been having this issue for about 4-6 days now and i just don't know what to do.I use mod manager 2 and every time i try to launch fallout 4 vr i get the error message v1.10.138.0,expected version v1.10.163.0.Everything is up to date(Fallout 4 vr,fallout 4,steam vr,steam,mod manager 2),literally everything.If i could get some assistance with this i would appreciate it,i believe it's multiple issues,so if you guys gives give me all the things you can think of i would appreciate it and i will try everything mentioned because i haven't been able to get it on my own,with extensive hours trying to research and figure this out.Everything on fallout 4 vr has been working just fine till about 4-6 days ago.

On a separate note every time i launch boarderlands 2 vr it launches but has a screen that show lines like it can't identify the game,on my computer screen it shows everything working as it should but in vr it shows nothing but the like a game not found image and i have unstalled both and reinstalled and still nothing.

**Comment by Silarn** [comment]
You have an outdated version of the F4VR loader, probably. Download the correct version for your game.

**Comment by Silarn** [comment]
Or you have a plugin for the regular FO4 F4SE and you need a version for VR.

**Comment by iamlegend264** [comment]
> You have an outdated version of the F4VR loader, probably. Download the correct version for your game.

I did uninstall everything and reinstall it,so it should be up to date,or how do i find the current F4VR loader?
