### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Veruxz** [ModOrganizer2/modorganizer#1868]
This isn't about MO2 but discord. I try joining the server and says unable to join and I don't know why.

**Comment by fl4shback** [comment]
Can confirm, discord invite is dead :/

**Comment by Al-Katraz** [comment]
That one is dead too - please update with new link - thank you.

**Comment by AdrianoCahete** [comment]
Try this one: https://discord.gg/AKE9wRGpy4

**Comment by Al-Katraz** [comment]
Invite Invalid
Are these 1 use codes ?

**Comment by AdrianoCahete** [comment]
I don't think so. This above is pinned in their info channel. Try another one: https://discord.gg/Dv4ztGfb

**Comment by Al-Katraz** [comment]
That one worked - thank you

**Comment by Veruxz** [comment]
Mine is saying unable to accept invite
