### ISSUE TITLE
Correctly sort newly added ESMs and ESLs to the correct part of the plugins list

### ISSUE THREAD

**Issue by ghost** [ModOrganizer2/modorganizer#187]
# The problem

All plugins modified in either xEdit or Wrye Bash that are moved to the Overwrite folder are forced to load after the core .esm(FalloutNV.esm, Fallout3.esm, and Oblivion.esm) files.  Sorting with LOOT will not reorder these files until they are moved into a mod folder.

Esm and esp Master plugins are not grouped above normal plugins when installed.  They are placed at the bottom of the load order until moved/sorted with LOOT.

# Environment

* Mod Organizer 2.1.1 (Standalone)
* Windows 7 x64 and Windows 10 x64

**Comment by Silarn** [comment]
Interesting. I'll take a look into this when I get the chance. I guess something about the filetime setter is skipping overwrite though loot should also be able to do this particularly if it can, in fact, see the file when sorting.

**Comment by Silarn** [comment]
There's a slim possibility my changes to load order parsing might help fix this. We can check the next build.

**Comment by Silarn** [comment]
Can you check this on the latest dev build? There's a good chance it's fixed.

**Comment by Moose109** [comment]
Where would I find the latest dev version?

**Comment by SuperSandro2000** [comment]
On discord. Link is in the readme

**Comment by Moose109** [comment]
Ok, the first part is fixed, but Master files (whether they are .esm's or master flaged .esp's) are still not placed above all the normal esp's when installed.

**Comment by Silarn** [comment]
I'm going to consider this an improvement since manually sorting or using a during tool will do this for you.

**Comment by Moose109** [comment]
Yup, big improvment.  Mods are no longer placed last when edited.

**Comment by Silarn** [comment]
As in no longer a serious bug but an improvement to be made. The engine topically loads esms first regardless of load order.
