### ISSUE TITLE
Add save support for game [Blade & Sorcery]

### ISSUE THREAD

**Issue by InFerNos1** [ModOrganizer2/modorganizer#1876]
- **Name:** Blade & Sorcery
- **Short name:** bladeandsorcery
- **Nexus ID [optional]:** bladeandsorcery
- **Executable:** BladeAndSorcery.exe
- **Data path:** BladeAndSorcery_Data\StreamingAssets\Mods
- **Documents path:** %DOCUMENTS%/My Games/BladeAndSorcery
- **Saves directory [optional]:** %GAME_DOCUMENTS%/Saves/Default
- **Save extension [optional]:** .chr, the "The Outer Rim" mod uses .tor_save with the same file name as the associated .chr
- **Steam ID [optional]:** ID of the game on Steam (if the game is on Steam).

Provide save data to the Blade & Sorcery plugin.

Listing the saves in the 'Saves' tab like seen in other games can provide the user with options to deal with saves, namely removing them when a game update is released, or a mod is uninstalled, which may cause issues with loading said save.

Saves can be read by a human, they are not encoded.
The "ID" is unique per save. There is only one save per character, with no backups. The singular save is created when the character is created, and relevant inventory data is only written to the save when leaving the player home / hub area.

The data possible to parse in the "Saves" tab is limited, with the saves only containing playtime, last time played (which may not work(?)), gamemode (there is currently only Sandbox, but this is planned to change in the future), character customization (ethnicity, hair, and colours of hair, skin, eyes), inventory and equipped weaponry, tutorial flags, and VR calibration data such as user height in meters.

The .tor_save saves data relating to "discovery" of its in-game items, usually secrets hidden in the maps included in the mod. Deleting a save in-game does not currently remove this file.

[Vanilla Save + TOR Save.zip](https://github.com/ModOrganizer2/modorganizer/files/12622399/Vanilla.Save.%2B.TOR.Save.zip)

**Comment by Silarn** [comment]
https://github.com/ModOrganizer2/modorganizer-basic_games/pull/114

**Comment by Silarn** [comment]
This will be available in the next release.
