### ISSUE TITLE
Mod Organizer does not remove NVSE/F4SE files along with their corresponding save.

### ISSUE THREAD

**Issue by CJM7** [Modorganizer2/modorganizer#188]
# The problem

Removing a save via the MO save manager tab does not clean up the corresponding script extender files.

# Environment

* Mod Organizer Version that exhibits the issue: -2.1.01

* Desktop OS/version used to run Mod Organizer: windows 10

https://pastebin.com/n1inX86Y

**Comment by Silarn** [comment]
I figured this would be quick to get done before the 2.1.2 beta build and I realized the implementation for transferring saves was implemented poorly. So this will fix both issues.
