### ISSUE TITLE
Add support for game The Sims 4

### ISSUE THREAD

**Issue by LonerEmperor** [ModOrganizer2/modorganizer#1890]
**This template is useful to add basic support using https://github.com/ModOrganizer2/modorganizer-basic_games.** 

**If you are vaguely familiar with programming you can try following the instructions on that link to get something working yourself. If you have trouble with that please fill in this template.**

**Please provide the following information for the game (remove the optional lines you do not use):**

- **Name:** The Sims 4
- **Short name:** TS4
- **Nexus ID [optional]:** thesims4
- **Executable:** TS4_x64.exe
- **Launcher [optional]:** ---
- **Data path:** \Steam\steamapps\common\The Sims 4
- **Documents path:** \Documents\Electronic Arts\The Sims 4
- **Saves directory [optional]:** ---
- **Save extension [optional]:** ---
- **Steam ID [optional]:** ---

**Provide additional details regarding the game that could be required for the plugin.**

**Comment by LonerEmperor** [comment]
Does it mean I can now use MO2 for The Sims 4?  Regards, Ian From: Jeremy RimpoSent: Friday, November 10, 2023 11:01 AMTo: ModOrganizer2/modorganizerCc: LonerEmperor; AuthorSubject: Re: [ModOrganizer2/modorganizer] Add support for game The Sims 4 (Issue #1890) Closed #1890 as completed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by LonerEmperor** [comment]
Does it mean I can now use MO2 for The Sims 4? Thanks.

**Comment by Silarn** [comment]
2.5.0 RC 1 includes a basic support plugin.
