### ISSUE TITLE
BodySlide only able to be run when MO is run as admin

### ISSUE THREAD

**Issue by GrantSP** [Modorganizer2/modorganizer#190]
# The problem

A user on the discord, @MadNugget posts that he can only get the FO4 tool BodySlide to work from MO2 if MO2 is running with elevated privileges

# Environment

* Mod Organizer Version that exhibits the issue: **2.1.1**
* Desktop OS/version used to run Mod Organizer: **Windows 10 on both systems**

# Details
MO2 must be run as admin to get tools to work

# Link to Mod Organizer logs

## USVFS
MadNugget's USVFS log
[https://pastebin.com/4J05gm4c](url)

My VFS when trying to do the same thing.
[https://pastebin.com/9dh3ViGe](url)

**Comment by Silarn** [comment]
This is a complete hunch -  but could you change your MO2 location such that there are no spaces in the path?

**Comment by Sir1Twist** [comment]
All of it is meant to be ran as Admin. MO, Bodyslide, even the game.

**Comment by GrantSP** [comment]
No. Nothing should be run as admin. If you have that situation then your OS is messed up.

**Comment by Sir1Twist** [comment]
I have spaces in where I have Mod Organizer installed, and I have had no problems with it. I also run it in both admin, and non-admin, and I have no problems. I had a problem, but it wasn't related to running things in admin. It was steam related, and thus not a problem with MO. It can be a good thing to run in admin mode. And also, if you install your game, and even MO, to Program files, or PF(x86). And if you run with UAC on.
