### ISSUE TITLE
Add /Geometries as recognized content 

### ISSUE THREAD

**Issue by twizz0r** [ModOrganizer2/modorganizer#1900]
**Is your feature request related to a problem? Please describe.**

Starfield has a /Geometries directory on the same level as /meshes, /textures, etc. 

MO2 should recognize mods that include this directory as having content.

Geometries are the actual mesh files in Starfield whereas NIFs contain pointers to the actual mesh. 

Do both get the mesh icon? Should a new icon be created for either?  Do  /Geometries get a new one?   I can help with that if a decision is made.

Example mod: https://www.nexusmods.com/starfield/mods/4874

**Comment by Silarn** [comment]
If you want to make a new icon for geometries, feel free.

**Comment by Silarn** [comment]
https://github.com/ModOrganizer2/modorganizer-game_starfield/pull/14

**Comment by Silarn** [comment]
I should probably also add 'videos' - @twizz0r do you think you can / want to make icons?

**Comment by twizz0r** [comment]
You bet. Just refresh my memory on the format you need.

**Comment by twizz0r** [comment]
[Geometries Icon](https://i.imgur.com/ODRYQcr.png)

[Video Icon](https://i.imgur.com/MxYKUwt.png)
