### ISSUE TITLE
Disabling Windows Defender

### ISSUE THREAD

**Issue by rtfmoz2** [ModOrganizer2/modorganizer#1914]
## The problem:
Your installation is trying to disable Windows defender for its directory.

![image](https://github.com/ModOrganizer2/modorganizer/assets/40995106/9fd4ce75-03ab-4d26-8d42-b8ba64a5766c)

## To Reproduce:
* Install release 2.4.4

## Environment:
* Windows 10 Professional
* Crowdstrike Threat Detection
* Mod Organizer 2.4.4
* Mod Organiser Download "Mod Organizer 2-6194-2-4-4-1640622655.exe"

## Details:
Why are you disabling a system tool that prevents malicious system behaviour?

![image](https://github.com/ModOrganizer2/modorganizer/assets/40995106/59f8b4ad-70b4-4312-be42-1f3c1d0e6e17)

**Comment by Silarn** [comment]
It's been an issue since day 1 that antiviruses falsely flag the custom virtual filesystem we use. This is for user convenience and this reality is literally in our documentation.

**Comment by Silarn** [comment]
Forgot to mention that this is one of the selectable options in the installer as well.
