### ISSUE TITLE
LOOT load order changes don't persist

### ISSUE THREAD

**Issue by olioster** [ModOrganizer2/modorganizer#1918]
If I use LOOT from MO2 to sort my load order, the changes LOOT does get reverted immediately after switching between the Plugins, Archives, etc tabs. MO2's sorting function works but takes so much longer than the newer LOOT versions.

**Comment by Holt59** [comment]
Are you sorting the plugin list by the correct column?

**Comment by olioster** [comment]
I'm not sure what you mean. I'm opening LOOT from the drop down program
list in MO2, sorting it, applying the sort and then closing LOOT and
returning to MO2. If I switch tabs back and forth, the sort appears to have
been applied but when I switch again, it's back to the way it was before
the sort.

**Comment by olioster** [comment]
Ah ok, I understand. I always have the load order sorted by priority so it
should be correctly reflecting my load order.

**Comment by Holt59** [comment]
What version of MO2 are you using?

**Comment by olioster** [comment]
2.4.4

**Comment by Holt59** [comment]
Could you upload logs after switching them to debug (in the Settings)?

**Comment by olioster** [comment]
It was too big to upload here so I put it on my Google Drive. Here is a link. https://drive.google.com/file/d/1r1iREL_aeOKhlkoaxa7rk9vUmEDBcZwF/view?usp=sharing

**Comment by Silarn** [comment]
I actually doubt this is a USVFS issue, can you attach the interface log as well?

**Comment by Silarn** [comment]
Off the top of my head the only reason MO2 would necessarily reorder plugins without user input would be if A) the load order files in the profile were not being written successfully causing it to eventually load the old order - but this is unlikely since it gets the load order from the plugins.txt LOOT writes or B) the plugins that are changing are technically force loaded and can't load where LOOT is trying to put them. But I'm not sure why that would happen because LOOT should be aware of those sorts of load order restrictions.

**Comment by olioster** [comment]
> I actually doubt this is a USVFS issue, can you attach the interface log as well?

[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/13311318/mo_interface.log)

**Comment by Holt59** [comment]
You have locking disabled, can you try with locking enable to see if it works?

**Comment by olioster** [comment]
That seems to have fixed the issue. Odd but I guess that's why it was set
on by default lol. Thanks for the help.

**Comment by Silarn** [comment]
The circumstances where I'd recommend doing that are very slim. The running VFS process will not recognize changes made in MO2 and the state of the files becomes somewhat ambiguous and prone to issues. I'm also not sure if MO2 will recognize when the application has been closed at that point, which is when it generally applies changes made to the load order by a running application.
