### ISSUE TITLE
MO2 doesn't launch, keeps open in task manager but nothing ever loads

### ISSUE THREAD

**Issue by xodotLBO** [ModOrganizer2/modorganizer#1922]
## The problem:
Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our [Discord server](https://discord.gg/ewUVAqyrQX).

## To Reproduce:

1. Go to 'mod launcher install folder'
2. Run 'modorganizer.exe'
3. -- ccc, nothing happens ---

## Environment:

* Mod Organizer Version that exhibits the issue: Latest 2.4.4 and even previous ones from GAMMA installations
* Last Mod Organizer Version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 11 now, used Windows 10 before and had no issues.

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

Not sure what else to describe nor how to get any logs since I can't launch it to debug.

**Comment by The-Rogan-josh** [comment]
Do you happen to have an AMD GPU?

I have the exact same issue and there is not a lot of information out there but someone has mentioned that AMD GPU drivers might be the issue.

**Comment by xodotLBO** [comment]
Apologies for not updating this. I've fixed it. It was on my end, I had a program called "Actual multiple monitors" which I use to manage my multiple monitors and it was, for some reason, blocking the program from SHOWING

**Comment by The-Rogan-josh** [comment]
Well glad you got it sorted out. Unfortunately I only have one monitor and no intermediate software to check.

**Comment by xodotLBO** [comment]
> Well glad you got it sorted out. Unfortunately I only have one monitor and no intermediate software to check.

This same program caused trouble for me earlier I don't know why I didn't test it instantly instead of going around complaining and trying to find solutions.. I don't think it's a famous software to use but I'm using it for 7-8+ years and pretty satisfied with it. 
Thanks for your reply and support for MO2!
