### ISSUE TITLE
Mods installed by MO2 don't work in Starfied XGP version

### ISSUE THREAD

**Issue by skyojoj** [ModOrganizer2/modorganizer#1939]
## The problem:
I follow the guide to install mods,but it doesn't work in game ,it works fine when I put them into XboxGames\Starfield\Content\Data directorycan't figure it out.

* Mod Organizer Version that exhibits the issue:2.5.0
* Desktop OS/version used to run Mod Organizer:WIN 11

**Comment by Holt59** [comment]
#1466
