### ISSUE TITLE
The modinfo of Plugins with the same name is not updated during refresh.

### ISSUE THREAD

**Issue by dunc001** [Modorganizer2/modorganizer#194]
# The problem

When switching profiles plugin masters are not being reparsed meaning plugins such as DynDOLOD.esp, SkyProc patches, etc which have different plugins per profile with common names are being flagged as having missing masters in switching profiles.

# Environment

* Mod Organizer Version that exhibits the issue: All recent versions up to and including latest 2.1.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Win 10 1079 FCE

**Comment by Silarn** [comment]
This is simply an issue with not refreshing the plugins and is hopefully a quick fix. I'll try to get this done before the next release.

**Comment by Silarn** [comment]
This issue has been resolved in development, with a release incoming.
