### ISSUE TITLE
MO2 Crash on Startup

### ISSUE THREAD

**Issue by PlatinumSix** [ModOrganizer2/modorganizer#1940]
## The problem:
Every time I attempt to launch MO2 I immediately get the message "The procedure entry point SystemParametersInforForDpi could not be located in the dynamic link library [my computer file path]\Qt6Gui.dll." This is followed by a crash.

## To Reproduce:

1. Go to 'ModOrganizer.exe'
2. Execute application.
3. Crash.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.5.0
* Last Mod Organizer Version that did not exhibit the issue (if applicable): Version 2.4.4
* Desktop OS/version used to run Mod Organizer: Windows 8.1.

## Link to Mod Organizer logs:
I cannot complete this part due to not being able to open MO2.

### USVFS:
I cannot complete this part due to not being able to open MO2, and thus being unable to create logs.

### MO Interface:
I cannot complete this part due to not being able to open MO2, and thus being unable to create logs.

**Comment by Silarn** [comment]
Unfortunately, as listed in the release notes, Qt 6 and Python 3.11 both require Windows 10. This is a hard restriction for 2.5.0.
