### ISSUE TITLE
Skyrim update 1.6.1130 doesn't read mods in load order as 'active'

### ISSUE THREAD

**Issue by Mpayatt** [ModOrganizer2/modorganizer#1944]
## The problem:
loading up a skyrim save after the update leads to the following message.
" This save relies on Creations you have already downloaded but are currently inactive. Activate now?"
yes causes the game to crash. No leads to the standard error message for loading when mods in the save aren't present. Either way it crashes

## To Reproduce:
1) Allow Steam to update skyrim to the newest version 1.6.1130
2) launch with most recent SKSE64 with as many of your mods updated as possible. They should be ticked in the load order to indicate they are active.
3) load a modded save

## Environment:
* Mod Organizer Version 2.5.0
* introduced with skyrim 1.6.1130
* Windows 10

## Details:
It has been suggested that this is tied to some new load order feature in skyrim that might be superceding the MO2 load order, so the mods are read as 'downloaded' but not 'active'.
https://www.reddit.com/r/skyrimmods/comments/18cu4gl/an_issue_with_mod_installation_after_a_161130/

**Comment by Holt59** [comment]
Did you check if this was related to the SSE Engine Fix bug? 

https://www.reddit.com/r/skyrimmods/comments/18btob5/updated_information_about_the_new_skyrim_update/

**Comment by Mpayatt** [comment]
No dice, unfortunately

**Comment by Mpayatt** [comment]
Ah, solved, it was an issue with SKSE Engine Fixes. having mod achievements set to true clashes with the setting associated with creation club mods in the new system.

**Comment by Mpayatt** [comment]
External issue, see https://www.nexusmods.com/skyrimspecialedition/mods/17230?tab=posts
