### ISSUE TITLE
Accidentally deleted creation club content and can't recover it

### ISSUE THREAD

**Issue by BobertoRodriguezFactorez** [ModOrganizer2/modorganizer#1947]
## The problem:
Creation Club content is gone and verifying files on steam doesn't seem to recover it, however the creation club menu is also gone, and no matter how I open skyrim, with, or without mods, I can't seem to find a creations menu to redownload the content. I accidentally deleted the content after I restored a backup of my mods and noticed in the overwrite directory was two sets of each creation club mod, and me being a big stupid idiot, deleted all of them.

## To Reproduce:

1. Create backup of all mods
2. Restore Backup
3. Delete all Creation club mods in the Overwrite Directory

## Environment:

* Mod Organizer Version  2.5.0 
* USVFS: 0.5.5.1
* Windows 11

## Details:
![20231211153504_1](https://github.com/ModOrganizer2/modorganizer/assets/153559772/19c63920-ae28-4f26-b80d-4e5b37aa488b)

**Comment by BobertoRodriguezFactorez** [comment]
I forgot to put the other image, my apologies
![Screenshot 2023-12-11 154536](https://github.com/ModOrganizer2/modorganizer/assets/153559772/08d33c53-79cb-4cd1-8092-607f5f1f8530)

**Comment by BobertoRodriguezFactorez** [comment]
Well, I figured there was no harm in messing with the game files to try and enable the "Thank you for purchasing Skyrim Anniversary Edition..." message so I could maybe redownload the files, and lo and behold, it worked! So I no longer need assistance.

**Comment by WyattTheSans** [comment]
Having the same issue here but differently for Fallout 4... I accidentally deleted the whole data folder, but I got it back so no worries there... Except I lost a few creation club items when my mods deployed so... Yeah... I'm screwed. And plus the weirdest part is that I can't redownload it cause for some reason it's stuck on being "owned."

**Comment by vooprin** [comment]
I'm having the same issue as you were @BobertoRodriguezFactorez, I'm wondering how you were able to make the thank you message pop up because my creation club content is also gone. Any help would be great!
