### ISSUE TITLE
Unable to reorder plugins and mods in MO2

### ISSUE THREAD

**Issue by nosnowowie93347** [ModOrganizer2/modorganizer#1953]
## The problem:
Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our [Discord server](https://discord.gg/ewUVAqyrQX).

I am unable to drag any of my mods or plugins to change the order in MO2

## Environment:

* Mod Organizer Version that exhibits the issue: It was happening on V.2.5.0 so i updated to 2.5.1 and it's still happening so both these versions
* Desktop OS/version used to run Mod Organizer: Windows 10

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/13721076/mo_interface.log)
[usvfs-2023-12-14_00-42-29.log](https://github.com/ModOrganizer2/modorganizer/files/13721077/usvfs-2023-12-14_00-42-29.log)
[usvfs-2023-12-14_01-25-45.log](https://github.com/ModOrganizer2/modorganizer/files/13721078/usvfs-2023-12-14_01-25-45.log)
[usvfs-2023-12-15_22-38-15.log](https://github.com/ModOrganizer2/modorganizer/files/13721079/usvfs-2023-12-15_22-38-15.log)
[usvfs-2023-12-16_02-21-42.log](https://github.com/ModOrganizer2/modorganizer/files/13721080/usvfs-2023-12-16_02-21-42.log)
[usvfs-2023-12-16_20-33-47.log](https://github.com/ModOrganizer2/modorganizer/files/13721081/usvfs-2023-12-16_20-33-47.log)
[usvfs-2023-12-16_21-11-15.log](https://github.com/ModOrganizer2/modorganizer/files/13721082/usvfs-2023-12-16_21-11-15.log)

**Comment by glimmerwell** [comment]
OMG! I have this issue, too, after updating to MO2 v.2.5.0. I am at a standstill!

On MO2's right side Plugin tab, I can barely move many of the plugins up or down. If I send them pretty far up I can't trust where they end up.

I see the issue is closed. How was it resolved?
