### ISSUE TITLE
Mod categories are set incorrectly upon installation for Fallout: New Vegas

### ISSUE THREAD

**Issue by oabdellatif** [ModOrganizer2/modorganizer#196]
# The problem

Installing mods for Fallout: New Vegas from Nexus downloaded using the "mod manager download" link results in the incorrect category being set in most cases. For example, a mod in the "Models and Textures" category is marked as a "Companion" mod upon installation. I have not verified whether this issue affects any other games, like Fallout 3, but Skyrim and Skyrim: Special Edition do not seem to exhibit it.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 10, version 1709

# Link to Mod Organizer logs

## MO Interface
https://gist.github.com/oabdellatif/f0f52de927a430eb1623fed41b266a81

**Comment by Silarn** [comment]
Yes, this is an oversight of the old MO2 code which assumes all categories are the same ID. Either Nexus made a change or MO never properly managed Nexus categories.

As mentioned in another ticket, we will need to break out the categorization code per game to account for different Nexus category IDs.

**Comment by Al12rs** [comment]
Here are the plans for categories in the future #253 closing for organization
