### ISSUE TITLE
MO2 Failed To initialize plugin after updating from 2.4.4 to 2.5

### ISSUE THREAD

**Issue by Sash1miboy** [ModOrganizer2/modorganizer#1963]
After updating my mo2 to 2.5, when i launch it, always show me this error message

![mo2-error](https://github.com/ModOrganizer2/modorganizer/assets/115966887/a92d1977-eca7-409e-ba90-d906116bb36c)

how can i fix this problem? or should i downgrade to v2.4.4?

**Comment by Sakurasrb** [comment]
how did you solve it? same issue for me
