### ISSUE TITLE
Python DuplicateOptionError on MO2 1.50 start

### ISSUE THREAD

**Issue by nesingho** [ModOrganizer2/modorganizer#1967]
## The problem:

After update from MO2 1.4.4 starting MO brings up an error message:

```
Error

failed to initialize plugin ../MO2/plugins/basic_games:
DuplicateOptionError: While reading from '<string>' [line 17]:
option 'user.throttle.bandwidthkbps' in section
'mod_organizer' already exists

At:
 configparser.py(1112): _read
 configparser.py(734): read_file
 configparser.py(739): read_string 
 ../MO2/plugins\basic_games\eadesktop.utils.py(40): find_games
 ../MO2/plugins\basic_games\basic_game.py(398): setup
 ../MO2/plugins\basic_games\__init__.py(16): <module> <frozen importlib._bootstrap>(241):_call_with_frame_removed
 <frozen importlib._bootstrap_external>(940): exec_module
 <frozen importlib._bootstrap>(705): _load_unlocked
 <frozen importlib._bootstrap>(1149): _find_and_load_unlocked
 <frozen importlib._bootstrap>(1176): _find_and_load
```

## To Reproduce:
Update from 1.4.4 or new install in fresh folder.

## Environment:

* Mod Organizer Version that exhibits the issue: 1.5.0
* Last Mod Organizer Version that did not exhibit the issue (if applicable): 1.4.4
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro 22H2 

## Details:
MO2 starts without problems after klicking away this error message.
I've searched all files in MO2 relevant folders for the option 'user.throttle.bandwidthkbps' with grepwin but found nothing.

## Link to Mod Organizer logs:
No log entries

### USVFS log:

```
12:45:43.650 [I] usvfs dll 0.5.5.1 initialized in process 9108
12:45:43.651 [D] remove from process 9108
12:45:43.651 [I] create config in 9108
12:45:43.651 [I] 0 processes
12:45:43.651 [I] mod_organizer_instance_1 created in process 9108
12:45:43.651 [I] attached to mod_organizer_instance_1 with 1 nodes, size 4,194,304 B
12:45:43.651 [I] inv_mod_organizer_instance_1 created in process 9108
12:45:43.651 [I] attached to inv_mod_organizer_instance_1 with 1 nodes, size 131,072 B
12:45:43.651 [D] context current shm: mod_organizer_instance (now 2 connections)
12:45:43.651 [D] clearing blacklist
12:45:43.651 [D] blacklisting 'Chrome.exe'
12:45:43.651 [D] blacklisting 'Firefox.exe'
12:45:43.651 [D] blacklisting 'TSVNCache.exe'
12:45:43.651 [D] blacklisting 'TGitCache.exe'
12:45:43.651 [D] blacklisting 'Steam.exe'
12:45:43.651 [D] blacklisting 'GameOverlayUI.exe'
12:45:43.651 [D] blacklisting 'Discord.exe'
12:45:43.651 [D] blacklisting 'GalaxyClient.exe'
12:45:43.651 [D] blacklisting 'Spotify.exe'
12:45:43.651 [D] blacklisting 'Brave.exe'
12:45:43.651 [D] clearing forced libraries
```

### MO Interface:

Nothing related but the error message:

[mo_interface.log](https://gist.github.com/nesingho/38515dabd13b797fb82a0678bdf0522b#file-mo_interface-log)

**Comment by Holt59** [comment]
This look like a broken settings file for EA Desktop - Maybe try starting EA Desktop, modifying a setting and then saving, and then relaunching MO2, maybe it will fix the file.

Otherwise, look at the settings file (`"%LocalAppData%/Electronic Arts/EA Desktop/user_xxx.ini`) and remove the duplicate options.

**Comment by nesingho** [comment]
> Otherwise, look at the settings file ("%LocalAppData%/Electronic Arts/EA Desktop/user_xxx.ini) and remove the duplicate options.

That did the trick.
The ini had two identical entries of this parameter -> deleted one -> No error. 

Many thanks!
