### ISSUE TITLE
Mo Crash when left Idle in background.

### ISSUE THREAD

**Issue by CptMcSplody** [Modorganizer2/modorganizer#197]
# The problem

Mo Crashes when left Idle in background for an extended period. 10 - 20 mins

# Environment
win 10 ver 1709 build 16299.192
* Mod Organizer Version that exhibits the issue: 2.1.1 - standalone
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

[Dumps & logs.zip](https://github.com/LePresidente/modorganizer/files/1609036/Dumps.logs.zip)

**Comment by erasmux** [comment]
Dump shows that we crashing when the findFile in the following line returns nulls:
https://github.com/LePresidente/modorganizer/blob/new_vfs_library/src/pluginlist.cpp#L124
Obviously we could prevent a crash by checking for null, but should at least do a minimal effort to understand the root cause here.

**Comment by Silarn** [comment]
I've certainly had MO open for a long time without crashes. The other ticket has a strange use case as well where - if I'm reading it right - he moved files outside MO then tried to move the same files inside MO. This is a case we should account for I guess but a very strange edge case and I assume having MO refresh the files before attempting to move them would fix it by correcting the file references.

**Comment by CptMcSplody** [comment]
@Silarn I've also had it open for longer periods without crash, in fact it has been open for several hours now without being used, and no crash. I also believe that MO being idle is not the root cause, but just the state the program was in when it happened to crash.

**Comment by Silarn** [comment]
Have you seen this happen recently? I'm not sure I've ever seen it or seen another report.

**Comment by CptMcSplody** [comment]
No haven't had it happen, will close it.
