### ISSUE TITLE
Crash after moving mod files

### ISSUE THREAD

**Issue by CptMcSplody** [Modorganizer2/modorganizer#198]
# The problem
MO crashes when moving files within MO, this is after moving files from one mod folder to another outside of MO.

# Environment

* Mod Organizer Version that exhibits the issue:2.1.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: win 10 ver 1709 build 16299.192

# Details
 dumps

https://drive.google.com/file/d/1xKUpIIlsW5ohCUQkkMtZK0lXca7A5RMR/view?usp=sharing

**Comment by Silarn** [comment]
Can we verify this is still an issue with the latest builds? It's not really a normal use case but we should account for it.

**Comment by CptMcSplody** [comment]
Haven't had this in a while.
