### ISSUE TITLE
MO2 2.5.X crash on proton

### ISSUE THREAD

**Issue by TyroneWatermelon420** [ModOrganizer2/modorganizer#1980]
## The problem: MO2 2.5.X crashes proton
When launching MO2 2.5.X through proton or wine on linux I get the following error in the terminal

[2024-02-01 14:57:33.141 W] SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2) failed: COM error 0x57: Ung├╝ltiger Parameter.
[2024-02-01 14:57:33.142 W] Qt's default DPI awareness context is DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2. If you know what you are doing you can overwrite this default using qt.conf (https://doc.qt.io/qt-6/
highdpi.html#configuring-windows)
creating minidump for the current process
trying file '.\ModOrganizer-2.5.1rc2-20240201T145733.dmp'
writing mini minidump
minidump written correctly
[2024-02-01 14:57:52.130 E] ModOrganizer has crashed, core dump created.
wine: Call from 000000007B00CDB7 to unimplemented function vcruntime140.dll.__C_specific_handler_noexcept, aborting

## To Reproduce:
1. Install MO2 2.5.X on linux
2. Launch MO2 2.5.X through wine or proton
3. crash

## Environment:

* Mod Organizer Version that exhibits the issue: 2.5.X
* Last Mod Organizer Version that did not exhibit the issue (if applicable): 2.4.4
* Desktop OS/version used to run Mod Organizer: Archlinux

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
Log: not created

dmp: [Here](https://github.com/TyroneWatermelon420/mo2crashdmp/blob/main/ModOrganizer-2.5.1rc2-20240201T145733.dmp)

**Comment by AnyOldName3** [comment]
If you can't reproduce this on Windows, you need to report it on Proton's tracker rather than ours. We can't fix bugs in Proton (which basically means anything that behaves differently on Proton to Windows), but the Proton team can.

**Comment by TyroneWatermelon420** [comment]
Ok from what I´ve found out its a problem with QT6 under wine which is fixed in wine 9, but beceause Proton is still based on wine 8 its crashing under it. LOOT has the same problem with QT6 under wine 8 but apparently when the app is cross compiled under linux for windows it has no problems.
