### ISSUE TITLE
Cannot link my Nexus account (MO2 "Failed to set API key")

### ISSUE THREAD

**Issue by MonkeyAdmirer** [ModOrganizer2/modorganizer#2007]
## The problem:
I was trying to link my Nexus account to MO2 so I could install mods directly. When I tried to connect the account by opening Nexus and clicking 'Authorise', MO2 said it had "Failed to set API key" so I tried it again by manually inputting the API key and the same issue persisted. I even regenerated new API keys and none of them worked.

## To Reproduce:

1. Go to 'Settings'
2. Click on 'Nexus'
3. Click on 'Connect to Nexus'
4. Read the box in the right of the 'Nexus Connection' section

## Environment:

* Mod Organizer Version that exhibits the issue: v2.5.1rc2
* Last Mod Organizer Version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10 version 22H2

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.
![image](https://github.com/ModOrganizer2/modorganizer/assets/166180701/ae2040f4-91a8-4400-a050-1f1d3d0e16ca)
I go here ^

![image](https://github.com/ModOrganizer2/modorganizer/assets/166180701/f2913568-f2a0-49ae-bdd3-c26759f4475b)
I click this ^

![image](https://github.com/ModOrganizer2/modorganizer/assets/166180701/e93d35aa-81b0-4206-b4ea-e5b673257650)
I click authorise^

![image](https://github.com/ModOrganizer2/modorganizer/assets/166180701/8a5eccb0-99d2-4bf2-8b4c-56edcc19fa42)
This occurs ^

The same thing happens if I enter the API key manually.

## Link to Mod Organizer logs:

[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/14891388/mo_interface.log)

Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS: https://gist.github.com/MonkeyAdmirer/c7bc0a2e93e93e72c2afcd80c16d1fcc#file-usvfs-2024-04-05_22-47-20-log
Create a [GIST](https://gist.github.com) which is a paste of your latest USVFS log, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface: https://gist.github.com/MonkeyAdmirer/a86ee488526c93dc0b8d99c08f7bdcc2#file-mo_interface-log
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by chaswa101** [comment]
I am having the same problem but on Windows 11.

**Comment by dev-kreg** [comment]
Same issue, Win 11 and I see this error in the console log:

`[2024-04-15 22:10:27.677 E] Storing API key failed: Notenoughmemoryresourcesareavailabletoprocessthiscommand. (0x8)`

**Comment by jinchu18** [comment]
I get the same error in the console log as @dev-kreg

**Comment by jinchu18** [comment]
> I get the same error in the console log as @dev-kreg

For anyone with similar issue, go to credentials manager and delete the sso credential should be at the bottom of the list. then re-launch mo2 and reconnect nexus. worked for me

**Comment by MonkeyAdmirer** [comment]
I figured out the issue, it was because my credentials vault, (and probably yours too) was full and my computer didn’t have enough memory left in the vault so in order to add the nexus API key, you have to delete a credential from the vault using Credential Manager (search it in taskbar) and delete a credential that you don’t need to make space for the API key. After you do this, your computer will have enough space into store the API key and you will be able to link your nexus account.
