### ISSUE TITLE
Fallout 4 DLC "unrecognized .bsa" error.

### ISSUE THREAD

**Issue by themotorhead30** [Modorganizer2/modorganizer#201]
# The problem

Mod Organizer gives the "failed to read mod: failed to parse bsa: not a bsa file" error for the official Fallout 4 DLC that it is not supposed to manage.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.0.8
* Desktop OS/version used to run Mod Organizer: Windows 10 64bit version 1703

**Comment by mrudat** [comment]
Please double-check version number; I had the same symptoms, but upon further investigation I was running an older version of Mod Organiser (due to having multiple copies installed). Running the correct version appears to have made the symptoms go away.

**Comment by Silarn** [comment]
Closing ticket due to lack of activity.
