### ISSUE TITLE
Handle conflicts with AI, maybe interface with OpenAI API

### ISSUE THREAD

**Issue by Melivo** [ModOrganizer2/modorganizer#2024]
**Is your feature request related to a problem? Please describe.**
Sometimes my game crashes. It would be cool to have an AI like ChatGPT to be able to look into the files and ask questions about the problem.

**Describe the solution you'd like**
Troubleshooting mod conflicts with ChatGPT.

Example: ChatGPT should search for mod conflicts and ask me which file I would prefer to replace. It should tell me and give a short explanation of what conflict there is. E.g. texture. mesh, etc. Also, I want to be able to ask questions about the conflict. E.g. I don't know much about NavData in Bethesda games, so that would be nice.

**Describe alternatives you've considered**
Interfacing with any other AI works to but I think ChatGPT is the best solution.

**Additional context**
The idea is basically to enhance Mod Organizer with an AI that is able to make changes on its own so that the user doesn't have to click through several prompt windows and not sure what conflict files he wants to have replaced or doesn't know what mods cause a conflict.

**Comment by AnyOldName3** [comment]
This is something that might be feasible with a MO2 plugin and only once someone figures out how to deal with the current diminishing returns of large language models, as they're currently only clever enough to guess plausible wrong answers for this kind of thing, not clever enough to actually help you. It's not something that can be put into MO2 itself any time soon, thanks to AI being to dumb to work for this, but if a good enough plugin was created, we might eventually start bundling it.

**Comment by Melivo** [comment]
I see, that makes sense. Thanks for the thorough explanation!

**Comment by Melivo** [comment]
I see, that makes sense. Thanks for the thorough explanation!
