### ISSUE TITLE
More In-Depth Filter That Can Read Notes Rather Than Only Comments

### ISSUE THREAD

**Issue by devthedevin** [ModOrganizer2/modorganizer#2038]
**Is your feature request related to a problem? Please describe.**
It's more of a personal problem, but after organizing a lot of my mods, MO2 seems to be unable to search through my Notes and only reads the comments instead, which can cause some headaches for patching with my modlist.

**Describe the solution you'd like**
An expansion to the Filter function in MO2, which can read through Notes alongside Comments.

**Describe alternatives you've considered**
Maybe it could be a toggle of some kind if users do not want it, being disabled by default?

**Additional context**
I believe it is easy to imagine a function like that once you try testing it out yourself in MO2 and see that it does not work.

**Comment by Holt59** [comment]
Might not have time to work on this but this should be pretty straightforward to do by updating https://github.com/ModOrganizer2/modorganizer/blob/master/src/modlistsortproxy.cpp#L462 for `ModInfo::notes`.
