### ISSUE TITLE
MO2 Refuses to run anything

### ISSUE THREAD

**Issue by Marrionetta** [ModOrganizer2/modorganizer#2042]
![ModOrganizer_PfogJHdtUK](https://github.com/ModOrganizer2/modorganizer/assets/88773456/b6a4b3eb-841c-4ac5-85a3-fd8984c1ca25)
![ModOrganizer_Lf6JO1TcTu](https://github.com/ModOrganizer2/modorganizer/assets/88773456/519906c1-16f6-4a45-a6ff-b7610dca70dc)
No matter what i do, these are the following errors i receive. It's either whining that this effing file path
X:/SteamLibrary/steamapps/common/Cyberpunk 2077/r6/cache/final.redscripts
is the same as this one
X:/SteamLibrary/steamapps/common/Cyberpunk 2077/r6/cache/final.redscripts (Which fking duh!!)

or its complaining that it can't find the cache folder in my overwrite but it refuses to save anything added to it so even if i try to make it myself it won't save it and will just refuse to run. Im running MO2 as admin and it worked perfectly fine yesterday so idk what's going on please tell me what i gotta do to fix this. reinstalling MO2 didn't work.

**Comment by DSeyka** [comment]
This error seems familiar. Read-only flags on those files or folders?

**Comment by Marrionetta** [comment]
I don't recall exactly what I did to fix it but I did. I deleted the plug in then got a new one from the github but I think what really did it was I deleted everything in the r6/cache finger then verified. I think that's what I did to fix it I'm not entirely sure.

**Comment by NotHighEnough** [comment]
I just had this same exact issue. I fixed it by copying the files in the r6 cache folder in the installed files to the r6 cache folder in the overwrite folder in the folder I'm storing the mod files in. I'm sorry if I don't make a whole lot of sense, I'm not a technical person. Hope this helps anyone else having problems.
