### ISSUE TITLE
[long message] does not accept mod manager downloads from nexus

### ISSUE THREAD

**Issue by lettuce-prey** [Modorganizer2/modorganizer#205]
# The problem
 i  can’t get through the tutorial, and have just skipped it.
The reason  i  can’t get through the tutorial is that  i  can’t get MO2 to receive \ accept the files when  i  tell nexus to use the manager download.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Mod Organizer: win 7 64bit 32gigs of ram

# Details
What have  i  done so far as troubleshooting?
Many things,  i ‘ll list them.
Not in any specific order because  i  have run through these actions a few times with the idea that the order of actions might make a difference.
One thing that  i  started with and before and during each installation was to be sure  i  was working in admin mode and the program had admin permissions.
 i  do not use F4SE.
Mo2 has it’s own directory [J:\MO2modorganizer\] on a drive different than the raid array [windows drive r:\steam\] where  i  keep the steam directory  
As the tutorial instructs,  i  clicked on the button instructing MO2 to intercept the files to be sent from nexus to the mod manager of my choice that is set to accept them.
MO2 in this case.
At first this still invoked the NMM, and so  i  went into the windows control panel [yes  i  was alone and unarmed] and set things to the mod organizer exe file.
So now it’s not calling NMM, but it’s not calling anything else.
Clicked on the button in the MO2 settings to grab the files from nexus again.
Restarted mo2.
Then went to control panel settings and took turns selecting each exe file in the MO2 home directory, and restarting windows each time.
 i  swear that  i  have rebooted this machine more today than in the rest of the year combined.
Oh wait we’re only in this year by 18 days, never mind.
So  i  went back and read the description at nexus for mo2.
 i  needed some programs from microsoft.
 i ‘ve downloaded a bunch of things from them to run stuff game related over the past couple of years and figured that  i  probably already had those so  i  skipped over them.
So  i  read the comments on what  i  was supposed to get from microsoft and clicked on the links.
Each time  i  arrived on the microsoft site with several selections, and none of them fit the description on my mo2 installation instructions.
So since  i  didn’t know what it was  i  was supposed to get  i  just downloaded and installed  everything that didn’t require me to log in and join the happy visual c developers club or buy a license.
More rebooting here.
Well  i  don’t plan on ever being a software developer, but if  i  DO  i ‘m loaded and ready.
Maybe,  i ‘m not sure.
Deleted the install.
checked github, [github.com/LePresidente/modorganizer/releases]
Downloaded latest from there and found that it was what  i  already had.
 reinstalled, clicked the correct buttons, started the tutorial.
Still no download.
Went through all of the exe files in the mo2 dir and connected them with the settings in control panel.
Nothing.
 i ‘m sure that  i  can just go back to NMM and it will work just fine, but  i  like the description of features for MO2 much better.

steam list of my system
Yea it’s not the best hardware, but  i  claim bragging rites for the OS Install Date: Dec 31 1969.
 i  was in high school in anchorage and my physics teacher said that time travel was impossible.
HA!
It was a very good year.
Computer Information:
    Manufacturer:  ASUS
    Model:  All Series
    Form Factor: Desktop
    No Touch Input Detected
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Supported
Operating System Version:
    Windows 7 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0
Video Card:
    Driver:  NVIDIA GeForce GTX 760
    DirectX Driver Name:  nvd3dum.dll
    Driver Version:  22.21.13.8541
    DirectX Driver Version:  22.21.13.8541
    Driver Date: 8 21 2017
    OpenGL Version: 4.5
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    DirectX Card: NVIDIA GeForce GTX 760
    VendorID:  0x10de
    DeviceID:  0x1187
    Revision:  0xa1
    Number of Monitors:  3
    Number of Logical Video Cards:  3
    No SLI or Crossfire Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 5760 x 1080
    Primary Display Size: 26.65" x 15.00" (30.55" diag)
                                            67.7cm x 38.1cm (77.6cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4095 MB
    Supported MSAA Modes:  2x 4x 8x 
Sound card:
    Audio device: Speakers (Realtek High Definiti
Memory:
    RAM:  32447 Mb
Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  6676195 Mb
    Largest Free Hard Disk Block:  2632053 Mb
    OS Install Date: Dec 31 1969
    Game Controller: None detected
    VR Headset: None detected

**Comment by Al12rs** [comment]
I'm pretty sure tutorials have never been updated to support the MO2 changes, so I would expect them to be broken. I would say the priority on fixing this is very low, since people can just skip them and never see them again. Future changes could potentially break them again even if fixed. Thanks for the report though, this will help to keep track of the stray issues.

**Comment by Silarn** [comment]
The tutorials WERE updated but since the archive tab was added back we need to update that tutorial index so it targets the correct tab.

**Comment by lettuce-prey** [comment]
you're right, i should not have mentioned the tutorial.
the problem is that clicking on the button at nexus to download with the mod manager does not activate the mod manager to start the download.
the rest of the message is a description of what i tried to do to fix this and why i tried those things.
i clearly did not organize the information in an easily understandable format.
my bad.

**Comment by Silarn** [comment]
It sounds like you simply don't have nxmhandler configured as the default NXM link handler. Run the exe (located in the MO directory) and hit the button to set it as the active handler - and make sure there's an entry for the appropriate game(s) and MO.exe listed. (This can also be done by hitting the associate button in the MO settings.)

**Comment by lettuce-prey** [comment]
i'm still exploring different workarounds and re-installs and things.
i'm glad to see Silarns remarks because i see that we are thinking the same things.
these were the first things i checked on.
i know that i'll get this worked out and the most frustrating part is that i KNOW it's working for other people, so it means the error is mine.
i just have to find it.
and when i DO eventually find what it took to fix it [no matter how embarrassingly simple it was] i'll come back and post what i did just in case there might be someone else having a similar problem.
till then i am occasionally working on it.

thank you all for your comments.
