### ISSUE TITLE
The application must run to completion because its output is required

### ISSUE THREAD

**Issue by JessieKr** [ModOrganizer2/modorganizer#2067]
Can't run the game via ModOranizer, got the message "**the application must run to completion because its output is required**" and then nothing happened

I did:
   1. Prerequisites (C++, NET, disable OneDrive, Steam autoupdate, overlay)
   2. Set up Skyrim to English
   3. Set up Pagefile and Shader Cache Size
   4. Donload all CC content on fresh copy
   5. Sucessfully installed all mods via wabbajack
   6. Add folders in Exclusion ![image](https://github.com/Geborgen/nordic-souls/assets/18751544/ced69170-ebfb-4146-8792-dc596e1ca94c)
   7. When I click RUN in ModOrganizer.exe this message Pop-UP 
   ![Screenshot 2024-07-08 130011](https://github.com/Geborgen/nordic-souls/assets/18751544/89c5bb9e-fd21-480a-8de6-f724f1556ecf)
I see that on Steam the game starts (the button changes from “play” to “close”, but Skyrim itself does not start) after 10-15 seconds the message window in ModOrganizer disappears and on Steam the “close” button changes back to “play”. 
  8. Then some loading occurs in ModOrganizer after which nothing happens 
  ![image](https://github.com/Geborgen/nordic-souls/assets/18751544/7d57da0e-806a-412a-8f20-740aac2c85cf)
  9. Checked the logs of mo_interface, which indicate that the RivaTuner (MSI Afterburner) program may cause problems. Exit the program. I tried to run it again and nothing happened, this time the logs seemed to be without errors.
[mo_interface.log](https://github.com/user-attachments/files/16126387/mo_interface.log)
  10. Checked the logs of usvfs-2024 and it seemed to be withouth errors. [usvfs-2024-07-08_10-33-16.log](https://github.com/user-attachments/files/16126448/usvfs-2024-07-08_10-33-16.log)

Steam itself     is installed in the path  _C:\Program Files (x86)\Steam_
Skyrim             is installed in the path  _F:\SteamLibrary\steamapps\common\Skyrim Special Edition_
Wabbjack        is installed in the path  _F:\wabbajack_
Nordick Souls is installed in the path _F:\Nordic Souls_

F: disc got 20 Gb assigned to Pagefile and now I have 100+ Gb of free space left

**Comment by jvalenti2** [comment]
did you ever figure this out? I am having the same issue and I have no idea what to do

**Comment by JinEhCAT** [comment]
I'm having the exact same issue. Can anyone offer any help?

**Comment by jvalenti2** [comment]
> I'm having the exact same issue. Can anyone offer any help?
dont click "unlock" and let the game run. It eventually should start up, it just takes a while

**Comment by JinEhCAT** [comment]
> > I'm having the exact same issue. Can anyone offer any help?
> > dont click "unlock" and let the game run. It eventually should start up, it just takes a while

Hi. I have tried waiting, but it gets to a black screen with enb related sentences on the top left, and then it just crashes to desktop. I have no clue what could be causing this.

**Comment by JessieKr** [comment]
The only thing that helped 

> did you ever figure this out? I am having the same issue and I have no idea what to do

In my case, the problem was related to OneDrive, which somehow changed the paths to folders with documents on the C:/ drive. Completely disabling OneDrive or any fight against it did not help me. The only thing that solved the problem was a complete reinstallation of Windows on a version of Windows where OneDrive was completely cut and disabled. I also recommend installing Windows initially in English.

**Comment by JessieKr** [comment]
> I'm having the exact same issue. Can anyone offer any help?

In my case, the problem was related to OneDrive, which somehow changed the paths to folders with documents on the C:/ drive. Completely disabling OneDrive or any fight against it did not help me. The only thing that solved the problem was a complete reinstallation of Windows on a version of Windows where OneDrive was completely cut and disabled. I also recommend installing Windows initially in English.

**Comment by JessieKr** [comment]
In my case, the problem was related to OneDrive, which somehow changed the paths to folders with documents on the C:/ drive. Completely disabling OneDrive or any fight against it did not help me. The only thing that solved the problem was a complete reinstallation of Windows on a version of Windows where OneDrive was completely cut and disabled. I also recommend installing Windows initially in English.

**Comment by WilhelmRyan2113** [comment]
Well I am still having this issue, I'm also an AMD user, and I changed all 3 "skyrimprefs.ini" from 0 to 1 in the "profiles" folders: "Normal", "Performance", and "UIltra" (which is what it's trying to use) and it's still giving me that same error message. I click unlock and it eventually loads with the black screen and "ENBSeries compiling shaders, please wait. Delete enbcache folder if preset's files are modified or on d3d11.dll update." I deleted the enbcache folder(s) and still the same issue. I don't know what else to change or edit at this point...

**Comment by wyatthannon** [comment]
I'm guessing this is related to LoreRim? I was getting the same error, for me I had a small button that said "Unlock" at the bottom of the error message. At first I was pressing it, and then nothing would happen. Finally, instead of pressing it, I just let ModOrganize sit for a few minutes and Skyrim eventually loaded, it took about five minutes for everything to fully load to where I was actually able to see "New, Load, and Quit" on the main screen and all mods loaded in fine.

**Comment by QuangGau** [comment]
> > > I'm having the exact same issue. Can anyone offer any help?
> > > dont click "unlock" and let the game run. It eventually should start up, it just takes a while
> 
> Hi. I have tried waiting, but it gets to a black screen with "enb series compiling shaders, please wait" on the top left, and then it just crashes to desktop. I have no clue what could be causing this. My specs are more than good enough for recommended requirements, I have everything installed outside of program files, I have uninstalled and re installed skyrim... Is it a mod causing the issue..?
> 
> (EDIT) ------- SOLUTION!!! I figured it out thankfully, as it was driving me nuts. You're probably an AMD user if you have the same problem I assume. If so, then, simply open up Mod Organiser, and scroll down to the line where is says in big bold letters; "AMD USERS DISABLE THESE AND IN PROFILES - SKYRIMPREFS.INI"..." and just do as it says. Facepalm moment for sure...

Hi, I'm currently having the same problem which is when I open Skyrim SE via Steam, the app just completely black an on top of the screen it said "enb series compiling shaders, please wait", when I tried to click on the screen, window said that Skyrim SE was not responding, can you tell me more on how to fix that problem, I'm currently using a laptop with AMD Ryzen, tysm
