### ISSUE TITLE
an error occurred: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by HashiraPawz** [ModOrganizer2/modorganizer#2071]
This is on Mod Organizer 2.5.0. Everything was working fine, but my computer was running a bit slow. I properly exited every program and then restarted my computer. Upon opening it again, I find I practically can't do ANYTHING on mod organizer 2 without the following error message popping up:
![Screenshot (136)](https://github.com/user-attachments/assets/6d34ae65-6bc1-43da-b311-d0459f962eb0)
Attached are my log files: Is there any way to fix this?
[mo_interface.log](https://github.com/user-attachments/files/16243444/mo_interface.log)

**Comment by HashiraPawz** [comment]
As an addon to this, all of my mods were moved to the "overwrite" section, and whenever I try to move them out, MO2 instantly crashes.

**Comment by Silarn** [comment]
Overwrite isn't a section, it sounds like you changed the sorting of the columns. 

As far as the initial error, that appears to be coming from root builder which is a third party plugin. You should open a ticket with kezyma.
