### ISSUE TITLE
Custom game option for new profiles.

### ISSUE THREAD

**Issue by malice936** [ModOrganizer2/modorganizer#2083]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The ability to select and setup a game that is not natively supported by Mod Organizer.

**Describe alternatives you've considered**
A janky work around that would utilize the folder pointer options in a dummy instance of another game. However I have not tried, and it seems like it would be more effort than I'd like to put in at this point.

**Additional context**
For me in particular, I want this for Rimworld, which has most of its mods on Steam Workshop which auto updates (frequently, and causes problems), but also has some Nexus presence, albeit not as much. In general though, it would potentially be useful, and would make it less necessary to add native support for games if the users could just "create custom instance" and have settings for where the mod files need to be in order for the game to function properly. For Rimworld specifically this would be pretty easy, but again I'd much rather have a simple option that could work for multiple games.

**Comment by Holt59** [comment]
You can create a plugin for a custom game in a few minutes within very little knowledge by adding a plugin to [`basic_games`](https://github.com/modorganizer2/modorganizer-basic_games). Check for instance some of these that are very basic:

- https://github.com/ModOrganizer2/modorganizer-basic_games/blob/master/games/game_assettocorsa.py
- https://github.com/ModOrganizer2/modorganizer-basic_games/blob/master/games/game_f123.py

All you need to do is create a `game_rimworld.py` file in the `plugins/basic_games/games/`, and then fill the file with something similar to the above: change the `AssettoCorsaGame` to `RimworldGame` and replace the values below.

**Comment by Silarn** [comment]
There are a number of reasons why this is a bad idea, particularly that many games require very specific modding setups and potentially workarounds to actually mod, particularly with MO2's VFS.

As Holt said, the better option is creating a simple basic games plugin file.
