### ISSUE TITLE
AttributeError is stopping me from installing mods

### ISSUE THREAD

**Issue by Aysthill** [ModOrganizer2/modorganizer#2091]
My Mod organizer had an update available so I started it. Still, after it was finished I started to get an error saying the Palworld game object didn't have an attribute which was weird since I don't use MO2 for Palworld anymore. I ignored it since I'm installing Skyrim SE mods but for some reason, I can install mods regardless of type and the error messing just pops up whenever I try. Do I need to reinstall MO2 or change a setting or something?

![Screenshot (1665)](https://github.com/user-attachments/assets/dde3b7ef-abc6-4402-8e92-568e02f9602f)

**Comment by Holt59** [comment]
This is from a third-party plugin (PalwordInstaller according to the screenshot), so you should ask the plugin author to update it and disable it until it gets updated.
