### ISSUE TITLE
update icon is greyed out on top right corner

### ISSUE THREAD

**Issue by ovojake** [ModOrganizer2/modorganizer#2093]
## The problem:
MO2 doesn't seem to recognize there's an update. Tried restarting, both update boxes are ticked in settings. Hovering over it says its up to date even though I'm on 2.5.1rc2

## Environment:

* Mod Organizer Version that exhibits the issue: v2.5.1rc2-ML1.4.1
* Last Mod Organizer Version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 11

**Comment by Liderate** [comment]
You have the Modding Linked fork which does not check the regular MO2 GitHub page for updates. It checks the forked page instead.

**Comment by ovojake** [comment]
how do I update it then?

**Comment by Holt59** [comment]
> how do I update it then?

If you want the Modding Link 2.5.2 version, you'll have to wait for them to update the fork. If you want to go back to the standard version, you can download the installer from Nexus or Github (https://github.com/ModOrganizer2/modorganizer/releases/tag/v2.5.2) and then point it to  your ML installation (updating from ML to standard with the installer should be fine).
