### ISSUE TITLE
[Feature Request] One Click Install Scripts 

### ISSUE THREAD

**Issue by RinMaru** [ModOrganizer2/modorganizer#2096]
After Following various guides on how to set up Tale of Two Wastelands I noticed they get updated and sometimes it requires allot of redownloading and hunting down the various mods you must remove or install.  I was thinking if it would be possible to make a (script or blueprint) that MO2 can read and this file would give a list of mods to download and how they should be set up including load order and Catagories. And if a update to one comes it can be run against the old one to see what needs to be removed and setup.

I think this would streamline allot of the work that guides like Wasteland Servival Guide (that require upto 200 mods)

Perhaps It could work like making a backup of load order and your mod list but you can make a script of your current mod setup and allow others to use it and MO2 will automatically download and set up the mods from that file.

**Comment by StrawChannel95** [comment]
Simply put, this is redundant because of Wabbajack.

**Comment by twizz0r** [comment]
It's an automated mod list installer that uses MO2 as it's mod manager.

https://www.wabbajack.org/
