### ISSUE TITLE
Issues with Fallout 4 London Mods

### ISSUE THREAD

**Issue by alex-nikols** [ModOrganizer2/modorganizer#2099]
## The problem:
Both source game and custom URL do not work with Fallout London mods.
The source game is not able to be changed from fallout 4.
And the custom URL pointing towards the fallout 4 London mods set does not work.
Query info points to the fallout 4 Nexus page instead of the fallout 4 London Nexus page. And since they use separate mod IDs they get confused for one another.

## To Reproduce:
1.	Download and install fallout 4 London.
2.	Then go to the fallout 4 London Nexus page.
3.	Manually download any mod from this page, into the mod organizer downloads folder.
4.	Install the mod.
5.	Right click on the installed mod pulling up the drop down menu 
6.	then select information from the dropdown menu
7.	Then navigate to the Nexus info page
8.	there you will see that the source game option is grayed out and is unable to be changed.
9.	Continuing down if you look at the use custom URL box at the bottom of the window and activate it using the check mark in the bottom left hand corner
10.	then giving it the correct fallout London Mod page in the box to the right of the checkbox.
11.	Then hitting refresh on the page it still states “This mod does not have a valid Nexus ID. You can add a custom web page for it in the "Custom URL" box below.”  Even after adding a custom URL.
## Environment:

* Mod Organizer Version that exhibits the issue: v2.522
* Last Mod Organizer Version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Mod Organizer: Win 10

## Details:
The problem is that mod organizer does not recognize the separate page for fallout 4 London as an extension of fallout 4. Because Nexus decided for some reason to separate them into two separate pages and since fallout 4 London is just a mod for fallout 4 the base game is still fallout 4. But for whatever reason I cannot point mod organizer to the correct pages. This error even breaks query info making it grab the data for fallout 4 mods that share the same mod ID. And since this is not able to be corrected it does not allow me to use the built in features to check for updated mods.

![Screenshot 2024-08-13 145702](https://github.com/user-attachments/assets/81dbdf92-6bf2-4c08-b792-067856967677)

 

### USVFS:
https://gist.github.com/alex-nikols/cf4bac2bab6b3545ac085582c04ed73d
### MO Interface:
https://gist.github.com/alex-nikols/7dd20c575ae180e3ac82d7660534f207

**Comment by twizz0r** [comment]
https://discord.com/channels/265929299490635777/265929299490635777/1268764939879972904

Try that.

**Comment by alex-nikols** [comment]
thank you that worked.

**Comment by InsanePanda** [comment]
> thank you that worked.

I cannot see this discord post even after joining Nexus's server so I have no idea what you did to solve it. Could you please explain?

**Comment by alex-nikols** [comment]
[FO 4 London fix.zip](https://github.com/user-attachments/files/16608797/FO.4.London.fix.zip)

this contains the dll plugin from the discord post along with install instruction and instructions for installing it on an existing MO2 instance.
