### ISSUE TITLE
fatal error on anomaly gamma : up_gr_firstab_ace52

### ISSUE THREAD

**Issue by cj55-dad** [ModOrganizer2/modorganizer#2100]
## The problem:
Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our [Discord server](https://discord.gg/ewUVAqyrQX).

## Environment:

* Mod Organizer Version that exhibits the issue: 2.5.2
* Last Mod Organizer Version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: windows 11 23H2 build 22631.4037
<img width="348" alt="FATAL ERROR" src="https://github.com/user-attachments/assets/addd54c1-fa07-4700-b0ef-8bce27995f40">
[mo_interface.log](https://github.com/user-attachments/files/16616140/mo_interface.log)

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.
Hello, i don't know how to describe the problem, just fatal error like the image... i re-install 2 times for the same résult, maybe an windows update ! sorry for my bad english i'm just french. thank you.

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your latest USVFS log, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by qudix** [comment]
You need to fill out the issue report. That error is from the game suggesting it's a mod issue.

**Comment by cj55-dad** [comment]
[xray_moit.log](https://github.com/user-attachments/files/16623180/xray_moit.log)
Thank you for answers, there is the xray.log. so it's mean that it's Gamma'update the problem... Cause, before alls were good. Have a good day.

**Comment by cj55-dad** [comment]
So, i downloaded another time Gamma's update. Finaly i did'nt touch any option to see for a new game, and it's done... So i recall my save ans it's done too, just had to change some option, and of course french language. For the moment no problem, thank for yours suggestions.
