### ISSUE TITLE
 Starfield 1.13.61 added SFBGS004.esm. ESM set to unmanaged and not being force-enabled

### ISSUE THREAD

**Issue by xon-xoff** [ModOrganizer2/modorganizer#2107]
Starfield 1.13.61 added SFBGS004.esm. ESM set to unmanaged and not being force-enabled

![image](https://github.com/user-attachments/assets/84822f23-7350-4b76-bb03-57dde3fb5dd9)

**Comment by gir489returns** [comment]
For some reason for me, when I check the box enabled, and start Starfield, after Starfield closes, the box is unchecked again.

**Comment by xon-xoff** [comment]
> For some reason for me, when I check the box enabled, and start Starfield, after Starfield closes, the box is unchecked again.

Because MO2 doesn't see it as a base esm it is not forcing it like the rest of the base game esms. That's what the ticket is for :)

**Comment by Silarn** [comment]
Discord has an update in #dev-builds

**Comment by xon-xoff** [comment]
Thanks for the update - the updated DLL is good.

**Comment by junip0r** [comment]
Can the updated DLL be posted on Github (rather than discord)? Thanks!

**Comment by randrade86** [comment]
Discord link for DLL Download https://discord.com/channels/265929299490635777/379225566122999808/1276040546472824934

**Comment by KingDoum** [comment]
> Discord link for DLL Download https://discord.com/channels/265929299490635777/379225566122999808/1276040546472824934

hi,randrade86  i can't into  discord when i click your website ,so please help me give some other download 
![image](https://github.com/user-attachments/assets/74fb2878-df77-484b-8bd6-748259e693dc)

**Comment by randrade86** [comment]
> > Discord link for DLL Download https://discord.com/channels/265929299490635777/379225566122999808/1276040546472824934
> 
> hi,randrade86 i can't into discord when i click your website ,so please help me give some other download ![image](https://private-user-images.githubusercontent.com/25241266/373921089-74fb2878-df77-484b-8bd6-748259e693dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDMwMzIsIm5iZiI6MTcyODMwMjczMiwicGF0aCI6Ii8yNTI0MTI2Ni8zNzM5MjEwODktNzRmYjI4NzgtZGY3Ny00ODRiLThiZDYtNzQ4MjU5ZTY5M2RjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEyMDUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNmYyYTE3YjhlMTY2OTU5MGM0MTNlY2MxYjI2MDIyMzExYWE5MTc0MjYxNzNhMDI2YTBhY2I5Mjg3MzNjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._x7mwidS2g4Y02_D1Vzqkky9dBNmRVJCeXWJAoWN_0E)

I believe that you need to join the Mod Organizer 2 Discord first... here is the link:
https://discord.gg/ewUVAqyrQX
