### ISSUE TITLE
Latest Windows 10 broken again? 

### ISSUE THREAD

**Issue by macronomicus** [Modorganizer2/modorganizer#211]
I reported in the windows feedback hub too.

After a recent windows update to 1709 (17074) Loot doesn't detect any plugins when launched from MO2 not even default esm's, all my mods on the right pane are now alphabetized with improper load order,  When I launch the game thru MO2, no plugins are detected, not even skyrim.esm update.esm, or the dlc. same as loot  D:  

* Mod Organizer 2.1.1
* Windows 10 Pro 1709 (os build 17074.1000) slow-ring
* Loot Version 0.12.1, tried the last four versions of loot with same result

Ive tried all sorts of things to resolve it with no luck yet, unfortunately windows wont let me downgrade to the most recent stable release so im stuck on 1709, unless I wipe the system and start from scratch.

Ive been using this playthrough with mo2 for over a year with no problems, at least until these recent updates to windows, over 350 hours gamed with the current setup.  I will keep investigating, and looking for any ways to fix it, anyone else having this issue or know where I should dig further?

## USVFS
https://gist.github.com/macronomicus/cfe99313245c2c9383517595727127b5
## MO Interface
https://gist.github.com/macronomicus/5fabd3d398aa4b8718fdb44d8ee3db85
## Loot
https://gist.github.com/macronomicus/ae686925598ea38371362842ad14fd40
CEFDebugLog.txt
[0121/202555.234:ERROR:main_delegate.cc(713)] Could not load cef_extensions.pak

**Comment by macronomicus** [comment]
I joined discord and tried the latest build, but then I noticed the notice lol
`Like all previous usvfs versions, this version does not work with the windows 10 insider preview builds`
dang... is there anything prior to usvfs versions that might work?  Seems so odd since mo2 worked great for over a year and now seems like its borked somehow, almost working but not quite.

**Comment by LePresidente** [comment]
Currently we just dont have the time to support every windows insider
preview, so we decided to only support offical main releases. If someone
has time they will look at this but its highly unlikely in the very near
future

**Comment by erasmux** [comment]
@macronomicus You are using a windows insider preview, thats what they do. They are not intended for day to day use but for microsoft to test things out and iron out the things they break before they release a proper version.
As far as I know no past usvfs version will work with these windows versions and it is a change to the way windows works and nothing to do with MO/usvfs (except that apparently usvfs relies on the regular way windows has done this for the last decade plus).

**Comment by erasmux** [comment]
I am not sure of the exact method behind the windows 10 version numbers but the 1709 is also the current the latest stable (not insider preview build). For example here is the current winver of my fully updated windows 10 VM:
![image](https://user-images.githubusercontent.com/334573/35212425-bc765126-ff62-11e7-9638-e73370be95ff.png)

And on such windows 10 installs MO2 should work fine, and if there are any major issues they should be a priority to fix. (In fact there have been reports that MO2 has problems with older windows 10 stable builds but I think at least some of those have been "accidentally" fixed, possibly only in the latest usvfs beta builds on the discord channels).

To be clear, I did take a very quick look at the issue with the insider preview builds (at least on the "fast ring" this has been broken for quite some time now), and it seems that something has changed in the behavior of the low level OS file access function which usvfs is hooking. This is not something that is easy to fix and will require considerable work.

**Comment by macronomicus** [comment]
Nope, same thing on a fresh "Clean Test setup" from the discord instructions.   I created a new profile, added two simple mods, and ran loot, which still shows zero plugins.

The game still plays fine launching outside of mo, maybe I should just do an old fashioned manual install of all the files lols...  240 mods 40gigs worth lol!

**Comment by macronomicus** [comment]
Ahh didnt see your second post, yes, im on 10 Pro 1709 (os build 17074.1000), but I have been on the insider preview a long time and mo2 was working for me, even the recent updated mo2 releases, however this win update a few days back broke things, on both fast and slow rings.

**Comment by erasmux** [comment]
Yes. That is what we are trying to tell you. MO2 does not work on the insider preview builds and most likely will not work until either microsoft rollbacks their changes (which is unlikely but you can never know) or they are released in a stable windows 10 release (I think that's scheduled for about 3 months from now). Even then it will take considerable work and time for MO to support these builds but at that point we will have no choice.

Until then you have only two choices:
- Use the regular 1709 builds which is what should be used for day to day usage and what most people do.
- Don't use MO2. If you choose to install you mods manually or use another mod manager is your choice.

**Comment by macronomicus** [comment]
Yeah, it wont allow a downgrade further to the older versions, at least not without a clean install.  I suppose I can just wait it out until the spring release, or do a manual install to continue my play through.  Either way I will miss Mo2!  D:  

Thanks for replying tho, Ill report back in case I find more info, and submit another feedback hub report to MS as well.

**Comment by macronomicus** [comment]
I was able to resume my playthrough.  I repackaged up my mods from mod organizer and installed them into NMM, its crude but its working.  It was such a relief to see loot do its thing, this is a much better way to wait white MS decides to break or not break the feature mo2 relies on lol.

**Comment by Al12rs** [comment]
Since the windows update will drop in less than a month and MO2 is still broken on the insider builds we will have to assume that MS will not fix this. The problem will need proper investigation to determine the exact cause of the issue. I don't know enough about c++, usvfs and debugging in general to take this on (although I will try non the less) so I hope somebody more versed in c++ can help out.

**Comment by Silarn** [comment]
The long and short of it is Microsoft created a new ntdll function that replaced one of the old ones for file searching. This meant we needed to create a new hook for that function in the virtualization library.

**Comment by macronomicus** [comment]
oooh im excited, I do miss MO!  Hopefully I can test that fix soon. :D

**Comment by SuperSandro2000** [comment]
Fix is life in #builds in discord

**Comment by macronomicus** [comment]
Ok going to test tonight, just have to migrate all my mods back from Nexus mod manager to MO, its like surgery, but it worked the other way so should in reverse too.  Im not abandoning my almost 700 hours playthrough lol.

**Comment by mikeroygray** [comment]
Hey guys! I’ve been away from Skyrim modding for a couple years - but I just finished DOS2 (took me. like, 6 months!), and I want to try my hand at modding SSE. I’m new to GitHub - surfed in because I was having trouble launching Skyrim from MO2 - and ALSO because I’m running a slow-ring preview build of Windows 10 - build 17074.1003. I downloaded AL12´s latest full build from discord (Dev build 0.2 27/02/2018), then swapped in the latest usvfs fix (Update J2: Silarn (07/03/18). As far as I can tell, MO2 is now launching SKSE64 successfully - and LOOT also works just fine. 
Only caveat: I have to start MO2 with admin rights, otherwise SKSE64 won’t load (Skyrim goes to the settings launcher). (Note: Steam is installed in c:\games\steam and MO2 is in c:\games?skyrim modding tool\mo2)
Note: For the future I’ve turned off preview builds - but I don’t have a restore point for a simple rollback, and I don’t want to reinstall Windows if I don’t have to.

**Comment by Silarn** [comment]
And you don't have to do that if you launch outside of mo? I mean it's possible there's a permissions issue somewhere but running as admin shouldn't be necessary.

**Comment by mikeroygray** [comment]
@Silarn: Oh. Damn. I thought I´d tested that, but something else must be messed up. I get the same result outside of MO2- i.e., if I run from explorer. So, while I DO have a problem, it’s NOT a MO2 problem. Sorry for wasting your time, and compliments on the nice work on MO2!

**Comment by Silarn** [comment]
This has been resolved and will be in the upcoming release.
