### ISSUE TITLE
MO2 Crashes on "Create New Instance"

### ISSUE THREAD

**Issue by MorbidEden** [ModOrganizer2/modorganizer#2117]
## The problem:
When attempting to create a new instance, MO2 crashes.

## To Reproduce:

1. Go to ModOrganizer.exe
2. Click on "Instance Manager" button.
3. Click on "Create New Instance" button.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.5.2
* Last Mod Organizer Version that did not exhibit the issue (if applicable): 2.5.0
* Desktop OS/version used to run Mod Organizer: Windows 11 Pro 23H2 Build 22631.4037

## Details:
After updating to version 2.5.2 via the in app updater, attempting to create a new instance crashes the program. I already have three instances (Cyberpunk, SkyrimSE and EnderalSE). Switching instances works as expected.

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
https://gist.github.com/MorbidEden/e2e448695a1674835e6e3203b0df8994#file-usvfs-2024-09-07_13-47-31-log

### MO Interface:
https://gist.github.com/MorbidEden/e2e448695a1674835e6e3203b0df8994#file-mo_interface-log

**Comment by MorbidEden** [comment]
A clean install as opposed to using the in app updater has it working again. I have the dmp file set aside if it is needed.

**Comment by tuokri** [comment]
I'm also having this issue on 2.5.2. I also used the automatic updater.

**Comment by Liderate** [comment]
This can happen if you started with a .7z release of MO2 that contains the Fallout 76 plugin and then used the in-app updater. The installer does not include the 76 plugin right now. You can delete the game_fallout76.dll or get it from the 2.5.2 archive release.

**Comment by MorbidEden** [comment]
Thank you, Liderate.
