### ISSUE TITLE
MO2 won't launch

### ISSUE THREAD

**Issue by PoorOldManNein** [ModOrganizer2/modorganizer#2125]
Tried many fixes like redownloading, installing on different drives, made exceptions to antivirus, deleted webcache etc... and still inst launching. I get these errors in the MO2 file. 
![Screenshot (32)](https://github.com/user-attachments/assets/8080bd37-9923-4685-8bdd-6193afae9a31)

**Comment by PoorOldManNein** [comment]
no help :D

**Comment by Aurorautius** [comment]
same here... :(

**Comment by Holt59** [comment]
You probably need to install latest VC Redist (https://aka.ms/vs/17/release/vc_redist.x64.exe).

**Comment by PoorOldManNein** [comment]
> You probably need to install latest VC Redist (https://aka.ms/vs/17/release/vc_redist.x64.exe).

Okay, thank you.
