### ISSUE TITLE
help with the problem

### ISSUE THREAD

**Issue by with4rok** [ModOrganizer2/modorganizer#2145]
![photo_2024-10-15_12-55-27](https://github.com/user-attachments/assets/8b50c686-a9e0-4f7c-9c0c-1ce113872f59)
I had this problem in the game Stalker Anomaly. How should I solve it and what is it? 
I also installed the Stalker Gamma

**Comment by Holt59** [comment]
Github issues are meant for features / bugs within MO2, this looks like a modding issue, so you should ask this on Discord https://discord.gg/ewUVAqyrQX.
