### ISSUE TITLE
Add support for game Fallout 4

### ISSUE THREAD

**Issue by Beerme72** [ModOrganizer2/modorganizer#2147]
**This template is useful to add basic support using https://github.com/ModOrganizer2/modorganizer-basic_games.** 

**If you are vaguely familiar with programming you can try following the instructions on that link to get something working yourself. If you have trouble with that please fill in this template.**

**Please provide the following information for the game (remove the optional lines you do not use):**

- Fallout 44
- https://www.nexusmods.com/fallout4
- https://www.nexusmods.com/fallout4

I just went through the process of downloading the mods as suggested by your website and upon enabling them, the game will not boot.  
I have a warning sign and it states this:

<The masters for some plugins (esp/esl/esm) are not enabled.
The game will crash unless you install and enable the following plugins: 

Master
Required By
cctosfo4002_neonflats.esm
ppf-neonflats-cr.esm
fakeInt.esp
fakeInt_DLC.esp
fakeInt_Boston.esp
fakeInt_DLC.esp

this is in two columns, and I have searched all over to try to find them....There's no search to help...and I'm stuck.  

please help me fix this.....

**Provide additional details regarding the game that could be required for the plugin.**

**Comment by Holt59** [comment]
Fallout 4 has been supported by MO2 for a long time. If you have issue modding the game, you should ask on Discord: https://discord.gg/ewUVAqyrQX
