### ISSUE TITLE
Games crash upon startup when launching with Windows 11 24H2

### ISSUE THREAD

**Issue by SUPERJERRY1234** [ModOrganizer2/modorganizer#2151]
## The problem:
Fallout 4 and Skyrim crash upon launching after installing Windows 11 24H2

Before updating to Windows 11 24H2 I was able to launch games through Mod Organizer 2 and the respectable mods I had installed

I've only got 3 simple mods installed and they are the exact same mods for both games

As soon as a launch the game it will go black screen as if the game is about to launch then I hear a second of audio from the intro and then crashes to desktop with no error message nor a error message in Windows Event Viewer

## To Reproduce:
1. Add a instance of either Fallout 4 or Skyrim to the managar
2. Add any mod (for me I had added Ultra-wide fix, Achievements Mods Enabler and Unoffical patch)
3. Launch the game and it should crash after a second or two of launching

## Environment:
* Mod Organizer Version that exhibits the issue: 2.5.2
* Last Mod Organizer Version that did not exhibit the issue (if applicable): 2.5.2
* Desktop OS/version used to run Mod Organizer: Windows 11 24H2 Build-26100.2033

## Link to Mod Organizer logs:
[usvfs-2024-10-19_04-23-58.log] (https://github.com/user-attachments/files/17442671/usvfs-2024-10-19_04-23-58.log)

### USVFS:
Don't know how to create 

### MO Interface:
Don't know how to create

**Comment by Slowiansky** [comment]
I have the same issue. Don't even have any mods or script extenders installed, clean game install and MO2 just refuses to launch it. Game works if launched through steam. Skyrim AE in my case.

**Comment by Gor-Rex** [comment]
Had the same issue and still can not open game

**Comment by Slowiansky** [comment]
I've managed to fix it. Bitdefender Antivirus turned out to be the problem. I had to add exception for game .exe in advanced threat protection. You need to do it for every .exe you're trying to launch.

**Comment by Gor-Rex** [comment]
Thanks greatly appreciated. 


Sent from Yahoo Mail for iPhone


On Friday, October 25, 2024, 11:10 AM, Slowiansky ***@***.***> wrote:




I've managed to fix it. Bitdefender Antivirus turned out to be the problem. I had to add exception for game .exe in advanced threat protection. You need to do it for every .exe you're trying to launch.

**Comment by SUPERJERRY1234** [comment]
That didn't work for me sadly. I didn't need to do that on 23H2 Windows 11 update but I tried it anyways and no matter what, that didn't do anything to make it work.

Clearly theres new codes and stuff that have been added to Windows becase I've got another program NVCleanstall that I can use normally to update my Graphics Card driver and now it's given me a error each time. I've resarched and other people are now having that issue.

Windows fumbled hard with this update, they should take more time between updates to make updates perfect otherwise devs have to go and fix there program just to be able to run again properly

**Comment by Slowiansky** [comment]
I'm sorry to hear that mate.
I didn't need to do it either on 23h2 and I was suprised when it turned out to be the problem.
Are you using Bitdefender aswell?
What exactly did you make an exception for in antivirus?

**Comment by SUPERJERRY1234** [comment]
Yeah I'm using Bitdefender. 
I went into Antivirus and then settings and manage exceptions and then clicked on add an exception and then added both games and mod organiser and made sure all boxes are turned on and yet nothing. 
I also added them into the firewall and still nothing.

**Comment by Slowiansky** [comment]
Glad to hear it!
