### ISSUE TITLE
Cannot add new separators once mod list gets long

### ISSUE THREAD

**Issue by sightergoliant** [ModOrganizer2/modorganizer#2152]
## The problem:
The usual way to add a separator is to left-click white space below the mods, and select "create separator". However, once you have too many mods, there is no white space left to right-click into, and every row of the left panel will provide context-specific behavior, none of which is context-specific to the white space where "create separator" is one of the options.

## To Reproduce:

1. Open Mod Organizer
2. The number of mods needed to fill up the white space is going to vary -- and it is possible regain the white space up to a point, for example by resizing the window -- but eventually you will always run out, and the scrollbar will only scroll down as far as your lowest category, leaving no space to add a separator.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.5.2
* Last Mod Organizer Version that did not exhibit the issue (if applicable): Not sure
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

![image](https://github.com/user-attachments/assets/c4cd2351-c7a0-469b-a370-faeb9e854a0f)
The scroll button does not produce anything lower than this "overwrite" area and there is no white space available for new separatros.

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your latest USVFS log, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by Holt59** [comment]
If you click on any mod or even Overwrite, there is a "All mods" menu that will give you exactly the same options as if you had clicked on the empty space. Plus, all the options are available using the first button in the toolbar above the mod list.
