### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by circuitsystem** [ModOrganizer2/modorganizer#2157]
**Is your feature request related to a problem? Please describe.**
It's a pain to use M02 on Linux because there is no official version by the current devs. There is [this port](https://github.com/rockerbacon/modorganizer2-linux-installer) however it doesnt want to detect game files that are in seperate drives, and editing the permissions seems impossible. Overall I and many others cant get it to install.

There is also the version on [Steam Tinker Launch](https://github.com/sonic2kk/steamtinkerlaunch) however that version refuses to load newly imported python plugin (A great example is [this plugin ](https://www.nexusmods.com/morrowind/mods/45642?tab=description)works fine on windows M02 but not on M02 on Steam Tinker Launch). Another problem with the steam tinker launch version of M02 is that the quality of the wine emulation is....weird. The quality of the lines and font on MO2 on steam tinker launch is very low quality. I'm including a picture below

![zzz tinker](https://github.com/user-attachments/assets/45c6d7b3-b58c-4178-861e-aac1af54d85b)

**Describe the solution you'd like**
A functional port of Mod Organizer 2 to Linux from the developers themselves, no matter how long it takes

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Holt59** [comment]
This is out-of-scope for the current MO2 project. A proper Linux port would require so much changes to the current codebase that writing a mod-manager from scratch would probably be faster. 

People are free to fork MO2 and try their best at porting it to Linux if they want a Linux port (although it's probably a bad idea).

**Comment by foresto** [comment]
For anyone else with fonts rendered incorrectly as pictured above, running `winetricks fontsmooth=rgb` on your Wine prefix may help.

Before:

<img width="493" height="444" alt="Image" src="https://github.com/user-attachments/assets/2e3459cc-3619-4e32-b982-d83f903f7c95" />

After:

<img width="493" height="444" alt="Image" src="https://github.com/user-attachments/assets/370d8a08-d4d1-4422-9ac9-6d4c3e9785e0" />
