### ISSUE TITLE
NXM handler is not changing to the correct game

### ISSUE THREAD

**Issue by GrantSP** [Modorganizer2/modorganizer#216]
# The problem

If you use MO2 as instanced for several games the last active instance is called for ALL downloads and will fail with this message if it is different:
![wrong-game](https://user-images.githubusercontent.com/3291695/35466278-60fd53a6-0356-11e8-883b-5b4fbd09f9b7.png)

# Environment

* Mod Organizer Version that exhibits the issue: **2.1.1**
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): **unsure if any MO2 instance worked**
* Desktop OS/version used to run Mod Organizer: **Windows 10 16299.125** 

# Details

Assume you have MO2 setup as instanced for Skyrim and Fallout4. The last time MO2 was open you had it manage Fallout4, It is now closed and you are browsing the Nexus on the Skyrim site and you see a mod that you want. Clicking the "Download with manager" button starts the process of downloading but the instance is not for Skyrim and the error message will appear.
You now have to change the instance to the correct game and restart the download.

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by GrantSP** [comment]
Additional information that may, or may not, be applicable.
My MO2 install is in:`D:\Games\MO2\`
I also have several MO1 installs in folders such as this: `D:\Games\ModOrganizer\FNV\` where the last folder is changed to reflect the actual game that is managed.
None of the settings in any of these MO1 installs points to any folder used by my MO2 install yet whenever I start a MO1 there is a newly created file in my MO2 install folder called: `nxmhandlers.ini`, note the pluralisation, and this file is specific to the MO1 that is active.
ie. If I start MO1 for FalloutNV the ini will be pointing to the nxmhandler setup for FalloutNV as it would be in MO1.

**Comment by Silarn** [comment]
NXMHandler looks at what the active NXM handler is in the OS and will typically search for the configuration file at that location (if you aren't using an instanced setup).

You need to launch the active handler exe and make sure each game is assigned to its own separate MO exe if you are using portable installs. It sounds like you have the Fallout 4 instance assigned to handle all of the games.

**Comment by GrantSP** [comment]
As stated I have MO2 installed only once and I am testing it, in instanced mode, as the only manager for all the supported games. This means there are only one set of executables. It is impossible to point a separate nxmhandler.exe for each game as there is only one.
