### ISSUE TITLE
MO2 causes file enumeration to be reversed (Reminder)

### ISSUE THREAD

**Issue by EsOmEs** [ModOrganizer2/modorganizer#217]
# The problem

MO2 seems to reverse order of file enumeration from a->z to z->a. This becomes obvious when looking at the dropdown list for outfits/bodies in BodySlide or by looking at the plugin load order for skse in %Documents%\MyGames\Skyrim Special Edition\SKSE\skse64.log

# Environment

* Mod Organizer Version that exhibits the issue: all MO2 so far but tested with 2.1.1 (usvfs version 0.3.1b5)
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): none
* Desktop OS/version used to run Mod Organizer: Win 10 x64 build 1709

# Details
See the problem. for certain SKSE64 DLLs this seems to be a problem as they dont load after certain others. Even though this might not be an issue directly caused by MO2, it might cause lots of other problems.

# Link to Mod Organizer logs
Not applicable.

## USVFS
Not applicable

## MO Interface
Not applicable

**Comment by AnyOldName3** [comment]
Just in case this gets forgotten, a few people, myself included, have failed to replicate this when trying.

**Comment by Silarn** [comment]
Is there any recent case of this happening with the latest test build?

**Comment by Silarn** [comment]
There's is a possible cause for this in that the search hooks return results after the original results and without directories sorted to the top. This could cause issues with programs that return the results as is without any sorting.

However the fix will be complex and we don't know about any serious issues caused by this.

**Comment by Al12rs** [comment]
Apparently this combined with a SKSE issue and enough plugins can cause #377 
Here is what LostDragonist found: https://discordapp.com/channels/265929299490635777/529544161750286359/538898232177328147

**Comment by Al12rs** [comment]
This commit https://github.com/ModOrganizer2/usvfs/commit/5f2493ab3c8526bcd32333537bf48aa079e6eaf1 should make sure to return the correct order but will most likely degrade performance. Since ntquery is pretty important and plenty used we should look for more performant alternatives with vectors
