### ISSUE TITLE
MO does not virtualize files for subsequent programs after having started a tool as admin

### ISSUE THREAD

**Issue by Xarec** [ModOrganizer2/modorganizer#218]
# The problem

If you run something through Mod Organizer that is set to always run as administrator, it causes other software that isn't running as administrator to be locked off from the VFS.

# Environment

* Mod Organizer Version that exhibits the issue: v2.1
* Desktop OS/version used to run Mod Organizer: Windows 10 Home

# Details

If you attempt launch something through MO which has this box checked;

![image](https://user-images.githubusercontent.com/13697777/35509150-5bcc0046-04f3-11e8-84a2-7e28a88af3d2.png)

you will be met with this screen asking you to allow Mod Organizer to be run as administrator.

![image](https://user-images.githubusercontent.com/13697777/35509242-be094160-04f3-11e8-9714-3289268ef864.png)

The issue arises once you've elevated Mod Organizer and then attempt to launch something without running it as administrator. To demonstrate, I'll make it so LOOT is always run as administrator and I'll select yes when asked to elevate MO.

![image](https://user-images.githubusercontent.com/13697777/35509389-45d86954-04f4-11e8-9b63-f877d148bcb8.png)

As you can see, LOOT launches and displays all the plugins just fine. But after closing LOOT, I then try to launch xEdit (SSEEdit) without running it as administrator, which causes this to happen:

![image](https://user-images.githubusercontent.com/13697777/35509523-b300f1fe-04f4-11e8-92af-dfc04472c242.png)

Nothing. None of my mods display. And this persists until I either:

1. Restart Mod Organizer and don't run anything as administrator.
2. I set every app to run as administrator by default.

If I run SSEEdit as administrator after elevating LOOT, the plugins show just fine. But I'd rather not do that, so restarting is usually my go-to.

So what this looks like to me is that when elevated, Mod Organizer locks off the VFS from anything that isn't also run as administrator. I don't know exactly why this is the case, and that's why I came here to see if anyone here might have any ideas.

# Link to Mod Organizer logs

## USVFS
[USVFS Log](https://gist.github.com/Xarec/98051ab399d4292439f4c6f765b6cb2e)
## MO Interface
[MO Interface Log](https://gist.github.com/Xarec/fe2fb711504b22ec2a14dda4d230114e)

**Comment by Al12rs** [comment]
With further testing we found out that everything works correctly if MO is started as admin from the start. If MO is not started as admin and needs to launch something that needs admin rights it will launch that program but it will not lock itself. Every program launched without admin rights afterwards will not see the mods.

**Comment by GrantSP** [comment]
Slightly off-topic but what tools absolutely NEED to be run as admin?
I am always wary of anything that says you must run as admin because I can't understand why they would need to access parts of my file-system that are locked off normally.

**Comment by LordOfLA** [comment]
Nothing to do with modding Bethesda games needs to be run as admin unless a person installed the games to program files. If that is the case the correct step is to move the game(s) outside of program files.

**Comment by Silarn** [comment]
Is the Program Files bit even 100% true? You don't usually need to run anything with Admin privileges even inside Program Files.

**Comment by LordOfLA** [comment]
Yes, the program files bit is true - it is a special folder protected by UAC. You should ideally never install games or their associated tools there. Will save a lot of hassle.

**Comment by TechAngel85** [comment]
> Slightly off-topic but what tools absolutely NEED to be run as admin?
> I am always wary of anything that says you must run as admin because I can't understand why they would need to access parts of my file-system that are locked off normally.

The only one that needs this that I run is Mod Analyzer. It will prompt to elevate privileges every time you run it.

**Comment by Al12rs** [comment]
This should be fixed or more accurately avoided by the new check that forces Mo2 to restart if admin is required.
