### ISSUE TITLE
Executables won't load mods if MO2 is installed inside the game folder.

### ISSUE THREAD

**Issue by LordNino215** [ModOrganizer2/modorganizer#224]
Having what seems to be a common issue. None of the executables in the drop-down window are loading esp's from the "mods" folder in the MO folder. FO4Edit, Wrye, Loot, MergePlugins are only loading from the Fallout4 Data folder <- I know this because I dropped a couple esp's into it just to check. I also tried to input some of the file pathing commands from the wiki into the "Arguments" box with seemingly no effect. Tried a complete re installation except for the "Downloads, Mods, and Profiles" folders; issue stayed the same. I can kinda live without Loot, MergePlugins, and Wrye, the worst part of that is some extra work. But XEdit is a necessity. Any helpful directions would be greatly appreciated, and would probably help a few folks with similar issues. Thanks for your time and great work.

* Mod Organizer Version 2.1.1
* Windows 8.1

Also just tried with the MO for SSE from that page, same setup, same issue.

**Comment by GrantSP** [comment]
You'll have to give us more to work on than just a description of what is happening. 
Logs, INI settings that sort of thing.

**Comment by LordNino215** [comment]
Sorry, never did this before. Always followed STEP w/o issues.

The "usvfs-*.log" files are all blank. IDK why.
Here is my "mo_interface.log"
[mo_interface.log](https://github.com/LePresidente/modorganizer/files/1714063/mo_interface.log)
Here is my "SSEEdit_log.txt:
[SSEEdit_log.txt](https://github.com/LePresidente/modorganizer/files/1714067/SSEEdit_log.txt)
Here is my MregePlugin log:
[log_021118_003629.txt](https://github.com/LePresidente/modorganizer/files/1714068/log_021118_003629.txt)
And i couldn't find one in Mopy.

.ini are as auto detected for Ultra, then modified by BethINI, "Presets" and "Recommended Tweaks" without any manual changes


"

**Comment by GrantSP** [comment]
The template for setting out these reports shows you what to provide and how to do it.

First issue is you have MO2 installed as a sub-folder off the game installation. We have increasingly found more reports of issues when this is the case, please move it somewhere else.

The INI I was asking about is the one used by MO found in the root MO install folder, those other tools have no bearing on this matter. that INI will show us how you have these tools installed.

**Comment by Al12rs** [comment]
Having a blank usvfs log could be caused by cleaning windows event logs (with CCleaner for example) and that breaks the virtualization for some reason. Restarting your computer should solve that problem (just don't clean the windows log again after restarting). If you have MO installed in the game folder move that out. Please read the pinned post on nexus for a list of these and other issues and workarounds: https://www.nexusmods.com/skyrimspecialedition/mods/6194?tab=posts

**Comment by LordNino215** [comment]
Sorry, Guys. I'm used to using idiot proof stuff.

MO .ini

[ModOrganizer.ini_.txt](https://github.com/LePresidente/modorganizer/files/1715310/ModOrganizer.ini_.txt)

And for reference, a screen shot of my game folder. I highlighted what I thought was pertinent.
![game folder](https://user-images.githubusercontent.com/17265034/36083437-2d997e0a-0f80-11e8-9049-9e5487f2f6ad.PNG)

**Comment by GrantSP** [comment]
Move all those tools, including MO2, out of the game install folder.
Set up something like:
`D:\Games\Tools\<each tool you use>`
MO2 will not function correctly with the current install you have.

**Comment by LordNino215** [comment]
I did. It worked. Thank you much. Sorry if I was any trouble. You guys are wizards.

**Comment by Al12rs** [comment]
@LordNino215 Would you be willing to come to the discord server (https://discord.gg/ucVRQPV) and help us try to fix the bug that causes the executables to not see the mods if MO is installed i the game folder? Me and the other devs don't have that problem so having somebody that can test and report would help us a lot.

**Comment by Silarn** [comment]
Is this repeatable with the latest usvfs? I believe it only happens if you have the game inside program files.

**Comment by Al12rs** [comment]
@HarewardH93 have you tried the latest Mo2 Dev builds avaliable on the Mo2 Development Discord server (link is everywhere on the nexus Mo2 page and pinned posts)?

**Comment by Al12rs** [comment]
merging into #169 for organization.
