### ISSUE TITLE
Downloading same file again from nexus hangs the new download at 0%

### ISSUE THREAD

**Issue by Al12rs** [Modorganizer2/modorganizer#230]
# The problem
When downloading from nexus a file that is already present in the download folder MO2 will show a messagebox asking if the user want to download it again with a different name (add 1_, 2_,... at the beginning of the name) or cancel the download.
If the user selects yes quickly enough the second download will start correctly, if the messagebox is left unanswered for 6-10 seconds before selecting Yes, the new download will start and get stuck at 0%.

![Messagebox in question](https://user-images.githubusercontent.com/26797547/36326927-10cf78d4-135d-11e8-83be-05bdd47d9c12.png)

![Download stuck](https://user-images.githubusercontent.com/26797547/36326978-45aca9e6-135d-11e8-892a-406e51014665.png)

If trying to cancel the download will do nothing and it will simple remove the context menu uptions for that download. Restarting MO (closing MO takes more time) will show a paused download that will behave correctly if started.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.1 Nexus release. Test builds on discord were tested too and they all exhibit the same behavior. 
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): Not applicabile.
* Desktop OS/version used to run Mod Organizer: Win 10 1709 build 16299.248

**Comment by Silarn** [comment]
We really shouldn't allow duplicate simultaneous downloads so I've removed that possibility

**Comment by Silarn** [comment]
I guess this was a different issue. It's probably some sort of timeout but I'm not sure.

**Comment by IceLancerSR** [comment]
It deleted original file and makes new one with size 0. But then it stops there.
