### ISSUE TITLE
[Feature Request] Add Support for oMod installers

### ISSUE THREAD

**Issue by SuperSandro2000** [ModOrganizer2/modorganizer#246]
# The problem

oMod are a popular mod format for Oblivion and adding support for it would enhance MO2 for these players significantly. Now they need to install those mods using OBMM and then move them to MO.

**Comment by SuperSandro2000** [comment]
oMod would be implemented trough NCC and until this https://github.com/LePresidente/modorganizer/issues/243 is not fixed I don't think it is worth while implementing something new. If we write a new plugin from scratch consider oMod support.

**Comment by Silarn** [comment]
Were oMods ever supported by MO? If the support was there in MO1 it should be there in MO2 unless something broke. Oblivion is the one game I haven't really tested as I'm not even sure how to obtain my old digital copy anymore.

**Comment by SuperSandro2000** [comment]
I don't think so...

**Comment by Silarn** [comment]
We considered the idea of hooking into the NMM monitor functions but apparently these are not really that well implemented. So this probably requires custom code. It'll take some time.

**Comment by Al12rs** [comment]
Refer to #848 for this.
