### ISSUE TITLE
[Feature Request] Plugin for TTW as it's own game.

### ISSUE THREAD

**Issue by RoyBatty64** [Modorganizer2/modorganizer#249]
The title says it all.

**Comment by SuperSandro2000** [comment]
I already thought about that and wanted to do it but what differentiates TTW from normal FNV?
We need a way to detect it... 
You want to lock the standard bsa's and make them essential right?

**Comment by Al12rs** [comment]
We should check how the a game is identified in the code, to see if we can differentiate it from FNV.

**Comment by SuperSandro2000** [comment]
I think for FNV this part of code handles that https://github.com/LePresidente/modorganizer-game_gamebryo/blob/master/src/gamegamebryo.cpp#L79

**Comment by GrantSP** [comment]
Honestly I don't see the need to do this. What exactly is gained? Creating an instance and calling it whatever you like, TTW e.g., and then pointing it to FNV does all the game needs to do.
As far as I can tell all that would change is the game name in the titlebar.

**Comment by SuperSandro2000** [comment]
@GrantSP hiding the F3 esm and fix their load order to prevent user error

**Comment by GrantSP** [comment]
Hiding the Fallout3 ESM? What for?

**Comment by SuperSandro2000** [comment]
So that no one can deactivate them in TTW and mess with their load order.

**Comment by GrantSP** [comment]
Okay, I can see that as an option. Also following the discussion in Discord there are probably a few other good reasons for a TTW game mode.

**Comment by monyarm** [comment]
Also adding it as it's own game and having it handle both FO3 and FNV Download with Manager, would be useful cause for a modded TTW you often use FO3 mods (usually you install the mod, disable the esp/esm, then enable a custom one, or make your own converted one)

**Comment by SuperSandro2000** [comment]
It will be in the next release as we currently fix some problems with the plugins API.
About handling mo3 games. I wanted to introduce that too but @Al12 and @Silarn @RoyBatty64 thought it was a bad idea

**Comment by SuperSandro2000** [comment]
@monyarm currently not possible with nxmhandler

**Comment by Silarn** [comment]
Closing as we do have preliminary support in the upcoming release.
