### ISSUE TITLE
[Feature Request] Add Path Settings During Instance Setup

### ISSUE THREAD

**Issue by twizz0r** [ModOrganizer2/modorganizer#254]
# The problem

To give MO users more control over their installs, add a path setting dialogue when creating a new instance.

# Environment

* Mod Organizer Version that exhibits the issue: All
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): All
* Desktop OS/version used to run Mod Organizer: N/A 

# Details

The way instances work is MO looks in Appdata and looks for the folder containing a modorganizer.ini file. That file contains all the paths of that instance and a bunch of other info such as executable. MO wouldn't know where to find the instance folder otherwise. This is not something configurable. It would be possible but it would just require to redo all the instance system and how MO stores settings. 

Adding the path settings during instance setup would be something easier since it just requires developers to add code, not change the current one, 

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by GrantSP** [comment]
Adding to this suggestion is the ability to cleanly cancel out of this process and not have MO present you with the process again from where you left off.
ie. You attempt to create a new instance and then decide against it and you press 'Cancel' and close MO. Upon opening MO again you are still in the process of selecting the game for the now cancelled instance.

**Comment by isanae** [comment]
The new instance creation dialog in 2.4 has a page to change the default paths.
