### ISSUE TITLE
Renaming a mod to an existing mod name fails but will actually overwrite the second mod files.

### ISSUE THREAD

**Issue by RoyBatty64** [Modorganizer2/modorganizer#256]
Edit by AL12: Renaming to an existing mod should not be allowed, we need to add a check to stop this from happening.

**Comment by GrantSP** [comment]
Not sure how Roy was doing that as I always get error messages from the OS saying the destination folder contains a folder of that name, and then offers the choice to proceed like this one.
![renaming](https://user-images.githubusercontent.com/3291695/37062369-572a8fb2-21ea-11e8-90a1-00c3d0b98bfa.png)

**Comment by SuperSandro2000** [comment]
I would assume he just did this and merged the folders.

**Comment by Al12rs** [comment]
The problem is that if the user selects replace the files are replaced but the two mods remain separate. The user should not be allowed to choose an existing name.
