### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by twizz0r** [ModOrganizer2/modorganizer#257]
# The problem

MO2 displays the following warning on start up: 

libpng warning: iCCP: known incorrect sRGB profile

# Environment

* Mod Organizer Version that exhibits the issue: MO2 v2.1.1 (2018-02-27) with usvfs fix for insider preview issue
* Last Mod Organizer Version that did not exhibit the issue (if applicable): 2.1
* Desktop OS/version used to run Mod Organizer: Windows 8.1 Pro

# Details

Seems there is a problem with one or more PNG files in MO2: 

https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile

This is just a warning and does not seem to impact MO2 functionality. 

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/twizz0r/41f05b8a9ecb8ed544089eb0f512f4d3

## MO Interface
https://gist.github.com/twizz0r/41f05b8a9ecb8ed544089eb0f512f4d3

**Comment by Al12rs** [comment]
It is a matter of hiding the warning, no actual problem. Very low priority. The message can be ignored.

**Comment by Silarn** [comment]
Can we verify this was fixed by running the images through the optimizer?

**Comment by Al12rs** [comment]
I don't think I see this anymore
