### ISSUE TITLE
Mod Organizer installer cannot extract qtwindowsvistastyle.dll

### ISSUE THREAD

**Issue by itaranto** [Modorganizer2/modorganizer#269]
# The problem
Mod Organizer installer cannot extract qtwindowsvistastyle.dll "Error 404 not found".
This causes the installation to fail.

# Environment
Mod Organizer v2.1.1 - Windows 7.

**Comment by Al12rs** [comment]
Could you check if it is fixed now?

**Comment by itaranto** [comment]
I tried form the latest version 2.1.1 from Dec 27, 2017.
Is there any newer version to try?

**Comment by Al12rs** [comment]
Please try installing again, we were moving the repos so it could have missed some stuff to download. If it still doesn't work, it will be fixed in the next release.

**Comment by Silarn** [comment]
I'm not sure if the old installer was ever updated but this will be fixed with the next release, which is soon.
