### ISSUE TITLE
Uninstalling a mod set as hidden does not update the download to show as uninstalled

### ISSUE THREAD

**Issue by ThisIsPatrick** [Modorganizer2/modorganizer#277]
# The problem

Uninstalling a mod set to hidden does not update the downloads to show it as 'uninstalled,' instead it's still listed as 'installed.'

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 10 v1709 build 16299.125

# Details

Ensure 'Show Hidden' is not checked.
Install a mod from the downloads pane, now right-click and select 'Hide' on that mod.
Select 'Remove mod...' on the mod that was just installed. Enable the 'Show Hidden' check mark and the appropriate mod in the downloads pane will not be updated to show that it has been uninstalled, instead it will still show as installed.

If 'Show Hidden' was enabled at the start of this the mod status will have been updated to show it as uninstalled.

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/ThisIsPatrick/2d592745aa3944ea7cad5f28beda4e78

## MO Interface
https://gist.github.com/ThisIsPatrick/b00c598ce258c5774dd8b6fb6097d4f5

**Comment by Silarn** [comment]
Interesting. I know this does work... sometimes anyway. USVFS logs are unlikely to help in this case. 

Is it only hidden downloads that do not update?

**Comment by ThisIsPatrick** [comment]
Yes, to your question.

**Comment by Silarn** [comment]
This seems like a relatively simple fix so I'll try to knock it out before we release.

**Comment by Silarn** [comment]
There's a fix for this in #builds - can you please test it and let me know if it works?

**Comment by ThisIsPatrick** [comment]
The fix did not work.
Now, when uninstalling a mod that is hidden from view a ,meta file is placed in the Base Directory that only contains "[General] uninstalled=true"
It looks as if the .meta file is meant to go in Downloads but is instead being placed in the Base Directory.

This new behavior (still) only happens when uninstalling a mod set as hidden from view and Show Hidden is not checked.

**Comment by Al12rs** [comment]
Reported to be fixed on discord on the release candidate
