### ISSUE TITLE
[Feature Request] View non-conflicting files

### ISSUE THREAD

**Issue by CJM7** [ModOrganizer2/modorganizer#278]
Said feature is helpful when comparing large numbers of files such as in texture/mesh replacement mods.

**Comment by cibrhusk** [comment]
I really would like this feature also. I'm currently in the process of creating a large Morrowind mod selection and for many texture/mesh mods there comes a point where one of the mods has been replaced on all it provides and could be removed.
Right now I the only way to do this is by comparing each mod with the total result (I do this with total commander's directory sync between the mod and the vfs result).
So +1 for this feature request
