### ISSUE TITLE
[Feature Request] Mod download inside MO

### ISSUE THREAD

**Issue by Yoosk** [ModOrganizer2/modorganizer#279]
As Silarn said: "it should be possible to parse the available files and give you a download dialogue of the file descriptions and versions."

Instead launching browser and checking for files there, i'd like to have an option to do that inside MO, so everything would be centralized.

**Comment by Silarn** [comment]
This is a more involved ticket and will probably not be implemented for a while. It'll require considerable restructuring of the current download handler.

**Comment by Al12rs** [comment]
This is probably a bad idea. users should visit the page before downloading an update anyways. Let me know if you wish for me to reopen this
