### ISSUE TITLE
Working directories of added executables (Issue/Feature Request)

### ISSUE THREAD

**Issue by MatejVitek** [Modorganizer2/modorganizer#282]
# The problem

Recently I tried changing the directory NIF Optimizer starts in when run from MO2. However, changing its "Start in" setting results in the application no longer running - when I try to run it, MO2 simply locks for a while and then unlocks again without doing anything.

If I do the exact same thing with a regular desktop shortcut (make the Target SSE NIF Optimizer.exe and set the Start In field to, say, C:\Users\Me), it works as expected - it runs NIF Optimizer with its current (working) directory set to C:\Users\Me.

Is MO2's "Start in" really only intended for running java archives?

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.1
* Desktop OS/version used to run Mod Organizer: Windows 10

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/MatejVitek/d507467a887a1a6a6a699c0a5c2d92e3

## MO Interface
https://gist.github.com/MatejVitek/5ab8686abf84a80c8abc5fd100e1e386

**Comment by Yoosk** [comment]
Works perfectly fine on latest dev version, so that should be closed as its already resolved.

**Comment by Al12rs** [comment]
@MatejVitek could you confirm that the issue does not appear for you when using the latest build in in the discord server under the #builds channel? Link to discord can be found on the main github page and on the Nexus Mo2 pages.

**Comment by MatejVitek** [comment]
The same issue still appears in the developmental build of 2.1.2. However, I've managed to pinpoint it a little better. The issue only appears when I try to start an executable in C:\Users\Me\AppData\Local\ModOrganizer\SkyrimSE\mods\ or its subfolders. I'm guessing it has to do with the way MO handles virtualization, which causes the mods directory to be inaccessible at the time of executable startup (even though it is accessible by the executable afterwards).

I'm closing this issue, as fixing it would likely take more effort than it's worth (literally only saves 1 double click for me).

**Comment by Yoosk** [comment]
You have skyrim inside you MO folder inside Appdata?

**Comment by MatejVitek** [comment]
No, I have Skyrim in C:\Games\Steam\steamapps\common\

The SkyrimSE folder in %localappdata%\ModOrganizer\ was just how MO2 set itself up when installed.

**Comment by Silarn** [comment]
Why is it you're trying to set the start in? You should probably set this to the virtual location in the game data directory rather than the actual location of the files in the mod directory.

**Comment by MatejVitek** [comment]
3 parts to that answer.

- Why am I trying to set Start in?
Because I'd like NIF Optimizer to start in a folder close to where it may actually have meshes to optimize and it doesn't have command line arguments to allow setting tha.

- Why am I starting it in the mods folder rather than the virtual Data one?
Because in the Data folder the files are no longer categorised by their respective mods. This makes files from a specific mod more difficult to find even when cleaning one by one and it makes automatic subdirectory cleaning impossible without also affecting other mods.

- Why not just run NO without MO2 then if I don't actually need the VFS?
I just like to have MO2 as my modding central and launch pretty much everything mod-related from it.
