### ISSUE TITLE
Download tab will not refresh when you drop files to it

### ISSUE THREAD

**Issue by Gnidddy** [Modorganizer2/modorganizer#285]
When dropping files in the downloads tab via drag and drop, the list will not show the files unless you click show hidden files

Windows 10 1709

* Mod Organizer Version that exhibits the issue: 2.1.2 beta1 by Silarn v4
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): dev build 0.2 with usvfs J2

**Comment by Gnidddy** [comment]
Got it working, but I dont know what I did other then restart  MO.
This was on a new Portable MO install

**Comment by Silarn** [comment]
It just isn't refreshing the download tab. We'll have to create an event to do this if you drop a file on it.

**Comment by Silarn** [comment]
It should show files right away but two things are possible. Either there was already a meta they was flagged as hidden or you dropped a file that mo didn't think was a valid install archive.

I would like to do something about invalid files so they can be at least deleted or something through MO. But that's another ticket.
