### ISSUE TITLE
image formats not supported

### ISSUE THREAD

**Issue by monyarm** [Modorganizer2/modorganizer#288]
# The problem

This indicates that files from dlls/imageformats are missing from your MO installation or outdated. Images in installers may not be displayed. Please re-install MO

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): I haven't used MO in a long time, so i don't know
* Desktop OS/version used to run Mod Organizer: Windows 10

# Details

There are no log files in the logs folder, but when i try to install a fomod i do get the following https://gist.github.com/monyarm/09f3961648f7a3b2c73b57db293df5b7

**Comment by Al12rs** [comment]
When do you get the issue, what steps do you do to reproduce?
Are you trying to install a specific mod?
Did you try to reinstall MO as asked?

**Comment by monyarm** [comment]
The error shows up as soon as i launch MO,
the errors from the log i posted happen when i try to install a mod with a fomod installer and images in said installer,
I have tried reinstalling,

Also joining the discord and downloading the latest dev version fixed it.

**Comment by SuperSandro2000** [comment]
It is quite likely that ``dlls\imageformats`` was missing some dll's. I think this can then be closed.
