### ISSUE TITLE
[Feature Request] Be able to download Oldrim mods with a Skyrim SE instance.

### ISSUE THREAD

**Issue by monyarm** [Modorganizer2/modorganizer#289]
I can see two ways of doing this, either make it so that if you have a Skyrim SE instance, Skyrim mods download into Skyrim SE. Or making it so that when

\---------------------------
Wrong Game
\---------------------------
The download link is for a mod for "Skyrim" but this instance of MO has been set up for "skyrimse".
\---------------------------
OK
\---------------------------

shows up, clicking OK makes it download it anyway

**Comment by monyarm** [comment]
Also doing this for TTW, so you can download both FO3 and FNV mods

**Comment by SuperSandro2000** [comment]
Kinda dupe with https://github.com/Modorganizer2/modorganizer/issues/249#issuecomment-375742097

**Comment by SuperSandro2000** [comment]
Not possible as nxm handler wouldn't know which games to open

**Comment by monyarm** [comment]
What do you mean which game to open? If I don't have an Oldrim instance,
but have Newrim, then open the Oldrim mods in the Newrim instance

**Comment by SuperSandro2000** [comment]
If you have an oldrim instance although? This is currently under discussion.

**Comment by monyarm** [comment]
If you have both then just do the current behavior

**Comment by Al12rs** [comment]
Completed as of 2.1.3
