### ISSUE TITLE
Cannot launch FO4 via F4SE any more

### ISSUE THREAD

**Issue by AndThereItIs** [Modorganizer2/modorganizer#290]
Before a recent Windows 10 update I was happily playing Fallout 4, using MO2 and F4SE.

Then, having played it the evening before, just before the update, it stopped working.  It gives these error messages as soon as I click the Run button:

![mo2_f2se_error_00](https://user-images.githubusercontent.com/37792144/37890810-406d084e-30d2-11e8-8bfd-f7bfd548c16e.png)

![mo2_f2se_error_01](https://user-images.githubusercontent.com/37792144/37890821-47396262-30d2-11e8-898a-5465f34621ec.png)

Thing I have tried:

- Made sure everything is 100% up to date (Windows 10 build 1709, Fallout 4 v1.10.75, F4SE v0.6.6, MO2 v2.1.1) 
- Fresh reinstalls of Fallout 4 and Mod Organizer 2 (including folders in documents and appdata), multiple times, clearing away folders and such
- Verified files through Steam (multiple times)
- Various compatibility settings

No change, same errors.

F4SE works if launched directly, or using NMM, but not via MO2 any more.

If necessary, describe the problem you have been experiencing in more detail.

No logs at all.

At my wits end here.  :(

**Comment by Al12rs** [comment]
Could you test the latest build on discord to see if it fixes the issue? The discord channel il linked both on the nexus pages and on the top of the github page.

**Comment by AndThereItIs** [comment]
Goodness me, that one works!  It works!  Ha haa!  Thank you, I had not dared to try that, thinking it was only for the daring.

But I can use it to play, no?  Thank you again.

**Comment by SuperSandro2000** [comment]
You can play with it. Fixed with next release label plz

**Comment by AndThereItIs** [comment]
Yay!  Thank you both.  ^_^
