### ISSUE TITLE
MO2.1.1 Skyrim SSE wont start

### ISSUE THREAD

**Issue by techietrooper** [Modorganizer2/modorganizer#291]
# The problem

MO2 will lock, start the script extender and start the SkyrimSE.exe file. Then the SkyrimSE.exe will crash and MO2 unlocks. SSE works fine with mods if I install using Nexus. I have tried and clean installed several times and cannot seem to figure out the issue. Same occurrence each time

# Environment

MO2.1.1 Windows 10 x64 Pro

**Comment by Silarn** [comment]
I'd suggest trying the Dev build on discord first.

**Comment by techietrooper** [comment]
I will look it up thank you

**Comment by techietrooper** [comment]
Downloaded the Dev5 build dated 3-28-2018 MO2-2.1.2 and it has the same issue. Am I missing something in configuration?

**Comment by techietrooper** [comment]
Just an update to clear this thread. The new build does work in vanilla with no mods. So it is likely a mod or order issue. Ill work it out. Thanks
