### ISSUE TITLE
Steam Overlay doesn't work with MO2

### ISSUE THREAD

**Issue by theFisher86** [ModOrganizer2/modorganizer#293]
# The problem

Launching F4SE or just regular FO4 the Steam proper overlay does not work.  Sometimes the normal, grey, steam overlay shows up however the proper (blue) Big Picture overlay that allows you to change your controller configs and use other steam controller features doesn't work.

# Environment

* MO2.1.2 rev 336216b
* Windows 10 

# Details

I've tried Launching F4SE and normal Fallout directly from MO2, creating an MO2 shortcut and launching that from steam but nothing seems to work properly.

When launching directly from MO2 is when you get the grey Steam overlay instead of the Big Picture.

Here's some other stuff that may be useful: 

- To my knowledge Steam uses the Big Picture Overlay when it detects a compatible controller attached to the PC.  I have a Steam controller (definitely compatible).  
- When launched from MO2 it shows the normal (grey) Steam Overlay, as if no controller was present.
- Steam does however properly emulate the controller in all these situations.  So it's doing something
- Could the way MO2 does it's hooks or whatever be _blocking_ Steam from detecting the controller?

**Comment by Silarn** [comment]
It's possible but I'm not really sure where to start looking for this.

**Comment by hyper1on** [comment]
This may not be any help, but steam big picture overlay used to work with mod organizer in a previous version.... Maybe the version that was current in february of this year?

**Comment by hyper1on** [comment]
Strange, it is working now.  It wasn't last night...

For reference, I am using F4QuickLauncher to launch F4SE from a MO shortcut in big picture mode.
