### ISSUE TITLE
MO2 doesn't work with the new Windows 10 Spring Creators Update

### ISSUE THREAD

**Issue by Paul-Kuhn** [Modorganizer2/modorganizer#296]
MO2 doesn't work with the new Windows 10 Pro x64 Bit Build 17133 (Spring Creators Update).

Games (Fallout-Series, Skyrim/SE) crashed. And there are also problems with LOOT (No Mods/ DLCs are displayed). Many Problems with MO2 and the upcoming Windows Update.

**Comment by Silarn** [comment]
Please see #211
