### ISSUE TITLE
MO Broken by Spring Creators Update?

### ISSUE THREAD

**Issue by Sonicskater** [Modorganizer2/modorganizer#297]
# The problem

Updated to windows build 1803, mod organizer completely failed to load even Skyrim.esm when loot or the game were started. Reverted to 1709, MO works perfectly fine again.

# Environment
MO v2.1.1 + SkyrimVR plugin
Windows build 1803
LOOT 0.12.3
SkyrimVR BuildID 2653205

## USVFS Log
https://gist.github.com/Sonicskater/9d4d0446703a969e3027efd0249005da

## MO Interface Log
Got overwritten, sorry :(

**Comment by Silarn** [comment]
#211 #296 

Please search closed tickets
