### ISSUE TITLE
Cannot Execute Modorganizer 2 (download from Nexus)

### ISSUE THREAD

**Issue by Ayla12** [Modorganizer2/modorganizer#299]
I cannot open the executable file found in the Mod Organizer 2 (Standalone Version) 7Z file. Whenever I try, I get a "side-by-side configuration is incorrect"-error.

I want to play modded Skyrim SE using Mod Organizer 2 version 2.1.1., downloaded from the Nexus today (08.04.2018, 12:50 CET). 

My OS version is Windows 10 Home. 
(Intel (R) Premium (R) CPU G3240 @ 3.10GHz 
12 GB Ram)

(I have played Skyrim SE before, modded with Nexus Mod Manager, but I have deleted all NMM/and mod related files and currently have no mods installed.)

I have tried to follow YouTube video instructions on how to correct this error, but when I copy the version given in the Event Viewer failure log, which is "1.0.0.0" (without the ") and paste it in google as the video suggests, I do not get links to download a  Microsoft Visual C++ Redistributable Package. According to the video, I should. 
What I do get are links to sites like "What is my IP Adress?".

I use Mod Organizer Version 1.3.11 for Skyrim Old Edition. No Problems with the installation, nor any problems with the modding itself.

Can anyone help me?

**Comment by Al12rs** [comment]
On the MO2 SSE Nexus page description there are links to the Visual C++ Redistributable, dowload all of them and click repair to see if that fixes the problem.

**Comment by Ayla12** [comment]
Thank you @Al12rs for the suggestion. I tried it out.

Unfortunately though, I already HAVE those Packages... all of them.

**Comment by Silarn** [comment]
This is usually caused by missing or blocked files. Make sure that you unblock the zip before you extract it and that nothing in MO's directory is getting blocked by an AV or the like.
