### ISSUE TITLE
Crash when installing two mods at once

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#300]
Reproduced with MO 2.1.1 and MO 2.1.2 Dev Build 7
Windows 10 Version 1709 (OS Build 16299.309)

Steps to reproduce:
1.  Start installing a large mod (e.g., KS Hairdos SSE 1.5).
2.  Wait a few seconds and start installing another mod (e.g., Point the Way 2.0.2).
3.  Wait for crash.

Logs here (v2.1.1) : https://gist.github.com/LostDragonist/43ebdc2b5e1f1d2feac31a8811a4849c
Crashdump (v2.1.1): [ModOrganizer.exe-352928.dmp.zip](https://github.com/Modorganizer2/modorganizer/files/1888035/ModOrganizer.exe-352928.dmp.zip)

**Comment by Silarn** [comment]
Can you please post a dump from dev build 7? I don't have the PDBs on hand for 2.1.1.

**Comment by LostDragonist** [comment]
[ModOrganizer.exe-376916.dmp.zip](https://github.com/Modorganizer2/modorganizer/files/1896842/ModOrganizer.exe-376916.dmp.zip)

I added the logs to the gist up above.

**Comment by Silarn** [comment]
I've heard some people say they can do this now. Worth a check.

**Comment by LostDragonist** [comment]
I'm still able to reproduce with 2.1.4 build 2, patch 2 using the mods named above.

**Comment by Al12rs** [comment]
Still a thing in 2.1.7alpha7

**Comment by Al12rs** [comment]
Now should show error message when trying to install a second mod:
https://github.com/ModOrganizer2/modorganizer/commit/ee266e52209fc9fce32031fd5ae0c9703b64cada
