### ISSUE TITLE
"Query Info" asks you to select from no longer existing file names

### ISSUE THREAD

**Issue by Qwinn1** [ModOrganizer2/modorganizer#301]
# The problem

I will describe how to easily replicate the issue.  For Skyrim Special Edition, go to this mod page:

https://www.nexusmods.com/skyrimspecialedition/mods/12371?tab=files

Note there are only 10 files on the Files tab.  Manually download the Gildergreen one (although the issue will happen for ANY of them).  On the Downloads tab in MO2, Right click "Skyrim 3D Gildergreen-12371-1-00g.rar" and click Query Info.   I get a Select box saying "Failed to guess mod for "Skyrim 3D Gildergreen-12371-1-00g.rar", please pick the correct one.  I can choose "1" (because it seems it's incorrectly parsing the version # as the mod page #, possibly the modder's fault for not following naming conventions) and "12371", the correct page.  I select 12371.  Then I get a Select box saying "No files on Nexus matches the selected file by name.  Please manually choose the correct one." and I am given 32 choices, all much older version numbers of the files than are available on the page.  The actual file I'm trying to install is not on the list, because the list appears to always be truncated after 32 choices.

There are also a few mods that actually have far more than 32 files active on the page at once, such as:

https://www.nexusmods.com/skyrimspecialedition/mods/7134

So, I'd suggest either expanding the possible options to greater than 32 (say, 128 or 256) or sorting them by file update time (if that info is available to you) in descending order before doing the truncate so the most recent files are the ones that make it into the 32 that you are offered. 

# Environment

Mod Organizer 2.1.1, one of the dev builds from February, apologies that I'm not sure which one but I believe it happens with all versions.

Windows 10.

**Comment by Silarn** [comment]
Interesting. We will have to see if there's some sort of flag in the API response to indicate a download that's hidden or unavailable.

**Comment by lettuce-prey** [comment]
it would be helpful in choosing a file if in the query info listing the date of the last change of the file, or the upload date could be added to the information on each line listing a file in the query info listing.

i was going to add a new comment, but i'll add to this one since it is along the same line.

the specific mod i am struggling with at this time, and i have had problems with many others also, is MCM [mod configuration menu] i am not finding version 1.26 that was uploaded to nexus on 25may2018
https://www.nexusmods.com/fallout4/mods/21497?tab=files

what would be better would be if the mod authors would have some consistent method for version naming, but we know that's not going to happen.

the methods you use to get around a lack of version naming conventions is very helpful, and i thank you for your efforts.

i enjoy playing around with adding and removing mods and mod organizer is very helpful with that.

**Comment by jmdavis** [comment]
I've hit this problem with several mods - e.g. https://www.nexusmods.com/skyrimspecialedition/mods/9651?tab=files currently only has two files, and yet "query info" lists a bunch of different files - none of which are the correct file.

**Comment by lettuce-prey** [comment]
> I've hit this problem with several mods - e.g. https://www.nexusmods.com/skyrimspecialedition/mods/9651?tab=files currently only has two files, and yet "query info" lists a bunch of different files - none of which are the correct file.
--> 
yes this is a problem that i run into often, and if in the query info window there were dates/times of the files uploading to nexus it would be much easier to make a choice.
it's frustrating.
i don't know what would be involved in putting time in the name listed there.
i have not yet run into the situation where none of them were the correct file.
i have however needed to download many of the files listed to eventually find the one i wanted.

**Comment by Al12rs** [comment]
We plan to move to the new nexus API, so this will not be fixed in the meantime as it would be stupid to fix it twice. 
For the API move itself we would need some help as we don't have much free time and we have other things that take precedence.

**Comment by jmdavis** [comment]
@Al12rs If someone were actually going to look into working on adding support for the new Nexus API, where would the documentation for it be found?

**Comment by Freso** [comment]
@jmdavis In the Vortex source code: https://github.com/Nexus-Mods/Vortex

**Comment by jmdavis** [comment]
So, the only documentation is the nexus' official mod manager's source code, and it's in typescript no less. Ouch.

**Comment by Silarn** [comment]
The newer API significantly changes how files are returned and this might go a long way to limiting this issue.

**Comment by Al12rs** [comment]
This should be completely fixed with the new API
