### ISSUE TITLE
64bit executables see virtual files but 32bit ones do not 

### ISSUE THREAD

**Issue by dt78** [Modorganizer2/modorganizer#302]
# The problem

usfvs seems to fail when running 32bit programs through MO. Loot, FNIS, and Wrye do not see any mods or plug-ins. Bodylisde64 and SKSE64 have no problem.

# Environment

* Mod Organizer Version 2.1.1+ (Pre-release 2.1.2 patch 9 same problem):
* Was working in 2.1.1 then suddenly stopped
* Windows 10 pro 1709 16299.309

# Details

Everything was working and then suddenly broke after updating the SKSE64 to 2.0.7 and Simply Knock mod. I tried to resort my mods with Loot and it only saw the vanilla ESMs. Tried all the following with no luck:
- Reversed the updates with.
- Deleted and reinstalled MO.
- Removed/Reinstalled VC_redist.x86 and x64.
- Deleted ALL MO program and user data +mods. Started with fresh MO setup.
- Started all over with fresh with pre-release version 2.1.2 and patches.
- Windows defender is disabled. No other AV is running. No registry cleaners have been used.
- MO running as admin.

USVFS logs are always blank now (even when it works). MO is set to Debug log level.

I don't know what else to try. Been through all the fixes I can find. Thanks in advance for any help!

## USVFS
Blank

## MO Interface
https://gist.github.com/dt78/e16a4c56c73088d002039346357fba9f

**Comment by dt78** [comment]
This eventually led back to a hardware issue causing file corruption. Closing this issue.

Thank you!

**Comment by Silarn** [comment]
Glad it wasn't directly MO. Thanks for letting us know.
