### ISSUE TITLE
MO Cannot handle NMM Links even with the separate handler used.

### ISSUE THREAD

**Issue by Commanduf** [Modorganizer2/modorganizer#303]
# The problem

MO Cannot handle NMM Links

# Environment

Version 2.1.1

# Details

When starting MO it always asks me if I want it to handle NMM links, despite clicking yes every time, when I do click download with the manager on the nexus I get the prompt again, clicking yes this time then causes an error to show saying no application has been registered to handle the link.

I tried following the fix on the sticky post of the nexus page for MO organiser activating NXMhandler.exe and clicking make active and it has changed nothing.

# Link to Mod Organizer logs

## MO Interface

https://gist.github.com/Commanduf/55ad62ad4b2d609ea52ec6f5b8b79c32

**Comment by Al12rs** [comment]
Can you try following the instructions for the NXMHandler part as explained here: https://www.google.it/url?sa=t&source=web&rct=j&url=https://m.youtube.com/watch%3Fv%3DK_An2ojM11I&ved=0ahUKEwj_7JvXxbTaAhXPzqQKHfUECNgQtwIIJTAA&usg=AOvVaw2CXBJcFTrYgYQQG5Y0nwEz
The description should have the timestamp where it is explained

**Comment by Commanduf** [comment]
Hello, I have tried following the video to the letter now (really helpful vid btw) but unfortunately, it still has not changed, I will now try deleting NXMhandler.

**Comment by Al12rs** [comment]
The INI not the exe!

**Comment by Commanduf** [comment]
Sorry thats what I meant, im still looking for it atm

**Comment by Commanduf** [comment]
I don't think there actually is an NXMHandler.ini in my MO folder, at least not in the root folder, I have checked over the other folders but I will have another look.

**Comment by Commanduf** [comment]
Yep, just did a search of the whole folder and there is not ini file for NXMHandler.

**Comment by Commanduf** [comment]
Ah, ty, that finally got it.

In the past I remember I had put in some sort of work around when using MO2 with fallout 4 and replaced the MO folder in appdate with a shortcut of the same name linking to the folder somwhere else.

Thanks alot for the help :D
