### ISSUE TITLE
MO2 integrated Update feature messagebox Dialog Too Large to Use

### ISSUE THREAD

**Issue by AZCoder** [Modorganizer2/modorganizer#306]
Simply that the modal dialog that pops up when you click the update button is larger than my 1080 vertical pixel height monitor. There's no way to resize or scroll to the bottom. I cannot use it to update because the bottom goes way off the screen (I'm surmising). The last item I can see is "added flag and description to ESL flagged ESPs".

**Comment by Silarn** [comment]
Just press enter for now. LePresidente will have to update his GitHub release changelog to shorted the text a bit. We'll update this display in future versions.

**Comment by AZCoder** [comment]
The update option came up last night and worked, thanks!

**Comment by Al12rs** [comment]
Yeah I just put everything in the information text filed but QMessageBox does not allow resizing so it is just tiny. To make it look good we either have to put it in a different kind of widget or subclass QMessageBox and change it to our needs. I didn't really feel like spending all that time on it so I just made it usable for now.
