### ISSUE TITLE
Error warning about masterfiles

### ISSUE THREAD

**Issue by Nico2b** [Modorganizer2/modorganizer#312]
# The problem

Error warning when clicking in my masterfiles in the mods pannel : invalid origin name: DLC:Dragonborn and for the 2 others. After 2 minutes they become normal, no more error warning and I can move them. But when I restart, they are put in the top of the list and the problem reapear.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.2
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.1.1
* Desktop OS/version used to run Mod Organizer: Win7 Pro 64bits

**Comment by Al12rs** [comment]
can anyone still reproduce?

**Comment by Al12rs** [comment]
Will close for lack of response and inability to reproduce in a few days.
