### ISSUE TITLE
MO2 Not Saving Mod into Overwrite from CK

### ISSUE THREAD

**Issue by geekalert** [Modorganizer2/modorganizer#313]
# The problem

After saving a plugin from CK when running it through MO v2.1.2, nothing is saved into the Overwrite folder.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.2
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.1.1
* Desktop OS/version used to run Mod Organizer: Win 10 Pro (Version 1709, build 16299.371)

# Details

I double-checked this issue by loading the Ck through v2.1.2 of MO 2 and trying to save a plugin; nothing was written into the Overwrite folder upon closing the CK, even though it had said it was saved. I uninstalled v2.1.2 and re-installed v2.1.1 and it worked without a problem. I tried it for both one more time and was able to duplicate the issue.

# Link to Mod Organizer logs

I will figure out how to run these and paste them into the areas below issue ASAP. I'm guessing you need the ones from both?

## USVFS
For v2.1.1 - https://gist.github.com/geekalert/b65c006a10980c8fdf7242c3801e0cf8
                   https://gist.github.com/geekalert/6a30742f50433126d6f5bb37e19281ef

For 2.1.2 - https://gist.github.com/geekalert/9214f00966c817a95453cf274a295014

## MO Interface
For v2.1.1 - https://gist.github.com/geekalert/f9b01d815cf4509cbfed23cb19bc925f

For 2.1.2 - https://gist.github.com/geekalert/ddada670a502c3a69516d168d144809c

**Comment by Silarn** [comment]
From the changelog:

Virtual File System (usvfs) changes:
- All the files that are edited inside the virtual folder will get properly edited now,
without getting copied over to overwrite. This means that plugins or masters edited
in xEdit for example will no longer show up in the overwrite folder as they did before
and the changes will instead be applied to the original file instead, like it was
supposed to do. The old behaviour can be considered a bug.
This will greatly lower the cluttering of the overwrite folder.
The overwrite folder will now only contain newly generated files that were not already
present in the virtual folder.
