### ISSUE TITLE
MO keeps updating to 2.1.2 

### ISSUE THREAD

**Issue by Taubin** [Modorganizer2/modorganizer#314]
# The problem

Mod Organizer keeps installing version 2.1.2 on startup, even if it's already been updated. If I do not allow it to update, I cannot load any saves or mods.  I have done an install manually (downloading the installation from github), and receive the same asking to update every time it opens. 

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.2
* Last Mod Organizer Version that did not exhibit the issue (if applicable): 2.1.1
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro (running as admin as always)

# Details

When I start MO, I see that there is an update available. I click the update, and it downloads and installs. Once completed, I am able to start up the game with my saves. However, the next time I start the app up, I get the same update available, and if I do not allow it to update, it will not load any of my mods, or my saves. 

Interface log:

## USVFS
https://gist.github.com/Taubin/8b1279163bc4d84f6420214d043464e6
https://gist.github.com/Taubin/94848a16ddbb25038d1981165a5cc4eb
https://gist.github.com/Taubin/903c13e2c2aae7351a0fe6e352dbd4a8

## MO Interface
https://gist.github.com/Taubin/cf8043d4bbe6b232ba6accf4304bd191

**Comment by Silarn** [comment]
I'm going to guess that you're running a separate copy of MO and when you update it you're installing the update to another location (which is then automatically run).

Make sure you are updating/running the correct copy of MO2.

The version number is baked into the EXE so there's really no way for this to be wrong.

**Comment by Taubin** [comment]
Boy am I an idiot, I was in fact not changing the location of the installation when updating. Sorry about that. You are entirely correct. I've updated it manually pointing it to the previous and it's working just fine. 

I'll make sure to pay better attention next time I update. Thank you for the help.
