### ISSUE TITLE
The Downloads pane reverts to sorting by Filetime

### ISSUE THREAD

**Issue by ThisIsPatrick** [Modorganizer2/modorganizer#319]
# The problem

The Downloads pane reverts to sorting by Filetime when certain actions are done in the pane window.
For example, installing or deleting a file. Sometimes, for unknown reasons, it will happen without any user input.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.x
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): Unknown
* Desktop OS/version used to run Mod Organizer: Windows 10 1709 OS Build 16299.125

# Details

To reproduce this behavior:
Sort the pane by Name or Done status.
Install or Delete a file from the Downloads pane.
The pane will then have sorted itself by Filetime.

There are some quirks to this. Sorting by Name and then by Done status (so that files are sorted by Done status in alphabetical order), and then installing/deleting a file will cause the pane to resort itself by Done status and Filetime - this will ruin the previous sorting of alphabetically by Done status.

# Link to Mod Organizer logs

**Comment by Al12rs** [comment]
Should be fixed by: https://github.com/Modorganizer2/modorganizer/commit/d02df7e4b4d6b539ed744135eee565530c24f006
