### ISSUE TITLE
skyrimVR will now continue with out sound

### ISSUE THREAD

**Issue by sky199411** [Modorganizer2/modorganizer#320]
if i use MO2.1.2 to start skyrimVR, it was no sound.

use steam to start skyrimVR，business as usual.

Is there anyone like me？

**Comment by Silarn** [comment]
I'm going to assume you're using local settings. Please delete your profile settings inis and let it regenerate the settings files - or just use the global ones.

**Comment by sky199411** [comment]
thank you!
....but where is my profile settings?
C:/Users/PeterPom/AppData/Local/ModOrganizer/NewName/profiles/   ---Is it here?

**Comment by Silarn** [comment]
There is a folder button in the upper right that can take you straight to your active profile. If NewName is what you named your running instance then that's where your profiles are located, yes.

**Comment by sky199411** [comment]
okey!  i'll try
thanks!

**Comment by Silarn** [comment]
Glad it worked out!
