### ISSUE TITLE
Mod Organizer 2 update has made my screen too big!

### ISSUE THREAD

**Issue by Geodyssian** [ModOrganizer2/modorganizer#321]
# The problem

The Mod Organizer 2 screen after the last update has simply been enlarged to the point I can't seem to deal with it well. I updated it using the update icon in the Mod Organizer and it simply became this:

![image](https://user-images.githubusercontent.com/38517190/38970522-5cba579e-43d9-11e8-9e72-31cc0c015cd7.png)

and after refreshing, adding or deleting, becomes this:

![image](https://user-images.githubusercontent.com/38517190/38970975-f276937c-43db-11e8-8a54-0425e8f2d827.png)

Also, previously, I could minimize it to half a page, now however:

![image](https://user-images.githubusercontent.com/38517190/38970988-115ffeae-43dc-11e8-8246-be2697c898c8.png)

Please help. Thank you.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.2
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.1.1
* Desktop OS/version used to run Mod Organizer: Windows 10

**Comment by Silarn** [comment]
You can adjust the windows scaling method in the application properties dialog (via windows). Most people report better results with one of these options. However, I believe we should transition to using relative sizes instead of relying on this scaling method.

**Comment by Silarn** [comment]
I've just pushed a very experimental (and essentially untested) alternative method for doing scaling to Discord. Please test this build and report your results.

**Comment by Geodyssian** [comment]
Thank you so much!

But...
a) How on earth do I download it? (I essentially downloaded the entire github file)
b) How do I implement it? (I downloaded Mod Organizer originally from Nexus so I'm not quite sure where your change is and where I should put aforementioned change)

**Comment by Silarn** [comment]
It's on the discord channel, there are links all around. Check the description on the main repo or on Nexus.

**Comment by Geodyssian** [comment]
I'm not sure what is happening, but whenever I do, I get this

![image](https://user-images.githubusercontent.com/38517190/39105933-f763e06a-46fb-11e8-82ec-ef7b9b69f301.png)

Mod Organizer (1) is the untested one you advised me to get.
![image](https://user-images.githubusercontent.com/38517190/39105954-0e314d5a-46fc-11e8-91da-a60a0bb42aab.png)

**Comment by Silarn** [comment]
You have to get the full build and replace the exe in that directory. You can't just run the exe by itself or it will be missing required libraries from the full install.

**Comment by Geodyssian** [comment]
Where is the full build?
