### ISSUE TITLE
[Feature Request] Allow Mod Organizer to support non-Bethesda games

### ISSUE THREAD

**Issue by AnyOldName3** [ModOrganizer2/modorganizer#327]
This is a meta issue to keep track of the parts of Mod Organizer which are known to be hardcoded to be only compatible with the games it already supports. So far, it's quite short, which is nice.

# Error message displayed if a game plugin doesn't have the script extender feature
![image](https://user-images.githubusercontent.com/8485112/39217211-d72cafea-4816-11e8-840c-69a4286b0983.png)
If a game plugin does not have the `ScriptExtender` game feature, the above error message is displayed.

`LoadMechanism::activate` calls `LoadMechanism::deactivateScriptExtender` regardless of whether or not the current game supports a script extender, but `LoadMechanism::deactivateScriptExtender` throws an exception if the current game doesn't support a script extender.
## Solutions
* `activate` could check if there's a script extender before calling `deactivateScriptExtender`
* `deactivateScriptExtender` could just stop complaining.
* As USVFS doesn't even support load mechanism selection, the offending code could just be removed.

# The plugins tab in the right pane and the optional ESPs tab in the mod info dialogue only displays ESM/P/L files
There's no way for a game to not use these file extensions for plugins. I'm pretty sure if you put an ESL into a Morrowind install, Mod Organizer would assume it was fine, too.

## Solutions
* Allow game plugins to specify their own file extensions for plugins.
* Maybe even make having plugins in the first place a Game Feature (or make it part of the existing `GamePlugins` feature), and if the current game doesn't have it, hide the tab.

# "No valid game data" warnings aren't controlled by the game plugin
This is even a problem for the games we already support - an SKSE folder isn't part of any valid New Vegas mod, but Mod Organizer would say it was.

## Solutions
* Let game plugins implement a function like `IGamePlugin::looksValid` (which we already have) that checks if a directory looks like a valid mod. Use that to determine whether this warning should be displayed.

# Game plugins have to implement the `GamePlugins` feature
This feature is in charge of writing the load order and list of active plugins out to text files in the profile directory and reading them back again. For the currently supported games, these text files are also the same ones as the game reads to determine which plugins to load. MO crashes on launch if the active game doesn't have it.

## Solutions
* Make this optional. This will probably be a long-term thing as not having it sort of implies not having plugins.

**Comment by Al12rs** [comment]
I have adapted the test pythom game plugin to support a generic folder as an experiment to see what kind of issues and grievances there are for users. This could be a stop gap solution for people that don't mind some discomfort but still would like to use MO2 for other games.

These are the problems that have come up for now:

- [ ] Empty plugin list and no way to hide it (removing plugins feature crashes MO2).
- [ ] Empty saves tab and no way to disable it.
- [ ] Mod validity is not queried to the plugin, but is instead based on hardcoded general check.
- [ ] Content icons and the checks for that content is also hardcoded in the main code.

**Comment by Holt59** [comment]
Here are a few things that I found while trying to support new games:

* [ ]  Some games do not have all saves directly under the save folder. E.g., Dungeon Siege II uses `Saves/SinglePlayer/CharacterName/`. There are multiple way to handle this, either recurse into the game folder, but we would have to keep relative path, or add some kind of features to game plugin to handle this.

**Comment by Holt59** [comment]
Since the support for non-Bethesda game has been greatly improved, and now that we have proper labels for this, I think this should be closed an we should open distinct Github issues for each issue (easier to track / fix).

**Comment by Al12rs** [comment]
Many games store mods in different folders but still have conflicts when different mods provide the same files. The conflicts system would need to be modularized so that it can be adapted for each game.
This sounds almost impossible without rewriting all the directory structure and internal file registry code from scratch, which in turn is a massive undertaking.

**Comment by Holt59** [comment]
> 
> 
> Many games store mods in different folders but still have conflicts when different mods provide the same files. The conflicts system would need to be modularized so that it can be adapted for each game.
> This sounds almost impossible without rewriting all the directory structure and internal file registry code from scratch, which in turn is a massive undertaking.

I think we could handle this by allowing game plugins to use a custom conflict checker. By default, we would use the current one, which is very efficient but only work with top-level data module, and game plugins could provide a custom one, that would use the `IFileTree` structure.

This is I think a good compromise, that would not require re-writting the whole directory structure stuff but only the part that displays conflict to the users (either using the built-in one or the custom one provided by the plugin).

**Comment by Al12rs** [comment]
So like keep the directory structure and all that, just reroute the final results to something provided by plugins? I see this as still very complex as all the computation done would need to be replicated on the plugins, all the constant updates to the structure would need to trigger an update on the plugin conflicts as well and then have the results ready for the flags and conflicts tabs. Still a lot of work. You have to create a conflict system from scratch in the plugin.
Not saying it's not doable or worth it, but definitely not a light undertaking.

**Comment by AnyOldName3** [comment]
So are we closing this or using it as an epic to track all the distinct issues?

**Comment by Holt59** [comment]
> So are we closing this or using it as an epic to track all the distinct issues?

I'd say we close this, most of the stuff above have been fixed. The major stuff remaining is linked to plugins, but that's a whole stuff by itself.

If there are game specific or feature specific issue, then people can open new ones.
