### ISSUE TITLE
Minor bug: Location name in saves do not displayed correctly when in Russian

### ISSUE THREAD

**Issue by isshininu** [Modorganizer2/modorganizer#330]
# The problem

![561](https://user-images.githubusercontent.com/6324523/39398691-6bcbf83c-4b22-11e8-8ea1-af9523b507ea.png)
As seen in attached image, Location name not displayed properly, I am playing russian version of the game.

# Environment
Mod Organizer 2.1.3 Dev Build 5

# Link to Mod Organizer logs
This issue probably does not require log.

**Comment by Silarn** [comment]
I'm going to guess this is a unicode display issue, but I might need an example save to test with.

**Comment by isshininu** [comment]
ok, here it is

[saves.zip](https://github.com/Modorganizer2/modorganizer/files/1958084/saves.zip)

**Comment by Silarn** [comment]
Thanks. I will check when I have time.

**Comment by Silarn** [comment]
I posted an updated Skyrim SE plugin DLL in our testers channel. This should fix the issue for you, and the fix will correct all game plugins in the next release.

**Comment by Silarn** [comment]
I've released a full build with the change included in all games. You can reopen this ticket if you can replicate with this build.
