### ISSUE TITLE
SKSE co-saves do not deleted automatically from local profile

### ISSUE THREAD

**Issue by isshininu** [Modorganizer2/modorganizer#331]
# The problem
Files with extension *.skse created along with quicksave and autosave *.ess in Profile.
However they do not deleted automatically when quicksave and autosave gets overwrited by newer version.
Result in thousands of unnecessary files.

![562](https://user-images.githubusercontent.com/6324523/39404520-b5a588fa-4ba5-11e8-927e-7e34bffbdfda.png)

# Environment
Mod Organizer Version 2.1.3 dev 5
Windows 8.1 x64

# Link to Mod Organizer logs
https://gist.github.com/isshininu/6c9934a72345cb7d0163dc5f3f1b3e0b

**Comment by Al12rs** [comment]
If I remember correctly this is a bug with skse and not MO, but I'm not sure

**Comment by Silarn** [comment]
Correct. Unless you are unable to replicate this outside of MO this is a skse issue.

**Comment by Silarn** [comment]
Please reopen this if you are unable to replicate the issue outside of MO.
