### ISSUE TITLE
The Reqtificator Failed! error (Requiem + Skyrim 32bits + MO2)

### ISSUE THREAD

**Issue by mano-1** [Modorganizer2/modorganizer#338]
I see it's time to move on and switch to MO 2, but unfortunately I am having problems with Requiem, more precisely, Reqtficator fails to start.

As described here (Requiem MO 1 guide):
https://requiem.atlassian.net/wiki/spaces/REQ19/pages/19300507/Installing+Requiem+with+Mod+Organizer

I should create an empty folder on Skyrim real folder, then add it in the "Start in" session. But, "The Reqtificator Failed!".
Screenshot: https://prnt.sc/jdyabo

MO2 log: https://gist.github.com/mano-1/beb6474f8404a7ae1fba06d652ae749a

I've already disabled Avast, the problem continues.
I've also tried creating a Java x86 executable (which I currently use in MO 1.3.11 without any problem), but on MO 2 I get exactly the same error above.
FNIS and LOOT worked fine, but I must say that Requiem is the only mod I use that requires Java. 

-Tested on MO 2.1.2 stable (Nexus) and MO 2.1.3 build 9 (Discord).
-Skyrim Legendary Steam
-Requiem 2.0.1
-Java 10 (JRE 10.0.1 x64) / Java 8 (JRE 1.8.0.172 x86)
-Windows 10 Pro 64bits - 1709

**Comment by Silarn** [comment]
I'll have to play around with it later but many of those steps should no longer be necessary.

**Comment by Silarn** [comment]
This setup works just fine for me. This is the default setup created when adding the jar file to the executables. In addition, no changes need to be made to your Data directory.

**Comment by Silarn** [comment]
I'm going to close this issue unless you can identify a specific MO2 issue. I know there can be problems just having certain mods enabled with that. You might be able to just assign more memory from the start to see if that helps.
