### ISSUE TITLE
Intermittent Nexus download failure "Requested Range Not Satisfiable (299)"

### ISSUE THREAD

**Issue by neokio** [Modorganizer2/modorganizer#339]
# The problem

Downloading mods via Nexus sometimes works, sometimes doesn't.
I can't detect the pattern, but clicking the download button on Nexus adds the download to Mod Organizer, which quickly gives the error "Download failed: Error transferring ... server replied: Requested Range Not Satisfiable (299)".
The UI shows the download in the "PAUSED" state with a red dot next to it.
Downloading MANUALLY via Nexus and then installing it via MO2 works fine.

Here's the error:
![mo2_error](https://user-images.githubusercontent.com/146623/39666910-4a6d5094-5079-11e8-886a-2a75ff054a98.png)

# Environment

* Mod Organizer Version 2.1.2, running as administrator
* Windows 8.1 Pro (64-bit) on i7-3770K @ 3.5GHz
* Skyrim SE (with valid Steam license)

# Details

It could be related to filesize (316788 bytes?). My drive has plenty of space, but I notice that smaller files (like [this](https://www.nexusmods.com/skyrimspecialedition/mods/16991?tab=files)) go through without triggering the error, while slightly larger files (like [this](https://www.nexusmods.com/skyrimspecialedition/mods/16994?tab=files)) fail more often.

Here's the MO2 log:
![mo2_error_2](https://user-images.githubusercontent.com/146623/39667051-cb17e752-507b-11e8-81f6-c7ad6bd186e1.png)

# Things I've Tried

* Running MO2 with Admin privileges
* Clearing the Nexus Cache in MO2's Settings.
* Deleting the "Caches" folder (webcache) inside my Base Directory to make sure it gets recreated on launch (it does).
* Making sure the file doesn't already exist partially downloaded in downloads (it doesn't).
* Writing this GitHub issue ...

**Comment by Al12rs** [comment]
We are already aware of the problem and it is not on us: 
![image](https://user-images.githubusercontent.com/26797547/39667374-d46d3daa-50b4-11e8-9327-33fe002ab3d3.png)

Here is the discord link: https://discord.gg/MB3CyMH
