### ISSUE TITLE
Mod Organizer 2 not loading Mods

### ISSUE THREAD

**Issue by SMM91** [Modorganizer2/modorganizer#344]
# The Problem
Mod Organizer 2 is not loading mods when I launch it. The window is also scaled at a low resolution in the top left corner, with black filling in the rest of the screen. Fallout 4 Script Extender seems to be working, but my mods from Mod Organizer aren't. 

# Environment
* **Mod Organizer Version that exhibits the issue:** 2.1.2 Portable, persists if downgrading to 2.1.1 and updating to 2.1.3 pre-release.
* **Last Mod Organizer Verison that did not exhibit the issue (if applicable):** 2.1.1 
* **Desktop OS/version used to run Mod Organizer:** Windows 8.1 64-bit

# Details
Yesterday (May 8 2018) after I updated to release 2.1.2, my plugins stopped loading properly when launching F4SE from Mod Organizer 2. The problem persists regardless of how I launch the game, without or without Script Extender.  I tried quiet a few things to fix this, but nothing seemed to work.

- I reinstalled Mod Organizer, downgraded it to 2.1.1, upgraded it to the 2.1.3 pre-release build on the Discord server, went back to 2.1.2, and then again to 2.1.1, with no improvement. I tried both portable and new instances. I ended up sticking with 2.1.2 for the logs I'm uploading here. 
- I made sure all my files were in areas that would not cause issues due to permissions. Programs relevant to Fallout 4 / Mod Organizer are listed in my Anti-Virus exclusions.
- I launched the game with and without F4SE to make sure F4SE wasn't causing the problem. 
- I verified and reinstalled my FO4 files. 
- I enabled and disabled my plugins one by one to make sure they were being activated correctly. 
- I ran my game from each profile to make sure this wasn't just an odd case with one of the profiles.
- I made sure FO4 and F4SE were updated. 
- I've restarted my computer several times during these processes. 
- Moving the MO2 Folder out of Steam-related directories didn't help. 

# Link to Mod Organizer logs
(All logs posted are from Mod Organizer 2 Version 2.1.2)

## USVFS
https://gist.github.com/SMM91/87121af14824e8c61a1edf572b658e69

## MO Interface
https://gist.github.com/SMM91/8f345d975bab84d2c0e3ecfe3a23ce2b

**Comment by LostDragonist** [comment]
Closing this due to age and lack of activity.  It's likely related to the usual issues with anti-virus, Windows event logs, Windows updates, etc.

If you are still having issues after all this time, please reopen the issue.  Maybe hit up the discord channel for some more timely help.
