### ISSUE TITLE
Download pane sorting reverting to default

### ISSUE THREAD

**Issue by therobmcg** [Modorganizer2/modorganizer#345]
# The problem

The sorting on the Downloads pane gets reverted to the default. 
My preference is to set it to sort by Filetime, with newest files showing at the bottom of the list. I have to re-do this every time I open MO or whenever I close the Settings dialog. 

# Environment

* Mod Organizer 2.1.3 rc2 (installer)
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): pre 2.x?
* Desktop OS/version used to run Mod Organizer: Windows 10/latest.

# Details

No further details.

# Link to Mod Organizer logs

## USVFS

GIST - https://gist.github.com/therobmcg/35d8335863df1e9e614a55de70cfd082

## MO Interface

GIST - https://gist.github.com/therobmcg/310da96149cdac4643c417e597fd5b2e

**Comment by Silarn** [comment]
This duplicates #319
