### ISSUE TITLE
Mod Organiser don't launch the Game with the Launcher and SKSE

### ISSUE THREAD

**Issue by Touh87** [Modorganizer2/modorganizer#346]
Hello. I need help.

Since i reinstalled Mod Organiser cause i can't connect Mod Organiser to Nexus. Now i can't laucnh the game with SKSE and with the Launcher of Skyrim in Mod Organiser.

My Mo logs:
https://gist.github.com/Touh87/f2642264903fe9e18ca356cbaf4ccc85/edit

**Comment by jonathanangelpena** [comment]
same

**Comment by Silarn** [comment]
The gist is giving me a 404 so I effectively have no information to debug this issue. However, there are several known causes of this and I suggest you go through those first. (They are available on Discord in the info channel and in the comments section of Nexus.)

**Comment by jonathanangelpena** [comment]
Where cause i cant find /
