### ISSUE TITLE
Deleting saves on Skyrim Classic with SKSE causes windows errors saying the skse parts don't exist.

### ISSUE THREAD

**Issue by Meridiano** [ModOrganizer2/modorganizer#349]
# The problem

Everytime I delete saves from MO2 on Skyrim Classic, I get annoying messages from Windows, that skse-parts of saves don't exist. It seems MO2 is trying to delete skse-parts twice, because actually really delete them.

# Environment

+ Mod Organizer version that exhibits the issue: MO 2.1.3 Standalone (NexusMods release).
+ Last Mod Organizer verison that did not exhibit the issue (if applicable): I don't know. I've started with 2.1.2 and the issue was also there.
+ OS version used to run Mod Organizer: Windows 10, 1709, 16299.371.

# Details

Album on imgur with actions and messages - [link](https://imgur.com/a/A6dWFdY).

# Link to Mod Organizer logs

## USVFS

https://gist.github.com/Meridiano/96690cdf38af2d18f828908ed3015213

## MO Interface

https://gist.github.com/Meridiano/f1eabd2354baa1e18d05fe11b09204dd

**Comment by Al12rs** [comment]
This seems to not happen anymore, let me know if you can still reproduce

**Comment by Al12rs** [comment]
This appears to happen for oblivion as well, deleting the bse file saves twice for some reason

**Comment by Al12rs** [comment]
Potentially fixed by this: https://github.com/ModOrganizer2/modorganizer-game_skyrim/commit/cd03904ccc67fad1d29a1f4064e2a7080575848e
