### ISSUE TITLE
Can't update MO2 because changelog is too long. (Pressing enter installs the update correctly)

### ISSUE THREAD

**Issue by cvsickle** [Modorganizer2/modorganizer#350]
# The problem

The dialog box that lists the extremely long change log when updating to 2.1.3 is so tall, that I cannot click on install without hiding the task bar, and even then it's only barely visible.

see the image here: https://1drv.ms/u/s!AmZo1RvEgELcgp4TqPsTOWST4H3MRg

I'm using a 1440p screen with scaling set to 100%. You may want to think about putting a max height on the update confirmation window. I was able to update by hiding the task bar so that I could click the Install button.

Don't get me wrong, I'm grateful that the change list is so long. You guys are doing great work!

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.2 updating to 2.1.3
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro v1803 64bit

![mo2updatewindowtootall](https://user-images.githubusercontent.com/38385820/39847499-f1ea6042-53cf-11e8-8d96-4e02be1ceefe.PNG)

**Comment by LostDragonist** [comment]
You can hit enter to kick off the update.  This issue has been fixed in 2.1.3.

**Comment by Silarn** [comment]
Please check closed tickets.

**Comment by cvsickle** [comment]
You're right - that's my bad. Should have checked the closed issues. Sorry about that.

**Comment by Silarn** [comment]
I'm going to keep this open for a while so people see it.
