### ISSUE TITLE
TES5Edit can't read plugins

### ISSUE THREAD

**Issue by laman132** [Modorganizer2/modorganizer#353]
# The problem

TES5Edit, and things based off it, don't detect plugins. It was working like fifteen minutes ago, I dunno why it stopped. I've installed the redists available, [Picture](https://i.imgur.com/NTmNfES.jpg) . Can't install the 2015 redist, I get 

`[1E04:1F50][2018-05-12T02:43:33]i052: Condition 'VersionNT >= v6.0 OR (VersionNT = v5.1 AND ServicePackLevel >= 2) OR (VersionNT = v5.2 AND ServicePackLevel >= 1)' evaluates to true.
[1E04:1F50][2018-05-12T02:43:33]i199: Detect complete, result: 0x0
[1E04:1FE4][2018-05-12T02:43:38]e000: Error 0x80070666: Cannot install a product when a newer version is installed.`

presumably because I have a more up-to-date version installed. 

# Environment

* Mod Organizer Version 2.1.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.1.3
* Win10 1803

# Link to Mod Organizer logs 
https://pastebin.com/mHQfPxXF

## USVFS
A few are empty. Random nonempty log: https://pastebin.com/30rwM8nD

**Comment by Silarn** [comment]
Disable the feature to clean the windows event logs, as this is what causes the failure.

**Comment by laman132** [comment]
I actually had done that, it didn't help. Also don't run CCleaner. Unfortunately, I downgraded to MO1 since I was impatient to play, so can't give more feedback. Closing.

**Comment by Al12rs** [comment]
I guess I need to open an issue for the Ccleaner problem so we can keep track of it. I should probably do also other known issues
