### ISSUE TITLE
MO2 cannot install custom file types

### ISSUE THREAD

**Issue by ahzaab** [Modorganizer2/modorganizer#354]
Since MO2 cannot install custom file types it cannot install the custom .mhud file used by moreHUD SE. Vortex and NMM is able too. If this is by designed and unable to change, please let me know so I can find another way to allow custom tables to be entered for moreHUD.

**Comment by ahzaab** [comment]
Normally I would not assume, but I have had a few users having issues installing with MO2.  It wasn't until I released an update today with more logging, that I found that the .mhud file was not being installed.  Like I said, if there is no way to fix this, I will find a different solution on my end.  Thanks for your dedication and hard work.
________________________________

**Comment by GrantSP** [comment]
I have just now installed it and all the files are active in the filesystem. I haven't as yet started the game to see it in play but I see no reason why it will not if it shows as active in the MO2 UI.
If there is something that is hindering the USVFS from loading this filetype the devs will surely add it in.

**Comment by ahzaab** [comment]
Ok.  I'll see if I can do some research and let you know.
________________________________

**Comment by LostDragonist** [comment]
Probably related to this issue:  https://github.com/Modorganizer2/modorganizer/issues/323

**Comment by GrantSP** [comment]
Good catch. We should probably close this one and post updates on the original.
