### ISSUE TITLE
Installer: download failed: SendRequest Error

### ISSUE THREAD

**Issue by plambros** [Modorganizer2/modorganizer#355]
# The problem

When reaching the C++ runtimes installation step, the installer tries to connect somewhere, then fails with `download failed: SendRequest Error`

# Environment
OS: Windows 7 x64 (6.1.7601 Service Pack 1 Build 7601)
Installer: Mod Organizer 2 (Installer Version)-6194-2-1-3.exe
MSVC:
Visual C++ 2005 Redistributable	8.0.59193
Visual C++ 2005 Redistributable (x64)	8.0.59192
Visual C++ 2008 Redistributable - x64 9.0.21022
Visual C++ 2008 Redistributable - x64 9.0.30729.6161
Visual C++ 2008 Redistributable - x86 9.0.21022
Visual C++ 2008 Redistributable - x86 9.0.30729.6161
Visual C++ 2010 x64 Redistributable - 10.0.40219
Visual C++ 2010 x86 Redistributable - 10.0.40219
Visual C++ 2012 Redistributable (x64) - 11.0.61030
Visual C++ 2012 Redistributable (x86) - 11.0.61030
Visual C++ 2013 Redistributable (x64) - 12.0.30501
Visual C++ 2017 Redistributable (x64) - 14.11.25325
Visual C++ 2017 Redistributable (x86) - 14.14.26405

# Details

Full installer logs:

```Output folder: C:\Program Files\ModOrganizer
Extract: ModOrganizer.exe
Extract: helper.exe
Extract: usvfs_x64.dll
Extract: usvfs_x86.dll
Extract: usvfs_proxy_x86.exe
Extract: usvfs_proxy_x64.exe
Extract: nxmhandler.exe
Extract: uibase.dll
Extract: QtWebEngineProcess.exe
Extract: libeay32.dll
Extract: ssleay32.dll
Extract: boost_python27-vc141-mt-x64-1_67.dll
Output folder: C:\Program Files\ModOrganizer\loot
Extract: lootcli.exe
Extract: loot_api.dll
Output folder: C:\Program Files\ModOrganizer\plugins
Extract: installer_bundle.dll
Extract: diagnose_basic.dll
Extract: bsa_extractor.dll
Extract: inibakery.dll
Create folder: C:\Program Files\ModOrganizer\logs
Output folder: C:\Program Files\ModOrganizer\licenses
Extract: 7zip.txt
Extract: AntlrBuildTask.txt
Extract: Castle.txt
Extract: DXTex.txt
Extract: GNU-LGPL-v2.1.txt
Extract: GPL-v2.0.txt
Extract: GPL-v3.0.txt
Extract: LGPL-v3.0.txt
Extract: boost.txt
Extract: cpptoml.txt
Extract: fmt.txt
Extract: openssl.txt
Extract: python.txt
Extract: sip.txt
Extract: spdlog.txt
Extract: udis86.txt
Output folder: C:\Program Files\ModOrganizer\platforms
Extract: qwindows.dll
Output folder: C:\Program Files\ModOrganizer\QtQuick.2
Extract: qtquick2plugin.dll
Extract: qmldir
Extract: plugins.qmltypes
Output folder: C:\Program Files\ModOrganizer\DLLs
Extract: 7z.dll
Extract: archive.dll
Extract: libeay32.dll
Extract: ssleay32.dll
Extract: liblz4.dll
Output folder: C:\Program Files\ModOrganizer\resources
Extract: icudtl.dat
Extract: qtwebengine_devtools_resources.pak
Extract: qtwebengine_resources.pak
Extract: qtwebengine_resources_100p.pak
Extract: qtwebengine_resources_200p.pak
Output folder: C:\Program Files\ModOrganizer\styles
Extract: qwindowsvistastyle.dll
download failed: SendRequest Error
```

**Comment by Silarn** [comment]
The installer downloads files from GitHub which enforces TLS 1.2.

You most likely have this issue:
https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in

Make sure to also do the registry edit specified in that page.

**Comment by plambros** [comment]
@Silarn That did it.

**Comment by ladyqueensryche** [comment]
Having a problem downloading a program and getting an error like this: 
Unable to download to
C:\Users\pop\AppData\Local\Temp\VuzeInstall (SendRequest
Error), click OK to abort installation
