### ISSUE TITLE
Can't change to a different game

### ISSUE THREAD

**Issue by Tonalberry** [Modorganizer2/modorganizer#359]
# The problem

When I try to create a new instance for Skyrim, it still has the DLC for Fallout 4 showing, and I can't figure out how to change it properly.

**Comment by Silarn** [comment]
You haven't really provided much info. The top left button changes your instance. If you have a "fallout 4" instance created already but it's the wrong game, then you must have selected the wrong game directory when creating the instance. Use the manage instances option to delete it and then recreate it while choosing the correct game directory. Alternatively you can edit the modorganizer.ini in that instance directory and make sure it specifies the correct directory and game.

**Comment by Al12rs** [comment]
Make sure to have the latest version of Mo2 as in older versions you if you selected the same instance name (I assume you simply select Skyrim from the drop-down) as an existing instance it would simply open that one. And you currently have an instance called Skyrim that is bound to Fo4. You can actually type in any name for the instance
