### ISSUE TITLE
Archives Tab MO Managed Archives Check Box

### ISSUE THREAD

**Issue by Manaroth** [Modorganizer2/modorganizer#363]
# The problem

I am using the STEP Extended Guide to setup Skyrim LE. I am using MO2 because MO v1.3.11 started having issues connecting to nexusmods and either your Github or MO2 nexus page said MO2 v2.1.3 would work with LE too not just SSE. The problem I came across is near the end of the Skyrim LE STEP Extended guide it says to go to the archive tab tick the have MO manage archives box for about 7 mods. There is no MO Managed Archives Box to tick in the Archives Tab.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 1.3.11?
* Desktop OS/version used to run Mod Organizer: Windows 10

**Comment by Silarn** [comment]
MO2 currently does not and may never have archive management in the way MO1 did, though showing archive file conflicts is in the works.

I suggest finding a guide for MO2, such as tucoguide or the video series by GamerPoets.
