### ISSUE TITLE
Renaming a plugin from outside MO2 and then double clicking on the containing mod causes MO2 to crash.

### ISSUE THREAD

**Issue by Al12rs** [ModOrganizer2/modorganizer#364]
# The problem

Open Mo2, open a mod containing an esp in explorer,
while Mo2 is still open rename the esp to another esp name,
bring Mo up again and double click on the mod containing the changed esp,
Mo2 will freeze and crash.

I did not test too extensively so the condition for the crash could be a little more vague or more specific.

# Environment

* Mod Organizer Version that exhibits the issue:2.1.4 devbuild and 2.1.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:win10

Easier to reproduce than to upload logs or dumps.

**Comment by isanae** [comment]
Not reproducible anymore.
