### ISSUE TITLE
Modifying Overwrite Path Triggers Problem Indicator

### ISSUE THREAD

**Issue by StormFX** [ModOrganizer2/modorganizer#37]
Just thought I'd let you know that if you modify the overwrite directory path or the base path, it triggers a "problem" stating that there's something in the overwrite directory despite that directory being empty.

Update: It seems that directory has to exist in the default location (%appdata%/local/mod organizer/<game>. The notification only appears if you remove the original directory. So it's probably not an issue for most users. I only found it because I'm a bit OCD about empty directories. :p

**Comment by Silarn** [comment]
I'll have to check this. It seems to work relative to the base game directory but may be broken with a completely custom path. Which should be an easy fix.

**Comment by Al12rs** [comment]
I can't seem to reproduce apart for a brief problem indication that goes away restarting Mo. I would consider this very low priority for now.

**Comment by Al12rs** [comment]
Closing for organization purposes please reopen if you can still reproduce.
