### ISSUE TITLE
Can't find Fallout 4 in Mod Organizer 2

### ISSUE THREAD

**Issue by Marcy666Tepes** [Modorganizer2/modorganizer#376]
# The problem

So, i started using MO2 less than a year ago, maybe. I was using it only on Fallout 4. At some point, i no longer could play fallout with it. Now i reinstalled it, and it can't find Fallout 4, only Skyrim, Oblivion, Fallout 3 and FNV. What can i do? i reinstalled Fallout4 several times, but still no use...

# Environment

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 7

**Comment by Silarn** [comment]
Run the launcher once, mo2 needs your registry entry to locate the game.
