### ISSUE TITLE
Skyrim SE not recognising mods, but LOOT does

### ISSUE THREAD

**Issue by isaaclch** [Modorganizer2/modorganizer#378]
# The problem
When I launch Skyrim SE, I receive a warning message for "This save relies on content......" but when I load LOOT/SSEEdit the problem does not arise. Also, my Skyrim is a cracked version, however, this problem did not arise until today (25-5-18) and I have over 200 hours gameplay already. 

# Environment
MO2 2.1.3
2.1.1 and 2.1.2 did not display any problems
Windows 10 Pro Version 1709 
OS Build 16299.431

**Comment by Silarn** [comment]
You can post your USVFS logs as requested, but if it's a VFS conflict with your crack there's really nothing we can do about it.

**Comment by Silarn** [comment]
You can substitute the usvfs files from an older build as well. You won't have some of the fixes we implemented in the latest version but I'd guess that's fine with you.

**Comment by isaaclch** [comment]
[usvfs-2018-05-25_16-44-41.log](https://github.com/Modorganizer2/modorganizer/files/2040214/usvfs-2018-05-25_16-44-41.log)

**Comment by Silarn** [comment]
18:45:25.527 [E] failed to hook NtOpenFile: RIP-relative addressing can't be relocated.
18:45:25.527 [E] failed to hook NtCreateFile: RIP-relative addressing can't be relocated.

This error indicates it's likely a conflict with the cracked exe.

**Comment by isaaclch** [comment]
Then is there anything I can do about this?

**Comment by Silarn** [comment]
Try USVFS files from the versions that were supposedly working, find an exe which doesn't conflict with USVFS.

**Comment by isaaclch** [comment]
Is there anywhere I could source those usvfs files?
