### ISSUE TITLE
Skyrim crashes when launched on MO2 even without Mods :(

### ISSUE THREAD

**Issue by BlasterIce** [Modorganizer2/modorganizer#380]
Have been using mod organizer 2 for about a day. At first, everything was fine but suddenly, Skyrim crashes at start up. I tried different Launchers such as the SKSE, Skyrim and Skyrim Launcher. All crashed. However, when I launched it without mod organizer it works. 
Now I have uninstalled all mods, reinstalled both skyrim and mod organizer 2. But even without any mods activated, Skyrim crashes when launched through Mod Organizer 2. Please help me. Ask for any information and I will try to provide it.

**Comment by BlasterIce** [comment]
This are the 2 logs generated when I launched it through MO2
[usvfs-2018-05-27_22-30-43.log](https://github.com/Modorganizer2/modorganizer/files/2043094/usvfs-2018-05-27_22-30-43.log)
[mo_interface.log](https://github.com/Modorganizer2/modorganizer/files/2043095/mo_interface.log)

**Comment by Silarn** [comment]
Your game path doesn't look like a typical Steam path (even for a separate download location). There are known problems with modified versions of the game that we can't fix.
