### ISSUE TITLE
MO2 crashes when redownloading or unpausing a mod download.

### ISSUE THREAD

**Issue by JDar2K** [ModOrganizer2/modorganizer#381]
# The problem
MO2 crashes when redownloading or unpausing a mod download.

# Environment
* Mod Organizer Version that exhibits the issue: 2.1.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.1.0
* Desktop OS/version used to run Mod Organizer: Windows 10 Home/Version 1803

# Details
After having my internet go down while downloading mods, I went to unpause them. Following the act, my MO2 crashed. I then went to redownload the mods and experienced the same problem. I've added a zip of my crash dump if that would help.

[ModOrganizer.exe-69088.zip](https://github.com/Modorganizer2/modorganizer/files/2043090/ModOrganizer.exe-69088.zip)

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/JDar2K/c774565b6f4ac0a6750701f84eee8d2d

## MO Interface
https://gist.github.com/JDar2K/d9afc9291aa2eea7f848a0d17f024a0f

**Comment by Al12rs** [comment]
Should be fixed in dev builds on discord, please check.

**Comment by JDar2K** [comment]
That seems to have worked!

**Comment by JDar2K** [comment]
But, now my downloads may not fully download.

**Comment by Al12rs** [comment]
Closing, there should be other open issues for the downloads getting stuck.
