### ISSUE TITLE
Unable to lock load order

### ISSUE THREAD

**Issue by aalt333** [Modorganizer2/modorganizer#382]
# The problem

Right-clicking on the .esp in the plugins pane brings up the menu and "lock load order" is available, but selecting it does nothing. The text file in the profile remains empty after selecting to lock.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): First time using MO2, haven't played since before it was released. 
* Desktop OS/version used to run Mod Organizer: Windows 10 Home version 1803

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/aalt333/b5d7dbcb7af5a213999777c53afe4bb2

## MO Interface
https://gist.github.com/aalt333/b17705b0e3bdeb1c3b8f2cf114105662

**Comment by LostDragonist** [comment]
This issue has been fixed in 2.1.4 dev builds.

**Comment by yonkiman** [comment]
I'm not sure it's completely fixed.  I used it to lock 4 ESP in order:
```
A.esp
B.esp
C.esp
D.esp
```
But after I ran Loot, the order became:
```
A.esp
B.esp
another.esp
C.esp
D.esp
```
They are still in the correct order, so maybe that's the way it's supposed to work.  But I didn't expect anything to be inserted into a locked group.

**Comment by Silarn** [comment]
It's fixed. This would be a related but different potential problem. But we would need much more specific info. There are reasons why this might happen that are legitimate.

**Comment by yonkiman** [comment]
I can live with it, it's not a problem in my case - would you like me to open a new issue (with more details) or drop it?

**Comment by aalt333** [comment]
Alright thanks, I'll keep an eye out for the 2.1.4 update then
