### ISSUE TITLE
Mod Organizer2, LOOT cant detect plugins.

### ISSUE THREAD

**Issue by Minafisto** [Modorganizer2/modorganizer#383]
Loot doesnt detect all my plugins. It worked like charm, but when i reinstall Skyrim/LOOT/MO the problem occurred. When i put mod in Skyrim DATA folder LOOT/Tes5edit, it works, so that must be something with Mod Organizer.

Basicly,  LOOT seems to detect only vanillia plugins (Skyrim, Update, HearthFires, Dragonborn, Dawngard). I tried to reinstall (with registry cleaning, manualy removing files from appdata). Did not help. 

After reinstall I launched vanillia skyrim to generate ini files (also I delete all registry files, and user metadata before reinstall).  Really don't know what caused problem. I just format my E disc (where i install skyrim, clean reinstall with Skyrim and all skyrim tolls eg. LOOT, MO2, Tes5edit, WyreBash etc.), and reinstall it. Before everything working good, strange. 

- LOOT Version: 0.12.5 (installer, i tried also dev build - did not help)
- Mod Organizer: 2.1.3 (also tried dev build)
- Windows 10, did not update my windows/ system/drivers. All i just did was format/and clean reinstall of Skyrim/Skyrim toolos.
- Tes5edit have same issue with Mod Organizer - detecting only vanilla plugins. 
- Skyrim Special Edition with latest patch 1.5.39

Loot Debug info:
https://pastebin.com/Q9Nt1raK

Mod Organizer log data:
https://pastebin.com/ceJjymGB

USVFS
Blank file

-----
 Mod Organizer path:
 C:/Users/Camilli/AppData/Local/ModOrganizer/SkyrimSE (tried to change it to ModOrganizer 
 folder/other folder, did not help.)
 %BASE_DIR%/downloads
 %BASE_DIR%/mods
 %BASE_DIR%/webcache
 %BASE_DIR%/profiles
 %BASE_DIR%/overwrite
---
LOOT path:
branch = "v0.10"
folder = "Skyrim Special Edition"
repo = "https://github.com/loot/skyrimse.git"
type = "Skyrim Special Edition"
registry = "Software\Bethesda Softworks\Skyrim Special Edition\Installed Path"    
name = "TES V: Skyrim Special Edition"
local_path = "" 
path = "E:\The Elder Scrolls V - Skyrim SE\"
master = "Skyrim.esm"

Before posting i search on google, lot of people had same issue, but i could find solution that works for me. I think its something with paths. Before it runs perfect, I even tried to change install folders to names that they had before reinstall, but did not helped.

**Comment by Zarggg** [comment]
Reboot your computer. The virtual file system is not activating properly, and a reboot is currently the only way to fix that.

**Comment by Al12rs** [comment]
usvfs blank means usvfs is no loading. Something is bloking it. Check antivirus or if windows is directly blocking the files. Make sure to reboot a couple of times and don't use ccleaner as it messes with usvfs

**Comment by octatone** [comment]
Seeing the same behavior launching LOOT v0.13.1 via MO v2.1.3 for Skyrim VR.  Only base game esm files are shown in loot. None of the 35 other mods installed show up.

**Comment by WayuAtLayer** [comment]
I had a similar issue, which was also compounded by the rest of MO cascading in a sort of waterfall of failure as after I was hit by the same LOOT issue, **all MO plugins** begun to fail one at a time.

However, it seems restarting my computer fixed this for some reason. I'm still not clear what happened, but I'd give it a shot.

**Comment by octatone** [comment]
> it seems restarting my computer fixed this for some reason.

Restarting my computer has no effect on LOOT showing my mods. It simply does not work.

@Al12rs how does ccleaner mess with usvfs, and how to restore functionality if you have used ccleaner recently?

**Comment by gerbilOFdoom** [comment]
I'm having the same issue. I did run ccleaner at some point in the recent past, although it doesn't seem to have broken the VFS entirely -- the game still loads with MO's plugins even though LOOT does not.

**Comment by octatone** [comment]
I had to run repair with https://go.microsoft.com/fwlink/?LinkId=746572 to get MO2 + LOOT working again.

**Comment by robinkooli** [comment]
Having the same problem.

**Comment by vsrnth** [comment]
Did someone get a fix or workaround for this issue?

Restarting the machine and MO2 is not helping. 
I even tried repairing VC++ as suggested, that too did not help.

**Comment by Al12rs** [comment]
Check your antivirus. If it blacklisted usvfs even if you disable it usvfs will still not work. You need to make sure it is not blocked or quarantined and disable antivirus before running Mo. This is assuming you already made sure to restart (and I don't mean turn off and on, literally you need to press the restart option) and checked if the usvfs files are not blocked by windows.

**Comment by robinkooli** [comment]
For me the fix was to enable both Windows Event Collector and Windows Event Log services, then restart PC.

**Comment by vsrnth** [comment]
It fixed itself on its own, I'm not sure what fixed it.

**Comment by Al12rs** [comment]
Will close for lack of response and inability to reproduce in a few days.
