### ISSUE TITLE
Missing Conlict Information

### ISSUE THREAD

**Issue by michaelco1964** [Modorganizer2/modorganizer#385]
# The problem

I just started using MO2 this past weekend.  It appears that MO2 is not fully recognizing conflicts.  The left-pane flag column will not display the appropriate flags for the conflicts nor are they being shown in the mod's information window.

# Environment

MO2 v2.1.3 Revision:886fb10
Running on Windows 7 64-bit

![image](https://user-images.githubusercontent.com/39751390/40694870-c37c62e4-637b-11e8-8e7f-ccc516870bc9.png)

**Comment by LostDragonist** [comment]
This was hashed out on discord.  michaelco1964 was expecting conflicts to be detected like MO1.  Conflicts between BSAs or between BSAs and loose files are not currently detected.  Conflicts within/between plugins are not detected.
