### ISSUE TITLE
nxmhandler.exe won't work with Vortex

### ISSUE THREAD

**Issue by SirCatInaHat** [ModOrganizer2/modorganizer#386]
# The problem

I would like to mention there seems to be an issue with the nxmhandler.exe and manually adding in Vortex to handle certain games like State of Decay, Adding vortex's exe manually isn't the issue but the "-d" that vortex itself adds when you let it handle nxm links causes the line to get removed when you close nxmhandler 

NOTE: This issue occurs even when Vortex doesn't handle nxm links

# Environment

* Mod Organizer Version that exhibits the issue: Version 2.1.3
* Desktop OS/version used to run Mod Organizer: Windows 10 Home edition 64bit

# Details

I'm not sure what Vortex needs that "-d" for but apparently it's important because adding just the executable works fine but it doesn't download and every time I add it in to the nxmhandler's list it just gets removed after I close it

**Comment by Silarn** [comment]
I think I did notice that when I was messing with it before. I think it happens when you reopen the nxmhandler dialogue but if you set the value and close it, it does work (or at least I seem to remember that being the case).

I'll investigate at some point.

**Comment by SirCatInaHat** [comment]
For me even that doesn't seem to work unless I am doing something wrong

**Comment by LostDragonist** [comment]
A quick test suggests that Vortex will register itself as the primary nxm handler, and re-register itself for every game, whenever it is opened.  This basically wipes out the nxmhandler.exe configuration.

**Comment by Silarn** [comment]
@LostDragonist That's pretty egregious but not really the same issue.

**Comment by Al12rs** [comment]
Fixed in: https://github.com/ModOrganizer2/modorganizer-nxmhandler/commit/e80abb25ab0743c422dce52b0ba3cb7e258321b6
