### ISSUE TITLE
Fnis not working

### ISSUE THREAD

**Issue by GalexPk** [Modorganizer2/modorganizer#388]
# The problem

FNIS suddenly stopped working, it says "ERROR(76): No se puede encontrar una parte de la ruta de acceso 'C:\Program Files (x86)\Steam\steamapps\common\Skyrim\data\tools\GenerateFNIS_for_Users\temporary_logs'."

# Environment

* v2.1.3
* MO
* win10

# Details

suddenly FNIS isnt working, happened after deleting the files generated in the OW after i uninstalled a mod that used those animations

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by Silarn** [comment]
I'm going to guess you are using redirected files but didn't disable your output mod before running FNIS. This will cause this to erase the local files which will tank your install. You will need to reinstall FNIS.
