### ISSUE TITLE
Assorted Feature Requests

### ISSUE THREAD

**Issue by Easykill** [ModOrganizer2/modorganizer#393]
I was asked to put this here on the Discord, though it doesn't seem to be a place for feature requests...

Edit by AL12: Changed to check list, going to update if somethings are done. Help wanted for most of these.

##Valid requests:
 
- [x]  Fixed width for download bars so they aren't jumping all over the place.
 
- [x]  Recognize bodyslide data as valid installation data, since you do for skyproc it seems. Probably other similar things too?
 
- [x]  Badly want a texture comparison feature/utility so I can compare conflicting textures easily and decide what I prefer. Even better if it could do meshes too, but not expecting that, just the raw textures would be nice.
 
- [ ]  Option to have the source file cloned to the downloads section in MO when installing from file? To allow reinstallation, easier file management.
 
- [ ]  FOMOD installer feature: click images for full size. Especially with textures, the imperfect compression is a pain.
 
- [ ] Improve detection of subfiles updates instead of just relying on the global version of the mod. (Check if the file has been moved to OldFiles or if it has been deleted)
 
- [ ]  I probably wouldn't use it, but I imagine some people would use reverse filters? Like, exclude Armor from view by double clicking the filter or something.
 
- [ ]  For the executable option "create files in mod instead of overwrite," allow searching by clicking and typing in the dropdown list instead of having to manually search through the alphabetical list.
 
- [ ]  Auto switch to newly created profiles. Some people may not like it, but I at least expected that behavior at first, and suffered when I realized.
 
- [ ]  An important thing is that I think MO should be able to handle mods that need to go in the base Skyrim folder.
 
- [ ]  Automatically handle mods from the same source when you endorse one of them, so they don't show the endorse flag.

- [ ]  It's obvious, but native bashed patch functionality would be cool.
 
- [ ]  Store chosen FOMOD/BAIN installation info in the mod information window somewhere. A flag would be too much, but it would be nice if there was a way to tell which mods had installation options that haven't been updated since the last time you made a change in MO as well. Best solution I can think of is for the installation formats to update to generate dependency lists that aren't just based on plugins. based on the chosen build and information input by the author. Doesn't seem likely.
 
- [ ] Change string "Use application's icon for shortcuts" to:  "Use application's icon for desktop shortcuts".
 
- [x]  Either widen the default window size to allow display of the entire "create files in mod instead of overwrite(*)" option, or just delete the "instead of overwrite" part. Hovertext covers that anyway.
 
- [x]  Make double clicking a mod on a specific part of a mod (version, category, flags) open its associated info tab, if applicable.
 
- [ ]  Support sorting by tag metadata instead of just the often vague and pigeonholed single categories nexus uses.
 
- [ ]  Have a separate overwrite for each profile, or have it as an option.
 
- [ ]  Change category tab hovertext from "Category of the mod" to "Primary category of the mod."
 
- [ ] If possible, have an option to delete the previous version of a download upon upgrade, to prevent buildup of outdated downloads. Checkbox for replace mod thing that offers to delete download file associated with the previous version? IDK.
 
##Needs clarification/don't know what you mean:

- [ ]  Ability to divide mods from the same nexus page into title and subtitle for easier organization. you can just write it out, but it would be an improvement for me who basically only uses the generated names because typing is a pain, then am confused at what "blah blah fix" is without context.
 
- [ ]  Ability to "attach" patches to their relevant mods like layer masks to layers in photoshop, for easier organization.
 
- [ ]  Not directly related to you guys, but one of the biggest things I could think of that would improve my mod management quality of life is the introduction of ini files for mcms such that default settings can be properly saved between games. I would worship you if you somehow made it happen.
- [ ]  A bunch of warnings pop up when checking if a mod file I created myself for overwrite junk has an update available. Seems like it should be skipped, as with manually installed mods. Just warnings though.
 

##Invalid unless reformulated or there are better ideas (I'm open to change this with good reasoning):
(many of these are competence of the stylesheet and not the code itself, it would be bad to enforce this and remove the abilities from the stylesheet.

- [ ]  Larger font option, because resembling a wall of text makes it harder to read stuff. Mighta just missed that option, but I did look.
 
- [ ]  More visible contrast between checked and unchecked boxes.
 
- [ ]  More visible contrast between downloaded and installed files.
 
- [ ] Give SKSE a proper icon, since it's so essential it may as well be part of your UI
 
- [ ]  Rework the black and white "content" icons that seem out of place and hard to distinguish compared to colourful ones.
 
- [ ]  If possible, trick the nexus into always saying "update available" for tracked files you don't currently have installed, so they're easier to spot. IDK how that works at all, probably a naive request.
 
- [ ]  Don't use green for version info of mods you chose "ignore update for," or add an icon. Or just add "clear version data" option to the relevant context window.
 
- [ ]  Since there's a lot of room and I had to reference the hovertext forever to remember their functions, couple top menu icons with simple text.
 
- [ ]  I'm not sure this is a good idea, but I noticed that my asset ordering was a mess because I only thought of load order. Perhaps add an option to sort asset priority on the premise that expected asset order matches load order? Would introduce at least some order to it.
 
- [ ]  Since you automatically include SKSE in the executables, automatically generate an "SKSE Logs" mod instead of sending them to Overwrite.
- [ ]  Not for me, but it might be good to add an option to straight up forbid(read: automatically delete) executables from writing to Overwrite.

**Comment by stavrossk** [comment]
Some good ideas you have here. Does anyone else think that it would be better for these requests to be broken/seperated into individual issues?

**Comment by AnyOldName3** [comment]
I think a start would be to change from the list being `-Item` it was edited to be `* Item` so that GitHub renders it as bullet points and gets the spacing nicer.

### Give SKSE a proper icon, since it's so essential it may as well be part of your UI.
This is SKSE's job. If they apply an icon to their `.exe` file, it will show up in MO.

### Recognize bodyslide data as valid installation data, since you do for skyproc it seems. Probably other similar things too?
BodySlide stuff is recognised if it's installed to the default location, so you're going to have to elaborate if this isn't happening for you.

### Either figure out how to pull correct version information from sub-files on the nexus, or keep version info for them blank, rather than needing to "ignore update" for them.
The Nexus gives us a version number for each download and the latest version number for each mod page and we do the best we can with that information. There's no way to check if an optional file has an update available and Mod Organizer isn't going to start second-guessing why people have multiple mods with the same Nexus ID, so we're not going to leave the version info blank for them.

### Badly want a texture comparison feature/utility so I can compare conflicting textures easily and decide what I prefer. Even better if it could do meshes too, but not expecting that, just that raw textures would be nice.
This has been a thing since MO1. If you look at the data tab on the right pane, you can preview textures and use the arrows to view alternate versions. You can also get this preview from the conflicts tab of a mod info dialogue.

### Option to have the source file cloned to the downloads section in MO when installing from file? To allow reinstallation, easier file management.
If you want this behaviour, it might be easier just to download files into MO's downloads directory.

### It's obvious, but native bashed patch functionality would be cool.
Mator Smash is the better tool these days. If you want it to be integrated, it should be possible to make a tool plugin that does it.

**Comment by Easykill** [comment]
**Give SKSE a proper icon, since it's so essential it may as well be part of your UI.**
That's... reasonable enough, though somewhat disappointing. I don't think they will.

**Recognize bodyslide data as valid installation data, since you do for skyproc it seems. Probably other similar things too?**
IDK if it's default, but it works like this but is labelled as empty: https://i.imgur.com/5HN4slP.png

**Either figure out how to pull correct version information from sub-files on the nexus, or keep version info for them blank, rather than needing to "ignore update" for them.**
That's a shame. I can only hope they start to include more granular data, since Vortex will probably need it too anyway.

**Badly want a texture comparison feature/utility so I can compare conflicting textures easily and decide what I prefer. Even better if it could do meshes too, but not expecting that, just that raw textures would be nice.**
That's embarrassing. 

**Option to have the source file cloned to the downloads section in MO when installing from file? To allow reinstallation, easier file management.**
That's kinda a pain, unless I can download through MO itself, in which case autodownloading into its folder would be fine. My idea was kind of inelegant though. How about changing the workflow such that  instead of "install mod from file" it's "import mod file" and you install it from the downloads pane as per usual after? It's an extra step, but enforces more uniformity.

**It's obvious, but native bashed patch functionality would be cool.**
I haven't really tried Mator Smash yet, but I'm willing to if it reduces the number of separate apps I need to run.

**Comment by Al12rs** [comment]
`What does "Use application's icon for shortcuts" option even do, given it seems to do that already? Beats me, so include a hovertext like with the other options.`
This is for the desktop shortcuts. If you create a desktop shortcut of a program from within Mo2 it will have the Mo2 icon, the option allows you to use the original icon instead.

**Comment by AnyOldName3** [comment]
Annoyingly, enabling that setting for one of the autodetected applications (such as the game itself or the script extender) makes it forget that the application was autodetected. I can't remember what specifically, but this has caused me some kind of bother before. Maybe something like updating something while the setting was set made a duplicate entry get added. 

A related annoyance is the not-all-script-extenders-having-an-icon one. I've had a couple of thoughts about that which aren't as invasive as automatically assigning them a custom one. We could add a checkbox next to the 'use applications

**Comment by Al12rs** [comment]
Merged the valid entries into #464 for organization.
