### ISSUE TITLE
Mods Refuse to be Removed

### ISSUE THREAD

**Issue by Rhaevyn** [Modorganizer2/modorganizer#394]
# The problem
I removed a handful of mods on a new profile I just created and they persist in showing up in game.

I have removed them from the Mods folder, I even removed the zips in the Downloads folder.  I removed the names of the mods in the plugins.txt (the AppData one) and when all that failed, I sent every FO4 related folder to my external drive, reinstalled the game, and they are still showing up!  I have no clue what's going on.  

# Environment ?

* Mod Organizer Version that exhibits the issue:  2.1.3
* Last Mod Organizer Version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Win 10 Pro 64 bit

**Comment by Silarn** [comment]
You sure you don't have them installed to Data from a previous mod
manager?

**Comment by Rhaevyn** [comment]
I don't use another mod manager.  And there are only three mods that had to be installed in data, the rest all go into MO2 Mods folder, this is why this makes no sense.  Is it because the profile I created is a new named profile that I cloned from the "Default"?  I noticed that the changes I made on the new profile also changed my Default profile, so I know I'm missing something.  Maybe I need to reinstall MO2 but having to reactivate and rearrange my load order all over again... again, is making my head hurt hhee

**Comment by Silarn** [comment]
By 'showing up in game' do you mean those mods are actually loaded and visible while playing? If MO2 doesn't show any mods in the list and the game's data folder is empty then it's simply not possible for those mods to exist. However, lots of things mods do are saved into your savegame (this is called a dirty save). Once certain records are saved in your save file, they're pretty much permanent until you start a new game. (You can use some tools to clean certain records but it's very difficult to return to a clean state.)

You can always use the directory button in MO2 to open the game location and MO2 directories to verify you're actually deleting things from the correct location.
