### ISSUE TITLE
SkyrimSE+SKSE64, when launched from MO2, sees no mods (not even Skyrim.esm and the DLCs)

### ISSUE THREAD

**Issue by fefe17** [Modorganizer2/modorganizer#395]
This is the latest public version of Windows 10 with SkyrimSE+SKSE64 and MO 2.1.3.
I have always used NMM because it worked, but it has gotten really flaky recently so I attempted to switch to MO2.

Installed it, ran it, it found all my mods, installed another mod, clicked Run (SKSE selected as run method)
SkyrimSE starts, music plays, all looks good. So I select Continue.
I get a popup from SkyrimSE that plugins are missing, and I get the top of the list of missing modules, and it contains everything, basically. Starts with Skyrim.esm, then dawnguard.esm, etc. Can't find anything. I click OK and Skyrim crashes.

How can I debug this?

**Comment by jarrard** [comment]
I think I have this issue also. (fallout4)

I went to _C:\Users\Riddick\AppData\Local\ModOrganizer\Fallout 4\logs_  and noticed something alarming.

[E] failed to hook NtQueryDirectoryFileEx: No Error

This would lead me to believe the usvfs ultimately can't function, this sounds pretty important.

**Comment by Al12rs** [comment]
@jarrad that is not your problem if you are using a version of Mo2 later than 2.1.2 and a version of Windows older than win 10 1803. That version of Windows has a new ntquerydirectoryfile function that usvfs needs to hook, if that function does not exist (because you are on an older version of Windows) then it will fail to hook it with no error

**Comment by jarrard** [comment]
Was pretty sure I ran windows update recently. I will check again.

**Comment by Project579** [comment]
You are still very much behind with updates 1607 was released last year.

**Comment by Silarn** [comment]
1607 was released in July 2016 (16)(07). There are sometimes problems with older versions of Windows 10 though it's not clear why. There was a known issue with 1703, and it's possible older versions could be affected as well. Versions from 1709 onward are known to work.

**Comment by Silarn** [comment]
You didn't post your logs but this could also come down to the old CCleaner / windows event log problem.

**Comment by fefe17** [comment]
Any recommendations for me?
I'm running the Windows version that came out a couple of weeks ago, fall creator's update or whatever it is called. I don't even know where to start debugging this. Any hints would be appreciated!

**Comment by fefe17** [comment]
Uh, excuse me? Someone hijacked my bug report here.
None of the banter applies to my bug.
Please reopen.

**Comment by Al12rs** [comment]
@fefe17 come to discord and you should be able to get it fixed. It's either AV or event logs not working. We have the complete list on discord  https://discord.gg/cYwdcxj
