### ISSUE TITLE
Unable to add mods in MO 2 for SSE

### ISSUE THREAD

**Issue by TQWorld** [Modorganizer2/modorganizer#396]
Hey all,

I took a break from playing Skyrim SSE w/MO2 for a few months (last played mid-Feb) and tried getting back into it yesterday and discovered I am unable to install mods. What triggered this was FNIS would throw an array error. During troubleshooting, I discovered that I am unable to install any mods - I receive "No game data on top level" warning even after selecting the data folder which normally changes the text to "Looks good."

I went back to Oldrim and MO1 and I am also seeing the "No game data on top level" warning.

Things I've tried which have had no impact:
Turned off all of the Windows 10 Game Mode options. 
Rebooted. 
Set MO to run as admin.
Reinstalled MO 2
Upgraded to MO 2 v2.1.3

Im guessing this is due to a Win10 update because nothing else has changed. I am currently on: Win 10 64-bit 1803 (Build 17134.48)

Any suggestions/recommendations would be appreciated.

**Comment by Al12rs** [comment]
Please reach out to the discord server if you still have problems https://discord.gg/5tCqt6V
Closing this for cleanup and frankly no idea how that could be MO2 fault. Probably some folder set as read only or windows bugging out on you.
