### ISSUE TITLE
MO v2.1.3 stopped connecting to Nexus a few days back

### ISSUE THREAD

**Issue by michaelco1964** [Modorganizer2/modorganizer#397]
I did not make any changes to MO2, but just recently it was not connecting to Nexus.  I was wondering if anyone can look at the startup log for me:

20:33:24 [W] libeay32.dll already loaded?!
20:33:24 [W] ssleay32.dll already loaded?!
20:33:24 [D] ssl support: 1
20:33:24 [D] data path: C:/Users/Owner/AppData/Local/ModOrganizer/SkyrimSE
20:33:24 [D] Working directory: O:\games\Steam\steamapps\common\ModOrganizer2
20:33:24 [D] Loaded settings:
20:33:24 [D]   base_directory=O:/games/Steam/steamapps/common/ModOrganizer2/SkyrimSE
20:33:24 [D]   compact_downloads=true
20:33:24 [D]   crash_dumps_max=5
20:33:24 [D]   crash_dumps_type=1
20:33:24 [D]   display_foreign=true
20:33:24 [D]   force_enable_core_files=true
20:33:24 [D]   hide_unchecked_plugins=false
20:33:24 [D]   language=en
20:33:24 [D]   load_mechanism=0
20:33:24 [D]   log_level=1
20:33:24 [D]   meta_downloads=false
20:33:24 [D]   nexus_login=true
20:33:24 [D]   nmm_version=0.65.5
20:33:24 [D]   offline_mode=false
20:33:24 [D]   style=
20:33:24 [D]   use_prereleases=false
20:33:24 [D]   use_proxy=true
20:33:24 [D] initializing core
20:33:24 [D] usvfs log messages are written to C:/Users/Owner/AppData/Local/ModOrganizer/SkyrimSE/logs/usvfs-2018-06-08_02-33-24.log
20:33:24 [D] Initializing VFS <mod_organizer_instance, 1, 1, C:/Users/Owner/AppData/Local/ModOrganizer/SkyrimSE/crashDumps>
20:33:24 [D] initialize plugins
20:33:24 [D] looking for plugins in O:\games\Steam\steamapps\common\ModOrganizer2\plugins
20:33:24 [D] loaded plugin "bsa_extractor.dll"
20:33:24 [D] loaded plugin "check_fnis.dll"
20:33:24 [D] loaded plugin "diagnose_basic.dll"
20:33:24 [D] loaded plugin "game_fallout3.dll"
20:33:24 [D] loaded plugin "game_fallout4.dll"
20:33:24 [D] loaded plugin "game_fallout4vr.dll"
20:33:24 [D] loaded plugin "game_falloutNV.dll"
20:33:24 [D] loaded plugin "game_morrowind.dll"
20:33:24 [D] loaded plugin "game_oblivion.dll"
20:33:24 [D] loaded plugin "game_skyrim.dll"
20:33:24 [D] loaded plugin "game_skyrimse.dll"
20:33:24 [D] loaded plugin "game_skyrimvr.dll"
20:33:24 [D] loaded plugin "game_ttw.dll"
20:33:24 [D] loaded plugin "inibakery.dll"
20:33:24 [D] loaded plugin "inieditor.dll"
20:33:24 [D] loaded plugin "installer_bain.dll"
20:33:24 [D] loaded plugin "installer_bundle.dll"
20:33:24 [D] loaded plugin "installer_fomod.dll"
20:33:24 [D] loaded plugin "installer_manual.dll"
20:33:24 [D] loaded plugin "installer_ncc.dll"
20:33:24 [D] loaded plugin "installer_quick.dll"
20:33:24 [D] loaded plugin "pyCfg.py"
20:33:24 [D] loaded plugin "plugin_python.dll"
20:33:24 [D] loaded plugin "preview_base.dll"
20:33:24 [D] no plugin splash
20:33:24 [D] managing game at O:\games\Steam\steamapps\common\Skyrim Special Edition
20:33:24 [D] setting up configured executables
20:33:24 [D] configured profile: Testing
20:33:24 [D] initializing tutorials
20:33:24 [D] localization file qt_en not found
20:33:24 [D] localization file qtbase_en not found
20:33:24 [D] localization file organizer_en not found
20:33:24 [D] localization file bsa_extractor_en not found
20:33:24 [D] localization file check_fnis_en not found
20:33:24 [D] localization file diagnose_basic_en not found
20:33:24 [D] localization file game_fallout3_en not found
20:33:24 [D] localization file game_fallout4_en not found
20:33:24 [D] localization file game_fallout4vr_en not found
20:33:24 [D] localization file game_falloutNV_en not found
20:33:24 [D] localization file game_morrowind_en not found
20:33:24 [D] localization file game_oblivion_en not found
20:33:24 [D] localization file game_skyrim_en not found
20:33:24 [D] localization file game_skyrimse_en not found
20:33:24 [D] localization file game_skyrimvr_en not found
20:33:24 [D] localization file game_ttw_en not found
20:33:24 [D] localization file inibakery_en not found
20:33:24 [D] localization file inieditor_en not found
20:33:24 [D] localization file installer_bain_en not found
20:33:24 [D] localization file installer_bundle_en not found
20:33:24 [D] localization file installer_fomod_en not found
20:33:24 [D] localization file installer_manual_en not found
20:33:24 [D] localization file installer_ncc_en not found
20:33:24 [D] localization file installer_quick_en not found
20:33:24 [D] localization file plugin_python_en not found
20:33:24 [D] localization file preview_base_en not found
20:33:24 [D] localization file pyCfg_en not found
20:33:24 [D] loaded language en
20:33:25 [D] interface Local Area Connection seems to be up (address: fe80::6970:8543:316b:ad74%ethernet_6)
20:33:25 [D] localization file bsa_extractor_en not found
20:33:25 [D] localization file check_fnis_en not found
20:33:25 [D] localization file diagnose_basic_en not found
20:33:25 [D] localization file game_fallout3_en not found
20:33:25 [D] localization file game_fallout4_en not found
20:33:25 [D] localization file game_fallout4vr_en not found
20:33:25 [D] localization file game_falloutNV_en not found
20:33:25 [D] localization file game_morrowind_en not found
20:33:25 [D] localization file game_oblivion_en not found
20:33:25 [D] localization file game_skyrim_en not found
20:33:25 [D] localization file game_skyrimse_en not found
20:33:25 [D] localization file game_skyrimvr_en not found
20:33:25 [D] localization file game_ttw_en not found
20:33:25 [D] localization file inibakery_en not found
20:33:25 [D] localization file inieditor_en not found
20:33:25 [D] localization file installer_bain_en not found
20:33:25 [D] localization file installer_bundle_en not found
20:33:25 [D] localization file installer_fomod_en not found
20:33:25 [D] localization file installer_manual_en not found
20:33:25 [D] localization file installer_ncc_en not found
20:33:25 [D] localization file installer_quick_en not found
20:33:25 [D] localization file plugin_python_en not found
20:33:25 [D] localization file preview_base_en not found
20:33:25 [D] localization file pyCfg_en not found
20:33:25 [D] reading save games from C:/Users/Owner/Documents/My Games/Skyrim Special Edition/Saves
20:33:25 [D] displaying main window
20:33:25 [D] O:\games\Steam\steamapps\common\ModOrganizer2\SkyrimSE\profiles\Testing\modlist.txt saved
20:33:27 [D] network error 99
20:33:27 [C] uncaught exception in handler (object , eventtype 43): Network failed: Proxy connection refused
20:33:27 [C] uncaught exception in handler (object , eventtype 43): HTTP Status 0: 
 [D]

**Comment by vsrnth** [comment]
These are the logs after I tried downloading from Nexus by clicking on the NMM button.

20:40:01 [D] C:\Modding\Skyrim Mods\MO\profiles\Default\modlist.txt saved
20:40:02 [D] update available: 2.1.2 -> 2.1.3
20:40:10 [D] Download started
20:40:10 [D] download requested: nxm://SkyrimSE/mods/16190/files/49843
20:40:10 [D] add nxm download: nxm://SkyrimSE/mods/16190/files/49843
20:40:10 [C] request (http://nmm.nexusmods.com/skyrimspecialedition/Files/49843/?game_id=1704) error: Host nmm.nexusmods.com not found (3)
20:40:10 [W] request failed: Host nmm.nexusmods.com not found
20:40:10 [D] Failed to request file info from nexus: Host nmm.nexusmods.com not found

**Comment by vsrnth** [comment]
I think it has something to do with download link being changed to this?

http://filedelivery.nexusmods.com/1704/SMIM%20SE%202-07-659-2-07.7z?fid=32625&ttl=1529597246&ri=8192&rs=8192&setec=b95c248fda6ac25cd4e0761e1ccc1b7c

When I try to ping nmm.nexusmods.com I get a 404
ping nmm.nexusmods.com
Ping request could not find host nmm.nexusmods.com. Please check the name and try again.

**Comment by Al12rs** [comment]
Please reach out to the discord server if you still have problems https://discord.gg/5tCqt6V
This should be fixed and if not you will get help there.
