### ISSUE TITLE
Rewrite installer and remove need download requirements

### ISSUE THREAD

**Issue by LePresidente** [ModOrganizer2/modorganizer#399]
This is a tracking issue for the new Wix Installer.

Main work will be done on my branch for the moment 
https://github.com/LePresidente/modorganizer-WixInstaller

Main changes that will be done

- combine everything into one installer, and remove the download dependencies
- Build installer using cmake and intergrate into umbrella
- More to be added

Limitation of Installer

1.  It will only allow you to install to one location, you cant have multiple installs (If you want more locations use the standalone zip file)

**Comment by LostDragonist** [comment]
[MO v2.1.6](https://github.com/ModOrganizer2/modorganizer/releases/tag/v2.1.6) has been released with the new installer and this issue can probably be closed

**Comment by LePresidente** [comment]
Closing due to it being completed.
