### ISSUE TITLE
Just a typo is all

### ISSUE THREAD

**Issue by MeaKyori** [Modorganizer2/modorganizer#401]
Found a small typo in the installer. On the description for the start menu option, it says starmenu. Not a big deal, just thought I'd let you know!

**Comment by Al12rs** [comment]
Where is this exactly? Can you post a pic?

**Comment by MeaKyori** [comment]
Oops, I already finished the install without screenshots. So I used the
installer on the Skyrim special edition version, and on the part where
you're choosing what to install (plugins and all that) there's a button
that says "startmenu". And in the description when you hover over that, it
says "starmenu" instead.

The point still gets across, I mean it isn't an issue per se, I just like
to help with typos/spelling/grammar/etc.

**Comment by Al12rs** [comment]
Since Lepresidente is working on a new installer I guess this will not be a problem once it's finished, thanks for letting us know anyway.
