### ISSUE TITLE
Mod Organizer 2 - SSE - Glitched main menu/CTD on New Game

### ISSUE THREAD

**Issue by TyphosTheD** [Modorganizer2/modorganizer#402]
When running the game from Mod Organizer 2, the main menu is missing the Skyrim logo, and there are various visual issues with the menu, eg., the "Mod Manager" section has a "$" in front of it. In addition, when I attempt to load or start a new game, I experience a CTD.

Version 2.1.3

I freshly installed MO2, freshly installed Skyrim SE, and the game ran. I installed SKSE64, and the game ran. I installed and modified Requiem files, including NIF Optimizer and other scripts according to the most recent guide for updating Requiem 1.9.4.1 for SSE, and that is where I started experiencing the issues.

I have tried disabling all of the plugins and mods, but to no avail, and need help determining where I went wrong in the process.

## USVFS
https://gist.github.com/TyphosTheD/4975decf7404dab6a00577d8484cc777

## MO Interface
https://gist.github.com/TyphosTheD/fdbdf4957a40dfdffaf2ec1c4540e046

**Comment by AsianTorde** [comment]
Did you ever find a solution to this problem? I have the exact same issue and cant' seem to fix it.

**Comment by TyphosTheD** [comment]
Asian,

I never figured out what exactly it was, but after completely erasing MO2, reinstalling to a separate directory from my game, it seems to have worked.

I think a setting from other mods changed something and caused the problem.

So that would be my suggestion.
