### ISSUE TITLE
Application load error: 3:0000065432

### ISSUE THREAD

**Issue by notkylewastaken** [Modorganizer2/modorganizer#403]
# Problem
Cannot seem to launch SSE on MO2, reinstalled SSE and installed SKSE64 even though there are no mods installed yet.

# Environment

* Skyrim Special Edition Mod Organiser v2.1.3
* Windows 10

# Details
Just installed SSE and immediately installed SKSE64 for future modding. Launches SSE on steam and works fine. Exit SSE. Installs a new profile for MO2 for SSE, tries launching SKSE through MO2 and got the error message: Application load error: 3:0000065432

Proceeds to reinstall SSE and MO2 twice followed by restarting my computer followed by angry hair pulling followed by disabling my antivirus followed by literally following everything that Google suggests me to do, followed by going on Reddit, seeking for help and then followed by coming on here to get help.

Any further details needed will be provided.

# Link to Mod Organizer logs, how do you find this?

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by LostDragonist** [comment]
Does SKSE64 work outside of MO2?

**Comment by notkylewastaken** [comment]
Yes, it works when launched from Steam and changing launch routes such as
SKSE, Skyrim Special Edition and Skyrim Special Edition Launcher from MO2
did not work at all.

**Comment by notkylewastaken** [comment]
Hey, thanks for the speedy reply but I just took the nuclear route, I
reformatted my PC. God knows I need it. I am just a bit sick and tired of
installing and reinstalling the games over and over for it to work. So I
will setup backup folders for both Fallout NV, 4 and Skyrim. Thanks for
your help man. I really appreciate it.
