### ISSUE TITLE
HTTP status 0

### ISSUE THREAD

**Issue by raw3868** [ModOrganizer2/modorganizer#404]
# The problem

error pops up every time I start MO2

# Environment

V2.1.3
Win10 1803

# Details

Still seems to work fine, just have to wait a minute or two for the error to pop up before starting a game.
Running Skyrim VR and FO4 VR

# Link to Mod Organizer logs

## USVFS
UCVFS logs are empty(0 bytes)

## MO Interface
[mo_interface.log](https://github.com/Modorganizer2/modorganizer/files/2094084/mo_interface.log)

**Comment by Al12rs** [comment]
Maybe related to missing internet connection. Needs testing on new API build.

**Comment by LostDragonist** [comment]
This has been fixed by https://github.com/ModOrganizer2/githubpp/commit/528fb775c12d6c7554c35b00524af7b9489b27fd and https://github.com/ModOrganizer2/modorganizer/commit/09a68079bb9ac083bd060b1e75bf329917a7d888.  Dialogs will no longer pop up regarding uncaught exceptions in the GitHub API code.

**Comment by Al12rs** [comment]
2.2.0 released on nexus
