### ISSUE TITLE
CTD on multiple Query Info actions

### ISSUE THREAD

**Issue by RealAntithesis** [ModOrganizer2/modorganizer#406]
# The problem
When attempting to Query Info for a download when an existing Query hasn't yet finished, MO will crash. This has been an issue for a number of versions for a while now, and is still present in MO 2.1.3.

# Environment
* Mod Organizer Version that exhibits the issue: 2.1.3 and earlier.
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): don't know.
* Desktop OS/version used to run Mod Organizer: Win 10 64 (latest build as at 14.06.18)

# Link to Mod Organizer logs
## USVFS
https://gist.github.com/RealAntithesis/6603ef3889ef198a054b11fe821cec64#file-usvfs-2018-06-14_11-15-28-log

## MO Interface
https://gist.github.com/RealAntithesis/5a61dd5a315a205cee20bf1274f503d5#file-mo_interface-ctd-log

**Comment by gerbilOFdoom** [comment]
This may also be involved in an issue where resuming a paused download causes a crash.

**Comment by Al12rs** [comment]
@RealAntithesis can you or anyone else still reproduce? I can't on my end

**Comment by Al12rs** [comment]
I'm not able to reproduce on newest builds. Please reopen if this isn't true for you.
