### ISSUE TITLE
Localisation Errors

### ISSUE THREAD

**Issue by MichaelDevers** [Modorganizer2/modorganizer#408]
Getting constant errors in the log window when Mod Organizer 2 starts up. Unsure if this is a minor or major issue:

21:46:25 [D] Starting Mod Organizer version 2.1.3 revision 886fb10
21:46:26 [D] ssl support: 1
21:46:26 [D] data path: D:/Steam/Steam Games/steamapps/common/Skyrim Special Edition/Mod Organizer
21:46:26 [D] Working directory: D:\Steam\Steam Games\steamapps\common\Skyrim Special Edition\Mod Organizer\stylesheets
21:46:26 [D] Loaded settings:
21:46:26 [D]   compact_downloads=false
21:46:26 [D]   crash_dumps_max=5
21:46:26 [D]   crash_dumps_type=1
21:46:26 [D]   display_foreign=true
21:46:26 [D]   force_enable_core_files=true
21:46:26 [D]   hide_unchecked_plugins=false
21:46:26 [D]   language=en
21:46:26 [D]   load_mechanism=0
21:46:26 [D]   log_level=1
21:46:26 [D]   meta_downloads=false
21:46:26 [D]   nexus_login=true
21:46:26 [D]   nmm_version=0.65.2
21:46:26 [D]   offline_mode=false
21:46:26 [D]   style=Paper Dark by 6788-00.qss
21:46:26 [D]   use_prereleases=false
21:46:26 [D]   use_proxy=false
21:46:26 [D] initializing core
21:46:26 [D] usvfs log messages are written to D:/Steam/Steam Games/steamapps/common/Skyrim Special Edition/Mod Organizer/logs/usvfs-2018-06-19_20-46-26.log
21:46:26 [D] Initializing VFS <mod_organizer_instance, 1, 1, D:/Steam/Steam Games/steamapps/common/Skyrim Special Edition/Mod Organizer/crashDumps>
21:46:26 [D] initialize plugins
21:46:26 [D] looking for plugins in D:\Steam\Steam Games\steamapps\common\Skyrim Special Edition\Mod Organizer\plugins
21:46:26 [D] loaded plugin "bsa_extractor.dll"
21:46:26 [D] loaded plugin "check_fnis.dll"
21:46:26 [D] loaded plugin "diagnose_basic.dll"
21:46:26 [D] loaded plugin "game_fallout3.dll"
21:46:26 [D] loaded plugin "game_fallout4.dll"
21:46:26 [D] loaded plugin "game_fallout4vr.dll"
21:46:26 [D] loaded plugin "game_falloutNV.dll"
21:46:26 [D] loaded plugin "game_morrowind.dll"
21:46:26 [D] loaded plugin "game_oblivion.dll"
21:46:26 [D] loaded plugin "game_skyrim.dll"
21:46:26 [D] loaded plugin "game_skyrimse.dll"
21:46:26 [D] loaded plugin "game_skyrimvr.dll"
21:46:26 [D] loaded plugin "game_ttw.dll"
21:46:26 [D] loaded plugin "inibakery.dll"
21:46:26 [D] loaded plugin "inieditor.dll"
21:46:26 [D] loaded plugin "installer_bain.dll"
21:46:26 [D] loaded plugin "installer_bundle.dll"
21:46:26 [D] loaded plugin "installer_fomod.dll"
21:46:26 [D] loaded plugin "installer_manual.dll"
21:46:26 [D] loaded plugin "installer_ncc.dll"
21:46:26 [D] loaded plugin "installer_quick.dll"
21:46:26 [D] loaded plugin "pyCfg.py"
21:46:26 [D] loaded plugin "plugin_python.dll"
21:46:26 [D] loaded plugin "preview_base.dll"
21:46:26 [D] downloads after refresh: 11
21:46:26 [D] no plugin splash
21:46:26 [D] managing game at D:\Steam\Steam Games\steamapps\common\Skyrim Special Edition
21:46:26 [D] setting up configured executables
21:46:26 [D] configured profile: Default [Skyrim Special Edition]
21:46:26 [D] validating login cookies
21:46:26 [D] initializing tutorials
21:46:27 [D] localization file qt_en not found
21:46:27 [D] localization file qtbase_en not found
21:46:27 [D] localization file organizer_en not found
21:46:27 [D] localization file bsa_extractor_en not found
21:46:27 [D] localization file check_fnis_en not found
21:46:27 [D] localization file diagnose_basic_en not found
21:46:27 [D] localization file game_fallout3_en not found
21:46:27 [D] localization file game_fallout4_en not found
21:46:27 [D] localization file game_fallout4vr_en not found
21:46:27 [D] localization file game_falloutNV_en not found
21:46:27 [D] localization file game_morrowind_en not found
21:46:27 [D] localization file game_oblivion_en not found
21:46:27 [D] localization file game_skyrim_en not found
21:46:27 [D] localization file game_skyrimse_en not found
21:46:27 [D] localization file game_skyrimvr_en not found
21:46:27 [D] localization file game_ttw_en not found
21:46:27 [D] localization file inibakery_en not found
21:46:27 [D] localization file inieditor_en not found
21:46:27 [D] localization file installer_bain_en not found
21:46:27 [D] localization file installer_bundle_en not found
21:46:27 [D] localization file installer_fomod_en not found
21:46:27 [D] localization file installer_manual_en not found
21:46:27 [D] localization file installer_ncc_en not found
21:46:27 [D] localization file installer_quick_en not found
21:46:27 [D] localization file plugin_python_en not found
21:46:27 [D] localization file preview_base_en not found
21:46:27 [D] localization file pyCfg_en not found
21:46:27 [D] loaded language en

21:46:27 [D] localization file bsa_extractor_en not found
21:46:27 [D] localization file check_fnis_en not found
21:46:27 [D] localization file diagnose_basic_en not found
21:46:27 [D] localization file game_fallout3_en not found
21:46:27 [D] localization file game_fallout4_en not found
21:46:27 [D] localization file game_fallout4vr_en not found
21:46:27 [D] localization file game_falloutNV_en not found
21:46:27 [D] localization file game_morrowind_en not found
21:46:27 [D] localization file game_oblivion_en not found
21:46:27 [D] localization file game_skyrim_en not found
21:46:27 [D] localization file game_skyrimse_en not found
21:46:27 [D] localization file game_skyrimvr_en not found
21:46:27 [D] localization file game_ttw_en not found
21:46:27 [D] localization file inibakery_en not found
21:46:27 [D] localization file inieditor_en not found
21:46:27 [D] localization file installer_bain_en not found
21:46:27 [D] localization file installer_bundle_en not found
21:46:27 [D] localization file installer_fomod_en not found
21:46:27 [D] localization file installer_manual_en not found
21:46:27 [D] localization file installer_ncc_en not found
21:46:27 [D] localization file installer_quick_en not found
21:46:27 [D] localization file plugin_python_en not found
21:46:27 [D] localization file preview_base_en not found
21:46:27 [D] localization file pyCfg_en not found
21:46:27 [D] reading save games from E:/--- Libraries ---/Documents/My Games/Skyrim Special Edition/Saves
21:46:27 [D] displaying main window
21:46:27 [D] D:\Steam\Steam Games\steamapps\common\Skyrim Special Edition\Mod Organizer\profiles\Default [Skyrim Special Edition]\modlist.txt saved
21:46:28 [D] retrieving credentials
21:49:02 [D] save D:/Steam/Steam Games/steamapps/common/Skyrim Special Edition/Mod Organizer/webcache/cookies.dat
21:49:02 [D] D:\Steam\Steam Games\steamapps\common\Skyrim Special Edition\Mod Organizer\profiles\Default [Skyrim Special Edition]\initweaks.ini saved
21:49:02 [D] D:\Steam\Steam Games\steamapps\common\Skyrim Special Edition\Mod Organizer\profiles\Default [Skyrim Special Edition]\plugins.txt saved
21:49:02 [D] D:\Steam\Steam Games\steamapps\common\Skyrim Special Edition\Mod Organizer\profiles\Default [Skyrim Special Edition]\loadorder.txt saved
21:49:02 [D] D:\Steam\Steam Games\steamapps\common\Skyrim Special Edition\Mod Organizer\profiles\Default [Skyrim Special Edition]\lockedorder.txt saved
21:49:02 [D] Load Mechanism: Mod Organizer
21:49:02 [D] USVFS DLL Name: usvfs_x64.dll
21:49:02 [D] save D:/Steam/Steam Games/steamapps/common/Skyrim Special Edition/Mod Organizer/webcache/nexus_cookies.dat

**Comment by Silarn** [comment]
The application is programmed in English by default so we don't include en localization files. There's one dummy en file for the main application just so that english shows up in the language options.
