### ISSUE TITLE
SKSE and Skyrim SE CTD No Errors When Launched From Mod Organizer 2

### ISSUE THREAD

**Issue by greyhat111b** [Modorganizer2/modorganizer#409]
# The problem

SKSE and Skyrim SE (properly and completely cleaned with SSEEdit) crash to desktop with no errors when launched from Mod Organizer 2. This always happens with or without mods.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.3.0
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro 1803

# Details

SKSE and Skyrim SE (properly and completely cleaned with SSEEdit) crash to desktop with no errors when launched from Mod Organizer 2. This always happens with or without mods.
Resetting Skyrim SE's settings does not help.
Both SKSE and Skyrim SE launch with no issue if not launched from Mod Organizer 2.

# Link to Mod Organizer logs

## USVFS
[usvfs-2018-06-20_06-13-21.log](https://github.com/Modorganizer2/modorganizer/files/2118160/usvfs-2018-06-20_06-13-21.log)

## MO Interface
[mo_interface.log](https://github.com/Modorganizer2/modorganizer/files/2118162/mo_interface.log)

**Comment by Al12rs** [comment]
Create a new instance from the top left button and see if that works. If it does and you are sure there were no mods installed then it's probably a messed up INI setting.

**Comment by janissimsons** [comment]
I had the same issue and spent a few hours debugging. The problem is with MO2 default .ini files, they are missing a lot of data when compared with the .ini files generated by the game itself.
Especially the texture.bsa files are missing.
Devs should fix this.

**Comment by LostDragonist** [comment]
That's an interesting observation as MO2 doesn't provide any default INI files.  It grabs them directly from somewhere else, either the My Games dirdctory or the game dirdctory itself.   

I guess there's no guarantee that the default game INIs are actually valid...

**Comment by janissimsons** [comment]
Well, then I am not sure where MO2 got that .ini file from.. could it be that it grabbed it from the old version of skyrim (not SSE) ?

Anyhow, it would be nice if you added a validation for the [Archive] section in .ini files.
These crashes happen when textures are missing, this is the fixed part of ini file:

```
[Archive]
sResourceArchiveList=Skyrim - Misc.bsa, Skyrim - Shaders.bsa, Skyrim - Interface.bsa, Skyrim - Animations.bsa, Skyrim - Meshes0.bsa, Skyrim - Meshes1.bsa, Skyrim - Sounds.bsa
sResourceArchiveList2=Skyrim - Voices_en0.bsa, Skyrim - Textures0.bsa, Skyrim - Textures1.bsa, Skyrim - Textures2.bsa, Skyrim - Textures3.bsa, Skyrim - Textures4.bsa, Skyrim - Textures5.bsa, Skyrim - Textures6.bsa, Skyrim - Textures7.bsa, Skyrim - Textures8.bsa, Skyrim - Patch.bsa
bLoadArchiveInMemory=1
sArchiveToLoadInMemoryList=Skyrim - Animations.bsa
```

**Comment by greyhat111b** [comment]
I tried deleting MO2's SkyrimSE profile folder contents. The issue persists. It didn't even fetch or create new INIs.

**Comment by greyhat111b** [comment]
Creating a new instance doesn't help as well. I'm still getting the same problem.

**Comment by janissimsons** [comment]
@greyhat111b, navigate to C:\Users\<username>\AppData\Local\ModOrganizer\Skyrim\profiles\Default
open Skyrim.ini and make sure the [Archive] section is correct.

**Comment by greyhat111b** [comment]
This is what I found:

[Archive]
sResourceArchiveList=Skyrim - Misc.bsa, Skyrim - Shaders.bsa, Skyrim - Interface.bsa, Skyrim - Animations.bsa, Skyrim - Meshes0.bsa, Skyrim - Meshes1.bsa, Skyrim - Sounds.bsa
sResourceArchiveList2=Skyrim - Voices_en0.bsa, Skyrim - Textures0.bsa, Skyrim - Textures1.bsa, Skyrim - Textures2.bsa, Skyrim - Textures3.bsa, Skyrim - Textures4.bsa, Skyrim - Textures5.bsa, Skyrim - Textures6.bsa, Skyrim - Textures7.bsa, Skyrim - Textures8.bsa, Skyrim - Patch.bsa
bLoadArchiveInMemory=1
sArchiveToLoadInMemoryList=Skyrim - Animations.bsa
bInvalidateOlderFiles=1

**Comment by greyhat111b** [comment]
That's from C:\Users\[User_Name]\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default.
I don't have an MO2 profile for Oldrim. I removed it since Skyrim SE's release. I just started with MO2 last week. I've been using NMM before this.

**Comment by Al12rs** [comment]
Please reach out to the discord server if you still have problems https://discord.gg/5tCqt6V
Closing this for cleanup of old issues, let us know there.
