### ISSUE TITLE
Feature request: Allow rewritten files to remain in the original location

### ISSUE THREAD

**Issue by fireundubh** [Modorganizer2/modorganizer#41]
### Steps to Reproduce

1. Load a plugin into xEdit, Wrye Bash, or any other application through MO.
2. Modify the plugin.
3. Save and exit.

### Result

The plugin is modified and moved to the override folder.

### Notes

This is the most annoying behavior to me as a modder, and has been happening for a long time. I can see how this behavior could be useful, but I'd rather have an option to modify plugins in-place.

**Comment by tjax323** [comment]
I can confirm this happens to me, as well. Each and every time I modify or create a patch in xEdit.

**Comment by mlandstreet** [comment]
That is the expected behavior. You can drag the file back into the mod if it correct. If it is not you can delete it, rename a backup, and drag it into the mod.

**Comment by fireundubh** [comment]
> That is the expected behavior. You can drag the file back into the mod if it correct. If it is not you can delete it, rename a backup, and drag it into the mod.

An issue is not necessarily a bug. This behavior was introduced sometime ago but earlier versions of Mod Organizer allowed you to modify plugins in-place. It was a bad change.

**Comment by LePresidente** [comment]
When you edit a program in Mo2 eg. Adding xedit binary to start with mod organizer. Near the bottom there is a drop down box where you can set the output location for the files to a specific mod folder. Can you test to make sure it works. Sorry my hardware is acting up so Cant do a screenshot

**Comment by fireundubh** [comment]
> Near the bottom there is a drop down box where you can set the output location for the files to a specific mod folder. Can you test to make sure it works.

No, the file is still moved to the overwrite folder.

**Comment by fireundubh** [comment]
I'll add that the plugin location and header information is also not updated. In this example, I changed the author of the plugin to read "steve42" and the Origin should have changed to overwrite.

![2017-01-09 21_01_34](https://cloud.githubusercontent.com/assets/1261664/21794408/e7f62b06-d6ae-11e6-8340-7ff2949a5d77.png)

**Comment by MaddBomber83** [comment]
You'll need to modify the meta yourself; or delete it from the mods section and reinstall.  If that is still a no go then delete it from both the mods and downloads; then download it from nexus.

I wish they auto updated too.

**Comment by fireundubh** [comment]
> You'll need to modify the meta yourself; or delete it from the mods section and reinstall. If that is still a no go then delete it from both the mods and downloads; then download it from nexus.

Or restart MO. Restarting MO refreshes the plugin list properly.

**Comment by Al12rs** [comment]
This has been implemented as of usvfs 0.3 beta 5 that is available in #Builds on the discord channel.

**Comment by Silarn** [comment]
This is the new default behavior of mo2 at least until we come up with a feasible way to redirect directly written files.
