### ISSUE TITLE
Unable to download from Nexusmods using the NMM download button

### ISSUE THREAD

**Issue by vsrnth** [Modorganizer2/modorganizer#411]
# The problem
After upgrading to MO 2.1.2, I've not been able to download from Nexusmods using the NMM download button.

# Environment

* Mod Organizer Version that exhibits the issue: MO 2.1.2
* Desktop OS/version used to run Mod Organizer: Windows 10 64 bit

# Link to Mod Organizer logs
https://gist.github.com/vsrnth/b19921ebcc844af02cd80e424c235de9

**Comment by vsrnth** [comment]
I think it has something to do with download link being changed to this?

`http://filedelivery.nexusmods.com/1704/SMIM%20SE%202-07-659-2-07.7z?fid=32625&ttl=1529597246&ri=8192&rs=8192&setec=b95c248fda6ac25cd4e0761e1ccc1b7c`

When I try to ping nmm.nexusmods.com I get a 404
```
ping nmm.nexusmods.com
Ping request could not find host nmm.nexusmods.com. Please check the name and try again.
```

**Comment by Al12rs** [comment]
@vsrnth please make sure you have the latest version of MO2 installed before reporting issues.

**Comment by vsrnth** [comment]
my bad it worked once I moved MO 2.1.3
