### ISSUE TITLE
When Double Clicking on Mods Doesn't show Conflicts, Flags also not loading.

### ISSUE THREAD

**Issue by Brunnengee** [Modorganizer2/modorganizer#412]
Mod Organizer 2.1.3
Modded Game: Original Skyrim including DLCs

# The problem

When I double click on a mod in mod organizer the conflicts panes are empty and it doesn't let me click on any of the tabs at the top. Also none of the flags are loading in the main application pane. There seems to be no issue in downloading mods.

![mainpane](https://user-images.githubusercontent.com/40472104/41742689-c296bb92-756c-11e8-9c98-03a07900ea0a.jpg)

![modpane](https://user-images.githubusercontent.com/40472104/41742691-c541f528-756c-11e8-90de-3d4cda075440.jpg)

If anyone has any ideas please let me know.

Thanks.

**Comment by Al12rs** [comment]
The localisation errors can be ignored, can you show some pictures of the missing flags and the messed up information dialog?

**Comment by Brunnengee** [comment]
Ok I added some pictures

**Comment by Silarn** [comment]
Please watch this series to understand how MO2 works. You can't just use it on an existing install.

You're showing a bunch of unmanaged mods which means they were installed manually into the game's Data directory (or with another tool) and not via MO.

https://www.youtube.com/watch?v=DG3eqyNOByw
