### ISSUE TITLE
Can't move bold esps or esms in the load order and cannot lock the load order

### ISSUE THREAD

**Issue by oStarZ** [Modorganizer2/modorganizer#413]
# The problem

I remember being able to move bold esms and esps but I cannot now for some reason. I also can't lock the load order. It does nothing.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 10

# Details

The bold esms and esps will only move to a place next to a bold esm or esp.

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/oStarZ/14b3c3ff524c4e419fdf3b01ac3e88c0

## MO Interface
https://gist.github.com/oStarZ/72c7731b1c922d714723db012d049e73

**Comment by LostDragonist** [comment]
Bold plguins are masters.  Masters will be loaded first.  MO2 is attempting to show the true load order of the game instead of letting you set it to a fake load order.

Being unable to lock the load order is a bug introduced in 2.1.3 and will be fixed in 2.1.4.  If you require this feature, you may want to jump on Discord and grab the latest developmental build.

**Comment by oStarZ** [comment]
So it's not possible to move masters? The way MO wants it to be is not how my load order should be.

**Comment by LostDragonist** [comment]
There is little to no reason to move masters in the way you want.  If someone is telling you they should be like that, they are telling you incorrect information.

**Comment by oStarZ** [comment]
Ok, I am using a modlist. https://www.nexusmods.com/fallout4/mods/23556
So I guess everyone who used this has it wrong. So should I just move all my masters to the top?

**Comment by LostDragonist** [comment]
That guide assumes that you're using NMM which behaves exactly the same in this fashion.  The difference is that NMM will not tell you which ESP files are really masters.  For example, "Unofficial Fallout 4 Patch.esp" is a master that NMM will not move below non-masters.

As far as I can see, there is nothing in that guide that tells you to reorder your plugins.  You are supposed to install the mods in order and never touch anything.  NMM will automatically shunt the masters to the top.  Therefore, having all of your masters at the top is expected.  The guide just never really tells you that. 

If you feel this is wrong, please ask the author of the guide.  They are pretty responsive to questions on the Nexus page.

**Comment by oStarZ** [comment]
Alright thank you.

**Comment by Silarn** [comment]
MO's plugin order is dictated by how the game(s) actually load plugins. In general ESMs and ESM-flagged ESPs will always be loaded first. Most games will also load the 'core' plugin files automatically before other plugins. (SSE loads all DLC plugins and CC plugins before anything else, always). MO2 is merely replicating this behavior.
