### ISSUE TITLE
Merge Plugins problems

### ISSUE THREAD

**Issue by Project579** [Modorganizer2/modorganizer#417]
# The problem

Merge Plugins ( https://github.com/matortheeternal/merge-plugins ) cannot read the load order from MO2 always uses the global one also probably other thing don't work but i could not get over that. The program auto test says it has file access permissions but I really don't believe it.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.4 Dev Build 5
* Last Mod Organizer Version that did not exhibit the issue (if applicable): 1.3.11 (the original)
* Desktop OS/version used to run Mod Organizer: Windows 7

# Link to Mod Organizer logs

## USVFS

Empty

## MO Interface

https://gist.github.com/Project579/db0ccec63fac4560b723954064a1f5d2

**Comment by Project579** [comment]
Ok so after some time I managed to fix it, the problem was that my Merge Plugins was installed inside of the MO2 folder so the USVFS process was not spawning.

So lesson learned never put stuff inside of the folder where MO2 is installed.

**Comment by Silarn** [comment]
I'm not really sure why exactly that would cause a problem, but in general I wouldn't recommend installing another tool in MO2's own directory. Game tools were essentially designed to live in the game directory but other third party tools weren't really designed to live within MO2. You're just asking for conflicts that way.
