### ISSUE TITLE
FO4 updated and MO2 isn't working

### ISSUE THREAD

**Issue by QQinmyPillow** [Modorganizer2/modorganizer#418]
# The problem

When I try to load Fallout 4 through MO2, I receive this error message: "Steam is required to be running already to correctly start the game.  Should MO try to start steam now?"
I already have Steam running.  This only started right after FO4's newest patch.

If I hit "no", the game loads but to the windowed options menu (which it never did before) instead of starting the game immediately.

When I try to load my save FO4 warns me that the three mods I used on said save or no longer being used and it could effect my game.  So the mods no longer work.

# Environment

I use mods:
SurvivalOptions.esp
SurvivalXPgainof1x.exp
NPC's Use Grenades.esp
and something I dropped in my FO4 folder that enables achievements with mods.

OS: Windows 10

# Other

I'm a complete newb to modding so I have no clue what all these logs are that are needed.  Sorry, I can try figuring them out later tonight if need be.  If so please tell me so and I will.  Otherwise I hope you all know how to resolve these mod issues based on the FO4 update.  Thx for your time in advance!

**Comment by Project579** [comment]
Make sure that Steam sees your game and that it can launch it from the library.

**Comment by Project579** [comment]
Also make sure when you Run from MO2 you have selected the actual game and not the launcher.

**Comment by Silarn** [comment]
Even if you run the launcher it would still hook the game through the launcher. If you haven't already I'd suggest rebooting once as MO2 should be able to see the steam executable running but apparently can't, which is pretty odd.

**Comment by Zarggg** [comment]
This seems similar to a known bug (to me at least) with the Fallout Launcher. Try quitting and reloading Steam. If that doesn't work, try forcing Steam to launch with Administrative rights.

**Comment by QQinmyPillow** [comment]
Rebooted everything > Started Steam as 'Run as Admin' > MO2 still doesn't see Steam executable > Load FO4 through windowed options screen anyways > Try to load save > Game warns me that some objects may be missing due to my three mods no longer being available.

I'm uninstalling and reinstalling MO2, the Mods, and possibly even FO4 if the first two don't work.  I'll let you all know what I find.  Also, if anyone has any need for any specific logs, please state so and I'll try and gather that info for you.

**Comment by LostDragonist** [comment]
Uploading your logs would probably be a good idea.  At least your mo_interface.log and the most recent usvfs_xxx.log where this occurs.

**Comment by QQinmyPillow** [comment]
Reinstalling MO2 and/or changing the base directory fixed the issue.  Sorry to bother you all with my minor issue.  Thx for your time again folks!
