### ISSUE TITLE
MO2 Bandwidth Issue

### ISSUE THREAD

**Issue by IrishWarrior22** [Modorganizer2/modorganizer#420]
# The problem

I watch YouTube on my Xbox while using my laptop, and normally it runs hi-def videos perfectly. But lately it's been crappy, running at very low quality and stalling a lot, and the app itself takes longer to work and thumbnails sometimes don't load.

Just a few minutes ago I was watching a video and it was working fine, full resolution and no buffering, and the app was running smoothly, and MO2 was closed. As soon as I opened it up the video quality dropped noticeably and it started buffering after a few seconds before continuing at an even lower quality. Now the app itself is slow again.

I've had MO2 open almost constantly in the past few days, as I've been on a Skyrim binge, and without it open the app runs smoothly and the videos are at proper resolution, so that must be what's causing it.

# Environment

Mod Organizer 2 v2.1.3

Windows 10

**Comment by Project579** [comment]
Did you check if MO2 was downloading something? (using the Windows Task Manager or The Resource Monitor)

**Comment by Al12rs** [comment]
Will close for lack of response and inability to reproduce in a few days.
