### ISSUE TITLE
MO2 and FNIS Error 2012 (SSE) (FIXED)

### ISSUE THREAD

**Issue by SirenBrink** [Modorganizer2/modorganizer#421]
# Issue is fixed

# Details

I ended up manually adding ModOrganizer.exe and usvfs_x64.dll to the Allow list in Windows Firewall, and setting Mod Organizer's folder permissions to Full Control for all users. Restarting my PC afterwards and trying again fixed the issue.

**Comment by Project579** [comment]
Did follow the instructions on FNIS page, it has different procedure when using MO2, please tell me how you installed it, I need to know so I can be sure it's not a user error.

**Comment by SirenBrink** [comment]
* I tried installing FNIS normally into MO and running GenerateFNISforUsers as an executable.
* I tried installing FNIS outside of MO, into the game's directory, and then running via MO.
* I also tried using FNIS File Redirection.

All of these resulted in ERROR(2012): Could not generate: defaultfemale.hkx defaultmale.hkx 0_master.hkx

**Comment by Al12rs** [comment]
@SirenBrink the new processes (the windows that you mentioned) do run under the vfs just fine for me. 
Please could you provide your modorganizer logs like instructed in the issue template? Those are critical to understand what is going on and without it the report is useless. 
To access the logs you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed. https://cdn.discordapp.com/attachments/458597400638914563/458728891620524032/unknown.png

In addition to the logs I would also need a picture of the Fnis executable settings in Mo2 to see the paths and how it is setup. Please for the sake of resolving the issue execute tests without using the Fnis redirection feature for now.

**Comment by SirenBrink** [comment]
![0](https://user-images.githubusercontent.com/40726044/42136856-6ff8a8be-7d28-11e8-943d-693bd2f01503.png)

![1](https://user-images.githubusercontent.com/40726044/42136847-4566b1b8-7d28-11e8-8eac-fec90faa55f0.png)

![2](https://user-images.githubusercontent.com/40726044/42136865-9b52053c-7d28-11e8-9585-4acd03fde496.png)

**Comment by kiasta** [comment]
The fact you have to jump through so many hoops to install this Fore's shitty mod is ridiculous.

**Comment by Project579** [comment]
An automatic Plugin should be coming
