### ISSUE TITLE
Nexus Downloads return “empty response.”

### ISSUE THREAD

**Issue by IAmNotTheNSA88** [ModOrganizer2/modorganizer#425]
The problem
Nexus Downloads return “empty response.”

Environment

MO2 – 2.13
The last time MO2 worked for me was prior to the Nexus EU rule compliance changes. 

Details
Whenever I download a mod through MO2, the download fails to begin and I receive an error: 

“nexus error: empty response
Failed to request file info from nexus: empty response”

I can still install mods via manual download/MO2/Install new mod from archive, but I can neither see which mods need updated nor can I download them via the organizer. 

Link to Mod Organizer logs

https://gist.github.com/Cowgirl1988/3cd37e8b9bd1c604b72129c8e27dca30#file-logs

USVFS
https://gist.github.com/Cowgirl1988/4baf1b44e4faec153fed8bd9acb9e7a7#file-usvfs
 MO Interface
https://gist.github.com/Cowgirl1988/401f0d1db7907d2a9ad00a432236ba7e#file-gistfile1-txt

**Comment by Al12rs** [comment]
This should be fixed on newer versions, reopen the ticket if it isn't the case.
