### ISSUE TITLE
I lost everything....

### ISSUE THREAD

**Issue by Jack5600** [Modorganizer2/modorganizer#426]
# The problem
I was trying to install Sky ui and get skse to work on MO 2, when suddenly all my mods disappeared, all the DLCs included, I have attached a link to the youtube tutorial i was following along https://www.youtube.com/watch?v=gT0QNBsjViQ 

Briefly describe the issue you are experiencing (or the feature you want to see added to Mod Organizer). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our discord channel

# Environment
MO2 v2.1.3
Windows 10

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by Project579** [comment]
If you launch the game without MO does it work, do you have all the DLCs in the Data folder?

**Comment by LostDragonist** [comment]
Closing due to lack of user response.  There's not enough information available for this issue to be useful.
