### ISSUE TITLE
Creation kit changes do not appear in overwrite folder

### ISSUE THREAD

**Issue by jamesa82** [Modorganizer2/modorganizer#427]
# The problem

Hi,
I'm having a slight issue with using the creation kit to update oldrim esps to skyrim se. When i load up the esp (in this case the skyforge esp for aMidianBorn) and save it i.e no other changes than this, and close the CK nothing appears in the overwrite folder. However i believe the changes have occurred as when i load up the mod in ssedit it says its form is 44 not 43 like it would be on oldrim. Just a bit confused as to why a new esp was not created and added to my overwrite folder. Things like smashed/merged/bashed patches all work fine and appear in the overwrite folder but the CK changes do not, they are just automatically applied.
Was this an intended affect or has something gone wrong on my end?
Thanks in advance for any help you can give.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Mod Organizer: w10

**Comment by LostDragonist** [comment]
2.1.2 or 2.1.3 changed the behavior of how files were modified.  They'll be modified in place instead of moved to the overwrite folder.

**Comment by jamesa82** [comment]
Ah alright thanks for the response, I take it this means there are no problems with how MO 2 is operating then?

**Comment by Al12rs** [comment]
No problems there, that is expected behavior now.
