### ISSUE TITLE
MO2 failing to connect to Nexus during setup phase.

### ISSUE THREAD

**Issue by Amenshawn** [Modorganizer2/modorganizer#428]
# The problem

During initial setup of MO2, there is a failure to log in to my Nexus account.  It will reach the Nexus site, but fail to log me in, so I can't get any further into the set up to download a mod and select a server.

# Environment

MO2 version 2.1.2
This is my first attempt using MO2, so no prior data available for comparison.
Running Win10pro  1803

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by LostDragonist** [comment]
You need at least 2.1.3 to connect to the Nexus.  There's very little reason to use 2.1.2 at this time.
