### ISSUE TITLE
Oldrim Creation Kit Saving Script(s) Issue (Unable to create or write temporary file for compilation)

### ISSUE THREAD

**Issue by Haravikk** [ModOrganizer2/modorganizer#429]
# The problem

When running 32-bit Skyrim's Creation Kit in Mod Organizer 2, everything works fine except for saving/compilation of scripts which works once, and only once, without workaround before giving the following error:

`Unable to create or write temporary file for compilation`

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): MO1 did not exhibit this.
* Desktop OS/version used to run Mod Organizer: Windows 10 with all latest patches (as if I had a choice!)

# Details

Basic steps to reproduce go something like this:

1. Setup 32-bit Skyrim and its Creation Kit in Mod Organizer 2. In my case I have Skyrim with all DLC.
2. Setup a folder for a scripted mod that you'd like to work on. In my case I've used a small personal mod of mine entitled "Custom Greybeard Robes" that gives me access to, well, custom greybeard robes. All of its existing scripts etc. are stored within its own mod folder, and enabled within MO2.
3. Open the Creation Kit and set your mod's esp to be the active file.
4. Select any script within your mod, right-click and choose "Edit Source".
5. Make any minor change (e.g- add and then remove a space) and save, this should be successful.
6. Do the same again and save. This time you will get the error `Unable to create or write temporary file for compilation`. If you are editing a dialogue script you may get a variation mentioning the source file specifically, even though it's in fact the compiled file that didn't save (your source file will contain your changes as normal).
7. At this point it is no longer possible to save any scripts, requiring Creation Kit to be restarted, giving you another one, and only one, save attempt. It doesn't matter if the script compiles or not.

# Notes and Workarounds

The issue does not appear to be 32-bit/64-bit based, as I've tried both an unedited PapyrusCompiler.exe and one edited to run only in 32-bit mode, both are affected.

The issue appears to have something to do with the interaction between MO2's overwrite folder capturing newly saved files, and how papyrus scripts are saved. As a reminder, they are stored first into `Data/Scripts/Source/Temp`, then moved back into position.

I have discovered one workaround, which is to edit Creation Kit in the executables list and set it to store changed files directly into a specific mod's folder instead of the overwrite folder. This enables unlimited script saving, but of course requires the user to manage the save target carefully, either setting it before each launch of CK for a new mod, or I suppose if executable target folders are profile specific then a profile for each mod could be used (I haven't tried this yet).

# Link to Mod Organizer logs
* USVFS: [GIST](https://gist.github.com/Haravikk/e8f6c54549a514f1e4e1972b062e8180#file-gistfile1-txt)
   This log is following a reproduction as described above, and after closing MO2 afterwards.
* MO Interface: [GIST](https://gist.github.com/Haravikk/e00fb2c98c22b4d100f74d13929f1e6d#file-mo_interface-log)

**Comment by Haravikk** [comment]
Just an added note, but I've tested this against 2.1.4 dev build 6 as well and unfortunately it still occurs there as well, despite a few fixes to the virtual filesystem (one I believe was regarding backslashes, so I'd hoped it might be the cause as my Steam library is on its own partition).

However, I've found a cleaner workaround for the issue which is to create a new profile for each mod that I wish to edit; this allows me to set Creation Kit to save into the correct folder for each mod, avoiding this issue (and the need to move files from overwrite), with the side benefit of allowing me to load only the bare minimum into CK (I didn't think it was even capable of loading so fast!).

Still, it's an odd issue that could do with being investigated in case it indicates other possible issues with how the overwrite folder is handled.

**Comment by Project579** [comment]
Did you unpack your scripts from the .zip?

**Comment by Haravikk** [comment]
The main Skyrim ones? Yeah, so that's not the issue.

Like I say, I can edit my scripts just fine if I make my mod the target of Creation Kit in MO2's executables list, it's only when new files are being saved into Overwrite that there's a problem.

**Comment by Project579** [comment]
This could be a issue related to the vfs, Wrye Bash has a similar problem on my system only difference is that it creates the files in the real Data folder.

**Comment by Al12rs** [comment]
@Haravikk We released a version of Mo2 on discord with a fix to the VFS that could potentially fix this issue, could you please try it out?
https://discord.gg/MB3CyMH

**Comment by Haravikk** [comment]
I've tried this new version and it does indeed seem to have fixed this issue as I can no longer reproduce it all, thanks!

Excellent timing as well btw as I just started working on some of my mods again on my new gaming PC today, so I had everything setup and ready when I got the e-mail notification 😉

**Comment by Al12rs** [comment]
Awesome! Thanks for testing and the feedback!
