### ISSUE TITLE
MO2 Crashes a few seconds after I click on "install mods" button every time. 

### ISSUE THREAD

**Issue by ntblood** [Modorganizer2/modorganizer#430]
I've used the first MO extensively. My problem is in the subject heading here. 
Any ideas?
Thanks

**Comment by LostDragonist** [comment]
Without any information, I'm guessing that you're using MO 2.1.3 and your downloads are coming out to be 0 KB.  You could try changing your preferred server in the MO2 Nexus settings.  You could try grabbing the latest development build from Discord.

Otherwise, you'll need to provide the info in the issue template.  Or really any information at all.

**Comment by ntblood** [comment]
Yes on installer version #.
I already manually downloaded so I was clicking the from archive install button.
So I'd guess the server wouldn't matter (?). So no zero KB downloads.

**Comment by LostDragonist** [comment]
You're really not going to get any help if you don't post at least your mo_interface.log per the issue template.  A crash dump would be even better.  Look in your MO2 install folder for a "crashDumps" folder and "logs" folder.  They might also be in "C:\Users\<user>\ModOrganizer\<instance>\".

**Comment by ntblood** [comment]
Do you have a link to the developer version of MO2 on Discord, after a search I'm lost. 

There are no logs in my MO2 log folder, there is no "crashDumps" folder either. There is no ModOrganizer folder in C:\Users\<user>\      for me, nor in  C:\Users\<user>\Documents   

So I don't seem to have or can find what you're asking for from the look of it.

**Comment by LostDragonist** [comment]
Sorry, it should be C:\Users\\<user>\\AppData\Local\ModOrganizer\\<instance>\".

The discord is here: https://discord.gg/cYwdcxj.  The development builds are in #builds.  If you use one be sure to unblock the archive before you extract it.

**Comment by ntblood** [comment]
[mo_interface.log](https://github.com/Modorganizer2/modorganizer/files/2177746/mo_interface.log)
[usvfs-2018-07-09_18-00-34.log](https://github.com/Modorganizer2/modorganizer/files/2177747/usvfs-2018-07-09_18-00-34.log)

**Comment by LostDragonist** [comment]
Alright, next prediction:  You have a Dell or Alienware computer that has a program named Alien Respawn or Dell Backup and Recovery that you need to go update.  

If that's not it, the crashdump would really be helpful.  The development version of MO2 isn't likely to help any in this case.

**Comment by ntblood** [comment]
The developer version seems to do the same thing. Crash a second after I click "install mod from archive" (a moment after it brings up windows file explorer window.

**Comment by LostDragonist** [comment]
I can't help any further without the crash dump.  Your log says it's here: C:/Users/\<user>/AppData/Local/ModOrganizer/SE Instance/crashDumps.  Opening that in Visual Studio will more or less tell me exactly why it crashed.

**Comment by ntblood** [comment]
They're all .dmp files and won't upload here

**Comment by LostDragonist** [comment]
You should be able to attach them if you zip them up first.

**Comment by ntblood** [comment]
[ModOrganizer.exe-1500.zip](https://github.com/Modorganizer2/modorganizer/files/2178010/ModOrganizer.exe-1500.zip)
[ModOrganizer.exe-7792.zip](https://github.com/Modorganizer2/modorganizer/files/2178011/ModOrganizer.exe-7792.zip)
[ModOrganizer.exe-9304.zip](https://github.com/Modorganizer2/modorganizer/files/2178012/ModOrganizer.exe-9304.zip)
[ModOrganizer.exe-11024.zip](https://github.com/Modorganizer2/modorganizer/files/2178013/ModOrganizer.exe-11024.zip)
[ModOrganizer.exe-12496.zip](https://github.com/Modorganizer2/modorganizer/files/2178014/ModOrganizer.exe-12496.zip)

**Comment by LostDragonist** [comment]
According to those, the crash occurred in DBROverlayIconBackedUp.dll.  I can only assume that DBR is Dell Backup and Recovery.  So you either need to update that or uninstall it.

**Comment by ntblood** [comment]
Ok.  How can I find it. It's not in my program list.

**Comment by ntblood** [comment]
I can't even find where to download it. I think I downloaded the newest one not just 2 weeks ago. When running the Dell website wouldn't finish it's online scan of my computer. I'd remove it if I could figure out how. If updating it didn't work which I don't think it will from my experience 2 weeks ago. I probably have the new one installed.

**Comment by ntblood** [comment]
I'll return to this issue next week. Thank you

**Comment by ntblood** [comment]
Ok, that fixed it. Thanks so much for the link. I would have never found it I guess/it seems. MO2 started working and then I was even able to uninstall the Dell Recovery Utility as it's pop-ups were a pain. Success!    
Thank you, LostDragonist!   ^_^*
