### ISSUE TITLE
403 Forbidden Error when downloading

### ISSUE THREAD

**Issue by BigFood2307** [Modorganizer2/modorganizer#431]
# The problem

When I try to download a mod from the nexus using "Mod Manager Download" I get a small "pop up" from MO2, warning me, that the Content type is wrong.
The downloaded file is tiny (it says 0KB) and gives an error when i want to install it.
I also cant open the 7z file with winrar, but when I open it with notepad, I can see an HTML response with an 403 forbidden error.
I can use the manual download as usually.

# Environment

Mod Organizer Version that exhibits the issue:
I'm using the newest version of MO2 from the Nexus on a Win 10 PC.
I havent been using MO for some time, but since I started again yesterday, I had this problem with any mod I wanted to download.

# Details

The complete text mentioned above:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /Libs/Common/Managers/Downloads
on this server.</p>
<p>Additionally, a 500 Internal Server Error
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
```

# Link to Mod Organizer logs

## USVFS
[https://gist.github.com/BigFood2307/8687a862e8dbf82b9eaa34550e7b1f6f](https://gist.github.com/BigFood2307/8687a862e8dbf82b9eaa34550e7b1f6f)

## MO Interface
[https://gist.github.com/BigFood2307/5da4923c6d1d47f88856c5028f85c03b](https://gist.github.com/BigFood2307/5da4923c6d1d47f88856c5028f85c03b)

**Comment by LostDragonist** [comment]
This is a known problem with MO 2.1.3.  If you have premium access to the Nexus, you may be able to work around it by changing your preferred server in the MO2 Nexus settings.  Usually picking anything besides EU #1 will work.

Otherwise, I'd suggest grabbing the latest 2.1.4 developmental build from Discord.

**Comment by BigFood2307** [comment]
Changing the server helped.
Thanks for the help!
