### ISSUE TITLE
Mod Organizer 2.1.3 crashes on startup

### ISSUE THREAD

**Issue by TheLoonish** [Modorganizer2/modorganizer#432]
# The problem

I cannot get Mod Organizer 2.1.3 to open:
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	ModOrganizer.exe
  Application Version:	2.1.3.0
  Application Timestamp:	5af2bb12
  Fault Module Name:	Qt5WebEngineCore.dll
  Fault Module Version:	5.10.0.0
  Fault Module Timestamp:	5a20cc4b
  Exception Code:	c0000005
  Exception Offset:	000000000011741d
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	cff9
  Additional Information 2:	cff96621dc03e0dcf1745e4ae07f01a1
  Additional Information 3:	735b
  Additional Information 4:	735b3029607329a810095ed84466a07a

# Environment

* 2.1.3
* Windows 7 64

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/TheLoonish/7f48b7764b7e540288ff0a91e14b1b72

## MO Interface
https://gist.github.com/TheLoonish/7c1a059fca53bdc43cb2cc69bcad1392

Thank you for your time and effort.

**Comment by LostDragonist** [comment]
Can you post one of the crash dumps located here?:  L:/Games/ModOrganizer 2/crashDumps  

You can attach it to the issue if you zip it up first.

**Comment by TheLoonish** [comment]
Hi LostDragonist,

Thank you for looking at this.

[ModOrganizer.exe-2868.zip](https://github.com/Modorganizer2/modorganizer/files/2185619/ModOrganizer.exe-2868.zip)

**Comment by LostDragonist** [comment]
Unfortunately that isn't terribly helpful at the moment.  I still need to figure out how to debug QT stuff.

Things to try:
First, go to https://github.com/Modorganizer2/modorganizer/releases/tag/v2.1.3 and download Qt5.10.0_p1.7z.  Unblock the archive (right-click, properties, unblock).  Extract the contents of that archive to L:/Games/ModOrganizer 2/DDLs.  See if it works.

After that, do the same for Mod.Organizer.2.1.3.7z except extract it to L:/Games/ModOrganizer 2.  Overwrite everything.  See if it works.

**Comment by TheLoonish** [comment]
Hi LostDragonist, 

The first thing you mentioned worked. Mod Organizer opened and everything seems fine. Thank you very much. 

Can I close this issue somewhere?

**Comment by LostDragonist** [comment]
Glad that worked.  You should have a "Close Issue" button next to the comment button on GitHub.
