### ISSUE TITLE
Crashes upon installing mod

### ISSUE THREAD

**Issue by Geodyssian** [Modorganizer2/modorganizer#434]
Mod Organizer 2 will crash upon any installation of a mod. It will be either during or at the end of the process.

* Mod Organizer Version that exhibits the issue: v.2.1.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): v.2.1.2
Windows 10

[usvfs-2018-07-14_05-19-16.log](https://github.com/Modorganizer2/modorganizer/files/2194674/usvfs-2018-07-14_05-19-16.log)
[mo_interface.log](https://github.com/Modorganizer2/modorganizer/files/2194673/mo_interface.log)

https://gist.github.com/Geodyssian/8ff3296532f4df1204c6072b8775688b

**Comment by Al12rs** [comment]
Can you test if this keeps happening on the latest 2.1.4 build?
You can get it here: https://discord.gg/5tCqt6V

**Comment by Geodyssian** [comment]
So it works now, however there is now another issue. Whenever I try to export to csv, I can't seem to export if I click on "Primary_Category". Please help.

**Comment by Al12rs** [comment]
Open a different issue for this please, or report on the server
