### ISSUE TITLE
Mod Organiser 2.1.4 will not boot the game from SkyrimLauncherSE.exe, SkyrimSE.exe and SKSE64.     

### ISSUE THREAD

**Issue by BadHumour** [Modorganizer2/modorganizer#435]
# The problem
-Mod Organiser 2.1.4 will not boot the game from SkyrimLauncherSE.exe, SkyrimSE.exe and SKSE64.     

# Environment
-Operating System: Windows 10 ver 1803
-Mod Organiser 2.1.4 Dev build

# Details
-Executables not launched from Mod Organiser 2.1.4 still run. 
-When booting the executables from Mod Organiser 2 the game will appear to be ready to boot up but will crash before any kind of screen appears. 
-Mods that are installed with Mod Organiser 2 wont load when running executables without mod organizer. Im guessing this is by design but I could be wrong.
-Other executables launched from Mod Organiser like Creation Club and LOOT do work. 

==Attempted Fixes==
-reinstalling and Validating SkyrmSE through steam
-Repairing  VCRedistx64 and x86
-repathing where the mods downloaded to. 
-resolving all incompatibilities and load order issues
-disabling and enabling suspected mods (not all of them because my mod library is very large and did not have time.)
-reinstalling Mod Organiser 2.1.4
-checked skyrim.ini for issues. 
-running in Admin mode. 
-made sure that the anti-virus doesnt go all SWAT team on it (It was really unhappy).
-redid the instance selection. 

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/BadHumour/f7da252f7afbc862d197f425fcbd2ac9

## MO Interface
https://gist.github.com/BadHumour/257dc3a9908e4c52a5d41d7557be977a

**Comment by BadHumour** [comment]
It was one of my mods causing the issue, I just now need to find which one. None of the mods in the data section are culprit.

**Comment by Al12rs** [comment]
I will close this up then.
