### ISSUE TITLE
Does not appear to work with fomods

### ISSUE THREAD

**Issue by CrazyV1ad** [Modorganizer2/modorganizer#437]
# problem MO 2 Not able to install some nexus mods with fomods e.g QUASIPC - Unified Patch Compendium v1_1_1-18369-1-1-1e. MO2 does not recognise downloads wth no Data directory e.g. Divine People of skyrim

Briefly describe the issue you are experiencing (or the feature you want to see added to Mod Organizer). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our discord channel

# Environment

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by LostDragonist** [comment]
Both of the mods you mentioned are working for me with MO 2.1.3 and MO 2.1.4 dev build 6.

I'm going to take a wild guess and say that some of your MO2 install is being blocked by Windows.  Please see this video on how to properly unblock and install MO2:  https://youtu.be/CBurE8aLTxE

If that's not it, you really need to provide the information in the issue template.  It's there for a reason.
