### ISSUE TITLE
Add Mod Name column to downloads tab

### ISSUE THREAD

**Issue by FWDekker** [ModOrganizer2/modorganizer#439]
# The problem
When viewing the list of downloaded files, I want to see what mod a file corresponds to.

> ![List of downloads with vague file name "FTO".](https://user-images.githubusercontent.com/13442533/42817736-46c7bb48-89cf-11e8-8a3e-d6102e0d2b81.png)
> **Wait, what does "FTO" mean again?**

Many mod authors do not use sensible names for the downloaded files, using acronyms that are easily forgotten after a few days. Other mod authors publish patch files that do not even include the name of the mod, instead describing only what the _patch_ does. When viewed in the list of downloads, it can be hard to see that a file belongs to a certain mod. As a result, when reinstalling a mod, it's hard to find the patches that should be applied.

> ![List of downloads with popup explaining the meaning of "FTO".](https://user-images.githubusercontent.com/13442533/42817885-b6c00ad6-89cf-11e8-9478-331f3438af16.png)
> **Oh, it's Fallout Texture Overhaul...**

I would like to request an additional column in the list of downloads that names the mod that a downloaded file corresponds to. While it's possible to find the mod that a file corresponds to by hovering over the mod, I would like to be able to sort my downloads by the mod's name to make it easier to decide which files I should install.

If this explanation is vague or leaves something to be desired, please tell me.

# Environment
My current environment is as follows:
* ModOrganizer v2.1.3
* Windows 10 x64

**Comment by Project579** [comment]
This also connects to the problem that MO doesn't actually know if a mod was uninstalled when you use merge, it will mark the last one installed as uninstalled but not the rest.

**Comment by Al12rs** [comment]
The download does not have the info of the mod, the mod has the info of the origin download. When the mod is uninstalled the origin downloads Uninstalled property is changed.

**Comment by Project579** [comment]
Is there no way to make the "info of the origin download" a vector or something so that it can mark as uninstalled more then one mod?

**Comment by Al12rs** [comment]
Probably. With downloads ad mods you have to be careful on what you add and change since there are interfaces that need to be respected and those things are used all over the code.

**Comment by Project579** [comment]
I see its just something that has bothered me for a long time. Uninstalling a mod and then in the download it still says it's installed because you merged an update or something with it and it only marks the last one.

**Comment by FWDekker** [comment]
I feel that this issue has derailed somewhat; it was originally about showing the mod with the file, not about tracking what constitutes an installation. Does the latter sound feasible to add to ModOrganizer?

**Comment by Al12rs** [comment]
You are right sorry about that.
If you just want it to show the name of the (nexus) mod from which the file was downloaded then that should be doable.
I'm not personally interested in it so if someone else want's to implement it feel free.

**Comment by Al12rs** [comment]
change current Name column to say "File Name"
