### ISSUE TITLE
Found unknown Compressed 

### ISSUE THREAD

**Issue by spyrosn** [ModOrganizer2/modorganizer#445]
[quicksave.zip](https://github.com/Modorganizer2/modorganizer/files/2216525/quicksave.zip)

# The problem

Disabled all mods on Skyrim (unticked ESPs under the tab Plugin). Quicksaved. Moved my quicksave from Skyrim to Skyrim SE. Tried to load it=> CTD

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10

# Details

In the Saves tab, I was prompted to raise an issue with the above title, attaching my savegame. So I did.

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/spyrosn/2838e101d0003b400f0b7835c0d814dd

## MO Interface
https://gist.github.com/spyrosn/7f6ee9b0971ac4589091da42a52869bf

**Comment by Project579** [comment]
Please update to the latest version, then if the problem persists make sure the Vanilla game runs, after that you can post your logs, remember to set the Log Level to Debug.

**Comment by Al12rs** [comment]
Closing for organization, reopen if someone is able to reproduce
