### ISSUE TITLE
Crashes upon switching profiles (No crash log created, goes not responding)

### ISSUE THREAD

**Issue by Drakonas** [Modorganizer2/modorganizer#448]
# The problem

I am trying to switch profiles in Mod Organizer, and after doing so within a few seconds, the window says "Not responding" and never responds. I have waited a couple minutes. I have also tried creating a new profile. Still happens.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10 April 2018 Update

# Details

I have also tried changing the profile and quickly closing MO2, and it seems to close, but then when I try to open MO2 again it says there is already an instance running. Looking in Task Manager, there is a ModManager process suspended.

# Link to Mod Organizer logs

## USVFS
[usvfs-2018-07-24_13-09-44.log](https://gist.github.com/Drakonas/3b0ed07dcf7dbb9c39c11738578f1fca) (Initial log)

[usvfs-2018-07-24_13-21-10.log](https://gist.github.com/Drakonas/eba88896b2eafa8c4f25676a1a14d569) (Repeatedly only making these logs now, as if it's entirely broken)

## MO Interface
[mo_interface.log](https://gist.github.com/Drakonas/362eac129f5d84bac71988e321c7e35e)

**Comment by Al12rs** [comment]
Can you download the latest dev build from Discord and test again?  https://discord.gg/MB3CyMH

**Comment by Drakonas** [comment]
Still happens @Al12rs Sorry I wasn't aware of the dev builds. Here are the new logs.
[mo_interface.log](https://gist.github.com/Drakonas/e06ef06733859cb12074b13bff4689c7)
[usvfs-2018-07-24_13-44-55.log](https://gist.github.com/Drakonas/941844efe23632c6edc901df03a9969b)

**Comment by Drakonas** [comment]
@Al12rs  Sorry I didn't read everything regarding installation of the dev build. My apologies. Here are the proper logs for 2.1.4 (double checked in the mo_interface.log myself).
[mo_interface.log](https://gist.github.com/Drakonas/93f103a737d4d5add8b1806eb17803c7)
[usvfs-2018-07-24_13-56-12.log](https://gist.github.com/Drakonas/3b250d0197c6e6d4e9c088ffd78f7e08)

**Comment by Al12rs** [comment]
@Drakonas do you have already a setup or are you just starting? Because I would suggest to delete the current profiles folders and let Mo2 create a new one, but if you already have a loadorder and all that is not good.

**Comment by Drakonas** [comment]
I had just started yesterday. I mean, deleting everything probably might fix the issue, but I don't think that would help us narrow down what's causing the problem.

**Comment by Drakonas** [comment]
@Al12rs I just renamed the profiles folder, and created a new one before running MO2, and I was able to create a new profile and switch to it, but then it crashed again when I switched back.

**Comment by Al12rs** [comment]
I think the problem is one of the files in your profile folder, Did you use something for your INI files? Are any of those files readonly?

**Comment by Drakonas** [comment]
I have been testing different things one after the other.

Deleting profiles folder: doesn't fix it.
Deleting profiles folder AND ModOrganizer.ini: doesn't fix it.
Deleting profiles folder AND ModOrganizer.ini AND webcache: doesn't fix it.
Deleting profiles folder AND ModOrganizer.ini AND webcache: doesn't fix it.

FYI, I did delete all folders and files that existed in the MO2.1.4_DevBuild_7_AL12.7z before dragging and dropping. The only thing left was crashDumps (empty), downloads, logs, mods, overwrite (empty), profiles, webcache, debug.log, ModOrganizer.ini, nxmhandler.ini, and uninstall.exe prior to the overwrite. As of right now, there should be nothing affecting this issue other than MO2 itself, or something somewhere else on my system.

**Comment by Al12rs** [comment]
Well if the files in your profiles folder are readonly that could cause the crash for example

**Comment by Al12rs** [comment]
You are the first person with such a problem

**Comment by Drakonas** [comment]
Yeah I tried restarting already and made sure it did restart.

**Comment by Al12rs** [comment]
Install Mo2 somewhere that isn't the game folder. Like in C:/Modding/Tools/Mo2

**Comment by Drakonas** [comment]
Just uninstalled it and extracted a brand the standalone to V:\ModOrganizer2 and move the mods, profiles, and ModOrganizer.ini folder into it and I still have the same issue. Is it possibly a corrupt file in the mods vfs?

**Comment by Drakonas** [comment]
Well @Al12rs I just made a completely fresh folder, fresh extraction from the Nexus download, added a mod, created a profile, switched profiles, and .. it crashed. There's not anything more I can troubleshoot.

**Comment by Al12rs** [comment]
I was sure that rebooting the PC should have fixed the issue. I can only assume there is something going very wrong with your windows permissions or something.
Can you try to send me the interface log of a run that crashed? In the logs you sent there is nothing to see

**Comment by Drakonas** [comment]
It never makes a log when it crashes. The only log right now in the fresh folder is [usvfs-2018-07-24_15-31-51.log](https://gist.github.com/Drakonas/3e321aa5a9985e507cbb4e185fc39513)

**Comment by Drakonas** [comment]
I can install Visual Studio and get you debugging information if you would like?

**Comment by Al12rs** [comment]
It always writes the interface log. The usvfs log is only for when you actually start programs with Mo2, so not relevant here. The interface log is reset when you open Mo2 and stops writing when you close it

**Comment by Drakonas** [comment]
Well it isn't there... lol. It doesn't get created when I open MO2, and doesn't show up after it crashed. Do you want to remote into my machine and see for yourself?

**Comment by Al12rs** [comment]
No sorry don't have time for it.

**Comment by Drakonas** [comment]
Here's an animated GIF then: [GIF](http://genesis.whatbox.ca:42424/img/2018-07-24_12-00-53.gif)

**Comment by LostDragonist** [comment]
@Drakonas Are there any .dmp files beings created in the crashDumps folder?  If there are, can you zip up the latest one and post it here?

**Comment by Drakonas** [comment]
There are none @LostDragonist I would have posted them if I had them, for sure.

**Comment by Al12rs** [comment]
Do you have antivirus installed? Can you try disabling all antivirus, reinstalling Mo2 and try again?

**Comment by Drakonas** [comment]
I had added an exclusion for my Antivirus, but I forgot that Acronis True Image has it's own security software baked in. Added an exclusion and profiles work again! [https://resource.dopus.com/t/crashes-and-hangs-in-windows-10-creators-update/25639/6](Thank you Google!)
