### ISSUE TITLE
Mod Organizer installs mods but they don't appear in game

### ISSUE THREAD

**Issue by oliolioxxinfree** [Modorganizer2/modorganizer#451]
So I've recently switched from NMM to MO2 and it'd be AMAZING if I didn't have this issue. When I pull up the OG Skyrim launcher and look in Data Files the mods I installed via MO don't show up. They don't show up in LOOT either. 
I still have mods on NMM, I don't know if that's a problem but I'm just too lazy to fully switch over at the moment.

**Comment by LostDragonist** [comment]
Are you running the launcher through MO2?  Any mods installed in MO2 will not show up in any game or tool executable unless run through MO2.

**Comment by LostDragonist** [comment]
If this issue is not resolved, please reopen it to continue the discussion.
