### ISSUE TITLE
can't delete mods in the mods file 

### ISSUE THREAD

**Issue by MessyMark** [Modorganizer2/modorganizer#453]
For some reason there are 2 mods in the mods file that i cant delete its keep saying the file has been move but every time i download a new mod those 2 files would appear and make all of my mod deactivated so i have to activate it again and remove the 2 mods that i can't delete

**Comment by LostDragonist** [comment]
It's possible those folders have an invalid name and Windows can't properly delete them.  Try using a program like 7-zip file manager (you probably have it installed on your computer already) to navigate to the mods folder and delete them.

**Comment by LostDragonist** [comment]
If this issue is not resolved, please reopen it to continue the discussion.
