### ISSUE TITLE
Doesn't connect with nexus

### ISSUE THREAD

**Issue by asbator** [Modorganizer2/modorganizer#455]
# The problem

It doesn't display any error neither. Doesnt seem to try to connect at all. In settings the Known Servers list is empty. Typing in credentials doesn't do anything. When i click download with mod manager on Nexus website nothing happens, no errors.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.3
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro

# Details

I never used MO before, my main concern about this situation is - wether i need to download mods using option "MOD MANAGER Download" in order to make MO2 display Nexus info and mod versions.
Tracking mod versions in Mod Organizer would be great solution.

# Link to Mod Organizer logs

## USVFS
15:10:23.562 [I] usvfs dll 0.4.0.0 initialized in process 13108
15:10:23.562 [D] remove from process 13108
15:10:23.562 [I] create config in 13108
15:10:23.562 [I] 0 processes - 1
15:10:23.562 [I] mod_organizer_instance_1 created in process 13108
15:10:23.562 [I] attached to mod_organizer_instance_1 with 1 nodes, size 65536
15:10:23.562 [I] inv_mod_organizer_instance_1 created in process 13108
15:10:23.562 [I] attached to inv_mod_organizer_instance_1 with 1 nodes, size 65536
15:10:23.562 [D] context current shm: mod_organizer_instance (now 2 connections)

## MO Interface
https://gist.github.com/asbator/bb6ea4014b94e886597a4ff0c62aa3db

**Comment by LostDragonist** [comment]
Try running nxmhandler.exe in the MO2 directory and clicking "register active" in the bottom right.  Then try downloading something again.

**Comment by Al12rs** [comment]
Will close for lack of response and inability to reproduce in a few days.
