### ISSUE TITLE
SKSE fails to initialize under certain conditions

### ISSUE THREAD

**Issue by AudieMurphy135** [ModOrganizer2/modorganizer#457]
# The problem

SKSE will sometimes fail to initialize after launching the game.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.3 / 2.1.4 pre-alpha (rev f824d25)
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 8.1

# Details

I don't know 100% what exactly causes the issue, but this is what I've found out so far:

It seems to be related to having a mod (left pane) that contains files that go within the SKSE folder, typically the ones that are generated on runtime or within the game (I made a mod containing these to keep my overwrite folder clean). If I alter the contents of this folder or install / update a mod that also has files that go within the SKSE folder, it will sometimes result in SKSE failing to initialize after launching the game (confirmed by using "getskseversion" within the command prompt). In the case today, I updated Quick Loot SE, which contains files that go within the SKSE folder.

This can usually be resolved by unchecking the mod containing the game-generated SKSE files, refreshing, launching the game, closing the game, checking the mod, refreshing, launching the game, closing the game, then removing the SKSE files that were generated during the first launch from the overwrite, refreshing, then launching it one last time.

It can also sometimes happen by simply closing the game and launching it again. I can almost always fix it in this instance by refreshing, closing MO2, then refreshing again and launching the game.

In extreme cases, it will cause the entire system to hang immediately before the menu options appear and while the spinny icon is at the bottom right ( https://i.imgur.com/PpelNIT.png ), requiring a hard restart of the PC. This only seems to happen if SKSE has already failed to initialize at least once.

# Link to Mod Organizer logs

## USVFS

I'm not sure which ones will be useful, so here all of the ones from while I was sorting out the issue. My system froze for the 5:18 and 5:23 logs, if that info helps any.

[5:04 PM] - https://gist.github.com/AudieMurphy135/5df4fb64a49086f545ac608aa91269ec

[5:17 PM] - https://gist.github.com/AudieMurphy135/d3114aa617fb53a9790c60d50bf1335a

[5:18 PM] - https://gist.github.com/AudieMurphy135/19e153cd7bd2f799d360d166ca149ba7

[5:23 PM] - https://gist.github.com/AudieMurphy135/deccb6b66a57dbe0f8e82ec2c2bf8117

[5:31 PM] - https://gist.github.com/AudieMurphy135/128676be8f5a51ebf609f58d4055ae36

[5:44 PM] - https://gist.github.com/AudieMurphy135/710ccd35163e476f21812209bbe81aaf

## MO Interface
https://gist.github.com/AudieMurphy135/fae9addfdbc4fcd4653b93445c96dbce

**Comment by Al12rs** [comment]
I'm closing this on the assumption that this no longer happens to you on newer versions as we didn't receive other reports similar to this. Please reopen if this is still an issue.
