### ISSUE TITLE
Modorganizer wont launch SkyrimSE

### ISSUE THREAD

**Issue by omnipotent20181** [Modorganizer2/modorganizer#458]
# The problem

when i click run for the SE launcher, it runs but when i click play , nothing happens, it just locks MO2... same applies to the running the game itself , it just locks then nothing happens
# Environment

* Mod Organizer Version that exhibits the issue:2.1.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:windows 10

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs
09:42:21 [D] ssl support: 1
09:42:21 [D] data path: C:/Users/gable/AppData/Local/ModOrganizer/SkyrimSE
09:42:21 [D] Working directory: C:\Users\gable\Downloads\Mod Organizer 2 SE
09:42:21 [D] Loaded settings:
09:42:21 [D]   compact_downloads=false
09:42:21 [D]   display_foreign=true
09:42:21 [D]   force_enable_core_files=true
09:42:21 [D]   hide_unchecked_plugins=false
09:42:21 [D]   language=en_US
09:42:21 [D]   load_mechanism=0
09:42:21 [D]   log_level=0
09:42:21 [D]   meta_downloads=false
09:42:21 [D]   nexus_login=true
09:42:21 [D]   nmm_version=0.61.13
09:42:21 [D]   offline_mode=false
09:42:21 [D]   use_prereleases=false
09:42:21 [D]   use_proxy=false
09:42:21 [D] initializing core
09:42:21 [D] usvfs log messages are written to C:/Users/gable/AppData/Local/ModOrganizer/SkyrimSE/logs/usvfs-2018-07-29_01-42-21.log
09:42:21 [D] Initializing VFS <mod_organizer_instance, 0, 1, C:/Users/gable/AppData/Local/ModOrganizer/SkyrimSE/crashDumps>
09:42:21 [D] initialize plugins
09:42:21 [D] looking for plugins in C:\Users\gable\Downloads\Mod Organizer 2 SE\plugins
09:42:21 [D] loaded plugin "bsa_extractor.dll"
09:42:21 [D] loaded plugin "check_fnis.dll"
09:42:21 [D] loaded plugin "diagnose_basic.dll"
09:42:21 [D] loaded plugin "game_fallout3.dll"
09:42:21 [D] loaded plugin "game_fallout4.dll"
09:42:21 [D] loaded plugin "game_fallout4vr.dll"
09:42:21 [D] loaded plugin "game_falloutNV.dll"
09:42:21 [D] loaded plugin "game_morrowind.dll"
09:42:21 [D] loaded plugin "game_oblivion.dll"
09:42:21 [D] loaded plugin "game_skyrim.dll"
09:42:21 [D] loaded plugin "game_skyrimse.dll"
09:42:21 [D] loaded plugin "game_skyrimvr.dll"
09:42:21 [D] loaded plugin "game_ttw.dll"
09:42:21 [D] loaded plugin "inibakery.dll"
09:42:21 [D] loaded plugin "inieditor.dll"
09:42:21 [D] loaded plugin "installer_bain.dll"
09:42:21 [D] loaded plugin "installer_bundle.dll"
09:42:21 [D] loaded plugin "installer_fomod.dll"
09:42:21 [D] loaded plugin "installer_manual.dll"
09:42:21 [D] loaded plugin "installer_ncc.dll"
09:42:21 [D] loaded plugin "installer_quick.dll"
09:42:22 [D] loaded plugin "pyCfg.py"
09:42:22 [D] loaded plugin "plugin_python.dll"
09:42:22 [D] loaded plugin "preview_base.dll"
09:42:22 [D] no plugin splash
09:42:22 [D] managing game at C:\Program Files (x86)\The Elder Scrolls V Skyrim Special Edition
09:42:22 [D] setting up configured executables
09:42:22 [D] configured profile: Default
09:42:23 [D] initializing tutorials
09:42:24 [D] loaded language en_US
09:42:25 [D] interface Wi-Fi seems to be up (address: fe80::3d70:2bdd:1a3a:a102%wireless_32768)
09:42:25 [D] reading save games from C:/Users/gable/AppData/Local/ModOrganizer/SkyrimSE/profiles/Default/saves
09:42:25 [D] displaying main window
09:42:26 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\modlist.txt saved
09:42:45 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\initweaks.ini saved
09:42:45 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\plugins.txt saved
09:42:45 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\loadorder.txt saved
09:42:45 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\lockedorder.txt saved
09:42:45 [D] Load Mechanism: Mod Organizer
09:42:45 [D] USVFS DLL Name: usvfs_x64.dll
09:42:45 [D] enable local saves: 1
09:42:45 [D] Updating VFS mappings...
09:42:46 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\archives.txt saved
09:42:47 [D] VFS mappings updated <linked 46 dirs, 4 files>
09:42:47 [D] Spawning direct process < "C:/Program Files (x86)/The Elder Scrolls V Skyrim Special Edition/skyrimseLauncher.exe" , "" , "C:/Program Files (x86)/The Elder Scrolls V Skyrim Special Edition" >
09:42:47 [D] Waiting for spawned process completion : SkyrimSELauncher.exe (8628)
09:42:49 [D] Waiting for usvfs process completion : SkyrimSE.exe (3784)
09:43:22 [D] Waiting for process completion successfull
09:43:23 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\lockedorder.txt saved
09:43:33 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\initweaks.ini saved
09:43:33 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\lockedorder.txt saved
09:43:33 [D] Load Mechanism: Mod Organizer
09:43:33 [D] USVFS DLL Name: usvfs_x64.dll
09:43:34 [D] enable local saves: 1
09:43:34 [D] Updating VFS mappings...
09:43:35 [D] VFS mappings updated <linked 46 dirs, 4 files>
09:43:35 [D] Spawning direct process < "C:/Program Files (x86)/The Elder Scrolls V Skyrim Special Edition/skyrimseLauncher.exe" , "" , "C:/Program Files (x86)/The Elder Scrolls V Skyrim Special Edition" >
09:43:35 [D] Waiting for spawned process completion : SkyrimSELauncher.exe (7940)
09:43:38 [D] Waiting for usvfs process completion : SkyrimSE.exe (5308)
09:44:05 [D] Waiting for process completion successfull
09:44:06 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\lockedorder.txt saved
09:44:46 [D] QWindowsNativeFileDialogBase::onSelectionChange () 0
09:44:50 [D] QWindowsNativeFileDialogBase::onSelectionChange () 0
09:44:52 [D] QWindowsNativeFileDialogBase::onSelectionChange (QUrl("file:///C:/Program Files (x86)/The Elder Scrolls V Skyrim Special Edition/SkyrimSELauncher.exe")) 1
09:44:53 [D] QWindowsNativeFileDialogBase::onSelectionChange (QUrl("file:///C:/Program Files (x86)/The Elder Scrolls V Skyrim Special Edition/SkyrimSE.exe")) 1
09:45:04 [D] QWindowsNativeFileDialogBase::onSelectionChange () 0
09:45:05 [D] QWindowsNativeFileDialogBase::onSelectionChange (QUrl("file:///C:/Program Files (x86)/The Elder Scrolls V Skyrim Special Edition/SkyrimSE.exe")) 1
09:45:13 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\initweaks.ini saved
09:45:13 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\lockedorder.txt saved
09:45:13 [D] Load Mechanism: Mod Organizer
09:45:13 [D] USVFS DLL Name: usvfs_x64.dll
09:45:13 [D] enable local saves: 1
09:45:13 [D] Updating VFS mappings...
09:45:15 [D] VFS mappings updated <linked 46 dirs, 4 files>
09:45:15 [D] Spawning direct process < "C:/Program Files (x86)/The Elder Scrolls V Skyrim Special Edition/SkyrimSE.exe" , "" , "C:/Program Files (x86)/The Elder Scrolls V Skyrim Special Edition" >
09:45:15 [D] Waiting for spawned process completion : SkyrimSE.exe (7536)
09:45:50 [D] Waiting for process completion successfull
09:45:51 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\lockedorder.txt saved
09:48:41 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\initweaks.ini saved
09:48:41 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\lockedorder.txt saved
09:48:41 [D] Load Mechanism: Mod Organizer
09:48:41 [D] USVFS DLL Name: usvfs_x64.dll
09:48:41 [D] enable local saves: 1
09:48:41 [D] Updating VFS mappings...
09:48:43 [D] VFS mappings updated <linked 46 dirs, 4 files>
09:48:43 [D] Spawning direct process < "C:/Program Files (x86)/The Elder Scrolls V Skyrim Special Edition/SkyrimSE.exe" , "" , "C:/Program Files (x86)/The Elder Scrolls V Skyrim Special Edition" >
09:48:44 [D] Waiting for spawned process completion : SkyrimSE.exe (2988)
09:49:20 [D] Waiting for process completion successfull
09:49:22 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\lockedorder.txt saved
09:50:30 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\initweaks.ini saved
09:50:30 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\lockedorder.txt saved
09:50:30 [D] Load Mechanism: Mod Organizer
09:50:30 [D] USVFS DLL Name: usvfs_x64.dll
09:50:31 [D] enable local saves: 1
09:50:31 [D] Updating VFS mappings...
09:50:33 [D] VFS mappings updated <linked 46 dirs, 4 files>
09:50:33 [D] Spawning direct process < "C:/Program Files (x86)/The Elder Scrolls V Skyrim Special Edition/skyrimseLauncher.exe" , "" , "C:/Program Files (x86)/The Elder Scrolls V Skyrim Special Edition" >
09:50:33 [D] Waiting for spawned process completion : SkyrimSELauncher.exe (1628)
09:50:35 [D] Waiting for process completion successfull
09:50:37 [D] C:\Users\gable\AppData\Local\ModOrganizer\SkyrimSE\profiles\Default\lockedorder.txt saved
 [D] 

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by LostDragonist** [comment]
1. You did not post your usvfs log.
2. Your running a cracked version of the game.  This has been known to cause problems in the past.  We generally do not support cracked games as we have no way of knowing what those cracks do.

**Comment by LostDragonist** [comment]
Closing due to lack of user response.  Please reopen the issue if you want.to continue the discussion.
