### ISSUE TITLE
Can't save new slider presets in BodySlide

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#460]
# Problem

In BodySlide for Skyrim SE, a new set of slider presets can not be saved to the Skyrim SE game folder.  Doing so results in an error ("Failed to save preset as 'C:\path\to\xml' (1)!").  Saving an already created preset works.  BodySlide handles this fine when installed manually.

# Test Environment
MO 2.1.4, Dev Build 8
Skyrim SE 1.5.39
BodySlide and Outfit Studio 4.6
CBBE 1.3
Windows 10, version 1803

# Logs

[Github gist of logs](https://gist.github.com/LostDragonist/7853f9356b492c964fee86fe99d6e79a)

usvfs-1-failed-tosave.log:  Reproduces the error of failing to save TEST_PRESET.xml to the game directory
usvfs-2-save-as.log:  Shows an example of successfully saving TEST_PRESET.xml to the desktop
usvfs-3-save.log:  Shows successfully updating TEST_PRESET.xml that was manually moved to an MO2 mod

**Comment by LostDragonist** [comment]
Looking at the BodySlide code, I believe the error is coming from a call to _wfopen_s in PresetCollection::SavePreset.  Any error in this function will return an error of 1 so the value itself is fairly meaningless.

There is another possible error path in XMLDocument::SaveFile but I don't see how it would actually error out.  I'd also find it unlikely to fail as the file would have already been read, destroyed, and reopened at that point.

**Comment by Amnesiac9** [comment]
Just to add to this, I'm also getting this bug with body slide for fallout 4 and MO2 v 2.1.3

As an aside, I did not get this bug when using Nexus Mod Manager. (just a bunch of other problems.)

**Comment by Project579** [comment]
I think it may be related to windows 10, it works as expected for me no errors and ends up in overwrite

**Comment by SuwinTzi** [comment]
I have this issue with MO2 only, running Windows 7.

Bodyslide is attempting to save the presets in the virtualized CalienteTools folder.  Manually redirecting to the actual CalienteTools folder in either "mods" from MO2 installation or located in AppData solves the problem.

However, you cannot save any updates through above method using the "Save" button, since Bodyslide will attempt to save to the virtualized location.

**Comment by Project579** [comment]
You should never write to files in the virtual folder from ouside of it, I need to check out this bug better on my system.

**Comment by hamletsdead** [comment]
If you're using MO2 just redirect the save file to the where the actual Caliente Tools/Bodyslide folder is -- e.g., in my case that's C:\Games\MO2 Mods\BodySlide and Outfit Studio - v4.7.0\CalienteTools\BodySlide. Once you do that the modified BodySlide preset saves just fine.

**Comment by LostDragonist** [comment]
[MO v2.1.6](https://github.com/ModOrganizer2/modorganizer/releases/tag/v2.1.6) has been released and this bug should be fixed. If anyone runs into this again, please submit a new issue.
