### ISSUE TITLE
Slow Downloads from premium servers

### ISSUE THREAD

**Issue by aplanetsabc** [Modorganizer2/modorganizer#461]
# Slow Downloads From Premium Servers
When I download through MO2 my download speeds are 1/8th the speed of manual or NMM download Speeds 

# Environment

* Latest
* N/A
* Windows 10
# Details

N/A

# Link to Mod Organizer logs

**Comment by LostDragonist** [comment]
If this issue is not resolved, please reopen it to continue the discussion.
