### ISSUE TITLE
Mod install: Default to using file title instead of last name with same ID.

### ISSUE THREAD

**Issue by Amnesiac9** [ModOrganizer2/modorganizer#462]
# The problem
Mod Names when Installing is naming the mod incorrectly, taking the name of the mod I previously installed.

# Environment

* Mod Organizer Version that exhibits the issue: v2.1.3
* Desktop OS/version used to run Mod Organizer: Windows 10 Latest 

# Details

For example, if I install a texture mod for Landscapes, called Vivid Landscapes, then install a texture mod for Animals, called Vivid Animals, it will name the Animal mod "Vivid Landscapes".

Why doesn't it just automatically take the name from the name of the mod I'm installing?

Is this a bug on my end or intended behavior?

Thanks for your time!

**Comment by LostDragonist** [comment]
Is this a theoretical example or a realistic example?  I can't find any mod named "Animals" or "Vivid Animals."

MO2 will automatically suggest the name you last used for a mod with the same Nexus ID.  If you install Vivid Landscapes, which has a Nexus ID of 5488 for Skyrim SE, and call it "Bob," then any download with the Nexus ID of 5488 will automatically suggest the name "Bob."  

I believe this is a great feature as mod authors do not always name their downloads sensibly.  For example, one of the downloads in Skyrim 2017 Textures for Skyrim SE is named something like "newwwwwww.7z."  

If the automatic suggestion is wrong, you can click the dropdown arrow to get an array of other suggestions, including more previous names that you used for the same Nexus ID.  A few of those suggestions will always be based on the name of the download.

**Comment by Silarn** [comment]
☝️

**Comment by Amnesiac9** [comment]
It was not a real example, a real example would be any mod which has multiple main or optional separate downloads. Which, while setting up my mod list for the first time in FO2, was quite a few of them.

Instead of defaulting to the name that is shown in the downloads pane, it defaults to the exact same name as the one you just installed, which doesn't seem all that useful to me, unless you are constantly reinstalling the same exact mod.

So I now have to click the drop down for every mod that defaults to the wrong name, not a big deal, but would it not be much more useful to default to the download name to preserve the difference in multiple files from the same nexus mod page?

**Comment by Amnesiac9** [comment]
The whole point of this issue was because one of the other suggestions in the drop down was more useful 99% of the time, and I was questioning whether or not that was supposed to happen.

I suppose if it's intended to be like that, then this isn't an issue, but more of a feature request, to change it so that you don't have to choose a new name from the dropdown so often, since most of the time the name showing in my downloads pane would be perfectly fine, but it doesn't default to that name. 

I do also have the setting "download meta data" checked so that file names are not displayed in the downloads pane, so if that option was made to apply to the default name suggested when installing, that would be amazing.

If feature requests are not taken here I understand, sorry to waste your time!

**Comment by Al12rs** [comment]
They are taken and I agree that a lot of the time with multiple files from the same mod it is jarring to have to select a different name. I do imagine though that it comes in handy that it uses the same name when updating a mod. At least you file it immediately and you can decide if you want to update it or remove it. If it was made into a good system that uses mod names well then it should work anyways.

**Comment by LostDragonist** [comment]
In my experience and opinion, the current behavior is more useful most of the time.  Maybe I'm overly used to it or have a different workflow.  If people agree there's a better way, I'm fine with it.

**Comment by Amnesiac9** [comment]
I think the best option would be to have a little checkbox, next to the option for showing mod names instead of file names in the download pane, that says "apply to mod naming suggestions when installing" or something similar. This way the default behavior could be retained and the overall speed of setting up a large mod list from scratch would be faster for people like me.



I do agree that the feature is great when updating mods or reinstalling a mod, and I haven't had to do much of that yet, but the the ability to keep the same name for those functions would be great as well, so I could simply toggle that option off when updating my mod list or reinstalling mods.

Thanks for the responses guys, i hope a feature or option like this makes its way into a build in the future, if it's not too much work for you all of course. I understand bug fixes and such take priority so I'm not expecting anything. 

I appreciate that you guys are still supporting mod organizer, its definitely the best MM available right now and I hope it continues to get improvements!

**Comment by Al12rs** [comment]
Our plans for new mods names are outlined here: #742 . Closing this for organization.
