### ISSUE TITLE
Mod Organizer Update doesn't detect it's current install location.

### ISSUE THREAD

**Issue by Ashotep** [ModOrganizer2/modorganizer#471]
# The problem

Mod Organizer doesn't detect it's install location if it was installed to a different directory then its default.  At First I thought when I clicked on the button within MO that it was messing up the install because when I would reopen MO from then shortcut on my desktop it will still say it was the old version I have installed.  I kept trying to update the organizer and it never seemed to stick.  I then noticed that when the installer ran it was listing the default install location.  I never paid attention to this because I thought it would detect where it was installed.  When I investigated I had two versions on MO installed.  One in the default and one in the directory I intended it to be in.

# Environment

2.1.3 ->2.1.4

**Comment by Al12rs** [comment]
the installer is getting replaced, the new one should have that feature after the first install

**Comment by LePresidente** [comment]
This has been completed with the release of 2.1.6, It will take effect when updating to the next version
