### ISSUE TITLE
Data Tab displays incomplete names and no extensions 

### ISSUE THREAD

**Issue by teytame** [Modorganizer2/modorganizer#474]
# The problem

In the middle of installing FNIS following guide, ran into this problem, when I need to make a specific file executable, but I can only see this https://s15.postimg.cc/c413y6523/MO_exe.jpg

# Environment

* Mod Organizer Version 2.1.3
* ~
* Windows 10

# The Data Tab shows only partial names and no extension.

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/teytame/9531c50a4fb9be5b5b387e9d009dd484

## MO Interface
https://gist.github.com/teytame/069cc04e171b9a2bebba1a0e1d27c1d9

I hope I'm doing this right because I've never done anything like this before.
Thank you in advance, guys.

**Comment by LostDragonist** [comment]
At the top of the data tab, there's a vertical line between the words "file" and "mod".  Click and drag that line to the right.

**Comment by teytame** [comment]
And now I feel utterly stupid, but grateful. Thank you very much =)
