### ISSUE TITLE
Manual Refresh Downloading

### ISSUE THREAD

**Issue by JFMillerUSA** [Modorganizer2/modorganizer#475]
The problem

Download stalls when mouse isn't moving

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.4
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10 Home (1803)

# Details

Any file downloaded from NM stops, when I move mouse between left and right pane the download refreshes.

# Link to Mod Organizer logs

## MO Interface: [mo_interface.log](https://gist.github.com/JFMillerUSA/71f065404f0341216ac25d4766e7e918.js)

**Comment by Project579** [comment]
Are you sure the downloads stall? there is an old bug of the UI that makes it so the bar for the download doesn't update.

**Comment by JFMillerUSA** [comment]
Maybe but I have to move between panels for it to refresh

**Comment by JFMillerUSA** [comment]
Fixed, setup Firefox to handle nxm links with "Use NXM Link Proxy (default)". And setup MO2 with configure and workarounds Nexus tab, Automatically Log-In to Nexus, Use HTTP Proxy (Use System Settings). And move known server to preferred side.
