### ISSUE TITLE
Files in overwrite folder?

### ISSUE THREAD

**Issue by breacherman** [Modorganizer2/modorganizer#476]
I've been following an outdated youtube guide where an older version of MO is used (currently using 2.1.4). 
After performing the mod cleaning procedures through SSEedit, he right clicks on the overwrite folder and creates a seperate mod of the files within. This folder contained addtional .esm's to what was in my overwrite, as he had 3 esm files above the SSEEdit folder in the Overwrite folder that I didn't have. My overwrite contains 5 esm.baclups within the SSedit folder (i assume he had them as well even though you don't see them).  
 I tried creating the separate mod containing the cleaned esm's but there was nothing in the mod once I created it. 
A commentor stated, "I just want to say that if you got the recent Mod Organizer then your ESMs will not show in overwrite folder. It will change it directly.
Since it appears I am not to create the mod out of the files in the overwite folder, what am I to do with them? I currently have the pylon thing with the exclamation point that states "there are files in your overwrite mod" seeming to indicate that I should be doing something with them.

Here is the part of the video in question in case I wasn't clear....
https://youtu.be/CqF22wJdTWY?t=663

screenshots
https://gyazo.com/13625ba3c22cdfdf8361dbe35e80e1f6
https://gyazo.com/4e2b50691d13a760a3a59e8e9dc63b89

**Comment by Project579** [comment]
Your overwrite only has inside the Backups from xEdit and its cache i usually move the xEdit cache to a dedicated/new Mod and then move the backups to the mod they come from.

**Comment by Project579** [comment]
also don't post these kinds of things on GitHub please go to the Discord, this place is for reporting bugs not teaching how to use the program.

**Comment by breacherman** [comment]
Discord? Hmm ok, sorry bout that and thanks for the reply.

**Comment by Al12rs** [comment]
Reopen if not concluded
