### ISSUE TITLE
Skse launches into skyrim launcher, and steam login

### ISSUE THREAD

**Issue by HimuraMai** [Modorganizer2/modorganizer#480]
Whenever I run skse64 in MO2 it will launch the Skyrim launcher instead, it can't seem to detect Skse64.
Another problem that's rather annoying is that whenever I try to launch any program in MO2 it will ask me to launch steam even though it's already running.

Mod Organizer 2.1.4
The last version. 
Windows 10, no updates since I updated MO.

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

Unfortunately,  the above has me confounded, I'm not a tech-viz of any kind, nor do I know if you need to be in order to understand USVFS whatever that is. I have no idea what they are trying to say.  As for logs there are none in the log folder in MO.

Nevermind it fixed itself somehow. I'll delete it when I can figure out how.

**Comment by LostDragonist** [comment]
Closing per user edit.
