### ISSUE TITLE
multiple profiles support Request

### ISSUE THREAD

**Issue by JFMillerUSA** [Modorganizer2/modorganizer#481]
Is there an environment variable like %BASE_DIR% but for other folders (ie: %PROFILES_DIR%).

Trying to setup multiple profiles for Fallout 4 with different mods.

**Comment by LostDragonist** [comment]
There is not.  The currently supported method for having different profiles with different mods is to create different instances instead.  This gets you a new set of profiles, mods, downloads, etc.  You can set up instances to share some stuff, like downloads, if you want.  

To access the instance manager, click the far left icon in the toolbar.

**Comment by Al12rs** [comment]
Closing, if you have more questions visit the Mo2 discord server
