### ISSUE TITLE
Cannot enable BSA files 

### ISSUE THREAD

**Issue by MessyMark** [Modorganizer2/modorganizer#482]
For some reason i cannot enable my bsa plugin and its making my game appearing exclamation marks

**Comment by Project579** [comment]
why can you not enable the plugin? what is the problem with it?

**Comment by MessyMark** [comment]
well because its in the archive section and its all grey out

**Comment by Zarggg** [comment]
MO2 does not suport direct toggling of installed BSAs. Make sure that the ESP file that loads the BSA is active.

**Comment by Al12rs** [comment]
Visit the Mo2 discord if you have more questions. This is not a bug, simply you need a plugin to load an archive
