### ISSUE TITLE
Implement ghosting of inactive plugins

### ISSUE THREAD

**Issue by flipdeezy** [ModOrganizer2/modorganizer#483]
# The problem

Hide inactive plugins feature in MO doesn't work

# Environment

*2.1.4
* N/A
*Windows 10 pro

**Comment by Project579** [comment]
What do you mean by hide inactive plugin?

**Comment by LostDragonist** [comment]
Pretty sure flipdeezy is talking about the "hide inactive ESPs/ESMs" option here: https://imgur.com/YiKUa9a

That feature hasn't been implemented in MO2.  In MO1, it essentially hid the inactive plugins at runtime.  This was done to avoid issues with having too many plugins as that can cause issues for some games.

**Comment by flipdeezy** [comment]
@LostDragonist is exactly correct

**Comment by Project579** [comment]
it will be replaced it in the future with a method similar to Wrye Bash Auto-Ghost.

**Comment by Project579** [comment]
so that other software like xEdit and Wrye Bash itself can still see hidden plugins to the game.

**Comment by flipdeezy** [comment]
That sounds awesome

**Comment by Al12rs** [comment]
tracked in #565
