### ISSUE TITLE
Archive Invalidation error

### ISSUE THREAD

**Issue by MessyMark** [Modorganizer2/modorganizer#484]
when i put on automatic invalidation check only one is green the others is all red but before i update the mod organizer it work perfectly fine

**Comment by LostDragonist** [comment]
What version of MO2 was working?  What version of MO2 is not working?  What is green?  What is red?  What game are you trying to manage?

There's a reason all that text is there when you create an issue.

**Comment by MessyMark** [comment]
the version im using is 2.1.4 the version that was working was 2.1.3 and only the first invalidation check work and the second and the third doesnt work and the game im trying to manage is Fallout New Vegas

**Comment by MessyMark** [comment]
hey is anyone here

**Comment by Project579** [comment]
You can come on the Discord we were discussing this just yesterday, LostDragonist may have a fix in a bit.

**Comment by MessyMark** [comment]
ok

**Comment by LostDragonist** [comment]
According to the discord conversation, all the stuff about green and red and invalidation checks is part of the installer for this mod: https://www.nexusmods.com/newvegas/mods/48222.  @MessyMark In the future, if you're talking about a specific mod, please start with that.  I had literally no clue what you were talking about.

The first check looks for bInvalidateOlderFiles=1 in Fallout.ini.  This may or may not work depending on how you have MO2 set up.  Local game settings must be disabled as the INI files are not redirected during mod installations.

The second check looks for "Fallout - AI!.bsa" or "ArchiveInvalidationInvalidated!.bsa".  This will not work as MO2 creates "Fallout - Invalidation.bsa".

The third checks sArchiveList in Fallout.ini for one of the BSAs above.  This combines the problems of the first and second checks and will not work.  

User reported success after this:

> So the temporary fix for AI seems to be: "I have to exit the game, go to the profile and tick the box again, save it, and open it again to make sure it took, then I can play".

Closing this issue as enhancements to AAI are already being worked on.
