### ISSUE TITLE
Endorsement state not updating

### ISSUE THREAD

**Issue by DankRafft** [Modorganizer2/modorganizer#485]
# The problem

With version 2.1.4 the endorsement state of newly added mods stays "unknown" when I activate "Check all for update".

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.4
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): IIRC 2.1.3
* Desktop OS/version used to run Mod Organizer: Windows 10, v1803

# Link to Mod Organizer logs

https://gist.github.com/DankRafft/8e6b47f7fea1b141ee6bd88592d2d2e8

**Comment by LostDragonist** [comment]
I believe this is an intentional change in 2.1.4.  The endorsement state should remain unknown for about 15 minutes after first downloading a mod.  Checking for updates after that should result in the heart popping up, allowing you to endorse or not endorse.

**Comment by DankRafft** [comment]
The endorsement state stays unknown even for mods I downloaded days ago. I don't think this is intentional.

**Comment by LostDragonist** [comment]
Okay, yes, I broke endorsement checks for new mods.  Apparently the Nexus can't tell us the difference between "never been endorsed" and "there's a temporary glitch where we screwed up and can't tell if you've endorsed something".  Bugger.

**Comment by MessyMark** [comment]
the archive invalidation doesnt work, when i turn it off then turn it on again the mod is still saying only 1 invalidation files is check

**Comment by LostDragonist** [comment]
Closing as this will be fixed in the next release
