### ISSUE TITLE
SSE - Some MCM menu don't appear in game

### ISSUE THREAD

**Issue by Yoplala** [Modorganizer2/modorganizer#490]
I don't know if it's a MO2 issue, but I have some mods that have an MCM menu but who don't appear in game.

I have reproduced the bug with only two mods : Violens and Heart Breaker, normally compatible, each with an MCM menu. Only the first loaded has an mcm menu that appears. Some friends have tested but they have not this issue. 

The common point of these mods, but I don't know if it's related, is that they have a uilib instance in the Interface folder and they need JContainer to save a profile. The skse.log say all the mod are normally loaded. I found this: http://forum.step-project.com/topic/13423-invisible-mods-in-mcm-menu/ , but the solution didn't work for me. 

I've tried a lot of things for the last three days : the console code (setstage SKI_configmanagerinstance 1), reinstall everything (MO, the game, SKSE, SkyUI, the mods), run as administrator, etc... I'm going crazy ;).

**Comment by Project579** [comment]
did you try waiting a lot in game?

**Comment by Yoplala** [comment]
Yes, of course ! :)

**Comment by Project579** [comment]
Did you try those two mods alone without MO2 involvement?

**Comment by Yoplala** [comment]
Hi
It's definitely not an MO2 issue , sorry. I tried with NMM and the problem is the same.

**Comment by Al12rs** [comment]
That is good to know, thanks
