### ISSUE TITLE
Add filter for mods containing Optional plugins

### ISSUE THREAD

**Issue by bchick1** [ModOrganizer2/modorganizer#496]
# The problem

When following established procedures for creating merged plugins (Mater's stand-alone merging tool)the original plugins must eventually be deactivated in MO2 (right pane or left<?>) after merged plugin is established as an active plugin. However, unless the plugin has resources (i.e. BSA then a red X icon is displayed) there is no indication that the plugin has been disabled (unchecked). Would SUGGEST the RED X be placed on ALL plugins where the ESP/ESM has been removed from the 'active' pane to the 'optional' pane in the 'Information' tab. This would clearly indicate that the plugin is deactivated. The little, tiny, MISSING grey checks in the boxes are insufficient.
# Environment
* Mod Organizer Version that exhibits the issue:  2.1.4
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):  N/A
* Desktop OS/version used to run Mod Organizer: MS Win 10

# Details
If necessary, describe the problem you have been experiencing in more detail.
Not a 'problem' per se, application is just difficult to see/use when deactivating plugins

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!
NOT REPORTING A BUG
## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!
NOT REPORTING A BUG

**Comment by Al12rs** [comment]
I'm not following, I suppose because I never used merge plugins (Mator discontinued support for it).
Can you show some pictures of the problem?

**Comment by Project579** [comment]
If i plugin is set to optional it is no longer there, it will just disappears from the load order (and the game for that matter) no need to mark it in some way, Regrading the adding of a red x on active plugins to me seems useless you can clearly tell if a plugin is enable or not, if you want you can use a style-sheet and make it yourself.

**Comment by Al12rs** [comment]
Should be addressed with https://github.com/ModOrganizer2/modorganizer-game_gamebryo/pull/19
