### ISSUE TITLE
Create Files in Mod instead of Overwrite didnt work

### ISSUE THREAD

**Issue by Kugane** [Modorganizer2/modorganizer#5]
I added FNIS in Mo2 & checked the option above. But Mo2 didnt copy the files in the specific folder (Mod).
The files get everytime in the Overwrite folder pasted

**Comment by pressure68** [comment]
I also get this same behavior when using FO4Edit or SSEEdit with MO2. Changed plugins and the original backups are always saved in Overwrite, as opposed the the original mod folder like it does with MO v1.

**Comment by simpson409** [comment]
same thing just happened to me.

**Comment by Al12rs** [comment]
That setting has been fixed in the (Al12 28/01/18) ModOrganizer.exe available in #builds in the discord channel. It still needs some testing.
