### ISSUE TITLE
Fallout instance shows Skyrim SE data

### ISSUE THREAD

**Issue by ANGRYWOLVERINE** [ModOrganizer2/modorganizer#500]
The MO2 when installed using either version installer or archive goes into another folder and grabs  up my  skyrim data game plus dlcs and displays that  those  and not the Fallout 4 data it was suppose to. show.It is installed the Fallout 4  folder which is a separate games folder that is not in the program folder. I am using windows 10 and did not have this problem with the old MO versions I am using the current MO2 version. I am going to either vortex or NMM.  .

**Comment by LostDragonist** [comment]
If you're new to MO2, as it would seem given your comment, then you may not be familiar with how MO2 can handle instances.  Here's a blurb about it:

> MO2 offers two different modes of use: Global instances and Portable instances.
With the term Instance we are referring to all the data specific to a modded setup, which would be: the mods, the downloads, the profiles, the overwrite folder, the executables, the user settings etc.

>The difference of the two modes is that with Global Instances MO2 avoids storing all the user's data (mods, downloads, loadorder, ini files etc) in the MO2 folder and instead stores them in separate folders in the user Appdata folder, which is the windows standard location for storing User data from a specific program. Mo2 then offers the user the possibility to move almost all the data from Appdata to a user defined location, that can be on a different drive altogether.

>Global instances are a good way to keep the modded setup files detached from the MO2 installation files so that if something happens that will need a reinstall of MO2 it will not compromise the modded setup data. Global instances allows the user to have multiple instances at the same time (of different games or of the same game) and all of them are accessible from any installation of Mo2 on your machine.

>A Portable Instance instead stores all the user data inside the MO2 installation folder itself (thus this requires that folder to be writable), which means that you can only have one Instance per MO2 installation. That instance will only be accessible from that particular installation. In this case as well the user has the choice to move most of the files in custom locations through the settings but not all of them (deleting the MO2 install folder will still compromise the modded setup because the modorganizer.ini is stored there). This completely avoids the use of the Appdata folder.

I'm guessing you have MO2 set up to use global instances.  You can change game instances, or configure new/old instances, by clicking the far left icon in the MO2 window.
