### ISSUE TITLE
[ENHANCEMENT] Replace Username/password in modorganizer.ini with Windows Credential Store.

### ISSUE THREAD

**Issue by LePresidente** [ModOrganizer2/modorganizer#501]
# Enhancement

Replace Username/Password in modorganizer.ini file with a more secure method 

Possibility use the https://github.com/frankosterfeld/qtkeychain project 
which is an Qt API to store passwords securely, on windows this will be Windows Credential Store

**Comment by Al12rs** [comment]
We should also consider what to do people with old saved passwords to avoid getting errors. Possibly delete old obfuscated password if present and store it encrypted

**Comment by Freso** [comment]
How will this work when switching to new Nexus authentication mechanism? (I'm all for this, by the way, just thinking that maybe too big changes shouldn't be made to this system while we know that the next iteration is "right around the corner" and we don't have all the details of it yet.)

**Comment by isanae** [comment]
Completed for both the nexus API key and steam password. There are no plans for putting the steam username in the credential store for the moment.
