### ISSUE TITLE
Error upon extracting mod for install

### ISSUE THREAD

**Issue by onimale** [ModOrganizer2/modorganizer#502]
# The problem

Stated In title

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.5
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 7

# Details

When i try to install CBBE it gets about halfway through the extracting bar and pops up an Error window that never gets the chance to load as it stops responding.
![error](https://user-images.githubusercontent.com/6852985/44627360-94690100-a8fa-11e8-9080-29956fcc3edc.PNG)

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/onimale/6004e0de4fbdcc11300162fa017e38ea

## MO Interface
https://gist.github.com/onimale/615b625be6b6939ee5f2f832babe9282

**Comment by Project579** [comment]
Normally this is caused by damaged archives.

**Comment by Al12rs** [comment]
Try downloading again?

**Comment by onimale** [comment]
Thank you for the help, I had tried to redownload but for some reason it didn't work the first time, but a third download did work.
