### ISSUE TITLE
Morrowind plugin requires local game settings to remain enabled

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#503]
# The problem

Trying to disable "local game settings" on a Morrowind profile will result in corrupting the profile's settings.

# Environment

* Mod Organizer Version that exhibits the issue: MO 2.1.5, should be all of them after MW support was added

# Details

Morrowind.ini contains part of the game's configuration (other stuff is stored in the registry), the plugin list, the archive list, and maybe some other stuff.  It's an important file for the game.

The current state of local game settings is determined by whether Morrowind.ini exists.  When local game settings is disabled, Morrowind.ini is renamed to Morrowind.ini\_.  When local game settings is enabled, Morrowind.ini\_, if it exists, is renamed to Morrowind.ini

The MO2 Morrowind plugin always writes the plugin list, and maybe some other stuff, to the MO2 profile's copy of Morrowind.ini.  There are no checks to see if local game settings are enabled or if the file exists.  This means that Morrowind.ini will always be created if it does not exist.  Therefore, local game settings will always be forced to enabled.  

Additionally, since the plugin list does not check for the existence of Morrowind.ini\_, the new Morrowind.ini is created blank, i.e., it does not carry over any settings from Morrowind.ini\_.  

# Suggestion

Either the Morrowind plugin needs to reworked to respect local game settings or the user needs to be prevented from disabling local game settings when Morrowind is the managed game.

# Workaround

To restore the previous settings after disabling local game settings:
1. Open the profile directory.
2. Close MO2.
3. Delete Morrowind.ini (size should be <1KB)
4. Rename morrowind.ini\_ to Morrowind.ini.
5. Delete any other errant files like "morrowind (1).ini\_"

**Comment by LostDragonist** [comment]
Should be fixed in https://github.com/ModOrganizer2/modorganizer-game_morrowind/commit/c7578b3c7fda9fcf58256de64e4b106ba7cf466b, plugin v0.2.1.  Needs some more testing before closing the issue.

**Comment by Al12rs** [comment]
Morrowind stores Saves and INI files in its game folder?

**Comment by KerberX** [comment]
Yes.
`%MorrowindDir%\Saves`
`%MorrowindDir%\Morrowind.ini`
