### ISSUE TITLE
Crashing on File Browser

### ISSUE THREAD

**Issue by AkkoNYR** [ModOrganizer2/modorganizer#505]
# The problem

First time using MO2 (2.1.5) on a new pc (Win10) and it crashes about 2 seconds after opening the file browser, specifically when it asks for a game to manage after first being installed. If I don't hit browse however, it does not crash. I installed both x64 and x86 VC. I've tried both the installer and archive. Tried adding it to exclusions in my anti-virus (Avast) as well disabling shields and running as admin. It is not installed a protected folder. I've tried installing it in multiple locations, both archive and installer.

Version 2.1.5
Windows 10 pro version 1803 (Build 17134.228)

USVFS
https://gist.github.com/AkkoNYR/5ddcd26d17d07f93d45e77fae5fb2ee7

MO Interface
https://gist.github.com/AkkoNYR/1d4bda311fb565d47d66ad7ffdb134f0

CrashDump
https://raw.githubusercontent.com/AkkoNYR/CrashDump/master/ModOrganizer.exe-15396.dmp

**Comment by LostDragonist** [comment]
Please see the "I have an Alienware/Dell computer and MO2 crashes!" section of our troubleshoot page: https://github.com/ModOrganizer2/modorganizer/wiki/Troubleshooting

**Comment by AkkoNYR** [comment]
That did it. Sorry I didn't see that troubleshooting page.
