### ISSUE TITLE
MO2 Profile plugins.txt Xedit issue

### ISSUE THREAD

**Issue by aplanetsabc** [ModOrganizer2/modorganizer#509]
# The problem

Default profile suddenly cannot use Xedit due to it being unable to read plugins.txt

# Environment

* LAtest
* Latest
* Windows 10

# Details

is able to read other profiles, but reading the default profile, even if deleting and recreating plugins.txt causes issues. (not fixed by a reinstall of either Xedit or MO2)

**Comment by LostDragonist** [comment]
This issue has basically zero useful information.  "Latest" is not a version as I can't trust that you know what the latest is.  Hell, even I don't what the latest is.  You have provided no logs.

The only possible guess I can make at this moment is that you have an anti-virus program that decided to mess with that particular file and none of the others.

**Comment by aplanetsabc** [comment]
So I solved it. (After 6 hours of testing rip) it was a specific mod I downloaded. When disabled ssedit was able to load the archive. V strange. Anyways, the latest stable release of mo2 is 2.1.5 in case you get any other morons like me

Alexander Harrison

**Comment by LostDragonist** [comment]
Any chance you can comment on which mod you think did this?  Or which version of xEdit you were using?

**Comment by aplanetsabc** [comment]
I checked with multiple versions of xedit. They all caused the issue. It had to do with a patch for blacksmith water fix (I think that’s what it’s called) that was flagged as an esl.

Alexander Harrison

**Comment by LostDragonist** [comment]
If you have any idea what the patch was for, or have a link to the specific patch, I'd be eternally grateful.  If mod can cause an error like this, we really need to know about it instead of just assuming it's a problem due to the mod.

**Comment by Sharlikran** [comment]
@aplanetsabc Was it [Blacksmith Forge Water Fix - Special Edition](https://www.nexusmods.com/skyrimspecialedition/mods/1291/)?

I didn't install the files, but they are all .esp files, none are esl files.

**Comment by Sharlikran** [comment]
No I don't think you corrupted it. Someone that uses MO2 tested it and flagging an ESP with the ESL flag didn't cause that error. Which file, or patch exactly did you install there are three different files at that link. I also found many other patches. Can you help provide a mod link and the file name?

**Comment by aplanetsabc** [comment]
The patch that cause the error was the CRF patch in the main file download section

**Comment by LostDragonist** [comment]
It looks like this issue is due to a bug in xEdit that can corrupt plugins that have an error during saving.  The corrupt, 0 byte plugin then throws the error as reported by the user.  

The cause of the error was trying to flag a plugin as ESL when it contained invalid form IDs for ESL plugins.  Assuming the plugin can be converted properly, the form IDs would need to compacted.

Once again, this issue would have been **much** easier to diagnose had the user provided logs per the issue template.  MO2 spits out an error "failed to parse plugin file <x>: file incomplete" when it reads a 0KB file.

**Comment by Sharlikran** [comment]
https://github.com/TES5Edit/TES5Edit/commit/3ef7ff6c5b94742c638e8f18f2f4c32e8e533b6f fixed in that commit
