### ISSUE TITLE
nmx.exe is missing

### ISSUE THREAD

**Issue by MessyMark** [ModOrganizer2/modorganizer#510]
im using mo2 version 2.1.5 and i try to reinstall the mod but it keep saying that acess to nmx.exe is denied

**Comment by LostDragonist** [comment]
There is nothing called "nmx.exe" in MO2 or accessed by MO2.  That's something on your computer that is interfering.  I have no idea what it could be as a Google search doesn't help.  I suggest searching your computer for this "nmx.exe" to try to see what it is.

**Comment by LostDragonist** [comment]
See if your nxmhandler.exe is being blocked by Windows.  This video might help.  https://youtu.be/CBurE8aLTxE

**Comment by MessyMark** [comment]
I check the nxmhandler it was not block but for some reason i still can move the mo2 archive but not the nxmhandler.exe in the archive
