### ISSUE TITLE
Corrupted plugin after saving during hotloading process in CK - Fallout 4

### ISSUE THREAD

**Issue by oddlittleturtle** [ModOrganizer2/modorganizer#514]
# The problem

Hot loading plugin corrupts into .tes file deposited to Overwrite directory when saving in Creation Kit for Fallout 4.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.5
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 10 Home, Version 1803 (OS Build 17134.228)

# Details

Got tired of the process of exiting Creation Kit, entering the game, exiting the game, and then waiting for CK to reload _all_ season pass ESMs while doing spot checking of a test cell that was giving me issues with crashing. Those particular crashes were on my end: nifs I'd created incorrectly. I was removing them one by one to see which one was giving me issues. Hot loading was my attempt to save time.

Followed steps to hot load plugin final time to check test cell after removing nifs with errors in them. (No crash when entering cell \0/ ) Finished up navmesh to cell and then when I saved in the editor, the file corrupted to .tes file type in Overwrite instead of saving correctly into .esp format. Yay.

**Unsure if the following is needed, but adding for completeness:**
(apologies if this is TMI?)

_Security software:_ 
All MO2-related .exe are white listed with Webroot

_file path to MO2:_ 
C:\Games\MO2 Fallout 4 
I have full control/access/permissions of the directory.

_file path to Fallout 4:_
C:\Steam\steamapps\common\Fallout 4\
I have full control/access/permissions of the directory.

_Mods enabled:_ 
See F4SE log

_CreationKitCustom.ini:_ 
https://gist.github.com/oddlittleturtle/d2f95677c0f21b3e2476c8f63d55c6b9

_Fallout4Custom.ini:_ 
https://gist.github.com/oddlittleturtle/994e766234bae076cd5698110b6d704b

_Papyrus Logs:_

1. https://gist.github.com/oddlittleturtle/3ac391b13fc56d70be9a811ffe49641b
2. https://gist.github.com/oddlittleturtle/84c5d7b0fb1c2f6b9712e2e1a716762c

_F4SE Log:_
https://gist.github.com/oddlittleturtle/5bf05f97cc95e611ae39dd14295e248b

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/oddlittleturtle/a06444f43a872508339776473c5271e0

## MO Interface
https://gist.github.com/oddlittleturtle/890806f35a1159a4ccec3d9af40f151e

**Comment by LostDragonist** [comment]
Since you didn't mention it, does this happen with the CK when MO2 is not involved?

**Comment by Al12rs** [comment]
Closing this for organization purposes, please reopen if you still have this issue.
