### ISSUE TITLE
Error when trying to launch LOOT through MO

### ISSUE THREAD

**Issue by loldev69** [ModOrganizer2/modorganizer#515]
# The problem
Attempting to launch LOOT through Mod Organizer fails, with error:
 
"Failed to spawn "LOOT.exe": failed to start process (the parameter is incorrect[87])

# Environment

The error is happening on version 2.1.5, running on up to date Windows 10.
However, the issue appeared out of the blue, as launching LOOT worked perfectly on the same configuration the day before.

# Details

Attempting to launch LOOT will result in a blank terminal window staying on screen for several seconds, titled [path to MO]\usvfs_proxy_x86.exe.
The window will then close and the error above will appear.

I tried checking LOOT launch parameters, but they seem correct: trying to launch without the --game parameter yields the same error in any case.

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/loldev69/fec331fdb4975ef67f2021249281f6c6#file-usvfs-2018-09-03_11-51-19-log

Log is very short and indicates a timeout error.

## MO Interface
https://gist.github.com/loldev69/96ee9ad0e26aff45674bd948507b8031

Nothing seems to be out of the ordinary here.

**Comment by Al12rs** [comment]
Could you try rebooting your pc?

**Comment by Freso** [comment]
What is your "Start in" set to in your LOOT application settings on MO? If it's not blank/empty, could you try making it empty?

**Comment by loldev69** [comment]
Tried rebooting, no change.
"Start in" was set to LOOT's install folder, blanking it caused no change.
Tried reinstalling LOOT, nothing.
I might try using window's sfc repair utility, but that's unlikely to help either.

**Comment by Freso** [comment]
Can you post a screenshot of the LOOT setup in MO?

**Comment by Al12rs** [comment]
Go in appdata/local and backup/delete the loot folder, run loot once from outside MO2, run Loot frol inside Mo2.

**Comment by loldev69** [comment]
The issue solved itself for no apparent reason, then returned (again for no apparent reason).

My LOOT setup in MO is as follows:
Title: LOOT
Binary: G:\Programmi vari\LOOT\Loot.exe
Start in: 
Arguments: --game="Fallout 4"
All three checkboxes below are unchecked.

**Comment by LostDragonist** [comment]
Any anti-virus software installed?  Avast, Bitdefender, Malwarebytes?

**Comment by DarkUncle64** [comment]
I had this same event happen after loading SKYUI 5.1, any chance your issue is related to that as well?

**Comment by Al12rs** [comment]
These issues should be fixed on 2.1.6, if that is not the case please reopen the issue

**Comment by genderneutralnoun** [comment]
I'm having this same problem on 2.2.1. I've been trying for the past two days to get this to work and I'm about ready to cry. (I'm using Skyrim SE.) SKSE64 and LOOT gives the same error, Bodyslide gives me the error "Could not load Setup.xrc". Notable is that I've also tried playing LE and it gives me the same error. It was working fine the other day, and now it's stopped. Please help?

**Comment by Al12rs** [comment]
@genderneutralnoun Please eiter drop by discord (https://discord.gg/6GKR9jZ) or open a new issue (discord is better).
