### ISSUE TITLE
MO2 and SKYUI 5.1 conflict.

### ISSUE THREAD

**Issue by DarkUncle64** [ModOrganizer2/modorganizer#517]
# The problem
Hi, I am having some difficulty with MO2 and SKYUI. I installed the mod build from SRLE LE and when I installed SKYUI things started going wrong. I was no longer able to use LOOT or most of the other executable's I had installed receiving the message " Failed to spawn LOOT exe failed to start process (The parameter is incorrect 87". As this happened just after installing SKYUI 5.1 (note I am using SKSE v1.7.3) i attempted to uninstall SKYUI and reinstall. When I reinstalled it 2 skyui folders showed up in my load order and removing one caused both to be removed. Next step remove skyui resulted in a folder that would not delete even with cmd prompt. I eventually got skyui loaded and finished the build but when in game I used the map and received an error about the wrong version being installed expected 5.1 but found 4.1. everything else seems fine and runs great so I again removed and installed skyui but all the executable's are down again. I am posting this here and with the SKYUI forum in an attempt to resolve the conflict. Also of note, when I try to use the sort button on MO2 I get two pop up boxes instead of one, one will clear the other has to be closed manually and crashes MO2.

# Environment

* Mod Organizer Version that exhibits the issue: Mod Organizer 2 (Archive) 6194 v2.1.5
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):N/A
* Desktop OS/version used to run Mod Organizer: Windows 10
# Details MO2 and Skyrim (Steam) are installed on a secondary SSD, I have used in MO1 in the past (over a year ago). 

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs
https://gist.github.com/DarkUncle64/5ef41ba179d0208654b231db31cbd686

**Comment by Project579** [comment]
Seems like your MO2 is blocked.

https://www.youtube.com/watch?v=CBurE8aLTxE&feature=youtu.be

**Comment by DarkUncle64** [comment]
No that is not an issue, I watched the install video and unblocked it at the start (I also just checked again to be certain). I have MO2 set to unpack BSA files (per the SRLE instructions) and I am wondering if that might be causing an issue (I am just to chicken to mess with it from fear it might do more damage and I spent several days on this build lol). I managed a "work around" for myself by removing SKYUI 5.1 and installing 5.0 then removing and reinstalling LOOT. It works (some MCM twitches in game) now.

**Comment by Project579** [comment]
keep BSA for core mods packed see if that helps, it may also be some incompatibilità with the SkyUI installer but that has worked until now.

**Comment by DarkUncle64** [comment]
I would like to update (just FYI) that though I had previously solved the issue with LOOT by a reinstall, today I received the same error code (Failed to spawn LOOT.exe failed to start process (The parameter is incorrect 87) and was again unable to launch LOOT or use the "sort plugins" function of MO2. After using the edit function for executable's to remove LOOT and then uninstalling LOOT from my PC (I even deleted the folder in app data) then restarting both my PC and MO2 LOOT has returned to the executable's list although the binary path and start in paths are blank. i just felt this might be something your team would want to know about.

**Comment by Al12rs** [comment]
These issues should be resolved with 2.1.6, please reopen if that is not the case
