### ISSUE TITLE
MO2 needs reinstall after every login to Windows

### ISSUE THREAD

**Issue by Leodriz** [ModOrganizer2/modorganizer#520]
# The problem

I'm not sure if this is a problem with Mo2 or with my Windows-profile but everytime I restart my computer or just log off an log in again Mo2 doesn't find my mods.
Only the mods stored in the overwrite folder are found. This is true for loot, fnis, skse. All executables i run from Mo2. To get it to work again I need to reinstall Mo2 and overwrite the existing install.
Do you have any idea as to what could be causing this? The only other strangeness i've noticed with my computer is that the mouse-settings in Windows doesn't save but resets to default on login.

If it seems to be aw Win-problem dou you know if it is possible to write a .bat file to automate the installation to install to the right folder automaticly.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.4
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Win 10 Home, 17134.228

# Details

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Edited: INserted link to usfs-log
https://gist.github.com/Leodriz/2c5e67e6f60b3dacc5358cb43c2afd63

## MO Interface
Editeted: inserted link to MOI-log
https://gist.github.com/Leodriz/ed0ef37ca11c260c9e4cbb91557bc832

**Comment by Leodriz** [comment]
Well, I cant find any logs in Mod Organizer and no way to enable logging. I have a folder named "logs" in my Mo folder but it is empty.
The Skyrim log is of no help with this since the problem is before skse starts and it the same with loot and every other executeble i run through MO2.

**Comment by Leodriz** [comment]
Ok, i found a mo_interface.log is this the one? It updates as i start MO but not when i run an executable.
This is how it looks after login to Win and befor re-install.
https://gist.github.com/Leodriz/ed0ef37ca11c260c9e4cbb91557bc832

**Comment by Leodriz** [comment]
Ah, I'm starting to get the hang of this i think. 
latest usvfs log, allso after login to win but before re-install of MO
https://gist.github.com/Leodriz/2c5e67e6f60b3dacc5358cb43c2afd63

**Comment by Al12rs** [comment]
Something is reverting your modorganizer.ini (which is in Appdata/local/modorganizer/Skyrim ) each time. I would suggest you try a portable installation so you don't use Appdata. Press the top left button and select portable by scrolling down (read what it means btw), now update your paths to the base directory you were using before

**Comment by Leodriz** [comment]
I've changed to portable and the logs now appears in MO's folders instead of appdata. But I still have the same problem. 
I have tried to log in and out of Windows a few times but each time I have to reinstall MO to get it to load the mods. :(

**Comment by Al12rs** [comment]
Closing for organization, if you are still able to reproduce please visit the discord server for help: https://discord.gg/6GKR9jZ
