### ISSUE TITLE
WB not starting if TEMP folder is on different drive (Win 10)

### ISSUE THREAD

**Issue by scar2801** [ModOrganizer2/modorganizer#521]
# The problem
Wrye Bash not starting from inside MO2. Wrye Bash Standalone Version 307.201807040057 is working on its own. But is not opening from inside MO2. It is showing an error "WryeBash_xxxxxx" (xxxxxx is random every time) folder or a file in it is opened in Another program.

# Environment

* Mod Organizer Version that exhibits the issue: MO2 v2.1.5
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro v1803

# Details

I have closed all the other programs and checked. Still this problem persists. WB can open on its own, but not with MO2.

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/scar2801/5645f3f3ec1fad82b2ae2811ed3d5e1f

## MO Interface
https://gist.github.com/scar2801/60d4c70269b8e06527e0533e536a3d0b

**Comment by LostDragonist** [comment]
Try creating a folder named "docs" in your real game directory.

**Comment by scar2801** [comment]
> 
> 
> Try creating a folder named "docs" in your real game directory.

Tried.
Same problem persists.

**Comment by TearsOfAMuppet** [comment]
I'm getting the identical error message.  It happens with both the.exe version and the Python version.

**Comment by TearsOfAMuppet** [comment]
I also just realized that before it crashes it creates the following file in MOO2's Overwrite folder, _tempfile.tmp with a size of 0 bytes.

**Comment by Project579** [comment]
thats normal WryeBash behaviour.

**Comment by TearsOfAMuppet** [comment]
I've got it fixed, though I'm not sure my solution will be of help to anyone else.  

Since most of the error messages regarding Wrye Bash being opened in another folder pertained to folder names that Wrye Bash was creating in the Windows TEMP folder (such as WryeBash_xxxx), I figured it may be related to the TEMP folder somehow.  I keep my TEMP folders on a drive other than the C drive, so I deleted their contents, set their location back to the Windows default location in the App Data folder, and rebooted.  

After that, all was fixed.  I have moved the TEMP folders off of the C drive once again and it still works perfectly.  I'm guessing there was some sort of issue going on with the Windows TEMP folder.

**Comment by Project579** [comment]
Thats the bug.

**Comment by Project579** [comment]
Temporary solution (for you google folks):

1. Open Wrye bash and let it crash;
2. Navigate to the real Data folder copy the Bashed Patch,0.esp; Docs folder and INITweaks folder to a new mod in MO2, if you do not find these folder or the file create them yourself.
3. delete the files in Data;
4. clear overwrite;
You can now run Wrye Bash freely.

**Comment by Al12rs** [comment]
@scar2801 can you still reproduce this issue with MO2.1.6 ?

**Comment by bragginsgt93** [comment]
I am having the same problem tried moving temp folder with no avail.  Also been trying 

[Temporary solution (for you google folks):Open Wrye bash and let it crash;Navigate to the real Data folder copy the Bashed Patch,0.esp; Docs folder and INITweaks folder to a new mod in MO2, if you do not find these folder or the file create them yourself.delete the files in Data;clear overwrite;You can now run Wrye Bash freely.]

No luck with that either keeps creating random temp folders then those are preventing anything further.

**Comment by LostDragonist** [comment]
@bragginsgt93 We found out at some point this was related to using Windows 10 build 1803.  We've been having people update manually to 1809 as we've been unable to fix this.  Google Windows update assistant if the "check for updates" button isn't helpful.

**Comment by Mandala02** [comment]
this issue happens also in 1809

**Comment by Sharlikran** [comment]
@Project579 By the way it's `Docs` and `INI Tweaks` (with a space) in the folder name.

**Comment by jarrard** [comment]
Latest MS update is 1903, I was using 1803 so hopefully updating works and resolves this issue. 

Wrye Bash for me yields this error on 1803 for me.

```
Traceback (most recent call last):
  File "bash\bash.pyo", line 322, in _main
  File "bash\env.pyo", line 652, in testUAC
  File "bash\env.pyo", line 570, in shellDeletePass
  File "bash\env.pyo", line 561, in shellDelete
  File "bash\env.pyo", line 527, in _fileOperation
CancelError: Action aborted by user.
```

**Comment by Sharlikran** [comment]
@jarrard This issue doesn't have anything to do with what you posted. Refer to #698

**Comment by Mrbebob1** [comment]
Just placing a comment in this thread to state that I also have this issue, the details I share are essentially just re-iteration of what the others had said previously.

Launching Wrye Bash outside of MO2 yields no issues and works without a hitch.
The error that pops up if Wyre Bash is launched via MO2 is this:
`Error! Unable to start Wrye Bash.

Please ensure Wrye Bash is correctly installed.

Traceback (most recent call last):
  File "bash\bash.pyo", line 322, in _main
  File "bash\env.pyo", line 652, in testUAC
  File "bash\env.pyo", line 570, in shellDeletePass
  File "bash\env.pyo", line 561, in shellDelete
  File "bash\env.pyo", line 527, in _fileOperation
CancelError: Action aborted by user.`

This error only appears if I select 'Cancel' when the message about the folder/file being in use by another program. Selecting 'Try again' just makes the message appear again.
![image](https://user-images.githubusercontent.com/29454185/61390946-9db4e080-a8b3-11e9-9f53-7fe5f0d7caaa.png)
![image](https://user-images.githubusercontent.com/29454185/61390978-aad1cf80-a8b3-11e9-844f-1ab2a6095f01.png)

**Comment by Mrbebob1** [comment]
This is the official statement the current MO2 gives regarding the issue on their MO2 dev Discord
![image](https://user-images.githubusercontent.com/29454185/61392048-ee2d3d80-a8b5-11e9-9a00-b403096d3fcf.png)

**Comment by Al12rs** [comment]
@Mrbebob1 did you test with the dev builds? Do you still have the issue there?

**Comment by Mrbebob1** [comment]
I updated to the most recent windows update and it works absolutely fine. When i did have the issues, my Windows 10 version was 1803. Now i've updated to 1903 and all is well.

**Comment by Mrbebob1** [comment]
I should also note that, after reading into the 1803 version, it apparently had a bunch of issues relating to updating as a whole as it would struggle to install windows update files and thus build an update backlog. So all in all, that version was just a buggy mess.
