### ISSUE TITLE
Editing plugin priority from pluginlist does not save changes in some cases

### ISSUE THREAD

**Issue by SuwinTzi** [ModOrganizer2/modorganizer#522]
Was checking list of merged plugins text file inside a mod folder created by Merged Plugins utility.  Then after closing the window, manually moved the specific plugins by using filter and imputing the desired priority number.  Upon reopening the mod folder in the left pane, checking plugin list text, and then closing the window, MO2 reverts the right pane load order to whatever it was before.  The plugins were disabled when they reverted.

It does not do so if I manually drag the plugin to the location.

Mod Organizer 2.1.5
OS Windows 7 Ultimate x64

**Comment by LostDragonist** [comment]
> the specific plugins by using filter and imputing the desired priority number

I did not know that was a thing.  That appears to have several problems associated with it.  For example, it breaks the enforced ordering of primary plugins, masters, and non-masters.  You can also try to set a negative priority or a priority larger than the number of plugins.

This specific problem happens as the plugins.txt and other applicable files aren't being written when the priority is changed.

Honestly, it kind of looks like the manual entry should just be disabled.  But maybe it can be fixed to work correctly.

**Comment by LostDragonist** [comment]
It looks like the mod list allows manual editing of the priority and does so in a correct manner.  Hopefully the plugin list can copy its implementation.
