### ISSUE TITLE
Mod URLs are not updated correctly

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#523]
Tested with v2.1.6, dev build 1, patch 1

The URL stored in a mod's meta.ini can be incorrect.  For example, mod 9822 ended up with a URL of http://www.nexusmods.com/skyrimspecialedition/mods/1523/.  Mod 1523 is installed.  In this case the URL for mod 1523 is correct.  

The primary use of the URL appears to be enabling a "visit web page" option in the mod's context menu.  This is used when the Nexus ID for the mod is invalid (0 or less).  

Steps to reproduce aren't known at this time.  Will investigate.

**Comment by Al12rs** [comment]
Damn because of this little issue I can't use the URL value as replacement for the nexus link. Because people will have a lot of mods with random urls.
I will look into this a bit
