### ISSUE TITLE
Long plugin setting names get truncated

### ISSUE THREAD

**Issue by Freso** [ModOrganizer2/modorganizer#524]
# The problem

Some plugins have long names for some settings leading them to get truncated. There's no way to adjust the width of the column they're displayed in, and since they don't have descriptions either, it makes it near impossible to guess what some of them do.

![billede](https://user-images.githubusercontent.com/177659/45611964-a6edda80-ba61-11e8-82f2-b1803cc7ce0e.png)
![billede](https://user-images.githubusercontent.com/177659/45612019-db619680-ba61-11e8-8fcf-b27204814de0.png)

# Environment

* Mod Organizer Version that exhibits the issue: MO2 v2.2.0 Dev Build 4
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): None that I know of…
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro, version 1803, build 17134.285

**Comment by Al12rs** [comment]
Should be fixed by https://github.com/ModOrganizer2/modorganizer/commit/4eaa0d16bb02bb08d0bde75a3b767e8f10b4559c
needs checking.

**Comment by LostDragonist** [comment]
[MO v2.1.6](https://github.com/ModOrganizer2/modorganizer/releases/tag/v2.1.6) has been released and this bug should be fixed. If anyone runs into this again, please submit a new issue.
