### ISSUE TITLE
Failed to start process (The Parameter is incorrect. [87]) (Fixed?? Restarting my computer seemed to fix it)

### ISSUE THREAD

**Issue by Timcanpy14** [ModOrganizer2/modorganizer#526]
# The problem

Can't start up any programs, giving me the error in the title. 

# Environment

* Mod Organizer Version that exhibits the issue: v2.1.5
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10

# Details

Not letting me run any program in MO. Even LOOT, Skyrim, Skyrim Launcher, ect. 
A command prompt pops up for a few seconds then dissappears and the error pops up.
Tried editing the binary files and still does nothing.

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

I dont know where to find the USVFS logs.

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

Im new to modding with MO so i dont know where to find the logs, sorry.

**Comment by Silarn** [comment]
Yeah, this is a pretty common issue. Probably either a hung hooked process or the windows event logs. Restarting will fix it.

**Comment by SALFATOR** [comment]
I'm having that issue and a restart not fixing it for me

**Comment by Al12rs** [comment]
@SALFATOR this is usually caused by your Antivirus eating the Mo2 files. Disable AV, install Mo2 again to make sure you have all the files and see if it works

**Comment by SALFATOR** [comment]
> @SALFATOR this is usually caused by your Antivirus eating the Mo2 files. Disable AV, install Mo2 again to make sure you have all the files and see if it works

Is it safe to reinstall with all my mods already in use  ?

**Comment by LostDragonist** [comment]
@SALFATOR Yes.  As long as you don't delete your mods, they'll still be there.

**Comment by SALFATOR** [comment]
@LostDragonist  @Al12rs   It's works again Dears .. !  Thank you so much.
