### ISSUE TITLE
MO2 wont start either Skyrim SE or SKSE64

### ISSUE THREAD

**Issue by Nymra** [ModOrganizer2/modorganizer#530]
# The problem

If I run SKSE64 or Skyrim SE through MO2 the small window appears "MO is locked et.c" 
but then after some time... nothing happens and the window disappears.

I can run the Skyrim SE Launcher through MO2 normally and the game also starts.
I can also run SKSE64 when launching the exe directly, but then I have no mods...

# Environment

latest version of MO2
I had no similar problems with MO1 and Oldrim ever.
WIN 10

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS
no idea what this is? 

## MO Interface
cant find any logs?!

**Comment by Project579** [comment]
You have an outdated mod.

**Comment by Nymra** [comment]
> You have an outdated mod.

Thx.
I cornered it and... disabled it. Works now :-)
