### ISSUE TITLE
MO2 won't launch Oldrim and the mods won't work

### ISSUE THREAD

**Issue by DaxusDragons** [ModOrganizer2/modorganizer#533]
So basically I've been testing a few mods and when I was launching Oldrim it didn't work so I used steam and it worked but when I started playing non- of the mods were work at all ,so please tell if something went wrong with the system or something I did

**Comment by SuperSandro2000** [comment]
You need to launch it tough steam and you didn't provide logs

**Comment by Al12rs** [comment]
Better if you contact us through discord: https://discord.gg/cYwdcxj
