### ISSUE TITLE
Download speed only updates when hovering mouse over the download

### ISSUE THREAD

**Issue by krisser143** [ModOrganizer2/modorganizer#538]
# The problem

Whenever I download something, the download speed will only update whenever I hover my mouse over the item that is downloading

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.5
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10

# Details

It also updates the download speed every time I move my mouse just a little bit, while hovering over the downloading item.

# Link to Mod Organizer logs

## USVFS
None

## MO Interface
https://gist.github.com/krisser143/20cd10f0f900765bb866a8e0f9c02bd5

**Comment by GioGr** [comment]
and progress for me

**Comment by Al12rs** [comment]
Fixed in #606
