### ISSUE TITLE
Mod organizer lock mod binded on wrong process

### ISSUE THREAD

**Issue by shiro-42** [ModOrganizer2/modorganizer#541]
# The problem

# Environment

* Mod Organizer V 2.1.5
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro 1803

# Details

I have opened wrye bash inside inside Mo2 then I put it in background, I launched chrome and then I closed wrye bash but mod organizer get stuck in lock mod saying chrome was still running the problem is I didn't opened chrome with mo2

# Link to Mod Organizer logs

## MO Interface

```

01:11:54 [D] Spawning direct process < "X:/steam/steamapps/common/Fallout 4/Mopy/Wrye Bash.exe" , "" , "X:/steam/steamapps/common/Fallout 4/Mopy" >
01:11:54 [D] Waiting for spawned process completion : Wrye Bash.exe (6092)
01:13:13 [D] Waiting for usvfs process completion : chrome.exe (12952)
01:13:32 [D] Waiting for process completion successfull
01:13:32 [D] C:\Users\beydo\AppData\Local\ModOrganizer\Fallout 4\profiles\Default\lockedorder.txt saved

```

Sorry for the english, I just want to report you in case you didn't know I don't have checked if it was already reported.

**Comment by Project579** [comment]
That is chromes fault not MO2 since they implemented the malware scanner MO2 will hook it due to the fact that it is actually using those files while scanning.

**Comment by Al12rs** [comment]
We know this and have things in mind on how to fix, just need the time and developer manpower
