### ISSUE TITLE
Wishes: Brief notes and a monospaced font

### ISSUE THREAD

**Issue by adrobkov** [ModOrganizer2/modorganizer#545]
I'm sorry, I just don't know how much more to write! I have only desires, not bugs.. If I may...

Hello! I can not imagine interaction with the game without this miracle Manager.
He's perfect! But, as they say, there is no limit to perfection...
I would really like to see some functionality in future releases, if there is such an opportunity.. In General, I have a lot of ideas, but I will not voice them all... I hope my English is more or less clear. And I apologize if I write the wrong way...
So, to dreams:

Support for monospaced font. Or the ability to choose a font in the settings. If it is, then tell me. I didn't find it in the theme file. Since such fonts have a crossed-out 0 and the width of the letters is the same, which will add visual convenience.
Additional field "Short comment" with full display of information in it. I use TotalCMD and it has the ability to write a comment by CTRL+F2, which can be seen in a different display. Current comments are different for long text and description and work fine. It would be convenient to write notes in it, such as "not compatible with that", "be Sure to ship first" or decoding the action.
If you are interested in other suggestions, how rude it sounds, let me know and I will be happy to describe them in detail.
Thank you very much for your work!

I wrote there https://github.com/TanninOne/modorganizer/issues/1186 , but apparently there's no one there.(

**Comment by SuperSandro2000** [comment]
To answer your last paragraph: that is the Modorganizer 1 repo and there is no one cause it is dead.

**Comment by Al12rs** [comment]
Hi, making suggestion here is totally fine, usually it's best to use the title to describe the wanted feature so that it can be easily recognised. 
About the font, I'm certainly not knowledgeable on this aspect but I'm 80% sure that you can set custom fonts using the stylesheets. There are even some Mo themes that use Skyrim like fonts etc.

About the comment thing, I'm not really sure what is that you want to comment exactly and how the comment should be accessed etc.
Right now the mods have a "Notes" section accessible by double-clicking on the mod and switching to the "Notes" tab. 
If a file has a note a special flag will be added to the mod in the modlist. Hovering with the mouse over that flag will show the content of the Note.

Does the existing Note system do what you wanted? If not what should be changed to make it better?

**Comment by adrobkov** [comment]
Thanks for the replies!
I've tried a few themes, but nowhere in stylesheets have I found a mention of a font where it could be specified.. Unfortunately..(
The last few years I use the theme UI-Tweaks...

As for the comments that are built into the organizer, I know and use them, but for me personally their disadvantage is that you need to hover the mouse over the icon, and then a hint with the content of the comment will appear. And I would very much like it to be a whole column on which it would be possible to sort and write useful information, so that it was always in sight.
As an example, here is a screenshot of comments in TotalCMD, where I store information about requirements and dependencies...
![image](https://user-images.githubusercontent.com/6213012/46829583-d533b100-cda6-11e8-8ed2-8258fb5415bc.png)

**Comment by adrobkov** [comment]
I changed the title to more understandable). Excuse me!

**Comment by adrobkov** [comment]
I have more than 3000 folders with mods in MO2, it is quite time-consuming to remember everything. But if it is to write in a name, it is very long...

**Comment by Al12rs** [comment]
Thanks @6788-00 .

Regarding comments I see what you mean and it was actually proposed by another developer as well. I will add it to the list of things to do. 

How long does TotalCMD allow comments to be? I assume no newLine is allowed

**Comment by adrobkov** [comment]
Thank you! The font works))))
The TotalCMD comment length is limited, if I'm not mistaken, to 512 characters. There's a multiline, but in MO2, it's not needed.
I don't know about others, but personally I think 512 characters per line would be ideal... I have a 4k monitor, and I want to have lots of information, if space allows. Besides, I like small things...

Thank you! Very cool! You reassured me! I'll wait!
