### ISSUE TITLE
ModOrganizer2 and Bodyslide Problem

### ISSUE THREAD

**Issue by gothsome** [ModOrganizer2/modorganizer#547]
Hello,

i have a problem with via Bodyslide created texture:
When i batch build evereything gets created in the override folder, and in the game the clothes are changedbcorreclyt, but the nude body didnt change like i am used from skyrim with mod organizer.

When i just klick on build in bodyslide with the CBBE anderen my preset the femalebody file changes to the right cration date in the vfs Data folder and override folder.

I use the MO2 from Nexus and CBBE for Fallout 4 on W10 pro x64.
The Mod i created from the override folder with the custom textures ist at the bottom with the highest Numbers with no file conflict - itself overrides from CBBE but dont get overwritten from any other mod.
The MO2 root folder ist not in the game directory and i reinstalled everything.
I switched from NMM, there worked everything.
 
I did evereything like i was used from skyrim with MM and BS.

Thank you in advance!
Matthias Dürre

**Comment by Al12rs** [comment]
We have released a MO2 build that could possibly fix this, could you please test it out?
https://discord.gg/MB3CyMH

**Comment by Al12rs** [comment]
Closing this for organization, please reopen if you can reproduce
