### ISSUE TITLE
There's no way for a plugin to tell MO to ignore the "Create Files in Mod instead of Overwrite" setting when launching an executable

### ISSUE THREAD

**Issue by AnyOldName3** [ModOrganizer2/modorganizer#548]
# The problem

There's no way for a plugin to tell MO to ignore the "Create Files in Mod instead of Overwrite" setting when launching an executable. All other executable settings can be overridden/ignored, but this one can't as it's newer and seems to have been forgotten when the setting was added.

This is causing problems with the upcoming FNISTool on machines where this setting has been set (I didn't think to test this as, again, all of the other settings can be overridden, so it never crossed my mind that there might be one which didn't).

# Environment

* Mod Organizer Version that exhibits the issue: All pre-2.2
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): Whichever was the last not to have this setting.
* Desktop OS/version used to run Mod Organizer: Windows 10

# Details

[`MOBase::IOrganizer::startApplication`](https://github.com/ModOrganizer2/modorganizer-uibase/blob/Develop/src/imoinfo.h#L263) should be given an extra parameter saying whether to ignore or respect this setting (and maybe another saying which mod to use instead, if any).

# Link to Mod Organizer logs

## USVFS
N/A

## MO Interface
N/A

**Comment by LostDragonist** [comment]
Implemented in commit b1af3eed10e65b6d39a038d5ccecc687ab94bff2

**Comment by AnyOldName3** [comment]
Are there the corresponding UIBase and plugin_python commits yet?

**Comment by AnyOldName3** [comment]
Actually, I'm checking myself:

* UIBase: https://github.com/ModOrganizer2/modorganizer-uibase/commit/e8e316b32489341403e40adb5d98e06765d6c4f4
* plugin_python: https://github.com/ModOrganizer2/modorganizer-plugin_python/commit/3eb85cd17fc629475afb256d78e2444cf054e2ef

The FNISTool seems to have been updated, too: https://github.com/ModOrganizer2/modorganizer-fnistool/commit/6c0eab201f69f742908b81f32cb2f88e135c3e27#diff-60d2694784058007285d53031ef509b8

**Comment by Al12rs** [comment]
2.2.0 released on nexus. I'm guessing this is fixed?
