### ISSUE TITLE
MO2 wont log into nexus after no internet

### ISSUE THREAD

**Issue by D-reads** [ModOrganizer2/modorganizer#550]
I had set-up MO2 to log into nexus - Automatically log-in to Nexus, checked, name & pass entered. Which I'm pretty sure was working until I fired up MO2 with no internet connection. I got a pop-up warning about could not log in, Which I dismissed. Now it doesn't log anymore when clicking the globe icon (with connection). I tried clearing cache & re-ticking auto log in & still nadda. Sorry no logs.

**Comment by Al12rs** [comment]
Clearing the cache should fix this, in any case the login system was completely remade in new Dev builds on discord. If you still have problems feel free to reopen.
