### ISSUE TITLE
MO2, Radeon R9 graphic cards, Morrowind Results in Black Screen

### ISSUE THREAD

**Issue by rando-dude** [ModOrganizer2/modorganizer#551]
# The problem
MO2 + Radeon R9 graphic cards + Morrowind = Black screen on game launch when a certain amount of mods are selected

# Environment
Versions tested 2.1.3 - 2.1.5
OS is windows 7 64 bit

# Details
There seems to be a limit to how many mods can be selected (even if the mod has only mesh and texture replacers) that results in a black screen on game launch, sound plays and the game is running, just no display.

Following the step guide, I can only select roughly half the mods (in any combination) for the game to run
Game works fine if I put all the mods directly in the game files folder
As a test I copied the entire mo folder to a different PC with a different card and the game works fine
Also tested with the mo folder both inside and outside the game directory

# Link to Mod Organizer logs
https://gist.github.com/rando-dude/6381c6606be68567d2e3cc440bf97793
https://gist.github.com/rando-dude/295ed2b0d34312e39e290675eb622a33

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by Alyndiar** [comment]
Here are my logs for the same problem. My configuration is very similar to OP.
[usvfs and mo_interface logs](https://gist.github.com/Alyndiar/eea922d76650e950c96f7b6cf770cab6)

**Comment by madmax02** [comment]
Same problem here, same OS/graphics card, using MO2 version 2.1.6
Recently updated to windows 10 and the problem disappeared.

**Comment by Al12rs** [comment]
Anyone able to reproduce with Mo2 v2.2.1?

**Comment by Al12rs** [comment]
We need debug level logs of this issue on 2.2.2.1 or above.

**Comment by isanae** [comment]
Reopen if the problem still occurs.
