### ISSUE TITLE
Unicode characters in MO2

### ISSUE THREAD

**Issue by adrobkov** [ModOrganizer2/modorganizer#552]
Hello!
I had a little problem. It is not very critical, but there may be a way to solve it quickly in my system...

# The problem
I use their font, which added to their characters provide a convenient shorthand for certain moments, for certain tasks and facilities.
All characters are entered using the keyboard "ALT" + "+" + "character Code" (for example, 203A), if the registry key type add REG_SZ and the value 1 in the branch HKCU\Control Panel\Input Method\EnableHexNumpad.
![image](https://user-images.githubusercontent.com/6213012/46945975-f7675080-d07e-11e8-860c-552a36a81fec.png)
In addition, some abbreviations occupy a single character and are the basis. As, for example, SKSE - ⒮ (code 24AE).
The font is assigned to the system as the primary font and is displayed correctly everywhere.
![image](https://user-images.githubusercontent.com/6213012/46945994-077f3000-d07f-11e8-9268-6470d02111e4.png)
But in the log, does not show these characters, and when you unpack the BSA archive, it complains that can not find the path. I understand that the problem is third-party symbols. But is there any chance to solve and somewhere else this font to register, to correctly perceive them.

Thank you in advance, and I apologize for the insolence...

**Comment by Al12rs** [comment]
Can you still reproduce with the latest dev builds from discord: https://discord.gg/ucVRQPV ?

**Comment by Al12rs** [comment]
Use the new Notes field for custom stuff like this. The mod name is actually the name of the folder on disk and you should avoid naming folders with weird names if you don't want programs to fail on you.
