### ISSUE TITLE
Crash on 'install a new mod from an archive'

### ISSUE THREAD

**Issue by Davastating** [ModOrganizer2/modorganizer#554]
# The Problem
Mod Organizer crashes when I click on 'install a new mod'. There's the 'choose mod' popup but then immediately crashes.

# Environment

* Mod Organizer Version that exhibits the issue: v2.1.5
* Desktop OS/version used to run Mod Organizer: Windows 8.1

# Details

On a new installation of Mod Organizer the 'install a new mod' function works fine, but after restarting the program I can't install any new mods because when I click on the 'install a new mod' button the popup for 'choose mod' opens but then the program immediately crashes.

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/Davastating/08310b00722ca6c0f0452152d9f0cc19#file-usvfs-2018-10-17_19-42-23-log

## MO Interface
https://gist.github.com/Davastating/08310b00722ca6c0f0452152d9f0cc19#file-mo_interface-log

**Comment by Davastating** [comment]
![unbenannt](https://user-images.githubusercontent.com/38959343/47114775-13c0e400-d25d-11e8-8a87-50a1557f4f7d.JPG)

**Comment by Project579** [comment]
This might be related to your Antivirus blocking the MO2 installer.

**Comment by Davastating** [comment]
I just found this [Troubleshooting](https://github.com/ModOrganizer2/modorganizer/wiki/Troubleshooting)
I updated Dell Backup and Recovery and now it works.
Sorry for not looking there first! I used the search function but that didn't show up.
