### ISSUE TITLE
MO2 loads Textures/Meshes/SKSE plugin but not other esps

### ISSUE THREAD

**Issue by SuwinTzi** [ModOrganizer2/modorganizer#555]
# The problem

After starting SKSE through MO2, none of the plugins load in-game (Classic Skyrim).  I get the textures, the meshes, and SKSE plugin mods, but not Alt start, not IA startup messages, etc.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.5
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 10

# Details

Recently fixed MO2 not virtualizing after upgrading from Win7 to Win10, now I have this issue.  As stated above, the modded textures, meshes and SKSE plugins are working, but not any actual esps.

I have MO2 installed in C: and Skyrim in D:

At this point I'm ready to roll back to Win7

Methods:
Troubleshooting FAQ was checked and even Windows Defender fully disabled, no go.
Skyrim SE loads plugins properly and is installed on C: drive, moved Skyrim LE to C:, still doesn't load plugins.

## USVFS
https://gist.github.com/SuwinTzi/831c2f5efd10aa4e2a581b62447e1b41

## MO Interface
https://gist.github.com/SuwinTzi/61c837164abe2c87a758ef7dfe169d64

**Comment by Al12rs** [comment]
Are you able to reproduce with 2.1.6 ?

**Comment by SuwinTzi** [comment]
Have not tried yet, gave up around Nov 2018?

Will try again, sometime next few days, just did a clean install of Windows
10

**Comment by Al12rs** [comment]
Closing this for organization purposes, please reopen if you still have this issue.
