### ISSUE TITLE
Feature Request: Restore ability to access new files

### ISSUE THREAD

**Issue by BadDogSkyrim** [ModOrganizer2/modorganizer#559]
# The problem

In the old MO, I could open CK through MO and access files that were created after I launched CK. This is important because if I'm modding, I'm often creating new nifs and such and want to reference them from the CK. That used to work. Now if I add a file to a folder and try to select it from the CK, I can see it in the folder but when I select it I get a "file not found" error. I have to close the CK and re-open it, which is very slow and makes the whole modding process a drag.

# Environment

MO 2.1.3 shows the issue; MO 1.* did not
Windows 10

**Comment by Al12rs** [comment]
Could you please test if this happens even while using the latest version of Mo2? Which would be the 2.1.5 available on Nexus, while you seem to be using 2.1.3. We fixed a number of issues in the meantime

**Comment by BadDogSkyrim** [comment]
Apologies, I am using 2.1.5. I just got it wrong in the post. Windows 10. Using it on oldrim CK--does that make a difference? Running in user mode, no compatibility mode.

I assumed this was just a known behavior change. No?

**Comment by Al12rs** [comment]
No, this is not by design (if I'm understanding the situation correctly).

We have done some more fixes to the virtualization library, thy are available on [discord](https://discord.gg/MB3CyMH) in the latest dev builds  2.1.6 (which we hope to release soon). Could you test and report if it works now?


If not would you be so kind to supply the log files for us to analyze:
```To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".
Before sending any Logs make sure the Log Level is set to Debug in Settings\Diagnostics, then close MO2 and clean the logs folder, after that you can reopen MO2 and reproduce the problem. 
Once done, close MO2 before sending or examining the logs as they are finished writing only after the program is closed; after you have finished testing setting the log level back to default is recommended.

You should always send the mo_interface.log file as that one contains the general information of your setup, for the usvfs log, you should upload the latest one if the issue is about programs started through Mo2.

You can drag and drop the logs directly on github to send them (tip: zip them if they are too big). https://cdn.discordapp.com/attachments/458597400638914563/458728891620524032/unknown.png
```

**Comment by Al12rs** [comment]
Wait, when you say add a file or folder, are you doing that from explorer? Or from MO2? 
That is a big nono.
You should not interfere with the vitualized files and folders  from outside the hooked programs. 
What you could try is to add files and folders from another hooked program (something that isn't really supported but at least the library was build to handle it), for example using FreeCommander as a explorer alternative. Even in this case you would still have to to only modify files from the game/data path, not the MO2/mods/modname/modfile path, as access and edits to that path are not monitored by the library but only the game/data ones are. So updates to the mods/modfile paths are not registered by the library.

**Comment by BadDogSkyrim** [comment]
BTW, the same thing happens if I try to override a file without reloading. If there's a file in a mod and I try to create a new version in my overriding mod, I get the same behavior.

**Comment by Al12rs** [comment]
How do you create these files? If you do so from within the CK then the fact that you can't access them later is a bug and we would need logs to fix it. 
If you are using Mo2 or explorer to create those files then you are not supposing to be doing that. The lock dialog that shows up when you start a program from mo2 is there for that reason.

**Comment by BadDogSkyrim** [comment]
Well, not explorer, but outside tools not running through MO. Create a nif in blender, export, load up in CK. Since I can only run one tool at a time through MO, that's the only way to do it. 

Are you saying this never should have worked? Because in MO 1.* it worked fine. If it's not supposed to work I haz a sad. Loading up CK is so slow I don't want to be jumping in and out all the time.

**Comment by Al12rs** [comment]
Start blender from Mo2 and save the nod to the data directory, it should work. You can unblock Mo2 to start another program and they should share the virtual folder. It's not something we officially support though so there might be some issues.

**Comment by BadDogSkyrim** [comment]
Huh. Okay, I've done that by accident and thought I was inviting a core meltdown or something. I'll give it a try.

**Comment by Al12rs** [comment]
The thing is that usvfs (the virtualization library) keeps the mapping of all the files in the virtual folder in shared memory between the hooked processes, so if a hooked program changes a file in the virtual folder all other hooked programs will be able to see the same change.

 What usvfs does not support is external changes, when programs that are not hooked by usvfs change the files in either data or in the mods folder.
Also no program, even the hooked ones should access the mods folders and files directly, the should only do so from the virtual folder. Usvfs will not monitor calls done to mapped files so if a madden file is delete usvfs would not know this and still point to a ghost location causing errors, while if the file is deleted from the data folder then usvfs can properly delete the mapping from it's internal registry.

**Comment by BadDogSkyrim** [comment]
That part makes total sense to me. And I assume files I create from hooked programs will go in Overwrite or in a mod folder, if I set that up. Playing now.

**Comment by Al12rs** [comment]
That is correct

**Comment by BadDogSkyrim** [comment]
I've been doing this and it's great. Occasionally CK quits when there's a lot of simultaneous disk access, but CK is squirrelly anyway.
