### ISSUE TITLE
MO2 Launches Game in a tiny window.

### ISSUE THREAD

**Issue by Ashotep** [ModOrganizer2/modorganizer#560]
# The problem

MO2 launches the game in a tiny window taking up a corner of my screen.  If I use Bethesda's launcher it starts normally.  If I used the direct link to F4SE it will launch normally.  The only time I run into a problem is when I use the F4SE link from within MO2

# Environment

* Mod Organizer Version that exhibits the issue:  2.1.5
* Desktop OS/version used to run Mod Organizer:  Windows 10

**Comment by LostDragonist** [comment]
MO2 keeps its own copy of the game's INI settings.  You can set up the game settings by running the launcher through MO2.  You can also disable this feature by opening the profiles dialog (looks like an ID card) and unchecking local game settings.
