### ISSUE TITLE
Crash on CRC error

### ISSUE THREAD

**Issue by SYNStack** [ModOrganizer2/modorganizer#563]
# The problem

When attempting to install a corrupt archive that causes 7zip to throw 'CRC fail', MO2 crashes. Sometimes it displays a "CRC Error" message, sometimes it doesn't, but crashes regardless.

Expected: MO2 should display "CRC Error" and continue on its way.

# Environment
v2.1.6 build 4
Windows 7 x64 Ultimate

# Details

User attempted to install a corrupt 'New Vegas Reloaded' archive that was off by a byte. 
![Byte](https://i.imgur.com/5zWRV12.png)

![MO2/7zip](https://i.imgur.com/UPhGIzX.png)

## Reproduce: 
Install broken archive: https://cloud.synstack.org/s/9pAcaMbAPRMSiMd

The working archive, for comparison, can be found at https://www.nexusmods.com/newvegas/mods/65525?tab=files

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/SYNStack/030be11275c7deb82e3a65553ec418fc

## MO Interface
https://gist.github.com/SYNStack/51a378f09f27780b501c550fa2f1d04e

## Crash Dump
https://cloud.synstack.org/s/zLXx2Wn5BFLxA7a

**Comment by LostDragonist** [comment]
Fix is pushed to Develop.  Reporter has verified the fix works.
