### ISSUE TITLE
MO2 Installer may not extract all files

### ISSUE THREAD

**Issue by Lucidi0us** [ModOrganizer2/modorganizer#567]
# The problem

When installing MO2, some files will not be extracted to the install directory.  There is no error when this happens, it just misses a portion of the files.  I only noticed because MO2 reported that the Fallout 4 plugin was missing.  Opening the installer with 7-Zip (or other zip program except Windows' built-in zip support) will allow you to manually extract missing files into the install directory. 

I believe this is related to the know issue in Windows 10 with zip files that Microsoft claims will be fixed in November.  I can only imagine the odd issues people may have when missing a couple important files, so I wanted to report it in.

# Environment

Windows 10 Pro 64-bit fully up to date as of 1/1/2018 (Build 17134.345)

**Comment by Al12rs** [comment]
I have not noticed any of this, Mo2 uses a built in 7zip library.
Can you please provide steps to reproduce this and make sure that something else was not at play?

**Comment by Lucidi0us** [comment]
Sure.  As I was attempting to solve another issue with Fallout 4 crashing only when MO2 executes it.   I decided to try removing MO2 and reinstalling it using "Mod Organizer 2 (Installer)-6194-2-1-5.exe".

The install process seemed normal. I selected all checkbox items, continued, saw a progress bar, install complete confirmation.
Executing MO2, it popped up an error stating "Plugin to handle Fallout 4 no longer installed"
![image](https://user-images.githubusercontent.com/2955403/47924314-0cb2ec00-de81-11e8-8c5f-422ed931754e.png)
Upon inspection, I noticed that the plugins folder contained only 8 items instead of 24.
I then removed the failed install and tried again.
This time I saw that only 9 items were in plugins, but also noticed that the directories "platforms", "resources", and "stylesheets" were missing.
Using 7zip, I opened the "Mod Organizer 2 (Installer)-6194-2-1-5.exe" package and manually extracted any missing items into the install directory.

This restored MO2 to functioning (except the fallout 4 CTD issue remains).

At the time this occurred, I had my anti-virus software removed for testing my original issue, and Windows Defender was disabled.  I am not able to locate any logs that show anything useful for this issue.

All that aside; if this issue only impacts me, then I don't see a reason to keep it open.  Just keep it in mind if others start seeing similar issues, or complain about missing plugins.

**Comment by Al12rs** [comment]
Ah I read that wrong then, I thought you were referring to installing mods not Mo2 itself.
The installer seems to be busted then, we always had problems with it and have been looking for a good replacement for a long time. 
I will just pull the installer from Nexus for now.
Using the Archive version is equivalent to the installer, just drop the contents over the existing installation of MO2 to update.
