### ISSUE TITLE
All mods installed from nexus mod manager site to Mod organizer 2 are not appearing in the game or in the game mode list. 

### ISSUE THREAD

**Issue by FlashJane** [ModOrganizer2/modorganizer#568]
# The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Mod Organizer). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our discord channel

# Environment

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by Al12rs** [comment]
Please explain better what is actually happening. Have you read the Mo2 description and watched the videos explaining how it works?
Mo2 uses a virtual install that shows the installed mods only to programs started from Mo2. So they will not appear in explorer or in the game if you don't run it from mo2.
Now given the scarcely of the report I can't tell if you mean the game or the Mo2 program itself.
If you have problems downloading mods from Nexus into Mo2 you should read he FAQ at the end of the Mo2 description or visit the Mo2 server for help from other users.

**Comment by Al12rs** [comment]
Closing since there is no information
