### ISSUE TITLE
Issue When Running Mod Organizer for Skyrim SE

### ISSUE THREAD

**Issue by FunM0nkey21** [ModOrganizer2/modorganizer#569]
# The problem

When I run any form of SkyrimSE either just the base game or through SKScriptExtender, the fullscreen extends off the monitor and I can only see about a quarter of the whole thing.

**Comment by Al12rs** [comment]
change your INI setting to reflect your monitor resolution:
![image](https://user-images.githubusercontent.com/26797547/48270495-870fdd00-e43a-11e8-9975-5daec1d8e922.png)
