### ISSUE TITLE
How to undo file nesting in left pane?

### ISSUE THREAD

**Issue by hamletsdead** [ModOrganizer2/modorganizer#570]
Love MO2 and it works great, way better than NMM. This isn't a real problem, more of a why-is-it-doing-this-and-how-can-I-stop-it? 

The left pane of MO2 has all the mods in order, except many of them are nested. I don't care if there are nested files for Apocalypse which nests Apocalypse with the Apocalypse-Ordinator Patch, but my left pane has at least 150 mods nested under the first entry. [If this is unclear and not a term of art, I apologize - by nested I mean there's a little file arrow (>) you click and it expands and shows all the other mods within the expanded set]. 

It would be okay if they were all in order, but I have 1-98, 102-121, 129-136, 141-147, 160-165, etc. In a load order of 460 mods, when there's a five mod gap and I need to make sure everything is loading in order, I have to scroll down 200 entries to see what comes next, and then go back up to the original expanded file to continue checking. Again, this doesn't break MO2 in any way, but I don't understand the benefit of doing this. 

For example, I just downloaded three mods, Mavari Armor, Mavari Black Retexture, and the Henrietta Riding Outfit. The first download ended up at 467 in the nested file, and the next two ended up at 468 and 469 at the very bottom of my load order. I can drag and drop them anywhere I like, but the last two mods even when correctly numbered will still be outside of the nested file. There seems to be no rhyme or reason for this, or any rationale that I can discover, and it seems like it would be a hell of a lot simpler if I could just view all my mods in a single load order list in the left pane without any nesting at all. 

So, questions, (a) why are mods being nested? (b) is there some hidden benefit? and (c) if not, is there a way to disable this function?

**Comment by LostDragonist** [comment]
You have a grouping method selected here:  https://gyazo.com/96d019270c02a7f77d2df1753796d253

Set it to no groups and the nesting will go away.
