### ISSUE TITLE
Squares in interface

### ISSUE THREAD

**Issue by Hikkari2018** [ModOrganizer2/modorganizer#571]
Constantly when I use your program or NMM, after installing a mod of any (especially where there are options), squares appear in the interface, which simply cannot be fixed. I don’t know if this is a problem in my files, but when I install it myself (manually), then everything is fine. I can not make a screenshot.

**Comment by Hikkari2018** [comment]
Well, if I still have this problem, then I will write to you and send a screenshot. And so I reinstalled the game. Thanks.


>Вторник, 13 ноября 2018, 17:27 +04:00 от Al <notifications@github.com>:
>
>Please find a way to make a screenshot and submit the mo_interface.log file of an occurrence of the problem, otherwise there is literally nothing to work on.
>We have never heard of such a problem, or at least I don't recognize it from your description.
>Instructions for log file:
>To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed. 
>You should always send the mo_interface.log file as that one contains the general information of your setup, for the usvfs log, you should upload the latest one if the issue is about programs started through Mo2.
>You can drag and drop the logs directly on discord to send them (tip: zip them if they are too big). https://cdn.discordapp.com/attachments/458597400638914563/458728891620524032/unknown.png
>
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Mystik Anime

**Comment by Hikkari2018** [comment]
Here I installed it again and this is what happened.


Here are the logs. Help me please. Tired of constantly reinstalling.
>Вторник, 13 ноября 2018, 17:27 +04:00 от Al <notifications@github.com>:
>
>Please find a way to make a screenshot and submit the mo_interface.log file of an occurrence of the problem, otherwise there is literally nothing to work on.
>We have never heard of such a problem, or at least I don't recognize it from your description.
>Instructions for log file:
>To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed. 
>You should always send the mo_interface.log file as that one contains the general information of your setup, for the usvfs log, you should upload the latest one if the issue is about programs started through Mo2.
>You can drag and drop the logs directly on discord to send them (tip: zip them if they are too big). https://cdn.discordapp.com/attachments/458597400638914563/458728891620524032/unknown.png
>
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Mystik Anime

**Comment by Al12rs** [comment]
I don't see any pictures, I think there is a problem with posting them from phone or something.

**Comment by Al12rs** [comment]
Closing for organization and lack of good explanation of the issue, please reopen this if you have more information
