### ISSUE TITLE
Unable to connect to Nexus with errors.

### ISSUE THREAD

**Issue by mangeloduran** [ModOrganizer2/modorganizer#572]
Trying to use the check for updates on Nexus when connection errors out with "connection canceled" error

Mod Organizer v2.1.5
Windows 10 Pro  Version	10.0.17134 Build 17134

# Details
Previously this worked with the same version - I did have an update to Windows 10, but the logged error more appears to be an API change on Nexus side, but I am not seeing any one else reporting the issue - I have not made any changes to load out or removal or additions to the location that I am using Mod organizer from.

# Link to Mod Organizer logs
https://gist.github.com/mangeloduran/287b86f009a4ece8e46f4d7a3531e651

**Comment by Al12rs** [comment]
Do you show up as logged in in the top bar of Mo2? Make sure you are properly logged in. Possibly delete the cache and log in again from the Mo2 settings, Nexus tab.

**Comment by mangeloduran** [comment]
Okay clearing the Cache worked - I had tried to a resign in already. 
Thank you
