### ISSUE TITLE
MO2 stops loading mods after a number of play sessions

### ISSUE THREAD

**Issue by kestrelgone** [ModOrganizer2/modorganizer#574]
# The problem

I had been successfully playing a modded game for a couple of weeks (Morrowind, in this case) launched through MO2.  However, after taking a break for a few days, MO2 is no longer loading any of my mods' esm or esp files.  None of the files have changed location or been altered in any way since I first started playing.  The files still appear in the  plugin list (and are checked) but aren't being used for some reason.  Also, they do not appear in the 'Data Files' list accessed through the Morrowind launcher.

# Environment

* Mod Organizer Version that exhibits the issue:  2.1.5
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:  Windows 10 v 1803

# Details

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/kestrelgone/4a5f9e4c5d85c5c6fbd0ae5f706bbf0c

## MO Interface
https://gist.github.com/kestrelgone/af09a6d26546fb4c0d693817cdcd0464

**Comment by Ocean112** [comment]
I've noticed this behavior as well. It happens to me on subsequent launches of the game. I have to restart my computer every time I restart my game or nothing is loaded. Not even the configs. My guess is after the initial run, it cannot re-implement the vfs for some reason or another. [https://pastebin.com/HffYCxCb](url)

**Comment by kestrelgone** [comment]
I've been able to get it to load most of the mod files by restarting and turning off virus protection.  However, prior to displaying the main menu, the game pops up a warning, stating that 'One or more plugins could not find the correct versions of the master files they depend on'.  As far as I know, the master files are the same versions they've been all along.  I certainly didn't change them but it certainly seems that something is being changed.  It doesn't seem to have much effect on loading the saved games, however..  I wonder if this is some kind of specific issue with Morrowind, as I've also been using MO2 with Fallout New Vegas and haven't had any issues.

**Comment by Al12rs** [comment]
Possibly this: https://github.com/ModOrganizer2/modorganizer/issues/218 ?

**Comment by kestrelgone** [comment]
That's interesting and it kind of does describe the behavior to a certain extent.  I don't have MO2 or the game .exe set to run as administrator though, and haven't experienced the elevation warning.  It also sounds like this manifests pretty consistently while my problem took a couple of weeks to appear. Puzzling.

**Comment by TechAngel85** [comment]
I just came here to see if this has been reported because it's driving me absolutely insane! It used to do it ever once in a while and wasn't a big deal, but on the latest release I'm about to pull my hair out!. I do a lot of editing in the CK and xEdit and am having to close and reopen MO after ever two to three program runs, which for me and testing is amounting to every 10 mins or so when I'm in my groove. It's become a nightmare to use for mod authoring, atm. So much so I'm about to switch over to using the game's data folder and take MO out of the picture for my authoring needs until it's worked out.

If you need anything from me, please let me know!

**Comment by Al12rs** [comment]
@TechAngel85 I pinged you on discord, we have a made some fixes to usvfs that I would like you to test.

**Comment by Al12rs** [comment]
Anyone still having this issue that is sure it's not the Elevation issue described here #218 , please test the latest devBuilds on discord (2.1.6 +) https://discord.gg/36yJNg , and report whether this still reproduces.

**Comment by kestrelgone** [comment]
I haven't seen it appear in a while now, though I haven't been playing very often,  I'm still using the same version I was when the problem appeared and my antivirus doesn't seem to be affecting it now so I'm not sure if that was the issue originally.  I'll try to play more often and see if I can get it to reproduce.  If I can, I'll post details.
 
 
 
-----Original Message-----

**Comment by Al12rs** [comment]
Thank you

**Comment by Al12rs** [comment]
If I have no reports on this still beeing an issue in 20 days I will close assuming it was caused by some of the bugs we fixed.
