### ISSUE TITLE
"Start Steam?" dialog behavior

### ISSUE THREAD

**Issue by bheimbaugh** [ModOrganizer2/modorganizer#576]
# Running F4SE before starting Steam causes problems

_Note: I'm using [F4SE](https://f4se.silverlock.org/), but that's probably irrelevant._

If you click the MO2 "Run" button for Fallout 4 before starting Steam, the **Start Steam?** dialog is displayed:
![start-steam-diag](https://user-images.githubusercontent.com/39772599/48969482-d6224a00-efc4-11e8-8254-cc52bdbc87ea.png)
If you click **[Yes]**, everything works. (The "Waiting" dialog is kludgy, but I presume is working as designed.) But if you want to cancel...
1. Clicking **[No]** or close window **[X]** should cancel the dialog without starting steam or running the game. Instead, they both start steam and run `Fallout4Launcher.exe` (not `f4se_loader.exe` as configured). 
2. after starting steam, the **Running virtualized proces...** dialog is displayed _until you exit steam_ (not just the game or the launcher). 

P.S. another, apparently unrelated problem is if you click the **[?]** control in the title bar, it does nothing except change the cursor to the "unavailable" icon (red circle w/ diagonal line) while in the dialog pane. No help is displayed and other behavior appears unaffected. 

# Environment

* Mod Organizer Version 2.1.5 Revision: 364289d
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): unknown, none?
* Desktop OS/version used to run Mod Organizer: Microsoft Windows 10 Pro version 10.0.17763 N/A Build 17763

# Details

N/A?

# Link to Mod Organizer logs

## USVFS
I have `usvfs-2018-11-24_15-46-12.log` if needed, but is it really necessary? Publishing the hook addresses of my system on the internet feels reckless. The issue is really easy to recreate, and I don't think there's anything useful in the logs anyway. 

## MO Interface
_Nothing is logged to mo_interface.log during the recreate steps:_
1. start MO2 without steam running...
2. click **[>Run]** (**Start Steam?** dialog is displayed...)
3. click **[?]** control of **Start Steam?** dialog...
4. click **[No]** button of **Start Steam?** dialog...
5. exit `Fallout4Launcher.exe`
6. exit steam

**Comment by LostDragonist** [comment]
I don't think the change in behavior is quite as clear cut.  There are ways to run games that "require" Steam without having Steam running.  The user needs a way to ignore the prompt and launch the game anyways.  

Steam being launched after canceling the dialog is a result of the game being launched requiring Steam.  There's not much MO2 can do about that besides not launch the game, which is discussed above.

Maybe there's an easy way to change the dialog to yes/no/cancel?  I'll try to look into that and doing something with the question mark.

**Comment by LostDragonist** [comment]
I forget that there's also the vastly more common usage of running tools that don't interact with Steam at all.  So there definitely needs to be a way to ignore the prompt.

Anyways, that'll be fixed in 2.1.6.  Clicking yes starts Steam and then starts the selected binary.  Clicking no starts the selected binary.  Clicking cancel or the red X does nothing.

I also removed the hint button as the window has no hints.
