### ISSUE TITLE
had to unistall

### ISSUE THREAD

**Issue by poolcube** [ModOrganizer2/modorganizer#578]
# The problem
I went through all of my mods to see which one was causing my character's walking animation to cease and desist only to find out that it was mo2.

# Environment

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

# Details
just walking around no leg movement.

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by poolcube** [comment]
dont remember if it was the stand alone or installer though...

**Comment by Al12rs** [comment]
Closing for organization and lack of info, please reopen if you can provide more information
