### ISSUE TITLE
MO2 fails to log

### ISSUE THREAD

**Issue by Gumbie101** [ModOrganizer2/modorganizer#580]
# The problem
I went to settings and turned on logging. after the error I had (installing a mod and MO2 getting an app hang error) I went to check the log and it is empty.

# Environment
* Mod Organizer Version that exhibits the issue:2.1.5
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): unkown
* Desktop OS/version used to run Mod Organizer: WIN7

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs <~~~~my issue

**Comment by LostDragonist** [comment]
[MO v2.1.6](https://github.com/ModOrganizer2/modorganizer/releases/tag/v2.1.6) has been released and this bug should be fixed.  Please give it a shot and see if your issue is fixed.
