### ISSUE TITLE
[Feature Request] Monster Hunter:World support

### ISSUE THREAD

**Issue by zyf2008Neptune** [ModOrganizer2/modorganizer#581]

**Comment by Al12rs** [comment]
I don't own that game, would you be able to tell us how that game is modded? Is there a "data" folder where all the mods go?

I can say though that the probability of being actually able to support a non Bethesda game is very slim.

**Comment by zyf2008Neptune** [comment]
The "data" folder is "nativePC".
And its path is "\\Steam\steamapps\common\Monster Hunter World\nativePC".
The way how mods working in Monster Hunter is very similar to those working in Skyrim without esps.

**Comment by Al12rs** [comment]
I see, it might be possible, but I very much doubt it will be implemented by any of the current developers. If this is similar enough to a bethesda games then it might even be pretty simple as Mo2 uses dll plugins to add support for new games, so it would just be a matter of cloning an existing plugin and changing all the values to be the ones of MH:W , problems arise when there are values requested that don't have correspondence in MH:W . 
In any case we would certainly be happy to add that game to MO2 if someone of that modding community develops the plugin for it. So basically you need someone with some basic c++ knowledge, interest in this feature and some free time to implement it.

**Comment by Al12rs** [comment]
Here is a list of things that might need to be implemented to add non bethesda games support: https://github.com/ModOrganizer2/modorganizer/issues/327

**Comment by Holt59** [comment]
Closing this since it's 2 years old and a lots has changed since. If you still want support for Monster Hunter: World, feel free to open a new game request using this template: https://github.com/ModOrganizer2/modorganizer/issues/new?assignees=&labels=additional+games+support%2C+Feature+Request%2C+area%3A+mo2+game+plugins&template=game-support-request.md&title=Add+support+for+game+%5BGAME+NAME%5D
