### ISSUE TITLE
MO2 breaks landing Vertibird code

### ISSUE THREAD

**Issue by githubsux** [ModOrganizer2/modorganizer#582]
# The problem

For some odd reason Mod Organizer 2 breaks Vertibird landing code in Fallout 4. I have disabled all mods in MO2 and started the game via MO2. Coc'd to sanctuary on start and set all the necessary game flags and threw a vertibird signal grenade. However, I get the pop-up stating 'The Vertibird will be unable to land at the requested location' even if the location is clear. Launching the game via vanilla launcher or F4SE's launcher fixes this issue and allows VB's to summoned with no problem. However launching the game via MO2 seems to prove fruitless. I don't want to throw accusations, but it's as if MO2 is breaking something memory-address wise related to Vertibird game code.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.5 / Revision: 364289d
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10 x64 Pro 

# Details

I have been able to call down Vertibirds just fine in-game since I have installed the Heather Casdin mod and used a vb to ferry her and I to the Prydwen to store my junk on-board. Since then, however I've installed a few more mods and it's been a while since I tried to call a vbird. However I've only installed a small number of mods, those including The Institute Safe house mod and Goodneighbor Condo. I have disabled all mods installed after I installed Heather Casdin and the issues till persists. I have disabled all mods installed via MO2 and the problem still persists. 

# Link to Mod Organizer logs

## USVFS
My latest USVFS file (Every event from today until disabling all mods) [usvfs-2018-12-08_08-15-54.log - Latest MO2 USVFS log](https://gist.github.com/githubsux/2eedf40aa201a556b181549872d0db0c)

[usvfs-2018-12-05_18-10-48.log ](https://gist.github.com/githubsux/5245a14cb09326d1a43b3083d50cefa0)

## MO Interface
[mo_interface.log](https://gist.github.com/githubsux/f7c0e43885f106ec769038f37163fcdd)

Thanks.

**Comment by Project579** [comment]
check your INI settings

**Comment by Al12rs** [comment]
Closing this for organization purposes, please reopen if you still have this issue.

**Comment by githubsux** [comment]
> 

check your INI settings
--


the hell's that supposed to mean?

**Comment by AnyOldName3** [comment]
It might have been more helpful to ask that last year instead of delaying this for no reason.

Anyway, I guess what they were asking was to make sure that you've not changed the game's `ini` files in any way, either the ones in the game directory, the ones in the `Documents\My Games\Fallout 4` folder, or MO2's profile-specific `ini`s. If you've unknowingly changed a setting to something that breaks vertibirds, it would still persist after you uninstalled all your mods.
