### ISSUE TITLE
Extended Dialogue Interface doesn't work

### ISSUE THREAD

**Issue by cfoster8** [ModOrganizer2/modorganizer#583]
# The problem

I can't get Extended Dialogue Interface to work.  The esm file appears in the list of plugins on the right side, very near the top and the .ba2 file is clicked in the Archives tab.  When I open the MCM menu in game, it even has an entry for XDI.  But when I open it, it says the XDI.esm file is missing.
# Environment

I'm running win 10.  My MO2 is version 2.1.5.  My FSE is v6.15.

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

https://gist.github.com/cfoster8/96b1cc28530a33396f6f25abc74ad074  for both the interface log and the usvfs.

**Comment by LostDragonist** [comment]
[MO v2.1.6](https://github.com/ModOrganizer2/modorganizer/releases/tag/v2.1.6) has been released and this bug should be fixed. If anyone runs into this again, please submit a new issue.
