### ISSUE TITLE
I think I broke Mod Organizer 2...somehow. 

### ISSUE THREAD

**Issue by GianniMaldonado** [ModOrganizer2/modorganizer#589]
# The problem
It keeps giving me this error message: failed to set archive key in c:/users/giann/appdata/local/modorganizer/FalloutNV/profiles/Rika/fallout.ini (errorcode 0)
Briefly describe the issue you are experiencing (or the feature you want to see added to Mod Organizer). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our discord channel

# Environment
Version 2.1.6
Windows 10
* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by LostDragonist** [comment]
The Fallout NV launcher does weird things to your INI files.  This includes setting them to read-only.  You can make this message go away by making them not read-only.  I'm not entirely sure if it would be the ones in your My Games folder or in your MO2 profiles folder.

**Comment by Silarn** [comment]
@LostDragonist has also updated the latest alpha builds to correct this automatically.
