### ISSUE TITLE
MO 2 Shell execute Error 5

### ISSUE THREAD

**Issue by Mrluks11** [ModOrganizer2/modorganizer#591]
After changing the base directory Skyrim SE MO 2 is not able to open links, if i try to open nexus from the globe icon, try to visit the nexus page of a mod, click in the wiki from the question mark icon, i get the same error shell execute -link of the page- error 5, I thought that it was just with skyrim but it actualy happens with any instance even if the archives of that instance are in the same place as before.
Also if i enter the nexus in chrome and try to download any mod MO will download it with no problem but it will not let me open any link.

PD: Already tried reinstalling MO 2 and it didnt work

[MO log.txt](https://github.com/ModOrganizer2/modorganizer/files/2705763/MO.log.txt)

**Comment by LostDragonist** [comment]
Try following the steps in this post?: https://stackoverflow.com/questions/13135144/shellexecute-permission-denied-in-windows/15620445

**Comment by Mrluks11** [comment]
Sadly it didn't work but i found that if i set Edge as my default explorer MO opens link with no problem so im going to reinstall chrome and see how things go.

**Comment by Mrluks11** [comment]
yep chrome was the problem, thanks for the help anyways.
