### ISSUE TITLE
"Compact Download Interface" Horizontal scroll does not work

### ISSUE THREAD

**Issue by VuthMuul** [ModOrganizer2/modorganizer#594]
# The problem

With the setting "compact download interface" enabled, and a small window size, one cannot horizontally scroll to see info such as download speed and ETA.
See gif for more information (or more rather, lack of information).
Using a theme but also occurs with stock theme.
![no scroll](https://user-images.githubusercontent.com/23411885/50396602-dfb4f280-07ba-11e9-8551-52247087f494.gif)

# Environment

MO 2 v2.1.6
Win 10 Pro build 1809

# Link to Mod Organizer logs

## USVFS

[GIST](https://gist.github.com/VuthMuul/edd7b928fe5e2ead65bc9c046ee58669)

## MO Interface

[GIST](https://gist.github.com/VuthMuul/91ef7cebdd85432206173f785915bab7)

**Comment by Al12rs** [comment]
Thanks for the report I had forgotten about the compact interface. I will send what I can do

**Comment by Silarn** [comment]
@Al12rs I don't believe this is an issue with new column display.

**Comment by Al12rs** [comment]
fixed in #606
