### ISSUE TITLE
executable support for powershell script

### ISSUE THREAD

**Issue by EntranceJew** [ModOrganizer2/modorganizer#595]
# The problem
The window to select a binary to launch a new window with does not accept PS1 (PowerShell) scripts, which allow access to writing slightly more sophisticated shell scripts than you can get with a basic batch file.

![cannot select `All Files *.*`](https://i.imgur.com/39EyfGD.png)

# Environment

* Mod Organizer 2 v2.1.6
* Desktop OS/version used to run Mod Organizer: Windows 10 (late December update)

# Details

There is a way to work around this, but, it is slightly cumbersome:
![workaround](https://i.imgur.com/6ta9NGr.png)
Or alternatively
![workaround 2](https://i.imgur.com/lwztVyj.png)

**Comment by Zarggg** [comment]
Makes sense to me. .ps1 files are not executable binaries. The "workaround" you provided would be the correct method of running such a script.

**Comment by LePresidente** [comment]
This is not an issue. As Zarggg stated above its not an executable binary though you will always need to hook into powershell.exe first
