### ISSUE TITLE
ModOrganizer 2

### ISSUE THREAD

**Issue by dale5351** [ModOrganizer2/modorganizer#596]
# The problem
I just installed upgrade to MO2 to 2.1.6.   I now notice that the column on the right hand screen for mod index is blank.  Previously, it would contain the index of the loaded mods.
# Environment

* Mod Organizer Version that exhibits the issue: MO2 2.1.6
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):not sure -- previous 
* Desktop OS/version used to run Mod Organizer: Win 7 Pro.

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS
I have no idea what a USVFS log is.
## MO Interface
Ditto

**Comment by LostDragonist** [comment]
There's not much information to go on...  Have you tried scrolling to the right?  Maybe the column got out of hand.

If you can't find it, go to settings > workarounds, enable reset window geometries, and click OK.

**Comment by dale5351** [comment]
I had tried scrolling to right, no joy.  BUT your second suggestion worked -- reset window geometry.  Now I have the mod index listed.
