### ISSUE TITLE
MO2 Installer (2.1.6) on Nexus being reported as a virus 

### ISSUE THREAD

**Issue by SparkofFate** [ModOrganizer2/modorganizer#598]
# The problem
![mo2 trojan](https://user-images.githubusercontent.com/46219088/50512696-db4c4a80-0ad6-11e9-8b25-dd00bad42327.png)

Upon downloading MO2 Installer (2.1.6) from NexusMods, Windows 10 is reporting it as a virus and immediately quarantine's it, saying it executes code from an attacker. It spits this out:

Trojan:Win32/Cloxer.D!cl

Alert Level: Severe
Status: Quarantined
Date: 12/28/2018 7:21 PM (I'm JST timezone)
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

# Environment
* Mod Organizer Version that exhibits the issue: 2.1.6
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): Unknown.
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro 64-bit (10.0, Build 17763)

# Details
Windows Defender lists a file in the download as a Trojan

# Link to Mod Organizer logs
N/A

## USVFS
N/A

## MO Interface
N/A

**Comment by Al12rs** [comment]
We know there is nothing wrong with the code. It's open source amd anyone can see what is being released. Some antivirus flag it some say it's fine. It's like that for all new software
