### ISSUE TITLE
[feature request] add highlight to empty mods

### ISSUE THREAD

**Issue by mealyman** [ModOrganizer2/modorganizer#600]
# The problem

I create quite a few "empty mods" for categorization, and scrolling up/down to find them is difficult.

# Details

Would be cool if the empty mods could have an option to highlight/change color to be more easily seen, and maybe perhaps a "hash" in the scroll bar to tell you where they are...

**Comment by Project579** [comment]
Don't use empty mods for categorization there is a separator that is design exactly for that.

**Comment by LostDragonist** [comment]
Version 2.1.6 introduced the concept of separators.  The option to create these are right next to the create empty mod option.  The text for separators are bolded and centered.  You can  right-click separators and set custom colors for them.

I suggest checking it out.  It's a pretty great feature.

**Comment by Al12rs** [comment]
We implemented Separators in 2.1.6 exactly to solve this issue: https://cdn.discordapp.com/attachments/271306913944174601/524315462809550858/unknown.png

**Comment by Al12rs** [comment]
Lol we answered in 3

**Comment by mealyman** [comment]
Ahhhh, got it!  Thanks!!!
