### ISSUE TITLE
MO2 not launching game (FNV)

### ISSUE THREAD

**Issue by Glariss** [ModOrganizer2/modorganizer#609]
# The problem

Just got started using MO2 a few days ago, and this problem has been present from the get go. I will start the program and select New Vegas as the game I want to manage. It will immediately say that this is the first time using MO2, and if I want the tutorial to start. I've in fact already been through the tutorial, so I say no and proceed. Asks about nxm links, I say yes. But when I get into the organizer, all the mods that I have downloaded(all downloaded using manual download and then retrieve mod from archive) aren't enabled and the only plugins are the base game .esm's and Fallout New California (which downloaded using it's own installer that I did not make use MO2's instance, cause I was having issues with MO2 at that point too). I then proceed to enable the mods I want to use, and try to run Fallout New Vegas from the manager, but all that happens is the manager closes shortly after, and just before it closes a black box with no text shows for a split second. And then, nothing. No launched programs. And since I can't get it to launch using the organizer, no mods using the organizer will show in game.

# Environment

* Mod Organizer v. 2.1.6
* Not sure if necessary but I'm running Windows 10, and my computer is a potato that has had a little work done to it over the years to make it a little less of a potato, but really don't think that's important.

# Details

I've gone into the paths and this is the managed game path:C:/Program Files (x86)/Steam/steamapps/common/Fallout New Vegas/FalloutNV.exe. It seems like the correct path, but whenever I've searched for my problem online the most I've been able to find is checking the path. So 

# Link to Mod Organizer logs

https://gist.github.com/Glariss/96e605ceb137826f6eeeceaaf55ac754

Both the most recent usfvs log and the mo_interface log is in there. First time using Gist, and reporting logs of any kind, but I think I did it correctly.  If not, let me know what I should do to fix it and give all necessary information.

**Comment by LostDragonist** [comment]
Do you have any kind of anti-virus program going other than Windows Defender? .I've seen a couple of them that will undo changes that MO2 has made and make it seem like it's being launched for the first time.  IIRC, these also tend to be the ones that don't respect exclusions properly and need to be uninstalled for MO2 to work.

**Comment by Theholybanjo** [comment]
I can second Glariss's problem, Will Post my own report shortly.  Brand New Desktop, Brand new Steam, MO2, and FONV installs, Windows defender is the only security atm. yet for what ever reason MO2 fails to launch due to a "failed to activate bsa invalidation in fallout.ini (errorcode 2%)"

**Comment by Glariss** [comment]
Okay, thanks for suggesting the antivirus. I use VIPRE, which covers me pretty well. Too well, I guess. I went into the settings and disabled all antivirus functions, and MO2 works like a charm now. No acting like its my first time or anything. Now the fun part- seeing which antivirus functions I can turn back on without it messing up my shit. I tried just running as administrator, but then it goes back to not launching FNV. I'm closing the issue anyway, cause at this point it's my turf, unless yall can continue to help me, and then, by all means.

**Comment by Glariss** [comment]
I did some tinkering, and thought this information might be useful for anyone else with VIPRE who doesn't want to completely shut down the antivirus stuff to get it working. Unchecking 'Block potentially malicious processes' under Manage, then Antivirus, will allow the game to launch, but it doesn't hurt to also run MO2 as administrator. I advise you to do both before starting MO2, as you may still get the first time notification and unchecked mods if you don't. Thanks Lost Dragonist
