### ISSUE TITLE
CTD when using MO2 to browse Windows Explorer for files

### ISSUE THREAD

**Issue by dap1984** [ModOrganizer2/modorganizer#611]
Whenever I attempt to use MO2 to browse Windows Explorer for archives/files or whatever I might need, it will CTD after a few seconds of sitting in the Explorer window. This seems to happen in every part of MO2 which opens Explorer. 

I am a very casual MO2/mod user and I apologise in advance if the issue lies with me; if so any advice you could give would be hugely appreciated as it forces me to do a lot of things manually which I'm not very comfortable with.

* Mod Organizer Version that exhibits the issue: 2.1.6
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 10

I would attach files which may be relevant; however I'm reluctant to include anything that may be irrelevant and as such waste your time for no reason. Let me know what you might need if you have an idea what could be causing this to happen.

Thank you.

**Comment by LostDragonist** [comment]
Do you have a Dell or Alienware computer?  If yes, you need to update or uninstall the software Dell Backup and Recovery or Alien Resapwn.

**Comment by dap1984** [comment]
I knew it would be something I was doing, rather than what MO2 wasn't!

Yes, I use an Alienware and I've just uninstalled Alien Respawn which has fixed the issue.

Thanks so much, I was at my wits end.
