### ISSUE TITLE
Merging plugins "ok" greyed out on intergrations 

### ISSUE THREAD

**Issue by Ostrich123** [ModOrganizer2/modorganizer#613]
# The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Mod Organizer). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our discord channel

# Environment

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by Ostrich123** [comment]
On the merge plugins saftware when im on the integrations and tick "im using mod organizer" the ok at thebottom right just greys out for some reason i dont know if its a mod organizer problem or merge plugins problem, ive only just started using mod orgainizer so theres a good chance im doing something wrong and just to let people know i am running the portable version, any help would be really appreciated. 

https://gyazo.com/a429bafde663cdbc6a4ceae61549ae20

**Comment by LostDragonist** [comment]
Merge Plugins does not fully support MO2.  The MO integration is for MO1 or MO2 in portable mode.

Most people either use no integration or use the NMM integration.
