### ISSUE TITLE
No mods loaded

### ISSUE THREAD

**Issue by Slipkerit** [ModOrganizer2/modorganizer#614]
# The problem

I installed mod with MO, but no files got pasted

# Environment

* Mod Organizer Version that exhibits the issue: v2.1.6
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Win10 64bit.

# Details

So, Installed about 30 mod with Mo2, I started the game with SKSE and my the game was telling me that some mod were not there anymore. So I looked to the game folder and no mod files were there and when I looked at the data thing in Mo2 it was showing all the mod files but not the game ones.

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/Slipkerit/1676eb515b91ce2b262072e68db02bd4

## MO Interface
https://gist.github.com/Slipkerit/078474b5e07e8c759c4788b56a356240

**Comment by LostDragonist** [comment]
MO2 does not put mod files in the game directory.  That's the entire point.  You need to run the game and any tools you use through MO2 in order for then to see the mods.

**Comment by totyaxy** [comment]
Do you run skse from Mod Organizer? You can select skse on the left side of RUN button, and press RUN. Because MO create virtual filesystem... while running.

**Comment by Al12rs** [comment]
Closing for organization and lack of info, please reopen this if needed
