### ISSUE TITLE
loot failed via sort button

### ISSUE THREAD

**Issue by totyaxy** [ModOrganizer2/modorganizer#615]
# The problem

If the profile name contain non-english character(s) for example the profile name is "ábc", then after the sort button pressed, I always got error message: loot failed. exit code was 1.
Loot installed (because I want set sometimes own order) Perhaps this is the loot application error.

# Environment

* Mod Organizer Version: 2.1.6
* Desktop OS/version used to run Mod Organizer: Win7
* Game: **Fallout New Vegas**

# Details
See # The problem

# Link to Mod Organizer logs
see above, try it with "ábc" profile name

## USVFS
see above, try it with "ábc" profile name

## MO Interface
see above, try it with "ábc" profile name

**Comment by LostDragonist** [comment]
Changes have been made to MO2 in general and to lootcli specifically in order to better support non-ASCII text and paths.  This will be availble with the next the next version.

**Comment by totyaxy** [comment]
Thank you!
