### ISSUE TITLE
MO2 2.1.6 Runs TexGen and DynDOLOD Elevated

### ISSUE THREAD

**Issue by TheRealKraggy** [ModOrganizer2/modorganizer#617]
# The problem

When running TexGen.exe and DynDOLOD.exe from the current 2.54 DynDOLOD release (https://forum.step-project.com/topic/13029-dyndolod-254-skyrim-sevr-beta/) MO2 decides to use process elevation.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.6
* Desktop OS/version used to run Mod Organizer: Win10 Pro

# Details

In the past I have avoided problems with MO2 and process elevation caused by the 'Run as Admin' option being set for a program by creating a second .EXE for it with the 'Run as admin' option not set and that allowed MO2 to run it without process elevation.

However, with TexGen.EXE and DynDOLOD.EXE, even though the 'Run as admin' setting for both is NOT set, MO2 is running them elevated.  In contrast, other tools such as Outfit Studio, Free Commander and 'non-admin' version of the tool I just mentioned run just fine without elevation.

It seems to show there's another state that can cause it that I don't know about and so don't know how to change.  Apart from 'run as admin' what other reasons does MO2 have to elevate processes it creates?

**Comment by LostDragonist** [comment]
MO2 is running them as administrator as shenson hardcoded the executables to need administrator privileges to run.  It's in the manifest for the executable files.  There's probably not much users can do except bug shenson to do another release.

This is likely to cause problems with MO 2.1.6 and earlier.  MO 2.1.7alpha3 will restart MO in administrator so it can properly handle the situation.  On older versions, you probably want to run MO as administrator to prevent any issues.
