### ISSUE TITLE
Skyrim SE Music Mods Won't Load

### ISSUE THREAD

**Issue by langevonschwerin** [ModOrganizer2/modorganizer#619]
# The problem

I only have one major mod installed (Unofficial High Definition Audio Project) for Skyrim SE, but whenever I launch Skyrim (thru SKSE thru MO2) the music will play for a brief moment and then cut out. 

# Environment

* Mod Organizer Version that exhibits the issue: v2.1.6
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10 Version 10.0.17763 Build 17763

# Details

Things I have already tried include: MO2 as admin, verifying game files, reinstalling both programs completely, uninstalling/cleaning disc/reinstalling. The mod itself is a handful of .bsas and .esps with only audio files. The music will play for a second and then there's an audible cutoff, like a click.

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/langevonschwerin/bd88a5c70df4cad6a2901ababd8d2543
https://gist.github.com/langevonschwerin/1006d8f3441313d9bcdaf30c5254e9a9
https://gist.github.com/langevonschwerin/ba7e3d46ea0e712d312b1046b60f83d0

## MO Interface
https://gist.github.com/langevonschwerin/e1cf8ac58069af842ac833ce1389d67b

**Comment by LostDragonist** [comment]
Can you attempt installing the mod manually and running the game with no involvement from MO2?  I don't really see how this can be related to MO2 at all.

**Comment by langevonschwerin** [comment]
USVF Logs

https://gist.github.com/langevonschwerin/9afcd125d742fbe229045c124236dc2c

https://gist.github.com/langevonschwerin/a33fa2464c66b5efbd30c58719a5edc0

https://gist.github.com/langevonschwerin/84490c9c37bcf7f3cb314796d03fcef7

MO Interface Log

https://gist.github.com/langevonschwerin/91060a8a1a28596d69f5b60cec516d72

**Comment by langevonschwerin** [comment]
The error was with a certain ESP in the UHDAP mod, specifically the MusicHQ.esp. Installing the UHD version worked.
