### ISSUE TITLE
Crash when installing 19th mod (Oblivion)

### ISSUE THREAD

**Issue by Thex-PiedDroit** [ModOrganizer2/modorganizer#620]
# The problem

MO2 freezes indefinitely after trying to install a _10th mod_ for oblivion, and will do so upon restarting the application if a _10th mod_ is installed. Only fixed by manually deleting one of the mods in MO's mods folder.
EDIT: It's not actually "a 10th mod" but a "19th thing on the mods list" actually (found out by removing one of the base esl from the game's data folder, which in turn allowed me to install one more mod)

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.6
* Desktop OS/version used to run Mod Organizer: Win10 completely up to date (not a dell environment)

# Details

This happens upon installing from an archive through MO itself, creating a mod from the content of Overwrite, or when installing a mod manually in MO's mods folder. The simple fact of having a 19th item in the mods list, even a separator, seems to trigger it.
I am using MO2 for SkyrimSE and Morrowind without any issue (178 mods on morrowind and 228 on skyrim) and i am now trying to set up Oblivion but it's absolutely impossible now.

I have tried using another profile, reinstalling MO2, restarting my computer, disabling my antivirus and installing a dummy mod containing only a text file. I have also made sure the modlist.txt and such were not polluted in any way. I'd like to link a dump file but as the program doesn't properly crash, there's no dump file at all.

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/Thex-PiedDroit/b61f85520a2176186bb478606b258d4f

## MO Interface
https://gist.github.com/Thex-PiedDroit/c35ec4fd354fb63afc5b2a7a7bcfc7c1

Thanks for reading, i hope this can be fixed and i wish you a very good one!

**Comment by Thex-PiedDroit** [comment]
Update:

It's not caused by having 10 folders in the mods folder but by having 19 things in the mods list (found out by removing one of the base esl files from the actual data folder, which in turn allowed me to install one more mod)

**Comment by Thex-PiedDroit** [comment]
Could not reproduce from visual studio, so this is probably going to be very complicated to debug :/
I do however get an error upon trying to enable mods by clicking on their checkbox in the mods list, error that comes from qapplication.cpp (couldn't debug that as i don't have the file) after the "emit aboutToChangeData();" line has been called in modlist.cpp line 522. I don't know if this is because i messed something up when setting up the project or of it's actually a bug but i can't effectively debug it anyways so if anyone thinks it's worth looking into it...

However, installing a mod through VS that would otherwise crash MO seems to have completely fixed the freeze issue on the retail executable. Even if i delete mods to return to 18 mods, installing a 19th one doesn't make it freeze anymore. So there's that.

**Comment by Al12rs** [comment]
Closing this for organization purposes, please reopen if you still have this issue.
