### ISSUE TITLE
Failed to set Archive Key Problem, Mod Manager is broken

### ISSUE THREAD

**Issue by KnightKrawler123** [ModOrganizer2/modorganizer#621]
# The problem

Every time I try to get into Mod Manager 2, a notification pops up and says "failed to set archive key in C:/Users/*My Name*/AppData/Local/ModOrganizer/FalloutNV/profiles/Default/fallout.ini (errorcode 0)"

# Environment

* Mod Organizer Version that exhibits the issue: v2.1.6
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10

# Details

This only happened after closing Mod Manager and trying to reopen it after installing DarNified UI v4 into my New Vegas directory (There was no other way to install the mod then that). However, I can open Mod Manager as Administrator.   

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by KnightKrawler123** [comment]
Forgot to mention that when in Mod Manager as Admin, the same message pops up but it refers to the Admin instead of my user. Also, I've tried uninstalling and reinstalling Mod Manager but to difference. Someone mentioned on a different page here mentioning the fallout.ini as the problem, since it can't read it. I've tried to make the ini readable but it keeps going back to unreadable.

**Comment by LostDragonist** [comment]
Hopefully you closing the issue means it's fixed for now.  If not, maybe grab 2.1.7alpha3 here on GitHub. It contains code that will let you make MO2 clear the read-only flags on the files when needed.
