### ISSUE TITLE
MO2 SkyrimSE Instance includes TESV settings, mods, etc after update.

### ISSUE THREAD

**Issue by Gumbie101** [ModOrganizer2/modorganizer#623]
Loaded my normal SE Instance and noticed that It included the TESV exe files along with the Launcher and SKSE for TESV.   
I reloaded and nothing changed. Then I reloaded a new Instance for TESV and everything was normal
I did update and install and replace the old version. which I use for TESV and SE.

* Mod Organizer Version that exhibits the issue: **2.16**
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): **2.1.5**
* Desktop OS/version used to run Mod Organizer: **Win 7 64bit**

## MO Interface
https://gist.github.com/Gumbie101/245b01169f3145dd322737b903eeb467

**Comment by Al12rs** [comment]
From your log it would appear as the managed game for your Skyrim SE instance got set to this:
`15:28:05 [D] managing game at E:\Steam\steamapps\common\Skyrim`
Make sure in the Mo2 settings/paths tab that each instance is managing the correct game.

**Comment by Gumbie101** [comment]
How do I do that? Sent from my Huawei Honor View 10-------- Original Message --------Subject: Re: [ModOrganizer2/modorganizer] MO2 SkyrimSE Instance includes TESV settings, mods, etc after update. (#623)From: Al To: ModOrganizer2/modorganizer CC: Gumbie101 ,Author From your log it would appear as the managed game for your Skyrim SE instance got set to this:
15:28:05 [D] managing game at E:\Steam\steamapps\common\Skyrim
Make sure in the Mo2 settings/paths tab that each instance is managing the correct game.

**Comment by Al12rs** [comment]
![image](https://user-images.githubusercontent.com/26797547/51062604-c7850600-15f7-11e9-80df-068c9fa857a4.png)

**Comment by Gumbie101** [comment]
thank you so much!
