### ISSUE TITLE
File access very slow under MO

### ISSUE THREAD

**Issue by BadDogSkyrim** [ModOrganizer2/modorganizer#624]
# The problem

Recently file access through MO has gotten very slow. I first noticed this in the open/save dialogs when blender or Outfit Studio were launched through MO. (Minutes for the dialog to update the file list when switching directories, for example.) More recently, I've seen excessively long load times running Skyrim itself, and I'm wondering if that's the same problem. 

Nothing has changed in my environment except the latest Windows 10 updates. Also I've started running multiple tools under MO at a time. But this behavior occurs even after a reboot.

Quite possibly something else in my environment is detuned, but I'm not sure what. Suggestions on how to hunt down the problem would be welcome.

# Environment

* 2.1.6
* Windows 10

**Comment by Al12rs** [comment]
Would you care to test the latest dev build available on discord? Here is the invite: https://discord.gg/MB3CyMH
We added some performance improvements, but in truth what you are describing does not seem to be a MO2 issue. Things you could take a look are your AntiVirus, which can horde quite a bit of resources and delay processes to check what they are doing.
I would propose using Task Manager to see if anything is using an abnormal amount of resources on your system. 
You might also want to check your drive performance, if it's a Hard Disk drive then fragmentation could slow it down.

**Comment by BadDogSkyrim** [comment]
System solved the problem for me by frying its motherboard. Might as well close this.
