### ISSUE TITLE
Endorse mod organizer again and again

### ISSUE THREAD

**Issue by totyaxy** [ModOrganizer2/modorganizer#625]
# The problem

On the right-top, I see the red heart. When I clicked to it, I got a question, "Do you want endorse...MO2?". I Click to YES. But sometimes the red heart visible again... I clicked to it...

If I see the red heart, then I see MO2 on the Skyrim nexus page, and I see, this app endorsed already, so this is a bug.

# Environment

* Mod Organizer Version that exhibits the issue: 2.16
* Desktop OS/version used to run Mod Organizer: Win7 x64
* Game: Fallout New Vegas

**Comment by Silarn** [comment]
I thought that someone updated the mo2 endorsement to be game independent and always use the sse mod. But perhaps that endorsement check was not properly updated.

**Comment by Al12rs** [comment]
I think it's more like the old api was literally bugged or something in the results
