### ISSUE TITLE
Improve conflicts tab of mod info dialog

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#628]
# Environment

MO 2.2.0alpha8
Windows 10 1809 17763.253

# Description

3 mods are installed as follows.  The flags on the mod list are correct.  
1. A Matter of Time (archive) is being overwritten by FISSES (loose) and Normal Quicksaves (loose).  
2. FISSES (loose) overwrites a Matter of Time (archive) and is overwritten by Normal Quicksaves (loose).
3. Normal Quicksaves (loose) overwrites a Matter of Time (archive) and FISSES (loose).

![image](https://user-images.githubusercontent.com/7862539/51415412-61d6d380-1b3b-11e9-86a7-271e39bf80a7.png)

The conflicts tab for a Matter of Time only shows the conflicts for Normal Quicksaves.  It should also show conflicts with FISSES.

![image](https://user-images.githubusercontent.com/7862539/51415445-80d56580-1b3b-11e9-8964-5be7b3fc5756.png)

The conflicts tab for FISSES only shows the conflicts for Normal Quicksaves.  It should also show conflicts with a Matter of Time.

![image](https://user-images.githubusercontent.com/7862539/51415462-8af76400-1b3b-11e9-9ca4-5af1699cd32a.png)

The conflicts tab for Normal Quicksaves shows conflicts for both a Matter of Time and FISSES.  This appears to be correct from what I know.

![image](https://user-images.githubusercontent.com/7862539/51415477-95196280-1b3b-11e9-9bac-dc45c93766a8.png)

**Comment by Al12rs** [comment]
I would say this has been addressed with the new advanced Conflicts tab implemented by isanae
