### ISSUE TITLE
[Classic]Skyrim main menu freeze, no text and music, no dragon logo

### ISSUE THREAD

**Issue by FoNV4** [ModOrganizer2/modorganizer#629]
I use MO2 since a long time and like the now features. For SSE an FO4 it works like a charm.
So I want port my old classic Skyrim to the new MO2.  no sooner said than done. But as I start Skyrim with MO2, there are only weird Boxes were normally the text is and the Bethesda that's all.
I turn off all mods and start the game again, also no text, menu freezes only this wired boxes. 
When I start it over MO1 it works like normal and without MO also. Any idea what the Problem could be?
Thank you for your help.

# Environment
Version 2.1.6
Windows 8
Asus Laptop with Nvidia Optimus
GTX 850M/ Intel HD 4600

#Bug Picture
![enb 2019_01_21 14_14_10_00](https://user-images.githubusercontent.com/46895053/51478368-86c18580-1d8b-11e9-9e52-21418e077508.jpg)

## USVFS
[usvfs-2018-02-02_09-40-33.log](https://github.com/ModOrganizer2/modorganizer/files/2779167/usvfs-2018-02-02_09-40-33.log)

## MO Interface
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/2779162/mo_interface.log)

**Comment by Project579** [comment]
It looks like assets are not being read make sure your INI are not damaged.

**Comment by FoNV4** [comment]
Thank you very much. It looks like it works!

I used the Default ini with out mods and Skyrim start as normal.
Now I will install some mods.

Thank you again!!
