### ISSUE TITLE
DDS Preview for Filetree

### ISSUE THREAD

**Issue by twizz0r** [ModOrganizer2/modorganizer#630]
# The problem

This is a request for an improvement.

# Environment

* Mod Organizer Version that exhibits the issue: All that I know of
* Last Mod Organizer Version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Win 8.1 x64

# Details

The DDS preview in the Data tab and also in the mod Conflict tab (for comparisons) are great features, but MO2 would be even more handy if a Preview option is added to the right-click menu in File Tree view. 

# Link to Mod Organizer logs
N/A

## USVFS
N/A

## MO Interface
N/A

**Comment by Al12rs** [comment]
Implemented in commit above.
