### ISSUE TITLE
Error Invalid origin name for DLC

### ISSUE THREAD

**Issue by Bradeck** [ModOrganizer2/modorganizer#633]
# The problem

Afet I add some mods to MO2 for Skyrim, after a relaunch I get the error warning : "invalid origin name DLC: Dawnguard". This error triggers whenever I change the priority of a mod.

# Environment
* Mod Organizer Version that exhibits the issue: 2.1.6
* Desktop OS/version used to run Mod Organizer: Win 10 x64

# Details
This issue arise first with the skyrim instance.
Afet it pops-up :
- When I try to drag an drop mod to change their priority, it says the drag'n drop didn't succees because of the "invalid origin name", but id does work
- When I try to set the priority manually by changing it in the column directly, it works the first time, and triggers the error warning, then I cannot set any priority manually, and must use drag'n driop, wich still trigger the warning message.
- Whenever the error trigger, if I change instance an go to Skyrim SE, which has only the DLC installed, the error trigers when I click on the DLC.
- If I close MO2 and relaunches it and go back to this clean Skyrim SE, the error does not trigger, but if I switch to the Skyrim one, it fires up again.
If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS
https://gist.github.com/Bradeck/17b31afc12cc5b9adf97bbfce8759884

## MO Interface
https://gist.github.com/Bradeck/39bf57a5c7af210a4ebd49f601165d46

**Comment by Al12rs** [comment]
Do you use the Mo2 french translation? I think the DLCs there are named incorrectly making Mo2 no longer match the mod with the new name, causing the error. Could you please confirm this is the case? 
(Btw, thank you for the nice report 👍)

**Comment by Bradeck** [comment]
Yes, the french translation is pretty well made so I kept it.

RIght after your inquiry, I swithed to English (american) and the problem did not occur after a relaunch. I switched back to the french translation and it reared it's ugly head again. So I think you're spot on,

**Comment by Yoplala** [comment]
Yop !

J'ai foiré un truc dans la traduction de la 2.1.6 alors que je pensais le problème résolu.
Vous trouverez une solution temporaire ici : https://www.confrerie-des-traducteurs.fr/forum/viewtopic.php?p=379060#p379060.

Et le problème est normalement réglé pour la prochaine version ! :)

**Comment by Al12rs** [comment]
2.2.0 released on nexus
