### ISSUE TITLE
Lots of problems

### ISSUE THREAD

**Issue by Darklustre** [ModOrganizer2/modorganizer#636]
I just downloaded the program. I started the tutorial. Things are great until you get to the downloading of mods. I begin the download with mod manager just fine. But it doesn't show the progress in the downloads. I waited over 20 minutes. I ended up clicking it and downloading it a few times. I left and came back. You can't pick up the tutorial where you left off, so I have to go back through it again. I finally get the mod installed. It unclicks itself when I click it. It said it wasn't organized right. But it looked to be. And I've never had problems using this mod. It's not giving me specific issues or how it should be filed. There should be a template offered when it says it isn't formatted correctly so you can see how it needs to change. Also how in the world you reorganize it? Dragging it wasn't really working. It would just stick it in folders, not move the subheading. So I couldn't drag Textures under Sounds, for instance. It would just keep depositing it in Sounds. I finally gave up on this. I have a red exclamation mark next to a simple esp. It's not telling me what the problem is. I've had to exit and restart MM and tutorial several times now. I still can't get anywhere. When I begin a new download of a mod, it tells me that it has already been downloaded and will need to be renamed. But it's new and I haven't downloaded it. So I can't figure out the problem. Then I finally double click to install and the program freezes and I can't get anything to respond.

**Comment by Al12rs** [comment]
The tutorial is not something we have been looking at for a long time and it has been report to be broken. If you are asked to do it, just skip it and instead use a good video guide as it could give you more issues than help.

Could you tell us the name of the mod that you had trouble installing so we can have a look at what is wrong? The way to fix incorrect packaged mods is by right-clicking on the folder that should be recognized at the game "Data", and selecting "set as Data directory". Basically to install mods without a manager you would drop files inside this folder manually and when a mod is packaged in a non standard way or you select the "manual install" option, Mo2 will let you manually specify the Data folder to ensure correct installation.

The downloads tab had multiple issues that we have actually been fixing in the past month, a development version of MO2 is available on Discord with a completely new downloads tab:  https://discord.gg/JUh7TTH

On discord you may also report problems and if someone has time they will try to help you solve them.

Let us know the name of that mod that was not being recognized correctly, I hope skipping the tutorial helps getting around the other issues.

**Comment by Darklustre** [comment]
Thanks that's good to know. I was trying to install Morrowind mods. I had to watch a bunch of videos to figure out the problem. I think I resolved that. But now I'm trying to start a new instance to do Skyrim. I pointed the MO at Skyrim and it pulls up all the mods I currently have in the game. But I had put the mods in with NMM and it screwed up my whole game. I'm not sure what to do? I had uninstalled Skyrim and resinstalled it. But all the mods are still in there and the game is absolutely wrecked. So I'm not sure how to fix this. Any ideas? Your help is much appreciated.

**Comment by Al12rs** [comment]
You should make sure to uninstall the mods from NMM or just manually nuke the Skyrim Data folder, then let Steam re-download any missing files. I know downloading can be bad for slow internet but that is the kind of issues that NMM will cause and MO2 will avoid. With Mo2 the  game data folder will not be touched, only the programs started from MO2 actually see the mods.

**Comment by Darklustre** [comment]
Where is the data folder located? I know Steam/Skyrim had some unusual paths. Also can you recommend a good video tutorial for covering the basics? I'm dying to play.

**Comment by Darklustre** [comment]
Thanks again. I will take a look. My Skyrim is crashing non-stop. Dying to get this fixed as quick as possible. Isn't there a Quick Start guide or something? It's so depressing when you are dying to play something and you can't :(

**Comment by Al12rs** [comment]
I'm afraid not, if you want to mod without issues you have to read a few things.

I will close this for organizations, if you still need help you might have better luck on discord or Reddit, I don't actually play the games anymore.
