### ISSUE TITLE
[Enhancement] Show total number of plugins

### ISSUE THREAD

**Issue by RealAntithesis** [ModOrganizer2/modorganizer#638]
Since ESLs and esl-flagged ESPs are becoming more common, it would be helpful to know how many plugins are being counted towards the maximum plugin limit, especially as the priority numbers no longer help with this since this now includes plugins that don't count towards the limit  (and not everyone can read hexadecimal).

Suggest an information panel somewhere that displays the total number of ESMs, ESPs, esl-flagged ESPs and ESLs.

And optionally warn the user if they try to launch the game with plugins that exceed the limit.

**Comment by LostDragonist** [comment]
Mod and plugin counters have already been added to the next version with all the information you'd ever want.  A slightly buggy implementation is available here on GitHub with 2.1.7alpha3 while the proper implementation is available on Discord.

**Comment by Al12rs** [comment]
![image](https://user-images.githubusercontent.com/26797547/51969159-fe6e6f00-2473-11e9-96a7-3db022f3b0bb.png)
Discord link: https://discord.gg/MB3CyMH

**Comment by RealAntithesis** [comment]
Great, thanks. Will try out.
