### ISSUE TITLE
Minor download confirmation bug: mod left "ghost" files that couldn't be removed from the Downloads tab until MO2 was restarted

### ISSUE THREAD

**Issue by DefinitelyNotFred** [ModOrganizer2/modorganizer#640]
## The problem:
I recently downloaded the [this mod](https://www.nexusmods.com/newvegas/mods/63526) to MO2 via Nexus' Vortex button and then I accidently downloaded it again. On the second download it went straight to asking me if I wanted to download it again (normally downloads are first "preloaded" in the downloads tab and say "Done - Double Click to install") I clicked no and noticed that the loading bar underneath the mod just stayed at zero. I then right clicked on the mod to open the context menu so I could get rid of it from the Downloads tab but the context menu only showed the last two sections (delete installed/uninstalled/all and hide installed/uninstalled/all). Clicking Refresh did nothing to get rid of it nor did deleting all files. Nothing showed up in my \MO2\downloads folder either. I tested this a few more times and it seemed the bug was reproducible but only for this particular mod. Clicking on Yes instead to accept the download would proceed with the normal preloading of the mod to the Downloads tab and everything would work like normal. After that I closed MO2 and tried downloading the mod a few more times to see what would happen but I couldn't reproduce the issue. That file did show up again in the Downloads tab as being ready for install, but it was willing to disappear now.
Possibly related is that I have a visual bug when downloading any sort of file to the Downloads tab: the green bar indicating the download progress of mods always starts at about an eighth of the way in, leaving that first eighth of the bar empty while the rest of the bar fills with green.

## Environment:
* Mod Organizer Version: 2.1.6
* Desktop OS: Windows 10 Home

### USVFS:
[USVFS log](https://gist.github.com/DefinitelyNotFred/5eb3adcf9384e9821e6ae9bd437b12fb)

### MO Interface:
[Interface log](https://gist.github.com/DefinitelyNotFred/96bd3c1e3959aaa271c012f4ec5b26fb)

**Comment by DefinitelyNotFred** [comment]
Seems to work so far, guess I'll let you guys know if anything comes up.

**Comment by Al12rs** [comment]
Awesome, will close this but feel free to reopen in case there are issues.
