### ISSUE TITLE
Mod Organizer 2 can't add executable

### ISSUE THREAD

**Issue by Matthan1** [ModOrganizer2/modorganizer#641]
## The problem:
Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our [discord channel](https://discord.gg/5tCqt6V)

I'm trying to "modify executables", namely, wrye mash and mlox, to Mod Organizer 2 v2.1.6.  After browsing to the .exe file for either of them, selecting the .exe in the "Binary" field, and then clicking "Add,"  the only thing that happens is that the field goes blank.  Executables cannot be added.

## To Reproduce:

Mod Organizer 2 v2.1.6

The gears icon at the top of the window, and then try to add either mlox or wrye mash
## Environment:

* Mod Organizer Version that exhibits the issue: v2.1.6
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer:  Windows 10 x64

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed.

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

https://gist.github.com/Matthan1/1c08dac8bab69c8da53b6cdcf012d207
[1c08dac8bab69c8da53b6cdcf012d207-6bcdb2270cc64363a6ad0a9f5a5db7a3cb7f3afc.zip](https://github.com/ModOrganizer2/modorganizer/files/2813944/1c08dac8bab69c8da53b6cdcf012d207-6bcdb2270cc64363a6ad0a9f5a5db7a3cb7f3afc.zip)

**Comment by LostDragonist** [comment]
Are you giving the executables a name in the top field?

**Comment by Al12rs** [comment]
I'm closing this for organization purposes, please reopen if it's still an issue.
