### ISSUE TITLE
steam oblivion cannot load data/obse/plugins/xxx.dll

### ISSUE THREAD

**Issue by tommyonsn** [ModOrganizer2/modorganizer#646]
if load oblivion from oblivion.exe (because steam oblivion game cannot loaded from obse_loader.exe, need load from oblivion.exe) in mo2, cannot load data/obse/plugins/xxx.dll.
But load oblivion.exe in nmm, it works.

**Comment by Al12rs** [comment]
We have implemented oblivion OBSE support in newer versions available on discord:https://discord.gg/6GKR9jZ

Instructions are provided here:
https://github.com/ModOrganizer2/modorganizer/wiki/Running-Oblivion-OBSE-with-MO2
