### ISSUE TITLE
MO2 editing .ini crashes game every time. Game works when edit Documents or Steam Skyrim

### ISSUE THREAD

**Issue by Darklustre** [ModOrganizer2/modorganizer#647]
I've been trying to understand why I'm having various problems but it's coming down to this weird glitch with MO2 preference.ini. I've installed Elder Blood ENB and it's working just fine. But I get this error message: bfloatpointrendertarget=1 is not set or you have multiple copies of this file. I've researched the heck out of it and set the other inis back to default, only changing the MO2 ini. However, once the settings are changed in MO2, it ctds my game on start of New game. But if I set that back to default and change the other directory settings- the game runs fine. What's weirder is that I have set all three directories to default vanilla and I have no issue with the ENB. I can't see why that would be. 

I can't use the ini in MO2 and that doesn't seem right. Please help me with a fix.

**Comment by Al12rs** [comment]
We would need more info to be able to investigate this, specifically all the info you skipped from the template:


## The problem:
Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our [discord channel](https://discord.gg/5tCqt6V)


## To Reproduce:
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'

## Environment:

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.


## Link to Mod Organizer logs:
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed.

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by Al12rs** [comment]
Particularly, what version of MO2 youa are on and interface log are quite needed. Also what method are you using to edit the MO2 ini files? (I'm assuming you are referring to skyrim.ini and skyrimprefs.ini for Oldrim?)

**Comment by Darklustre** [comment]
Thank you for the response. Sorry for the lack of protocol. I'm just a bit confused. How can I show the issue if I've had to reset the ini back to vanilla for the game to run? Do you want me to restore the changes to the ini and then submit the issue? 

In the meantime, to answer your questions quickly- I'm on 2.1.6. I have Windows 8. Method? I click the puzzle piece, access the skyrimpreferences.ini, change the values necessary. Then I save and exit.

**Comment by Al12rs** [comment]
Are you using the Configurator or simply the INI editor?
The configurator is not maintained and should not be used. We will disable it by default in the next release.

**Comment by Al12rs** [comment]
In any case please upload your interface log as instructed, even if you are not reproducing the issue right now. It contains information on your setup which might give insight to what was causing the issue.

**Comment by Darklustre** [comment]
Just the ini editor. 
i
Ok I might be doing this wrong but I went to MO program and tried clicking the 'logs' hyperlink. It wouldn't open. So I went to my MO folder and clicked on logs folder. But it was empty.

**Comment by Al12rs** [comment]
Over the modlist there is a small folder icon with a drop-down menu. There should be an entry saying Mo2 logs folder.

**Comment by Darklustre** [comment]
I'm sorry. I don't know what I'm doing. I have the logs open now. But the directions with the GIST don't make sense. It says to paste them but not to paste them. Is there something with more detailed directions. This is extremely new to me. I'm a tech disaster at the best of times. I feel really stupid.

**Comment by AnyOldName3** [comment]
Open the GIST link. Type in a filename and paste the log into the big textbox. Press create public gist. You'll be given a URL. Paste that URL here.

**Comment by Darklustre** [comment]
How do I get the file name of the rar I just created? I'm only used to browsing the folders and selecting the file. I tried typing it in. Also dragging it. I'm probably doing it wrong like a total dumbarse. Everything I tried didn't work and it wouldn't let me select secret or public. So I hope this thing will work, or you can tell me what to do like I'm a 10 year old that should probably already know this. My face is so red my head is going to explode.

[MO Log.zip](https://github.com/ModOrganizer2/modorganizer/files/2861608/MO.Log.zip)

**Comment by Darklustre** [comment]
Please don't tell me you've given up on me. I really need help with this. The directions aren't clear to someone who has never done any of this before. I'm trying to get it right. :(

**Comment by AnyOldName3** [comment]
So that was a zip file containing a rar file containing a USVFS log. You're right that you do need help. 😕 

I'll stick that one in a gist so you only have to do the MO interface one yourself.

**Comment by AnyOldName3** [comment]
Darklustre's USVFS log: https://gist.github.com/AnyOldName3/08e30a17cc23ddd73340a811cd294f31

**Comment by AnyOldName3** [comment]
What you should do:

1. Open the gist link so you have the page in front of you.
1. Open MO's logs folder by clicking this button in MO: 
![image](https://user-images.githubusercontent.com/8485112/52752592-4c927f00-2feb-11e9-9638-2ec380bd4979.png)
1. Click and drag `mo_interface.log` from the logs folder onto the gist website.
1. Click Create public gist.
1. This will take you to a new webpage. Copy its URL to this conversation here.

**Comment by Darklustre** [comment]
"You're right that you do need help." Well really. Hmpf. I thought I was supposed to type in the file name on my computer. Like not give it a name. But I was supposed to know the name of the file and type it in so the program could access it. Well shit. I'm so embarrassed I think it's actually funny. 

Thanks for explaining it.

**Comment by Darklustre** [comment]
https://gist.github.com/Darklustre/d01b0e1b3a3967c3275d90ab34fcfd75

**Comment by Darklustre** [comment]
UPDATE: So I recently installed BethINI to help tweak the ini in case the problem was caused by user error (not hard to imagine that, is it?). BethINI tweaked the MO2 skyrimpreferences.ini correctly. The changes are what the Elder Blood ENB author said to change. But again, once I finish character creation, the game immediately CTDs. 

I'm hoping you can tell me what is wrong with this because no one on other forums seems able to run down what the problem might be.

**Comment by AnyOldName3** [comment]
Now you've got the hang of gists, you could gist your ini file before and after editing it

**Comment by Darklustre** [comment]
BethINI just changed the ini. I'll GIST you the changed one?


https://gist.github.com/Darklustre/7cb74a17991caec6f2c4a164987c06a3

**Comment by Darklustre** [comment]
UPDATE:

So I fixed my issue myself. But it doesn't make any sense. I reset the MO2 skyrimpreferences.ini back to vanilla and ONLY changed the bfloatrender value to 1. I didn't change all the other values that should be changed. My game is running fine. There is no red error message. ENB seems to be working. I get the intro message in the upper left hand corner. Graphics seem improved. I still need your help in understanding what is going wrong in my MO2 settings to make this happen.

**Comment by Darklustre** [comment]
Here's the new one that is working, but definitely not optimized. 

https://gist.github.com/Darklustre/e02c40fa4ef850020857fd7a69000311

**Comment by Darklustre** [comment]
So is there anything you can tell me?

**Comment by Al12rs** [comment]
So basically one INI crashes the game and another one doesn't?
I would simply imagine that the one that crashes the game has an incorrect setting somewhere.

**Comment by Darklustre** [comment]
Except that I'm pasting that exact one in docs or skyrim directory and it doesn't crash the game? And the settings aren't incorrect. I only changed like 4 values, according to the ENB author's instructions.

**Comment by Al12rs** [comment]
And you copied all the ini files from the profile folder to the mygames folder when you tested?

**Comment by Darklustre** [comment]
Yes I changed them in Skyrim first. Then read it was supposed to be in Documents. So I changed it there. I got the bfloatrender error message and ended up reading that I needed to change the values in MO2. So I set those two back to default and cut and pasted that ini to MO2. Then it's been ctd after character creation every time. I don't know why it would ctd from the few changes I made.

**Comment by Al12rs** [comment]
Ok so you are aware now that Mo2 has its own set of INI files in the profile folder.
Are you also aware how to disable and enable this feature?

Press the editProfiles icon on the toolbar, then select your current profile and uncheck "profile specific INI files". 
With that Mo2 will instead let the game use the INI files in myGames.

Now can you demonstrate that the same INI files work if you have the option disabled but doesn't work if you have the option enabled?
To test this you would simply need to have the exact same set of INI files both in the profiles and myGames folder.
By set of INI files I mean both skyrim.ini and  skyrimprefs.ini (if you have Skyrimcustom.ini leave it blank please)

**Comment by Darklustre** [comment]
So I'm confused. Didn't I just say that I did that?

**Comment by Al12rs** [comment]
I'm closing this for organization purposes, please reopen if it's still an issue.
