### ISSUE TITLE
MO2 asks for Steam to be running even though it is.

### ISSUE THREAD

**Issue by MortalisJhen** [ModOrganizer2/modorganizer#649]
Hello, I have been having an issue for the past week. Any program I try to launch through MO2 asks for Steam to be running which it already is.  I have tried exiting Steam and letting MO2 open it. Restarting PC, reinstalling MO2. Everything works but its now just an annoyance. I wasn't able to find much online about this problem. Thanks for any help. I am currently running a clean profile with no mods as a test.

MO2 version - v2.1.6
Managed game - fallout 4
Windows Version - Windows 10 Version 1809

mo log - https://pastebin.com/q19nWj6U
usvfs log - https://pastebin.com/BEzP6UiK

**Comment by Al12rs** [comment]
We have discovered this is likely to happen if steam has been started as administrator. We raccomand not to start steam as admin, but if there is a concrete reason to do so the you will need to start Mo2 as administrator as well to allow it to feed steam the correct steamAppID. 

So either start both programs as admin or neither.
LostDragonist has added a way to detect this case and propose the solution in the next releases.

**Comment by MortalisJhen** [comment]
Thank you. That fixed it, I had Steam to run as admin for some reason. Everything works great now.
