### ISSUE TITLE
Mass file deletion by Mo2

### ISSUE THREAD

**Issue by draltiin992000** [ModOrganizer2/modorganizer#657]
I am having a issue where it completely deletes all the mods i have downloaded and and uninstall them as well.  
 I'm using the news version

**Comment by Al12rs** [comment]
Can you tell us what you where doing when everything was deleted?
Was there a specific action that triggered it? Did Mo2 freeze/crash before deleting things?

**Comment by draltiin992000** [comment]
i fiqured out what happen this time for some reason i forgot where i put the directory.

**Comment by Al12rs** [comment]
So I can close this?
