### ISSUE TITLE
Failed to spawn "XX": failed to start process (Access is Denied [5])

### ISSUE THREAD

**Issue by Mr123keelos** [ModOrganizer2/modorganizer#658]
Everytime I try to open any application, i get an acces is denied error. I tried to run as admin, compatibility mode, reinstallation and nothing works. Is there a way to fix this issue?

> 13:08:41.848 [D] ssl support: 1
> 13:08:41.848 [D] data path: C:/Users/123keelos/AppData/Local/ModOrganizer/Fallout NV
> 13:08:42.181 [D] Working directory: C:\Games\ModOrganizer 2
> 13:08:42.182 [D] Loaded settings:
> 13:08:42.182 [D]   archive_parsing_experimental=false
> 13:08:42.182 [D]   base_directory=C:/Games/ModOrganizer 2
> 13:08:42.182 [D]   colorSeparatorScrollbars=true
> 13:08:42.182 [D]   compact_downloads=false
> 13:08:42.182 [D]   containedColor=#400000ff
> 13:08:42.182 [D]   containsPluginColor=#400000ff
> 13:08:42.182 [D]   crash_dumps_max=1
> 13:08:42.182 [D]   crash_dumps_type=1
> 13:08:42.182 [D]   display_foreign=true
> 13:08:42.182 [D]   endorsement_integration=true
> 13:08:42.182 [D]   executable_blacklist=Chrome.exe;Firefox.exe;TSVNCache.exe;TGitCache.exe;Steam.exe;GameOverlayUI.exe;Discord.exe;GalaxyClient.exe;Spotify.exe
> 13:08:42.182 [D]   force_enable_core_files=true
> 13:08:42.182 [D]   hide_unchecked_plugins=false
> 13:08:42.182 [D]   language=en
> 13:08:42.182 [D]   load_mechanism=0
> 13:08:42.182 [D]   lock_gui=true
> 13:08:42.182 [D]   log_level=1
> 13:08:42.182 [D]   meta_downloads=false
> 13:08:42.182 [D]   nexus_login=true
> 13:08:42.182 [D]   nmm_version=0.65.2
> 13:08:42.182 [D]   offline_mode=false
> 13:08:42.182 [D]   overwritingArchiveFilesColor=#40ff00ff
> 13:08:42.182 [D]   overwritingLooseFilesColor=#40ff0000
> 13:08:42.182 [D]   overwrittenArchiveFilesColor=#4000ffff
> 13:08:42.182 [D]   overwrittenLooseFilesColor=#4000ff00
> 13:08:42.182 [D]   style=vs15 Dark.qss
> 13:08:42.182 [D]   use_prereleases=false
> 13:08:42.182 [D]   use_proxy=false
> 13:08:42.182 [D] initializing core
> 13:08:42.203 [D] usvfs log messages are written to C:/Users/123keelos/AppData/Local/ModOrganizer/Fallout NV/logs/usvfs-2019-02-18_18-08-42.log
> 13:08:42.212 [D] Initializing VFS <mod_organizer_instance, 1, 1, C:/Users/123keelos/AppData/Local/ModOrganizer/Fallout NV/crashDumps>
> 13:08:42.216 [D] Downloads after refresh: 0
> 13:08:42.220 [D] initialize plugins
> 13:08:42.221 [D] looking for plugins in C:\Games\ModOrganizer 2\plugins
> 13:08:42.225 [D] loaded plugin "bsa_extractor.dll"
> 13:08:42.228 [D] loaded plugin "check_fnis.dll"
> 13:08:42.231 [D] loaded plugin "diagnose_basic.dll"
> 13:08:42.236 [D] loaded plugin "game_enderal.dll"
> 13:08:42.239 [D] loaded plugin "game_fallout3.dll"
> 13:08:42.243 [D] loaded plugin "game_fallout4.dll"
> 13:08:42.247 [D] loaded plugin "game_fallout4vr.dll"
> 13:08:42.250 [D] loaded plugin "game_falloutNV.dll"
> 13:08:42.255 [D] loaded plugin "game_morrowind.dll"
> 13:08:42.258 [D] loaded plugin "game_oblivion.dll"
> 13:08:42.261 [D] loaded plugin "game_skyrim.dll"
> 13:08:42.265 [D] loaded plugin "game_skyrimse.dll"
> 13:08:42.275 [D] loaded plugin "game_skyrimvr.dll"
> 13:08:42.283 [D] loaded plugin "game_ttw.dll"
> 13:08:42.287 [D] loaded plugin "inibakery.dll"
> 13:08:42.290 [D] loaded plugin "inieditor.dll"
> 13:08:42.293 [D] loaded plugin "installer_bain.dll"
> 13:08:42.295 [D] loaded plugin "installer_bundle.dll"
> 13:08:42.298 [D] loaded plugin "installer_fomod.dll"
> 13:08:42.301 [D] loaded plugin "installer_manual.dll"
> 13:08:42.303 [D] loaded plugin "installer_ncc.dll"
> 13:08:42.306 [D] loaded plugin "installer_quick.dll"
> 13:08:43.089 [D] loaded plugin "FNISPatches.py"
> 13:08:43.093 [D] loaded plugin "FNISTool.py"
> 13:08:43.201 [D] loaded plugin "pyCfg.py"
> 13:08:43.201 [D] loaded plugin "plugin_python.dll"
> 13:08:43.221 [D] loaded plugin "preview_base.dll"
> 13:08:43.222 [D] Downloads after refresh: 0
> 13:08:43.222 [D] no plugin splash
> 13:08:43.223 [D] managing game at c:\games\fallout - new vegas
> 13:08:43.224 [D] setting up configured executables
> 13:08:43.351 [D] configured profile: Default
> 13:08:43.520 [D] initializing tutorials
> 13:08:45.869 [D] loaded language en
> 13:08:45.934 [D] Downloads after refresh: 0
> 13:08:46.462 [D] close C:/Games/ModOrganizer 2/profiles/Default/plugins.txt
> 13:08:46.488 [D] C:\Games\ModOrganizer 2\profiles\Default\modlist.txt saved
> 13:08:46.646 [D] Downloads after refresh: 0
> 13:08:46.868 [D] interface Ethernet seems to be up (address: 192.168.0.11)
> 13:08:46.912 [D] reading save games from C:/Games/ModOrganizer 2/profiles/Default/saves
> 13:08:47.120 [D] enable local saves: 1
> 13:08:47.155 [D] displaying main window
> 13:08:47.730 [D] This version is newer than the latest released one: 2.2.0beta2 -> 2.1.6
> 13:08:48.510 [D] close C:/Games/ModOrganizer 2/profiles/Default/plugins.txt
> 13:09:19.381 [D] C:\Games\ModOrganizer 2\profiles\Default\initweaks.ini saved
> 13:09:19.388 [D] C:\Games\ModOrganizer 2\profiles\Default\plugins.txt saved
> 13:09:19.395 [D] C:\Games\ModOrganizer 2\profiles\Default\loadorder.txt saved
> 13:09:19.399 [D] C:\Games\ModOrganizer 2\profiles\Default\lockedorder.txt saved
> 13:09:19.401 [D] setting file times on esps
> 13:09:19.429 [D] Load Mechanism: Mod Organizer
> 13:09:19.431 [D] USVFS DLL Name: usvfs_x86.dll
> 13:09:19.582 [D] enable local saves: 1
> 13:09:19.653 [D] Updating VFS mappings...
> 13:09:19.903 [D] C:\Games\ModOrganizer 2\profiles\Default\archives.txt saved
> 13:09:21.348 [D] VFS mappings updated <linked 131 dirs, 8 files>
> 13:09:21.354 [D] Spawning direct process < "C:/Games/Fallout - New Vegas/Mopy/Wrye Flash.exe" , "" , "C:/Games/Fallout - New Vegas/Mopy" >
> 13:09:21.356 [D] Creating process hooked: < "\"C:\\Games\\Fallout - New Vegas\\Mopy\\Wrye Flash.exe\"\u0000\u0000" >
>  [D]

**Comment by Al12rs** [comment]
This usually happens when steam is started as admin.
I'm closing this for organization purposes, please reopen if it's still an issue.
