### ISSUE TITLE
Running CCleaner removes MO2 Nexus authorization

### ISSUE THREAD

**Issue by ThisIsPatrick** [ModOrganizer2/modorganizer#664]
## The problem:
Using 'Run Cleaner' in CCleaner causes MO2 to require reauthorization to the Nexus when MO2 is restarted.

## To Reproduce:
Open CCleaner
In the 'Cleaner' tab press 'Run Cleaner'
Restart/start MO2
MO2 will no longer be connected to your Nexus account, requiring you to connect again

* Mod Organizer Version that exhibits the issue: Mod Organizer 2.2.0 beta4
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): Unknown
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details:
CCleaner doesn't need to finds any files to clean when you press the 'Run Cleaner' button for the issue to occur.
Using 'Analyze' in CCleaner and manually cleaning found files will not cause the issue.

Checked entries in CCleaner Windows tab:
![image](https://user-images.githubusercontent.com/8843593/53289853-bc320800-3769-11e9-8e3d-c0ac0289eb09.png)
Checked entries in CCleaner Applications tab:
![image](https://user-images.githubusercontent.com/8843593/53289864-df5cb780-3769-11e9-8888-ea99a32ba1d0.png)

Included log files are taken after the issue occurs. Log level is 'Debug.'
### USVFS:
https://gist.github.com/ThisIsPatrick/5ece34a33cd58357407fd58caa09ed52
### MO Interface:
https://gist.github.com/ThisIsPatrick/05ade5f39dec6b8e8fa3c34a9d0348de

**Comment by Project579** [comment]
This is a problem caused by CCleaner and the reason why Microsoft now advice's against using it, as it will break windows and all other software in the system due to some of the cleaning it does (MO2 is one of those softwares).

To solve the problem either uninstall CCleaner and no longer use it, then restart your PC or remove "Windows Event Logs" from the cleaning process then restart your PC.

**Comment by ThisIsPatrick** [comment]
This solved the issue.

**Comment by Silarn** [comment]
I'm a bit puzzled by this. The API uses the windows credential manager to store the API key. Why would CCleaner wipe that out?

**Comment by Silarn** [comment]
Well I see several entries for saved passwords. Wipe those out and you get what you ask for. If you don't want to save passwords, most of those applications let you turn that off. IMO that's better than wiping them after the fact?

**Comment by Project579** [comment]
always happens when software does not tell you what it does to the system.
