### ISSUE TITLE
Usvfs crash with enderal SkyrimRedirector

### ISSUE THREAD

**Issue by Al12rs** [ModOrganizer2/modorganizer#667]
Taederias reported this issue on discord: https://discordapp.com/channels/265929299490635777/271306913944174601/549331420955279363
Crash on startup with crash inn the redirector code.
logs:
https://discordapp.com/channels/265929299490635777/271306913944174601/549331818961174530

There clearly seems to be an issue as the logs end with
```
21:02:58.653 [E] exception in usvfs::hook_GetFullPathNameA: boost::filesystem::path codecvt to wstring: error
21:02:58.653 [W] 
21:02:58.653 [E] exception in usvfs::hook_GetFullPathNameA: boost::filesystem::path codecvt to wstring: error
21:02:58.653 [W] 
```

For me it was working fine the other day.

Apparently the username contains spaces as well as other special characters and that seems like the most likely culprit.

**Comment by Silarn** [comment]
I think this is no longer an issue
