### ISSUE TITLE
Binary path and save file support  realitive path

### ISSUE THREAD

**Issue by GoogleBeEvil** [ModOrganizer2/modorganizer#669]
I put game in mobile HDD ,I  should modify the path each time plug in diffrent pc for the label of disk is diffrent.and the save file same. If MO2 suppport realitive path, this will help

**Comment by Al12rs** [comment]
Could you upload your mo_interface.log ?
It contains your current paths and setup so I can understand what the situation is.

You can access the logs from the "Open folder" drop-down menu over the modlist. There is an entry saying open logs folder.
Close Mo2 and drag and drop the log on github

**Comment by GoogleBeEvil** [comment]
ok let me make it clear，my skyrim folder ：
all files include mo2 ,esp-esm translate tools in SSEA folder ,and game  binary file in SSEB folder,if i rename SSEA to SSEC, i should modify the game path in mo2 .
![](https://i.imgur.com/fXf9WFo.png)
can make mo2  binary  path support  realitive path such as
binary:  ..\The Elder Scrolls V SSEB\skse64_loader.exe
start in: ..\The Elder Scrolls V SSEB\
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/2924344/mo_interface.log)
