### ISSUE TITLE
Make Archives Tab behave like Plugins Tab when clicking a name of mod (since we cant click bsa(s))

### ISSUE THREAD

**Issue by GioGr** [ModOrganizer2/modorganizer#670]
as title says

what im talking about is 

when u click a esp at plugin tab its mod folder is highlighted with blue 
can we have the same at archive tab?

**Comment by Al12rs** [comment]
Actually the archive tab is to either be scrapped or completely rewritten.
The only reason it's still there is to allow extracting BSAs. Will will move that functionality to the mod information view.
