### ISSUE TITLE
Issue With Installation

### ISSUE THREAD

**Issue by RageYT** [ModOrganizer2/modorganizer#673]
Whenever I try and launch MO2 after installation I receive these errors and can not start it up at all.

![image](https://user-images.githubusercontent.com/17907584/54080305-cc45fd80-42ba-11e9-8ad4-0df3032038ad.png)

![image](https://user-images.githubusercontent.com/17907584/54080309-d7992900-42ba-11e9-82c6-5407ad13e02c.png)

**Comment by SuperSandro2000** [comment]
You don't have write rights on those folders. Check them with Windows Explorer if you can create files there and adjust permission if necessary.

**Comment by RageYT** [comment]
> You don't have write rights on those folders. Check them with Windows Explorer if you can create files there and adjust permission if necessary.

The D: location isn't even a HDD nor a valid storage location.

**Comment by LostDragonist** [comment]
In that case, you have some old MO2 settings hanging around pointing to that location.  We should probably handle that more gracefully.

If you're looking for a total wipe of MO2, go delete `C:\Users\<user>\AppData\Local\ModOrganizer`.

**Comment by RageYT** [comment]
> In that case, you have some old MO2 settings hanging around pointing to that location. We should probably handle that more gracefully.
> 
> If you're looking for a total wipe of MO2, go delete `C:\Users\<user>\AppData\Local\ModOrganizer`.

Awesome, thanks that solved the issue.
