### ISSUE TITLE
F4SE crashes when launched from MO2

### ISSUE THREAD

**Issue by Esynthesis** [ModOrganizer2/modorganizer#675]
## The problem: 
Since Bethesda's most recent update, the according update of F4SE crashes when loaded from MO2, CTD before the main menu. Any help would be appreciated. 

## To Reproduce:
1. Launching F4SE from MO2 with mods enabled causes a crash before the main menu.
2. Launching F4SE from MO2 without any mods enabled causes the same crash.
3. Launching f4se_loader.exe "manually" results in no crash (but also no mods loaded).
4. Launching non-script-extended FO4 from MO2 also results in no crash (but mods dependent on F4SE breaking)

## Environment:

* Mod Organizer Version 2.0.7 and 2.2.0beta3 (updating did not help)
* Windows 10, 64-bit 

## Details:
Issue started after having updated F4SE, and three dependent mods (LookMenu, RenameAnything, MCM)

### USVFS:
Sorry, browser (Vivaldi in my case) _always_ crashes upon submission of my larger USVFS file (with unlabeled bird icon). I have no way of uploading anything but the smaller one. 

https://gist.github.com/Esynthesis/ca6c7a1f55f4e2e4341ff3554e52ddc3

### MO Interface:

https://gist.github.com/Esynthesis/481d3540713971a7f000260bb277bb1a

**Comment by LostDragonist** [comment]
See if it keeps happening in a new empty profile:
![](https://cdn.discordapp.com/attachments/403979692501106688/524939782435110924/unknown.png)
![](https://cdn.discordapp.com/attachments/403979692501106688/524940397643038740/unknown.png)
If this fixes it, it could be related to one of the INI settings in an old profile.

**Comment by Esynthesis** [comment]
LostDragonist, thank you for replying so quickly. That did, in fact, solve the issue (which is surprising, since I don't use the profile functionality--my previous solution was to disable all the mods on the existing profile, and that made no difference). 

I've never even looked at the profile INI settings, do you know I would need to do next to get F4SE working again? I should add I attempted reinstalling the latest F4SE package multiple times (in the Steam install directory).

**Comment by LostDragonist** [comment]
The easier method would be to copy your INI settings from the new profile to the old profile.  You can access the profile folder using the folder icon here: 
![image](https://user-images.githubusercontent.com/7862539/54405014-3e478980-46a3-11e9-9c6b-93f6db5008c6.png)

You might want to go line by line in the INI files to check for differences as that can sometimes affect save games as well.

**Comment by Esynthesis** [comment]
Sorry, as I mentioned I'm really new in this area--if I do this, I'll need to re-activate my mods again, one by one, right? The testing profile has no mods activated (much less in the correct order). This is going from the (working) "Test Profile" to the (broken original) "Default".

**Comment by LostDragonist** [comment]
Go back to your old profile.  Open the profile folder.  Right-click fallout.ini and select copy.

Go to the new profile.  Open the profile folder.  Right-click fallout.ini and select rename.  Name it fallout_old.ini.  Right-click empty space in the folder and paste.

Go back to the old profile.

Now you have your mod list with the reset INI settings and it should work.  Probably.  Maybe.

**Comment by Esynthesis** [comment]
Thanks for your patience with this, I'm sure I sound very dumb. So transferring the default profile's INI data to the testing profile INI...didn't change anything (so it wasn't automatically broken). 
So, I copied the testing profile's INI file on top of the default profile's (I've backed everything up) and F4SE still crashes on launching from Mod Organizer.

Unless I'm mistaken, that would rule out the INI file at least.

**Comment by LostDragonist** [comment]
Hmm, okay.  The other thing you could do is grab your plugins.txt, modlist.txt, and loadorder.txt from your old profile and copy them to the new profile.  Those contain all the information about the mod and plugin state (order and activations).

**Comment by Esynthesis** [comment]
That's good to know. I copied over loadorder, lockorder (I do have a few locked mods), modlist, and plugins. 

The testing profile crashed upon launching, the same way the default did (getting past ENB, right before reaching the menu). I guess that's another way to do it wrong, at least.

**Comment by Esynthesis** [comment]
Well, thank you for your patience and help so far, LostDragonist. At the very least I'm being forced to learn something about the configuration behind the profiles...and I suppose the worse case scenario is I can start with a new profile, and add mods in a few at a time, until something breaks or I can load up my save. If you can think of anything else, by all means let me know. 

(I've already lost a +100 hour character in FO4 and restarted, I don't think I could convince myself to start a third time.)

**Comment by Al12rs** [comment]
Hey, you mentioned you just updated F4SE dye to the new patch of the game, did you make sure all the F4SE plugins have also been updated to work with the new version?
Updating the script extender is just the first step, then authors need to update the plugins that use it as well.

You can either play without all your F4SE plugins or roll back the update and wait all the mods to be updated before upgrading again.

**Comment by Esynthesis** [comment]
> Hey, you mentioned you just updated F4SE due to the new patch of the game, did you make sure all the F4SE plugins have also been updated to work with the new version?
> 
> Updating the script extender is just the first step, then authors need to update the plugins that use it as well.
> 
> You can either play without all your F4SE plugins or roll back the update and wait all the mods to be updated before upgrading again.

No, I had not--or at least, I don't think so. In my desperation of reinstalling F4SE a third time, I did delete F4SE's own files rather than just overwriting them. I don't think I have that many mods that run F4SE plugins, though I might have a few that generate them (in which case, I should probably just delete all those generated files, and if the mod breaks, well I can just reinstall them). Where should I go?

**Comment by Esynthesis** [comment]
So, I updated almost every mod--certainly every mod reliant on F4SE that had an update--and got the same outcome. Though it was a good idea to update them, one would assume.

The next step, I guess, is to check each mod for script extender files (presumably, they'll be in a folder called 'F4SE' for each mod) and...delete them and reinstall the mod? 

As before, thank you for your help, but I should ask--I don't suppose there's some FO4 crash log tool I could turn to in this case?

**Comment by Al12rs** [comment]
No, you don't simply reinstall the mods that have not been updated, you simply canr use them untill the author releases an update for them. you simply uncheck thebmods in the left pane that have a dll file in them.
This is why people are so upset about game updates, it makes a lot of mods unplayable until they get updated by the authors.

Here is the masterlist of updated plugins and corresponding game version: https://www.reddit.com/r/skyrimmods/comments/9lpdsr/skse64_plugin_update_status_masterlist/

**Comment by Al12rs** [comment]
Since this does not swem to be a Mo2 issue Im closing for organization. You can still post messages if you need

**Comment by Esynthesis** [comment]
Oh, I didn't know about that list.

As it happened, turning off all Script Extender mods removed the issue. From there, it was very easy to isolate it from seven mods (Knockout Framework). Which, if I had guessed earlier, wouldn't have surprised me. 

So it was not an MO2 issue, though MO2 was remarkably useful in isolating the issue. I wish I'd known that earlier (or even just guessed correctly), and I could've saved a few hours of work.

Thank you very much for all your help.

**Comment by Al12rs** [comment]
You are welcome 🍻
