### ISSUE TITLE
LOOT Failed. failed to parse condition product version

### ISSUE THREAD

**Issue by somerandomuser1** [ModOrganizer2/modorganizer#676]
17:28:26.333 [D] retrieving credentials
17:28:26.351 [D] D:\Program Files\Skyrim SE\MO2\profiles\Default\modlist.txt saved
17:28:27.570 [D] D:\Program Files\Skyrim SE\MO2\profiles\Default\plugins.txt saved
17:28:27.575 [D] D:\Program Files\Skyrim SE\MO2\profiles\Default\loadorder.txt saved
17:28:27.580 [D] D:\Program Files\Skyrim SE\MO2\profiles\Default\lockedorder.txt saved
17:28:27.589 [D] Updating VFS mappings...
17:28:27.760 [D] VFS mappings updated <linked 35 dirs, 4 files>
17:28:27.763 [D] Creating process hooked: < "\"D:\\Program Files\\Skyrim SE\\MO2\\loot\\lootcli.exe\" --game skyrimse --gamePath \"D:/Program Files/Skyrim SE/steamapps/common/Skyrim Special Edition\" --pluginListPath ...
17:28:45.300 [D] D:\Program Files\Skyrim SE\MO2\profiles\Default\lockedorder.txt saved
17:28:45.309 [D] Updating VFS mappings...
17:28:45.470 [D] VFS mappings updated <linked 35 dirs, 4 files>
17:28:45.473 [D] Creating process hooked: < "\"D:\\Program Files\\Skyrim SE\\MO2\\loot\\lootcli.exe\" --game skyrimse --gamePath \"D:/Program Files/Skyrim SE/steamapps/common/Skyrim Special Edition\" --pluginListPath ...
17:28:45.958 [D] [loot] LOOT failed: yaml-cpp: error at line 1125, column 9: bad conversion: invalid condition syntax: Failed to parse condition "product_version("../SkyrimSE.exe", "1.5.62.0", <) and file("../SkyrimSE...
 [D] 

googled all around about this issue, couldnt find any solution.

**Comment by LostDragonist** [comment]
Are you using a cracked/pirated version of Skyrim?  There's a bunch of bad cracks going around that cause this to happen.  That's been the case 100% of the time this error has occurred (so far).

**Comment by somerandomuser1** [comment]
nvm. updating to the latest BETA version fixed the problem.

**Comment by somerandomuser1** [comment]
no. its not a cracked version. i own the special edition. it works fine after updating to BETA version of MO2

**Comment by LostDragonist** [comment]
Hmm... wrong version of lootapi then?  I don't remember that causing this specific error but maybe something has changed.

Oh well.
