### ISSUE TITLE
MO2 stuck as a background process (wintab32.dll)

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#678]
Reported by AralynDarkwhisper#2849 on Discord

User reported MO2 not launching.  Process was active and appeared to be consuming 100% CPU on one core.  Task Manager reported it as a background process.  The attached dump shows the main process being stuck in wintab32.dll.  User reported having a Huion GT 220 monitor installed that is the likely source for this driver.

[ModOrganizer.zip](https://github.com/ModOrganizer2/modorganizer/files/2975750/ModOrganizer.zip)

**Comment by isanae** [comment]
Probably a problem with a third-party DLL, not MO. Closing as this hasn't been reported since.
