### ISSUE TITLE
failed to spawn "...": failed to start process(The parameter is incorrect.[87]). when I try to launch SKSE in MO and restart my pc doesnt seen to work

### ISSUE THREAD

**Issue by kickfyck01** [ModOrganizer2/modorganizer#679]
## The problem:
Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our [discord channel](https://discord.gg/5tCqt6V)

## Environment:

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed.

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by LostDragonist** [comment]
Can you explain your issue a little more?  All I'm seeing are steps to reproduce but you don't seem to describe what it's trying to reproduce...

**Comment by Al12rs** [comment]
Closing this for organization purposes, please reopen if you still have this issue.
