### ISSUE TITLE
Mod Deployment

### ISSUE THREAD

**Issue by stsk1** [ModOrganizer2/modorganizer#680]
mod organizer 2 does not activate mods in game is there a way around this, or did i do something wrong?

**Comment by LostDragonist** [comment]
Are you running the game through MO2?

**Comment by stsk1** [comment]
yes

**Comment by LostDragonist** [comment]
> To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".
> 
> Before sending any Logs make sure the Log Level is set to Debug in Settings\Diagnostics, then close MO2 and clean the logs folder, after that you can reopen MO2 and reproduce the problem. 
> 
> Once you have reproduced the problem, close MO2 before sending or examining the logs as they are finished writing only after the program is closed; after you have finished testing setting the log level back to default is recommended.
> 
> You should always send the mo_interface.log file as that one contains the general information of your setup, for the usvfs log, you should upload the latest one if the issue is about programs started through Mo2.
>
>Zip the log files up and drag&drop them onto a Github comment here.
 ![](https://cdn.discordapp.com/attachments/458597400638914563/458728891620524032/unknown.png)

**Comment by stsk1** [comment]
[usvfs-2019-03-26_22-25-21.log](https://github.com/ModOrganizer2/modorganizer/files/3010863/usvfs-2019-03-26_22-25-21.log)

**Comment by stsk1** [comment]
interface:
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/3010871/mo_interface.log)

**Comment by LostDragonist** [comment]
Your USVFS log doesn't contain the debug information requested so it's pretty useless.  

Your mo_interface.log has this error which is probably not good: `18:18:13 [C] failed to parse plugin file E:\ModOrganizer\SkyrimSE\mods\Dust Effects by HHaleyy\DustEffectsSSE.esp: invalid file type`

You probably want to fix or disable that mod.

**Comment by stsk1** [comment]
disabled

**Comment by LostDragonist** [comment]
Did you try running the game after that?  If you're still having problems, go do this and upload some new logs:

>Before sending any Logs make sure the Log Level is set to Debug in Settings\Diagnostics, then close MO2 and clean the logs folder, after that you can reopen MO2 and reproduce the problem.

**Comment by stsk1** [comment]
mods are still not enabled in game. is there a way to enable them?

**Comment by LostDragonist** [comment]
If you're still having problems, go do this and upload some new logs:

Before sending any Logs make sure the Log Level is set to Debug in Settings\Diagnostics, then close MO2 and clean the logs folder, after that you can reopen MO2 and reproduce the problem.

**Comment by Al12rs** [comment]
Closing this for organization purposes, please reopen if you still have this issue.
