### ISSUE TITLE
What does this mean.

### ISSUE THREAD

**Issue by grsspirit** [ModOrganizer2/modorganizer#681]
[user did not provide any info]

**Comment by grsspirit** [comment]
I get crashes and it says  QWindowsXPStylePrivate::buffer(1048575x531), CreateDIBSection() failed. (The parameter is incorrect.)  I am wondering what this means.

**Comment by LostDragonist** [comment]
No clue.  When are you receiving this error?  Any time you try to launch MO2?   What version of MO2 are you trying to use? Did you use the installer or the archive?  What version of Windows are you using?

**Comment by grsspirit** [comment]
Hi! I am using windows 10. Using Mod Organizer v2.1.6 . It happens when I was playing fallout 4 for a while. I was doing a play through with a few new weapon mods. It could be something to do with those weapon mods.
I have started a new play through without those weapon mods and will see what happens but before never really happened.

**Comment by LostDragonist** [comment]
Is MO2 crashing or is FO4 crashing?  Where are you getting the error from?  Is it some sort of dialog pop up or some kind of log?  Is that from MO2 or FO4?

> To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".
> 
> Before sending any Logs make sure the Log Level is set to Debug in Settings\Diagnostics, then close MO2 and clean the logs folder, after that you can reopen MO2 and reproduce the problem. 
> 
> Once you have reproduced the problem, close MO2 before sending or examining the logs as they are finished writing only after the program is closed; after you have finished testing setting the log level back to default is recommended.
> 
> You should always send the mo_interface.log file as that one contains the general information of your setup, for the usvfs log, you should upload the latest one if the issue is about programs started through Mo2.
>
>Zip the log files up and drag&drop them onto a Github comment here.
 ![](https://cdn.discordapp.com/attachments/458597400638914563/458728891620524032/unknown.png)

**Comment by grsspirit** [comment]
Ok Thanks! I will get around to doing this sometime soon.

**Comment by grsspirit** [comment]
[logs.zip](https://github.com/ModOrganizer2/modorganizer/files/3024772/logs.zip)

Hi. I hope I done correct. I get this error at the bottom of the Mod Organizer page. Last time it happened when opened the Mod organizer page and before after exiting fallout 4.

**Comment by LostDragonist** [comment]
Do you have any files in `C:/Users/User/AppData/Local/ModOrganizer/Fallout 4/crashDumps`?  If you do, please upload one of them here after zipping it up.

**Comment by grsspirit** [comment]
I do not have any files there. The path is not correct for me. I will take a look to see where these are. thanks

**Comment by Al12rs** [comment]
Closed for inactivity, you ma reopen if needed.
