### ISSUE TITLE
Wrye Bash and MO2, always troublesome  and stressful pain

### ISSUE THREAD

**Issue by FabioManoel1977** [ModOrganizer2/modorganizer#684]
Sorry bad english

Wrye Bash always freeze/crash when it finishes the batch creation, after days searching in google a way to fix it, I finally find it, I just need first to create a bashed patch OUTSIDE of Mod Organize and then again INSIDE Mod organizer I can REBUILD this patch created outside and then everything works fine.

However, I have 50 plugins merged that I created using the merged patch, and every time that I run Wrye Bash it DISABLES all my plugin on Mod Organizer and then I need to enable ALL plugins first and then disable each plugin merged manually. this is a waste of time, sometimes I spend 30 minutes or one hour doing it. I know that an easy way to fix it is to DELETE the plugin that is already merged, but, this is so dangerous, If something happens and I need to make a new merge, I just need to enable the plugin. If I delete it, If something bad happens and I need to remake my merged plugin I am doomed.

Then exist any way to make Wrye Bash stop disable my plugin on Mod Organizer without my permission?

**Comment by LostDragonist** [comment]
Given the lack of information, I'm going.to guess you're modding Skyrim LE and you're using MO 2.1.6.  The "disable plugins" issue will be fixed in the next release.  You can get a pre-release here on GitHub.

**Comment by FabioManoel1977** [comment]
can I update MO2 without losing anything? I have almost 300 mods installed, so many merged plugins so many days installing, merging and setting load order to make the game stable... If I update and lose everything will be disturbing. My game is stable, but, I need a batched patch because I have so many creatures, armor and weapons installed but they are not showing up in the game. I guess only a batched patch will make the things begin to happen... I am surprised, I have 6 different mods adding creatures in the game and I am 2 hours playing and I am finding only wolves and deers in the wild...

**Comment by FabioManoel1977** [comment]
forget it, I updated it and looks good. Thank you very much for all your attention, I am really grateful. for the time being, everything is ok now. this thread can be locked.

Very thanks
