### ISSUE TITLE
 overloads fashion

### ISSUE THREAD

**Issue by ARXLINCH** [ModOrganizer2/modorganizer#685]
am Russian.
I'm sorry if I'm not writing there.
I play fallout 4.
two days everything was fine.
Now I wear armor, take weapons from mods. Save.
Uploading.
I am without weapons and armor from fashion.
everything is in the same place where it lay.
each time it loads, as it were, a fallout. makes a new start in my save.
if i do even some things, furniture. He removes them as well.

I guess I knocked down the settings.
I have 16 gigabytes of virtual memory. But as the MO2 works strangely.

**Comment by Al12rs** [comment]
Closing this for organization purposes, please reopen if you still have this issue.
