### ISSUE TITLE
MO2.1.6 can't open SKSE

### ISSUE THREAD

**Issue by yemmy1270** [ModOrganizer2/modorganizer#686]
Skyrim SE: 1.5.73
MO2: 2.1.6
SKSE64: 2.0.15

I can play skyrim through SKSE.
I can start Skyrim launcher and play through MO2.
But if I start SKSE through MO2, I haven't seen Bethesda logo yet and crash to desktop.
I've tried to disable all mod. It doesn't work too.

**Comment by paulharrison1957** [comment]
For me the first time I run SKSE through MO2 the game crashes almost immediately. However, if I then run SKSE the second time then it runs OK. This can be intermittent and usually happens after I make some changes within MO2.

**Comment by yemmy1270** [comment]
Thanks for your advising.
I've found the problem is that I have wrong version of mods.

**Comment by Al12rs** [comment]
Closing this for organization purposes, please reopen if you still have this issue.
