### ISSUE TITLE
Not compatible with wryebash

### ISSUE THREAD

**Issue by 525566534** [ModOrganizer2/modorganizer#688]
## The problem:
When I try to make a patch by Wrye Bash,it shows that it's being saved, but that's all. I waited six hours for wryebash to do the same.I left many messages to the author of wryebash, who asked me to come to you for help.

## To Reproduce:
I loaded wryebash with mo2

## Environment:

* Mod Organizer Version that exhibits the issue:2.16
* Desktop OS/version used to run Mod Organizer:win7x64

**Comment by Sharlikran** [comment]
Since you have windows 7 you need to refer to issue #521 as the solution provided by  Project579 commented on Oct 19, 2018. MO2 doesn't allow the creation of certain folders and you have to make them manually.

**Comment by Al12rs** [comment]
This problem should be fixed in the latest version, please reopen if that is not the case

**Comment by 525566534** [comment]
yes,i had down the latest version, It has been settled.Thanks!
