### ISSUE TITLE
New Vegas NVSE: Fails to start with a low processor speed.

### ISSUE THREAD

**Issue by MildlyFootwear** [ModOrganizer2/modorganizer#694]
## The problem:

When attempting to start NVSE with a low processor speed, the game will fail to launch when launching through Mod Organizer 2. 

On my main computer (gaming laptop with 1070/i7 7700HQ), this consistently happens with the processor speed limited to 40% on battery. This does not happen with the NVSE enabled GECK, nor does it happen with FNVEdit, and this issue goes away if I increase the maximum processor speed to 100% or launch without MO2. ~~I suspect the cause is because Windows can't set up the virtual file system fast enough, as NVSE GECK works just fine through MO2.~~ I don't think this anymore.

## To Reproduce

1. Limit processor speed to a low value (10-40%). Using Windows Power Options.
2. Launch NVSE through Mod Organizer 2.

## Environment:

MO2 v2.1.6
Windows 10 v1709

### USVFS:

https://gist.github.com/MildlyFootwear/c818555a51a9036a78fa57a191b7e402

### MO Interface:

https://gist.github.com/MildlyFootwear/44decf862b872b4050c826477aaee929

## Additional:

I've removed my Windows username as it is my real name, but I assume that is perfectly fine.
I can very easily reproduce this as it happens every single time I launch through MO2, but does not happen if I launch nvse_loader.exe directly. When launched through MO2 like this, NVSE doesn't even reach the point of generating nvse.log.  

Edit: It's worth noting, I do use a SSD, so that might be somewhat related. ~~I'm not sure if it would be possible to add a user-set delay between setting up the virtual file system and launching applications then just have that default to 0, but that would be the first thing I'd try.~~ Tried a batch file inbetween with timeout, no luck. I've also only noticed this issue when not plugged in.  
Edit2: Updated formatting and logs.

**Comment by Al12rs** [comment]
This is too specific to reproduce or investigate. We can't do much with this report sadly. There are a bunch of other factors that could cause the game to crash that aren't related to mo2.
If you are still having this issue please drop by the mo2 discord instead where maybe we can do some tests.
