### ISSUE TITLE
fnv new california starts to crash using MO2

### ISSUE THREAD

**Issue by dukeonthelooks** [ModOrganizer2/modorganizer#696]
## The problem:
I had no problems to play fallout new vegas new california, but it started to crash while finishing the game mod.
## To Reproduce:

1. Go to last load (which I made different saves to)
2. Click on try and play past 4 minutes

## Environment:

* Mod Organizer Version that exhibits the issue: MO 2.1.6
* Desktop OS/version used to run Mod Organizer: I have windows 10

## Details:
my specs are 8 gb ram and video card gtx 710 (I KNOW strarter quality)

**Comment by LostDragonist** [comment]
Given the complete lack of information, I'm going to give out this horribly generic response to start with.

> To check whether the issue is related to one of the mods installed or your ini settings, see if it keeps happening in a new empty profile:
> ![](https://cdn.discordapp.com/attachments/403979692501106688/524939782435110924/unknown.png)
> ![](https://cdn.discordapp.com/attachments/403979692501106688/524940397643038740/unknown.png)
> 
> Also make sure you don't have any mods installed in actual game folder, and test if the issue happens outside of Mo2 if you didn't already.

**Comment by dukeonthelooks** [comment]
yeah sorry i accidentaly saved the issue before finishing but thanks.

**Comment by dukeonthelooks** [comment]
well i created a new profile on MO2 to see what happens, it automaticly chooses the default profile but it helped me create a new game although I all my progress was lost and the game doesn´t crash anymore.

**Comment by dukeonthelooks** [comment]
jk the game new california started breaking down again.

**Comment by Al12rs** [comment]
This does not sound like a Mo2 issue, Closing this for organization purposes, please reopen if you still have this issue.
