### ISSUE TITLE
WryeBash and MO2: won't run

### ISSUE THREAD

**Issue by MysticDaedra** [ModOrganizer2/modorganizer#698]
Trying to run Wrye Bash from MO2. I installed the standalone version of Wrye Bash, then added the executable via MO2. When I run it, I get the following windows error: 

"This action can't be completed because the folder or a file in it is open in another program. Close the folder or file and try again." Folder in question is WryeBash_sjfeup

If I click "cancel", it then gives me the following Wrye Bash error:

Error! Unable to start Wrye Bash.

Please ensure Wrye Bash is correctly installed.

Traceback (most recent call last):
File "bash\bash.pyo", line 280, in _main
File "bash\env.pyo", line 731, in testUAC
File "bash\env.pyo", line 649, in shellDeletePass
File "bash\env.pyo", line 640, in shellDelete
File "bash\env.pyo", line 606, in _fileOperation
CancelError: Action aborted by user.

**Comment by LostDragonist** [comment]
The only real way we've found to solve this is to update Windows 10 to build 1809.  If the "check for updates" button isn't doing it for you, Google the Windows update assistant.

**Comment by jarrard** [comment]
Updating to windows 10 1903 solved this problem for me, must have been a issue somewhere in windows core filesystem?

**Comment by SigynX1** [comment]
Thank you so much for this info. I had the same problem as MysticDaedra. I noticed that I was on Windows 10 1803, so I started updating it. It went through the rest of its 1803 updates and then skipped right to 1903. As soon as that version was installed, my Wyre Bash worked. Thanks again!
