### ISSUE TITLE
SSL Handshake Failed 

### ISSUE THREAD

**Issue by Darrkwater295** [ModOrganizer2/modorganizer#699]
## The problem:
Attempting to download a mod from Nexus results in the error "Failed to request file info from Nexus: SSL handshake failed

## To Reproduce:

1. Go to any mod on Nexus
2. Click on Mod Manager Download

## Environment:

* Mod Organizer Version that exhibits the issue: 2.1.6
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N\A
* Desktop OS/version used to run Mod Organizer: Windows 10 Professional

## Details:
Specifically, the original issue was, attempting to download a mod would result in the error "Login Failed, SSL handshake failed" - I corrected this by adding the other Nexus servers to the preferred side in the settings of MO2. After that, it would log me in automatically, but then resulted in the new error for which this report is opened

## Link to Mod Organizer logs:
![Capture](https://user-images.githubusercontent.com/50223033/57116306-3fe81200-6d22-11e9-82ae-8028c7cab20e.PNG)

**Comment by LostDragonist** [comment]
The legacy API appears to be having problems right now.  Newer versions of MO2, i.e., betas that are about to release, aren't having the same problem.  You can grab MO 2.2.0rc3 here if you want: https://mega.nz/#!suJhCIAC!FVJbiloiAWsByRgcUrI9eC9aWwbZpsK2fp9Rl73pqQg

**Comment by Darrkwater295** [comment]
Thank you, this has helped tremendously.
