### ISSUE TITLE
[Feature Request] Allow the ini editor to edit global files when local saves are disabled

### ISSUE THREAD

**Issue by brian-reinhart** [Modorganizer2/modorganizer#70]
Pulling up the INI editor for Skyrim Special Edition does not show skyrim.ini.

Starting the INI configurator plugin results in the following error:

Plugin "Configurator" failed: Traceback (most recent call last):
  File "D:/Games/Skyrim/Mod Organizer/current/plugins/pyCfg.py", line 576, in display
    self.updateSettings(settings, iniFile)
  File "D:/Games/Skyrim/Mod Organizer/current/plugins/pyCfg.py", line 477, in updateSettings
    base_path = self._organizer.managedGame().documentsDirectory().absolutePath()
  TypeError: No to_python (by-value) converter found for C++ type: class QDir

This is on a Windows 10 install.

**Comment by MindscapeNexus** [comment]
I'm receiving the same error message (I believe), however, I do have skyrim.ini in the INI Editor.

![image](https://user-images.githubusercontent.com/6716049/27204958-5af800cc-51eb-11e7-88be-e714c022aa86.png)

**Comment by MindscapeNexus** [comment]
I think I figured out what the problem is (on my end).  I didn't have Local Game Settings checked off in the Profile.  After checking this off, the Configurator ran again.

**Comment by Silarn** [comment]
This may be related to the local profile issues that were recently fixed. We need to test this on the latest builds to see if it still occurs.

**Comment by Silarn** [comment]
The configurator issue was fixed. The INI editor does not seem to work with global inis. I will need to investigate.

**Comment by Silarn** [comment]
The ini editor will work with local profile inis as of the current version but will not fall back to global inis

**Comment by Al12rs** [comment]
This has been implemented and the iniEditor.dll is available in #builds on the discord channel.
