### ISSUE TITLE
Mod Organizer 2.2.0 Reports Campfire and Frostfall as Incompatible Plugins

### ISSUE THREAD

**Issue by Ozyman2195** [ModOrganizer2/modorganizer#703]
## The problem:
Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our [discord channel](https://discord.gg/5tCqt6V)

I updated from 2.1.6 on an existing game that I was using for trying out mods.  I had the following mods installed: USSEP, SKSE64, SkyUI 5.2E, A Quality World Map 9.0.1, Static Mesh Improvement Mod, SSE Engine Fixes 4.3, Campfire 1.12.1, and Frostfall 3.4.1.  This set of mods ran fine under 2.1.6 and gave me no issues.

After updating over the previous install as instructed on the MO2 Nexus page, the Red Triangle warning icon lit up with the message: "Script extender log reports incompatible plugins".  The only way to turn it off is to uncheck both Campfire and Frostfall.

## To Reproduce:

1. Install mods as listed above using 2.1.6. 
2. Download and run the MO2 2.2.0 installer over the existing installation.

## Environment:

* Mod Organizer Version that exhibits the issue:  2.2.0
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.1.6
* Desktop OS/version used to run Mod Organizer:  Windows 7 Pro x64

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed.

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

https://gist.github.com/Ozyman2195/9f702fb49b1b1f1e7aba40822b3f47a9

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

Not sure where they are.  I added the logs that I could find at the GIST listed above.

Gordon

**Comment by LostDragonist** [comment]
Campfire 1.12.1SEVR contains an out of date version of PapyrusUtil that is indeed incompatible with current versions of SKSE64/Skyrim SE.  You can make that error go away by installing the current version of PapyrusUtil and making sure it loads after Campfire.  You can also delete the PapyrusUtil from Campfire as it is doing nothing.

To clarify in advance, the warning is a new warning in 2.2.0.  The mod was broken with 2.1.6.  It just wasn't being reported as broken therefore you didn't know it was broken.

I'm closing this assuming one of those things fixes it.  Feel free to reopen and provide more information if that's not the case.

**Comment by Ozyman2195** [comment]
As instructed, I downloaded the latest version (3.7) of PapyrusUtil SE with MO2.  Even though I activated it, the warning did not go away.  I tried moving it both above and below Campfire and Frostfall, but it made no difference.  I also tried deleting the copy of PapyrusUtil inside Campfire, but that didn't make any difference either.

![image](https://user-images.githubusercontent.com/50278877/57187456-f7586200-6ea3-11e9-96c2-03a1fff4ddf1.png)

**Comment by LostDragonist** [comment]
Did you run the game?  You have to run the game to refresh the log the notification is based on.

**Comment by Ozyman2195** [comment]
No, your reply didn't say anything about rerunning the game.  I have now done so, closed MO and reopened, and it is still there exactly as before.

Regards, Gordon

------ Original Message ------

**Comment by Ozyman2195** [comment]
Nevermind, it threw files into the Overwrite folder and I didn't notice.  Once I removed them, it was fine.

Regards, Gordon

------ Original Message ------
From: "Ozy Mandias" <ozyman2195@hotmail.com<mailto:ozyman2195@hotmail.com>>
To: "ModOrganizer2/modorganizer" <reply@reply.github.com<mailto:reply@reply.github.com>>
Sent: 5/4/2019 7:40:57 PM
Subject: Re[2]: [ModOrganizer2/modorganizer] Mod Organizer 2.2.0 Reports Campfire and Frostfall as Incompatible Plugins (#703)

No, your reply didn't say anything about rerunning the game.  I have now done so, closed MO and reopened, and it is still there exactly as before.

Regards, Gordon

------ Original Message ------
