### ISSUE TITLE
Incompatbility with NVR-NVGE Viva New Vegas Preset

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#706]
User report by Qolore722#7568 on Discord.

Fallout NV, MO 2.2.0.  User reports an error message when trying to change in-game settings or save the game.  Issue is not present in MO 2.1.6.

![](https://cdn.discordapp.com/attachments/403979692501106688/574407538817368094/Untitled.png)

Minimum load order to reproduce the issue appears to be:
* [NVSE](http://nvse.silverlock.org/)
* [New Vegas Reloaded - NVGE](https://www.nexusmods.com/newvegas/mods/65525)
* [Viva New Vegas - NVGE Preset](https://www.nexusmods.com/newvegas/mods/66650)

**Comment by LostDragonist** [comment]
This might actually not be an MO2 issue.  I can get this to occur by installing the mods outside MO2.  The problem also occurs with mods installed in MO 2.1.6.

**Comment by LostDragonist** [comment]
Changing SaveSettings from 0 to 1 in the preset's INI file makes the settings work again.  That seems like such a weird setting to have disabled in a distributed preset.

**Comment by Zarggg** [comment]
Looks like the author of Viva New Vegas uploaded a new version today that corrects this issue.
