### ISSUE TITLE
nxmhandler Doesn't handle short download links correctly

### ISSUE THREAD

**Issue by EssGeeEich** [ModOrganizer2/modorganizer#708]
## The problem:
nxmhandler can't handle short "premium" links correctly.

## To Reproduce:

Go to this page: `nxm://Skyrim/mods/3863/files/1000172397`

Currently, nxmhandler will show [this alert](https://i.imgur.com/ggX2zFb.png).

## Environment:

* Mod Organizer 2.2.0
* I recall a previous version was working correctly
* Windows 10

I can't really pinpoint the previously working version.

## Details:

Another friend has confirmed that those short links used to work.
Part of the NXMUrl code also make it look like it should work.

This link:
`nxm://Skyrim/mods/3863/files/1000172397`
should work correctly for premium users.

For the time being, this link:
`nxm://Skyrim/mods/3863/files/1000172397?key=0&expires=0&user_id=0`
seems to work just fine.

What strikes me as odd, is that this link:
`nxm://Skyrim/mods/3863/files/1000172397?key=0&expires=0`
does NOT work.

Odd, because the NXMUrl regex is the following:
`nxm://([a-z0-9]+)/mods/(\\d+)/files/(\\d+)\\?key\\=([^&]+)\\&expires\\=(\\d+)`
As seen [here](https://github.com/ModOrganizer2/modorganizer-uibase/blob/master/src/nxmurl.cpp#L27).

## Link to Mod Organizer logs:
The issue is with nxmhandler, so no logs will be provided.

**Comment by TanninOne** [comment]
This is actually a bit problematic as Vortex will support nxm://Skyrim/mods/3863/files/1000172397
but not nxm://Skyrim/mods/3863/files/1000172397?key=0&expires=0&user_id=0

Basically Vortex makes no assumption on what keys, expires or user_ids are valid, if the link contains them, Vortex will relay them to the api.
And the server side api will do the same: If the user_id is 0, it will try to match the key against a userid of 0, so the request will fail.

**Comment by Silarn** [comment]
I'm not really sure why I didn't see this class when I was first modifying the link handling to parse the attributes but I should be able to adjust it to just use QUrlQuery to check for those attributes rather than relying on regex.

**Comment by Silarn** [comment]
The latest alpha builds should handle these links better. Regex is only used to get the game, mod, and file IDs. Parameters are parsed separately. In addition, if a premium account is used we essentially ignore any parameters. Otherwise we attempt to prevalidate the user id against the current API key, as that is derived from the token by the API. I suppose we should also attempt to check the expiration as well.

**Comment by EssGeeEich** [comment]
The issue seems to be persisting.
I am still unable to get nxmhandler to run properly on these links.
This is for Alpha 1, and for Alpha 5 as well.

If I saw correctly, there should be no more issues for Mod Organizer.
But the issues may be persisting inside the nxmhandler project.

**Comment by EssGeeEich** [comment]
QRegularExpression::PartialPreferFirstMatch expects more characters at the end of the regex.
It should be changed into QRegularExpression::PartialPreferCompleteMatch in order to complete the support for premium-like links.

See: [QRegularExpression docs](https://doc.qt.io/qt-5/qregularexpression.html#MatchType-enum).

**Comment by Silarn** [comment]
Fixed by ModOrganizer2/modorganizer-uibase@785d33714de4d66ef582c8818b3731a9beec60a4 - probably.

**Comment by EssGeeEich** [comment]
The code seems to work as expected now. Issue closed.
