### ISSUE TITLE
Cannot Update.

### ISSUE THREAD

**Issue by reconphil** [ModOrganizer2/modorganizer#713]
I tried to update my mods but "login failed".  When I put in my user name and password, it still failed.  I went to Nexus and put in user name and password and it logged in no problem.  I checked for a MO2 update and it said update available.  I tried to update and it said "login failed" and still would not accept my user name and password even though Nexus accepts it and logs me in directly through the website.  I tried going into "configure settings" to ensure the password and username weren't, somehow, corrupted and reentered them but it still says login failed.  I tried restarting my computer but the same thing happens.

**Comment by Silarn** [comment]
Update to 2.2.0, the old API has been shut down and previous versions will not be able to connect to Nexus.
