### ISSUE TITLE
Add warning if the game is installed in a protected folder (Program Files (x86))

### ISSUE THREAD

**Issue by nmeocisco** [ModOrganizer2/modorganizer#714]
## The problem:

Mod Organizer will display an access denied error for DLCFrostcrag.esp when performing various actions such as sorting plugins and even on exit of Mod Organizer. I have the original Oblivion and all the DLC installed from DVD, not the steam version. Based on the logs it appears that it is trying to set the file times for the esp when it is read-only in the installation folder. This happens when there are no other mods installed yet.

## To Reproduce:

Make sure that Oblivion and DLC for Frostcrag Spire are installed from the DVD into the default installation location of C:\Program Files (x86)\Bethesda Softworks\Oblivion, then perform various actions such as sorting plugins or simply exiting the program and a pop up message will appear with access is denied.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.0
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): First time using with Oblivion, never used an older version
* Desktop OS/version used to run Mod Organizer: Windows 10 1809 x64

## Details:

Below is a section from the logs where the error happens. It appears that Mod Organizer is trying to set file times on the esps when they are read-only in the installation folder.

22:04:32 [D] setting file times on esps
22:04:32 [C] uncaught exception in handler (object bossButton, eventtype 3): failed to access C:\Program Files (x86)\Bethesda Softworks\Oblivion\data\DLCFrostcrag.esp (Access is denied. [5])
22:09:37 [D] E:\Mods\Oblivion\profiles\Default\plugins.txt saved
22:09:37 [D] E:\Mods\Oblivion\profiles\Default\lockedorder.txt saved
22:09:37 [D] setting file times on esps
22:09:37 [C] uncaught exception in handler (object , eventtype 1): failed to access C:\Program Files (x86)\Bethesda Softworks\Oblivion\data\DLCFrostcrag.esp (Access is denied. [5])

**Comment by Al12rs** [comment]
For now you can manually remove the read-only flag. Since it's not a very common occurrence and the user can solve it by themselves this has low priority.

**Comment by nmeocisco** [comment]
The problem is though is that the read-only flag isn't actually set when I right click on the properties of the file. I am guessing the problem has to do with the DVD installing into "C:\Program Files (x86)" which is not meant to be modified by regular users. I looked at maybe changing the permissions, but I can't make sense of the Windows security settings. Would be good if Mod Organizer would open these files in read-only mode since it really shouldn't be modifying ESP files anyway just doing things like sorting or exiting the program.

**Comment by Al12rs** [comment]
Ah, no Mo needs to be able to change the filetime on the dlc to make sure it gets loaded before other mods. Could you try starting Mo2 as admin instead?

**Comment by Al12rs** [comment]
You should not install games you intend to mod into Program Files (x86), as programs need admin rights to modify files inside that folder.
