### ISSUE TITLE
MO2 Unable to download from Nexus - "server replied: Not Found"

### ISSUE THREAD

**Issue by minerman5777** [ModOrganizer2/modorganizer#722]
Gist: https://gist.github.com/minerman5777/949b47ac77931f646d3483b026cc5ae3

I can't download mod from the nexus via the mod manager/vortex button. Manual installation works fine, but I'd much rather let MO2 do everything. This is my first time using MO2 in a few months and I was sure to update to the latest version.

**Comment by LostDragonist** [comment]
You need to update to 2.2.0.  It looks like you may have done so at some point but went back to 2.1.5?  It's possible you didn't point the updater/installer to your previous MO2 location and now you have two different installs going on.  The installer defaults to "C:\Modding\MO2" so maybe go check that out.

**Comment by minerman5777** [comment]
That is 100% what happened. Seems I forgot I had MO2 previously installed in Documents. I just updated my desktop shortcut, so I should be good to go. Thank you!
