### ISSUE TITLE
Unable to start any application through MO2 2.2.0

### ISSUE THREAD

**Issue by DeadyJ** [ModOrganizer2/modorganizer#729]
## The problem:
I am unable to start any application through the latest update of MO2. I rewrite the binary's for F4SE and Fallout itself, even Body slider, it will attempt to open it, but just restart to the MO2 home screen. If I open the applications directly, or through steam they work fine however none of my mods installed through MO2 are installed.

## To Reproduce:

1. Go to MO2 
2. Click on Run
3. Helper.exe opens
4. MO2 closes then reopens without opening intended application.

## Environment:

* Mod Organizer Version that exhibits the issue:2.2.0
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):Previous
* Desktop OS/version used to run Mod Organizer:Windows 10 Version:1803

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.
![image](https://user-images.githubusercontent.com/51007818/58359986-271bd980-7e54-11e9-9d73-93213d1b802c.png)\
![image](https://user-images.githubusercontent.com/51007818/58360019-54688780-7e54-11e9-9c1e-919e937fcc36.png)
![image](https://user-images.githubusercontent.com/51007818/58360028-664a2a80-7e54-11e9-8eec-4f5f5aee2e25.png)

### USVFS:
https://gist.github.com/DeadyJ/195991e9f96fdc80ede5bbc8314a181e#file-usvfs-2019-05-24_22-30-02-log

### MO Interface:
https://gist.github.com/DeadyJ/fd578f0d52608941becd734785713ed6#file-mo_interface-log

**Comment by LostDragonist** [comment]
You have the game set to run as admin.  MO is restarting itself in admin so you can run the game as admin.  You'll need to click run again.  There should be a window telling you this but I'm guessing you hid it at some point.  You can reset that dialog by going to settings and finding the reset dialogs button.

**Comment by DeadyJ** [comment]
So do I run MO as an admin and not run steam as an admin then? If I choose to run MO without the admin selection it works fine but I'm not sure what the differences are between MO w/ admin and steam w/o admin and vice versa.

**Comment by LostDragonist** [comment]
Ideally, you run nothing as admin as that's the intended method.

If you need to run Steam or Fallout 4 as admin, you probably need to run MO2 as admin as well.
