### ISSUE TITLE
Wrye Bash and MO2 2019

### ISSUE THREAD

**Issue by ClausA78** [ModOrganizer2/modorganizer#737]
I have used 12 hours to try and resolve this issue, i reinstall all my steam games in c: drive not program files that has permission issues. also MO2 and Wrye Bash are in the root folder with steam, however i had to place MO2 to E drive because of 200gb mods.

When i set the location of Wrye Bash and try to launch it, it first comes with folder in use in the temp folder, i have tried all the suggest fixes such as using an lockhunter and all that it may get wrye bash to launch a single time, but when you try to create a bashed patch you get another folder that's in use which is Docs everytime while Mod Organizer has an empty overwrite btw.

Please fix your program, everything works outside MO2 so its obviously your problem.

**Comment by Al12rs** [comment]
Please provide the information requested in the issue report template. Like what version of Mo2 you are using and what version of Windows you are using.
As written on the Nexus page if you are on win 10 you need to update to the latest version as there is a build of win 10 that makes wb not work through Mo2.
https://cdn.discordapp.com/attachments/347329036084707330/582592061694541834/Screenshot_20190527-173204.png

**Comment by ClausA78** [comment]
Thanks for the reply btw i love Mod organizer but i'm at 255 plugins now and need a patch, could the update be this ?

2019-05 Cumulative Update for Windows 10 Version 1803 for x64-based Systems (KB4499183)

**Comment by Al12rs** [comment]
You need to be on 1809 or higher, there is already 1903 I think for some people.
The tempfile will not remain there once it works. You can delete it. It's part of the bug that doesn't allow renaming it.

**Comment by ClausA78** [comment]
The update a assistant start windows 10 setup like it wants to installl a new windows copy so i panicked and closed it down.

**Comment by ClausA78** [comment]
https://gyazo.com/b96d9a1564fd55c0ffb1af5f48bd7b33

**Comment by Al12rs** [comment]
Glad you got it working!
