### ISSUE TITLE
[Bug] MO2 and TES5Edit - TES5Edit cannot overwrite original esm with cleaned esm

### ISSUE THREAD

**Issue by Aareon** [ModOrganizer2/modorganizer#741]
## The problem:
Running TES5EditQuickAutoClean (4.0.2) via MO2 (2.2.0), selecting `Dawnguard.esm` for cleaning and closing, TES5Edit cannot rename Dawnguard save to `Dawnguard.esm`.

## To Reproduce:

1. Open MO2 (non-admin), run TES5EditQuickAutoClean (non-admin)
2. Click on `Dawnguard.esm`
3. Wait for cleaning, `Ctrl+S` to ensure everything is saved.
4. Close TES5Edit
5. See error

## Environment:

* Mod Organizer Version that exhibits the issue: `2.2.0`
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: `Windows 10 Version 10.0.17763`

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.
1. [After cleaning](https://i.imgur.com/JGetKmi.png)
2. [Ctrl+S](https://i.imgur.com/8sbARYf.png)
3. [Close TES5EditQuickAutoClean](https://i.imgur.com/csqwLee.png)

### USVFS:
[usvfs-2019-06-01_18-20-03](https://gist.github.com/Aareon/120958b321a383eed21b45a91f8a9431)

### MO Interface:
[mo_interface](https://gist.github.com/Aareon/7a3203b73957c628b91bbcf4bbaf0f6e)

**Comment by Aareon** [comment]
Any suggestions for this? Or perhaps where I could get started if I wanted to try to fix this myself?

**Comment by Al12rs** [comment]
This should be fixed with the new usvfs files available on discord. Could you please test if the usvfs patch there fixes the problem? 
https://discord.gg/6GKR9jZ
