### ISSUE TITLE
MO 2.2 unable to handshake with Nexus.

### ISSUE THREAD

**Issue by Leer0x** [ModOrganizer2/modorganizer#743]
## The problem:
I just downloaded and installed Mod Organizer 2 v2.2.0 to find that there is a new API which this update uses new code to interface with. Upon clicking "Connect to Nexus" on a brand new installation (I have tried both Zip and executable installations to no avail), It tells me to login within the browser and accept the prompt...however this never shows up. In the debug console at the bottom of MO it gives me several error messages (All of these in MO Interface GIST at the bottom of this issue report).

## To Reproduce:

As far as I can tell all I did was install a new installation of the file currently on the Nexus page for Mod Organizer 2 (v2.2.0) as of 06/02/19 9:00pm EST. It always gives me the error "Failed to retrieve Nexus API Key". a browser window should pop up; however, none of my browsers bring up this authorization page.

## Environment:

* Mod Organizer Version that exhibits the issue: v2.2.0
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.1.6 (Legacy API)
* Desktop OS/version used to run Mod Organizer: Windows 10 (x64)

### USVFS:
https://gist.github.com/Leer0x/329e1e8eec156dc42f5dbb5474d13d89

### MO Interface:
https://gist.github.com/Leer0x/403c2b8cc2e4d914af5165a280c6cc6c

**Comment by LostDragonist** [comment]
The Nexus appears to be having server problems right now.  There's nothing to be done but waiting.

**Comment by Leer0x** [comment]
@LostDragonist I'll leave this up till issue resolves itself thru Nexus coming back.

**Comment by radroachhd** [comment]
I am having this issue as well.

**Comment by andreyka909** [comment]
Same problem here.

**Comment by LostDragonist** [comment]
I've been told the issue is fixed now.  Let me know if you're still having problems and I'll pass them on.

**Comment by dfarley1** [comment]
I was having the problem last night but it's fixed now!  Maybe there should be some kind of error message on MO's part when it fails to connect?  Right now it does nothing but eventually times out.

**Comment by radroachhd** [comment]
Yes, it's indeed fixed as of now.

**Comment by Leer0x** [comment]
Issue resolved. Closing this thread.
