### ISSUE TITLE
Nexus API Connection

### ISSUE THREAD

**Issue by wondergeekak** [ModOrganizer2/modorganizer#745]
## The problem:
When trying to setup MO2 version 2.2.0, I go in to connect the API and no browser window ever opens. I can access nexusmods site from all of my browsers (Edge, IE, Chrome, Firefox) with no issues. Have tried switching default browser, rebooting system, then trying again. No change in result.

## To Reproduce:

1. Go to Mod Organizer settings
2. Click on Nexus tab
3. Click on button to connect API.
4. System just waits, no open.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.0
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.1.7 Alpha 3
* Desktop OS/version used to run Mod Organizer: Windows 10 1903 x64

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

### USVFS:
<script src="https://gist.github.com/wondergeekak/f7991e3166e04dbaf190859e29f878a8.js"></script>

### MO Interface:
<script src="https://gist.github.com/wondergeekak/7b36531d4ccc5b515abc7702a82b1a3c.js"></script>

**Comment by lolascenekid** [comment]
I am having this issue too how can i fix it?
