### ISSUE TITLE
[USVFS] Not all files exist in VFS

### ISSUE THREAD

**Issue by maciozo** [ModOrganizer2/modorganizer#757]
## The problem:
Some files are visible, but not accessible under the virtual file system.

## To Reproduce:

1. Install `XP32 Maximum Skeleton Special Extended`.
2. Install `FNIS Behavior SE`.
3. Run any program through MO2.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.0, 2.1.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:
Windows Version 10.0.17763.503 (Windows 10 Enterprise Evaluation)
Windows Version 6.3.9600 (Windows Embedded 8.1 Industry Pro)
All as VirtualBox guests.

Note that Windows is running in a VirtualBox VM, and S: is a mounted share located on an EXT4 Linux host OS.

## Details:
In this case, the problem affects `XP32 Maximum Skeleton Special Extended` specifically, whose files/directories with a depth (from `/data/`) greater than 2, e.g. all directories under `/data/meshes/actors/`, are visible, but inaccesible. Files are also visible, but are empty.

![image](https://user-images.githubusercontent.com/15807067/59070995-6a426780-88ac-11e9-9d53-c13d90631cec.png)

However, some mods, such as `FNIS Behavior SE` aren't affected.

![image](https://user-images.githubusercontent.com/15807067/59071107-cd33fe80-88ac-11e9-87cd-973f2ae7caee.png)

Notice that in the image above, only the directories related to FNIS are visible in the VFS.

### USVFS:
https://gist.github.com/maciozo/7ce81f8b4974e82839311156c28b0882

Debug: https://gist.github.com/maciozo/bbfc0ff02ff55e1a0f0ab4c0c4855bcc

### MO Interface:
https://gist.github.com/maciozo/42af4b20a4509094cb2a07db9570521b

Debug: https://gist.github.com/maciozo/4a367c76d253b0506865f8270f0ed31d

**Comment by Al12rs** [comment]
This could be due to the version of windows you are running. Usvfs is incompatible with some of the older versions of win 10 as some of the functions that it hooks have been changed in those versions. 
You seem to be running a windows 10 Enterprise version for which we have no data. The version number would suggest that it's based on a few cycles back of the normal windows 10 home/pro. We currently support the last two versions of Windows 10 available as it's too difficult to support older versions.

I can't actually guarantee that is the issue here. Someone else would need to test whether the issue is reproducible with that windows version, or if this is a problem with the virtualized windows installation (I doubt though this is the case).

**Comment by Al12rs** [comment]
The version number traces back to a 1809 version of windows which *should* be fine though. 
Have you tried accessing the files with other programs that aren't explorer++?

**Comment by maciozo** [comment]
@Al12rs 
>Have you tried accessing the files with other programs that aren't explorer++?

7-Zip running through MO2 is also unable to access the relevant files. No error though - it just does nothing when you try to open say, the `meshes/actors/character` directory.

FNIS keeps throwing out error 53's about missing files (e.g. `ERROR(53): Could not find file 'S:\Games\The Elder Scrolls V Skyrim Special Edition\data\tools\GenerateFNIS_for_Users\temporary_logs\defaultfemale.xml'.`) when manually installed to the data directory. It does not run at all if installed with MO2.

---
I will also try with Windows 8.1 shortly. Hopefully that'll reveal if it's an issue with virtualisation.

**Comment by maciozo** [comment]
It does not work on Windows 8.1 either, @Al12rs. I guess this makes it an issue with the virtualisation process itself, which is weird, since the way I understand it, USVFS shouldn't really care.

**Comment by Al12rs** [comment]
The drive that is seen by the VM, what filesystem does the cm see on it? Are you doing some kind of links, like symbolic or hardlinks?

**Comment by maciozo** [comment]
The guest OS sees the drive as VBoxSharedFolderFS. It is a VirtualBox shared folder.

The only symbolic links I'm using are on the Linux side (https://github.com/ajventer/ksp_stuff/blob/master/movfs4l.py), since VFS does not work on Linux. I remove the symbolic links before running MO2.

Interestingly, now that I've added some more mods, the situation seems to have gotten worse.

![image](https://user-images.githubusercontent.com/15807067/60104711-86218680-9751-11e9-8e9f-1ed76eb8e353.png)

**Comment by Al12rs** [comment]
Usvfs only supports ntfs and no other filesystems have been tested or even been considered during development as far as I know. So that could be the reason of the problem.

**Comment by maciozo** [comment]
That wouldn't really surprise me, but it still seems rather odd that it manages to work with *some* of the files, rather than all of them, or not at all.
