### ISSUE TITLE
Ability to disable read-only check for INI files

### ISSUE THREAD

**Issue by VisualVirus** [ModOrganizer2/modorganizer#758]
SkyrimVR
When using Bilago’s Configuration Tool for INI editing it normally locks all INI files to prevent their modification by the game.
This creates a problem in MO2 ver. 2.2 (was not a problem for 2.1.6) with a read-only check dialogue constantly popping up for Skyrimvr.ini whenever any program is launched through MO2. Interestingly, this is not a problem, ie. the dialogue does not pop, for other INI files such as Skyrim.ini or SkyrimPrefs.ini.

A good solution to maintain the compatibility with Bilago's tool would be to add the ability to disable this check as this dialogue is annoying as it constatly shows up when you want to launch any program from within MO2.

Setting skyrimvr.ini to writeable is not a good solution as it becomes read-only whenever you finish using Bilago's tool and besides keeping it read-only at all times prevents any unwanted modifications by the game.

Note (may be relevant): I do not use Profile specific INI files

**Comment by LostDragonist** [comment]
https://github.com/ModOrganizer2/modorganizer-uibase/pull/25 should takes care of this and will be in 2.2.2.
