### ISSUE TITLE
SkyrimCustom.ini now supported, but how please?

### ISSUE THREAD

**Issue by Raging-Beard** [ModOrganizer2/modorganizer#761]
Tried putting SkyrimCustom.ini in the My Folders location, and the MO profile, but the ini does not show up as available to edit in MO.

Am I getting it completely wrong? This is for Skyrim VR, should I be using this ini or adding to SkyrimVR.ini?

Thanks.

**Comment by LostDragonist** [comment]
It looks like our SkyrimVR plugin doesn't support a SkyrimCustom.ini file.  Should it?

**Comment by Al12rs** [comment]
It seems that SkyrimVR does not support SkyrimCustom.ini or at least from what I read it's ignored.
