### ISSUE TITLE
MO2 2.2.0 freezing requires End Task to close.

### ISSUE THREAD

**Issue by Rockon451** [ModOrganizer2/modorganizer#766]
## The problem:
Since the 2.2.0 update every time I click on the Warning Icon in the MO2 tool bar the program freezes and I have to use Task Manager to close. The pointer jumps to the far edge of the right hand monitor each time, I have MO2 running on the left hand monitor. It's like the pop up is not on the desktop instead located somewhere off screen to the right. 
Just tried to Right click on Overwrite and got the message that a window was already open and to restart if it wasn't.  
 

## To Reproduce:
Click on Warning Icon

## Environment:
Recently updated Win 10,intel I7, 16 g ram, NVidia 1070ti, 2 - 4k LG monitors. Did not have this issue with the previous version.

### MO Interface and usvfs

First time to do this so...
<script src="https://gist.github.com/Rockon451/165920dcd130b6b8ff58ff3421e3c541.js"></script>
### 
<script src="https://gist.github.com/Rockon451/ba3743d5ac0227102b5608b49ef2ece6.js"></script>

**Comment by Al12rs** [comment]
Try going in settings> workarounds> reset windows geometry. This is a step that is advised to be done each time you update Mo2.

**Comment by Rockon451** [comment]
That fixed the problem.
I did miss that step when I in stalled the update. My Apologies and thank
you for your time and assistance.

**Comment by Al12rs** [comment]
No problem

**Comment by PyroSoldat** [comment]
I've had occasions  that not even task manager's end task can get rid of it.. lmao

Only Solution is restarting PC
