### ISSUE TITLE
MO2 doesn't open the Nexus website.

### ISSUE THREAD

**Issue by heyhey546** [ModOrganizer2/modorganizer#767]
## The problem:
Mod Organizer 2 V2.2.0 doesn't open up a web browser to open the Nexus website.

## To Reproduce:

No idea. I just linked MO2 with Skyrim Special Edition and tried to link it with Nexus, but it said "Failed to retrieve a Nexus API key! Please try again. A browser window should open asking you to authorize."

## Details:
Whenever I press the Connect to Nexus button, no webpage opens and my only option from that point is hitting 'OK'. That's when I get the error I explained above.

### MO Interface:
https://gist.github.com/heyhey546/5c8b938a7a667e1d5ba88ed0e92024b4

**Comment by Al12rs** [comment]
It appears that the Nexus authentication server is currently having issues and Nexus is already aware.  You could download manually in the mean time, or you could try one of the new Dev builds available on the MO2 discord to manually insert the authentication key:
https://cdn.discordapp.com/attachments/403979692501106688/590272772324982805/unknown.png
https://cdn.discordapp.com/attachments/403979692501106688/590273194863099967/unknown.png
Link to the server: https://discord.gg/6GKR9jZ

**Comment by AJAdair110** [comment]
The newest Dev Build fixes this issue for me. It pops up on my browser correctly.

**Comment by Al12rs** [comment]
Nexus simply fixed the SSO server.
