### ISSUE TITLE
CBBE Not Working - Fallout 4

### ISSUE THREAD

**Issue by James0MEGA** [ModOrganizer2/modorganizer#768]
CBBE does not show in-game when Mod Organizer 2 runs. It works fine with BodySlide and Outfit Studio, and a manual install in the Steam folder functions normally (with or without F4SE). Running the game through Mod Organizer 2, with or without the mod installed (active or deactivated) reinstates vanilla assets. The MO2 folder directory is structured properly and all necessary files are in place, both in the mods folder and the Data tab of the application.

Any assistance would be appreciated, this is the first problem I've had with MO2. Everything else has been great so far!

**Comment by LostDragonist** [comment]
CBBE for FO4 has instructions in the description to make modifications to your INI files.  With MO2, these should be done in the INI editor in the tools drop-down menu to ensure the correct INI files are being changed.

Give that a shot and see if it fixes it.

**Comment by James0MEGA** [comment]
Should I modify both the Prefs and Custom ini files in MO2 in addition to
Fallout 4's? Apologies if I missed that: I don't remember seeing it in any
of the tutorials.

I'm doing a fresh install of FO4 right now just to be safe, I'll do that as
soon as it's available.

Thank you for the quick response!

J0

**Comment by LostDragonist** [comment]
The instructions say to edit Fallout4Custom.ini in MO2 so I'd start with that.

**Comment by James0MEGA** [comment]
Yep! That did it. Thank you for helping and being polite about it. I'll have to be more diligent on reading those install instructions in the future. Peace!

J0
