### ISSUE TITLE
2.0.8.3: File names are  truncated on Downloads tab

### ISSUE THREAD

**Issue by unqltango** [ModOrganizer2/modorganizer#77]
On the Downloads tab the filenames are shorter than the column width. The end of the files is chopped off.

[http://imgur.com/a/rZqHZ](http://imgur.com/a/rZqHZ)

In this example, I have 4 different versions of the USLEEP downloaded. The user has to hover over with the mouse pointer to see the full filename.

**Comment by Al12rs** [comment]
Fixed on new downloads tab
