### ISSUE TITLE
Ability to filter downloads based on mod ID

### ISSUE THREAD

**Issue by jmdavis** [ModOrganizer2/modorganizer#771]
**Is your feature request related to a problem? Please describe.**
Currently, it really isn't possible to find all the downloaded files related to a mod in the Downloads tab in MO unless they all happen to have a particular piece of text in their display names that you can search for (e.g. if the mod author was nice enough to put the mod's name in the names for all of its files). However, mod authors frequently do not name their files consistently, let alone put the mod's name in all of them. The result of this is that it's frequently impossible to use the filter on the Downloads tab to find all of the files for a mod unless you actually go to the Nexus and look up what the files listed for the mod are to then filter on them. It certainly isn't possible at present to filter on a mod's Nexus ID to find them, because the mod ID is not in the display names unless the file was added manually, and "Query Info" was never used on it, so the display name is then the actual file name.

**Describe the solution you'd like**
I'd like the filter on the Downloads tab to filter on both the display name and the actual file name, because files from the Nexus contain the mod's Nexus ID in their actual file names (whereas the name from the Nexus which becomes the display name does not, and any files not from the Nexus just get their file name displayed anyway, meaning that their display name _is_ the file name). That way, it becomes possible to filter the files based on mod ID.

**Describe alternatives you've considered**
Alternatively, it would make sense to just have the filter treat numbers as possible mod IDs and display the file if its associated Nexus mod ID matches the filter string. However, that's a more complicated solution, and it relies on "Query Info" having gotten the mod ID right (which it should do, but there have historically been problems with that). It _would_ have the advantage though of making it possible to have files which are part of an installed mod but don't come from the Nexus be treated as part of the mod in the filter. However, given that MO doesn't currently give you the ability to tell it the Nexus mod ID of a file (meaning that the only way to do that would be to manually edit the associated .meta file), that's not something that would really happen in practice. Rather, such files simply wouldn't have a Nexus mod ID. Also, it's arguably better practice to have such files installed in a separate MO mod that then overwrites the files of the one associated with the mod on the Nexus rather than installing them to the same MO mod.

An even simpler solution would be to just always filter on the file name rather than the display name given that the display name should be part of the actual file name if the file is from the Nexus (since the Nexus seems to always put the name it shows on the mod's files tab in the name of the file you download, meaning that the display name in MO should always be part of the actual file name), and files not from the Nexus already have their file name as their display name. However, I could see that backfiring if there ever isn't a direct link between the display name and the file name (e.g. if it's actually possible to get a file from the Nexus where the name displayed on the Nexus page isn't actually part of the file name or if we ever got the ability in MO to set the display name for a download). So, it's probably better to just filter on both the display name and the actual file name.

Of course, it would also be possible to combine solutions and filter on the Nexus mod ID in the .meta file, on the display name, and on the file name, but that seems like overkill to me.

**Comment by LostDragonist** [comment]
The default display for downloads is the download files name.  Do you have "download meta information" checked in the MO2 settings?  That'll make it so that other stuff is shown instead of the file name.

**Comment by isanae** [comment]
The latest development build on discord adds the mod name, file version and mod id to the downloads tab. They are sortable and included in the filter.

**Comment by jmdavis** [comment]
> The default display for downloads is the download files name. Do you have "download meta information" checked in the MO2 settings? That'll make it so that other stuff is shown instead of the file name.

Yes. I have that checked. Having it display stuff other than the file names isn't the problem (it's often more legible). The problem is that you then can't filter on the file name, so you can't filter on the mod ID.

> The latest development build on discord adds the mod name, file version and mod id to the downloads tab. They are sortable and included in the filter.

Well, if that's the case, then presumably, that will fix the problem.
