### ISSUE TITLE
Make Version column in mod list respect system date formatting.

### ISSUE THREAD

**Issue by lukemoore66** [ModOrganizer2/modorganizer#776]
The 'Version' field in the mod list does not respect the system date format, yet the installation date and time does, as well as download filetimes etc... I'm from Australia and it is frustrating when reading dates back-to-front, especially when it is formatted correctly in all other sections of MO2.

If possible, could we have the Version column in mod list respect system date formatting please?

**Comment by isanae** [comment]
Confirmed, versioninfo.cpp:168 hardcodes the date in ISO format (Y-M-D) instead of localizing it.
