### ISSUE TITLE
MO2 is not installing my FO4 mods with their BA2 assets

### ISSUE THREAD

**Issue by DJWolf1** [ModOrganizer2/modorganizer#777]
## The problem:
I don't understand Discord.  Where do you chat?  Therefore I must come here.  Several of my FO4 mods installed by MO2 aren't working.  Some don't even show up in the 'Plugins' panel although they are in the download list and checked in the Left hand mods panel.  I found their "ba2" asset in 'Archives'.  They are unchecked and MO says it isn't managing them and that they will ignore an installation order.  I can't check them and the only option is to 'extract' them but to where?  And, should I?  How do I get MO to install my mods?

## To Reproduce:
Used MO 2 to download and install mods from Nexus.  Right click on download to choose install.  Checked mod in Left hand panel.  Some did and some didn't appear in plugins

## Environment:

* Mod Organizer Version that exhibits the issue:  V2.2
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Win 10 Professional

## Details:
I cannot be clearer than I have been.

## Link to Mod Organizer logs:
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed.

### USVFS:
I'm really hoping you don't need them.  IT is not my field

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by LostDragonist** [comment]
Can you give an example of the mods you're talking about?

MO2 doesn't manage BSA/BA2 files.  The only way they'll be active is if you have a plugin enabled that will activate them.

**Comment by DJWolf1** [comment]
Sure, and thank you.  LED Platinum Pip-Boy Deluxe (Clean-New-Silver-Metal-PipBoy) by Mega TimX and then there are another 20 or so ba2 texture files that I can't identify as being from one mod or another.  However, I had thought that a couple of my settlement building mods were included but I've found them further down in the archive list and they are checked.  The problem is that they, and half of the rest of my mods aren't in the game.  I am beginning to suspect that something is conflicting with my settlement menus and should take a closer look with FO4Edit.

**Comment by LostDragonist** [comment]
>LED Platinum Pip-Boy Deluxe (Clean-New-Silver-Metal-PipBoy) by Mega TimX

https://www.nexusmods.com/fallout4/mods/4511 

This mod doesn't have any BA2 files.  If you're not seeing this take effect, it's possible you haven't set up your FO4 installation for modding.  You need to follow the steps in "How to enable Fallout 4 mods" in this page: http://wiki.tesnexus.com/index.php/Fallout_4_Mod_Installation.  You'll want to do that using the MO2 INI editor in the tools menu (puzzle pieces in the toolbar).

**Comment by DJWolf1** [comment]
Thank you so much.  After changing my .ini file, I got back a few of my settlement building mods but the pipboy remained brown and the magazines didn't glow.  So, I deleted all my mods, and reinstalled them from the download tab before starting a new game...  I must have done some serious harm because by the time I left the vault and reached Sanctuary in this new play-through, the magazines are still not glowing and the Pipboy is still brown.  I'm at a bit of a loss but I can't thank you enough.  This was not a MO2 issue but you helped anyway.

**Comment by DJWolf1** [comment]
I used to be a engineer and considered myself to be so smart.  How humbling it is to bathe in idiocy.  I read your comment, went to the first link, followed it's instruction to alter my 'fallout4custom.ini file' because there couldn't be two of them...   I missed the bit about doing it in the MO2 interface... Sorry to have subjected you to this.
