### ISSUE TITLE
MO2 Not Downloading Above the 1MB/s cap 

### ISSUE THREAD

**Issue by koldarra** [ModOrganizer2/modorganizer#778]
After reinstalling MO2 today, I noticed my download speeds are incredibly slow despite being a pro member for nexus. They never go above 1.5 MB/s.

How do I fix this? I'm running MO2 v2.2.0

Fixes I've tried:

- Clearing cache and restarting computer
- Setting new preferred download location on Nexus
- Dragging and dropping preffered servers in MO2 Nexus Settings
- Reinstalling MO2

**Comment by Al12rs** [comment]
I can suggest logging in again. Closing this for organizational purposes, please reopen if you are still experiencing this problem.
