### ISSUE TITLE
Changes/additions to left-side mod organizing pane.

### ISSUE THREAD

**Issue by mealyman** [ModOrganizer2/modorganizer#779]
Would be cool if the icon could be different depending if it's an ESL file or a ESP/ESM file in the assets column.

Also, some sort of better way to move mods in the left pane, perhaps copy/paste or something like that, instead of dragging.  Gets tedious when you have a lot of mods, or screw up your asset order.

Ability to multi-select downloads in the right pane for deleting, etc.

**Comment by Al12rs** [comment]
You can edit the priority column of a mod directly to manually set the priority. Alternatively you can right click on a group of one or more selected mods and use the "Send to.." option. You can either send to a specific priority, to the top or bottom, or to a specific separator.
To create a colored separator right click on the modlist, All mods, create separator.

A cut and paste idea could be considered to be added in the future.

Regarding adding icons for the different types of plugins, I'm reluctant to doing is as it would clutter up the Contents column a lot. There are ESP, ESM, ESP flagged as ESM, ESL, esp flagged as ESL etc. I don't think it would be very practical. Also not all games supported by Mo2 have esls for example.

Multi select in download tab is planned but it's a lot of work to implement all the methods to work with multiple downloads in a performance friendly way. It's not high on the priority list.

**Comment by mealyman** [comment]
Great!  I thought there might have been some way to move them around without click+hold+drag that I didn't know about... 

Fortunately, I do have quite a few separators already created.

As for the other requests, not deal breakers, just considerations.  :)

Thanks!
