### ISSUE TITLE
Using the script compiler in Oldrim Creation Kit thru MO 2.2.0 puts compiled scripts (.pex files) in inconsistent places.

### ISSUE THREAD

**Issue by ogrotten** [ModOrganizer2/modorganizer#785]
## The problem:
In 220, when working on scripts, compiler output can go to seemingly unpredictable directories. In 216, it was consitent and predictable. 

Game is Oldrim.

## Workflow for 216
- Have MO running.
- Start CK thru MO
- CK > Gameplay Menu > Script Manager
- In MO, open the mod dir in explorer and open a script into your editor.
- Run Oldrim and get where you need to be.
- *Test the script.
- In script editor, make changes and save.
- CK > in Script Manager, rclick the script > Compile.  **<---Here's where the problem shows**
- Fix the forgotten paren or close quote and recompile.
- In game: console > `reloadscript <scriptname>` then load from recent save,
- Repeat from *Test the script.

In MO 220, the .pex resulting from a compile can wind up either in the mod dir or Overwrite, inconsistently. It could wind up Overwrite whether or not a previous .pex exists in the mod dir. When the .psc is in the steam game dir skyrim/data/scripts/source, compiling still puts the .pex into Overwrite.

In MO 216, compiling will always put the file into the mod dir, **_and_** it seems as if the VFS is updated to it's position because reloading the script in game is effective. Additionally, if the .psc is in the steam game dir skyrim/data/scripts/source, compiling will put the .pex into skyrim/data/scripts (required destination).

## Environment:

* 2.2.0 -- Mod Organizer Version that exhibits the issue:
* 2.1.6 -- Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Win10 -- Desktop OS/version used to run Mod Organizer:

I'm unable to attach logs. When I found it didn't work, I reverted back to 2.1.6 to verify that it worked.

**Comment by Al12rs** [comment]
This issues should hopefully be fixed with the latest dev build available on discord: https://discord.gg/6GKR9jZ
Could you please check if that is the case?

**Comment by ogrotten** [comment]
> This issues should hopefully be fixed with the latest dev build available on discord: https://discord.gg/6GKR9jZ
> Could you please check if that is the case?

I will attempt to try it this week or on the w'end.

**Comment by ogrotten** [comment]
I have not spaced this, I simply haven't been able to get to it. I've purposefully left the tab open tho so it's a reminder.

**Comment by ogrotten** [comment]
I went to discord today, downloaded and setup 2.2.2 alpha 4. 

I performed a brief test, but it appears to work as expected.

I shall do some stuff to it, see if I can break it, but at this point all seems copacetic. I'd say this is ok to "close" as "fixed". If it pops up again I'll do a new ticket and reference this one.

**Comment by Al12rs** [comment]
Thanks for testing, if you find that it isn't working please reopen
