### ISSUE TITLE
Fallout 4: MO2-managed fallout4custom.ini does not work

### ISSUE THREAD

**Issue by bartmoss** [ModOrganizer2/modorganizer#790]
## The problem:
I entered some settings in the MO2-maintained fallout4custom.ini via tools -> ini editor -> fallou4custom.ini tab. It looks like MO2 does not expose this to FO4; only by entering the same configuration under My Games\Fallout 4\fallout4custom.ini did the settings work.

If this is "by design", i.e. an unimplemented feature, it would be cool if the tab could be disabled. This just drove me quite crazy until I figured it out. :)

Version used: MO 2.2.0 Revision 179a738

**Comment by Silarn** [comment]
I thought that tool was supposed to choose the correct version of the file based on whether you have local ini settings turned on, but could be I have that wrong. Open the profile editor and see if that's turned on.

**Comment by bartmoss** [comment]
"Use profile specific INI files" is enabled, if you mean that.

**Comment by Al12rs** [comment]
unless we misspelled the file or fallout4custom.ini is not to be placed in the same folder with the other ini files it should be working. I checked the code and everything looked fine. I'm going to ask some users to see if it works for them.

**Comment by Al12rs** [comment]
apparently having the ini file to readonly could cause the game to not see it

**Comment by bartmoss** [comment]
I think maybe you are misunderstanding me (or I am not reading you correctly). The file in "My Games\Fallout4" works. It's the settings I edit directly in MO2 that do not take effect.

If you *are* referring to the files in MO2's Profile folder, well, the question would then be why they would ever be readonly.

But I just checked, "fallout4custom.ini" in "C:\Users\nils\AppData\Local\ModOrganizer\Fallout4\profiles\Default" is not read-only (nor is the other one).

**Comment by bartmoss** [comment]
Also, I realize the specific settings I wanted to change may or may not be of interest. It's essentially to enable loose files, i.e. the usual:

[Archive]
bInvalidateOlderFiles=1
sResourceDataDirsFinal=

I ran into it trying the Full Dialog interface mod, and assumed a bug in that, until the MCM mod also couldn't load its strings file. That's when I realized there was a deeper issue.

**Comment by Al12rs** [comment]
Archive invalidation should automatically be handled by MO2, at least I think. Could you try some other settings instead?

**Comment by Al12rs** [comment]
There is a setting for archive invalidation in the Mo2 profile settings

**Comment by Al12rs** [comment]
Another user was able to confirm that using the fallout4custom from MO2 with Profile INI files enabled works correctly by testing with:
```
[Grass]
iMinGrassSize=60
```
Set it to a value that is grossly different from your current one, like from 20 to 100 or from 60 to 20 and see if grass density changes in game

**Comment by bartmoss** [comment]
I'm thinking there is a deeper problem. I just had the odd issue that the vfs wasn't built correctly - it contained no mods etc at all. This also includes not applying the MO2-managed fallout4custom.ini settings correctly, as the game started with the intro - which is also disabled in my settings. The mods also did not show up in LOOT or the "explore virtual folder" option.

I assume this is the cause:

21:20:36.892 [I] command line "D:\Games\LOOT\Loot.exe" --game="Fallout4" is blacklisted
21:20:52.182 [I] command line "D:\Games\LOOT\Loot.exe" --game="Fallout4" is blacklisted
21:21:23.202 [I] command line "F:\GAMES\steamapps\common\Fallout 4\f4se_loader.exe" is blacklisted
21:22:41.109 [I] command line "F:\GAMES\steamapps\common\Fallout 4\f4se_loader.exe" is blacklisted
21:23:21.279 [I] command line "F:\GAMES\steamapps\common\Fallout 4\f4se_loader.exe" is blacklisted
21:24:19.347 [I] command line "F:\GAMES\steamapps\common\Fallout 4\f4se_loader.exe" is blacklisted
21:25:02.548 [I] command line "D:\Games\LOOT\Loot.exe" --game="Fallout4" is blacklisted
21:25:42.617 [I] command line "D:\Games\LOOT\Loot.exe" --game="Fallout4" is blacklisted
21:26:37.206 [I] command line "F:\GAMES\ModOrganizer2\explorer++\Explorer++.exe" "F:\GAMES\steamapps\common\Fallout 4\data" is blacklisted
21:28:10.203 [I] command line "F:\GAMES\steamapps\common\Fallout 4\f4se_loader.exe" is blacklisted

Full usvfs log: https://pastebin.com/3tSFSw1J

A restart of MO2, without any changes to my setup at all, seems to have corrected this.

The good news is, after the restart the settings are being applied correctly.

Of course I now wonder if something similar happened on the 4th, but unfortunately there does not seem to be any uvfs log from that day.

**Comment by Al12rs** [comment]
Blacklisting programs is a feature of Mo2 that you can access from the MO2 settings. I can't tell you why it would blacklist those programs supposing you didn't touch it

**Comment by bartmoss** [comment]
Didn't touch it, either before or after.

Programs blacklisted:

Chrome.exe
Firefox.exe
TSVNCache.exe
TGitCache.exe
Steam.exe
GameOverlayUI.exe
Discord.exe
GalaxyClient.exe
Spotify.exe

**Comment by Al12rs** [comment]
Somehow it borked up. Keep an eye on the logs and let us know if you manage to reproduce consistently.

**Comment by Al12rs** [comment]
Closing this for organizational purposes, please reopen if you are still experiencing this problem.
