### ISSUE TITLE
Add an option to disable specific flag icons from showing up in the Flags column

### ISSUE THREAD

**Issue by ThisIsPatrick** [ModOrganizer2/modorganizer#795]
With the addition of newly added flags in the installed mods flags column, some mods are cluttered with flag icons.

The column has primarily been used to make tracking down file conflicts/overwrites simple, adding flags which don't contribute towards it without the option of disabling them undermines the convenience of this feature.

**There should be an option to disable less important flags like mod tracking and endorsement, or any specific flag of a users choosing**. There's already the option of "won't endorse" to remove the endorsement icon but the newer tracking flag has no option like that. Currently, in order to stop seeing the flag you have to unendorse the file on the Nexus, which is an absurd compromise.

**Comment by Silarn** [comment]
To be honest it might make sense to move conflict flags to their own column. This would be a simpler fix.

**Comment by LostDragonist** [comment]
I think moving the conflict flags to their own column would make sense as an independent change.  They're already treated differently than the others (code to keep them aligned when the column is "big enough").

I don't think it's a fix by itself.  There have been a few requests here and there to disable *just* this flag or *just* that flag.

**Comment by Holt59** [comment]
Closing since conflicts have their own column since... well, I don't know, since before I started working on MO2, so this should probably have been closed ages ago.
