### ISSUE TITLE
Loot failed. Exit code was:1

### ISSUE THREAD

**Issue by 1069761512** [ModOrganizer2/modorganizer#800]
Mo version 2.2.0
SkyrimSE 1.5.73
Run the LOOT button
Loot failed. Exit code was:1

**Comment by 1069761512** [comment]
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/3412118/mo_interface.log)

**Comment by Silarn** [comment]
Can you replicate this on 2.2.1? There have been several updates to libloot which might affect this issue.

**Comment by Al12rs** [comment]
Closing this for organizational purposes, please reopen if you are still experiencing this problem.
