### ISSUE TITLE
Failed to request file info from nexus: Error transferring

### ISSUE THREAD

**Issue by ProdigyDxx** [ModOrganizer2/modorganizer#802]
## The problem:
Whenever I try to download a mod from nexus as a mod manager download  I get this response: Failed to request file info from nexus: Error transferring. this didn't happen before with the same version of MO2.

## Environment:

* Mod Organizer Version that exhibits the issue: MO2 v2.2.0
* Desktop OS/version used to run Mod Organizer: win10 1809

## Link to Mod Organizer logs:
[usvfs-2019-07-26_18-26-57.log](https://github.com/ModOrganizer2/modorganizer/files/3438069/usvfs-2019-07-26_18-26-57.log)
[usvfs-2019-07-26_18-31-42.log](https://github.com/ModOrganizer2/modorganizer/files/3438070/usvfs-2019-07-26_18-31-42.log)
[usvfs-2019-07-26_18-37-12.log](https://github.com/ModOrganizer2/modorganizer/files/3438071/usvfs-2019-07-26_18-37-12.log)
[usvfs-2019-07-27_10-23-02.log](https://github.com/ModOrganizer2/modorganizer/files/3438072/usvfs-2019-07-27_10-23-02.log)
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/3438073/mo_interface.log)
[usvfs-2019-07-14_15-51-27.log](https://github.com/ModOrganizer2/modorganizer/files/3438074/usvfs-2019-07-14_15-51-27.log)
[usvfs-2019-07-26_18-18-16.log](https://github.com/ModOrganizer2/modorganizer/files/3438075/usvfs-2019-07-26_18-18-16.log)

**Comment by Silarn** [comment]
Please try updating to 2.2.1 first and see if you can replicate the issue.

**Comment by ProdigyDxx** [comment]
Before I updated I tried again with 2.2.0 and it worked again. All of a sudden the problem was gone.

**Comment by Al12rs** [comment]
Closing this for organizational purposes, please reopen if you are still experiencing this problem.
