### ISSUE TITLE
File already exists error when trying to install mod configuration menu mod for TTW Mod Organiser.

### ISSUE THREAD

**Issue by E-Gamma-102** [ModOrganizer2/modorganizer#803]
I've tried installing the mod from the fomod file in the zip file but I get the same error. I've deleted any remnants of the mod in the temp folder but same error. I seem to be having the same issue with Project Nevada and the character overhaul mod. Where it says "The file exists". I have downloaded these mods before with fallout  but I had to do a clean install. I have TTW.

**Comment by Al12rs** [comment]
This seems to be an issue with the NMM code that handles the Fomod extraction. You need to clear out the files you have in the temp folder.
Closing this for organizational purposes, please reopen if you are still experiencing this problem.
