### ISSUE TITLE
failed to spawn fo4edit.exe failed to start process, parameter incorrect{87} MO2 V2.2.1

### ISSUE THREAD

**Issue by sillybob86** [ModOrganizer2/modorganizer#810]
## The problem:
I recently updated to MO2 v 2.2.1 from the most recent version.
Some of the executables do not work, (under fallout 4 instance, or skyrim se instance)
Bodyslide, gameclient, FNIS for example work.

LOOT, FO4Edit do not work, and give me "failed to spawn fo4edit.exe failed to start process, parameter incorrect{87}" pop up.

## To Reproduce:
Not sure how to reproduce, but here is what I have done.
1) rebooted computer
2) reinstalled mo2
3) reinstalled fo4edit/loot
4) re-added them to drop down list.

## Environment:

Version 2.2.1 is giving me this issue,  most recent(previous) version of Mo2 did not have these issues.
I run on windows 10.

## Link to Mod Organizer logs:
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed.

### USVFS:
https://gist.github.com/sillybob86/5b8ff9471f11af78eb809ee1a3e4627d

### MO Interface:
https://gist.github.com/sillybob86/ca017a28a3715a1efa6e41e27f258315

**Comment by Al12rs** [comment]
It looks like your antivirus ate the MO2 virtual library dll. Disable the AV or add explusions for the MO2 folder and try reinstalling MO2.

**Comment by sillybob86** [comment]
> It looks like your antivirus ate the MO2 virtual library dll. Disable the AV or add explusions for the MO2 folder and try reinstalling MO2.

Guess you are right, I didnt get/notice the "we moved a file to quarantine flag" last time

I already had exceptions to all 5 .exe i saw in ModOrganizer >

##Fix
So I re, reinstalled v2.2.1 by extracting, and copy and pasting the files into C:\ModOrganizer

This time, my antivirus flagged something from a heuristic scan.  I didnt see it last time i suppose, but anyway- even with the exceptions already there - I had to go into quarantine folder, and release the usvs.exe from jail.

**Comment by 352** [comment]
I had the same issue and have reported the false positive to, in my 
case, Bitdefender.
