### ISSUE TITLE
No handler found error! With pic :P

### ISSUE THREAD

**Issue by edumeyer99** [ModOrganizer2/modorganizer#811]
Hello people

I'm a big fan of the game. However, I always played it 'clean'. Now I would like to play with MODS.

I installed the program, but, it presents the following error.

Look at the picture.

![Sem título](https://user-images.githubusercontent.com/53628395/62401651-7b30f180-b55a-11e9-9493-1e00483a7a1e.jpg)

I'm sorry for the english, I'm from Brazil ....

**Comment by LostDragonist** [comment]
Resolved on Discord.  User is trying to download Skyrim SE mods in a Skyrim instance.
