### ISSUE TITLE
error downloading 

### ISSUE THREAD

**Issue by arkane149** [ModOrganizer2/modorganizer#813]
## The problem:
Since updating.  upon starting up i get a error aborting download.  Either you clicked on a premium only-link and your account is not premium. or the link was not generated by the link that was stored in mod organizer.  This is the account i have been using since 2017.  Restarting MO2 lets it work correctly.  I verified that my account was logged in.

## To Reproduce:

1. Go to 'any nexus download with manager link..'
2. Click on 'the link....'

## Environment:

* Mod Organizer Version that exhibits the issue:2.2.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):2.2.0
* Desktop OS/version used to run Mod Organizer:windows 10

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed.
### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!05:35:58 [D] Download started
05:35:58 [D] download requested: nxm://SkyrimSE/mods/18135/files/99342?key=fH7jPVQZ2JVvdY_xl6xuVw&expires=1565256957&user_id=48239063
05:35:58 [D] add nxm download: nxm://SkyrimSE/mods/18135/files/99342?key=fH7jPVQZ2JVvdY_xl6xuVw&expires=1565256957&user_id=48239063
05:35:58 [W] "Aborting download: Either you clicked on a premium-only link and your account is not premium, or the download link was generated by a different account than the one stored in Mod Organizer."
06:00:02 [D] Downloads after refresh: 1734
06:00:02 [D] save C:/Game Utilities/modorganizer/webcache/cookies.dat
06:00:02 [D] C:\Game Utilities\modorganizer\profiles\Yash\initweaks.ini saved
06:00:02 [D] C:\Game Utilities\modorganizer\profiles\Yash\plugins.txt saved
06:00:02 [D] C:\Game Utilities\modorganizer\profiles\Yash\loadorder.txt saved
06:00:02 [D] C:\Game Utilities\modorganizer\profiles\Yash\lockedorder.txt saved
06:00:02 [D] Load Mechanism: Mod Organizer
06:00:02 [D] USVFS DLL Name: usvfs_x64.dll

**Comment by Silarn** [comment]
It sounds like mo2 failed to parse your Nexus user id properly. However, you said restarting fixed it. Are you able to reproduce this consistently?

**Comment by arkane149** [comment]
Yeah it was doing this every time.  Today after replacing McAfee's it went through with out restarting it.

**Comment by Al12rs** [comment]
I'm closing this for organization purposes, please reopen if it's still an issue.
