### ISSUE TITLE
MO2 doesn't start the games

### ISSUE THREAD

**Issue by SoFFuSeD** [ModOrganizer2/modorganizer#814]
## The problem:
After downloading the mods I wanted and launching Skyrim with SKSE inbetween I ended up with the game not launching at all nor the normal version only the launcher works.No warnings of mods interfering nothing.

## To Reproduce:
No specific steps just used the platform as usual.

## Environment:

* Mod Organizer Version that exhibits the issue:
Latest version downloaded it the same day
* Desktop OS/version used to run Mod Organizer:
Windows 7 Professional Service Pack 1

## Details:
I was using the MO1 platform and after realising it's no longer supported I tried switching over to MO2 I followed the tutorial just in case something major changed and then proceeded to downloading all my previous mods from scratch. Between downloads, although there were no mod interferences, I launched the game with SKSE to make sure the game works. After finishing downloading all the mods and with no Wargnings i tried launching the game firstly through SKSE and after that not launching and showing a message(in the 1st screenshot) I tried opening the normal game, resulting in the same issue. Only thing working was the Skyrim launcher.

### USVFS:
https://gist.github.com/SoFFuSeD/8ae9f3c947972901f29fde278d3ffdfd

### MO Interface:
https://gist.github.com/SoFFuSeD/017ddb40bf5d2cbdf5239dc7879251c4

**Comment by SoFFuSeD** [comment]
https://imgur.com/a/oHpUKqZ forgot to include this...this is the problem that appears

**Comment by isanae** [comment]
Does the game start if you disable all your mods?

**Comment by SoFFuSeD** [comment]
> Does the game start if you disable all your mods? 

Just tried it and yes it starts...Thing is I tried launching it the same mods as I used with MO1 and still didn't start

**Comment by isanae** [comment]
You have incompatible mods that are preventing the game from starting. Enable them slowly, starting the game each time, until you find the offending one(s). This is not an issue with Mod Organizer.

**Comment by SoFFuSeD** [comment]
So I did the process and it appears that I did have and incompatible mod thank you a lot for taking blitz action and helping
