### ISSUE TITLE
FNIS In MO2 Problem

### ISSUE THREAD

**Issue by Tigertailz** [ModOrganizer2/modorganizer#816]
Can anyone help? I always get this problem when trying to run FNIS I have tried running MO2 as admin also tried running FNIS as admin, turned off all antivirus software, tried a clean install nothing works. I'am using Skyrim SE 1.5.80 and running FNIS through Mod Organizer.

ERROR(2012): Could not generate: weapequip.hkx staggerbehavior.hkx sprintbehavior.hkx shout_behavior.hkx magicmountedbehavior.hkx magicbehavior.hkx magic_readied_direction_behavior.hkx 1hm_locomotion.hkx 1hm_behavior.hkx

**Comment by Al12rs** [comment]
Please provide proper information such as what version of Mo2 you are running, windows version and the logs as described by the issue template.

**Comment by Tigertailz** [comment]
windows 10 Home Version 1809, MO2 V2.21

**Comment by Al12rs** [comment]
Closing for insufficient information (logs). We have other issues open regarding FNIS. For support please visit the dev discord server.
