### ISSUE TITLE
zip files don't drop into Downloads field

### ISSUE THREAD

**Issue by Delgathar** [ModOrganizer2/modorganizer#822]
## The problem:
When I try to drop an archive into downloads, 7z or zip it gives me the forbidden symbol.  

## To Reproduce:
1. Click on downloads tab in MO2.
2. Click on any zip or 7z file in explorer and attempt to drip in file area.

## Environment:
Windows 10.
M02 2.2.1

## Details:
I can drop indirectly if I click on the download arrow in Mozilla (for a manual download) and then drag the pop-up icon of the archive to the downloads window.  Screenshots seem to be disabled when I click on  the downolad button so no pictures.   But if I try to drag and drop the file from explorer it will not be allowed. 

### USVFS:  ### MO Interface:
There is no USVFS log for today.  mo_interface.log does not register an event for this action.

**Comment by LostDragonist** [comment]
Most of the time, this is due to running MO2 as admin.

**Comment by Delgathar** [comment]
That was it!  I run MO2 in admin so I can run VoiceMacro in admin so I didn't even consider that it might be an admin privilege issue.  If I can't mark this as resolved, someone else can.  Thank you LostDragonist.

**Comment by Delgathar** [comment]
Just trying to change the label to not a bug.

**Comment by Delgathar** [comment]
Learned I can't change the label.  Reclosing.  Have a nice day.
