### ISSUE TITLE
Information dialog not displayed properly (windows 7 custom theme)

### ISSUE THREAD

**Issue by neizvestnyy** [ModOrganizer2/modorganizer#824]
MO 2.2.1
using a custom windows 7 theme with patched dll by UltraUXThemePatcher
elements hit-boxes not aligned with their graphic representation
like stretching the display from top and bottom by the center
resizing the window does not change this behavior

a few screenshots showing this
when hovering an element
![hover](https://user-images.githubusercontent.com/32224016/64074390-e7faf100-ccaa-11e9-9adb-aa9939fc0d80.png)
a more visible example showing the shift between graphic and hit-box
![difference](https://user-images.githubusercontent.com/32224016/64074389-e7625a80-ccaa-11e9-9ad9-5a63560bc2f6.png)
the tabs on the top are partially hidden due to the stretching
![tabs](https://user-images.githubusercontent.com/32224016/64074391-e7faf100-ccaa-11e9-8a6c-659c61c98837.PNG)
the settings dialog which has a similar layout is displayed properly
![settings](https://user-images.githubusercontent.com/32224016/64074484-2d6bee00-ccac-11e9-86f4-66571d7bb0ea.PNG)

**Comment by Al12rs** [comment]
I'd say don't use that custom theme if it breaks applications 🤷‍♂️

**Comment by KerberX** [comment]
It's a known Qt problem. Happens quite randomly.

**Comment by Al12rs** [comment]
Independently with using that theme or not?

**Comment by KerberX** [comment]
I mean, when using custom theme.
