### ISSUE TITLE
Mod Organizer 2 won't load past loading screen

### ISSUE THREAD

**Issue by dasMol3** [ModOrganizer2/modorganizer#825]
## The problem:
When I try to load MO2 it only shows the MO2 loading screen and a notification that it is "validating nexus connection" but then that goes away and nothing ever loads. The app says it is running if I try to launch it again and indicates its open but it wont appear on my screen. Current game it was modding was Skyrim SE. It had been working fine a few hours earlier and I had not made any changes since I had last used it.

* Mod Organizer Version that exhibits the issue: 2.2.1
* Desktop OS/version used to run Mod Organizer: Windows 10

### USVFS:
18:23:44.714 [I] usvfs dll 0.4.4.0 initialized in process 12800
18:23:44.715 [D] remove from process 12800
18:23:44.715 [I] create config in 12800
18:23:44.715 [I] 0 processes - 1
18:23:44.715 [I] mod_organizer_instance_1 created in process 12800
18:23:44.715 [I] attached to mod_organizer_instance_1 with 1 nodes, size 65536
18:23:44.715 [I] inv_mod_organizer_instance_1 created in process 12800
18:23:44.715 [I] attached to inv_mod_organizer_instance_1 with 1 nodes, size 65536
18:23:44.715 [D] context current shm: mod_organizer_instance (now 2 connections)### MO

**Comment by LostDragonist** [comment]
Try to select the program in the taskbar.  Then press Alt+Space.  Then press M.  Then press the left or right arrow.  The program should magically appear.

**Comment by dasMol3** [comment]
> Try to select the program in the taskbar. Then press Alt+Space. Then press M. Then press the left or right arrow. The program should magically appear.

Thank you for the black magic! Worked like a charm.

**Comment by LostDragonist** [comment]
@Silarn The best guess at this point is that it's another oddity related to saving and restoring the window geometry.  It feels like the window is on "another monitor" but that "monitor" doesn't exist so the normal methods of trying to move a window don't work.  

I think @isanae was working on a different way of saving the geometry that would probably help with this issue.

**Comment by Silarn** [comment]
Well, in the latest version with the newest Qt, I did some refactoring which was forced to include additional handling for how MO2 selects a screen to display on. Could be this might also help in this case.
