### ISSUE TITLE
Can not start BodySlide in MO

### ISSUE THREAD

**Issue by zhanghua000** [ModOrganizer2/modorganizer#826]
## The problem:
When I start BodySlide in MO, it shows me an error: "Failed to load Setup.xrc file", However, this file exists and if I start BodySlide directly in Windows Explorer, BodySlide works well.

## To Reproduce:
Just start BodySlide  by executing the executable file created by MO.
## Environment:
Game: Fallout 4
MO version: 2.2.1.0
OS version: Windows 10 18362.295

## Details:
When start BodySlide in MO, it shows an error:"Failed to load Setup.xrc file", but Setup.xrc file exisis. If I start it manually in Windows Explorer, I can start BodySlide normally. I have reinstalled MO, it doesn't work.

### USVFS:
Logs are here:
https://gist.github.com/zhanghua000/35382f750659b075cc75f801bc64084f
### MO Interface:
Logs are here:
https://gist.github.com/zhanghua000/d160c9597a17a4702b2828f82fca7d77

**Comment by LostDragonist** [comment]
Can you go to Settings > Diagnostics and set the Log Level to Debug?  Then restart MO, run Bodyslide, and update the USVFS log.

**Comment by zhanghua000** [comment]
The new USVFS log is here:
https://gist.github.com/zhanghua000/33b667ed10c857f22c5beb62a1137c4c

**Comment by LostDragonist** [comment]
>C:\Program Files\MacType

MacType is a pretty invasive program and screws up a lot of things.  They have to build in specific code in order to not break programs like MO2.  The only suggestions I can give are to get them to fix it or to uninstall the program.

**Comment by zhanghua000** [comment]
@LostDragonist That's works. Thank you very much for your help.
