### ISSUE TITLE
[Bug] API Request Counter shown on start when set to hide

### ISSUE THREAD

**Issue by yoyokenny** [ModOrganizer2/modorganizer#828]
## The problem:
When the "Hide API Request Counter" setting is enabled, the counter is displayed after closing and restarting Mod Organizer.

## To Reproduce:

1. Go to 'Settings > Nexus'
2. Check 'Hide API Request Counter'

## Environment:

* Mod Organizer Version that exhibits the issue: v2.2.1
* Desktop OS/version used to run Mod Organizer: Windows 7 Pro x64

### MO Interface:
[mo_interface.log](https://gist.github.com/yoyokenny/149fe89825314e04e99350f33a6b23f9)

## Notes:
Setting is still set (log shows it being loaded), but doesn't seem to be applied on start.

**Comment by isanae** [comment]
That's my fault, I'll fix it.
