### ISSUE TITLE
',' (comma) symbol in notes text of meta.ini of mod

### ISSUE THREAD

**Issue by TokcDK** [ModOrganizer2/modorganizer#829]
## The problem:
Noticed notes in meta.ini not working when ',' (comma) symbol there

## To Reproduce:
Open meta.ini of mod and add something like Word1**,** word2. where will be atleast one ','.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): ?
* Desktop OS/version used to run Mod Organizer: W7

## Details:
Note icon and text will not be displayed in flags tab of mod if atleast one **,** was added after **notes=** .

### MO Interface:

**Comment by LostDragonist** [comment]
It works for me as long as I put the string in quotes.  

`notes="alpha, bravo, charlie"` is a valid setting.
`notes=alpha, bravo, charlie` is not a valid setting.

**Comment by LostDragonist** [comment]
Huh, okay, that was actually the comment field.  The notes field turns into this:

`notes="<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">alpha, bravo, charlie</p></body></html>"`

Which basically means... don't manually edit the notes field.

**Comment by TokcDK** [comment]
Yeah, edited meta.ini manually not from properties.. Thanks.
