### ISSUE TITLE
Update to MO2 , run fnis and bodyslide crashed

### ISSUE THREAD

**Issue by magicdmer** [ModOrganizer2/modorganizer#832]
## The problem:
Update MO1 to MO2 , run fnis and bodyslide crashed , the operation bellow (gif) :
https://imgur.com/CRstm5r

## Environment:

* Mod Organizer Version :  2.2.1
* Desktop OS/version used to run Mod Organizer:  windows 7 x64

### USVFS:
https://gist.github.com/magicdmer/0fd9d1a1b5c17a030d8d4265aa2c7b7f

### MO Interface:
https://gist.github.com/magicdmer/cd6c29be86ff021928157eb30168c884

**Comment by LostDragonist** [comment]
My first guess is that it's related to the MacType program.  We've seen many cases where MacType interferes with programs like Bodyslide and causes issues.

**Comment by magicdmer** [comment]
> My first guess is that it's related to the MacType program. We've seen many cases where MacType interferes with programs like Bodyslide and causes issues.
You're right. after disableing it, everything goes back to normal. 
Mactype caused a lot of strange problem before, and I should have doubted it first, but I forgot.
