### ISSUE TITLE
Lost my Mod Organizer configuration after reinstalling Windows.

### ISSUE THREAD

**Issue by lolcocks123** [ModOrganizer2/modorganizer#833]
Currently, my Mod Organizer resides in "E:\Games\Mod Organizer" and it was linked to my Skyrim in "E:\Games\Skyrim - Legendary Edition" 

I formatted and reinstalled Windows about two months ago and now when I launch Mod Organizer I am showed a "Choose Instance" menu.

Is my entire configuration lost? Was it stored in the "My Documents" folder or the Skyrim folder? Is there a way to check and if possible, get it back?

**Comment by Yoosk** [comment]
It was stored in neither of those. It is user specific and resides under: `%userprofile%\AppData\Local\ModOrganizer`
Doubt you can get it back unless you have backup.

**Comment by Al12rs** [comment]
If you had everything on the default paths I'm afraid tyou lost it, if you had moved stuff to different folders then you can point Mo2 to those folders and it will pick things up.
