### ISSUE TITLE
Oblivion crashes immediately (GOG, OBSE)

### ISSUE THREAD

**Issue by 07416** [ModOrganizer2/modorganizer#840]
## The problem:
Oblivion crashes immediately when launched via Mod Organizer 2. I've followed [the instructions in the wiki](https://github.com/ModOrganizer2/modorganizer/wiki/Running-Oblivion-OBSE-with-MO2).

## To Reproduce:

N/A

## Environment:

* Mod Organizer Version that exhibits the issue: v2.2.1
* Last Mod Organizer Version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 10 64-bit

## Details:

OBSE v0021 ~~with the GOG loader~~. GOG version of Oblivion (1.2.0416 CS)

All mods disabled in MO2. **I can launch the game directly** from Oblivion.exe and also obse_loader.exe (when added to the folder).

### USVFS:

https://gist.github.com/07416/c8d75c51228c6062b6e0f6d92c7ab163

### MO Interface:

https://gist.github.com/07416/16a754487dc99362ab23ea198da133ae

**Comment by Al12rs** [comment]
You should not be using the gog loaded. You have to follow those instructions to the letter and they say you don't need any loader. Make sure your setup is correct and disable all the mods that could be causing the crash.
If that still does crash then disable the library loading and see if oblivion is starting correctly without it loading OBSE.

**Comment by 07416** [comment]
@Al12rs Sorry, I don't have the OBSE loader stored in the game folder, I mentioned it by accident. I have also disabled all mods in MO2.

Disabling library loading doesn't resolve the issue. I can launch directly from Oblivion.exe and also obse_loader.exe (when adding to the folder).

**Comment by Al12rs** [comment]
So it still crashes with library loading disabled?

**Comment by 07416** [comment]
> 
> 
> So it still crashes with library loading disabled?

Yes.

**Comment by Al12rs** [comment]
Then this is most likely something wrong in your INI files.
Try this:

To check whether the issue is related to one of the mods installed or your ini settings, see if it keeps happening in a new empty profile:
https://cdn.discordapp.com/attachments/403979692501106688/524939782435110924/unknown.png
https://cdn.discordapp.com/attachments/403979692501106688/524940397643038740/unknown.png

Also make sure you don't have any mods installed in actual game folder, and test if the issue happens outside of Mo2 if you didn't already.

**Comment by 07416** [comment]
This issue was indeed causes by the MO's INI files, which I have slightly modified.
[oblivion.ini for reference](https://gist.github.com/07416/3a7411e7e77ff593617e73658227a5f0)

Initially I had an issue with MO not using the profile-specific INI files, I then started modifying Oblivion.ini in the game directory — I hope that this bug can be tracked down.
