### ISSUE TITLE
MD5 calculation incorrect when querying info

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#843]
## The problem:
When querying info for Skyrim Realistic Overhaul, Part 1 (Skyrim_Realistic_Overhaul_Part_1.7z), the MD5 is calculated as d41d8cd98f00b204e9800998ecf8427e (hash 1).  fciv calculates the MD5 as a87d624bf831b3382d5f70588d8c1adc (hash 2). 

Hash 2 correctly returns no results for the file on SkyrimSE and Skyrim.  This is expected because the file is not present on the Nexus.

Hash 1 returns results for a lot of Skyrim mods, ultimately picking the Russian version of [Skyrim Unbound Reborn](https://www.nexusmods.com/skyrim/mods/98850), version 1.1.3.  

Bonus points if the functionality is improved to allow the user to correct this issue somehow.  Hash 1 is a very good test case for an MD5 collision as *so many* mods seem to result in that hash.  

## To Reproduce:

Download [Skyrim Realistic Overhaul, Part 1](https://www.moddb.com/mods/skyrim-realistic-overhaul/downloads/skyrim-realistic-overhaul-part-1) and place it into the MO downloads folder.  Right-click and query info.  Hover the mouse over the download and observe the incorrect info attached to the download.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer:  windows: version: 10.0.18362, 18362.356, release 1903, 18362.1.amd64fre.19h1_release.190318-1202, Windows 10 Home, elevated: no

**Comment by LostDragonist** [comment]
7-zip hashes of the downloaded file in case it matters at some point.

![image](https://user-images.githubusercontent.com/7862539/65812763-8aff3780-e191-11e9-9f11-14c1f7d16c15.png)

**Comment by LostDragonist** [comment]
Okay.  Apparently hash 1 (d41d8cd98f00b204e9800998ecf8427e) is the hash of an empty zip file.  Which helps explain why so many mods have the same file hash.

**Comment by Al12rs** [comment]
Noghty... #770

**Comment by LostDragonist** [comment]
/facepalm.  Thanks, Al.
