### ISSUE TITLE
OMOD support

### ISSUE THREAD

**Issue by erri120** [ModOrganizer2/modorganizer#848]
_We already talked about this in the `#dev-discussions` channel and this is just for centralizing this request._

The Oblivion Mod Manager aka OBMM is old. Since OBMM introduced `.omod` files, it has been the only problem when modding Oblivion. In the moddern Oblivion modding scene you would use MO2 for everything except like 2 mods which you would have to install using OBMM. 

My [OMOD-Framework](https://github.com/erri120/OMOD-Framework), written in C#, is a framework for extracting OMODs and executing the installation script.
The C# example is [here](https://github.com/erri120/OMOD-Framework/tree/master/OMOD-Framework-Example) and the C++/CLI one is [here](https://github.com/erri120/OMOD-Framework/tree/master/OMOD-Framework.CLR-Example).
Do note that the C++/CLI example is 'the same' as the C# one and not tested.

Since my C++ is a bit ... _mega bad_ and I'm too high level programming oriented to comprehend and work with CMake, I'm very reluctant about writing the installer plugin for this.
What I am able to do is change the Framework if the need arises and answer questions about implementation. The examples and the framework are also fully documented (public functions at least).

Things we would need in the installer plugin:

- UI:
  - Yes-No Dialog
  - Input Dialog (just string input that maybe has some initial contents)
  - Item-Select Dialog with each item having a possible image and a description
  - Warn Popup if desired (should be active for debugging)
  - Messagebox (or not, not really used that much)
  - Displays for Image and Text (yes, Displaying Text is the same as using a message box. I also dont know why there are seperate functions for this)
- Functions:
  - ExistsFile (relative to the oblivion game folder)
  - GetFileVersion (relative to the oblivion game folder)
  - GetActiveESPNames (list of all plugin names, can be active or not idc, WITHOUT extensions `.esp` or `.esm`)
  - GetFileFromPath (check the documentation for this one in the examples)

**Comment by ravensm** [comment]
any updates on this? would love to remove the need for the old oblivion managers

**Comment by erri120** [comment]
I've updated my [OMODFramework](https://github.com/erri120/OMODFramework) to 2.0.0. New release split the Scripting from the main project so you now have `OMODFramework` (.NET Standard 2.0) and `OMODFramework.Scripting` (.NET Framework 4.8).

**Comment by ravensm** [comment]
so i tried 2.0. mo2 (v2.2.2.1) fails to load plugin. it says it cant extract the meta data from the dll. what i did was just drop it into the plugins folder. am i doing something wrong? i tried both

**Comment by AnyOldName3** [comment]
What DLL? The only OMOD installer DLLs for MO2 in existence are on my computer, and they barely work.

**Comment by ravensm** [comment]
https://github.com/erri120/OMODFramework/releases

**Comment by Qudix** [comment]
That's not an MO2 plugin. There is no OMOD support plugin for public use yet.

**Comment by ravensm** [comment]
at the top of this page, its listen for mo2, so unless the creator steps in, i would have to disagree with you

**Comment by AnyOldName3** [comment]
Which creator? Everyone who's created anything relevant has already told you you're wrong.

This is an issue for MO2 on the MO2 repo, saying it's not got an OMOD installer yet. You've downloaded a DLL from another repo (that mentions that MO2 can run Oblivion and OBSE now, but also that it's incapable of installing OMODs), put it in your MO2 plugins directory for some reason, then posted on MO2's page about the DLL from another project not magically making MO2 able to do something that several pages you must have looked at have said is impossible right now.

A reasonable analogy for what you've done would be putting a pan in your car and complaining to Ford that it hasn't started making you pasta.

**Comment by erri120** [comment]
> 
> 
> at the top of this page, its listen for mo2, so unless the creator steps in, i would have to disagree with you

How about the creator steps in and tells you that the OMODFramework is a .NET library for working with omod files as stated on the GitHub page and not a C++/Python plugin for MO2.

**Comment by Holt59** [comment]
The plugin is now available at https://github.com/modorganizer2/modorganizer-installer_omod and is already included in the latest dev-builds. It will be included in the next MO2 release (2.4).
