### ISSUE TITLE
Uninstalling MO prompts to delete user data but doesn't give a "no" option

### ISSUE THREAD

**Issue by Freso** [Modorganizer2/modorganizer#86]
At some point during uninstalling Mod Organizer it asks whether you also want to remove (what I assume is) `%LocalAppData%/ModOrganizer`. The only button on this dialog is an "OK" one. I would expect something like a "Yes"/"No" option.

Screenshot: https://i.imgur.com/TaPvvCU.png

**Comment by LePresidente** [comment]
I have zero time to work on this, was going to migrate the installer to WIX though life has caught up with me.

so unless others take this over, doubt there will be any movement on this

https://github.com/TanninOne/modorganizer-umbrella/issues/37

**Comment by LePresidente** [comment]
Fixed in 2.1.2
