### ISSUE TITLE
PY module creating an error due to module syntax <!DOCTYPE html>

### ISSUE THREAD

**Issue by bladeraptor** [ModOrganizer2/modorganizer#865]
## The problem:
Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our [discord channel](https://discord.gg/5tCqt6V)

This relates to the pySyncModOrder.py found at https://github.com/deorder/mo2-plugins 

When launching Mod Organizer 2 having installed a couple of plugins as suggested by this Fallout New Vegas run through https://vivanewvegas.github.io/prerequisites.html, I get the following dialogue box error (see enclosed screenshot) relating to pySyncModOrder.py

Mod Organizer version 2.2.1 Revision e69078e
System Windows 10

![mod organizer 2 issue](https://user-images.githubusercontent.com/8452443/66477779-c8689c80-ea90-11e9-957f-2bb47c4551a6.JPG)

## To Reproduce:

1. Go to '...' Install the pySyncModOrder.py plugin from the location above and launch Mod Organiser on a Windows 10 machine

## Environment:

* Mod Organizer Version that exhibits the issue:

Mod Organizer version 2.2.1 Revision e69078e

* Last Mod Organizer Verison that did not exhibit the issue (if applicable):

N/A

* Desktop OS/version used to run Mod Organizer:

Windows 10 ver 1903 build 18362.388

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

This relates to the pySyncModOrder.py found at https://github.com/deorder/mo2-plugins 

When launching Mod Organizer 2 having installed a couple of plugins as suggested by this Fallout New Vegas run through https://vivanewvegas.github.io/prerequisites.html, I get the following dialogue box error (see enclosed screenshot) relating to pySyncModOrder.py

Mod Organizer version 2.2.1 Revision e69078e
System Windows 10

## Link to Mod Organizer logs:
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed.

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

<script src="https://gist.github.com/bladeraptor/e125debebf13d535788926e03df2a8c1.js"></script>

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

 <script src="https://gist.github.com/bladeraptor/e28166c47eeffcdd65c0aeaefc7a8dc9.js"></script>

**Comment by LostDragonist** [comment]
It looks like you saved the HTML file of the python script instead of the python script.  Though you really need the entire repo as a single file is not going to work so well.  You'll want to use the download zip button to get the repo contents.

![image](https://user-images.githubusercontent.com/7862539/66478616-655f1180-ea60-11e9-84a4-f3f01a1935bf.png)

**Comment by bladeraptor** [comment]
@LostDragonist - thanks so much for the speedy reply

The challenge is that is exactly what I did - downloaded the zip and extracted - the issues seems to be the same - see screengrabs 

![Mod Org zip](https://user-images.githubusercontent.com/8452443/66484434-e3420d80-ea9e-11e9-863f-8bb391e56990.JPG)

And 

![Mod Org zip 2](https://user-images.githubusercontent.com/8452443/66484452-ea691b80-ea9e-11e9-957a-06df24d1cbf9.JPG)

So maybe the format of the .py was pulled into the zip incorrectly as well?

**Comment by LostDragonist** [comment]
According to your log, you have both a pySyncModOrder.py (right) and a syncModOrder.py (wrong) in the plugins folder of the MO2 install.  

I guess start off by deleting syncModOrder.py.  When it's installed properly, that file should be buried in the plugins\data folder.

**Comment by LostDragonist** [comment]
Judging by the thumbs up, I'm guessing this issue is resolved and I'll be closing it.  If you still have problems, please feel free to reopen the issue with new info.
