### ISSUE TITLE
Better handling of improperly packaged FOMODS

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#880]
Weapons of the New Millenia v1.1.a (https://www.nexusmods.com/newvegas/mods/55008) is packaged such that MO can't recognize it as a valid FOMOD.  Currently (2.2.2alpha4), the manual install dialog pops up and has the user fix it and there is no way to run the FOMOD afterwards.

A couple possibilities come to mind:

1.  Recurse through the file tree looking for a valid fomod folder.  Automatically move that folder and its siblings up to the top level of the mod and then run the FOMOD installer.

2.  Figure out how to run a FOMOD installer after fixing stuff in the manual install dialog.  Perhaps a dialog can pop up saying "This looks like a FOMOD archive.  Would you like to install it as a FOMOD mod?"

Apparently this kind of file worked back in the MO1 days so it'd be nice to get it working again.

**Comment by Holt59** [comment]
This is half-fixed by the FOMOD C# installer:
- The FOMOD C# installer recognize the mod correctly and thus can install it.
- The NCC installer still does not work for this mod.
