### ISSUE TITLE
Issue with missing drive & data paths

### ISSUE THREAD

**Issue by ElementalSon** [ModOrganizer2/modorganizer#881]
History: I was installing some software (Mod Organizer 2) on my external hard-drive two days ago, as per the official video installation instructions. During this installation, I accidentally knocked the cable out of my external harddrive. Since this time, I have not been able to get my external harddrive to be read by any computer, nor can I get a fresh install of MO2 to start.

Issue: When attempting to launch the MO2 installer, I get two errors: 
1. 
![image](https://user-images.githubusercontent.com/45890265/67394859-a45c9d80-f5f0-11e9-877e-64dfc83bd898.png)

2. 
![image](https://user-images.githubusercontent.com/45890265/67394901-b5a5aa00-f5f0-11e9-8de5-16e39bd0f5c6.png)

I have looked for the .ini file for MO2, and cannot find an instance of it, as I no longer have a functioning E/ drive to search. Additionally, external harddrive is not readable, despite blue light appearing when first plugged in (for approximately four seconds) Also no longer plays the audio cue for 'new USB device detected', nor 'USB device removed' if taken out. All USB ports tried have been confirmed to work immediately with other plug and play hardware (mouse, thumbdrive, etc.) 

Attempted fixes: 
- Running MO2 setup as admin.
- Different USB port
- Different cable
- Restarting laptop with external hard drive plugged in. 
- Restarting laptop with external hard drive unplugged.
 -Checking the Windows Device Manager (compmgmt.msc) - device is not recognised, nor is there any indication of an unknown device present. Not under any sub menu. No yellow exclamation marks. 
- Asking rubber duck sensei for aid. 
- Fresh download of MO2 archive.
- Giving in and contacting you guys. 

Would super appreciate any advice re either MO2 or the EXT HD. My cat passed away this morning, and I'm really hoping I can access some photos of her I have on this thing (I've also contacted the manufacturer). Any help greatly appreciated.

**Comment by Silarn** [comment]
This doesn't particularly sound like an MO2 issue, I'm sorry to say. Disconnecting actively running drives is generally a bad idea.

It sounds like this is a hard drive enclosure and not just a flash stick or something. You can always hope that you managed to just damage the enclosure/USB interface and not the drive itself.

Usually you can open those up to get out the actual hard drive and connect it directly to standard SATA or a new enclosure. It's worth a shot before taking it to a shop.

**Comment by Silarn** [comment]
As far as running MO2 on your good drives, there are really only two locations that global config file would be and if you happened to configure your data paths to the failing drive that could cause issues when starting. In fact we might want to have MO2 check on the existence of said paths to avoid possible crashes like this.

Hopefully you know if you were running as an instance or portable install. A portable install will set up the modorganizer.ini inside the install directory while instances use a file I'm your user directory's AppData\Local\ModOrganizer directory which is hidden by default in Windows.

As this was a new install, I would just delete the file and run MO2 fresh.

**Comment by ElementalSon** [comment]
Thank you very much, Silarn - deleting the MOD2 files in AppData did the trick - was able to reinstall and set up MO2 as per the instruction video. 

The EXT.HD still isn't alive, but it's not quite dead either - I plug it into a USB port and its light comes on for a few seconds and I can hear it boot. I'm not going to take it apart until I hear back from the manufacturer as it's still under warranty, so we'll see what they suggest.
