### ISSUE TITLE
F4SE crash when launched from MO2

### ISSUE THREAD

**Issue by Laydralae** [ModOrganizer2/modorganizer#883]
## The problem:
I am having an issue identical to the issue described in issue #675. However, following the steps given by LostDragonist did not resolve my issue. 

## To Reproduce:

1. Launch F4SE in MO2 with mods enabled results in crash.
2. Launch F4SE in MO2 without mods enabled results in crash.
3. Launch FO4 in MO2 with mods enabled does not result in crash.
4. Launch FO4 in MO2 without mods enabled does not result in crash.
5. Launch F4SE outside of MO2 does not result in crash.
6. Launch FO4 from Steam does not result in crash.
7. Launch F4SE from Steam (using add a non steam game) does not result in crash.

## Environment:

* MO2 v2.2.1
* Fallout 4 v1.10.138
* F4SE v0.6.7
* Windows 10 Home x64 v1903 Build 18362.418

## Details:
This is a fresh install of both Fallout 4 and F4SE, never before installed on this machine. On a whim I tried launching Skyrim SE through SKSE on MO2 and it worked fine. I tried setting the load mechanism to "Script Extender" and it still crashed. 

### USVFS:
https://gist.github.com/Laydralae/91eb67602aa3a8743aa7a9e3cf32f486

### MO Interface:
https://gist.github.com/Laydralae/1e111d76ba49a041538930ef224dcbbd

**Comment by Al12rs** [comment]
Setting load mechanism to script extender is wrong. Set it back to Modorganizer.
Can you confirm that the issue persists with F4SE if the mechanism is Modorganizer and you are using a new empty profile? Please make sure you are using a new profile not just disabling the mods.

**Comment by Laydralae** [comment]
I had it on Mord Organizer originally, I was changing settings to see if they had any effect. I created multiple new profiles, switching to them didn't appear to change anything and still causes the game to crash. Do you mean when I create a new profile it's supposed to clear my mod list or no?

**Comment by Al12rs** [comment]
The new profile also has clean ini files which can cause issues. I have also seen users telling me they had all the mods disabled when they were actually only disabling the plugins and not the mods themselves. 
Did you install the scripts part of F4SE through MO2 by any chance?

**Comment by Laydralae** [comment]
I did not do the scripts part, I'm was unaware there was a difference and am unaware how to do that,

All the items in the left box are unchecked, the only items in the right box are the ESM files for the game and its DLCs.

**Comment by Laydralae** [comment]
I installed F4SE the way I did with Skyrim and SE, and had no problems there. If there is a different way to install them for FO4 then thats probably my issue.

**Comment by Al12rs** [comment]
If you just instaled F4SE in the game folder that is fine.
Follow the instructions to get some debug level logs:
Upload your log files here. Follow these steps:

1) Go in the Settings, Diagnostics tab, set Log Level to Debug.
2) Restart MO.
3) Recreate your problem.
4) You can use the "Open Folders" button to open the logs folder.
5) Close MO.

Drag and drop mo_interface.log here. It might need to be compressed. Also upload the most recent usvfs log.
https://cdn.discordapp.com/attachments/458597400638914563/617049541350260794/openlogs.png

**Comment by Laydralae** [comment]
[usvfs-2019-10-28_07-51-03.log](https://github.com/ModOrganizer2/modorganizer/files/3777646/usvfs-2019-10-28_07-51-03.log)

**Comment by Laydralae** [comment]
[usvfs-2019-10-28_07-51-03.log](https://github.com/ModOrganizer2/modorganizer/files/3777647/usvfs-2019-10-28_07-51-03.log)

**Comment by Al12rs** [comment]
Some people like to install the scripts part of SKSE in MO2 since those go in the data folder, to keep it clean. I just wanted to make sure you didn't have to enable that to get it working. But if you just installed all of F4SE directy in the game folder then that is not the problem

**Comment by Laydralae** [comment]
![Fallout 4 01](https://user-images.githubusercontent.com/10361421/67661160-bc4c5e00-f91d-11e9-8b04-a8d76d7a1c6a.PNG)
![Fallout 4 02](https://user-images.githubusercontent.com/10361421/67661163-bd7d8b00-f91d-11e9-9e61-95478b040100.PNG)
![Fallout 4 03](https://user-images.githubusercontent.com/10361421/67661167-bf474e80-f91d-11e9-99b6-ce54da2a94c2.PNG)

**Comment by Al12rs** [comment]
Could you upload your interface.log please? You seem to have some weird paths going on

**Comment by Laydralae** [comment]
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/3777658/mo_interface.log)

**Comment by Laydralae** [comment]
This is how I told it to be set up.

![Fallout 4 04](https://user-images.githubusercontent.com/10361421/67661327-2bc24d80-f91e-11e9-8682-95fb58591e3f.PNG)

**Comment by Al12rs** [comment]
What about the F4SE executable?

**Comment by Laydralae** [comment]
![Fallout 4 04](https://user-images.githubusercontent.com/10361421/67661441-7b087e00-f91e-11e9-8877-128efba8be42.PNG)

**Comment by Laydralae** [comment]
![Fallout 4 05](https://user-images.githubusercontent.com/10361421/67661456-82c82280-f91e-11e9-85d1-06195be52ea3.PNG)

**Comment by Laydralae** [comment]
Wait, oh I think I see it. Its the start in being wrong isn't it?

**Comment by Al12rs** [comment]
Remove the start in line, it seems it's wrong for some reason.

**Comment by Laydralae** [comment]
Okay yep that was the issue. Wow I feel embarrassed. Thanks for helping me with this issue!

**Comment by Al12rs** [comment]
No, problem. Do you know if you messed with it at some point? Otherwise it might be Mo2's fault for setting it up wrong

**Comment by Laydralae** [comment]
I'm pretty sure I mistyped it because I created the executable myself.

**Comment by Al12rs** [comment]
Good to know, thank you.
