### ISSUE TITLE
Mod Installation - Install To Mod Option / Name Auto-Completion

### ISSUE THREAD

**Issue by Dakraid** [ModOrganizer2/modorganizer#886]
Being able to either select already installed mods or have some kind of suggestion when installing mods and naming them would be a nice feature to have.

**Scenario:**
Let's say I have a mod installed with a different name than MO2 would have used and want to install an update to it. By default MO2 would resort to the archive name or whatever meta information it has.
Right now if I want to install to that specially named mod, I have to copy and paste the name beforehand. 

**Request:**
Have a button next to the naming field, that directly that allows me to select an "Install Location" similar to the "Move Overwrite to Mod..." context menu.

Alternatively, the possibility to just start typing the first letters and MO2 gives me a suggestion based on my installed mods through the drop down menu.

**Comment by Silarn** [comment]
If you have a Nexus ID associated with your downloads and mods, it should attempt to locate and suggest mods with the same Nexus mod ID. Those options should be prepopulated in the drop-down.

However, adding an autocomplete based on input is possible.

**Comment by Dakraid** [comment]
This is also for mods that do not offer mod manager downloads and instead rely on archive installation, since not all Nexusmods pages offer mod manager downloads and especially other sources do not offer this option at all.

**Comment by Al12rs** [comment]
Discussion should be continued here: #742 #1031
