### ISSUE TITLE
External tools can't find data directory.

### ISSUE THREAD

**Issue by DaemonPhenex** [ModOrganizer2/modorganizer#888]
## The problem:
I can get the game to run with mods enabled without an issue...
though when I click "Explore Virtual Folder" it is supposed to bring me to the games data directory.
this does not seem to work and even extends to LOOT which is also unable to locate the data directory.

## To Reproduce:
I honestly don't know how I got here. I've uninstalled and reinstalled multiple times.
Both applications are being run through Mod Organizer and don't have issue locating the data folder when ran outside of Mod Organizer.

## Environment:
Mod Organizer Version 2.2.1
Windows 10 1909 ( OS Build 18363.356 )

### Mods enabled
![EnabledMods](https://user-images.githubusercontent.com/36192863/68361828-1ac1cb00-00da-11ea-9e37-796fbdceb7ed.jpg)

### Data directory exists in Explorer.exe
![ExistingDirectories](https://user-images.githubusercontent.com/36192863/68361849-28775080-00da-11ea-8d56-c4919cabc456.jpg)

### Data directory DOES NOT exists in Explorer++.exe
![VirtualFolder](https://user-images.githubusercontent.com/36192863/68361869-3d53e400-00da-11ea-8f4c-a4a23a7de801.jpg)

### LOOT concures that the data directory DOES NOT exist
![moloot](https://user-images.githubusercontent.com/36192863/68361890-50ff4a80-00da-11ea-8de0-b7d787f225aa.jpg)

LOOTDebugLog:
`
[21:06:21.548760] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[21:06:23.020914] [error]: Exception while executing query: directory_iterator::directory_iterator: The system cannot find the path specified.
: "G:\Game Files\Non-Steam\The Elder Scrolls V Skyrim Special Edition\Data"
[21:06:23.026868] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5757: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5757:9194)
`

---

### USVFS:
https://pastebin.com/tM8FQ8uV

### MO Interface:
https://pastebin.com/RubkmYL4

Log output after opening MO2, attempting to launch LOOT and failing to find data directory.
and then launching the game executable with not issues. All mods seems to be working due to manually load order.

**Comment by LostDragonist** [comment]
Please grab some debug logs of the issue.

1.  Go to settings > diagnostics.
2.  Set the log level to debug.
3.  Click OK.  Say no to restarting MO.
4.  Restart MO manually.
5.  Launch a tool or the game.
6.  Close the tool or the game.
7.  Grab new log and upload them (mo_interface.log and usvfs_xxx.log).

**Comment by DaemonPhenex** [comment]
### mo_interface.log
https://pastebin.com/MzWtFfSp

### usvfs_xxx.log
https://pastebin.com/W9xNLZZP

**Comment by DaemonPhenex** [comment]
I was thinking maybe it was a bad path string in the config but the data folder didn't exist when manually navigating to the data directory from "Virtual Explorer".

Just deleting my profiles in $LocalAppdata\ModOrganizer\ and rebuilding them managed to work. 
Thanks for the time.
