### ISSUE TITLE
an error occurred: failed to open temporary file

### ISSUE THREAD

**Issue by madzumi** [ModOrganizer2/modorganizer#889]
Task:
 uncaught exception in handler (object , eventtype 43): failed to open temporary file

Corrupt Mod Organizer 2 files.  

I reinstalled MO2 with the same error persisting.  

Without reinstalling FO4, what are the options to fix this problem?  I double checked the Temp directory the AppData directory and it is updated, but the plugin cannot be saved.  What are my options to fix this problem?

**Comment by LostDragonist** [comment]
When is this error happening?  Is this an MO error or an error of a program or tool you're running through MO?  Is your C:\ drive full or nearly full?

**Comment by madzumi** [comment]
The error started after I abruptly closed FO4 down from task manager due to a freeze.  

This is a MO error.  MO is installed on a different drive (same drive as my FO4), not the C drive which is not full.  The error is related to "failed to write mod list: failed to open temporary file" when starting the program.  The error message is consistent while opening MO and exiting.    

I cannot save backup my plugin mod order.  (clicking Create Backup icon in right Plugins tab)

![MO2_error](https://user-images.githubusercontent.com/34282828/68546755-46250e00-0397-11ea-90c9-24de1472757e.png)

**Comment by LostDragonist** [comment]
My only guess as a quick fix right now would be to clear your temporary files out.  

1. Open up Windows Explorer.  
2. Go to the address bar.  
3.  Put in "%TEMP%" and hit enter.  
4. Ctrl-A to select everything.  
5. Delete.  
6.  Skip everything that you can't delete.  
7.  Do the same for the "%TMP%" folder (which is normally the same folder but might as well cover all bases).  
 8.  Restart your PC.
9. Try MO again.

If that doesn't work, please post your mo_interface.log file. It can hopefully be found in the MO logs folder here: https://cdn.discordapp.com/attachments/458597400638914563/617049541350260794/openlogs.png

**Comment by madzumi** [comment]
The quick fix appears to have worked.  I hope this is a more permanent solution and the issue does not reoccur.  

Thank you.

**Comment by isanae** [comment]
We've added some more logging to try to understand the problem in the future, but right now it doesn't look like an issue with MO. Closing for now.
