### ISSUE TITLE
A (Possibly?) simple, logical extention to the Separator system

### ISSUE THREAD

**Issue by Ratione** [ModOrganizer2/modorganizer#892]
### **Is your feature request related to a problem?**

Yes. Kindof. I am one of *those* modders. I have probably spent more time modding Skyrim et al. than I have actually playing them, and I have several thousand hours playing them. I compile massive, unholy collections of mods that I then spend countless hours meticulously xEdit'ing into submission. My record for Skyrim was over a thousand plugin-containing mods, merged into something approximating a playable game. Falkreathe sat at like 15fps for some reason I never figured out, but it was otherwise totally playable. 

Point is, I have a *lot* of mods. The only reason I am able to get away with that is through careful categorization and sorting. The separator system is a godsend, and way better than the hack I was using before that was implemented, but it leaves some things to be desired. 

Specifically, while it mostly solves the "readability" problem, I am still left with a list of 86 thousand files that I have to scroll through every time I want to add a file, or move one to a new location. To get around this I currently use separators as a break in between categories of mods i.e.

> ...

> * Not Skimpy Armor Mod
> * Also not Skimpy Armor Mod
>> **--------------CHEESE OVERHAUL--------------**
> * Cows produce milk
> * Cheese Economy

> ...

Like everyone else does. In this way, I am using the separator system like a File System. There are categories which are basically black boxes, or "Folders" until something goes wrong, and I have to actually open one to see whats going on. Many times the majority of plugins in a given section have been merged together, and those mod files are only there to provide textures/meshes for the larger merged plugins, or somesuch. And thats actually a pretty good system. Spoiler alert, Mod Organizer is pretty neat, which is why we all use it, instead of Vortex or (*snicker*) NMM. The Problem arises when you are dealing with an large, some would say, "unreasonable" modlist. When I have approaching two thousand mods, the vast majority of which are kilobytes in size, changing one or two textures or meshes.

The "Problem" is that I have too many damn mods to sort through, but because this is the Internet, that is somehow your fault.

### **Describe the solution you'd like**

I want a "Fold" function. 

You know, like the little arrow that hides all the files in a folder in your file explorer's "Tree" view.

It doesn't have to be 'complicated'. I don't need a nested, full-blown actual file system, I just think that separators already exist, and are already distinguished by the program. A logical extension of that would be a purely visual, non-nesting "Collapse" feature. It would take everything between the current separator and the next separator/end-of-list and hide it until toggled again. Let me reiterate, that would be a purely visual change to reduce clutter. Nesting would be super nice, but totally out of the scope of the initial feature request. 

Now, just to make sure this horse is really good and dead, my previous example might look like this after the "Cheese Overhaul" section was collapsed. 

> ...

> * Not Skimpy Armor Mod
> * Also not Skimpy Armor Mod
>> **--------------CHEESE OVERHAUL--------------** ^
>> **--------------SOCK MAKING OVERHAUL--------------** ╧
> * Actual Knitting - Keep your Feet Warm
> * Shear your own Sheep - Now with Sheep v.098

> ...

### **Why is this a simple solution?**
This is a simple solution because the basic infrastructure is already present. 

1. There is already a ui system present with a "drop-down" feature, which is essentially what this is.
2. Mod Organizer already treats separators differently, if only slightly. Unless I am mistaken, It looks for the "_separator" suffix in a folder name and then simply doesnt count that folder as containing any files. That provides an existing codeblock to hook into for aforementioned feature
3. Unless I am woefully misunderstanding something, the code required for that scale of ui change is not that complicated, as many of the component elements are already present in the program.

### **Describe alternatives you've considered**
Well, I have thought about ways to adapt the currently existing category system into something approaching usable, but that would require a similar scope of UI change. The main problem with the category system as it stands is that it is too hard setup a Category List, add/reorder/remove categories, or reliably batch-organize files into or out-of individual, much less multiple categories. Not to mention that mods are given the categories pulled from the nexus by default with no toggle. 

It is not that that system cannot be made to work for what I am trying to do, but rather that it would require so much work to convert an established modpack to that system, or setup a new one, that it is simply not worth the effort. 

I have also tried brute forcing the problem with a VCS and manually combining folders, sacrificing disk space in favor of readability and a reliable 'undo' button. This fails hilariously when you start dealing with 50-100GB of mod files. Even if most of those files are never actually seen by the game, it starts to take literal *hours* to commit changes of any significant size. Or at least it does when you are still using a Hard Drive instead of an ssd.

### **Additional context**

I've been struggling against not having a robust organization system for years. Separators are a helluva lot better than creating empty mod folders with lots of hyphens to catch your attention. I wish they could be color coated or something to better delineate between sections, and I think that there should generally be more customization options regarding text and coloring in general without diving into config/css files, but generally speaking, the issue I have outlined here is the broadest reaching, its solution would have the most benefit as far as I am concerned. 

But none of that is to say that the system is not perfectly usable in its current state, nor to say that these perceived problems are anything but a byproduct of my own neurosies. I am the kind of person that takes notes in 5 different colors of pen, so I may be the only person who thinks there is an issue to begin with.

**Comment by LostDragonist** [comment]
Closing as a duplicate to https://github.com/ModOrganizer2/modorganizer/issues/627.  

This is basically the #1 wanted feature but no one on the team really has time to work on it.  As for...

>I wish they could be color coated or something to better delineate between sections

You can actually change the color of the separators if you right-click on them.  This will even show in the scrollbar to the right so you can more quickly jump between sections.  The color doesn't apply for all the mods in the section... though that could be an interesting addition with some possible issues.

**Comment by Ratione** [comment]
Thanks for the Color sorting thing! I didnt know about that one. Thats awesome, and solves several of my problems by itself. It really makes it easier to see where the boundaries are on the Minimap/Scrollbar.

While I do still look forward to the day I can nest folder structures in Mod Organizer, that makes it way more usable in the meantime.

**Comment by Al12rs** [comment]
Btw the coding requered is not trivial at all, mainly because we would like to maintain the ability for users to drag and drop mods to change priority. You can see how the category grouping thing esplicitly does not allow you to change priority because it startes to get really messy. I actually tried another approach wich is more of a hack but you get issues with the hidden mods no longer being detected as being present even though they actually are and that causes crashes.
Using the groups infrastructure is the right thing to do but the group thing is a custom thing that Tannin created specifically for grouping by a caratteristic of a mod, which is not the case for separators since mods in different profiles can be under different separators. It's really not that simple and it would probably require a little less than a week of full time work and investigation. 
None of the devs has that time at the moment (we don't get anything for working on MO).

**Comment by GF-Huang** [comment]
Are you all talking about something like modpack (which means a package includes many mods)? Does MO2 supports to pack mods into a modpack now? 

For example, I use 100 mods to make Skyrim like an action game, then I pack these mods into a modpack which naming "Action Mods". And I use another 50 mods to make it like an travel game, then pack them into a modpack which naming " Travel Mods". When I want to play action game, I can very simply enable all mods of "Action Mods" then disable all other mods, and when I want to play travel game, I can very simply to do it too. 

Can MO2 do it now?

**Comment by Al12rs** [comment]
Please don't post on closed issues, create a new issue instead or chat with us directly on discord for this sort of questions. 

To address the question, no, Mo2 does not support mod packs. You can have a look at wabbajack for that, but it's for complete modlists.

Separators aren't folders full of mods, all the mods are still top level items, separators just subdivide the list for visual purposes. They don't "contain" mods.
