### ISSUE TITLE
ModOrganizer 2 resetting and locking my .ini file everytime I launch FNV

### ISSUE THREAD

**Issue by gonrhcp** [ModOrganizer2/modorganizer#893]
## The problem:
Whenever I try to launch NVSE through MO2, I get a locked fallout.ini file in my MO2 profile and it resets its contents. I have tried removing the lock in the file explorer but everytime I launch the game it resets.
![Captura](https://user-images.githubusercontent.com/33702133/69077032-044e3480-0a35-11ea-99cc-7e37d049cd1a.PNG)

## To Reproduce:
I just changed an ENB file in the data folder of the game and installed a new mod, then sorted through LOOT and when I launched the game MO2 asked for permission to change .ini file from read-only to something that allows modifications, and then it all started.
I have tried resetting the changes I made (uninstalled the mod, reverted the ENB changes), but now the game is messed up, with a weird load order that has some bugs and the old ENB not working properly.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.2.1
* Desktop OS/version used to run Mod Organizer: Windows 7 Ultimate, SP1

### USVFS:
https://gist.github.com/gonrhcp/207ab5852508e8fce8f88498cef3bd45

### MO Interface:
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/3859990/mo_interface.log)

**Comment by Al12rs** [comment]
Should be better handled with 2.2.2+
