### ISSUE TITLE
Loot And Mod orginizer not playing well together.

### ISSUE THREAD

**Issue by MaxTimber745** [ModOrganizer2/modorganizer#898]
Recently Loot both built in and instaled as a exe. is not able to detect any plugins i have installed. is anyone Else having this issue? 

the error code when running the built in Loot is 1 

and get this When launch Loot as a Exe. though mod orginizer.
[LOOTDebugLog.txt](https://github.com/ModOrganizer2/modorganizer/files/3883143/LOOTDebugLog.txt)
but Loot runs fine when using it normally with actual files. 

anyone got a fix?

**Comment by LostDragonist** [comment]
[21:09:09.548140] [error]: Exception while executing query: file_size: The system cannot find the file specified.
: "D:\Steam\steamapps\common\Skyrim Special Edition\Data\Tainted_Blood_Imperious_Compatibility_Patch.esp.ghost"

I think you have this file in your plugins.txt.  Try ... IDK, disabling and enabling any random plugin to get MO to generate the plugins.txt again?

**Comment by MaxTimber745** [comment]
hey! thanks! it was the ghosted plugin!
