### ISSUE TITLE
DDS Preview and Comparison feature not working

### ISSUE THREAD

**Issue by newclearsky** [ModOrganizer2/modorganizer#899]
The DDS preview and comparison feature was working until I tried previewing a 4k texture. When trying to use the feature the Preview window shows up in the task bar but is unusable and invisible.
![Untitled](https://user-images.githubusercontent.com/58128817/69490073-4cfc5800-0e50-11ea-94a3-913fd747b7ca.jpg)

## Environment:
Mod Organizer v2.2.1
Windows 10

## Logs:
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/3883227/mo_interface.log)

**Comment by Silarn** [comment]
The qt dds image format plugin we've been using doesn't support newer dds formats. The dev builds include a new preview plugin that is able to display nearly all DDS formats by making use of your GPU via OpenGL.

**Comment by newclearsky** [comment]
Not sure why it would suddenly stop working but I was able to restore it using this method:
1. Open Task Manager
2. Click the arrow next to ModOrganizer to view the Preview window.
3. Right click Preview and choose Maximize
