### ISSUE TITLE
"No internet connectivity" exception not handled

### ISSUE THREAD

**Issue by JamesYeoman** [ModOrganizer2/modorganizer#90]
If I am not connected to the internet, I get the following log (snippet)

`19:37:20 [D] network error 3`
`19:37:20 [C] uncaught exception in handler (object , eventtype 43): Network failed: Host api.github.com not found`
`19:37:20 [C] uncaught exception in handler (object , eventtype 43): HTTP Status 0:` 

I think these sorts of exceptions should be handled (atleast for a release) so that the less tech-savvy don't get all confused and file a bug report or something as it would be a waste of bug reporting.

**Comment by Silarn** [comment]
@LePresidente I know you did some changes to help fix this, but is the issue actually resolved?

**Comment by isanae** [comment]
I can't reproduce this. The dialog box for connecting to nexus stays up until it times out, but it's not modal, and there's another dialog to try again. Checking for updates fails first, followed by nexus:

    [D] network error 3
    [D] Unable to connect to github.com to check version
    [D] login failed: There was a timeout during the request
    [D] Nexus API validation failed: There was a timeout during the request

The network error could be better, but there are no unhandled exceptions.
