### ISSUE TITLE
information panel with French translation

### ISSUE THREAD

**Issue by Greglp3** [ModOrganizer2/modorganizer#912]
## The problem:

I use Mo2 for skryrim se. The program is set in French. When i want to see the information panel of a mod, Mo2 is not responding.

No problem in English

## To Reproduce:

Set Mo2 in french and right-click on a mod -> information.

**Comment by LostDragonist** [comment]
I'm not seeing any problems here with version 2.2.1.  Maybe try resetting the GUI by going to Settings > Workarounds > Reset Window Geometries.

If that doesn't help, you'll need to provide some more information like log files and example mods that cause the issue.  You can use the "Open Folders" button to open the logs folder and retrieve your mo_interface.log.  Please upload the file *after* closing MO2.

https://cdn.discordapp.com/attachments/458597400638914563/617049541350260794/openlogs.png

**Comment by isanae** [comment]
I'm guessing you have something like Nahimic or RivaTuner installed, the logs would tell us what exactly. Some OSDs are incompatible with MO, you have to uninstall them.

**Comment by Greglp3** [comment]
fixed with reset windows geometries. Thanks a lot !
