### ISSUE TITLE
Add open stylesheets folder button

### ISSUE THREAD

**Issue by 6788-00** [ModOrganizer2/modorganizer#914]
**Is your feature request related to a problem? Please describe.**
There is no way to open the stylesheets folder within MO2 to facilitate quicker and easier installation of themes/stylesheets.

**Describe the solution you'd like**
An Open Stylesheets Folder button on the Settings dialog near the Style dropdown and/or on the Open Folders menu.

**Comment by Al12rs** [comment]
Would a link like this under the style setting work? https://cdn.discordapp.com/attachments/412414009694748693/649327990475325441/translate.png

**Comment by 6788-00** [comment]
I suppose it would, but it feels to me like it would be somewhat non-standard since I usually associate hyperlinks with web pages. I'm partial to a button under the Style dropdown menu, but an entry at the top or bottom of the dropdown could be a possibility as well.

**Comment by Al12rs** [comment]
Yeah, I also feel the link should be reserved for web stuff, it was mainly a compromise to try to save space. Either way is fine for me
