### ISSUE TITLE
Add dialog box telling users they can't rename-delete the current profile instead of failing silently.

### ISSUE THREAD

**Issue by GrayedFox** [ModOrganizer2/modorganizer#926]
## The problem:
The current edition of Mod Organiser 2 does not allow people to change profile names. This can be worked around by copying your current profile and naming it how you like, transferring all saves, and then deleting the original profile (a process that I am sure will make most MO2 users uncomfortable!).

Keep up the great work :)

## To Reproduce:

1. Open MO2
2. Go to Manage Profiles
3. Rename the currently active profile
4. Close the Profile Manager dialogue/window
5. Observe

Or refer to this GIF:

![cannot_rename_profiles_mo2](https://user-images.githubusercontent.com/6493307/70367565-77fb9880-18a1-11ea-87b1-a53456752745.gif)

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Mod Organizer: Windows 10

## Mod Organizer Logs:

[usvfs-2019-12-07_02-13-46.log](https://github.com/ModOrganizer2/modorganizer/files/3934623/usvfs-2019-12-07_02-13-46.log)

### MO Interface:

https://gist.github.com/GrayedFox/d4a8d89dd4b1289309b1c5e0f8587e53

**Comment by LostDragonist** [comment]
This should only apply to the currently active profile.  If you switch to another profile first, you should be able to rename the other profile.   

We ran into the same thing with deleting the active profile which now has a "you can't do that" pop up.  I guess we need to add the same thing for renaming profiles.  (Or fix it but meh.)

**Comment by GrayedFox** [comment]
Certainly makes sense to flash a warning and tell the user they cannot delete the currently active profile (good and standard practise for most destructive ops). Renaming, however, I would argue here that wouldn't make sense - it's just a bit of a PITA for the user to work around it.

Hmm, had a quick read of the code base - seems like [this method](https://github.com/ModOrganizer2/modorganizer/blob/Develop/src/profile.cpp#L907) is the culprit. From what I can see, profiles don't actually have names _per se_ - the profile is loaded based on the absolute path of the file, and the user just sees the file name as the profile name.

What's stopping us from renaming the active profile? Been a long time since I touched anything C based, excuse my ignorance! Is the file being in use/memory the limiter here?

Without refactoring the whole profile name system (decoupling file paths from names, for example), might I humbly suggest some naive workarounds:

1. create a new profile with the new name and delete the old one? (bloaty, feels bad man)
2. switch to the default profile before renaming the active one, switch back after? (assumes there is always a default profile, but perhaps less bloaty, still - my profile takes quite a while to load on an up to speed gaming PC)
3. create a hidden, "active" shell profile that in inherits it's name and all properties from the profile that is loaded at startup/when a user loads a profile. This active profile could then act as a proxy to whatever profile was last loaded/chosen - thus renaming a profile would rename the last chosen/loaded profile, and we then refresh the proxy profile (which fetches changes). Would require more work, perhaps less work than decoupling profile names from file paths - would essentially just mean adding a layer of complexity to how mods/changes/settings are saved to disk and read but would prevent problems like this coming up in the future.

Sorry for the lengthy post, thanks for the product and keep up the great work :)

**Comment by Al12rs** [comment]
To be honest I don't think we have the time to to invest into elaborately fixing this. The warning is probably the only thing that will get implemented. 

We actually have pretty limited manpower, understandably since Mo2 development is not paying anything, so we need to make some selection in where we want to spend the limited time we have. This does not add new functionality and does not significantly improve usability. Renaming a profile is a fairly rare operation and the only profile that has a problem is the current one, which can be worked around by switching to a new one in a few seconds.

I agree that adding the warning is needed to inform the user on the limitation.

Regarding the question, the profile name is the name of the folder that contains all the files of the profile, such as modlist, loadorder, ini files etc. A lot of these are open and used by Mo2 so renaming the folder does not work unless the active profile is switched.

**Comment by GrayedFox** [comment]
> ... renaming a profile is a fairly rare operation and the only profile that has a problem is the current one

Yes that is an excellent point - sorry it's my QA perfectionism getting the better of me. The little warning dialogue is a nice workaround and can piggy back of existing functionality - thanks for clarifying those points :)
