### ISSUE TITLE
"May be Pyton & UTF-8 trable" 'charmap' codec can't decode byte 0x98 in position 1832: character maps to <undefined>

### ISSUE THREAD

**Issue by Volgerd** [ModOrganizer2/modorganizer#938]
## The problem:
It hangs when you try to open an additional window in the notifications (red exclamation mark) and when you click on the "settings" icon. Reinstall and
 resetting the result failed.
![Trabl  -MO2 Notification](https://user-images.githubusercontent.com/58877805/70847777-28086d00-1e71-11ea-9c93-8920e1525739.png)

## Environment:
 Win10 LTSC system, MO-2 v2.2.1

## Link to Mod Organizer logs:
[usvfs-2019-12-14_10-31-39.log](https://github.com/ModOrganizer2/modorganizer/files/3963729/usvfs-2019-12-14_10-31-39.log)
[usvfs-2019-12-14_10-38-19.log](https://github.com/ModOrganizer2/modorganizer/files/3963730/usvfs-2019-12-14_10-38-19.log)
[usvfs-2019-12-14_10-39-27.log](https://github.com/ModOrganizer2/modorganizer/files/3963731/usvfs-2019-12-14_10-39-27.log)
[usvfs-2019-12-14_10-39-38.log](https://github.com/ModOrganizer2/modorganizer/files/3963732/usvfs-2019-12-14_10-39-38.log)
[usvfs-2019-12-14_10-40-23.log](https://github.com/ModOrganizer2/modorganizer/files/3963733/usvfs-2019-12-14_10-40-23.log)
[usvfs-2019-12-14_10-41-05.log](https://github.com/ModOrganizer2/modorganizer/files/3963734/usvfs-2019-12-14_10-41-05.log)

### MO Interface:
![mo_interface logs](https://user-images.githubusercontent.com/58877805/70847956-87677c80-1e73-11ea-9598-1787d2e7dac2.png)
!

**Comment by AnyOldName3** [comment]
There should be a MO Interface log as a text file, and that'll be much easier for us to work with than that series of screenshots.

**Comment by Volgerd** [comment]
I do not know where it lies

**Comment by Silarn** [comment]
I can't replicate this on 2.2.2rc4, so this bug may be fixed. Please see if you can download from Discord and try.

**Comment by AnyOldName3** [comment]
I'm 95% sure this user is using a system language that doesn't use the cp1252 text encoding. Python picks the encoding to open files with based on the system default, and it looks like I haven't manually specified an override [here](https://github.com/ModOrganizer2/modorganizer-script_extender_plugin_checker/blob/Develop/src/ScriptExtenderPluginChecker.py#L231) or [here](https://github.com/ModOrganizer2/modorganizer-script_extender_plugin_checker/blob/Develop/src/ScriptExtenderPluginChecker.py#L245). The SKSE log will always be a fixed encoding (either UTF-8 or cp1252 - I'll check), so it might break if loaded as something else.

**Comment by AnyOldName3** [comment]
@Volgerd Ideally, we need two things from you.

* The most important one right now is your Fallout 4 script extender log. In your Documents directory, you should have a folder called `My Games` (although it might be localised to your system language). Inside that, there'll be a `Fallout 4` directory, and in that, there'll be an `F4SE` directory. The log will be in there.
* The other thing is the MO2 interface log. It should be in the same place as you found the USVFS logs you'be already uploaded. You can get here quickly by opening MO2, clicking on the folder button at the top of the mods list, and choosing the option to open the logs folder.
