### ISSUE TITLE
[Feature request] Enable/disable selected mod(s) via right click menu.

### ISSUE THREAD

**Issue by Matakor** [ModOrganizer2/modorganizer#94]
Basically title. I would like to be able to easily disable multiple mods at the same time without disabling all mods, mostly so that I can ensure that texture only mods load esps, ba2s, etc after other mods without a ton of extra work looking around to figure out which esp goes to what.

Thanks for looking into it!

**Comment by Al12rs** [comment]
You can do that with the (quite hidden) functionality of pressing space-bar. It will toggle all the selected modi's status. For enable selected and disable selected menu entries we would need to add some code and then we would have an even longer menu. I will look into the menu options to see if we can order and hide some of them depending on the situation to get a cleaner menu.

**Comment by Al12rs** [comment]
Done by LostDragonist
