### ISSUE TITLE
All mods gone?

### ISSUE THREAD

**Issue by Marvin7321** [ModOrganizer2/modorganizer#946]
Mod manager base directionary was on a wrong ard drive so i moved it and set all paths to new location started it no mods no profile nothing i can even readd them because all folders are empty i dont know what to do it took me an entire day to download and install all my mods again

**Comment by Al12rs** [comment]
Like you moved the files and after starting Mo2 they disappeared? Are you absolutely sure that something didn't go wrong with the copy or that you somehow set the paths wrong or copied somewhere else? 
I have moved the paths and folders multiple times and only thing that can happen is that you can lose the profile loadorder if you only move partially or stuff like that. Deleting the mods is not something Mo2 should be capable of doing.

**Comment by Marvin7321** [comment]
not really i ust closed it moved te base directionary and set the path now all my folders are empty

**Comment by Marvin7321** [comment]
i have no profile no mods no downloads but the hard drive space wich is 20+ GB is used but i dont know where they should be

**Comment by Marvin7321** [comment]
yeah the folder is 21+ GB but nothinbg is in there i dont have any clue on what to do now

**Comment by Al12rs** [comment]
I don't really know what is going on there. You need to figure out where your files are. Check the Recycle bin maybe. I don't know how to help you otherwise. I don't think Mo2 could have done this.

**Comment by Marvin7321** [comment]
got it Mo2 created 3 hidden subsections dont ask me wy i will never touch it again and leave the settings be but hey at least i got my mods back
