### ISSUE TITLE
Small Screen Bug

### ISSUE THREAD

**Issue by JPStephens8** [ModOrganizer2/modorganizer#949]
problem:
Launching Fallout 4 from the Mod Organizer application regardless if mods are installed causes the game to launch in a smaller screen. Issue could not be reprimanded after altering fallout4prefs.ini files to have resolution set to the correct dimensions. Mod Organizer is currently at its most up-to-date version from Nexus. If this issue could be resolved soon it would be much appreciated.

Link to Mod Organizer logs:
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/4006538/mo_interface.log)
[usvfs-2019-12-26_06-28-00.log](https://github.com/ModOrganizer2/modorganizer/files/4006539/usvfs-2019-12-26_06-28-00.log)
[usvfs-2019-12-26_06-42-37.log](https://github.com/ModOrganizer2/modorganizer/files/4006540/usvfs-2019-12-26_06-42-37.log)
[usvfs-2019-12-26_06-46-23.log](https://github.com/ModOrganizer2/modorganizer/files/4006541/usvfs-2019-12-26_06-46-23.log)
[usvfs-2019-12-26_06-58-38.log](https://github.com/ModOrganizer2/modorganizer/files/4006542/usvfs-2019-12-26_06-58-38.log)
[usvfs-2019-12-26_07-10-08.log](https://github.com/ModOrganizer2/modorganizer/files/4006543/usvfs-2019-12-26_07-10-08.log)
[usvfs-2019-12-28_00-28-38.log](https://github.com/ModOrganizer2/modorganizer/files/4006545/usvfs-2019-12-28_00-28-38.log)

**Comment by LostDragonist** [comment]
MO keeps its own set of INI files by default.  You need to use the MO INI editor in the tools menu (puzzle pieces) to make sure you're editing the right files.

You can also run the Fallout 4 launcher through MO in order to set up your options.

**Comment by JPStephens8** [comment]
Thankyou, I was unaware that MO itself had an INI editor, I was able to make the corrections I needed
