### ISSUE TITLE
Starting "First Steps" Tutorial again results in a instant shutdown of MO2

### ISSUE THREAD

**Issue by ThePhiRatio** [ModOrganizer2/modorganizer#951]

**Comment by Al12rs** [comment]
That usually means that you have a program interfearing with MO2 like an overlay or some bugged audio drivers.
Try disabling any background software you are using. If it's still happening then upload here your interface log:

Drag and drop your mo_interface.log here. It's in the logs folder of your instance. You can use the "Open Folders" button to open the logs folder.

https://cdn.discordapp.com/attachments/458597400638914563/617049541350260794/openlogs.png

I can't reproduce this issue on the latest builds in any case,
