### ISSUE TITLE
MO2 Not Correctly Installing .esp Files

### ISSUE THREAD

**Issue by ThePhiRatio** [ModOrganizer2/modorganizer#955]
## The problem:
When I download **Any** mod that has .esp files, it does not install correctly. I have tried it with more than 3 different mods. I have found no solution to this problem on the internet. If it helps, I have MO2's folders on a different drive than Skyrim special edition. I don't know how that would make much of a difference. 

It says on the plugins tab that X.esp is there, but when I use LOOT or go directly to the game folder, none of them are there. I cannot find a solution.

## To Reproduce:

1. Download any mod that has an .esp
2. Install normally
3. Then you can't find the esp in game folder.

## Environment:

* Mod Organizer Version that exhibits the issue: v2.2.1
* Desktop OS/version used to run Mod Organizer: Windows 10

### USVFS:
https://gist.github.com/ThePhiRatio/29508646ccbd91f6917f25e7d1b8773e

### MO Interface:
https://gist.github.com/ThePhiRatio/90f98a5ec5709bce755379df55892f19

## Comments:
Thank you so much for your help! I love MO2 but this issue makes it quite difficult to use effectively. 
I appreciate you taking the time to listen to your users. 

-The Phi Ratio

**Comment by isanae** [comment]
Mod Organizer does not put files into the game's folder. It keeps them in separate folders in `C:\Users\username\AppData\Local\ModOrganizer\instance\mods`. If you want to run a program so it can see your mods, you have to run it through MO by adding it as an executable (if it's not already there), selecting it in the list and pressing the big orange "Run" button.

**Comment by jarrard** [comment]
If you want to explore your plugins in a virtual folder to see that all is placed correctly, you can select that option from the drop down list left of run.
