### ISSUE TITLE
FNIS gone from the tools menu after a python error

### ISSUE THREAD

**Issue by Alfatossa** [ModOrganizer2/modorganizer#963]
## The problem:
So I had an error with python_plugin.dll and now FNIS is no longer in the tools tab. I need to run FNIS now that i added like 300+ animations so how can I add it again? All I see in the plugin setting about FNIS, is FNIS Checker and yes I have FNIS installed and EVERYTHING 

## Environment:
Mod Organizer V. 2.2.2
Windows 10 Pro 64-bit

**Comment by LostDragonist** [comment]
Upload your log files here. Follow these steps:

1) Go in the Settings, Diagnostics tab, set Log Level to Debug.
2) Restart MO.
3) Recreate your problem.
4) Use the "Open Folders" button to open the logs folder.
5) Close MO.
6) Drop mo_interface.log and the most recent usvfs log here. You might need to compress them.

https://cdn.discordapp.com/attachments/458597400638914563/617049541350260794/openlogs.png

**Comment by Silarn** [comment]
While diagnosing the cause of the crash would be ideal, you will probably need to go to Settings -> Plugins. Either the python plugin was disabled or it might be in the bottom 'blacklisted' box. Either reenable it in the plugin settings or selecting and press delete to remove it from the blacklist and restart MO2.

You may see a dialog telling you there was a problem and asking if you want to disable the python plugin. Tell it to let it load. There may even be two dialog boxes.

If it crashes again, then we will need to diagnose why and logs will help with that.

**Comment by Alfatossa** [comment]
THanks @Silarn that fixed it

**Comment by Alfatossa** [comment]
Thanks @Silarn that fixed it

**Comment by AnyOldName3** [comment]
What was the error with `plugin_python.dll`? If that's breaking badly enough for MO2 to suggest blacklisting it, we've got something to fix. I thought I'd got rid of all the situations where a Python plugin error could turn into a major C++ issue.

**Comment by Silarn** [comment]
That's just what happens if a plugin crashes, I think. I had it happen once when I upgraded my Linux install, but after turning it back on it didn't crash again. Not sure what happened in this case.

**Comment by AnyOldName3** [comment]
The point I'm making is that the stuff I've done should have made it so that a crashing Python plugin would only make the proxy throw an exception, which doesn't trigger blacklisting, and the proxy isn't supposed to crash.

**Comment by Silarn** [comment]
By plugin I was speaking generically about MO2 plugins. In my case something caused the proxy to crash at launch, but as I said it only happened once right after upgrading that Linux instance and didn't happen again.
