### ISSUE TITLE
Enderal support bugged

### ISSUE THREAD

**Issue by Sarund9** [ModOrganizer2/modorganizer#966]
When I launch the game from steam, it works fine.
When I launch from MO2 however, stuff hapens:

When i open my savefiles, I can see my skyrim savefiles. New game causes a CTD.

I have the Steam version of Enderal.
I am loading no mods at all in MO2.
I have Reinstalled Enderal and still the same.
I have Uninstalled skyrim.
I have deleted skyrim Instance from MO2.

This is a copy from my reddit post:
https://www.reddit.com/r/enderal/comments/emk5bf/weird_issue_when_launching_from_mo2/

Most likely a bug with the latest version of MO2

**Comment by LostDragonist** [comment]
I know the savegame issue is an MO2 bug.  That's going to be fixed today/tomorrow with a quick release.  You can fix it now with this file: [game_enderal.dll](https://cdn.discordapp.com/attachments/403979692501106688/665000436964786176/game_enderal.dll).  Download that and put it in MO2\Plugins.  Then you'll want to right-click it, go to properties, click/check Unblock at the bottom of the general tab and hit OK.  

After that, you'll probably want to create a new profile in MO with default game settings.  

![](https://cdn.discordapp.com/attachments/403979692501106688/524939782435110924/unknown.png)
![](https://cdn.discordapp.com/attachments/403979692501106688/524940397643038740/unknown.png)

That'll fix the save issue.  It *might* fix the other problems but I kind of doubt it  If you're still having problems, you'll need to post your logs...

1) Go in the Settings, Diagnostics tab, set Log Level to Debug.
2) Restart MO.
3) Recreate your problem.
4) Use the "Open Folders" button to open the logs folder.
5) Close MO.
6) Drop mo_interface.log and the most recent usvfs log here. You might need to compress them.

![](https://cdn.discordapp.com/attachments/458597400638914563/617049541350260794/openlogs.png)
