### ISSUE TITLE
error usvfs_x64.dll with mod organiser 2 version 2.2.2

### ISSUE THREAD

**Issue by samael85000** [ModOrganizer2/modorganizer#968]
hello,

I use mo2 to play skyrim se, with netscriptframework, I have this error 0x7FFCD7AAF160 (usvfs_x64.dll + 7F160) (char *) "@SVWATAUAVAWH ???".
It does not prevent the game from launching but I would like to know where this problem comes from with usvfs_x64.dll.
thank you.

**Comment by Al12rs** [comment]
If you can still reproduce this error please drop by our discord server so we can have a look at those logs
