### ISSUE TITLE
Run only with filtered entries

### ISSUE THREAD

**Issue by TomConnery** [ModOrganizer2/modorganizer#975]
**Is your feature request related to a problem? Please describe.**
Not related.

**Describe the solution you'd like**
If I apply a filter on my plugin list and, say, tick a box in the filter section, I can run SKSE or whatever with only the filtered plugins.

**Describe alternatives you've considered**
Roughly:

-> Apply filter
-> Select mods
-> Activate mods
-> [insert activity here]
-> Deactivate mods
-> De-select mods
-> Goto 0

**Additional context**
I'm by no means a pro at using MO yet, but I can't find a way to only have my currently active and filtered plugins on my play-profile be selected for running. I always need to switch over to my modding profile, where nothing is selected, set the filter I want to apply and then compare which mods are inactive on my other profile.

**Comment by Al12rs** [comment]
You can right click-> disable all, then right click again and select Enable Visible. There is no way to go back though. So to this I would just clone the profile first, do this trick and then delete the profile once I'm done.

**Comment by Al12rs** [comment]
I'm not really sure what you need to do with only some of the mods enabled though, if you could tell us that maybe it's easier to think of improvements

**Comment by TomConnery** [comment]
You're right, I should have been more precise with what I'm trying to achieve.

At the moment, I am seeking to flag as many ESPs as ESL as possible. Texture mods are a good point to start with, I think, and I wondered how I can take the selection of tex mods and load only those into xEdit.
This can be applied to other scenarios, of course.

Loading animation-mods only would be great for using FNIS, I assume, but I haven't spent too much thought on that yet.

**Comment by Al12rs** [comment]
Then would the procedure I explained above work for you? It should work for both modlist and pluginlist as both have the option to enable/disable all and enable/disable visible mods (the modlist options are under "All Mods" section).

**Comment by Al12rs** [comment]
Can I close this then?
