### ISSUE TITLE
Dragging files from overwrite does not preserve file path

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#981]
Honestly, I could be wrong that this is how it used to work but right now it seems useless.

## To Reproduce:

1. Save a character preset file with RaceMenu.
2.  Observe the file is created in overwrite with the path \SKSE\Plugins\CharGen\Presets\\<FILE\>.
3.  Create an empty mod.
4.  Drag \<FILE\> from overwrite to the new mod.
5.  Open the mod and observe \<FILE\> is in the top-level folder.

Expected result:  <FILE> should be placed in \SKSE\Plugins\CharGen\Presets\\<File\> instead.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.2.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): <2.2.0
* Desktop OS/version used to run Mod Organizer:  Windows 10, version 1909

**Comment by AnyOldName3** [comment]
It definitely used to preserve relative paths.
