### ISSUE TITLE
Be able to specify required Mods

### ISSUE THREAD

**Issue by Ranger1230** [ModOrganizer2/modorganizer#982]
**Is your feature request related to a problem? Please describe.**
At the moment if we are building a new profile and selecting what mods we want, we have to either remember the other mods are required or look up the required mods and enable them

**Describe the solution you'd like**
Allow for a way for us to state (probably manually) what mods are required for a specific mod so when we enable it we are given the option to enable the mods we marked as being required.

While I know this sort of method has the draw back of if you need a patch to get two mods to work together there isn't a good way to mark that you need it (other then a loot message), but this would help with the bigger requirements.

**Comment by selsie** [comment]
I second this, like reading a modgroup.

**Comment by Al12rs** [comment]
Feature implementation and progress will be tracked in #838
