### ISSUE TITLE
Mod Organizer 2.2.2.1 Failed. You lack the permission do this action.

### ISSUE THREAD

**Issue by ssc4690** [ModOrganizer2/modorganizer#985]
## The problem:
Basically I been having problems with mod organizer since 2.2.1 . But resonantly I when downloading it again I didn't get a prompt to access anything from my mods I re-downloaded it again. I think I screwed it up because its not even finding it as an app on my computer and its windows 10 program. Ether Its my computer or some where in coding I did something wrong of downloading. I also am to afraid I well lose everything if i delete all older mod organizers... I am wondering what to do because I can not even get in to mod organizer it self even going in to its file and do (exe.) so can someone help me navigate to windows app permission or any ideas on how fix my mess up?

**Comment by isanae** [comment]
Come by [discord](https://discord.gg/c2pHyU6) to get some help with this.
