### ISSUE TITLE
Crash when mods are removed from the filtered list

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#995]
## The problem:
When a filter is active in the mod list, making changes to mods that would remove mods from the filter is liable to make MO crash.

## To Reproduce:

1. Create a bunch of empty mods.
2. Filter by "Not <Has valid game data>".
3. Select all the mods.
4.  Right-click and select "ignore missing data".
5. Wait for the crash.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.2.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): ???
* Desktop OS/version used to run Mod Organizer: Windows 10, version 1909 (18363.592)

## Logs: 
[log + crashdump.zip](https://github.com/ModOrganizer2/modorganizer/files/4186195/log.%2B.crashdump.zip)

Note: Log mentions RTSS.  Disabling RTSS does not solve the issue.

**Comment by LostDragonist** [comment]
This is crashing in ignoreMissingData_clicked when it emits the modListDataChanged signal.  I'm not sure if that function is doing something wrong or if the display/filter code is doing something wrong.

If it's on the function side, whatever the fix is should be applied to all context menu actions that can happen for multiple selections.

**Comment by Al12rs** [comment]
I know that other modlist actions manually call m_modlistSortProxy->invalidate() to avoid this problem, don't know if that is the correct solution

**Comment by isanae** [comment]
See #723 and [this PR](https://github.com/ModOrganizer2/modorganizer/pull/909/files), may be related.
